### ISSUE TITLE
transformation not work

### ISSUE THREAD

**Issue by libinglong** [raphw/byte-buddy#1002]
Hi！
I write a bootstrap agent.
I want to enhance java.util.concurrent.ThreadPoolExecutor#submit

When I disable disableClassFormatChanges(), it works.
When enable, It can not work.

env
buddy 1.10.19
java 8

I have debuged,
It's different at MethodRegistry.java line 481
> relevanceMatcher.matches(methodDescription)

What does disableClassFormatChanges do?

My code is at [github my-agent](https://github.com/libinglong/byte-buddy-agent)

run mvn clean package -DskipTests to get an agent.

The test class is AgentTest.java

Thank you for your help!

**Comment by raphw** [comment]
Most JVMs do not allow changes in the class file format for classes that have been loaded previously. If this is not allowed, you can tell Byte Buddy to not even attempt it, you will get cleaner error messages and some functionality is simply no longer supported. Using this option, Byte Buddy therefore also disables this functionality. Typically, you use this option in conjunction to only applying `Advice`.

**Comment by libinglong** [comment]
> Most JVMs do not allow changes in the class file format for classes that have been loaded previously. If this is not allowed, you can tell Byte Buddy to not even attempt it, you will get cleaner error messages and some functionality is simply no longer supported. Using this option, Byte Buddy therefore also disables this functionality. Typically, you use this option in conjunction to only applying `Advice`.

The log says the class has not been loaded.
> On Transformation class java.util.concurrent.ThreadPoolExecutor loaded:false

```java
@Override
public void onTransformation(final TypeDescription typeDescription,
                             final ClassLoader classLoader,
                             final JavaModule module,
                             final boolean loaded,
                             final DynamicType dynamicType) {
    System.out.println("On Transformation class " + typeDescription.getName() + " loaded:" + loaded);
}
@Override
public void onError(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded, Throwable throwable) {
    throwable.printStackTrace();
    System.out.println("error " + typeName);
}
```

And there is no error message here. @raphw

**Comment by libinglong** [comment]
Now I find the point why the method can not match.

It's the TypeStrategy.Default.REDEFINE_FROZEN config in disableClassFormatChanges()
```java
REDEFINE_FROZEN {
          /** {@inheritDoc} */
          public DynamicType.Builder<?> builder(TypeDescription typeDescription,
                                                ByteBuddy byteBuddy,
                                                ClassFileLocator classFileLocator,
                                                MethodNameTransformer methodNameTransformer,
                                                ClassLoader classLoader,
                                                JavaModule module,
                                                ProtectionDomain protectionDomain) {
              return byteBuddy.with(InstrumentedType.Factory.Default.FROZEN)
                      .with(VisibilityBridgeStrategy.Default.NEVER)
                      .redefine(typeDescription, classFileLocator)
                      .ignoreAlso(LatentMatcher.ForSelfDeclaredMethod.NOT_DECLARED);
          }
      }
```
the code demand method should be declared in the instrumentType.
But submit method is not declared in the ThreadPoolExecutor.
> .ignoreAlso(LatentMatcher.ForSelfDeclaredMethod.NOT_DECLARED);
