### ISSUE TITLE
MethodDescription#isBootstrap(List) is too restrictive

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#1003]
I'm not entirely sure of all the logic going on here:

https://github.com/raphw/byte-buddy/blob/bf3ad4e3c8c416e3cd19d0b95f9ad3dabeea014f/byte-buddy-dep/src/main/java/net/bytebuddy/description/method/MethodDescription.java#L626-L649

…but it looks to me like a candidate bootstrap method is being checked incorrectly at various points to see if it has a trailing parameter of type `Object...`.  **This is too restrictive**, as the trailing varargs parameter of a bootstrap method may be of _any_ (constant) type (such as, for example `String...` or `Class<?>...`).

For reference, look for the "Sample Bootstrap Methods" table found [in the package javadoc](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/lang/invoke/package-summary.html).  Note that row #8 features `String...` as the trailing varargs parameter type.

I think this (incorrect) logic may also appear here:

https://github.com/raphw/byte-buddy/blob/bf3ad4e3c8c416e3cd19d0b95f9ad3dabeea014f/byte-buddy-dep/src/main/java/net/bytebuddy/description/method/MethodDescription.java#L598-L617

I don't know what the proper validation should be, given that just about anything can be a constant type (at least for JVMs with condy).

The workaround for me (and others) is to ensure that your bootstrap methods that ByteBuddy-generated code invokes have `Object...` as a trailing parameter if you need to accept variable arguments.  Then your bootstrap method must convert `Object[]` to whatever you need.

Thanks as always for a great project.  I hope this bug report helps improve ByteBuddy!

**Comment by raphw** [comment]
You are right, this restriction comes from older days where condy wasn't a thing yet, and it was likely wrong back then. I will need to clean that code up, any method can be a bootstrap method nowadays really, so it cannot be enforced without knowing the arguments.

**Comment by raphw** [comment]
Should be fixed on master now.
