### ISSUE TITLE
Advice added using AgentBuilder is not getting invoked

### ISSUE THREAD

**Issue by shivchelwa** [raphw/byte-buddy#1005]
Hi,

I am new to ByteBuddy and trying to add a advice in my application so that the onEnter and onExit gets called when a method CassandraFunctions.loadObjectByKey is invoked during execution flow. I used below code to register a advice.

`	private void instrument() {

		Instrumentation instrument = null;
                // Get loader initialized in premain class
		try {
			Class<?> c = Class.forName("com.me.runtime.loader.InstrumentLoader");
			java.lang.reflect.Method m = c.getMethod("getInstrument");
			instrument = (Instrumentation) m.invoke(null);
		} catch (ClassNotFoundException | NoSuchMethodException | SecurityException | IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
			e.printStackTrace();
		}

		if(instrument == null) {
			return;
		}
        
                 // Add a advice to trace
		String clzName = CassandraFunctionsAdvice.class.getName();
		new AgentBuilder.Default()
        	.type(ElementMatchers.named("com.me.functions.CassandraFunctions"))
        	.transform( 
        			new AgentBuilder.Transformer.ForAdvice()
        				.include(Thread.currentThread().getContextClassLoader())
        				.advice(ElementMatchers.named("loadObjectByKey"), clzName))
        	.installOn(instrument);
	}`

And the advice class looks like below:

`
public class CassandraFunctionsAdvice {

    @Advice.OnMethodEnter
    public static void onEnter(
            @Advice.Argument(0) String key) {

        String debugText = "OnMethodEnter|loadObjectByKey|key=" + key;
        System.out.println(debugText);
    }

    @Advice.OnMethodExit
    public static void onExit(
            @Advice.Thrown Throwable throwable) {
        String debugText = "OnMethodExit|loadObjectByKey";
        System.out.println(debugText);
    }
}
`

Can you please help identify what is missing.

Thanks

**Comment by raphw** [comment]
It seems as if you are not setting up the agent from a premain method. Is the class already loaded when you are installing the agent? If so, you would need to specify:

```java
.disableClassFormatChanges().with(RetransformationStrategy.RETRANSFORM)
```

You can use *byte-buddy-agent* to attach to a JVM more reliably then with your reflection-hacl.

**Comment by shivchelwa** [comment]
Hi @raphw, Thanks for the suggestion. I made couple of changes as per your suggestion. Enabled Can-Retransform-Classes on javaagent. I could not find RetransformationStrategy.RETRANSFORM with 1.10.19, hence modified AgentBuilder like below
   		
```
    new AgentBuilder.Default()
		.disableClassFormatChanges()
		.with(AgentBuilder.Listener.StreamWriting.toSystemError())
		.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
		.type(ElementMatchers.named("com.me.functions.CassandraFunctions"))
		.transform( 
    			new AgentBuilder.Transformer.ForAdvice()
    				.include(Thread.currentThread().getContextClassLoader())
    				.advice(ElementMatchers.named("loadObjectByKey"), clzName))
    		.installOn(instrument);
```

Also, I added some meaningful code in CassandraFunctionsAdvice as below:

```
public class CassandraFunctionsAdvice {
	
	private static Tracer tracer = GlobalOpenTelemetry.getTracer("my.functions");

	@Advice.OnMethodEnter
	public static void onEnter(
			@Advice.Argument(0) String key, 
			@Advice.Argument(1) boolean loadContained,
			@Advice.Argument(2) String keySpace,
			@Advice.Local("otelContext") Context context,
			@Advice.Local("otelScope") Scope scope) {

		String funcSpan = "loadObjectByKey(key:" + key + ", loadContained:" + loadContained + ", keySpace:"
				+ keySpace;
		System.out.println(funcSpan);
		Span span = tracer.spanBuilder(funcSpan).setParent(Context.current()).startSpan();
		context = Context.current().with(span);
		scope = context.makeCurrent();
	}

	@Advice.OnMethodExit(onThrowable = Throwable.class, suppress = Throwable.class)
	public static void stopSpan(
			@Advice.Thrown Throwable throwable, 
			@Advice.Local("otelContext") Context context,
			@Advice.Local("otelScope") Scope scope) {
        scope.close();
        if (throwable != null) {
            Span span = Span.fromContext(context);
            span.setStatus(StatusCode.ERROR);
            Throwable t = throwable instanceof ExecutionException ? throwable.getCause() : throwable;
            span.recordException(t);
            span.end();
        }
	}
}
```

But, now I get a runtime exception:
```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalAccessError: class com.me.functions.CassandraFunctions tried to access private field com.my.telemetry.CassandraFunctionsAdvice.tracer (com.me.functions.CassandraFunctions and com.my.telemetry.CassandraFunctionsAdvice are in unnamed module of loader 'app')
```

I see that the issue because of _private static member_ variable. When if I change it to _public static member_ variable I don't get any error, but I dont see the advice onEnter and onExit getting executed. For one, `System.out.println` in `CassandraFunctionsAdvice.onEnter` is not printed on console and two, I ran application in debug mode in my eclipse workspace and put a breakpoint in onEnter, but the execution did not suspend in the advice class. 

Can you please suggest what needs to change to get the System.out printed from advice class.

**Comment by raphw** [comment]
The advice code is just a template. The private field is not visible to the code once it is inlined by Byte Buddy.

The question you need to ask yourself is: Could I copy-paste this code to the target class and would it still compile? If no, then you need to change your advice. If you want to manage shared state, you would need to move it to a class that is accessible to the class loader(s) in question and inject it into an appropriate location.
