### ISSUE TITLE
A new MethodDescription.Latent with a constructor Token results in an invalid method name

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#1007]
This is an odd one and again I'll refine this bug report as I learn more.

I have a `MethodDescription.Token` that represents a constructor.  Here is a message from some debug output where I just print the `Token`:
```
*** building constructor; token is: MethodDescription.Token{name='<init>', modifiers=2, typeVariableTokens=[], returnType=void, parameterTokens=[ParameterDescription.Token{type=class java.lang.Integer, annotations=[], name='null', modifiers=null}], exceptionTypes=[], annotations=[], defaultValue=null, receiverType=null}
```
You can see that its name is `<init>` and it takes one `Integer` parameter.  Simple.

Then I build a `MethodDescription.Latent` out of it:
```
final MethodDescription constructor = new MethodDescriptionLatent(theType, theToken);
```
In this case `theType` happens to be a nested class (`com.foobar.Test$FooBar`).  I don't know whether that matters or not.

When I print this `constructor` object it has a strange name (it is not `<init>` and it has no return type):
```
private com.foobar.Test$FooBar(java.lang.Integer)
```
I run some assertions:
```
assert constructor.isConstructor();
assert !constructor.isStatic();
assert constructor.getReturnType().equals(TypeDescription.VOID);
assert constructor.getInternalName().equals(MethodDescription.CONSTRUCTOR_INTERNAL_NAME);
assert constructor.getName().equals(MethodDescription.CONSTRUCTOR_INTERNAL_NAME);
```
The last assertion fails.  I don't know if that's helpful or not.

The error I get at runtime when I load the class that I've generated containing this method is:
```
java.lang.ClassFormatError: Illegal method name "com.foobar.Test$FooBar" [...]
```
I am not sure whether there is a bug in here, but it seems like I should be able to build a `MethodDescription.Latent` "by hand" that behaves like a constructor.  I can't offhand see where the problem might be.

**Comment by raphw** [comment]
In what context does this error happen? The toString output is expected, it aligns with the JVM's toString output.

**Comment by ljnelson** [comment]
Aha, that was it.  I'll close this bug report.  For posterity: the `InvokeDynamic.WithImplicitTarget#invoke(String, TypeDescription)` method must have a legal method name supplied to it.  The return value of a `MethodDescription#getName()` or `MethodDescription#getInternalName()` call for a `MethodDescription` that represents a constructor will not work here.  That's fine, as the constant name is ignored by the bootstrap method in this case anyway (you don't need a method name to look up a constructor).  I still feel like something is off here, but I don't think it has to do with `MethodDescription.Latent.`

**Comment by ljnelson** [comment]
(See also: https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/lang/constant/ConstantDescs.html#DEFAULT_NAME)
