### ISSUE TITLE
Support using currently loaded classes as TypePool

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#101]
When writing an agent, I might want to formulate a transformation based on a type description like this:
```
    Resolution httpServlet = typePool.describe("javax.servlet.http.HttpServlet");
    if (httpServlet.isResolved()) {
      TypeDescription httpServletType = httpServlet.resolve();
      transformer = agentBuilder.type(subTypeOf(httpServletType)))
```
Now, there are a couple of ways to obtain the typePool. Like `typePool = TypePool.Default.ofClassPath();`
The problem here is that HttpServlet is *not* on the classpath.
it is however contained in "allLoadedClasses" of "Instrumentation"

So how about an Instrumentation based type pool which works like this?
```
  private void initByteBuddy(final Instrumentation inst) {
    typePool = TypePool.Default.of(new ClassFileLocator() {

      @Override
      public Resolution locate(String typeName) throws IOException {
        Class<?>[] allLoadedClasses = inst.getAllLoadedClasses();
        for (Class<?> clazz : allLoadedClasses) {
          if (clazz.getName().equals(typeName)) {
            return ClassFileLocator.ForClassLoader.read(clazz);
          }
        }
        return Resolution.Illegal.INSTANCE;
      }

    });
 }
```

This works, but I am unsure about performance and other implications. For example I assume that the type pool will only have loaded classes, so using a Typedescription for the initial load of something might not work.

**Comment by CodingFabian** [comment]
or even better a LazyTypeDescription which would be resolved only when needed for the element matcher:
```
      transformer = agentBuilder.type(subTypeOf(LazyTypeDescription.of("javax.servlet.http.HttpServlet"))))
```

**Comment by CodingFabian** [comment]
btw, my proposed solution does not work either :-)
java.lang.NullPointerException:
at net.bytebuddy.dynamic.ClassFileLocator$ForClassLoader.locate(ClassFileLocator.java:288)

**Comment by raphw** [comment]
Basically, you want to have a `TypePool` that uses loaded types when possible but without triggering any type loading by itself? I am a bit sceptical for two reasons:

1. The above approach can still trigger class loading. A loaded class does not require its field or method types to be loaded. Accessing a field or method of a loaded class can still trigger class loading.
2. The performance can be terrible in scenarios. Looking up a class is something that happens fairly often when navigating types. For each type, finding out if there already is a loaded type is quite a heavy-load operation. One would need to be very careful when using this approach.

**Comment by CodingFabian** [comment]
yes it is somewhat into that direction.
The most common use case is that I want the TypeDescription for "name matching".
For example there is a takesArgument(index, typeDescription).
When that analysis is done, I know that the type for the argument has been loaded by the classloader already. So I want to reuse that easily. However when I install the transformer (premain, agentmain), that class might not be loaded (especially in complex classloading scenarios, like springboot). When matching, it is loaded (because it is a prerequiste for the type matched) so in those cases I would like to use it lazily.

I can show you code examples where that would be super convenient.

**Comment by CodingFabian** [comment]
Actually it does not need to classload. For my purpose of using them in matchers, It has to be loaded to have a chance of actually matching.
So basically it is a LazyMatchingTypeDescription
```
matches(type) {
desc = typePool.describe("foo.bar.Baz");
return desc.isResolved() && desc.resolve().matches(type) 
```

I think something like that is already possible by using a custom matcher, but I want to move that to the type description so it is usable in all matchers..

**Comment by raphw** [comment]
I played a bit with this, the problem I have with implementing such a solution is both:

1. The `getAllLoadedClasses` array can be **huge**. I just tried this on WebSphere, OMG.
2. A loaded class can be ambigous. On an application server, for example, different loaded classes `Foo` might exist, so a name is not definite. It is not enough to resolve all classes, one also needs to resolve any class relatively to a class loader hierarchy. This can be tricky with non-standard class loaders with multiple parents that some application servers use.

Worst case, such a `TypePool` would return false results. I am not sure if that justifies an implementation, especially since I am bit doubtful about the performance advantages.

**Comment by CodingFabian** [comment]
I hired a consultant to fix this issue for us. He will probably send a PR soon :)

**Comment by raphw** [comment]
I hope he is good because I am picky with those ;)

**Comment by CodingFabian** [comment]
I guess we can close this. The type pool is the wrong solution and we should use raw matchers.
