### ISSUE TITLE
Default `OnMethodEnter`/`OnMethodExit` `suppress` behavior

### ISSUE THREAD

**Issue by tylerbenson** [raphw/byte-buddy#1012]
It is rather error prone to require adding `suppress` to advice to ensure that exceptions within the advice don't affect the running application.

Any chance there's a setting that can change the default behavior of `suppress` at runtime?  (We'd like different behavior for tests vs release.)

It's also easy to forget to add `onThrowable`, and expect the advice to be run when an exception is thrown but it doesn't. Having a setting to change this behavior might also be useful.

**Comment by raphw** [comment]
Hi Tyler,

you are right, this is a property that should be able to be configurable. I will think about how this can be added without creating too much fuzz in the API. The original thought was that suppression is a behavior that should not change between test and production, and that one should rather configure the suppression handler. As for the on-throwable dynamic, the advice-creation does some early validation with regards to `@Thrown`.

I still find both approaches valid, and I like the readability of advices that come with it. Maybe this would be best solved by a linter? You could for example process all classes in your build and check for the advice annotations to see if they declare the annotations that you expect. You could even alter them for test builds.

As said, I see why this can be an issue, I am however still trying to consider the "casual user" who might not find such constructs intuitive.

Let me think about it, without any promises!

**Comment by tylerbenson** [comment]
The reason for wanting it configurable between test and runtime is that our advice classes should never throw exceptions, but that can be difficult to detect when they are suppressed.

> configure the suppression handler

Perhaps this will help. Could you elaborate please what you mean by this?

**Comment by richardstartin** [comment]
There’s another aspect to this: how much bytecode is added to the target method by default? Some advice simply cannot fail, and it shouldn’t pay for the weight of error handling by default. Being able to opt in to error handling but stay lightweight by default was the right decision, in my opinion, and already a lot better than needing to write the error handling manually.

**Comment by tylerbenson** [comment]
Yeah, I agree that it is the right default.  I'm only suggesting that it would be nice to be configurable.

**Comment by raphw** [comment]
If you want to throw an exception in test, you can implement an exception handler that rethrows the exception: https://github.com/raphw/byte-buddy/blob/3d0d06a5d5b987c6bf29a34e8c316158b71680fe/byte-buddy-dep/src/main/java/net/bytebuddy/asm/Advice.java#L6429

I might just add a default handler for this.

**Comment by raphw** [comment]
Just added a handler to master. Would that work for you? (`ExceptionHandler.Default.RETHROWING`)

**Comment by tylerbenson** [comment]
Cool, thanks.

So if we create advice with `new AgentBuilder.Transformer.ForAdvice().withExceptionHandler(Advice.ExceptionHandler.Default.SUPPRESSING)` then is the `suppress` flag ignored?

**Comment by raphw** [comment]
No, then the suppress flag swallows any exception without reaction. You'd use `AgentBuilder.Transformer.ForAdvice().withExceptionHandler(Advice.ExceptionHandler.Default.RETHROWING)`. If you want to try it, the exception handler is a one-liner that you can copy in in the mean time.

**Comment by tylerbenson** [comment]
I'm still not understanding the relationship between `withExceptionHandler` and `suppress`.

**Comment by raphw** [comment]
So, an exception handler for an advice is responsible to handling the generated catch block of an advice. Considering:

```java
@OnMethodEnter(suppress = Throwable.class)
void exceptionAdvice() {
  throw new RuntimeException("bø!");
}
```

you'd end up with advised code:

```java
try {
  throw new RuntimeException("bø!");
} catch (Throwable t) {
  // suppress
}
```

This would be the suppressing exception handler. The rethrowing would however implement:

```java
try {
  throw new RuntimeException("bø!");
} catch (Throwable t) {
  throw t; // rethrowing exception handler
}
```

The suppression is therefore no longer "suppressed" in the original sense but effectively disabled.

**Comment by raphw** [comment]
`suppress` is properly a bad name for the property in the annotation. Read 'triggerExceptionHandlerOn'. The suppression handler is triggered for any exception that is thrown within an advice. If you use `suppress = NoExceptionHandler.class`, it means that no exception handler is ever triggered for this advice, the exception is just thrown as if it occurred in the actual method.

If you do use `suppress = Throwable.class`, it means that the exception handler is triggered for any throwable thrown within the advice, but if using `Advice.ExceptionHandler.Default.RETHROWING`, the exception handler simply rethrows the exception what yields to the same effect as setting `suppress = NoExceptionHandler.class`, the exception handler voids itself. When using `Advice.ExceptionHandler.Default.SUPPRESSING` on the other hand means that the original behavior (from when the property was introduced) is applied where the exception is simply ignored.

**Comment by tylerbenson** [comment]
Thanks for the explanation.  That helps.  It sounds like the `suppress` option is still needed.  I guess my original request for a way to override the default still applies, but I have a much better understanding how the exception handler is used.

**Comment by raphw** [comment]
No, this is not yet addressed. I am not certain yet if I want to add a programmatic mechanism here since it changes the behavior of the advice and I am not sure if it makes advice easier to process. For now, I suggest that you add a small build plugin as a linter to fail the build if you find an advice method without the suppression. You could for example add an annotation processor which would even be recognized by IDEs.
