### ISSUE TITLE
Redefine class to replace public static final field value

### ISSUE THREAD

**Issue by rnoennig** [raphw/byte-buddy#1015]
I'd like to change a static field's value using byte-buddy in a javaagent:
Original class:
```java
package thirdpartylibrary;

public class ExecEnvironment {
	public static final boolean value = false;
}
```

I'd like to replace this class, so that all access to the field `value` will evaluate to `true`.
I simulate the thirdpartylibrary with this class:

```java
package thirdpartylibrary;

public class Server {

	Server() {
		System.out.println("Classloader during Instrumentalisation: " +
			ExecEnvironment.class.getClassLoader().getName());
		if (!ExecEnvironment.value) {
			throw new RuntimeException("ExecEnvironment.value still has the orignal value false!");
		}
		System.out.println("~~ > ~~ > ~~ > ~~ > ~~ > ~~ . ~~ < ~~ < ~~ < ~~ < ~~ < ~~ < ");
		System.out.println("                  IT FINALLY WORKED!!!!");
		System.out.println("~~ > ~~ > ~~ > ~~ > ~~ > ~~ . ~~ < ~~ < ~~ < ~~ < ~~ < ~~ < ");
	}
	
	public static void main(String[] args) {
		new Server();
	}

}
```

My attempt using byte-buddy:
```java
package agent;

import static net.bytebuddy.matcher.ElementMatchers.named;

import java.lang.instrument.Instrumentation;

import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.agent.builder.AgentBuilder.Transformer;
import net.bytebuddy.description.modifier.Ownership;
import net.bytebuddy.description.modifier.Visibility;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.DynamicType.Builder;
import net.bytebuddy.implementation.LoadedTypeInitializer;
import net.bytebuddy.pool.TypePool;
import net.bytebuddy.utility.JavaModule;

public class Agent {

	public static void premain(String args, Instrumentation instrumentation) throws NoSuchFieldException, SecurityException, Exception {
		System.out.println("---- PREMAIN ----");
		
		String targetClassName = "thirdpartylibrary.ExecEnvironment";
		String fieldName = "value";
		Class<?> fieldType = Boolean.class;
		boolean newValue = true;
		
		TypePool typePool = TypePool.Default.ofSystemLoader();
		TypeDescription targetClassType = typePool.describe(targetClassName).resolve();
		
	    new AgentBuilder.Default()
	    .with(AgentBuilder.Listener.StreamWriting.toSystemError().withTransformationsOnly())
	    .with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
	    .type(named(targetClassName))
	    .transform(new Transformer() {
			
			@Override
			public Builder<?> transform(Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader,
					JavaModule module) {
				System.out.println("Modding type: " + typeDescription);
				System.out.println("Classloader during Instrumentalisation: " + classLoader.getName());
				return builder
						.defineField(fieldName, fieldType, Visibility.PUBLIC, Ownership.STATIC)
						.initializer(new LoadedTypeInitializer.ForStaticField(fieldName, newValue))
						;
			}
			
		}).installOn(instrumentation);
	}

}
```

Log output:
```
---- PREMAIN ----
Modding type: class thirdpartylibrary.ExecEnvironment
Classloader during Instrumentalisation: app
[Byte Buddy] TRANSFORM thirdpartylibrary.ExecEnvironment [jdk.internal.loader.ClassLoaders$AppClassLoader@3d4eac69, unnamed module @a3d8174, loaded=false]
Classloader during Instrumentalisation: app
Exception in thread "main" java.lang.RuntimeException: ExecEnvironment.value still has the orignal value false!
	at thirdpartylibrary.Server.<init>(Server.java:8)
	at thirdpartylibrary.Server.main(Server.java:16)
```

I build the javaagent via maven and call it using `-javaagent:/path/to/TestAgent-0.0.1-SNAPSHOT-jar-with-dependencies.jar` in my eclipse run configuration.

I verified via debugging that during transformation and when I access my field that the classloaders have the same ID.

Is it even possible to redefine a class so that the public static field's value has a different value?

It seems like a simple enough use case, but I might be missing some information.

**Comment by raphw** [comment]
You are out of luck in this particular scenario. A public static final primitive or string value is considered a conpile time constant by javac if assigned directly. It will be resolved to this value by javac anywhere the field is accessed. At rumtime, the fields value does therefore no longer matter as the compile time constant is filled in.

You can validate this by replacing the boolean value by Boolean.parseBoolean("true").

**Comment by rnoennig** [comment]
Thank you so much for explaining this. Good to know what's going on!

Well, I guess I have to take a look where the variable is being used and try to modifier those methods using advices.
Thanks for putting in the work in making this library and giving talks about these topics!

**Comment by raphw** [comment]
I'm closing this issue, please get in touch if you have any further questions.

**Comment by domenicosf** [comment]
@raphw how can i access a property of a final class. Any tips? I just need to access the property of a final sub class and intercept a method of a superclass

**Comment by raphw** [comment]
You need to access it? From the outside? I would use method handles or reflection for this.

**Comment by domenicosf** [comment]
I just need read access to the field. I need this field to add the value as a header in the superclass method, but the method is in the superclass and the field is in the subclass that is final
