### ISSUE TITLE
Advice fixed return value helper

### ISSUE THREAD

**Issue by pimterry** [raphw/byte-buddy#1018]
I'm writing a java agent which attaches to a running process and hooks various methods. As far as I can tell, the only way to do this is using Advice classes - every other approach I tried hit various JVM redefinition errors - and that seems to match the advice (ha!) I've found everywhere.

In 90% of these Advice classes, I'm just using OnMethodExit and setting a fixed return value.

When I do this though, I need to define a separate advice class for each case, and somehow statically provide the return value in question, which is all quite fiddly.

Would it be possible to provide a helper to easily define fixed return value advice? I imagine that getting the value itself is tricky, since as I understand it you can't directly use an object instance, but I think there could be ways to describe static values conveniently. For example:

```java
.visit(Advice.fixedReturn(123)) // Constant literal values
.visit(Advice.fixedReturn(com.example.MyClass, "staticField")) // Static field ref by name
.visit(Advice.fixedReturn(objInstance)); // Maybe bytebuddy implicitly stores this elsewhere statically?
```

The last might be a bit optimistic, but even the first two would be super useful to me (and I think it would be possible to build number 3 yourself from number 2 + a static field in the transformer anyway). 

Each of those is representable with a full advice class too, but it's much more verbose and it would be useful to be able to put the transformation logic and the fixed value in the same place. This would also help me with #1014 - because this would replace 100% of the cases where I set the return value :smile:

**Comment by raphw** [comment]
You can easily construct something like this yourself. You would need an advice like this:

```java
class MyReturnAdvice {
  static void exit(@Advice.Return(readOnly = false, typing = Assigner.Typing.DYNAMIC) Object returned, @MyAnnotation Object value) {
    returned = value;
  }
}
```

Now you create `Advice.withCustomBinding().bind(MyAnnotation.class, ...).to(MyReturnAdvice.class)` and you can assign the value as you want it while being able to easily extend your advice later on.

**Comment by pimterry** [comment]
Ok, I'll try that out, I think that makes sense.

Still, I think this is really widely applicable for a lot of advice use cases, and the above would be tricky to work out for yourself if you're not super familiar with how everything works already. Would you be open to including the above implementation and a convenient `Advice.fixedReturn(...)` helper to use it in bytebuddy itself?

**Comment by raphw** [comment]
It would be a rather specific extension to add and there are a thousand shortcuts and helpers one can add. Therefore, I prefer the "clean" approach where this is expressed within the general semantics. I'm closing this issue, please get in touch if you have any further questions.
