### ISSUE TITLE
[Question] In this sample the interceptor is called twice.

### ISSUE THREAD

**Issue by tveronezi** [raphw/byte-buddy#1020]
Hi, 

I have a pretty simple sample of code (based on a gist I saw here) that intercepts the `HttpURLConnection#getRequestMethod`  method, but the interceptor is executed twice when I can `new URL("http://www.google.com").openConnection()`. Can you say what I'm doing wrong?

* sample project: https://github.com/tveronezi/help-bytebuddy-intecepted-twice

* sample agent: https://github.com/tveronezi/help-bytebuddy-intecepted-twice/blob/main/sources/javaagent/src/main/java/agentfun/agent/Agent.java

* sample standalone app: https://github.com/tveronezi/help-bytebuddy-intecepted-twice/blob/main/sources/sample-standalone/src/main/java/agentfun/standalone/Main.java

Output: 

```
Intercepted!
Intercepted!
GET
```

Thanks!

**Comment by raphw** [comment]
I assume that you both intercept `sun.net.www.protocol.http.HttpURLConnection` and `java.net.HttpURLConnection` where the former extends the latter.

You should make your matcher more specific to avoid catching both methods where one invokes the super method such that you receive two callbacks. Alternatively, you can store state in some thread local and deactivate the interception within a try catch block.

**Comment by raphw** [comment]
I'm closing this issue, please get in touch if you have any further questions.
