### ISSUE TITLE
How to enhance slf4j

### ISSUE THREAD

**Issue by all4you** [raphw/byte-buddy#1023]
Hi @raphw:
  Thank you for this amazing project. I am a new guy to byte-buddy and I am developing a agent recently which is used to tracking biz logs and send them to remote endpoint. I have struggled for several days cause I can't find out how to enhance the `org.slf4j.Logger` class and intercept the `debug`、`warn`、`info`、`error` method. The most block is that there are many middleware jars in our project and each jar has slf4j enbedded. 
And another middleware is pandora which is used to isolate classes in different jars by define customer classLoaders,I think this has some conflicts with bytebuddy but don't know why.
  Here is the code I do:
  ```java
PluginHolder pluginHolder = new PluginHolder(config);
        new AgentBuilder.Default()
                .type(pluginHolder.getTypeMatcher())
                .transform(new Transformer(pluginHolder))
                .with(new NoOpAgentListener())
                .installOn(inst);

public class PluginHolder {

    private TrackTraceConfig config;

    private List<AbstractPluginDefine> pluginDefines = new ArrayList<>();

    public PluginHolder(TrackTraceConfig config) {
        this.config = config;
        this.pluginDefines = PluginLoader.loadPlugins();
    }

    /**
     * 需要增强的类
     */
    @SuppressWarnings(value = "unchecked")
    public ElementMatcher<? super TypeDescription> getTypeMatcher() {
        ElementMatcher.Junction<TypeDescription> packageJunction = packageMatcher();
        // 首先排除掉接口
        ElementMatcher.Junction junction = packageJunction.and(not(isInterface()));
        for (AbstractPluginDefine pluginDefine : pluginDefines) {
            TypeMatcher matcher = pluginDefine.getTypeMatcher();
            // 每一个junction都需要在指定的package下
            junction = junction.or(matcher.buildJunction());
        }
        return new SafeMatcher(junction);
    }

    private ElementMatcher.Junction<TypeDescription> packageMatcher() {
        String enhancedPackage = config.getEnhancedPackage();
        String[] enhancedPackages = Arrays.stream(enhancedPackage.split(",")).distinct().toArray(String[]::new);
        ElementMatcher.Junction<TypeDescription> elementMatcher = ElementMatchers.nameStartsWith(enhancedPackages[0]);
        // 如果有除第一个包路径之外的多个包路径，使用or连接
        List<String> otherPackages = Arrays.stream(enhancedPackages, 1, enhancedPackages.length).collect(Collectors.toList());
        if (!otherPackages.isEmpty()) {
            for (String otherPackage : otherPackages) {
                elementMatcher = elementMatcher.or(ElementMatchers.nameStartsWith(otherPackage));
            }
        }
        return elementMatcher;
    }

    public List<AbstractPluginDefine> findPlugins(TypeDescription typeDescription) {
        List<AbstractPluginDefine> plugins = new ArrayList<>();
        for (AbstractPluginDefine pluginDefine : pluginDefines) {
            TypeMatcher matcher = pluginDefine.getTypeMatcher();
            if (matcher.isMatch(typeDescription)) {
                plugins.add(pluginDefine);
            }
        }
        return plugins;
    }
    /**
     * 定义一个安全的Matcher，当byte-buddy出现"Can't resolve type description"的异常时，将忽略
     * @param <T>
     */
    private class SafeMatcher<T> extends ElementMatcher.Junction.AbstractBase<T> {

        private final ElementMatcher<? super T> matcher;

        SafeMatcher(ElementMatcher<? super T> matcher) {
            this.matcher = matcher;
        }

        public boolean matches(T target) {
            try {
                return this.matcher.matches(target);
            } catch (Throwable t) {
                TtLog.debug( "Byte-Buddy occurs exception when match type. You can just ignore this message. cause=" + t.getMessage());
                return false;
            }
        }
    }
}

 public class Transformer implements AgentBuilder.Transformer {

    private PluginHolder pluginHolder;

    public Transformer(PluginHolder pluginHolder) {
        this.pluginHolder = pluginHolder;
    }

    @Override
    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
        List<AbstractPluginDefine> plugins = pluginHolder.findPlugins(typeDescription);
        if (plugins.isEmpty()) {
            return builder;
        }
        DynamicType.Builder<?> newBuilder = builder;
        for(AbstractPluginDefine plugin : plugins) {
            DynamicType.Builder<?> possibleNewBuilder = plugin.build(typeDescription, newBuilder, classLoader);
            if (possibleNewBuilder != null) {
                newBuilder = possibleNewBuilder;
            }
        }
        return newBuilder;
    }
}




  public class AutoTrackingPlugin extends AbstractPluginDefine {

    @Override
    protected TypeMatcher getTypeMatcher() {
       // find all classes which has super type of org.slf4j.Logger
        return SuperTypeMatcher.bySuperType("org.slf4j.Logger");
    }

    @Override
    protected List<InterceptorPoint> getInterceptorPoints() {
        return Collections.singletonList(new InterceptorPoint() {
            @Override
            public ElementMatcher<MethodDescription> getMethodMatcher() {
                return named("debug").or(named("info")).or(named("warn")).or(named("error"));
            }

            @Override
            public Interceptor getInterceptor() {
                // the interceptor 
                return new AutoTrackingInterceptor();
            }
        });
    }
}

public class SuperTypeMatcher implements TypeMatcher {

    private String[] superTypes;

    private SuperTypeMatcher(String[] superTypes) {
        if (superTypes == null || superTypes.length == 0) {
            throw new IllegalArgumentException("superTypes is null");
        }
        this.superTypes = superTypes;
    }

    public static TypeMatcher bySuperType(String... superTypes) {
        return new SuperTypeMatcher(superTypes);
    }

    @Override
    public ElementMatcher.Junction buildJunction() {
        ElementMatcher.Junction junction = null;
        for (String superType : superTypes) {
            if (junction == null) {
                junction = buildSuperType(superType);
            } else {
                junction = junction.or(buildSuperType(superType));
            }
        }
        junction = junction.and(not(isInterface()));
        return junction;
    }

    private ElementMatcher.Junction buildSuperType(String superType) {
        return hasSuperType(named(superType));
    }
}
  ```

**Comment by raphw** [comment]
I assume your type matcher is to strict. Consider matching all types with `hasSuperType(named("org.slf4j.Logger"))` and then add the restrictions after it.

**Comment by all4you** [comment]
But there is a problem if I matching the types with `hasSuperType(named("org.slf4j.Logger"))` then all the jars (such as `hsf-client.jar`,`mtop-client.jar`) that uses `slf4j` will be matched either. But I just want to match the biz classes in my project not the classes in the jars. 
Can you please give me some suggestion, thanks!

**Comment by raphw** [comment]
That's why you need to set a composite matcher such as: `hasSuperType(named("org.slf4j.Logger")).and(...)` where you further narrow down the classes.

**Comment by all4you** [comment]
I see.Thanks a lot!
Is there any matcher that only matches the classes in the classpath but not in the jars?

**Comment by raphw** [comment]
At runtime, everything is in a jar, typically. You can use a `RawMatcher` which provides the protection domain of a transformed class which offers the code location. Do however note that this is optional and it's normally more reliable to add a package-prefix matcher (`nameStartsWith`).

**Comment by all4you** [comment]
Can you give me a simple example code please?
Say that I have a config item: `${enhancedPackage}` achieved from System properties.
How can I match all the classes which package is startWith `${enhancedPackage}` and has the field Logger which `hasSuperType(named("org.slf4j.Logger"))`.

**Comment by all4you** [comment]
Maybe I don't describe my problem clearly, blow is what i want to do.
```java
// Class A is a biz class and it has a logger so I need to enhance it
Class A {
    org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(A.class);

   public void foo() {
     // do some biz
     logger.info("foo"); // this log will be auto tracked by byte-buddy
  }
}

// Class B is in jar so I don't want to match it
Class B {
    org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(A.class);

   public void bar() {
     logger.info("bar"); // this log will not be auto tracked
  }
}
```

**Comment by raphw** [comment]
`hasSuperType(named("org.slf4j.Logger")).and(nameStartsWith("foo.bar."))` would match all loggers in a package within *foo.bar*

**Comment by all4you** [comment]
I think you have misunderstanding my purpose.
I want to match those classes in `${enhancedPackage}` such as Class `foo.bar.A` because it is startWith `foo.bar` and `has` a `org.slf4j.Logger` field.
If I match classes by `hasSuperType(named("org.slf4j.Logger"))` I will get `ch.qos.logback.classic.Logger` And if I add `.and(nameStartsWith("foo.bar."))` I will not achieve it any more.
Because the Logger instance(`ch.qos.logback.classic.Logger`) which `hasSuperType(named("org.slf4j.Logger"))` does  not startWith `foo.bar`.So I can't match it.

**Comment by all4you** [comment]
maybe `nameStartsWith("foo.bar.").and(hasField(hasSuperType(named("org.slf4j.Logger"))))`  will meet the requirements

**Comment by raphw** [comment]
Yes, if you are looking into instrumenting all classes that declare a field of type logger, this would be right.

**Comment by all4you** [comment]
I have matched the types by `nameStartsWith("foo.bar.").and(hasType(hasSuperType(named("org.slf4j.Logger"))))` for example Class A.
but how can I match the method while Class A does not has a method named `info`,`warn`,`error`. It's the logger filed which has those methods. 
When the logger field executes the `logger.info()`,`logger.warn()`,`logger.error()` method I need to make an interception.

**Comment by raphw** [comment]
You need to instrument the class for which you want to change the behavior of. If you want to change logging for applications from given locations, you would need to instrument the class as such and then locate the caller from within the instrumented class to see if the instrumentation shpuld be applied.

**Comment by all4you** [comment]
Sorry, I don't know how to locate the caller.
```java
package foo.bar;
Class A {
  private org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(A.class);
  public void doBiz() {
     // do some biz
     logger.info("this log will be auto tracked"); // i just need to collect the logs 
 }
}
```
Do you mean that I need to locate the `logger.info` in my interceptor class? But how to do it ?

**Comment by raphw** [comment]
You'd need to instrument the subclass of `org.slf4j.Logger` and then from the instrumentation, you would check if the caller of `info` is a class of interest, in your case `A`. You can do so by:

- Using the `StackWalker` API starting from Java 9.
- Using `Thread.getStackTrace()` up to Java 8.

**Comment by all4you** [comment]
Can you give me a demo code please? I'm not quite understand your description.
I have already use the `AgentBuilder` to make some transform:
```java
new AgentBuilder.Default()
                .type(pluginHolder.getTypeMatcher())
                .transform(new Transformer(pluginHolder))
                .with(new NoOpAgentListener())
                .installOn(inst);
```
How to instrument a subclass of `org.slf4j.Logger` and put the code together with my `AgentBuilder`?

**Comment by raphw** [comment]
You'd match all subclasses of `org.slf4j.Logger` and then instrument these classes, for example by using `Advice` on the `info` method. From the advice code, you would use the `StackWalker` API for instance to see where you are being called from:

Advice is really just Java code:

```java
class MyAdvice {
  @OnMethodEnter
  static void enter() { 
    // use stack walker to identify caller here
  }
}
```

**Comment by all4you** [comment]
I now understand.Thank you for your help!
You are soooo Kind!
