### ISSUE TITLE
When enhance method with Annotation it conflicts with spring cglib

### ISSUE THREAD

**Issue by all4you** [raphw/byte-buddy#1025]
Hi @raphw 
 Thanks for your help last time,I have met another problem which I searched the issues and haven't found similar problems.
 I enhanced method with a self-defined Annotation but unfortunately the method has been marked with spring Annotation like `org.springframework.transaction.annotation.Transactional`.
The code is like blow:
```java
@Transactional(rollbackFor = Exception.class)
@SelfDefinedAnnotation 
public boolean foo() {
	// do biz
}
```
`SelfDefinedAnnotation` is used to match all those methods need to be enhanced by bytebuddy.
But when I start the application I find these logs print by spring:
```
2021-03-17 23:45:54.535|INFO|99030|main|||o.s.a.f.CglibAopProxy|Final method [final boolean some.package.SomeClass.foo$original$s5dTpKPq$accessor$jx2DPj48()] cannot get proxied via CGLIB: Calls to this method will NOT be routed to the target instance and might lead to NPEs against uninitialized fields in the proxy instance.
```
Which I think bytebuddy has rebased the method and make the method  `final` that cause spring can't enhance the method by cglib.
How can I avoid this?

**Comment by raphw** [comment]
The rebased method should neither be proxied as it is an internal construct. It will only ever be invoked by Byte Buddy and Spring's proxy should and does respect that. I would argue that you should safely ignore the warning.

**Comment by all4you** [comment]
But I'm afraid that if the method rebased by Byte Buddy and Spring has no chance to apply the `@Transactional` on the same method which may cause our business error, for example a expected transaction rollback will not happen.
Should I not apply my SelfDefined Annotation and give a warning log to the user when the method already had a Spring Annotation, that because I should ensure the normal business logic first.

**Comment by raphw** [comment]
There should never be an annotation on the rebased copy. It's merely a synthetic projection used by Byte Buddy, that's why I thi k you can safely ignore the method.

**Comment by all4you** [comment]
Can I make the delegated method `foo()` not to be `final` so that cglib can also proxy the method?
If there is a way can you show me some code please?

**Comment by raphw** [comment]
No, this is a Byte Buddy internal method, it is created that way, to make transformations chainable. You'd need to find a way to tell Spring that this is ok.
