### ISSUE TITLE
Use of @Advice.Return in Scala

### ISSUE THREAD

**Issue by adamhamlin** [raphw/byte-buddy#1027]
Hi, just wanted to say this library is great. It's really helped us solve some really intractable problems.

Our codebase is primarily Scala, and currently we are using ByteBuddy to do some hot swap manipulations using the `@Advice` paradigm (must be hot swap -- using `premain` is not an option for us). However, we'd like to add a new transformation hook that manipulates the return value of a function, but in Scala you can't reassign a function parameter (it's immutable):

```scala
@Advice.OnMethodExit
def hook(@Advice.This callingObj: AnyRef, @Advice.Return(readOnly = false, typing = Assigner.Typing.DYNAMIC) returnRef: AnyRef): Unit = {
  // We can make it here, but below reassignment is illegal. How can we tell Scala to repoint the return value?
  returnRef = getReturnValue(callingObj, returnRef)
}
```
Of course we could just write this function in Java, but we've had intractable issues with our coverage reporting when mixing Java/Scala code within a module, and we're trying to avoid creating another Java module (we'd have to do some hoop jumping to avoid circular dependencies).

So my question is, do you know of a trick to use `@Advice.Return` paradigm in Scala? The only thing I could think of was something like below (which would eliminate circular dependency), but it doesn't work/is pretty naive:

```scala
@Advice.OnMethodExit
def hook(@Advice.This callingObj: AnyRef, @Advice.Return(readOnly = false, typing = Assigner.Typing.DYNAMIC) returnRef: AnyRef): Unit = {
  Blah.setReturnValue(returnRef, getReturnValue(callingObj, returnRef))
}
```
```java
class Blah {
    public static void setReturnValue(@Advice.Return(readOnly = false, typing = Assigner.Typing.DYNAMIC) Object refToChange, Object value) {
        refToChange = value;
    }
}
```

Thanks very much for your time.

**Comment by raphw** [comment]
Unfortunately, no, at the moment. I would add field instructions, but they yield a different byte code sequence which makes the replacement costly. I would however recommend to always use Java for the advice code, not only because it fits well, but also because of the byte code created. The Scala compiler can sometimes create patterns that are not inlineable, this is a problem you will run into eventually, I am afraid.

**Comment by adamhamlin** [comment]
Fair enough, thank you for the explanation 👍
