### ISSUE TITLE
[Question] Instantiating a class that has no constructor?

### ISSUE THREAD

**Issue by realdadfish** [raphw/byte-buddy#1028]
I'm trying to instantiate a proprietary Samsung framework class on Android (this one: https://github.com/fonix232/SCoverRE/blob/master/Reversed/framework/com/samsung/android/content/clipboard/SemClipboardManager.java, but probably a newer version than it), like so:

```java
ClassLoadingStrategy strategy = new AndroidClassLoadingStrategy.Wrapping(getDir("generated", Context.MODE_PRIVATE));
Class<?> dynamicType = new ByteBuddy()
  .subclass(samsungServiceInstance.getClass())
  .method(ElementMatchers.named("isEnabled"))
  .intercept(FixedValue.value(false))
  .make()
  .load(service.getClass().getClassLoader(), strategy)
  .getLoaded();
```

Now, when I try to instantiate that `dynamicType` I get a `NoSuchMethodException` because I cannot find a constructor on the type. Moreover, I cannot even find any constructor on the original `samsungServiceInstance` class either, when I query `getConstructors()` or `getDeclaredConstructors()`. I have read that not every class in the JVM needs to have a constructor, but how can it be that there is an instance of a class when this class has no constructor? How could have this instance then be created? Or is it possible that for my client code this constructor got somehow removed?

**Comment by raphw** [comment]
I assume that they use a reflection factory (JVM internals) somehow to instantiate it, if no constructor is declared. The Java programming language always adds a constructor, but if none exists, the JVM does not care about it. Is `ReflectonFactory` available on the JVM in question? In this case, this would be a possibility to instantiate it, using JVM internals.

Otherwise: is the class serializable? Then you could use a deserialization from a pseudo stream to create a class without internal API.

**Comment by realdadfish** [comment]
This is Android, so I'm in doubt ReflectionFactory is in the classpath being it residing in the sun.* namespace (but I'll try later nonetheless) - Androids codesearch only brings up these instances: https://cs.android.com/search?q=ReflectionFactory&sq=

From what I saw the class is not serializable either, but I'll double check this later as well (currently on the go). 

Am 24. März 2021 11:07:38 MEZ schrieb Rafael Winterhalter ***@***.***>:
>I assume that they use a reflection factory (JVM internals) somehow to
>instantiate it, if no constructor is declared. The Java programming
>language always adds a constructor, but if none exists, the JVM does
>not care about it. Is `ReflectonFactory` available on the JVM in
>question? In this case, this would be a possibility to instantiate it,
>using JVM internals.
>
>Otherwise: is the class serializable? Then you could use a
>deserialization from a pseudo stream to create a class without internal
>API.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/raphw/byte-buddy/issues/1028#issuecomment-805669235

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by realdadfish** [comment]
Just double-checked, the class does not implement `Serializable` (checked via `instanceof` in the debugger) and `sun.reflect.ReflectionFactory` cannot be found in the classloader that loaded the service class either.

I still don't understand how the class could have been created at all by the Android runtime in first place.

**Comment by raphw** [comment]
There's likely some trickery, for example it might be created in the native layer.

**Comment by realdadfish** [comment]
Hah, I got a tip that `objenisis` could help, and indeed, that worked (with version 2.6):

```java
ClassLoadingStrategy strategy = new AndroidClassLoadingStrategy.Wrapping(getDir("generated", Context.MODE_PRIVATE));
Class<?> dynamicType = new ByteBuddy()
  .subclass(service.getClass())
  .method(ElementMatchers.named("isEnabled"))
  .intercept(FixedValue.value(false))
  .make()
  .load(service.getClass().getClassLoader(), strategy)
  .getLoaded();
Objenesis objenesis = new ObjenesisStd();
return objenesis.newInstance(dynamicType);
```
