### ISSUE TITLE
Not declared by class...

### ISSUE THREAD

**Issue by LikeTheSalad** [raphw/byte-buddy#1034]
[**Possibly not a Byte Buddy issue**, I'm just asking just in case it's seen before or it can lead to know what's going on]

Hi! there's a bug on Android Buddy: https://github.com/LikeTheSalad/android-buddy/issues/1 which only happens in a specific project, under specific circumstances which the creator of the bug hasn't been able of reproducing it in another project. I haven't been able of reproducing it either and it kinda looks like it might be something related to the project itself, however, I would still like to ask here just in case this type of issue rings a bell on what could be causing it on Byte Buddy side. In other words, I just would like to know what does it usually mean when Byte Buddy throws this type of error (if there's some config issues or classpath issues etc.) so that I could take a look at those at Android Buddy just in case.

Please let me know if any other information is needed.

Thanks!

**Comment by raphw** [comment]
Seems like you have a class that defines itself to be declared by a type and method that is not defined by that specified type. When Byte Buddy tries to change that class and reassemble the class file, it finds this inconsistency and fails as a result.

Ideally, Byte Buddy would ignore and reproduce the inconsistency, but this is easier said then done since the class serialization and deserialization are seperate.

I do however wonder if that's a Kotlin issue, I remember in the back of my head to have seen this before in this context. If it's related to an incremental build, I do however wonder if the incremental build algorithm overlooks something and fails to recompile a class that has indeed changed metadata (the "declaring method" attribute) which turns out inconsistent as a result.

**Comment by LikeTheSalad** [comment]
Got it, thanks for your quick response. To be honest, I got a little lost in the last part of the types not defined by that type 😅 -  However, it seems like you think these kinds of inconsistencies are likely to happen which is why, ideally, a way to deal with them would be by ignoring them?

In any case, it does seem that some sort of cache or just the incremental build system might be causing the issue, although it's quite strange to me that these cases wouldn't be always reproducible (like every time you make a change to a class and compile again) which is why I think that, maybe due to the apparently big refactoring made by the author of the bug, seems like there might be too many changes for the Gradle incremental build to handle them properly after switching branches between the old and the refactored project? - Although it's still strange because I think Gradle should do a compilation from scratch in those cases... I'm starting to think to myself if maybe the git repo contains the build dir tracked...

In regards to Kotlin, to be honest I'm not sure... I do know of one curious thing I noticed long ago (maybe you know already) which is that they tend to add some code before the `super()` call in a class constructor, which would be forbidden writing it in plain Java but apparently it's ok in bytecode and Kotlin does it. I'm not saying that it could be the cause for this issue, but I guess is fair to say that in the Kotlin bytecode there could be some "Java-illegal" things around. Intellij IDEA has a handy Kotlin bytecode decompiler tool in case you'd like to quickly see what the Kotlin bytecode looks like, in case it helps!

I'm going to dig a bit further into the Gradle's incremental build system doc to see if there's something I'm missing about the way it's supposed to work. Do you think there's anything regarding the Byte Buddy API setup I could double check just to make sure things are properly configured?

**Comment by raphw** [comment]
So, the class pretends to be defined as in:

```java
class Foo {
  void m() {
    class Bar { }
  }
}
```

This is legal Java. However, in your application, `Bar` still claims to be defined within a method `m` of `Foo` but it seems that `Foo` does no longer declare `m`. Maybe the method was renamed but the incremental build does not discover it. It has no real consequence for the compilation of `Bar` but for this one meta-data block.

If you can produce a stable reproduction, I could look into it. The more I look at the code, the more I think it's a bug in Gradle.

**Comment by LikeTheSalad** [comment]
Thanks for the explanation, it is much clearer now. You're right, there's no much to do if we can't reproduce it on-demand. I'll try to find a way to do so possibly during the weekend to see if I can find something and will update here if anything. I understand your concern as I've found a couple of Gradle incremental issues that seem quite similar to this one so it seems like there's still some work going on regarding this feature. I'll leave the similar issues here as future reference for myself and also just in case you'd like to have a look.

https://github.com/gradle/gradle/issues/6038
https://github.com/gradle/gradle/issues/11316
https://github.com/gradle/gradle/pull/16536

**Comment by oehme** [comment]
Is this Java or Kotlin code? If Kotlin, then please open a Kotlin bug, since they maintain their own incremental compiler. If Java, we'd need a reproducible sample. I tried the obvious, creating a local class and then removing it again and the class file is deleted as expected.

**Comment by raphw** [comment]
Sounds like it's Kotlin to me, since it's Android, it's quite likely.

**Comment by LikeTheSalad** [comment]
Thanks for jumping in @oehme, I need to ask that, but yeah most likely should be Kotlin, I didn't know that they had their own incremental compiler.

**Comment by LikeTheSalad** [comment]
I tried to reproduce it without luck so I asked the author of the ticket to provide a sample project where we could reproduce it, however, he's previously mentioned that he wasn't able of reproducing it in a different project so it seems like it's quite difficult to get this issue. In any case, I'll close this ticket as it doesn't look like there's anything wrong on Byte Buddy's side and also, there doesn't seem to be much extra info we can gather without a stable way of reproducing it so keeping this ticket open doesn't seem necessary, at least until further notice anyway. Thanks everybody for your help!
