### ISSUE TITLE
Getting java.lang.NoClassDefFoundError when trying to dynamically define an Enum and use it

### ISSUE THREAD

**Issue by rkuppadakath** [raphw/byte-buddy#1035]
I am trying to dynamically define (a) Enum and use it as one of the property for a dynamically generated Java bean.
I have tested both of them independently and it is working fine. However when I put them together I am getting the following exception.  Any idea what could be wrong? using 1.10.19 version.

Caused by: java.lang.ClassNotFoundException: com.f3.metadata.cache.SideEnum
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:348)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 52 more

```
	public static Class<? extends Enum> createEnum(CbeanField f, ClassLoader cl) {
		return new ByteBuddy()
		.with(new NamingStrategy.AbstractBase() {
			@Override
			protected String name(TypeDescription superClass) {
				return Cbean.class.getPackage().getName() + "." + Util.firstLetterToUppercase(f.getName())
						+ "Enum";
			}
		})
		.makeEnumeration(f.getOptions().toArray(new String[0])).make().load(cl).getLoaded();
	}

	public static Class<?> createCbeanClass(CbeanMetaDefinition def) {
	
		DynamicType.Builder<Cbean> builder = new ByteBuddy()
				.with(new NamingStrategy.AbstractBase() {
					@Override
					protected String name(TypeDescription superClass) {
						return Cbean.class.getPackage().getName() + "."
								+ Util.firstLetterToUppercase(def.getCache());
					}
				})
				.subclass(Cbean.class);
		String key = null;
		for (CbeanField f : def.getFields()) {
			builder = builder.defineProperty(f.getName(),f.isEnum()?createEnum(f,def.getClass().getClassLoader()):CbeanField.getJavaType(f));
			if (f.getKey() != null && f.getKey()) {
				key = f.getName(); // this can be ignored 
			}
		}
		return builder.method(ElementMatchers.named("key"))
				.intercept(MethodCall.invoke(ElementMatchers.namedIgnoreCase("get" + key))).make()
				.load(def.getClass().getClassLoader()).getLoaded();

	}
// for clarity CbeanField is just a pojo to hold the field definition
public class CbeanField {
	private String name;
	private String type;
	private Boolean key;
	private List<String> options;
}
```
thanks
Rajeev

**Comment by raphw** [comment]
By calling `.load(x.getClass().getClassLoader())`, you are creating a new class loader which can only see the classes by it's child class. You probably want to call `include` on the first `DynamicType` and then load them together in a common class loader such that the two classes can see each other.

**Comment by raphw** [comment]
I'm closing this issue, please get in touch if you have any further questions.
