### ISSUE TITLE
Collapsing nesting conjunctions and disjunctions

### ISSUE THREAD

**Issue by richardstartin** [raphw/byte-buddy#1036]
In the Datadog tracer we often see stack traces like this where there are multiple layered conjunctions or disjunctions

<img width="929" alt="Screenshot 2021-04-13 at 10 50 17" src="https://user-images.githubusercontent.com/16439049/114533793-3245a180-9c46-11eb-99e0-eb5c2c0c1663.png">

I expect that inlining these binary matchers into a wider N-way conjunction/disjunction matcher would be profitable (but haven't actually done any experiments yet). This would be straightforward to do eagerly without requiring an optimising pass over the tree. 

Currently the matchers have a one to one correspondence with what the user defines, and care has been taken to represent the structure faithfully in the `toString` implementations, but is this something you have previously thought about doing? Is there any potential to break something I haven't thought about or other users rely on/expect?

**Comment by raphw** [comment]
That's a good point and I considered it from time to time, mainly for the `ElementMatcher` API but it's just as legitimate for the agent-related matchers. I always postponed it for the binary incompatible change but now is as good of a time as ever for a new feature release.

I fixed it in the most compatible manner possible and applied it for all matchers, it's not a big change so it was easy enough. Thanks for pushing this back into my memory.
