### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@24de6541

### ISSUE THREAD

**Issue by ram2012k** [raphw/byte-buddy#1042]
When i try to run test file from intellij they are working fine .

But if i run from terminal by ```mvn clean install ```. it is giving the following error 

`[ERROR] testGetSuccess on testGetSuccess(com.controller.DeviceControllerTest)(com.controller.DeviceControllerTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@cbf7f90
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 

Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : 1.8
JVM vendor name    : AdoptOpenJDK
JVM vendor version : 25.275-b01
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 1.8.0_275-b01
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.14.6

Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@24de6541
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.tools.attach.LinuxVirtualMachine`

**Comment by ram2012k** [comment]
My $JAVA_HOME /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home

**Comment by ram2012k** [comment]
Using 
[INFO] +- org.mockito:mockito-core:jar:2.8.47:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.10.19:compile
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.19:test
[INFO] |  \- org.objenesis:objenesis:jar:2.5:test

**Comment by raphw** [comment]
Are you running a JRE and not a JDK? This is not supposed to happen: java.lang.NoClassDefFoundError: Could not initialize class sun.tools.attach.LinuxVirtualMachine

**Comment by ram2012k** [comment]
How to check if I am running a JRE and not JDK ? 
What is JNA path in macOS ?

**Comment by raphw** [comment]
For Java 8, check of there's a tools.jar in the lib folder. JNA is a library that you can find on Maven Central. You'd include it just like Mockito.

**Comment by ram2012k** [comment]
it is present inside.
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/
I tried adding this in $PATH also 

The thing is , setup is working fine few days ago , without JNA , Only from yesterday i am facing the problem .

**Comment by raphw** [comment]
You can find the `ByteBuddyAgent.install()` call in Mockito and debug it, if it worked before, something must have changed.

**Comment by ram2012k** [comment]
in which class ?

**Comment by raphw** [comment]
It's somewhere in ByteBuddyInlineMockMaker,I think. You can use GitHubs code search on the Mockito project.

**Comment by raphw** [comment]
I'm closing this issue, please get in touch if you have any further questions.
