### ISSUE TITLE
FixedValue fails for values of different types with same hashCode() in the same class

### ISSUE THREAD

**Issue by tiwieso** [raphw/byte-buddy#1043]
When subclassing an (abstract) class and creating multiple FixedValues for intercepted methods an `IllegalStateException` is thrown in `FixedValue.getOnly()` when the values are of different type, but have the same hashCode (...might be also a problem with fields, did not check that yet).
The problem seems to be in `FixedValue.ForValue.fieldName` generation, so maybe it affects other FixedValue implementations, too... as far as is could see do they work in a similar way.

```
protected ForValue(Object value) {
    this(PREFIX + "$" + RandomString.hashOf(value.hashCode()), value);
}
```

Example Code (in Kotlin, intercepting the Java-getters, but this should not be relevant for the behavior)
```
data class X(val y: Int = 0, val x: List<String> = emptyList())
data class Y(val y: Int = 0, val x: List<String> = emptyList())

abstract class Test {
    abstract val a: X
    abstract val b: Y
    override fun toString(): String = "Test($a, $b)"
}

val cls = Test::class
val instance = ByteBuddy(ClassFileVersion.JAVA_V8)
    .with(AnnotationRetention.ENABLED)
    .subclass(Test::class.java)
    .attribute(TypeAttributeAppender.ForInstrumentedType.INSTANCE)
    .name("${Test::class.qualifiedName}\$ByteBuddy")
    .method(ElementMatchers.named("getA"))
    .intercept(FixedValue.value(X()))
    .method(ElementMatchers.named("getB"))
    .intercept(FixedValue.value(Y()))
    .make() // java.lang.IllegalStateException: size = 2
	         // at net.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:139)
    .load(cls.java.classLoader, ClassLoadingStrategy.Default.WRAPPER)
    .loaded
    .getDeclaredConstructor()
    .newInstance()
println(instance.a.hashCode())
println(instance.b.hashCode())
println(instance)
```

As this seems not to be a problem when I replace the `b` in the `Test`-class with another type `X` instead of `Y`, i assume that this only affects values of different types with the same hashCode, so maybe including the fully qualified class name in the field name could prevent this.

```
protected ForValue(Object value) {
    this(PREFIX + "$" + value::class.name.replaceAll(".", "_") + RandomString.hashOf(value.hashCode()), value);
}
```

**Comment by tiwieso** [comment]
Update: Same Type, different content, but same hashCode (forced by implementation for the sake of the example):

```
data class X(val y: Int = 0, val x: List<String> = emptyList()) {
    override fun hashCode(): Int {
        return 1
    }
}
...
abstract class Test {
    abstract val a: X
    abstract val b: X
    override fun toString(): String = "Test($a, $b)"
}
...
    .method(ElementMatchers.named("getA"))
    .intercept(FixedValue.value(X()))
    .method(ElementMatchers.named("getB"))
    .intercept(FixedValue.value(X(1)))
...
```

results in a 
```
java.lang.IllegalStateException: Duplicate field definition for public static volatile my.package.X my.package.Test$ByteBuddy.value$1000000
```
At least for this the above proposal is most likely not enough to fix this.

**Comment by tiwieso** [comment]
Update: in the case of a hash collision without equality there is another problem:

```
data class X(val y: Int = 0, val x: List<String> = emptyList()) {
    override fun hashCode(): Int {
        return 1 // forced for the sake of the example
    }
}
...
abstract class Test {
    abstract val a: X
    abstract val b: X
    override fun toString(): String = "Test($a, $b)"
}
...
    .method(ElementMatchers.named("getA"))
    .intercept(FixedValue.value(X()))
    .method(ElementMatchers.named("getB"))
    .intercept(FixedValue.value(X(1)))
```
results in:
```
java.lang.IllegalStateException: Duplicate field definition for public static volatile some.package.X some.package.Test$ByteBuddy.value$1000000
```

**Comment by raphw** [comment]
That's by design, the names of the fields need to be stable, otherwise the classes would not be reproducable. You can always set your own names for fields, there are overloads. Addmittedly, the error message could be better and I added an explicit check. I also improved the naming strategy to avoid the clash if two structural equal classes collide.

**Comment by tiwieso** [comment]
Wow, that was quick, thanks a lot! :)

Its not only about structural equal classes. At least in Kotlin data classes (and in generated hashCode() implementations you only need all properties to be 0 or false)
```
// data class y = Int, b = Boolean, c = Char
public int hashCode() {
      int var10000 = this.y * 31;
      byte var10001 = this.b;
      if (var10001 != 0) {
         var10001 = 1;
      }

      return (var10000 + var10001) * 31 + this.c;
   }

// same but generated
override fun hashCode(): Int {
        var result = y
        result = 31 * result + b.hashCode()
        result = 31 * result + c.hashCode()
        return result
    }
```

so a class `X(0,0,0)` will get the same hashCode as a class `Y(false, false)` and `X(0,0,1)` will have the same as `Y(false, true)`

```
this(PREFIX + "$" + RandomString.hashOf(value.getClass().hashCode() ^ value.hashCode()), value);
```

`Class` does not override `hashCode()` (at least in openjdk 1.8), so it uses the default implementation in `Object`, which means, the new naming strategy might solve the case from the first post on most environments, but this is not necessarily the case in all jvms:

```
     * As much as is reasonably practical, the hashCode method defined by
     * class {@code Object} does return distinct integers for distinct
     * objects. (This is typically implemented by converting the internal
     * address of the object into an integer, but this implementation
     * technique is not required by the Java&trade; programming language.) <<<
```

The default implementation in openjdk seems to be one of (different for different java versions/implementations) and according to this dev 
([blogpost](https://srvaroa.github.io/jvm/java/openjdk/biased-locking/2017/01/30/hashCode.html)) has nothing to do with memory address in openjdk 6, 7, 8 or 9 (I do not know for Dalvik)

```
0. A randomly generated number. // for openjdk 6 and 7 according to the blogpost
1. A function of memory address of the object.
2. A hardcoded 1 (used for sensitivity testing.)
3. A sequence.
4. The memory address of the object, cast to int.
5. Thread state combined with xorshift (https://en.wikipedia.org/wiki/Xorshift) // for openjdk 8+ according to the blogpost
```

But even in this cases it will still have problems with cases from my second comment where there are hashCode-collisions for instances of the same type with different contents (just like the class.name-approach).

I will try to generate the fieldNames manually for now, thanks for the hint. :)

**Comment by raphw** [comment]
Yes, I agree this possible collision is far from ideal. The rationale, however, is that one would normally only add few static values and that collisions are rather rare to observe. Basing the name on the hash code is the next best thing when hoping for reproducibility.

**Comment by tiwieso** [comment]
I agree and I think my use case is kind of special, as i have to auto-generate lots of default values for the property/return types in a class. The change you committed should fix the cases from my first post (the same-class collisions should not occur for my use-case anyways). 

Thanks and have a nice week!
