### ISSUE TITLE
bytebuddy with springboot

### ISSUE THREAD

**Issue by xu1009** [raphw/byte-buddy#1044]
bytebuddy use in speingboot 1.5 project, springboot can not start，it stuck，where is the problem

the image show the  org.springframework.boot.loader.LaunchedURLClassLoader just load one class

![image](https://user-images.githubusercontent.com/22722907/115720884-0c3fa000-a3b0-11eb-98e1-e0f978698ec1.png)

**Comment by raphw** [comment]
That is insufficient information to really say anything. Is your application deadlocked?

**Comment by raphw** [comment]
I'm closing this issue, please get in touch if you have any further questions.
