### ISSUE TITLE
Filtering methods on advice visit

### ISSUE THREAD

**Issue by nomemory** [raphw/byte-buddy#1045]
Hello, 

I want to "scan" all the classes that are annotated with a given annotation (let's call it `SomeAnnotation`). Furthermore, I want to be able to create an advice on the methods of those classes, but with a given condition, the methods should have arguments, and the arguments should also be annotated with various annotations (I support).

Something like:

```java
ByteBuddyAgent.install();

new AgentBuilder.Default()
        .type(isAnnotatedWith(SomeAnotation.class))
        .transform(
                (builder, typeDescription, classLoader, javaModule) -> {
                    return builder.visit(Advice.to(Validator.class).on(
                            /** code here */
                            /** needs to apply on methods that have arguments */
                            /** needs to apply on methods that have arguments which are annotated with a given type */
                    )
                }
        )
        .installOnByteBuddyAgent();
```

Is it possible to write a method like this ?

**Comment by raphw** [comment]
Sure, ElementMatcher is a functional interface getting passed a MethodDescription. You can more or less implement this youraelf by copy-pasting what you would do when using reflection. Iterate over the parameters and check.

**Comment by nomemory** [comment]
Thank you for the quick answer. I've narrowed things down to the following questions.

```java
ByteBuddyAgent.install();

new AgentBuilder.Default()
  .type(isAnnotatedWith(Validium.class))
  .transform(
          (builder, typeDescription, classLoader, javaModule) ->
                  builder.visit(Advice.to(NotNullAdvice.class).on(isMethod().and(m ->
                      m.getParameters().stream().anyMatch(p ->
                              p.getDeclaredAnnotations().isAnnotationPresent(NotNull.class))
  ))))
  .installOnByteBuddyAgent();
```

And the `NonNullAdvice.java` is:

```java
package net.andreinc.validium.advice;

import net.bytebuddy.asm.Advice;

import java.lang.reflect.Method;

public class NotNullAdvice {
    @Advice.OnMethodEnter
    public static void enter(@Advice.Origin Method method, @Advice.AllArguments Object[] args, /** Arguments with NotNull on them */) {
        /**
         * For all the arguments with @NonNull on them check if they are NULL
         */
    }

    @Advice.OnMethodExit
    public static void exit() {}
}
```

Is there a way to pass the arguments that I found to be marked with `@NoNull`? so I don't have to iterate in the `Advice` again over all the arguments/method.params again ?

**Comment by raphw** [comment]
The code you are posting should work, I think? If you want to do more at compile time, you can use `Advice.withCustomBinding().bind(MyAnnon.class, ...)`. You can then for example only inject arguments of parameters that are annotated. Have a look at the binder for `@Advice.AllArguments` to see how this is done.
