### ISSUE TITLE
Getting Runtime Bean Attribute

### ISSUE THREAD

**Issue by leon90dm** [raphw/byte-buddy#105]
Hi, Does byte-buddy have the Feature of Getting Runtime Bean Attribute ? For example
A simple POJO Bean like below:
```
public static class Person{
        private String name = "tom";
        .... other attributes
        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }
```
And an interface:
```
public interface AttributeGetter {
        Object getAttr(Object target);
    }
```
I want bytebuddy to generate a class that implements AttributeGetter with a given attribute name like `person.name`, when invoking the AttributeGetter instance's `getAttr()` method by passing a given Person instance will get `Person's name` attribute value?

**Comment by raphw** [comment]
Of course that is possible:

```java
class MyInterceptor {
  public static Object intercept(Object arg) {
    // do what you intend to do.
  }
}

new ByteBuddy()
  .subclass(AttributeGetter.class)
  .method(named("getAttr"))
  .intercept(MethodDelegation.to(MyInterceptor.class))
  .make();
```

**Comment by leon90dm** [comment]
It's close but  doesn't solve my problem.
How can i generate `MyInterceptor` in runtime based on `Person` and attribute `name`.
```
class MyInterceptor {
  public static Object intercept(Object arg) {
    // do what you intend to do such as:
    return ((Person) arg).getName();
  }
}
```
that's to say this stuff `return ((Person) arg).getName();` is generated in runtime. Cause i have many other attributes to generate such as
```
class MyInterceptor {
  public static Object intercept(Object arg) {
    return ((Person) arg).getAge();
  }
}
```
While i don't want to write `MyInterceptor` for every attribute of `Person`.

**Comment by raphw** [comment]
You can just hard-code a method call using dynamic assignment:


```java
new ByteBuddy()
  .subclass(AttributeGetter.class)
  .method(ElementMatchers.named("getAttr"))
  .intercept(MethodCall.invoke(Person.class.getDeclaredMethod("getName"))
                                    .onArgument(0)
                                    .withAssigner(Assigner.DEFAULT, Assigner.Typing.DYNAMIC))
  .make();
```

**Comment by leon90dm** [comment]
Awesome That's it! Thanks a lot！
