### ISSUE TITLE
Cannot inject auxiliary class into bootstrap loader using reflection

### ISSUE THREAD

**Issue by hucaicai** [raphw/byte-buddy#1056]
java.lang.IllegalStateException: Cannot inject auxiliary class into bootstrap loader using reflection

What is the cause of the above problem?

**Comment by raphw** [comment]
You need to configure an injection strategy that supports injection into the boot loader. The default strategy that uses Java reflection cannot work on the bootstrap loader which is represented by `null`. You can configure an injection strategy on the `AgentBuilder` that you are using.

**Comment by hucaicai** [comment]
This is my strategy now.
agentBuilder.type(pluginFinder.buildMatch())
                    .transform(new Transformer(pluginFinder))
                    .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                    .with(new Listener())
                    .installOn(instrumentation);

How to set the specific strategy?

**Comment by raphw** [comment]
The injection strategy is configured on the builder: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/agent/builder/AgentBuilder.java#L261

There's multiple options which are described in their respective javadoc.

**Comment by raphw** [comment]
I'm closing this issue, please get in touch if you have any further questions.
