### ISSUE TITLE
TypeDescription implementations now must implement getPermittedSubtypes()

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#1057]
Existing (user) implementations of `TypeDescription` now apparently need to implement `getPermittedSubtypes()` in 1.11.1.

This is a breaking change from 1.11.0.

My guess is that `TypeDescription.AbstractBase` should probably implement this method and should return an empty `TypeList` by default.  Most user occurrences of `TypeDescription` "in the wild" probably extend from this abstract class anyway.

**Comment by raphw** [comment]
The interface is considered as a sealed type and I do not expect it to be implemented manually by many people. It's of course a bit unclean from a user perspective, but it has worked well over the years to use such common sense. I agree that it's not ideal from a user perspective if one does implement the interface, but I don't think I will change this approach. The `AbstractBase` is meant as an approximation of default methods. I think a compile error is to be preferred here, as an empty implementation would yield incorrect results. Often, the method would not be called on custom implementations anyways.
