### ISSUE TITLE
getPermittedSubclasses() method disappeared

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#1058]
In ByteBuddy 1.11.1, it looks like `getPermittedSubclasses()`, an interface method on `TypeDescription`, was renamed to `getPermittedSubtypes()`.  Existing `TypeDescription` implementations "in the wild" will break.

Related to #1057 (or perhaps the same issue).

**Comment by raphw** [comment]
Similar to: https://github.com/raphw/byte-buddy/issues/1057
