### ISSUE TITLE
Problem with array-typed ClassDescs in JavaConstant.java leads to incorrect descriptor string somewhere

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#1059]
I apologize for the vague issue title; there's a lot going on here.

Consider:

https://github.com/raphw/byte-buddy/blob/77fbfb937d376260ac5400028c2942ac9f0f390d/byte-buddy-dep/src/main/java/net/bytebuddy/utility/JavaConstant.java#L292-L329

Within this range of code, there are I think ten (or so) instances of `net.bytebuddy.jar.asm.Type.getClassName()` being passed to `TypePool.describe()`.  When this class name is, for example, `java.lang.reflect.Type[]` (my particular arbitrary case), the lazy type description that gets created will not in fact be able to be resolved.

More specifically, consider this method when `name` is "`java.lang.reflect.Type[]`" (again, my arbitrary example, encountered during debugging):

https://github.com/raphw/byte-buddy/blob/77fbfb937d376260ac5400028c2942ac9f0f390d/byte-buddy-dep/src/main/java/net/bytebuddy/pool/TypePool.java#L507-L530

Specifically, at line 512 "`java.lang.reflect.Type[]`" will _not_ start with `[` because `name` in this case is not a descriptor string.

I don't know much more than this but I do know that this problem leads to a `ClassFormatError` if a ByteBuddy-generated type makes use of a constant generated in this manner.

I will add more details to this issue if I can find them.

**Comment by ljnelson** [comment]
So how, you may ask, did "`java.lang.reflect.Type[]`" end up as the name in question?  It's what is returned by `java.lang.reflect.Type.class.describeConstable().orElseThrow().arrayType().displayName()`.  I'm not familiar enough with the ByteBuddy dispatching pattern (for old VMs) to know how this got used, but maybe `java.lang.reflect.Type.class.describeConstable().orElseThrow().arrayType().descriptorString()` needs to be used instead?

**Comment by ljnelson** [comment]
I tried replacing `getClassName()` with `getDescriptor()` just quickly, but `TypePool::describe` fails in this case because the descriptor returned contains `/` characters.

**Comment by ljnelson** [comment]
See #1060.  This fixes the problem but may not be where you want to solve it; not sure.

**Comment by raphw** [comment]
You are right, of course. `TypePool` accepts the output of `java.lang.Class.getName()` and I would like it to stay consistent in this regard. For this reason, I need to add a check on the ASM `Type` and render a different output for arrays. I am doing the same already on two other uses but did not think of this in this new code.

I adjusted the problem on master. Can you try if everything works as expected now?

**Comment by ljnelson** [comment]
In building `master`, I get a test failure:
```
[ERROR] net.bytebuddy.utility.JavaConstantSimpleConstantDescriptionTest.testDynamic  Time elapsed: 0 s  <<< ERROR!
java.lang.StringIndexOutOfBoundsException: String index out of range: 18
	at net.bytebuddy.utility.JavaConstantSimpleConstantDescriptionTest.testDynamic(JavaConstantSimpleConstantDescriptionTest.java:81)
```

**Comment by raphw** [comment]
My bad, resolved the wrong value. Should work now.

**Comment by ljnelson** [comment]
Yes, this fixes this issue.  On to figuring out [the next one](https://stackoverflow.com/questions/67827844/elementmatchersistostring-fails-in-bytebuddy-1-11-1-when-tostring-is-not-def)!  Thanks for your work and time.

**Comment by ljnelson** [comment]
…ha, which I see you've already answered! You move quick!  I'll take a look at the change.

**Comment by raphw** [comment]
Fixed on master.
