### ISSUE TITLE
Add compatibility with Java 9 (JEP 223 + class file version 53)

### ISSUE THREAD

**Issue by don-vip** [raphw/byte-buddy#106]
Java 9 introduces two major changes that need to be implemented in `net.bytebuddy.ClassFileVersion`:

- New version schema (JEP 223): https://bugs.openjdk.java.net/browse/JDK-8061493
- Class file version 53: https://bugs.openjdk.java.net/browse/JDK-8148785

**Comment by don-vip** [comment]
Maybe some other tasks must be done by Oracle first: https://bugs.openjdk.java.net/browse/JDK-8148651

**Comment by raphw** [comment]
I added support for the new JDK 9 version string but I do now depend on the `jdk.Version` class which is supposed to be renamed in the future. As for the byte code level, Byte Buddy still treats Java 9 as Java 8 byte code as the byte code level was not yet updated in the JDK. This is always done rather late in the process.
