### ISSUE TITLE
`JavaModule#modify` disappeared in 1.11.1

### ISSUE THREAD

**Issue by bsideup** [raphw/byte-buddy#1063]
Hi! I was trying to update from 1.11.0 to 1.11.1 and got a compilation error because `JavaModule#modify` is missing.

Replacing it with `ClassInjector.UsingInstrumentation.redefineModule` did the trick, but I guess this regression wasn't intentional (unless it was a necessary evil. You can close this issue in that case :))

**Comment by raphw** [comment]
Yes and no, I should have made a new minor release, but I had to remove the method. Are you calling it directly? I did not really expect that to be used outside of BB, normally there's better high-level utilities.

I had to remove `Instrumentation` from several places as it would break Byte Buddy when jlink is used and the *java.instrument* module is not used. The `JavaModule` class could not be loaded in such a case.

**Comment by bsideup** [comment]
@raphw I do :D 
https://github.com/bsideup/jabel/blob/e501c48e52adc38c6ea107ebee56245fc3447f84/jabel-javac-plugin/src/main/java/com/github/bsideup/jabel/JabelCompilerPlugin.java#L107-L120

Is there a better API to do the same? Would appreciate a hint!

**Comment by raphw** [comment]
Yes, `net.bytebuddy.dynamic.loading.ClassInjector.UsingInstrumentation#redefineModule`.

**Comment by bsideup** [comment]
Ah, okay, that's exactly the one I am using now :) (as mentioned in the issue body)

Cool, thanks! 👍
