### ISSUE TITLE
ASM throws IllegalStateException while creating bytecode

### ISSUE THREAD

**Issue by mariusoe** [raphw/byte-buddy#1067]
Hi Rafael,

we're using ByteBuddy (version 1.11.2) in a custom Java agent which works great! Nevertheless, we have some problems during bytecode creation (instrumentation) of certain classes. These classes are proxy classes, generated by the JBoss Weld CDI "framework". In case we try to instrument the bytecode of these classes, an `IllegalStateException` is thrown by ASM during bytecode creation in the `DynamicType.Builder`s `make` method.

We use ByteBuddy to instrument and generate bytecode like following:

```
ClassFileLocator byteCodeClassFileLocator = ClassFileLocator.Simple.of(type.getName(), originalByteCode);
DynamicType.Builder<?> builder = new ByteBuddy().redefine(type, byteCodeClassFileLocator);

// bunch of advices are created here - just one as an example
builder = builder.visit(
        Advice.to(NonStaticMethodAdvice.class)
                .on(methodMatchers));
// ...

// "Compile" the builder to bytecode
DynamicType.Unloaded<?> instrumentedClass = builder.make();
```

We only use `OnMethodEnter` and `OnMethodExit` in our advices. As already mentioned, in some cases the following exception is thrown:
```
java.lang.IllegalStateException: null
	at net.bytebuddy.jar.asm.MethodWriter.visitFrame(MethodWriter.java:791)
	at net.bytebuddy.jar.asm.MethodVisitor.visitFrame(MethodVisitor.java:299)
	at net.bytebuddy.jar.asm.MethodVisitor.visitFrame(MethodVisitor.java:299)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$InitializationHandler$Appending.visitFrame(TypeWriter.java:4201)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2046)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1488)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:718)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:401)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3827)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:224)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:123)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3595)
       ....
```

The [ASM code where this exception is thrown](https://github.com/consulo/objectweb-asm/blob/abd1869f332166bdd858c6348d3e4a0cfc1f0e65/asm/src/main/java/org/objectweb/asm/MethodWriter.java#L791) is doing some check using an Opcode related to `A compressed frame with exactly the same locals as the previous frame and with an empty stack.`, according its docs. But I don't know what this is about.

Is this a problem of our target class or its bytecode, or is this a problem in Bytebuddy or how we are using it?

All the best,
Marius

**Comment by raphw** [comment]
Could you set a break point and provide the arguments to viaitFrame.

**Comment by mariusoe** [comment]
Hi @raphw 

> Could you set a break point and provide the arguments to visitFrame?

Yes, the arguments are the following:

- type: `0`
- numLocal: `0`
- local: `Object[0]`
- numStack: `0`
- stack: `Object[5]` - all elements are `null`

I also discovered that this error is also occuring when I'm not adding any advice at all. So just calling the following code is causing the same exception: `new ByteBuddy().redefine(type, byteCodeClassFileLocator).make()`

So I'm assuming that there is something wrong with the bytecode itself? When viewing the bytecode of the affected class in IntelliJ using its built-in decompiler, it shows some methods that define a throw-statement but without an exception.
![image](https://user-images.githubusercontent.com/1217782/122033567-f0b1ae00-cdd0-11eb-92e9-32c0c0f5e769.png)
I'm not sure if this is caused by the decompilation or if the bytecode itself is some kind of broken (or is this some Java feature which I don't know). Anyway, this is strange because that's the bytecode which is passed by the JVM into my class-transformer.

I'm checking whether I'm able to provide you some example bytecode.

**Comment by raphw** [comment]
The decompiler is not showing any frames, could you add a printout of javap? better even, the entire class file.

**Comment by mariusoe** [comment]
Here is one of the affected classes which leads to the described problem. I had to mask some parts of it but I ensured that it didn't affect the behavior.

Here it is: [sample_class.zip](https://github.com/raphw/byte-buddy/files/6655500/sample_class.zip)

**Comment by mariusoe** [comment]
In a first, local test, it looks like the problem is fixed, now.
I'll test it in the coming days (hopefully this week) on the real system, which is unfortunately not possible at the moment. I will give you feedback asap once I have been able to test it.

Thanks for the help and quick fix. In case this solves the problem, what is your release cycle? Do you already have any idea when you will release version 1.11.3?

**Comment by raphw** [comment]
Great, I am planning a realase rather soon, but I might wait for you to confirm.

By the way: you might already solve your issue by using *decorate* rather then *redefine*, if you only add wrappers, this should be sufficient.

**Comment by mariusoe** [comment]
Awesome! Thanks.

I'll have a look on the `decorate` method, that sounds interesting. But are there any limitations compared to `redefine` in case I'm only adding advices to the target methods and keep the original bytecode? I mean, you're writing in the documentation `A decoration does not allow for any standard transformations` - that sounds understandable to me, if the method is only wrapped.
But is a "decoration" still injected into the target class but just does not provide the ability to change its actual implementation? So, some kind of "lite redefinition" for wrapping methods? Because,  there is no difference in the resulting bytecode (`redefine` vs `decorate`) when I compare both methods.

**Comment by raphw** [comment]
Decoration is basically limited to wrappers like `Advice` which are used via `builder.visit`. You cannot define new methods or fields using it.

**Comment by mariusoe** [comment]
Hi @raphw 

your fix solved our problem. Thanks for the help and quick reaction :)
All the best
