### ISSUE TITLE
Listenings to invokes of methods in the classes in android

### ISSUE THREAD

**Issue by XomaDev** [raphw/byte-buddy#1068]
Is there any way that I can listen to all the invokes in the class?

```
public class Animal {

    public void animal() {
        System.out.println("Dog!");
    }

}
```

For example here I have a class. I am creating a new object of the class:

```
Animal animal = new Animal();
animal.animal();
```

I am calling the animal function. When the object is created, is it posible to know when it invokes with the methods and the return value...? I want to also listen to all the invokes of methods in classes.

**Comment by raphw** [comment]
Have a look into the `AgentBuilder` API which allows you to instrument code of any given type and method. There are several tutorials online that demonstrate how this is done.

**Comment by XomaDev** [comment]
Hello thanks for the reply. Is it possible to do everything within the code?

**Comment by raphw** [comment]
On a regular JVM, yes, by using an agent. In Android, you could only subclass `Animal`, if you are in control of the instantiations, but other than that, there is no option as Android does not support instrumentation.

**Comment by raphw** [comment]
I'm closing this issue, please get in touch if you have any further questions.
