### ISSUE TITLE
Cannot resolve type description when enhance class constructor twice

### ISSUE THREAD

**Issue by Yolo-Hao** [raphw/byte-buddy#1071]
Hi raphw, we're building a apm agent using bytebuddy. For some historical reasons, we'll have two agent using bytebuddy enhance the same class twice in develop env, and it'll throw exception like this`java.lang.IllegalStateException: Cannot resolve type description for redis.clients.jedis.Jedis$auxiliary$3rnvz8kR` when we enhance the constructor method twice, but not the other methods.

when enhance constructor, bytebuddy will generated some private method with "Jedis$auxiliary$3rnvz8kR" type param, eg:
![image](https://user-images.githubusercontent.com/5838480/122904585-10257980-d383-11eb-92d0-64ca8a28196d.png)

 and then, when the twice enhancement start, it won't find the "Jedis$auxiliary$3rnvz8kR" class file, causing the validation fail.

can you give me some advice? thanks!

**Comment by raphw** [comment]
You would need to register an `AgentBuilder.Listener` which registers such auxiliary types' byte code somewhere. It is provided on the `onTransform` method. You then need to provide this byte code to the next agent via `LocationStrategy`. Simply delegate to an existing strategy but provide a `ClassFileLocator` that also knows about the auxiliary types.

**Comment by Yolo-Hao** [comment]
@raphw thanks, i will try it!

**Comment by Yolo-Hao** [comment]
@raphw  Hi, raphw, it works by saving the bytecode in the first agent, and provider a `LocationStrategy` in the second agent like this:
```java
public class ApmClassFileLocationStrategy implements AgentBuilder.LocationStrategy {

    private final AgentBuilder.LocationStrategy defaultStrategy;

    private final String dir;

    public ApmClassFileLocationStrategy(AgentBuilder.LocationStrategy defaultStrategy, String dir) {
        this.defaultStrategy = defaultStrategy;
        this.dir = dir;
    }

    public static ApmClassFileLocationStrategy of(AgentBuilder.LocationStrategy defaultStrategy, String dir) {
        return new ApmClassFileLocationStrategy(defaultStrategy, dir);
    }

    @Override
    public ClassFileLocator classFileLocator(ClassLoader classLoader, JavaModule module) {
        ClassFileLocator folderLocator = new ClassFileLocator.ForFolder(new File(dir));
        return new ClassFileLocator.Compound(defaultStrategy.classFileLocator(classLoader, module), folderLocator);
    }

}
```

thanks a lot！
