### ISSUE TITLE
Encrypt Critical Class files and decrypt it with key

### ISSUE THREAD

**Issue by eix128** [raphw/byte-buddy#1073]
Hi , i want to block symbolic code execution and for license protection ,
I want to encrypt some methods and classes and ask user for license key.
That license key will be used as secret key to decrypt class files and some class methods.

Is it possible to make this with this library ?
I dont know where to start for this problem.

Thank you

**Comment by raphw** [comment]
The key would end up in the same JVM. Such protection can always be breached by the entity controlling the VM. Byte Buddy does not support such encryption and I recommend against using it.

**Comment by eix128** [comment]
Yes , it can be breached but when only person knows the license key!

**Comment by raphw** [comment]
The key will end up in the Java heap which can be easily dumped.

**Comment by eix128** [comment]
No , its not on heap its required input by the user.
That will enter into heap when user enters it.Without user knows , how its stored on heap ?

So you can crack veracrypt.Its password stored on heap.But when user knows and enters the password....

**Comment by raphw** [comment]
In this case, I would rather encrypt the entire jar and decrypt it before starting the application.

**Comment by eix128** [comment]
encrypting entire jar slows.
Maybe just method and class is better in some situations for performance reasons.
Also for preventing symbolic code execution prevention
