### ISSUE TITLE
How to create a class with an inner classes?

### ISSUE THREAD

**Issue by RinOrz** [raphw/byte-buddy#1077]
How should I create a class like the following code and load them for testing?
```java
class Foo {
    class Bar {}
    class Gav {
        class Nested {}
    }
}
```

If any code example would be appreciated!

**Comment by raphw** [comment]
Byte Buddy has a DSL where you can define inner and outer classes. While defining a class, you need to set `DynamicType.Builder#innerTypeOf` to define the top level class. And you can set `DynamicType.Builder#declaredTypes` to make the top-level class aware of its inner class. Simply define the classes as they should be formed and then pass each class's `TypeDescription` to the appropiate method. You can resolve a `TypeDescription` from the `DynamicType.Builder#toTypeDescription`. It's important to not rename the classes after doing so, the API is immutable.

The Java naming convention is `Foo$Gav$Nested` but it's not strictly required.

**Comment by RinOrz** [comment]
@raphw Can you provide a code example? In addition, I want to know how to output these classes to JAR, I found that it will only output OuterClass to JAR instead of InnerClasses

**Comment by raphw** [comment]
Here is an example, please make sure to define the inner class properties first and then set the outer type properties. Otherwise, the type definitions will be contradictory.

```java
package foo;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.test.utility.DebuggingWrapper;

import java.util.Arrays;

public class Bar {

    public static void main(String[] args) {
        ByteBuddy bb = new ByteBuddy();

        DynamicType.Builder<Object> outer = bb.subclass(Object.class).name("foo.Outer");
        DynamicType.Builder<Object> inner = bb.subclass(Object.class).name("foo.Outer$Inner");

        inner = inner.innerTypeOf(outer.toTypeDescription()).asMemberType();
        outer = outer.declaredTypes(inner.toTypeDescription());

        DynamicType.Loaded<Object> l = outer.make().include(inner.make()).load(null);

        System.out.println(l.getLoadedAuxiliaryTypes().values().iterator().next().getDeclaringClass());
        System.out.println(Arrays.toString(l.getLoaded().getDeclaredClasses()));
    }
}
```
