### ISSUE TITLE
How to delegate method calls of an existing class to its proxy (subclass) class 

### ISSUE THREAD

**Issue by vsaji** [raphw/byte-buddy#1078]
I have a requirement of dynamically applying the proxy object over the actual object in my project, Let me explain you in detail.
I need to provide a feature in my framework whereby the developers can provide the actual class and its proxies via an annotation.
Example
```java
@Proxies(
    {
       @Proxy(srcClass=SomeClass.class,proxyClass=SomeClassProxy.class)
       @Proxy(srcClass=DifferentClass.class,proxyClass=DifferentClassProxy.class)
    }
)
public class MyStarterClass(){
}
```
My framework needs to read this annotation and extract the metadata provided. Using bytebuddy, I need to intercept all method calls to srcClass to proxyClass. While intercepting, it will check a condition, if the condition is true, then only it requires to forward the calls to proxyClass.

I won't be able to use javaagent solution here as I will come to know the list of classes only after scanning the annotation.
The annotation scanning will be done as soon as it enters the main method.

Example SomeClass.class

```java

public class SomeClass{
      public void doOperation1(){
             System.out.println("SomeClass.doOperation1");
      }

      public List<String> fetchOperation(){
         return Arrays.asList("KJ2323","DK34556");
      }
}
```
Example SomeClassProxy.class

```java

public class SomeClassProxy extends SomeClass{
      public void doOperation1(){
             System.out.println("SomeClassProxy .doOperation1");
      }

      public List<String> fetchOperation(){
         return Arrays.asList("ZSX2323","WWRF34556");
      }
}
```
SomeClass can be created or used anywhere in the application, so it must be modified as below before it is being used.

```java

public class SomeClass{
  SomeClassProxy proxy;

      public void doOperation1(){
             if(ConditionChecker.check()){
                   proxy.doOperation1();
                   return;
             }
             System.out.println("SomeClass.doOperation1");
      }

      public List<String> fetchOperation(){
            if(ConditionChecker.check()){
                   return proxy.fetchOperation();
             }
         return Arrays.asList("KJ2323","DK34556");
      }
}
```
Can you please advise me how to achieve this behavior using ByteBuddy ? if you can provide with some sample code would be much appreciated. Alternatively, you can point me to some sample too.

Thanks

**Comment by vsaji** [comment]
I could implement the solution the way I wanted to by mixing javassit and byte-buddy. I could achieve the following things via this implementation

- Do instrumentation without attaching -javaagent in the command line

- I could include multiple agents under a single jar and call them as required from the main method.

- I could change the behavior of a method and add new fields at the class level.

Though there hasn't been any response for my question, it was nice experience to learn various aspects of this topic and reaching to a point where I could implement the solution as requested

**Comment by raphw** [comment]
I already answered you on StackOverflow. You should look into `MethodDelegation` and its ability to invoke the original method on another object.
