### ISSUE TITLE
Append bytebuddy jar file to classpath inside premain method

### ISSUE THREAD

**Issue by amar1019** [raphw/byte-buddy#1082]
Right now, i am adding bytebuddy jar file to the classpath manually inside JAVA_TOOL_OPTIONS. I am thinking to attach my java agent to already running JVM. For that, i will need to add bytebuddy jar file to the classpath inside agentmain method. But for now, i am trying to add it in premain method. 

              `try {
			inst.appendToBootstrapClassLoaderSearch(new JarFile("/xxxxxx/byte-buddy-1.10.6.jar"));
                        //inst.appendToSystemClassLoaderSearch(new JarFile("/xxxxxx/byte-buddy-1.10.6.jar"));
		} catch (IOException e) {
			e.printStackTrace();
		}`

I tried both ways. I get ClassNotFound Exception

java.lang.NoClassDefFoundError: net/bytebuddy/matcher/ElementMatcher
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethod(Class.java:2128)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:327)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.matcher.ElementMatcher
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

**How can i do it ?**

**Comment by raphw** [comment]
The premain class of the manifest file is loaded by the JVM via reflection. If this reflection discovers types (here as part of a method signature) that are part of Byte Buddy, your attachment code is run before you can append any jar file.

To avoid this, make sure that your premain class really only contains the code that you included and then dispatches the "actual" premain code to another, separate utility class.

**Comment by amar1019** [comment]
@raphw This worked. but i ran into classloading issues after that. I think this approach (using appendToSystemClassLoaderSearch) is not as flexible as mentioning the jar file directly on the classpath.

**Comment by raphw** [comment]
You won't include resources, just classes. Ideally, you shade Byte Buddy into your agent jar.

**Comment by amar1019** [comment]
Bytebuddy is loading fine. I am getting **java.lang.ClassNotFoundException: javax.servlet.ServletOutputStream** when i try to instrument servlet doFilter method. Its happening on the line where i am executing **httpServletRequest.getRequestURI()**.

**Comment by amar1019** [comment]
I have used MANIFEST file of agent jar file for specifying classpath. Everything is working fine when i attach it to the Vm before start using -javaagent:agent.jar. But when i try to attach it for a running JVM, it is failing. 

`new AgentBuilder.Default().with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
				.with(new AgentBuilder.Listener.Filtering(
						new StringMatcher("java.io.FileInputStream", StringMatcher.Mode.EQUALS_FULLY),
						AgentBuilder.Listener.StreamWriting.toSystemOut()))
				.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
				.with(AgentBuilder.TypeStrategy.Default.REDEFINE)
				.ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
				.type(ElementMatchers.named("java.io.FileInputStream"))
				.transform(new Transformer.ForAdvice().include(ProbeAgent.class.getClassLoader()).advice(
						ElementMatchers.isConstructor().and(ElementMatchers.takesArguments(File.class)),
						"com.test.FileAccessAdvice"))
				.installOn(inst);`

[Byte Buddy] DISCOVERY java.io.FileInputStream [null, null, loaded=true]
[Byte Buddy] ERROR java.io.FileInputStream [null, null, loaded=true]
java.lang.IllegalStateException: Cannot resolve type description for ccom.test.FileAccessAdvice

@raphw Any suggestions

**Comment by raphw** [comment]
The problem is that you only attach classes when you use this API, but not resources. For advice, you need to resolve a class file what is not possible with these approaches as a class file is a resource.

You need to either include the advice in the original jar or include all dependencies and load the agent from a separate URLClassLoader
