### ISSUE TITLE
Inconsistent return of getInternalName() methods

### ISSUE THREAD

**Issue by cataphract** [raphw/byte-buddy#1083]
I believe `new TypeDescription.ForLoadedType(boolean.class).getInternalName()` should return `Z` rather than `boolean`; the javadoc of `getInternalName()` indicates it returns "[t]he internal internalName of this byte code element as used within the Java class file format."

This value differs from that of the asm library's `Type` class; this mismatch potentially leading to a bug:

```groovy
@Grapes(@Grab(group='net.bytebuddy', module='byte-buddy', version='1.11.8'))
import net.bytebuddy.description.type.TypeDescription
import net.bytebuddy.jar.asm.Type

println Type.getType('Z').is(Type.BOOLEAN_TYPE)
println Type.BOOLEAN_TYPE.internalName
println new TypeDescription.ForLoadedType(boolean.class).internalName
```

results in:
<pre>
true
Z
boolean
</pre>

**Comment by raphw** [comment]
Technically speaking, primitive types do not define an internal name. It's indeed unfortunate that ASM and Byte Buddy return different values here (Byte Buddy returns the reflection name, ASM returns the descriptor), but I like my choice better to be honest.

You can define a class in the default package called `Z`. This class's internal name would be `Z` (its descriptor would be *LZ;*). This way, ASM is ambiguous. Byte Buddy returns the reflection name of the primitive type which is a keyword, thus no type in the default package can be named `boolean` and have this internal name, the return value is not ambiguous.
