### ISSUE TITLE
Names are not available via reflection for a generated record's constructor parameters

### ISSUE THREAD

**Issue by wilkinsona** [raphw/byte-buddy#1084]
I'm trying to generate a record class with ByteBuddy 1.11.8 in such a way that parameter names are available for its constructor parameters. Here's a test that hopefully illustrates what I'm trying to do:

```java
Class<?> someRecord = new ByteBuddy(ClassFileVersion.JAVA_V16)
    .makeRecord()
        .name("example.SomeRecord")
        .defineRecordComponent("someString", String.class)
        .defineRecordComponent("someInteger", Integer.class)
    .make().load(getClass().getClassLoader()).getLoaded();
assertThat(someRecord.getConstructor(String.class, Integer.class).getParameters())
    .extracting(Parameter::getName).containsExactly("someString", "someInteger");
```

It fails as the parameters' names are `arg0` and `arg1`.

In an attempt to verify that I haven't overlooked something obvious, I tried something similar with an interface:

```java
Class<?> someInterface = new ByteBuddy(ClassFileVersion.JAVA_V16)
    .makeInterface()
        .name("example.SomeInterface")
        .defineMethod("someMethod", void.class, Modifier.PUBLIC)
            .withParameter(String.class, "someString", 0)
            .withParameter(Integer.class, "someInteger", 0)
            .withoutCode()
    .make().load(getClass().getClassLoader()).getLoaded();
assertThat(someInterface.getMethod("someMethod", String.class).getParameters())
    .extracting(Parameter::getName).containsExactly("someString", "someInteger");
```

This test passes which makes me suspect that the lack of parameter names in the record case may be a bug. I'm using AdoptOpenJDK-16.0.1+9.

**Comment by raphw** [comment]
Good catch, I did not retain the name within the *Parameters* attribute of the class file. I was not aware that *javac* includes the parameter name for the constructor by default, but this is of course a good idea. This is now fixed on master and will be part of the next release. Is this an urgent issue to you?

**Comment by wilkinsona** [comment]
Thanks for the super-quick fix, @raphw. This isn't particularly urgent. The background is that I was trying to add a test to Spring Boot for using a feature with records without requiring Java 16. I got pretty far without the parameter names being available but thought it worth reporting their absence regardless.

**Comment by raphw** [comment]
Part of today's release.
