### ISSUE TITLE
"protected" fields are not accessible when instrumenting a sub-class

### ISSUE THREAD

**Issue by avshenuk** [raphw/byte-buddy#1086]
```
class MyClass {
   protected String foo;
}

new ByteBuddy().subclass(MyClass.class, ConstructorStrategy.Default.NO_CONSTRUCTORS)
            .name("Foo")
            .defineConstructor(Visibility.PUBLIC)
            .intercept(SuperMethodCall.INSTANCE.andThen(MethodCall.construct(String.class.getDeclaredConstructor()).setsField(named("foo"))))
            .make()
            .load(ClassLoader.getSystemClassLoader())
            .getLoaded();
```

results in 
```
java.lang.IllegalStateException: name(equals(foo)) does not locate any accessible fields for class Foo
	at net.bytebuddy.implementation.MethodCall$TerminationHandler$FieldSetting$Implicit.make(MethodCall.java:3182)
```

Seems, like both `Explicit` and `Implicit` `TerminationHandler`s are checking for "accessibility" rather than "visibility". 
Is that the correct behavior? I would guess there should be a difference between when you're accessing a field from within the instrumented type vs on some external field of that type?

And thank you for such an awesome library and all your efforts keeping it alive for all these years!

**Comment by raphw** [comment]
Good catch. Since the field is always set on the own instance, it is possible to set protected fields even if they are declared by a super class. This is fixed on master now.
