### ISSUE TITLE
"protected" methods are not accessible when instrumenting a sub-class

### ISSUE THREAD

**Issue by avshenuk** [raphw/byte-buddy#1087]
Similar to https://github.com/raphw/byte-buddy/issues/1086

```
package bar;
class MyClass {
   protected String foo() {
   }
}

DynamicType.Builder<?> typeBuilder = new ByteBuddy().subclass(MyClass.class)
            .name("foo.Foo");

typeBuilder.invokable(isTypeInitializer())
            .intercept(MethodCall.invoke(named("foo")).onField("instance"))
            .defineField("instance", typeBuilder.toTypeDescription(), Visibility.PUBLIC, Ownership.STATIC)
            .make()
            .load(ClassLoader.getSystemClassLoader())
            .getLoaded();
```
results in
```
java.lang.IllegalStateException: Cannot invoke protected java.lang.String bar.MyClass.foo() virtually
	at net.bytebuddy.implementation.MethodCall$MethodInvoker$ForVirtualInvocation$WithImplicitType.toStackManipulation(MethodCall.java:2819)
```
since `MethodInvoker.ForVirtualInvocation.WithImplicitType` is checking for "accessibility" as well. 
Supposedly, it should call `isInvokableOn` instead.

Verified that according to Java rules, it's allowed to access protected members on the instances of the sub-class from within that same class.
So the code like this:
```
package foo;
class Foo extends MyClass {
    public static Foo instance;
    static {
        instance.foo();
    }
}
```
does indeed compile.

**Comment by raphw** [comment]
It does not compile for me and would surprise me if it did. This way, one could "break into" system classes such as `ClassLoader` and define classes in foreign instances what would break encapsulation.

How did you compile this?

**Comment by avshenuk** [comment]
But we're accessing the member through an instance of our own class (the one we declared) so we're not actually breaking the encapsulation here?
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/4578760/127451628-78c27eaa-4e7f-4a8f-923d-9d06b90f99cb.png">

You perhaps referred to the case when we're trying to access the member through an instance of the super-class instead? Like this:
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/4578760/127451755-73816ad3-20e5-4f45-8b1a-6f6bd3022584.png">

**Comment by raphw** [comment]
Ah, here you are using the same package with both classes, then it works via package scope.

**Comment by avshenuk** [comment]
What do you mean I'm using the same package? :) One is `analytics.foo`, the other one is `analytics.bar`.

**Comment by raphw** [comment]
Indeed. Unfortunately, Byte Buddy only considers the method declaration at this point, not the type of the method. I would need to include such a refinement in a future release. A workaround would be to explicitly implement "foo" in the subclass and invoke the super method from it.

**Comment by avshenuk** [comment]
Right, thank you for looking into it.
