### ISSUE TITLE
cannot write to constant value How to change final args?

### ISSUE THREAD

**Issue by Holmesus** [raphw/byte-buddy#1088]
Hello.I'm working for a java agent lib where i need to change some arguments by modify bytecode.I use "new AgentBuilder.Transformer.ForAdvice().advice" to do that ,and it works well.But some third party lib's method has final arguments,when i use advice ,it throws exception.
How can id change final args?

**Comment by raphw** [comment]
What do you mean by *final argument*? A parameter? This should not make a difference as final parameters are not considered in bytecode.

**Comment by Holmesus** [comment]
Thanks a lot! I made a mistake..I use @Advice.Origin to get qualified method name,and use substring() to get only the method name.When i delete the code "origin = orgin.substring(..)" ,it doesn't throw exception now.

**Comment by Holmesus** [comment]
done
