### ISSUE TITLE
java.lang.IllegalStateException: Registration of auxiliary types was disabled: net.bytebuddy.implementation.auxiliary.MethodCallProxy@39036fde

### ISSUE THREAD

**Issue by goudai** [raphw/byte-buddy#1089]
java.lang.IllegalStateException: Registration of auxiliary types was disabled: net.bytebuddy.implementation.auxiliary.MethodCallProxy@39036fde

**Comment by raphw** [comment]
You need to register an `AgentBuilder.InjectionStrategy` in the `AgentBuilder` which is what I assume that you are using.
