### ISSUE TITLE
how to use byte buddy instrument spring bean?

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#109]
i run javaagent application with spring boot
but has exception

> java.lang.IllegalStateException:
>  Cannot resolve type description for com.dragon.study.bytebuddy.httpclient.HttpClientInterceptor
>     at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:149)
>     at com.dragon.study.bytebuddy.httpclient.HttpClientTransformer.transform(HttpClientTransformer.java:34)
>     at net.bytebuddy.agent.builder.AgentBuilder$Transformer$Compound.transform(AgentBuilder.java:549)
>     at net.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:4236)
>     at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:4536)
>     at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
>     at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
>     at java.lang.ClassLoader.defineClass1(Native Method)
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>     at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>     at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>     at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
>     at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>     at com.dragon.study.bytebuddy.timer.TimerPerson.httpClientTest(TimerPerson.java:29)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
>     at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
>     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
>     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)

and i find my MANIFEST.MF file is

> Manifest-Version: 1.0
> Archiver-Version: Plexus Archiver
> Built-By: dragon
> Start-Class: com.dragon.study.bytebuddy.Application
> Spring-Boot-Version: 1.3.3.RELEASE
> Created-By: Apache Maven 3.2.1
> Build-Jdk: 1.8.0_73
> Main-Class: org.springframework.boot.loader.JarLauncher

how can i slove this problem ?

thanks

**Comment by raphw** [comment]
As you closed this ticket, did you manage to resolve this issue by yourself?

**Comment by dragontree101** [comment]
i slove this problem, because in springboot exclude javaagent
so i add myagent into springboot classloader by reflect, 
` 
private static Method ADD_URL;
  private static Set<URL> URL_SET = new HashSet<>();

  static {
    try {
      ADD_URL = URLClassLoader.class.getDeclaredMethod("addURL", URL.class);
      ADD_URL.setAccessible(true);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public boolean injectToURLClassLoader(URL[] urls, URLClassLoader classLoader)
      throws IllegalArgumentException, IllegalAccessException, InvocationTargetException, ClassNotFoundException {
    if (urls != null) {
      for (URL url : urls) {
        if (!URL_SET.contains(url)) {
          ADD_URL.invoke(classLoader, url);
          URL_SET.add(url);
          return true;
        }
      }
    }
    return false;
  }
`

and i use 
`builder.method(...)..intercept(...)` can works

but， i want to update to byte buddy 1.3.19 and use advice annotation to refactor my code
`builder.visit(Advice.to(....).on(.....))`;

and has error
`
onError:org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher
java.lang.NoClassDefFoundError: javax/ws/rs/core/Response
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at net.bytebuddy.description.method.MethodList$ForLoadedType.<init>(MethodList.java:90)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.getDeclaredMethods(TypeDescription.java:7414)
	at net.bytebuddy.asm.Advice.to(Advice.java:227)
	at net.bytebuddy.asm.Advice.to(Advice.java:211)
....
` 

i don't know different from `builder.method(...)..intercept(...)` bewteen `builder.visit(Advice.to(....).on(.....))`

i guess when i use  `builder.method(...)..intercept(...)`  springboot's classloader not load this class,

now i doesn't slove this problem again
