### ISSUE TITLE
Hello, I want to use MethodDelegation to intercept java.util.concurrent.ThreadPoolExecutor. I don’t want to use advice to intercept, because advice can only use static methods, which is very unfriendly to me.

### ISSUE THREAD

**Issue by goudai** [raphw/byte-buddy#1091]
Hello, I want to use MethodDelegation to intercept `java.util.concurrent.ThreadPoolExecutor`. I don’t want to use advice to intercept, because advice can only use static methods, which is very unfriendly to me.

**Comment by raphw** [comment]
Advice is merely a template, you would need to inject any state by either:

- binding a custom annotation to a given value via `Advice.withCustomBinding()`.
- injecting a dispatcher into the boot loader via `Instrumentation` and then read the state from this dispatcher.

**Comment by goudai** [comment]
How to use advice to enhance, pass in an `instance` instead of a `class`。
Since advice requires that the annotated method is static, polymorphism cannot be used, which leads me to do a lot of extra work for the class enhancement of the java package instead of just an `@RuntimeType` annotation.

**Comment by goudai** [comment]
If I want to use @RuntimeType in the form of enhanced tripartite package to enhance java package, what should I do? I really like to use RuntimeType. Advice is really uncomfortable.

**Comment by goudai** [comment]
In order to adapt to the abstract polymorphism of Advice, I have to use cumbersome and complex dynamic class generation, dynamically generating countless classes with @MethodExit, @MethodEnter static methods. I think this is stupid. Is there a better one? I am grateful for suggestions.

**Comment by raphw** [comment]
It needs to be static as the code is inlined, this only works if the method does not represent an instance.

Instead of RuntimeType, aet typing = DYNAMIC as property on the Advice.Returned annotation. If that's not what you're out after, please deschrive your issue in more detail, I can surely recommend a different approach.

**Comment by goudai** [comment]
@raphw  I want to use this method to intercept the constructor of java.util.concurrent.ThreadPoolExecutor, how can I modify this code. see ：https://github.com/raphw/byte-buddy/issues/797 

```java
public class BootstrapAgent {

    public static void main(String[] args) throws Exception {
        premain(null, ByteBuddyAgent.install());
        final ExecutorService executorService = Executors.newCachedThreadPool();
      
    }

    public static void premain(String arg, Instrumentation instrumentation) throws Exception {
        File temp = Files.createTempDirectory("tmp").toFile();
        ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation)
                .inject(Collections.singletonMap(
                        new TypeDescription.ForLoadedType(GeneralInterceptor.class),
                        ClassFileLocator.ForClassLoader.read(GeneralInterceptor.class)));

        String interceptor = "GeneralInterceptor";
        ClassFileLocator locator = ClassFileLocator.ForClassLoader.ofSystemLoader();
        TypePool pool = TypePool.Default.of(locator);
        final TypeDescription target = pool.describe(interceptor).resolve();

//        File temp = Files.createTempDirectory("tmp").toFile();
        ClassInjector.UsingInstrumentation
                .of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation)
                .injectRaw(Collections.singletonMap(interceptor, locator.locate(interceptor).resolve()));

        new AgentBuilder.Default()
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
                .with(new AgentBuilder.InjectionStrategy.UsingInstrumentation(instrumentation, temp))
                .type(ElementMatchers.nameEndsWith("java.util.concurrent.ThreadPoolExecutor"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
                        return builder.defineField("delegator", target, Ownership.STATIC, Visibility.PRIVATE)
                                .initializer(new LoadedTypeInitializer() {
                                    @Override
                                    public void onLoad(Class<?> type) {
                                        try {
                                            Field field = type.getDeclaredField("delegator");
                                            field.setAccessible(true);
                                            field.set(null, Class.forName(interceptor, false, null).getConstructor().newInstance());
                                        } catch (Exception e) {
                                            throw new RuntimeException(e);
                                        }
                                    }

                                    @Override
                                    public boolean isAlive() {
                                        return true;
                                    }
                                })
                                .method(ElementMatchers.isConstructor())
                                .intercept(MethodDelegation.toField("delegator"));
                    }
                })
                .installOn(instrumentation);
    }

}

public class GeneralInterceptor {

    @RuntimeType
    public Object intercept(@AllArguments Object[] allArguments,
                            @Origin Method method, @SuperCall Callable<?> callable) throws Exception {

        System.out.println("===============================intercept");
        return callable.call();
    }
}
````

**Comment by raphw** [comment]
As I wrote in my other answer, intercepting constructors without using advice is a bit tricky. I'd use advice and rather inject some sort of dispatching logic to the bootstrap loader. Put everything you need in your advice code into this loader and then access these objects from you advice via this dispatcher.

**Comment by shixiaoxianga** [comment]
> 

Hello, has this code solved the problem？

**Comment by shixiaoxianga** [comment]
> @raphw I want to use this method to intercept the constructor of java.util.concurrent.ThreadPoolExecutor, how can I modify this code. see ：#797
> 
> ```java
> public class BootstrapAgent {
> 
>     public static void main(String[] args) throws Exception {
>         premain(null, ByteBuddyAgent.install());
>         final ExecutorService executorService = Executors.newCachedThreadPool();
>       
>     }
> 
>     public static void premain(String arg, Instrumentation instrumentation) throws Exception {
>         File temp = Files.createTempDirectory("tmp").toFile();
>         ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation)
>                 .inject(Collections.singletonMap(
>                         new TypeDescription.ForLoadedType(GeneralInterceptor.class),
>                         ClassFileLocator.ForClassLoader.read(GeneralInterceptor.class)));
> 
>         String interceptor = "GeneralInterceptor";
>         ClassFileLocator locator = ClassFileLocator.ForClassLoader.ofSystemLoader();
>         TypePool pool = TypePool.Default.of(locator);
>         final TypeDescription target = pool.describe(interceptor).resolve();
> 
> //        File temp = Files.createTempDirectory("tmp").toFile();
>         ClassInjector.UsingInstrumentation
>                 .of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation)
>                 .injectRaw(Collections.singletonMap(interceptor, locator.locate(interceptor).resolve()));
> 
>         new AgentBuilder.Default()
>                 .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
>                 .with(new AgentBuilder.InjectionStrategy.UsingInstrumentation(instrumentation, temp))
>                 .type(ElementMatchers.nameEndsWith("java.util.concurrent.ThreadPoolExecutor"))
>                 .transform(new AgentBuilder.Transformer() {
>                     @Override
>                     public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
>                         return builder.defineField("delegator", target, Ownership.STATIC, Visibility.PRIVATE)
>                                 .initializer(new LoadedTypeInitializer() {
>                                     @Override
>                                     public void onLoad(Class<?> type) {
>                                         try {
>                                             Field field = type.getDeclaredField("delegator");
>                                             field.setAccessible(true);
>                                             field.set(null, Class.forName(interceptor, false, null).getConstructor().newInstance());
>                                         } catch (Exception e) {
>                                             throw new RuntimeException(e);
>                                         }
>                                     }
> 
>                                     @Override
>                                     public boolean isAlive() {
>                                         return true;
>                                     }
>                                 })
>                                  // Interception constructor not work
>                                 // .method(ElementMatchers.named("runWorker")) is work
>                                 .method(ElementMatchers.isConstructor())
>                                 .intercept(MethodDelegation.toField("delegator"));
>                     }
>                 })
>                 .installOn(instrumentation);
>     }
> 
> }
> 
> public class GeneralInterceptor {
> 
>     @RuntimeType
>     public Object intercept(@AllArguments Object[] allArguments,
>                             @Origin Method method, @SuperCall Callable<?> callable) throws Exception {
> 
>         System.out.println("===============================intercept");
>         return callable.call();
>     }
> }
> ```

Hello, has this code solved the problem？
