### ISSUE TITLE
High latency for method call transfer from Advice

### ISSUE THREAD

**Issue by ananthvanchip** [raphw/byte-buddy#1092]
Hi,
We have used Bytebuddy to add custom instrumentation to our code. We noticed that when we call a static method from within the Advice, the call's latency is sometimes around 100ms or more. This is even if the method has no code within it and it's an empty call. We also added instrumentation to check and merely calling the method is taking time. 

Example.
```
    @Advice.OnMethodEnter
    public static long enter(@Advice.Origin Method method, @Advice.AllArguments Object[] args) {
        long startTime = System.nanoTime();
        TestClass.executeSimple(method, args, startTime);
        System.out.println("Total time:" + (System.nanoTime() - startTime));
    }

........

public class TestClass {
    public static void executeSimple(Method method, Object[] args, long startTime) {
        System.out.println("Method enter time:" + (System.nanoTime() - startTime));
        //Write some simple execution with method and args.
    }
}
```

Time time printed by **`Method enter time`** sometimes goes in 10s or 100s of milliseconds. We do not see it in any other method calls in our application but specifically the ones which are called from the Advice. While this is not consistent, it is definitely prevalent. 

I would like to understand why this happens and some insights on this.

**Comment by raphw** [comment]
That's curious, but likely a measuring error. Byte Buddy only changes the byte code, but this change causes the VM to deoptimize where code will be run through the interpreter after, until recompiled. There's no special treatment of instrumented code, this code should be as fast as if it was written as such once compiled.

Have you aligned this with the compiler log?

**Comment by ananthvanchip** [comment]
>There's no special treatment of instrumented code, this code should be as fast as if it was written as such once compiled.

I did not understand the "once compiled" part of this statement. Is there anything specific we would need to do? I merely add the advice as a part of the `AgentBuiler`.


>Have you aligned this with the compiler log?

How do I check this?

**Comment by ananthvanchip** [comment]
We noticed one more thing is we added an object to be passed to the method using StackManipulation. 

```
       return new Advice.OffsetMapping() {
            @Override
            public Target resolve(TypeDescription instrumentedType, MethodDescription instrumentedMethod, Assigner assigner, Advice.ArgumentHandler argumentHandler, Sort sort) {
                return new Target.ForStackManipulation(SerializedConstant.of(getMetricValue(instrumentedMethod)));
            }
        };

```
........
`getMetricValue` return an ArrayList<Objects>. In the advice onEnter method, I added this param using a custom annotation. If I try to read the param within the Advice code, the time to read it is also sometimes in the order of 10s or 100s of ms. This is consistent.

For this reason, we removed passing this parameter completely. This is expected too?

**Comment by raphw** [comment]
In this case, you deserialize a value on every call, this is rather expensive. The same is true for reading a Method object via Origin. Those are constructed upon each request. It's better to use true constants such as String values and to process them outside a method if you want to improve performance here.

**Comment by ananthvanchip** [comment]
Ok. But if I need some parts of the MethodObject to perform the instrumentation, how can I go about doing it? eg. I want to know the methodName.

> There's no special treatment of instrumented code, this code should be as fast as if it was written as such once compiled.
I did not understand the "once compiled" part of this statement. Is there anything specific we would need to do? I merely add the advice as a part of the AgentBuiler.

> Have you aligned this with the compiler log?
How do I check this?

**Comment by raphw** [comment]
Have a look at the javadoc of the Origin annotation which can be placed on a string and accepts a parameter for reading the name of the method.

The JVM can omits compiler events (please check on Google). You'd need to see when your method is JITed and only consider time after this.

**Comment by ananthvanchip** [comment]
Thanks for the support. This solved our problem.
