### ISSUE TITLE
MethodGraph throws NPE when compiling bytecode

### ISSUE THREAD

**Issue by mariusoe** [raphw/byte-buddy#1095]
Hi @raphw 

we're using ByteBuddy to decorate specific methods of certain classes using the `decorate` method.
When doing the following call `new ByteBuddy().decorate(proxyClass).make();` - so, without adding anything to the target class - the following exception occurs:

```
java.lang.NullPointerException
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:572)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:465)
	at net.bytebuddy.dynamic.scaffold.inline.DecoratingDynamicTypeBuilder.make(DecoratingDynamicTypeBuilder.java:495)
	at net.bytebuddy.dynamic.scaffold.inline.DecoratingDynamicTypeBuilder.make(DecoratingDynamicTypeBuilder.java:485)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3658)
```

When looking into the method throwing the exception (`net.bytebuddy.dynamic.scaffold.MethodGraph.Compiler.Default#compile`), it tries to load an entry from a hashmap but receives `null`, leading to the exception because this object is used for another call: `snapshots.get(interfaceType).asGraph(merger)`.

But, when we're looking into the current state using a debugger, the element should be existing: 
![image](https://user-images.githubusercontent.com/1217782/129568814-ae283f19-0063-4337-84e5-193f9a43ce95.png)

I've attached a Gradle/IntelliJ sample project for reproducing this error. The error occurs when decorating the class `Programs$ProxyFor_3181456282201357971.class`. Its bytecode is located in the `example` directory. 

[sample-project.zip](https://github.com/raphw/byte-buddy/files/6992574/sample-project.zip)

**Comment by raphw** [comment]
I just added an explicit check to avoid the null pointer as this can indeed happen with inconsistent class hierarchies. This is the result of divergent interfaces where the generic hierarchy is not resulting in the same types. A type is part of the same hierarchy in two different generic shapes so to speak, what is not legal in Java. Is this also a result of your code generator?

When decorating, you can use a simplifies method graph compiler `MethodGraph.Compiler.ForDeclaredMethods.INSTANCE` which does not resolve the hierarchy but only methods of the instrumented class what is normally a meaningful combination when using *decoration*.

**Comment by mariusoe** [comment]
Thanks for the explenation and checking in on this.

What are the disadvantages of using the `ForDeclaredMethods` method graph instead of the default one? Is there any or does this have no implications when decorating methods?

**Comment by raphw** [comment]
You would not be notified of the hierarchy of a method, but for your use case, that's irrelevant. Using the alternative strategy likely even boosts performance.

**Comment by mariusoe** [comment]
Thanks @raphw for taking the time for this issue.

We're using the `decorate`functionallity in combination with the `ForDeclaredMethods` method graph, now, which solves the mentioned problems.
