### ISSUE TITLE
Overwriting method with MethodDelegation silently ignored when applied from ByteBuddy agent

### ISSUE THREAD

**Issue by perlun** [raphw/byte-buddy#1097]
### My use case

I am looking into using ByteBuddy for weaving in some extra logic in one of our methods related to performing DB calls. Since the method is called very often, and the extra logic involves a `ConcurrentHashMap` being accessed (and in the worst case, written to), we want to avoid doing this in the "real" production code.

Instead, we are trying to create a dynamic type which _only_ gets used when we run our integration tests. We use this by utilizing the `@BeforeSuite` annotation in `testng`, to let us install the ByteBuddy Agent and our transformations at an early-enough stage.

The class we are trying to replace is `DatabaseMediator` in the example below.

### What works

```java
        ByteBuddyAgent.install();

        new AgentBuilder.Default()
                .ignore( none() )
                .with( AgentBuilder.InitializationStrategy.NoOp.INSTANCE )
                .with( AgentBuilder.TypeStrategy.Default.REBASE )
                .with( AgentBuilder.RedefinitionStrategy.REDEFINITION )
                .type( named( DatabaseMediator.class.getName() ) ).transform( new AgentBuilder.Transformer() {
            @Override
            public DynamicType.Builder<?> transform( DynamicType.Builder<?> builder, TypeDescription typeDescription, lassLoader classLoader, JavaModule javaModule ) {
                return new ByteBuddy()
                        .redefine( DatabaseMediator.class )
                        .method( named( "getQuery" ) )
                        .intercept( FixedValue.value( "OVERWRITTEN VALUE BY BYTEBUDDY!" ) );
            }
        } )
                .installOnByteBuddyAgent();
```

The approach above overwrites our `private String getQuery( String queryId )` method with a new dummy method, returning the fixed string above. When running this, all DB queries fail since they try to execute `OVERWRITTEN VALUE BY BYTEBUDDY!` as an SQL query.

Unfortunately though, this is not fully enough for our use case. :wink:

### What does not work

This is closer to what we actually need:

```java
    @BeforeSuite
    public void beforeSuite() {
        Builder<DatabaseMediator> databaseMediatorBuilder = new ByteBuddy()
                .rebase( DatabaseMediator.class )
                .method( named( "getQuery" ) )
                .intercept( MethodDelegation.to( SeenQueriesInterceptor.class ) );

        // Added to avoid simple errors in the definition (will be silently ignored by `ByteBuddyAgent`)
        databaseMediatorBuilder.make();

        ByteBuddyAgent.install();

        new AgentBuilder.Default()
                .ignore( none() )
                .with( NoOp.INSTANCE )
                .with( AgentBuilder.TypeStrategy.Default.REDEFINE )
                .with( AgentBuilder.RedefinitionStrategy.REDEFINITION )
                .type( named( DatabaseMediator.class.getName() ) ).transform( new Transformer() {
            @Override
            public Builder<?> transform( Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule ) {
                return databaseMediatorBuilder;
            }
        } )
                .installOnByteBuddyAgent();
    }
```

The `SeenQueriesInterceptor` looks like this:

```java
    public static class SeenQueriesInterceptor {

        @RuntimeType
        public static Object intercept( @SuperCall Callable<?> zuper, @AllArguments Object[] args ) throws Exception {
            System.out.println( "Hello world from method interceptor" );
            return "foo";
        }
    }
```

Unfortunately, whenever I install the transformation above, the transformation is completely ignored and no exceptions are thrown. The original `getQuery()` method is executed instead.

### Things tested thus far

Apart from the `@BeforeSuite` example above, I've also tried calling my interceptor from a simpler example like this (note, no ByteBuddy Agent involved):

```java
    public static class Foo {
        public String getQuery( String id ) {
            return "value from Foo";
        }
    }

    @BeforeSuite
    public void beforeSuite() throws Exception {
        DynamicType.Loaded<Foo> loaded = new ByteBuddy()
                .subclass( Foo.class )
                .method( isDeclaredBy( Foo.class ) )
                .intercept( MethodDelegation.to( SeenQueriesInterceptor.class ) )
                .make()
                .load( Foo.class.getClassLoader(), ClassLoadingStrategy.Default.WRAPPER );
        Foo instance = loaded.getLoaded().getDeclaredConstructor().newInstance();
        String s = instance.getQuery( "foo" );
    }

    public static class SeenQueriesInterceptor {

        @RuntimeType
        public static Object intercept( @SuperCall Callable<?> zuper, @AllArguments Object[] args ) throws Exception {
            System.out.println( "Hello world from method interceptor" );
            return "foo";
        }
    }
```

The above works, but note an important difference here: the `getQuery()` method is public; the real `DatabaseMediator.getQuery()` method which I'm trying to replace is `private`.

I feel quite stuck here. Any ideas on what could be the problem here?

----

One thing that is a bit frustrating in this is that whenever I try to do these transformations via the ByteBuddy Agent, it feels like all errors are silently disregarded. That's why I move the actual transformation out of the transform()` method and added the explicit `databaseMediatorBuilder.make()`. This was helpful in making sure the `SeenQueriesInterceptor.intercept()` method has the correct method signature. :pray: 

I guess there isn't any way to enable more logging from the ByteBuddy Agent, if something goes wrong with a particular transformation? It's much easier to debug errors which gets printed somewhere than just the dreaded "nothing works, and no exception is thrown"-type of errors. :sweat_smile: 

Thanks in advance for any help with this, appreciated.

**Comment by raphw** [comment]
The default behavior of a `ClassFileTransformer` does exactly that: disregard the error. You can register an `AgentBuilder.Listener` to be notified of any errors, for example by printing them to the console.

As for your setup, you would probably want rebasing if you were using a `MethodDelegation`. The original code would be copied to another method if you require a `SuperCall` what retransformation does not allow. I assume this would be what the exception would be telling you, too.

Rather then method delegation, you should probably use `Advice` which allows you to add logic to a method without requiring any additional methods. You should then also use `.disableClassFormatChanges()`.

**Comment by perlun** [comment]
> The default behavior of a `ClassFileTransformer` does exactly that: disregard the error. You can register an `AgentBuilder.Listener` to be notified of any errors, for example by printing them to the console.

Thanks. :+1: For reference, here's one way to add it to the `AgentBuilder`:

```java
.with( AgentBuilder.Listener.WithErrorsOnly.StreamWriting.toSystemError() )
```

This will typically produce loads of output, so to get a filtered view of only the transformations of a given class, you can use something like this:

```java
.with( new AgentBuilder.Listener.Filtering( 
        name -> name.equals( "fi.hibox.centre.server.database.DatabaseMediator" ), 
        AgentBuilder.Listener.StreamWriting.toSystemError() )
)
```

Interestingly enough though, the transformation does seem to succeed - no errors are printed. :thinking: 
```
Gradle suite STANDARD_ERROR
    [Byte Buddy] DISCOVERY fi.hibox.centre.server.database.DatabaseMediator [jdk.internal.loader.ClassLoaders$AppClassLoader@9e89d68, unnamed module @1068e947, loaded=true]
    [Byte Buddy] TRANSFORM fi.hibox.centre.server.database.DatabaseMediator [jdk.internal.loader.ClassLoaders$AppClassLoader@9e89d68, unnamed module @1068e947, loaded=true]
    [Byte Buddy] COMPLETE fi.hibox.centre.server.database.DatabaseMediator [jdk.internal.loader.ClassLoaders$AppClassLoader@9e89d68, unnamed module @1068e947, loaded=true]
```

> As for your setup, you would probably want rebasing if you were using a MethodDelegation. The original code would be copied to another method if you require a SuperCall what retransformation does not allow. I assume this would be what the exception would be telling you, too.

Yeah, you're right. I've been trying various ways to see if it would behave differently, but you're right - to make my use case work I'd need rebasing to be able to perform the `SuperCall§.

I tried changing the `.with( AgentBuilder.TypeStrategy.Default.REDEFINE )` call to use `REBASE` now. Interestingly enough, it behaves and logs similarly. The transformation seems to succeed but the original method still gets called instead of the interceptor. Do you need to do something special to be able to rewrite private methods with ByteBuddy?

Regardless, you might be right in that `Advice` would be a better strategy. I'll check it out and see if I can get it working.

(Some form of "cookbook" of examples of how to use ByteBuddy on the webpage would be incredibly useful, IMHO. I'd happily add an example for my use case if/when I get it working. :grin:)

**Comment by perlun** [comment]
For reference, I managed to get this working with the `Advice`-based approach. Much appreciated @raphw! In case anyone's interested, here's what I ended up with:

```java
    @BeforeSuite
    public void beforeSuite() {
        ByteBuddyAgent.install();

        // Add an Advice to the DatabaseMediator.getQuery() method, to be able to inject custom
        // logic to it which is only applied when integration tests are executed.
        new AgentBuilder.Default()
                .disableClassFormatChanges()
                .with( AgentBuilder.RedefinitionStrategy.RETRANSFORMATION )
                .with( AgentBuilder.RedefinitionStrategy.DiscoveryStrategy.Reiterating.INSTANCE )
                .ignore( none() )
                .type( named( DatabaseMediator.class.getName() ), ElementMatchers.is( DatabaseMediatorAdvice.class.getClassLoader() ) )
                .transform( new AgentBuilder.Transformer.ForAdvice()
                        .with( AgentBuilder.LocationStrategy.ForClassLoader.STRONG )
                        .include( DatabaseMediatorAdvice.class.getClassLoader() )
                        .with( Assigner.DEFAULT )
                        .withExceptionHandler( new Advice.ExceptionHandler.Simple( Removal.SINGLE ) )
                        .advice( named( "getQuery" ), DatabaseMediatorAdvice.class.getName() )
                )
                .installOnByteBuddyAgent();
    }

    public static class DatabaseMediatorAdvice {
        // Must be public to avoid IllegalAccessError exceptions.
        //
        // I think the reason this happens is because the bytecode for the OnMethodExit() method
        // gets added to the DatabaseMediator class, meaning the SEEN_QUERIES.add() call actually
        // takes place from outside this class.
        public static final Set<String> SEEN_QUERIES = Collections.newSetFromMap( new ConcurrentHashMap<>( 1500 ) );

        public static Set<String> getSeenQueries() {
            return SEEN_QUERIES;
        }

        // The getQuery method signature looks like this: private String getQuery( String queryId ). In this method, add whatever
        // logic you need to execute after the original method has exited.
        @Advice.OnMethodExit
        private static void exit( @Advice.Argument( 0 ) String queryId, @Advice.Return String sql ) {
            if ( sql != null ) {
                SEEN_QUERIES.add( queryId );
            }
        }
```

In case a "tutorials/cookbooks" section gets added to the website (or this repo), let me know and I'll happily add the examples above to such a place. :+1: For now, posting it here in the hope that it will be useful and somewhat googlable to others.

**Comment by raphw** [comment]
Just for reference, instead of:

    .with( AgentBuilder.Listener.WithErrorsOnly.StreamWriting.toSystemError() )

you would write

    .with( AgentBuilder.Listener.StreamWriting.toSystemError().withErrorsOnly() )

The former does not what you expect as `WithErrorsOnly` does inherit all nested classes of its parent. You can also add `withTransformationsOnly` what will print errors and transformed classes.

That the delegation example is working surprises me, but I assume that there's something else going wrong.

**Comment by perlun** [comment]
Thanks for that clarification. :pray: As you might expect, I am quite stumbling in the dark here, trying to wrestle my way towards something that is even close to working. :joy: 

> That the delegation example is working surprises me, but I assume that there's something else going wrong.

There must indeed be something weird going on there yes. Could the logging fix above give us more details about it? :thinking:
