### ISSUE TITLE
Add method InjectionClassLoader.close()

### ISSUE THREAD

**Issue by pro100kryto** [raphw/byte-buddy#1100]
InjectionClassLoader
Suggest to add new method close() which prohibits further use of the class loader, like in URLClassLoader.

"Closes this URLClassLoader, so that it can no longer be used to load new classes or resources that are defined by this loader. Classes and resources defined by any of this loader's parents in the delegation hierarchy are still accessible. Also, any classes or resources that are already loaded, are still accessible."

**Comment by raphw** [comment]
That's a good idea since it might open for a relaxed preparation stage before returning . I fixed this on master and it's going to be part of the next release.
