### ISSUE TITLE
Ambiguous annotations leading to dummy mistakes

### ISSUE THREAD

**Issue by novoj** [raphw/byte-buddy#1104]
This problem originates in this StackOverflow question: https://stackoverflow.com/questions/69044329/intercepting-unimplemented-interface-method-with-bytebuddy/69044855#69044855

The problem is that some annotations are declared twice in ByteBuddy in different packages - for example:

```
net.bytebuddy.implementation.bind.annotation.AllArguments
net.bytebuddy.asm.Advice.AllArguments
```

When annotation from the `implementation` package is used, everything works. But when the annotation from `asm` package is used the method on MehodDelegate is always excluded as non matching (obviously).
That's a nasty catch because it's hard to see! Idea offers selection from two imports but there is no clear hint which one should be used and which not.

Would it be possible to either rename the wrong annotations (which would be hard due to backward compatibility I guess) or add an validation to the generator logic that will print a warning message when class which is delegated to contains annotations from improper packages in the adept delegation methods?

**Comment by raphw** [comment]
Unfortunately, renaming is not possible without breaking a lot of code. `MethodDelegation` and `Advice` are the most used concepts in Byte Buddy, and the change would be too irritating.

I see your point however. I never use imports of inner classes, this is the reason I overlooked this potential. The idea was to create irreconcilability, but some people run into these non-intuitive problems and its too bad.

Unfortunately, it's neither possible to forbid the annotation. Some people use the same class with both advice and delegation, depending on the context, and then parameters are annotated with multiple parameters. Thus, failing on the "paired" annotation is neither a solution.

Unfortunately, I'd change the annotation names with a name, not a type prefix, today.

**Comment by novoj** [comment]
I thought it would be complicated.

The reason why I imported the annotations from the `asm` package was bad intuition - the package has "shorter" path, the package contains word `Advice` which was something I thougth I've been writing. On the contrary the correct annotation is in pakcage `implementation` which resonated as something `internal` or `implementation specific` for me.

I also looked into the documentation https://bytebuddy.net/#/tutorial but I found no hint or clue why these annotations are twice and which one to use. Also Javadoc in annotations is not much helpful to decide which is correct or when should I use this one over another:

![image](https://user-images.githubusercontent.com/202912/132084714-cb5d04cf-e0ba-4520-b3eb-50018732db37.png)
![image](https://user-images.githubusercontent.com/202912/132084725-c865bcf7-5398-4fff-8e2c-dd3916765d43.png)

I don't want to take you precious time, but what is the case I would need to use `net.bytebuddy.asm.Advice.AllArguments` and such in method delegation? Is there any moment when this declaration in method signature is correct and what it would do?

```java
import net.bytebuddy.asm.Advice.AllArguments;
import net.bytebuddy.asm.Advice.Origin;
import net.bytebuddy.asm.Advice.This;
import net.bytebuddy.implementation.bind.annotation.DefaultCall;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;
import net.bytebuddy.implementation.bind.annotation.SuperCall;

@RuntimeType
public Object interceptMethodCall(
	@This Object proxy,
	@Origin Method method,
	@SuperCall(nullIfImpossible = true, serializableProxy = true, fallbackToDefault = false) Callable<Object> superMethod,
	@DefaultCall(nullIfImpossible = true, serializableProxy = true) Callable<Object> defaultMethod,
	@AllArguments Object[] args
) throws Throwable {
}
```

**Comment by raphw** [comment]
You would not normally need to do this, but if you wanted to write an
interceptor that can be used by advice and method delegation, you would
need both annotations as they both have slightly different semantics and
arguments.

In most cases, with MethodDelegation you would use the @AllArguments
annotation from the net.bytebuddy.implementation.bind.annotation package:
https://github.com/raphw/byte-buddy/tree/master/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/bind/annotation

And if you also wanted to use this interceptor with advice, you would also
add the Advice annotations if you wanted the same bindings. In this case,
you'd add both annotations.

Am Sa., 4. Sept. 2021 um 08:12 Uhr schrieb Jan Novotný <
***@***.***>:

**Comment by novoj** [comment]
I see, I'm sorry to disturb you with reporting problems that originate in my lack of knowledge. Thank you for clarification. What would you say to at least adding "a warning notice" to the respective parts of the documentation? I'd make a pull request for this, but I didn't find a source of https://bytebuddy.net/#/tutorial in the repository.

**Comment by raphw** [comment]
No, it's a very legitimate question. The tutorial is rather outdated. I had started on a new one but it's a lot of work.

Please file a PR to clarify on the import issue. It's probably good to mention in the javadoc.

**Comment by novoj** [comment]
Pull request created: https://github.com/raphw/byte-buddy/pull/1107
