### ISSUE TITLE
Q: multiple interceptors referencing same class?

### ISSUE THREAD

**Issue by jrodbx** [raphw/byte-buddy#1105]
Hi there,

We're using ByteBuddy in https://github.com/cashapp/paparazzi -- an Android snapshot testing library -- to intercept, redirect, and correct methods calls from https://android.googlesource.com/platform/frameworks/layoutlib to the bundled Android platforms for methods that are not yet implemented or buggy.

It's been working great for us so far!  Here are two examples: https://github.com/cashapp/paparazzi/pull/132 and https://github.com/cashapp/paparazzi/pull/145.

Specifically, note how we use [AgentTestRule](https://github.com/cashapp/paparazzi/blob/master/paparazzi-agent/src/main/java/app/cash/paparazzi/agent/AgentTestRule.kt) to install the ByteBuddyAgent, followed by a collection of interceptors via [InterceptorRegistrar](https://github.com/cashapp/paparazzi/blob/master/paparazzi-agent/src/main/java/app/cash/paparazzi/agent/InterceptorRegistrar.kt).

Most recently, we're trying to intercept calls to [android.opengl.Matrix#multiplyMM](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/opengl/java/android/opengl/Matrix.java;l=72-73) and [android.opengl.Matrix#multiplyMV](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/opengl/java/android/opengl/Matrix.java;l=97-99), both defined as native static methods.

```
    public static native void multiplyMM(float[] result, int resultOffset,
            float[] lhs, int lhsOffset, float[] rhs, int rhsOffset);

    public static native void multiplyMV(float[] resultVec,
            int resultVecOffset, float[] lhsMat, int lhsMatOffset,
            float[] rhsVec, int rhsVecOffset);
```

Here's a WIP branch attempting such: https://github.com/cashapp/paparazzi/compare/jrod/2021-02-28/wip-layout-lib-native...jrod/2021-09-03/matrix-multiply?expand=1

Note that the first commit which intercepts multiplyMM works!  Here's a debugging session screenshot that shows that:

<img width="1156" alt="Screen Shot 2021-09-03 at 5 19 15 PM" src="https://user-images.githubusercontent.com/1868149/132070485-32c4a5d4-3108-429e-bbf6-9cbf9b824318.png">

However, the second commits which intercepts multiplyMV *overrides and clobbers the first commit, so that interception of multiplyMM no longer works!*

<img width="955" alt="Screen Shot 2021-09-03 at 5 49 05 PM" src="https://user-images.githubusercontent.com/1868149/132070555-cba1288c-0032-44f6-b346-fc531e916a7b.png">

As a last resort, I attempted bumping from ByteBuddy 1.11.9 to 1.11.15, but that didn't seem to help.

Feels like I'm close; what am I missing in my setup in order to get both interceptors working correctly?

**Comment by raphw** [comment]
I am not fully certain how this all hangs together, but I think that you are removing the previous modification. Every time you *redefine*, the class file is read from the jar file that stores the original class and likely replaces the previous. Ideally, you would add the interceptions to a single run of `ByteBuddy`. If you wanted to supply a previous byte array, you would need to extract the class file from the generated `DynamicType` and provide it as a second argument to `redefine` via a `ClassFileLocator`.

Also, note that redefine has some limitations in the sense that you cannot change modifiers or add methods. You would therefore not be able to make `native` methods non-native. For this, you would need to register a `ClassFileTransformer` via an `AgentBuilder` where you can register a native method prefix. This does not really work for classes that are already loaded, however.

**Comment by jrodbx** [comment]
> I am not fully certain how this all hangs together, but I think that you are removing the previous modification. Every time you _redefine_, the class file is read from the jar file that stores the original class and likely replaces the previous. Ideally, you would add the interceptions to a single run of `ByteBuddy`. 

Ah, makes sense!  Using a single instance + adding all interceptions related to a receiver class at the same time seemed to fix the issue: https://github.com/cashapp/paparazzi/commit/b3eaeb1726e8b16baa3eafe324ce095c7f37f71e

Thanks!
