### ISSUE TITLE
Lambda expressions for generic target types

### ISSUE THREAD

**Issue by raner** [raphw/byte-buddy#1112]
I am using `InvokeDynamic.lambda(InDefinedShape, TypeDescription)` to create the equivalent of these two methods:
```
    static interface StringMeasure
    {
        Integer measure(String string);
    }
    
    StringMeasure stringMeasure()
    {
        return String::length;
    }

    Function<String, Integer> stringLengthFunction()
    {
        return String::length;
    }
```
This works as expected for the `stringMeasure()` method, but I'm having a hard time getting Byte Buddy to generate correct code for the `stringLengthFunction()` method. So far, my efforts have yielded `NoSuchMethodError`s, `AbstractMethodError`s, or `LambdaConversionException: Invalid receiver type`.

I noticed that there is a slight difference in the bootstrap methods generated for the two cases.
For `stringMeasure()` the Java compiler produces the following:
```
  fava.tests.ByteBuddyTest$StringMeasure stringMeasure();
    Code:
       0: invokedynamic #16,  0             // InvokeDynamic #0:measure:()Lfava/tests/ByteBuddyTest$StringMeasure;
       5: areturn

...

BootstrapMethods:
  0: #38 REF_invokeStatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #40 (Ljava/lang/String;)Ljava/lang/Integer;
      #47 REF_invokeVirtual java/lang/String.length:()I
      #48 (Ljava/lang/String;)Ljava/lang/Integer;
```

For the other method, the Java compiler's output looks a little different:
```
  java.util.function.Function<java.lang.String, java.lang.Integer> stringLengthFunction();
    Code:
       0: invokedynamic #23,  0             // InvokeDynamic #1:apply:()Ljava/util/function/Function;
       5: areturn

...

  1: #38 REF_invokeStatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #50 (Ljava/lang/Object;)Ljava/lang/Object;
      #51 REF_invokeVirtual java/lang/String.length:()I
      #52 (Ljava/lang/String;)Ljava/lang/Integer;
```
The difference is the first argument to the bootstrap method: when targeting the (non-parameterized) `StringMeasure` interface we see the input and output types as expected: ` (Ljava/lang/String;)Ljava/lang/Integer;`.
When targeting the `java.util.function.Function` interface, the first argument corresponds to the type erasure of the interface, i.e., `(Ljava/lang/Object;)Ljava/lang/Object;`, whereas the third argument appears to be the fully reified signature.

Both of these examples were collected from the output of the Java compiler. I can generate the code for the first example in Byte Buddy,  but the second example is giving me trouble: I end up with `(Ljava/lang/Object;)Ljava/lang/Object;` for both the first and the third bootstrap method argument.
This even makes somewhat sense: the method description is passed as a `MethodDescription.InDefinedShape`, which does not resolve type variables, and the functional interface type is passed as a `TypeDescription`, which again can only represent non-generic types.

It seems to me that one would need the capability to pass the functional interface as a `Generic` type, to address this case. Is this a current limitation of Byte Buddy, or is there a different way to generate lambda expressions for generic interfaces?

**Comment by raphw** [comment]
I'm not fully sure if I follow you. If you have a method

    Function<String, Integer> stringLengthFunction() {
        return String::length;
    }

it should be declared somewhere. Would this reference not be passable to Byte Buddy?

Ideally, you could create an executable, copy-pastable reproduction of your issue so I can easily follow your example. Thanks!

**Comment by raner** [comment]
Here's my test case:
```
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.function.Function;
import org.junit.Test;
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.description.method.MethodDescription;
import net.bytebuddy.description.modifier.Visibility;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.description.type.TypeDescription.Generic;
import net.bytebuddy.implementation.InvokeDynamic;
import static java.util.Collections.emptyList;
import static org.junit.Assert.assertEquals;

public class ByteBuddyTests
{
  public static interface StringMeasure
  {
      Integer measure(String string);
  }

  final MethodDescription.InDefinedShape STRING_LENGTH = new MethodDescription.Latent
  (
    TypeDescription.ForLoadedType.of(String.class),
    "length",
    Modifier.PUBLIC,
    emptyList(),
    TypeDescription.ForLoadedType.of(int.class).asGenericType(),
    emptyList(),
    emptyList(),
    emptyList(),
    null,
    null
  );

  /**
   * Generates a class with the following method:
   * 
   *   StringMeasure stringMeasure()
   *   {
   *     return String::length;
   *   }
   */
  @Test
  public void returnLambdaExpressionForNonParameterizedInterface() throws Exception
  {
    TypeDescription typeStringMeasure = new TypeDescription.ForLoadedType(StringMeasure.class);
    Class<?> classReturningStringMeasure = new ByteBuddy()
      .subclass(Object.class)
      .defineMethod("stringMeasure", typeStringMeasure, Visibility.PUBLIC)
      .intercept(InvokeDynamic.lambda(STRING_LENGTH, typeStringMeasure))
      .make()
      .load(getClass().getClassLoader())
      .getLoaded();
    Method stringMeasureMethod = classReturningStringMeasure.getDeclaredMethod("stringMeasure");
    Object instance = classReturningStringMeasure.getDeclaredConstructor().newInstance();
    StringMeasure stringMeasure = (StringMeasure)stringMeasureMethod.invoke(instance);
    assertEquals(Integer.valueOf(5), stringMeasure.measure("Hello"));
  }
  
  /**
   * Generates a class with the following method:
   * 
   *   Function<String, Integer> stringLengthFunction()
   *   {
   *     return String::length;
   *   }
   */
  @Test
  public void returnLambdaExpressionForParameterizedInterface() throws Exception
  {
    Generic typeFunctionStringInteger = Generic.Builder
      .parameterizedType(Function.class, String.class, Integer.class).build();
    Class<?> classReturningStringLengthFunction = new ByteBuddy()
      .subclass(Object.class)
      .defineMethod("stringLengthFunction", typeFunctionStringInteger, Visibility.PUBLIC)
      .intercept(InvokeDynamic.lambda(STRING_LENGTH, typeFunctionStringInteger.asErasure()))
      .make() // Needs erasure here because lambda() does not accept Generic type ^^^
      .load(getClass().getClassLoader())
      .getLoaded();
    Method stringLengthFunctionMethod = classReturningStringLengthFunction.getDeclaredMethod("stringLengthFunction");
    Object instance = classReturningStringLengthFunction.getDeclaredConstructor().newInstance();
    @SuppressWarnings("unchecked")
    Function<String, Integer> function = (Function<String, Integer>)stringLengthFunctionMethod.invoke(instance);
    assertEquals(Integer.valueOf(5), function.apply("Hello"));
  }
}
```
The first test, `returnLambdaExpressionForNonParameterizedInterface()`, passes as expected.
The second test, `returnLambdaExpressionForParameterizedInterface()`, fails with the following exception:
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at ByteBuddyTests.returnLambdaExpressionForParameterizedInterface(ByteBuddyTests.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	...
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.BootstrapMethodError: call site initialization exception
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:385)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:250)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:240)
	at net.bytebuddy.renamed.java.lang.Object$ByteBuddy$yJTLzpas.stringLengthFunction(Unknown Source)
	... 31 more
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type class java.lang.Object; not a subtype of implementation type class java.lang.String
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:254)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:311)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:332)
	... 34 more
```
My theory is that this exception is caused by type erasure in the `Function` interface, which causes `(Ljava/lang/Object;)Ljava/lang/Object;` to be passed as third argument to the bootstrap method, instead of the reified signature, `(Ljava/lang/String;)Ljava/lang/Integer;` (it is a notable difference when examining the generated bytecode, and the error message also seems to hint that this might indeed be the problem).
However, I don't see a way to pass the full type including its type arguments to the `lambda(...)` method. In the second test case, `typeFunctionStringInteger` contains the full type information, but in order to pass the type description to the `lambda(...)` method I have to call `asErasure()`, which wipes out the type arguments.

If the method signature were `lambda(InDefinedShape, Generic)` instead (and the full type information is retained throughout), then it seems it should be possible to generate the lambda expression correctly.

Does that make any sense?

**Comment by raphw** [comment]
I see, I also think that I understand what the solution must be, but this requires an adjustment on a rather crucial API to operate of generic types. I will see what I can do but I would need to add this to a 1.12.x release which might be overdue anyways.

**Comment by raphw** [comment]
Was easier then expected and is fixed on master.

**Comment by raner** [comment]
Thank you so much for fixing this so quickly, @raphw - I really appreciate it.

**Comment by raner** [comment]
Will there be another Byte Buddy release this month? I'm just curious when I can expect this to be available in Maven Central. Thanks!

**Comment by raphw** [comment]
This week, I think.
