### ISSUE TITLE
ExceptionInInitializerError thrown in Eclipse OpenJ9 JVM

### ISSUE THREAD

**Issue by mateusbandeiraa** [raphw/byte-buddy#1118]
When trying to run tests using Eclipse OpenJ9, I get this error:
```
java.lang.ExceptionInInitializerError
        at com.bar.foo.<clinit>(FooTest.java:24)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.ClassLoader$CompoundEnumeration@626d5804
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.mockito.exceptions.base.MockitoInitializationException:

Could not initialize inline Byte Buddy mock maker.

It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 11
JVM vendor name    : Eclipse OpenJ9
JVM vendor version : openj9-0.23.0
JVM name           : Eclipse OpenJ9 VM
JVM version        : 11.0.9+11
JVM info           : JRE 11 Windows 10 amd64-64-Bit Compressed References 20201022_795 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 3b09cfd7e9 based on jdk-11.0.9+11
OS name            : Windows 10
OS version         : 10.0

Caused by: java.lang.IllegalStateException: Could not self-attach to current VM using external process

```

I tried running the same test using [Oracle's OpenJDK 11](https://jdk.java.net/java-se-ri/11) implementation and it ran successfully.

I'm not familiar with Byte Buddy at all, so I don't know how to fix it myself. But I really think there's something wrong with the implementation, because my tests are able to run on a specific JVM but not in other.

**Comment by raphw** [comment]
Seems like the attach api does not work. can you run a test that only calls ByteBuddyAgent.install()

**Comment by mateusbandeiraa** [comment]
Here's my test class:
```Java
import org.junit.jupiter.api.Test;

import net.bytebuddy.agent.ByteBuddyAgent;

class ByteBuddyTest {
    
    @Test
    void test() {
	ByteBuddyAgent.install();
    }
    
}

```
Running `mvn verify -Dtest=ByteBuddyTest` resulted in:
```
[ERROR] test  Time elapsed: 0.462 s  <<< ERROR!
java.lang.IllegalStateException: Could not self-attach to current VM using external process
        at com.ibm.gimage.toolbox.ByteBuddyTest.test(ByteBuddyTest.java:11)

```

Running on Oracle's JVM did work as expected.

**Comment by raphw** [comment]
Can you try setting: `-Djdk.attach.allowAttachSelf=true`? Self-attachment is no longer legal but there are many work arrounds that make this possible normally. If it also fails with the option, it's a different error.

**Comment by raphw** [comment]
Just downloaded an official OpenJ9 11 (for Linux) and things work as expected. I wonder if this is a system setup issue. If it works with the parameter, your application might not be able to start processes.

**Comment by mateusbandeiraa** [comment]
Setting `-Djdk.attach.allowAttachSelf=true` did not fix the issue.

I made some intriguing findings. When I tried to replicate the issue this morning, it started working. During all my tests and troubleshooting yesterday, I had Eclipse IDE opened. Here's what I found:

1. If Eclipse is not running, `mvn verify -Dtest=ByteBuddyTest` works as expected;
2. If Eclipse is running, `mvn verify -Dtest=ByteBuddyTest` throws `java.lang.IllegalStateException: Could not self-attach to current VM using external process`;
3. If Eclipse is running and I open a command prompt window as administrator, `mvn verify -Dtest=ByteBuddyTest` works as expected.

I'm very puzzled about this. I don't run Eclipse with the same JVM I'm using to run the tests in the command line (Eclipse is running on IBM J9 Java 1.8). I have no clue of how this could be related, but it seems to be the case.

This confirms that this is a system setup issue. Being the case, do you want me to close the issue or would you still like to investigate some more? I can run more tests if you wish so.

**Comment by raphw** [comment]
It might be some JAVA_HOME confusion. If BB picks up a regular VM to attach to J9, things might break unexpectedly

**Comment by mateusbandeiraa** [comment]
I double checked. My JAVA_HOME and path is set to openj9 11. Also, if that were the case (a conflicting env variable setting) running as administrator wouldn't fix it... Or would it?

**Comment by raphw** [comment]
I wonder if Windows struggles with isolating an environment in this case. But then again, I do not know a thing about Windows.

**Comment by mateusbandeiraa** [comment]
I made some experiments:

**Command prompt as user:**
| Eclipse JVM | Opened Eclipse as admin? |Oracle 11 |IBM J9 1.8 | Eclipse OpenJ9 11 |
|-|-|-|-|-|
| Oracle 11| Yes |✅|✅|✅|
| Oracle 11| No |✅|✅|✅|
| IBM J9 1.8| **Yes** |✅|❌|❌|
| IBM J9 1.8| No |✅|✅|✅|
| Eclipse OpenJ9 11| **Yes** |✅|❌|❌|
| Eclipse OpenJ9 11| No |✅|✅|✅|

**Command prompt as admin:**
| Eclipse JVM | Opened Eclipse as admin? | Eclipse OpenJ9 11 |
|-|-|-|
| IBM J9 1.8| **Yes** |✅|
| Eclipse OpenJ9 11| **Yes** |✅|

I also checked that when I run the tests as user, there are new Java processes owned by my user, so I guess the application is able to create the processes.

My guess would be that ByteBuddy is trying to attach itself to the wrong process (the Eclipse JVM, owned by the admin). Not sure how that works, neither if that's really possible.

**Comment by raphw** [comment]
Interesting finding. It extracts the process id and then uses sn official API to connect to this process. To me this indicates that the there's an issue in J9.

**Comment by mateusbandeiraa** [comment]
Closing this issue since it is an OpenJ9 bug rather than a ByteBuddy problem.
