### ISSUE TITLE
Return type and parameter type options for @Advice.Origin#value()

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#112]
It would be nice to format method names like this:

```
int org.example.MyClass.method(String)
```

The closest I can get is `@Advice.Origin("#t.#m#d")` which results in:

```
org.example.MyClass.method(Ljava/lang/String;)I
```

**Comment by raphw** [comment]
This is already possible in the current *development* version where the `@Advice.Origin` annotation includes additional values and where you can also compute a custom value by adding your own annotation and mapping.
