### ISSUE TITLE
Allow running ByteBuddy transformation against the runtime classpath of a build

### ISSUE THREAD

**Issue by odrotbohm** [raphw/byte-buddy#1121]
AOT gaining quite a bit of attention the following case could arise that the ByteBuddy Maven plugin doesn't handle:

1. Some AOT plugin inspects both compile and runtime dependencies and generates code based on that.
2. That code gets compiled against the *runtime* classpath.
3. If ByteBuddy is now run against that code, it will fail to load classes only available on the runtime classpath that might be referred to from the generated code.

I see the classpath elements currently obtained within `ForProductionTypes.getClasspathElements()` and are fixed to the compile classpath. Does it make sense to introduce a configuration option that could still default to the compile classpath but allow users to flip that to the runtime one in case their build is using AOT?

**Comment by raphw** [comment]
Good point, I just added the option! Never really thought about it but it's a valid use case.

**Comment by raphw** [comment]
Fixed on master.

**Comment by odrotbohm** [comment]
What's actually used is completely determined by the newly introduced flag, isn't it? I might be mistaken but would hope that `getCompileClasspathElements()` returns what it implies to return.

**Comment by raphw** [comment]
It is, but the resolution is heavier. I just decided to rather introduce two goals, one being the previous *transform* and the other being *transform-runtime*.
