### ISSUE TITLE
Intercept with lambda

### ISSUE THREAD

**Issue by Cormanz** [raphw/byte-buddy#1124]
Hi, so I'm trying to use ByteBuddy to dynamically extend an abstract class with implementations of methods as lambdas.

From my testing you can use `.method(...).intercept(...)`, but I can't find a way to intercept the function's call with a lambda, only intercepting it with a static class

Is there a way to intercept a method of a class with a lambda/anonymous class callback, like `.method(named('lambda')).intercept(new LambdaDelegation(args -> ...))`?

**Comment by raphw** [comment]
You can certainly use a functional expression, for example by using a `InvocationHandlerAdapter` which accepts an `InvocationHandler` which is a functional interface. Lambda expressions are dynamic classes themselves, which makes it complicated to process them for annotations. But you are right that there should be an easier way using a `MethodDelegation` with a functional interface. I will look into how this can be improved.

**Comment by Cormanz** [comment]
Also, is there an easy way to reference currently scoped values directly in the new class definition?

**Comment by raphw** [comment]
What do you mean by *currently scoped*? 

As for the lambda, you can create a functional interface such as:

```java
interface MyDelegation {
  void intercept(@Argument(0) Object arg);
}
```

and supply the type as in: `MethodDelegation.to((MyDelegation) arg -> { }, MyDelegation.class). There is no way to use a lambda with a variable amount of arguments, that is the issue here.
