### ISSUE TITLE
Methods mirroring doesn't work as expected

### ISSUE THREAD

**Issue by PhantomYdn** [raphw/byte-buddy#1127]
Hello, @raphw, 

Seems I have found an interesting issue with ByteBuddy or a way how we use it. Please consider the following test case:

```java
public static class MyClass {
		public <V> V echo(V value) {
			return value;
		}
		
		public <T extends MyClass> T getThis() {
			return (T) this;
		}
	}
	
	public static interface MyInterface {
		public <V> V echo(V value);
		public <T extends MyInterface> T getThis();
	}
	
	@Test
	public void testMethodsMirroring() throws Exception {
		 DynamicType.Loaded<?> loaded = new ByteBuddy()
	                .subclass(MyClass.class)
	                .implement(MyInterface.class)
	                .make()
	                .load(getClass().getClassLoader(), ClassLoadingStrategy.Default.WRAPPER);
		 MyInterface obj =  (MyInterface)loaded.getLoaded().newInstance();
		 assertEquals("Test", obj.echo("Test")); //Executed OK
		 assertEquals(obj, obj.getThis()); //Failing HERE
	}
```
Method `echo` works perfectly. But on trying to do `getThis()` code failing with the following exception:
```
java.lang.AbstractMethodError: org.orienteer.transponder.ByteBuddyTest$MyClass$ByteBuddy$VA9TIAd1.getThis()Lorg/orienteer/transponder/ByteBuddyTest$MyInterface;
	at org.orienteer.transponder.ByteBuddyTest.testMethodsMirroring(ByteBuddyTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
So it's NOT failing during making a dynamic class, but during using it.
I understand that return type of `MyClass.getThis()` and `MyInterface.getThis()` are technically different. So was ready to implement the corresponding mirroring by delegator like this:
```java
public static class MirrorDelegator {
		@RuntimeType
		public static Object invoke(@Origin Method method, @This Object wrapper, @AllArguments Object[] args) {
			try {
				Method destination = MyClass.class.getMethod(method.getName(), method.getParameterTypes());
				return destination.invoke(wrapper, args);
			} catch (Exception e) {
				e.printStackTrace();
				throw new IllegalStateException("Mirror method can't be invoked:"+method, e);
			}
		}
		
	}
```
But `ElementMatchers` can't catch exact methods... I have tried:

-  `isDeclaredBy(MyInterface.class).and(isAbstract())` 
-  `isAbstract()` 
-  `named(...)`

Please advice if something can be done in my code to get that solved...

**Comment by PhantomYdn** [comment]
I'm aware that with this setup in pure java it's not possible to do the following class:
```java
public static class JointMyClass extends MyClass implements MyInterface {

}
```
It become compilable only of MyInterface will have `getThis` defined as "default" method. If it's the ONLY solution - it's ugly, but solution... What do you think?

**Comment by raphw** [comment]
The issue here is that Byte Buddy resolves the hierarchy after the rules of the Java language, not by JVM symbols. You can switch this to using JVM symbols by configuring Byte Buddy to do so:

    new ByteBuddy().with(MethodGraph.Compiler.Default.forJVMHierarchy())

**Comment by PhantomYdn** [comment]
@raphw, thank you for your answers! Closing the issue:)
