### ISSUE TITLE
how I use bytebuddy  load system class and  My  define class

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1129]
```
public class ByteTaintFlowAgent {

    public static String Fxxx="xxx";
    
    public static void premain(String arg, Instrumentation inst) throws Exception {
        File temp = Files.createTempDirectory("tmpzzzzzzzzzzzzzzzzzzzzzzz").toFile();
        ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, inst).inject(Collections.singletonMap(
                new TypeDescription.ForLoadedType(MyInterceptor.class),
                ClassFileLocator.ForClassLoader.read(MyInterceptor.class)));
        new AgentBuilder.Default()
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
                .with(new AgentBuilder.InjectionStrategy.UsingInstrumentation(inst, temp))
                .type(ElementMatchers.nameEndsWith(".HttpURLConnection"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
                        return builder.method(ElementMatchers.named("getRequestMethod")).intercept(MethodDelegation.to(MyInterceptor.class));
                    }

                }).installOn(inst);
    }

    public static class MyInterceptor {

        public static String intercept(@SuperCall Callable<String> zuper) throws Exception {
            System.out.println("Intercepted!");

            System.out.println("Source Enter Taint: "+ByteTaintFlowAgent.Fxxx);
            return zuper.call();
        }
    }

}
```

but when  run, i have  recivced  error：
Intercepted!
Exception in thread "main" java.lang.NoClassDefFoundError: com/taint/agent/ByteTaintFlowAgent
	at com.taint.agent.ByteTaintFlowAgent$MyInterceptor.intercept(ByteTaintFlowAgent.java:77)
	at sun.net.www.protocol.http.HttpURLConnection.getRequestMethod(HttpURLConnection.java)
	at test.JavaInject.main(JavaInject.java:43)

how  can   user  bootstrap  correctly!!!

**Comment by cor0ps** [comment]
I   solve this problem I have encountered new difficulties, same static  code  ,but  get  answer is not same
Code Example:
public class ByteTaintFlowAgent {

    public static String Fxxx="xxxzzzzzzzzzzzzzzz";
    private static ConcurrentHashMap<String, Set<String>> sources = new ConcurrentHashMap<>();

    public static ConcurrentHashMap<String, Set<String>> getSources() {
        return sources;
    }

    public static void setSources(ConcurrentHashMap<String, Set<String>> sources) {
        ByteTaintFlowAgent.sources = sources;
    }



    public static void premain(String arg, Instrumentation inst) throws Exception {



        Set<String> methods1 = new HashSet<>();
        methods1.add("getExpression");
        methods1.add("getExpression2");
        sources.put("com/taint/agent/ByteTaintFlowAgent", methods1);

        System.out.println(ByteTaintFlowAgent.getSources().size());_**//this  output is  1,is  right**_

        File temp = null;
        //temp = Files.createTempDirectory("classloader").toFile();
        temp=new File("C:\\tmp\\debug-source-sink\\classloader");
        if(temp.exists()){
            temp.getParentFile().mkdirs();
        }
        Map<TypeDescription, byte[]> map = new HashMap<>();
        map.put(new TypeDescription.ForLoadedType(com.taint.agent.ByteTaintFlowAgent.class), ClassFileLocator.ForClassLoader.read(com.taint.agent.ByteTaintFlowAgent.class));
        ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, inst).inject(map);

        new AgentBuilder.Default()
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
                .with(new AgentBuilder.InjectionStrategy.UsingInstrumentation(inst, temp))
                .type(ElementMatchers.nameEndsWith(".HttpURLConnection"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
                        return builder.method(ElementMatchers.named("getRequestMethod")).intercept(Advice.to(MethodAdvice.class));
                    }
                }).installOn(inst);
    }

}
public class MethodAdvice {

    @Advice.OnMethodEnter
    public static void MethodBefore(@Advice.Origin("#t") String type, @Advice.Origin("#m") String method, @Advice.Origin("#s") String sig) {
        System.out.println("Method advice");
        System.out.println(ByteTaintFlowAgent.Fxxx);**_//output  is  xxxzzzzzzzzzzzzzzz ,is  right  ._**
        System.out.println(ByteTaintFlowAgent.getSources().size()); _**//this  output  is  0,is not my want**_
    }
}


I  read source and find  my reason  is 

injectRaw code: result.put(name, Class.forName(name, false, this.target.getClassLoader()));  
class.forName  initialize is false    

maybe  i  set   initialize  true  can  solve  this  problem   

and   have  any  ways  to  solve  this  problem？？？？

**Comment by cor0ps** [comment]
> I manually initialize my  classes failure, Can you  give  me  a simple demo??? thanks

**Comment by cor0ps** [comment]
> `MyInterceptor` should not be an inner class, this way the outer class reference will be broken. Move it to it's own top-level.

there are many inner class and thanks   later  support this

**Comment by raphw** [comment]
Please reopen this ticket if there are further questions.
