### ISSUE TITLE
IllegalArgumentException: Can not set static XXX field YYY to XXX

### ISSUE THREAD

**Issue by YoannBuch** [raphw/byte-buddy#113]
I built a java agent with byte buddy (1.3.10), and it works pretty well for most cases. However I ran into an issue when I attached it to Intellij itself (I want to trace what happens when I use the "Run with Coverage") and I'm having a hard time isolating the problem.

Here's what happens:

> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.intellij.coverage.CoverageExecutor.<clinit>(CoverageExecutor.java)
> 	... 46 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.bytebuddy.agent.builder.Nexus.initialize(Nexus.java:95)
> 	... 51 more
> Caused by: java.lang.IllegalArgumentException: Can not set static agent.Interceptor field com.intellij.coverage.CoverageExecutor.delegate$1466166956 to agent.Interceptor
> 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
> 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
> 	at sun.reflect.UnsafeStaticObjectFieldAccessorImpl.set(UnsafeStaticObjectFieldAccessorImpl.java:79)
> 	at java.lang.reflect.Field.set(Field.java:764)
> 	at net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:105)
> 	at net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:180)
> 	at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:1542)
> 	... 56 more

The code:

```
new AgentBuilder.Default().type(nameStartsWith("com.intellij.coverage").and(not(nameContains("auxiliary")))).transform(new AgentBuilder.Transformer() {

	public Builder<?> transform(Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader) {

		return builder.method(isDeclaredBy(typeDescription)).intercept(MethodDelegation.to(new Interceptor()));
	}
}).installOn(instrumentation);
```

_As an aside, you'll notice the filter I'm using on auxiliary classes. I'm probably missing something but I thought I didn't need to do that any more (see http://stackoverflow.com/a/34946824/3408654)._

I'm using an instance to intercept method calls. **However the issue is gone if I use a static reference like**:

```
return builder.method(isDeclaredBy(typeDescription)).intercept(MethodDelegation.to(Interceptor.class));
```

But I would rather not use a static reference.

Note that I tried to attach the agent with instance or static reference to a simple program and both versions worked. The issue only occurs when I attach it to Intellij.

Any ideas? Anything I should do to help figure out the root cause?

Thanks!

**Comment by YoannBuch** [comment]
Instead of delegating to an instance I tried to delegate to a class (which in turns delegates to an instance) but I run into another issue (as part of the Intellij scenario):

```
public class Interceptor {

	// Using this pattern after our discussion:
	// https://github.com/raphw/byte-buddy/issues/95#issuecomment-175559645
	private static volatile Interceptor dispatcher;

	public static void setDispatcher(Interceptor dispatcher) {

		// Prints "CL: sun.misc.Launcher$AppClassLoader@14dad5dc"
		System.out.println("CL: " + Interceptor.class.getClassLoader());

		Interceptor.dispatcher = dispatcher;
	}
	
	@RuntimeType
	public static Object doIntercept(@SuperCall Callable<?> zuper) throws Exception {

		// Prints "CL: com.intellij.util.lang.UrlClassLoader@17c386de"
		System.out.println("CL: " + Interceptor.class.getClassLoader());
		
		// 'setDispatcher' was first called, then 'doIntercept'
		// but 'dispatcher' is null => NullPointerException
		// 
		// Hypothesis: 'Interceptor' class was loaded twice, the first one
		// got its static member 'dispatcher' assigned to a value whereas 
		// the second one didn't?
		return dispatcher.intercept(zuper);
	}
	
	private Object intercept(Callable<?> zuper)
			throws Exception {
		
		System.out.println("Intercepted!");
		
		return zuper.call();
	}
}
```

**Comment by raphw** [comment]
This is not too surprising. In order to avoid interference with a program, IntelliJ runs all of its code in a separate class loader. This separate class loader has your application classes accessible but does not load them from the system class loader (i.e. `sun.misc.Launcher$AppClassLoader`) but from a custom class loader that references the same jar file via a custom URL class loader (`com.intellij.util.lang.UrlClassLoader`).

A Java class is represented by a tuple in its loaded format that is a class name and a class loader. In this case, the instances are not equal. The instance you create is an instance of the app class loader's class, when the IntelliJ class is instrumented, it however resolves the class to the one loaded by the IntelliJ class loader. The types are no longer equal and the exception you observe is happening.

One option would be to use a primitive for representing the interceptor type. Neither class loader can avoid loading a class from the bootstrap class loader where types are always shared. (e.g. make your "interceptor") an instance of `java.lang.function.Function`.

**Comment by YoannBuch** [comment]
Thank you, Rafael!

I'm not sure to understand your suggestion. How can I make the interceptor an instance of a primitive and still be able to add my interception methods to it?

**Comment by raphw** [comment]
The problam is that a class loaded by two different class loaders constitues two different types.

By using a type that both class loaders consider equal (java.* types), you can resolve this disagreement.

**Comment by YoannBuch** [comment]
I think I understand that part. What I don't understand is how I can give an instance of a java.* type to Byte Buddy and at the same time augmenting that same type with methods used for interception.

**Comment by raphw** [comment]
You would apply the same pattern that you suggested with `setDispatcher(Function function)`.

**Comment by YoannBuch** [comment]
I'm not sure what you mean. What I understand:

I should not do the following otherwise `Interceptor` will be loaded twice, which causes the `NullPointerException` when its static member `dispatcher` is used:
```
return builder.method(isDeclaredBy(typeDescription))
  .intercept(MethodDelegation.to(Interceptor.class));
```

Making the `dispatcher` an instance of java.* type doesn't solve the problem.
```
setDispatcher(Function function)
```
`dispatcher` will be null.

I thought I should give to Byte Buddy a java.* type like:
```
return builder.method(isDeclaredBy(typeDescription))
  .intercept(MethodDelegation.to(java.lang.Runnable.class));
```
However I can't add behavior (i.e. a new static member or a new method) to `Runnable`, like adding that method:
```
@RuntimeType
public static Object doIntercept(@SuperCall Callable<?> zuper) throws Exception 
```

Extending or implementing a java.* type won't help either because that new type won't be part of the bootstrap class loader.

Also, like mentioned in the first comment, I also tried to give Byte Buddy an instance of `Interceptor`:
```
return builder.method(methodMatchers(typeDescription))
  .intercept(MethodDelegation.to(new Interceptor()));
```
Which gave me the following exception:

> Caused by: java.lang.IllegalArgumentException: Can not set static com.test.Interceptor field com.intellij.coverage.CoverageExecutor.delegate$867271420 to com.test.Interceptor
> 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
> 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
> 	at sun.reflect.UnsafeStaticObjectFieldAccessorImpl.set(UnsafeStaticObjectFieldAccessorImpl.java:79)
> 	at java.lang.reflect.Field.set(Field.java:764)
> 	at com.test.shaded.net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:105)
> 	at com.test.shaded.net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:180)
> 	at com.test.shaded.net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:1542)

What am I missing?

**Comment by raphw** [comment]
The problem is that two types are only equal if they are loaded by the same class loader. If you have two types `Foo` and you attempt to assign one instance to the other, these types are incompatible and this causes the `IllegalArgumentException` you observe.

The instrumented class is loaded in isolation by IntelliJ and your `new Interceptor()` is not assignable to the IntelliJ version of the`Interceptor` type. If you are using class delegation, Byte Buddy hard-codes the type reference into the IntellIJ class which implicitly references the "right" version of the class.

In order to avoid the boundary between "your" and the "IntelliJ" version of this class, you need to use a type that is equal for both sides of the view. The only class loader that IntelliJ and you have in common is the bootstrap class loader. The remaning challange is that you need to transport this instance from your side to the IntelliJ side of things where Byte Buddy cannot offer you an out of box solution. You would need to transfer the instance by putting it into, for example, the system propery map, which is however discouraged by the API contract.

**Comment by YoannBuch** [comment]
Thank you so much for taking the time to explain all that!

It's a shame the `IllegalArgumentException` is not more explicit about what really happens. But now I understand.

I used the system property map and it finally works! Note that I could not cast my instance of `Interceptor` (same issue with different class loaders) and therefore had to use reflection to make the call. That's probably not a good idea as it will slow things down, right?

```
public class Interceptor {

    @RuntimeType
    public static Object doIntercept(@SuperCall Callable<?> zuper) throws Exception {

        Properties systemProperties = System.getProperties();

        // the property "myinterceptor" was set when the java agent started
        Object interceptorInstance = systemProperties.get("myinterceptor");

        // Throws ClassCastException:
        // Interceptor interceptor = (Interceptor) interceptorInstance

        Method interceptMethod = interceptorInstance.getClass().getMethod(
            "intercept", 
            Callable.class);

        return interceptMethod.invoke(interceptorInstance, zuper);
    }

    public Object intercept(Callable<?> zuper)
            throws Exception {

        System.out.println("Intercepted!");

        return zuper.call();
    }
}
```

Taking a step back, I feel like my case is pretty common, don't you think? 

If we generalize things, one usually gives to Byte Buddy class or instance interceptors that were loaded by the system class loader. It's a problem because instrumented classes may be loaded by class loaders that are different from the system class loader. If I understand things right, it may therefore impact a wide range of applications: web containers, OSGI apps, applications like IntelliJ, etc.

**Comment by raphw** [comment]
I added an exception that is a bit more explicit over the problem. Thanks for the feedback!

**Comment by YoannBuch** [comment]
I finally got the time to work on this. Thanks for the hint, it solved a bunch of my problems. I added all the classes of my agent to the bootstrap class loader similarly as what was done in this agent:
https://github.com/glowroot/glowroot/blob/9cec83704211d4c374c799ebf9f036be461a7126/agent-parent/agent/src/main/java/org/glowroot/agent/AgentPremain.java

**Comment by raphw** [comment]
Great, thank you for the feedback.

**Comment by YoannBuch** [comment]
FYI, it's not working out of the box for some OSGI frameworks. By default, bundles have a limited access to classes available from the bootstrap class loader. The workaround is to explicitly tell the framework what packages should be available to bundles through the setting `org.osgi.framework.bootdelegation`.

**Comment by raphw** [comment]
You are right. From my experience, it is always best to prefix such injected classes by java.*

**Comment by YoannBuch** [comment]
I didn't think about it, thanks!

**Comment by YoannBuch** [comment]
I'm afraid I can't do that:

```
java.lang.SecurityException: Prohibited package name: java.com.mycompany
```

**Comment by raphw** [comment]
This only happens when you load such classes in a class loader that is not the bootstrap class loader. It was my understanding that you were using the bootstrap class loader (see the respective `ClassInjector`).

**Comment by YoannBuch** [comment]
You're right. My mistake was that I renamed the packages in the source and therefore I was getting that exception when I was running my tests (where the bootstrap class loader is not used). 

I solved it by renaming my packages only when I maven package my agent jar.
