### ISSUE TITLE
how to advice  request Annotation

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1131]
demo is:
```
public   Response  getXXXX(@RequestParam String username,@RequestParam String password,@RequestParam String xxxx,){
}
```

  new AgentBuilder.Default()
                .type(named("test.Test"))
                .transform((builder, type, classLoader, module) ->
                        builder.method(named("getXXXX"))
                                .intercept(Advice.withCustomMapping().bind(RequestParam .class, zzzz).to(MyAdvice.class))
                ).installOn(inst);

how  can  I   get   username  password  xxxx value??  what  kind  zzzz   need  to  bind?

**Comment by raphw** [comment]
This would not require a custom binding. Rather, you would need to get hold of the argument values what is possible by `@Advice.Argument(...)`.

**Comment by cor0ps** [comment]
thanks

**Comment by cor0ps** [comment]
> This would not require a custom binding. Rather, you would need to get hold of the argument values what is possible by `@Advice.Argument(...)`.

so maybe this is not I want ,I want scan all method or all argument which is use @RequestParam Annotation, I want use ByteBuddy distingush which use @RequestParam and get parameter name and last is get parameter value, thanks give some suggets?

**Comment by raphw** [comment]
For this, you'd need to create a custom binding and register it via Advice.withCustomBinding().bind(...).

You can then for example process all arguments and generate a map of values.

Alternatively, you can use good old reflection and the Advice.Origin annotation to process it in your advice method.
