### ISSUE TITLE
Help ide to detect new field 

### ISSUE THREAD

**Issue by AVR-David** [raphw/byte-buddy#1134]
I everyone ,

I want to create new field into an entity but my IDE canno't found it. How i can help my IDE for detected my new field like lombok ?

for example :
```java

public class MyClass {
    public static void main(String args[]) {
      MyEntity entity = new ByteBuddy()
        .subclass(MyEntity.class)
        .defineField("name", String.class, VISIBILITY.Public)
        .make()
        .load(getClass().getClassLoader())
        .getLoaded().newInstance();
      
       System.out.println(entity.name)
    }

   class MyEntity {}

}
```

An idea ?

**Comment by raphw** [comment]
The class will only exist at runtime, without source code. You can dump the class file somewhere (after make) where your IDE scans for class files, but there's no obvious way.

**Comment by AVR-David** [comment]
so, i need to create plugin for scan new class ?
