### ISSUE TITLE
using byte-buddy in android 5

### ISSUE THREAD

**Issue by MK-42** [raphw/byte-buddy#114]
I'm trying to include byte-buddy in my android app because some lib needs it.

the problem is, that byte-buddy refuses to work because of:

```
Caused by: java.lang.IllegalStateException: This JVM's version string does not seem to be valid: 0
at net.bytebuddy.ClassFileVersion.forCurrentJavaVersion(ClassFileVersion.java:120)
```
the problem is, that the Java.version property in android is just "0" and you can't change that anymore since android 5. So the suggested approach of setting it to some reasonable value before calling byte-buddy does not work.

I saw that there is even a byte-buddy-android and some fix in 0.6.15 that should make it work with android 5, but I can't get it to work.

what to do?

**Comment by raphw** [comment]
You can create an instance using the constructor taking an explicit version, for example:

```java
new ByteBuddy(ClassFileVersion.V1_6);
```

Unfortunately, Android does not well-behave with respect to the standard properties and Byte Buddy could only guess the correct version. Therefore, there is no work around specifying it explicitly.
