### ISSUE TITLE
hasSuperType maybe  advice one  method  many  times

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1140]
when  I  advice   one  method  , I encountered this kind of confusion。

example：
public class Request implements HttpServletRequest 

public interface HttpServletRequest extends ServletRequest

when  i   
```
AgentBuilder.type(not(isAbstract()).and(not(isInterface()))
                        .and(not(isEnum())).and(hasSuperType(containted(“ServletRequest”))))
                        .transform(xxxx)
                        .installOn(instrumentation);
```

I  found   Request   will   add  twice   or  more   advice.

```
 public ServletInputStream getInputStream() throws IOException {
    long l1 = Thread.currentThread().getId();
    System.out.println("xxxxxxx: " + "getInputStream" + " threadId:" + l1 + " type:" + str1 + " " );
    RequestFacade requestFacade1 = this;
    long l2 = Thread.currentThread().getId();
    System.out.println("Source Enter Taint: " + "getInputStream" + " threadId:" + l2 + " type:" + str2 + " ");
    RequestFacade requestFacade2 = requestFacade1;
    if (requestFacade2.request == null)
      throw new IllegalStateException(sm
          .getString("requestFacade.nullRequest")); 
  }
```

how  Can  I  solve  it???

**Comment by raphw** [comment]
This is nothing Byte Buddy can solve. If a method is overridden and invokes its super method, this is nothing that can be detected statically. Only when invoking the advice code, this can be discovered. One way of doing it is by setting some state in the enter advice which is cleared in the exit advice. If a subsequent enter advice discovers that the enter advice flag is already set, it must deactivate itself to avoid the duplicate instrumentation.

**Comment by cor0ps** [comment]
thanks，maybe  i  should  set flag to  it.
