### ISSUE TITLE
Support of Repeatable Annotations

### ISSUE THREAD

**Issue by PhantomYdn** [raphw/byte-buddy#1142]
It will be great if ByteBuddy would support a more convenient way to work with Repeatable Annotations. Right now, for example `declaresAnnotation(is(a))` doesn't work if there is more than 1 repeatable annotation. And to make that work - it requires some extra coding. For example like this:

```java
	public <T extends AnnotationSource> ElementMatcher<T> hasRepeatableAnnotation(AnnotationDescription annotation, TypeDescription containerType) {
		return new ElementMatcher.Junction.AbstractBase<T>() {

			@Override
			public boolean matches(T target) {
				if(target.getDeclaredAnnotations().contains(annotation)) return true;
				AnnotationList list = target.getDeclaredAnnotations().filter(ElementMatchers.annotationType(containerType));
				if(list.isEmpty()) return false;
				else {
					return Arrays.asList(list.getOnly().getValue("value").resolve(AnnotationDescription[].class))
							.contains(annotation);
				}
			}
			
		};
	}
```

**Comment by raphw** [comment]
Byte Buddy normally sticks to byte code conventions, this is more of a javac specific feature. There are many combinations of conditions of what you try to achieve, adding matchers for all possible scenarios would quickly explode. I therefore do not think I want to add this at this point.

**Comment by PhantomYdn** [comment]
@raphw , understand! Thank you for your quick response!
Here is some code that might help others with the same cases:
https://github.com/OrienteerBAP/Transponder/commit/eb21478965f6cc677fc0015a6298de308cbc2931
Especially:
https://github.com/OrienteerBAP/Transponder/commit/eb21478965f6cc677fc0015a6298de308cbc2931#diff-6bff08caa0f11a0b26f0e818f1c1e972fc631c32635bc3534cff67ccecca950aR204-R219
https://github.com/OrienteerBAP/Transponder/commit/eb21478965f6cc677fc0015a6298de308cbc2931#diff-8520948ec01159ae249e08c18c0bcd7233597f05bd94faf0d78afcca19c3a99eR504-R519
Testcase:
https://github.com/OrienteerBAP/Transponder/commit/eb21478965f6cc677fc0015a6298de308cbc2931#diff-0c978694bad7d29811b427515ad2da362e545921ff6c8f1561123b71c36d9d11R50-R111
