### ISSUE TITLE
Moving NamingStrategy.SuffixingRandom.BaseNameResolver was a breaking change

### ISSUE THREAD

**Issue by MatthewRyanRead** [raphw/byte-buddy#1145]
In 1.12.0, the public interface `NamingStrategy.SuffixingRandom.BaseNameResolver` is now `NamingStrategy.Suffixing.BaseNameResolver`.  Naturally, this breaks code that referenced that interface directly, such as Hibernate (see [this code](https://github.com/hibernate/hibernate-orm/blob/016625e/hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BytecodeProviderImpl.java#L89) for example).

Is this intentional?  I can of course submit a PR to Hibernate for this, but it will make it impossible to use new versions of Byte Buddy with older versions of Hibernate.

**Comment by raphw** [comment]
My bad, it's source code compatible but not binary compatible. I'll add deprecated versions of the old interface again and overloaded constructors.

Thanks for reporting!

**Comment by raphw** [comment]
I fixed it on master, I think. Could you build BB and double check?

**Comment by MatthewRyanRead** [comment]
Awesome, `1.12.1-SNAPSHOT` build locally works for me.  Thanks for the quick response!

**Comment by raphw** [comment]
Brilliant, releasing now.
