### ISSUE TITLE
Nexus.TYPE_INITIALIZERS hold classloader forever

### ISSUE THREAD

**Issue by LHanL** [raphw/byte-buddy#1150]
Hi, raphw

First, I really apologize to you for my poor English, and thank you for your patience.

We use byte-buddy's **MethodDelegation** to intercept some target class in order to add some code.

Now we have some **hot deploy** application's **meta space** has **memory leak** after times hot deploy action.
```
AppClassloader --> HotDeployClassloader1 (should been gc)
             |
             |  --> HotDeployClassloader2 (should been gc)
             |
              ...
             |  --> HotDeployClassloaderN (running)
```
We find Nexus.TYPE_INITIALIZERS will hold ClassInjector.UsingReflection and it will hold HotDeployClassloader until  target class begin first instantiation. 

like this.
``` java
public class Clients {
     public static AClient a();

     public static BClient b();
}
```
Both class AClient and BClient we use MethodDelegation to intercept, but only Clients.a() will been invoke, then BClient's LoadedTypeInitializer will be hold by Nexus.TYPE_INITIALIZERS forever, and it lead to HotDeployClassloader can't be gc.

Is there a way solve this?

Thank you for your patience again!

**Comment by raphw** [comment]
Hi, you can disable the Nexus altogether if you set the system property `net.bytebuddy.nexus.disabled` before loading Byte Buddy. That it is injected and holds references does however indicate that the Nexus is used somewhere in your app. It's strange that it is not cleared as it should be so once a class initializes itself.

Are those nexus instances of a particular type that that's the case?

You can also change the type initialization strategy being used in the `make` method of the dynamic type building API, for example by using a passive strategy.

**Comment by LHanL** [comment]
Thanks for reply, I'll try `make`
