### ISSUE TITLE
ClassCastException while invoking a method in an abstract class

### ISSUE THREAD

**Issue by vnandwana** [raphw/byte-buddy#1151]
I'm trying to replace cglib with ByteBuddy in a project and facing some issues.

Replaced cglib's `return methodProxy.invokeSuper(proxy, args);` with the following:

```
TypeCache<Class<?>> typeCache = new TypeCache<>(TypeCache.Sort.SOFT);
Class<?> loadedClass = typeCache.findOrInsert(proxy.getClass().getClassLoader(), proxy.getClass(), () -> new ByteBuddy()
        .subclass(proxy.getClass())
        .method(any())
        .intercept(InvocationHandlerAdapter.of((objProxy, method1, args1) -> method1.invoke(objProxy, args1)))
        .make()
        .load(proxy.getClass().getClassLoader(), Default.INJECTION)
        .getLoaded());

try {
    return proxy.getClass().cast(loadedClass.getConstructor().newInstance());
} catch (final ReflectiveOperationException e) {
    throw new AssertionError("Failed to instantiate proxy class for " + proxy.getClass().getName(), e);
}
```
With this in place, I'm testing the following:
```
public abstract class SomethingDao
{
    @SqlUpdate("insert into something (id, name) values (:id, :name)")
    public abstract void insert(@Bind("id") int id, @Bind("name") String name);

    @SqlQuery("select id, name from something where id = :id")
    public abstract Something findById(@Bind("id") int id);

    public Something findByIdHeeHee(int id) {
        return findById(id);
    }

    public abstract void totallyBroken();
}
```
Unit tests

```
    @Test
    public void testPassThroughMethodWithDaoInAnotherPackage() throws Exception
    {
        SomethingDao dao = handle.attach(SomethingDao.class);
        dao.insert(3, "Cora");

        Something c = dao.findByIdHeeHee(3); // This call is causing the issue, actual method (present in abstract class) is not getting invoked. 
        // This kind of method calls are working in classes that are not abstract.
        assertThat(c, equalTo(new Something(3, "Cora")));
    }
```
Results in 

```
java.lang.ClassCastException: class org.skife.jdbi.v2.sqlobject.TestClassBasedSqlObject$Dao$ByteBuddy$K2PIAHG1$ByteBuddy$Va483UCb cannot be cast to class org.skife.jdbi.v2.Something (org.skife.jdbi.v2.sqlobject.TestClassBasedSqlObject$Dao$ByteBuddy$K2PIAHG1$ByteBuddy$Va483UCb and org.skife.jdbi.v2.Something are in unnamed module of loader 'app')

	at org.skife.jdbi.v2.sqlobject.TestClassBasedSqlObject$Dao$ByteBuddy$K2PIAHG1.findByIdHeeHee(Unknown Source)
	at org.skife.jdbi.v2.sqlobject.TestClassBasedSqlObject.testPassThroughMethod(TestClassBasedSqlObject.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Another test:

```
    @Test(expected = AbstractMethodError.class)
    public void testUnimplementedMethodWithDaoInAnotherPackage() throws Exception
    {
        SomethingDao dao = handle.attach(SomethingDao.class);
        dao.totallyBroken(); // ideally this should throw an exception.
    }
```
Results in `java.lang.AssertionError: Expected exception: java.lang.AbstractMethodError`

**Comment by raphw** [comment]
This does not seem quite right to me:

    (objProxy, method1, args1) -> method1.invoke(objProxy, args1)

You are simply invoking the same method on the instance itself. This should loop forever. Rather, you should invoke on a different instance.

As you are writing your code right now, you are instrumenting `any()` method. Maybe you want to skip non-abstract methods (`not(isAbstract())`) - or only instrument methods with a certain annotation?

**Comment by vnandwana** [comment]
I tried MethodDelegation instead of InvocationHandlerAdapter but the results are the same. Also tried `MethodCall.invokeSuper()`. Tried a few more things by referring to the examples present [here](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/test/java/net/bytebuddy/implementation/MethodCallTest.java).

```
new ByteBuddy()
.subclass(proxy.getClass())
.method(not(isAbstract()))
.intercept(MethodDelegation.to(SampleInterceptor.class))
.make()
.load(proxy.getClass().getClassLoader(), Default.INJECTION)
.getLoaded());
```

```
public class SampleInterceptor {

    @RuntimeType
    public static Object intercept(@SuperCall Callable<?> zuper) throws Exception {
        return zuper.call();
    }
}
```

**Comment by raphw** [comment]
Do you have a branch that is using Byte Buddy? I would need a reproduction and an explanation what you want to achieve.

**Comment by vnandwana** [comment]
[This branch is using ByteBuddy.](https://github.com/vnandwana/killbill-commons/blob/cglib-bytebuddy/jdbi/src/main/java/org/skife/jdbi/v2/sqlobject/SqlObject.java) -- Please check `buildSqlObject(..)` and `invoke(..)` methods.

The goal is to replace cglib with ByteBuddy.
[This branch is using cglib.](https://github.com/killbill/killbill-commons/blob/master/jdbi/src/main/java/org/skife/jdbi/v2/sqlobject/SqlObject.java#L55) 

As you can see in cglib version of [buildSqlObject(..)](https://github.com/killbill/killbill-commons/blob/master/jdbi/src/main/java/org/skife/jdbi/v2/sqlobject/SqlObject.java#L55) method that it creates a handler for DAO's and simply calls the [invoke(..)](https://github.com/killbill/killbill-commons/blob/master/jdbi/src/main/java/org/skife/jdbi/v2/sqlobject/SqlObject.java#L170) which in turn checks the DAO method (could be abstract and non-abstract) and find the appropriate handler and call handler's `invoke(..)` method. But for methods that do not have any handlers, then using `methodProxy.invokeSuper(proxy, args)` it calls the actual method.

Example: 
```
public abstract class SomethingDao
{
    @SqlUpdate("insert into something (id, name) values (:id, :name)")
    public abstract void insert(@Bind("id") int id, @Bind("name") String name);  // Direct call to this method works as its handler's invoke method gets invoked.

    @SqlQuery("select id, name from something where id = :id")
    public abstract Something findById(@Bind("id") int id);

    public Something findByIdHeeHee(int id) { // This method has no handler. methodProxy.invokeSuper() invokes this method but ByteBuddy throws ClassCastException.
        return findById(id);   // This method has a handler, the response is returned successfully but ByteBuddy never gets inside.
    }

    public abstract void totallyBroken(); // This also has no handlers and no body, methodProxy.invokeSuper() tries to invoke and throws an expected AbstractMethodError but ByteBuddy doesn't.
}
```

Please check these three tests:
[TestClassBasedSqlObject.java](https://github.com/vnandwana/killbill-commons/blob/cglib-bytebuddy/jdbi/src/test/java/org/skife/jdbi/v2/sqlobject/TestClassBasedSqlObject.java)
[TestTransactionAnnotation.java](https://github.com/vnandwana/killbill-commons/blob/cglib-bytebuddy/jdbi/src/test/java/org/skife/jdbi/v2/sqlobject/TestTransactionAnnotation.java)
[TestFinalizeBehavior](https://github.com/vnandwana/killbill-commons/blob/cglib-bytebuddy/jdbi/src/test/java/org/skife/jdbi/v2/sqlobject/TestFinalizeBehavior.java)

[Here is the full summary of tests that are failing with ByteBuddy.](https://github.com/killbill/killbill-commons/runs/4210445494?check_suite_focus=true#step:8:2377)

**Comment by vnandwana** [comment]
Did you get a chance to look at the links that I have shared?

**Comment by raphw** [comment]
I think you are confusing cglibs callback with the `InvocationHandlerAdapter` which in a way reflects the proxy API.

You should probably use the `MethodDelegation` API instead. The handler method could look like this:

 ```java
class MyHandler {
  final SqlObject so;
  @RuntimeType
  public Object handle(
    @Origin Method origin,
    @SuperMethod(nullIfImpossible = true) Method delegate, 
    @This Object self,
    @AllArguments Object[] args) {
      ...
  }
}
```

You can delegate to an instance via `MethodDelegation.to(new MyHandler(so))`. If you want to invoke the original method, invoke it on the delegate `Method`, otherwise you will loop. If no super method can be invoked, the value will be `null`.

Make sure to not confuse the annotations with those from `Advice`.

**Comment by vnandwana** [comment]
Thank you for your inputs. It was really helpful. I resolved most of the issues but need help with a couple of more issues.

I'm trying to intercept all method calls and invoke a specific method (`so.invoke(..)`) that in turn calls a method in a different class. In that other method, I'm trying to invoke the super method. To achieve this I created two interceptors, one that invokes `so.invoke(..)` method on all calls and another for invoking a super method. 

Problem:  The intercept method that invokes the super method works in the interceptor that initiated the request (`so.invoke(..)`)  but the same intercept method doesn't in another interceptor that got created in the downstream logic. And I'm not sure how to return the actual response of the super method.

Example:

1. In the following test, a call to `dao.failed(..)` is intercepted by `SqlObjectInterceptor.class` and invokes a `so.invoke(..) ` method. Everything is good till here.
```
        try {
            dao.failed(1, "Ian");
            fail("should have raised exception");
        }
        catch (TransactionFailedException e) {
            assertThat(e.getCause().getMessage(), equalTo("woof"));
        }
```

```
        final SqlObject so = new SqlObject(buildHandlersFor(sqlObjectType), handle);

        TypeCache<Class<?>> typeCache = new TypeCache<>(TypeCache.Sort.SOFT);
        Class<?> loadedClass = typeCache.findOrInsert(sqlObjectType.getClassLoader(), sqlObjectType, () -> new ByteBuddy()
                .subclass(sqlObjectType)
                .method(any())
                .intercept(MethodDelegation.to(new SqlObjectInterceptor(so)))
                .make()
                .load(sqlObjectType.getClassLoader(), Default.INJECTION)
                .getLoaded());

        try {
            return sqlObjectType.cast(loadedClass.getConstructor().newInstance());
        } catch (final ReflectiveOperationException e) {
            throw new AssertionError("Failed to instantiate proxy class for " + sqlObjectType.getName(), e);
        }
```

```
public class SqlObjectInterceptor {

    SqlObject so;

    public SqlObjectInterceptor(final SqlObject so) {this.so = so;}

    @RuntimeType
    public Object intercept(@This Object target,
                            @Origin Method method,
                            @SuperMethod(nullIfImpossible = true) Method superMethod,
                            @AllArguments Object[] args) throws Throwable {

        return so.invoke(target, method, args, so);
    }
```

2. This `so.invoke(..)` performs some logic and triggers a method. In that new method call, I'm trying to add another interceptor or use the same one and invoke the super method and return the response.

```
    @Override
    public Object invoke(HandleDing ding, final Object target, final Object[] args)
    {
        ding.retain("pass-through-transaction");
        try {
            Handle h = ding.getHandle();
            if (isolation == TransactionIsolationLevel.INVALID_LEVEL) {
                return h.inTransaction(new TransactionCallback<Object>()
                {
                    @Override
                    public Object inTransaction(Handle conn, TransactionStatus status) throws Exception
                    {
                        try {
                            **// Super method needs to be invoked here and return its response. Just like cglib's return `methodProxy.invokeSuper(proxy, args);`**
                                    Class<?> loadedClass =  new ByteBuddy()
                                    .subclass(target.getClass())
                                    .method(any())
                                    .intercept(MethodDelegation.to(MethodProxyHandler.class))
                                    .make()
                                    .load(target.getClass().getClassLoader(), Default.INJECTION)
                                    .getLoaded();
                            try {
                                return target.getClass().cast(loadedClass.getConstructor().newInstance());
                            } catch (final ReflectiveOperationException e) {
                                throw new AssertionError("Failed to instantiate proxy class for " + target.getClass().getName(), e);
                            }
                        }
                        catch (Throwable throwable) {
                            if (throwable instanceof Exception) {
                                throw (Exception) throwable;
                            }
```

3.) The following intercept method in the newly created `MethodProxyHandler.class` throws IllegalArgumentException:

```
    @RuntimeType
    public Object intercept(@Origin Method method,
                            @SuperCall Callable<?> proxy,
                            @SuperMethod() Method superMethod,
                            @This Object target,
                            @AllArguments Object[] args) throws Throwable {

        // return superMethod.invoke(target, args);
        return proxy.call();
    }
```

```
java.lang.IllegalArgumentException: None of [] allows for delegation from public boolean org.skife.jdbi.v2.sqlobject.TestTransactionAnnotation$Dao$ByteBuddy$6EVc9xW7.equals(java.lang.Object)

	at net.bytebuddy.implementation.bind.MethodDelegationBinder$Processor.bind(MethodDelegationBinder.java:1096)

```

**Comment by raphw** [comment]
SuperCall also has a nullIfImpossible attribute. An abstract method would be overridden with null for this value as no super method can be invoked. In cglib, this would cause an AbstractMethodError.
