### ISSUE TITLE
Incorrect type with generic interface

### ISSUE THREAD

**Issue by DvSmi** [raphw/byte-buddy#1152]
I'm trying to resolve following code to get a interface which is 
```
@Test
   void test() {
      var typeDescription = TypeDescription.Generic.Builder.parameterizedType( TestInterface.class, String.class ).build();
      var loader = typeDescription.getClass().getClassLoader();
      var bbClass = new ByteBuddy()
            .makeInterface( typeDescription )
            .make()
            .load( loader )
            .getLoaded();
      print( bbClass );
   }

   public interface TestInterface<T> {
      String getString( T returnString );
   }

   private void print( Class<?> clazz ) {
      Arrays.stream( clazz.getMethods() ).forEach( System.out::println );
   }
```

I would expect the outcome to be like 
`public abstract java.lang.String test.ByteBuddyTest$TestInterface.getString(java.lang.String)`
with a String as the method parameter but its 
`public abstract java.lang.String test.ByteBuddyTest$TestInterface.getString(java.lang.Object)`
instead. What am i missing?

**Comment by raphw** [comment]
The interface inherits the method. You can override it and redefine it without code (as abstract). Then the reflection API pucks it up. Otherwise, it just shows ypu the original declaration.
