### ISSUE TITLE
Gradle plugin fails when java classpath is empty

### ISSUE THREAD

**Issue by deje07** [raphw/byte-buddy#1157]
During a Gradle build, if the java compile task has no input (empty project), the execution of the ByteBuddy plugin will fail with the following message:

```
A problem was found with the configuration of task ':lib:byteBuddy' (type 'ByteBuddyTask').
  - In plugin 'net.bytebuddy.byte-buddy-gradle-plugin' type 'net.bytebuddy.build.gradle.ByteBuddyTask' property 'source' specifies directory '.../byte-buddy-test/lib/build/classes/java/raw' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
    Possible solutions:
      1. Make sure the directory exists before the task is called.
      2. Make sure that the task which produces the directory is declared as an input.
    
    Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.
```

I think the source of the problem is that when there are no input classes, the **JavaCompile** task will be skipped, and will not create its output directory under `build`, so the `raw` subdirectory cannot be created as well.

I had a little experiment with the class [`ByteBuddyTask`](https://github.com/raphw/byte-buddy/blob/da957be7391387e11391664188da2e5e52277be5/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/ByteBuddyTask.java) and if I annotate the property `classPath` with `@SkipWhenEmpty` then in this case the ByteBuddy plugin task will also be skipped, just like the JavaCompile.

```java
    @InputFiles
    @CompileClasspath
    @SkipWhenEmpty
    public abstract ConfigurableFileCollection getClassPath();
```

Setting the same annotation for the property `source` does not work. I'm not sure if this is the proper way to solve this issue (relying on classpath instead of `.class` file directory), but seems legitimate.

The very simple project used for testing is here: [byte-buddy-test.zip](https://github.com/raphw/byte-buddy/files/7562090/byte-buddy-test.zip)

**Comment by raphw** [comment]
Thanks, this makes sense in a way. I do however wonder if this is the right approach. As you say yourself, the `@SkipWhenEmpty` annotation should be placed on the `source` property; there might just be a class path with nothing to compile in your particular project.

I will see if I can get feedback from someone who knows Gradle better then me! [I found this workaround, maybe this is still the way to go.](https://github.com/gradle/gradle/issues/2919)

**Comment by oehme** [comment]
You can mark it as `@InputFiles` instead of `@InputDirectory`. Then Gradle won't care whether it actually exists. `@InputDirectory` is specifically designed to fail if the given thing is not an existing directory.

**Comment by raphw** [comment]
Brilliant, that sounds like a good suggestion. Does this work for you @deje07 ? I'd appreciate if you can try this for your project.

**Comment by raphw** [comment]
I changed it on master. Can you give it a try @deje07?

**Comment by raphw** [comment]
Please ping me if this did not solve the problem.

**Comment by deje07** [comment]
Hi! Sorry I was busy with other tasks, will have time for this tomorrow!

BR,
Gabor

Rafael Winterhalter ***@***.***> ezt írta (időpont: 2021.
nov. 22., H 21:45):
