### ISSUE TITLE
JavaConstant.Dynamic.bootstrap() does not work when bootstrap method not declared by the constant type

### ISSUE THREAD

**Issue by bgaraude** [raphw/byte-buddy#1158]
When using the JavaConstant.Dynamic.bootstrap(String, <bootstrapMethod>, <args>) methods with a static bootstrap method, it seems required that the bootstrap method is declared by the constant type.

In byte buddy's unit tests, it's all green because the tested constants are of DynamicConstantBootstrap type, and all the bootstrap static methods are also declared by this type.
 
 If you look at the following gist, it no longer works when the bootstrap method is not declared by the constant type:
 https://gist.github.com/bgaraude/9649bddb78bfd7812d0f5f1991fb1d55

I have only a little experience with condy, so I'm not sure if this is expected or not.

But it seems that in net.bytebuddy.utility.JavaConstant.java:2146, the static bootstrap method's return type is passed rather than the declaring type to the 2nd argument of MethodHandle's constructor. Which should be the ownerType.
If I replace the return type with the declaring type at this location, then it works fine.

I experience this on 1.12.1

**Comment by raphw** [comment]
You're right, that's a bug. Thanks for reporting, I'll fix this in the next release.

**Comment by raphw** [comment]
It's fixed on master and I added a test.
