### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: 

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1159]
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.taint.agent.Agent
	at java.lang.Runtime.getRuntime(Runtime.java:58)
Advice:
```
 public static void MethodBefore(@Advice.Origin("#t") String type, @Advice.Origin("#m") String method, @Advice.Origin("#s") String sig, @Advice.AllArguments Object[] args) {
        InputStream in= Configuration.class.getResourceAsStream("/methods.yaml");
        Map conf =new Yaml().load(in);
        LinkedHashMap sinks = (LinkedHashMap) conf.get("sinks");
        System.out.println(sinks.size());
```

ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation).inject(map);
this method can't be satisfied in this way, and I can't load all the classes of sneakyaml one by one

and  I   add this  method  to solve:

instrumentation.appendToBootstrapClassLoaderSearch("snakeyaml.jar")

but  also  not  take effect，how  can  I  solve  it?  can  give  me  a  example?

**Comment by raphw** [comment]
You need to put the `Yaml` bit into a different method (ideally class) to avoid premature loading. Often, the JVM validates an entire method or even class file in one chunk before executing any code. This is why you get this error.

Ideally, you run your premain as follows:

```java
public void premain(String args, Instrumentation inst) {
  inst.appendToBootstrapClassLoaderSearch(...)
  Class.forName("my.actual.Dispatcher").getMethod("myagent").invoke(null);
}
```

**Comment by cor0ps** [comment]
thanks
