### ISSUE TITLE
How to edit laoded class

### ISSUE THREAD

**Issue by hugoviktor** [raphw/byte-buddy#1160]
Hello! 
My agent receives new classes to intercept through a websocket, when I try to redefine that class an error "classes have already been loaded" is generated. So my question is: how can I redefine classes that are already loaded. And another question: can the matcher be redefined at runtime with a new class name that I receive via the websocket?
Thanks a lot for amazing lib.

**Comment by raphw** [comment]
Have a look at AgentBuilder which offers to register a RetransformationStrategy. Doing so, you can retransform existing classes.
