### ISSUE TITLE
Support for Gradle configuration cache

### ISSUE THREAD

**Issue by jprinet** [raphw/byte-buddy#1163]
The [Gradle configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html) can't be enabled when using byte-buddy Gradle plugin.

Using a reference to the Project object at runtime is not supported:
https://github.com/raphw/byte-buddy/blob/aaf0017b1a867396d4a1ef62815f5bb2894fba0c/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/AbstractByteBuddyTask.java#L367

**Comment by raphw** [comment]
I added a possibility to configure the class file version in the extension. This way, the bit with `getProject` is not invoked. I do however wonder if there is a possibility to still default to the Java plugin's version and allowing to use the configuration cache? I am happy to take any suggestion.

**Comment by eskatos** [comment]
Hi Rafael,

The target compatibility is an input to the task, so it should be expressed as such a property:

```java
public abstract class AbstractByteBuddyTask extends DefaultTask {
    @Input public abstract Property<String> getClassFileJavaVersion();
}
```

Then when you configure the task you can wire a conventional value for this input from the Java extension, something like the following:

```java
JavaPluginConvention convention = (JavaPluginConvention) getProject().getConvention().getPlugins().get("java");
byteBuddyTask.getClassFileJavaVersion().convention(convention.getTargetCompatibility());
```

This basically moves grabbing data from the `Project` at configuration time.

Now if you want to expose the classFileVersion on your ByteBuddy extension you can set the property as above on your extension instead of a task and then wire your extension's property to the one on the task.

HTH

Cheers

**Comment by raphw** [comment]
Would I call the above code from the task implementation, still? 

According to the ticket, it's the `getProject()` call that is the problem. Given this solution, it would not be an improvement to change the code in this way.

I still support rather old Gradle versions (v2) since code instrumentation is a very handy approach for maintaining legacy systems, therefore I would ideally want to avoid depending on `Property`.

**Comment by eskatos** [comment]
> Would I call the above code from the task implementation, still?

If you mean the second snippet in my comment above, no, you would do that in your `Plugin`, at configuration time, when configuring the task, thus removing the access to `Project` from execution time.

> I still support rather old Gradle versions (v2) since code instrumentation is a very handy approach for maintaining legacy systems, therefore I would ideally want to avoid depending on Property.

If you can't use Gradle >2 it's doable bit will be a bit more clumsy:

Like with newer Gradle versions, declare the classFileVersion as in input to your task but as a Java bean property:

```java
public abstract class AbstractByteBuddyTask extends DefaultTask {
    private String classFileJavaVersion;
    @Input public String getClassFileJavaVersion() { return  classFileJavaVersion; }
    public void setClassFileJavaVersion(String classFileJavaVersion) { this.classFileJavaVersion = classFileJavaVersion; }

    // In the task action, at execution time, you only get that simple String property
}
```

Then in your plugin, you need to rely on `project.afterEvaluate {}` to read the Java plugin convention late, and configure the task input with its value:

```java
public class ThePlugin implements Plugin<Project> {
    @Override public void apply(Project project) {
        SomeBuddyTask task = project.tasks.create("someTaskName", SomeBuddyTask.class)
        project.afterEvaluate {
            JavaPluginConvention convention = (JavaPluginConvention) project.getConvention().getPlugins().get("java");
            task.setClassFileJavaVersion(convention.getTargetCompatibility().getMajorVersion());
        }
    }
}
```

**Comment by raphw** [comment]
Thanks for the hint, I changed the plugin to hopefully support it.

While I have you: I resolve Byte Buddy's `ClassFileVersion` to an `int` right now as the incremental build feature does not seem to support `null` values. Is there a way around this or is this the way to go?

**Comment by eskatos** [comment]
Great!

If you want to make sure your plugin supports configuration caching now and onwards you can enable it in your tests. Enabling the configuration cache adds more strictness to the Gradle runtime so if it works with it enabled, it'll work with it disabled. I recommend enabling the configuration cache by default in your tests. If you have cross-Gradle-version testing you can do that starting with the Gradle version for which your plugin works with the configuration cache. Gradle 7.0 should be a good target.

> While I have you: I resolve Byte Buddy's ClassFileVersion to an int right now as the incremental build feature does not seem to support null values. Is there a way around this or is this the way to go?

A task `@Input` is required to have a value by default, you can change that to is accepts `null` by marking it as `@Optional`.

**Comment by raphw** [comment]
Thanks, I fixed this and enabled the cache during the build.

It will be included in the next release.

**Comment by raphw** [comment]
Fixed on master.

**Comment by eskatos** [comment]
Awesome!

BTW I meant to enable the configuration cache in the Gradle plugin integration tests not in the Gradle plugin build.

**Comment by raphw** [comment]
Right, I changed it, thanks for spotting!

**Comment by eskatos** [comment]
One more little thing, ideally you don't need `-Dorg.gradle.unsafe.configuration-cache-problems=warn`.
This option basically ignores problems.
