### ISSUE TITLE
Interceptor not working when attaching agent dynamically?

### ISSUE THREAD

**Issue by newk5** [raphw/byte-buddy#1164]
Hey, I had a simple static agent that I attached with -javaagent and everything worked fine. Now I tried changing it to work dyamically, meaning my application is attaching it instead of using -javaagent and the method interceptor no longer works, it's not being called for any method, am I doing something wrong ? Here's my code:

```java
 public static void agentmain(String args, Instrumentation instrumentation) throws URISyntaxException {

        ElementMatcher.Junction matches = ElementMatchers.nameStartsWith("fullPackagenameHere");
        new AgentBuilder.Default().type(matches)
                
                .transform((builder, typeDescription, classLoader, module) -> builder
                .method(ElementMatchers.any())
                .intercept(MethodDelegation.to(new Interceptor())))
                .installOn(instrumentation);
        System.out.println(">>>>>>>>>>>>>>>>>>>>> INITIALIZED AGENT");

    }
```
Interceptor:
```java
public class Interceptor {

    @RuntimeType
    public Object intercept(@SuperCall Callable<?> callable, @AllArguments Object[] allArguments, @Origin Method method, @Origin Class clazz) throws Exception {

        System.out.println("CALLED EVENT " + method.getName());

        Object response;
        try {
            response = callable.call();
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
        return response;

    }

}
````

I can see the "INITIALIZED AGENT" print when I attach the agent so I know it's being attached, but the interceptor is never called.
The exact same code works fine if I rename agentmain to premain and attach it statically with -javaagent

**Comment by newk5** [comment]
Ok so I thought myabe my "matches" junction was wrong and tried to change the "matches" junction to: ElementMatchers.any() and check to see if the methods I wanted to intercept were being intercepted, and it turns out they weren't, even using ElementMatchers.any() they're never intercepted, it seems like they're being ignored for some reason, it intercepts pretty much all other methods except the ones I need, I dont understand why.

However when attaching the agent statically with -javaagent, they're being intercepted correctly, it just doesn't work when the agent is attached dynamically.

The methods I'm trying to intercept are CDI/Managed beans in a JSF web application running on tomcat (not sure if this matters)

**Comment by raphw** [comment]
Might the class in question already be loaded when you attach your agent dynamically? You have not specified any retransformation, therefore loaded types will not be included.

Note that retransformation limits your retransformation capabilities and you might need to use `Advice` instead of `MethodDelegation`. The former is a little more constrained for this reason.

Typically, you'd `.disableClassFormatChanges()` when working with retransformation as most JVMs do not support this.

**Comment by newk5** [comment]
Yes I believe the classes are already loaded by the time the agent is attached. My use case is very simple I just want to measure how long methods take to execute, I have also tried to use advice but I get the same issue. I don't understand how I can use "retransformation", how would I change my code to use it ?

At the moment I changed it to use an Advice so this is what I'm using:
```java
 new AgentBuilder.Default().type(matches)
                .transform((builder, type, classLoader, module)
                        -> builder.visit(Advice.to(TimerAdvice.class).on(ElementMatchers.any())))
                .installOn(instrumentation);
````
What do I need to change to use restransformation?

**Comment by raphw** [comment]
Add .with(RedefinitionStrategy.RETRANSFORMATION) to the agent builder. Ideally, also disable class file transformation and use advice.

**Comment by newk5** [comment]
Ok I did that but now when I attach the agent I'm getting an exception::
```
Caused by: java.lang.IllegalStateException: Could not install class file transformer
java.lang.UnsupportedOperationException: adding retransformable transformers is not supported in this environment
	at sun.instrument.InstrumentationImpl.addTransformer(InstrumentationImpl.java:88)
```

This is my code:
```java
 new AgentBuilder.Default().disableClassFormatChanges().with(RedefinitionStrategy.RETRANSFORMATION)
                .type(matches)
                .transform((builder, type, classLoader, module) -> builder.visit(Advice.to(TimerAdvice.class).on(ElementMatchers.any())))
                .installOn(instrumentation);
```
TimerAdvice class:
```java
public class TimerAdvice {

    @Advice.OnMethodEnter
    static long enter() {
        return System.currentTimeMillis();
    }

    @Advice.OnMethodExit()
    static void exit(@Advice.Origin String method, @Advice.Enter long start) {
        System.out.println(method + " took " + (System.currentTimeMillis() - start));
    }
}

```
Did I do something wrong or is this just not supported for my use case?

**Comment by raphw** [comment]
You need to enable retransformation in your agents manifest. Otherwise, the JVM will disallow it.

**Comment by newk5** [comment]
I see. My manifest.mf at the moment has the Agent-Class entry, what is the retransformation  entry that I need to add?

**Comment by raphw** [comment]
It's defined by the reference: https://docs.oracle.com/javase/9/docs/api/java/lang/instrument/package-summary.html

**Comment by newk5** [comment]
Oh I see what you mean, I thought it was a bytebuddy specific entry, it's all working now, thank you for helping.

**Comment by Rablidad** [comment]
Great!
