### ISSUE TITLE
Advice/Interceptors not working when the class is from a shaded dependency

### ISSUE THREAD

**Issue by gauravat16** [raphw/byte-buddy#1165]
Hi!

We have a java runtime agent which is based on byte-buddy. It uses couple of dependencies like codahale metrics, hystrix etc. 
As these dependencies can also be used in the application where the agent is added at runtime, we shaded them. This allows us to avoid version mismatches etc.

Now if the advice or interceptor is on `com.codahale....Timer` class or some other class in the shaded dependencies, they aren't _intercepted_.

To further debug this, I tried loading the class by : `AgentStart.class.getClassLoader().loadClass("com.codahale....Timer")`, but I got the Class object of `shaded.com.codahale....Timer.`

**Comment by raphw** [comment]
Yes, the shading plugin replaces all references, including strings. What you can do is that you shade the dependencies in a seperate module and then only include this shaded module in your agent, without shading.

But even more elegant: You do not shade at all (only include) and then create a so-called trampoline agent. This trampoline agent only contains your real agent as a nested jar file. Then, you unpack this jar file somewhere and create a new URLClassLoader in your trampoline agent where you reference this class file with the boot or extension class loader as a parent. This new class loader will then be fully seperate from the class path and not colide thanks to a seperate class loader while keeping the original name.

Just make sure to exclude this agent class loader from instrumenting.
