### ISSUE TITLE
Applying MemberSubstitution on newly defined elements

### ISSUE THREAD

**Issue by Gingerbreadz** [raphw/byte-buddy#1166]
Hi!

When applying a member substitution on fields or methods defined during the instrumentation, the visitor fails to find these elements.

Code example:
```java
builder.defineMethod("getFoo", int.class).intercept(FieldAccessor.ofField("foo"))
       .visit(MemberSubstitution.relaxed()
       .field(named("bar")).onRead()
       .replaceWithMethod(named("getFoo"))
       .on(any())
```
Same behavior with `defineField` and `replaceWithField`

Error:
```
java.lang.IllegalStateException: Not exactly one method that matches (name(equals("getFoo"))): []
```

Is this usage not intended ? i.e. using the matching method/field resolver for defined elements instead of the explicit resolver for field/method descripton

If not, looks like this can be fixed by looking for field/methods from the instrumentedType referenced in the resolver. I'm attaching a PR #1166  with the relevant changes and test scenarios.

**Comment by Gingerbreadz** [comment]
#1167

**Comment by raphw** [comment]
Good point, that's a better solution indeed. I merged your PR.
