### ISSUE TITLE
Configurable error handling strategy in Gradle/Maven plugins

### ISSUE THREAD

**Issue by deje07** [raphw/byte-buddy#1168]
When using ByteBuddy from Gradle or Maven, the error handling strategy of the `Plugin.Engine.Default` can only be configured in a very limited way, even might be causing unexpected behavior.

For example the `FAIL_FAST` handler is optional (configured via `failFast` parameter), but if this handler is not installed, then there will be no failing error handlers configured! This implies that even if processing error occurs, no `Exception` will be forwarded to the Gradle or Maven build engine, causing the build to succeed and not to fail. While this behavior might be reasonable in some cases, the user must be very well aware that disabling fail fast will disable error handling all together. If we wanted `FAIL_LAST` behavior, it is not possible to be configured. 

I'd suggest that disabling `failFast` should automatically enable `FAIL_LAST`, or if no fail error handling is needed, there should be a separate parameter for that (like `skipErrors` or something). It might also be a good idea to expose the `errorHandlers` as a configurable property, so maximum control can be achieved, or even customized error handlers could be used from Gradle or Maven.

**Comment by raphw** [comment]
Thanks, that's an oversight. I registered the fail last. I do not want an easy way to disable failing altogether, this would create rather random builds. Thanks!
