### ISSUE TITLE
ByteBuddy gradle task are not cache-friendly

### ISSUE THREAD

**Issue by iNikem** [raphw/byte-buddy#1169]
All subclasses of `AbstractByteBuddyTask` define some `@InputDirectory` or `@InputFile` Gradle property and do not specify any [PathSensitivity](https://docs.gradle.org/current/userguide/build_cache_concepts.html#relocatability). Therefore the results of those tasks cannot be re-used from Gradle cache when run on different computers.

All file-based inputs of these tasks probably should use [PathSensitivity.RELATIVE](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/PathSensitivity.html#RELATIVE)

**Comment by raphw** [comment]
Good point, I was not aware of this option, I thought this was the default.

I will add this in the next release, thanks.

**Comment by raphw** [comment]
I added it to master. But I have no idea of it, could you test to see if it works as expected?

**Comment by iNikem** [comment]
I tried to build your main branch locally, but my build scan still shows that `ByteBuddySimpleTask` uses "Normalization: absolute path". Although the source seems correct. Is it possible that vendoring in Gradle classes breaks this? How is it expected to work, if you don't use `org.gradle.api.tasks.PathSensitivity` but `net.bytebuddy.build.gradle.api.PathSensitivity`?

**Comment by raphw** [comment]
They are supposed to be ASM translated. Let me dee if this does not work for some reason.

**Comment by iNikem** [comment]
Hm, final jar does contain correct class references... I will debug further

**Comment by raphw** [comment]
Can you try again?

**Comment by iNikem** [comment]
Damn I was starting at this for like 2 minutes and did not notice:D 
```
    RuntimeVisibleAnnotations:
      0: #44()
        org.gradle.api.tasks.InputDirectory
    RuntimeInvisibleAnnotations:
      0: #45(#46=e#47.#48)
        org.gradle.api.tasks.PathSensitive(
          value=Lorg/gradle/api/tasks/PathSensitivity;.RELATIVE
        )
```

Will try at once

**Comment by iNikem** [comment]
It works not. Thank you! :)

**Comment by raphw** [comment]
Fixed on master.
