### ISSUE TITLE
Gradle plugin fails for incremental builds after removing all sources from source set

### ISSUE THREAD

**Issue by rmlekus** [raphw/byte-buddy#1170]
When using the gradle plugin (1.12.2, 1.12.3) in the context of incremental java builds, the  byte-buddy gradle plugin fails with an exception when applied after removing all `.java` sources for a gradle source set (following a build with >=1 .java sources in the very same source set.

References: 
  - [#1157 Gradle plugin fails when java classpath is empty](#1157) describing a related problem when building a gradle project without sources for an initial build (@deje07 fyi)
  - https://github.com/rmlekus/empty-inc-bytebuddy-gradle-build-test providing a minimal gradle test project checking for the functionality of gradle incremental builds based on adding and/or removing sources from a gradle main source set including tests for building a source set with 0 sources.  [test-incremental-builds.sh](https://github.com/rmlekus/empty-inc-bytebuddy-gradle-build-test/blob/main/test-incremental-builds.sh) will execute a sequence of gradle builds with
     - initially 0 `.java` source files in the main source set (works as expected ✅ )
     - after adding a single source file (works as expected ✅ )
     - after adding a further source file (works as expected ✅ )
     - after adding a third and removing one of the previously added source files  (works as expected ✅ )
     - after removing all source files again ( 💣   - build fails with stack-trace )
- [build.log](https://github.com/raphw/byte-buddy/files/7662855/build.log) - the gradle build log and exception encountered after removing all `.java` files from the `main` java source set of the example project
- shortened stack trace (for quick reference):

   ```
   * Exception is:
   org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':byteBuddy'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
   ...
   Caused by: java.lang.IllegalStateException: Failed to transform class files in /Users/robert/git/byte-buddy-test/empty-inc-bytebuddy-gradle-build-test/build/classes/java/raw
        at net.bytebuddy.build.gradle.AbstractByteBuddyTask.doApply(AbstractByteBuddyTask.java:425)
        at net.bytebuddy.build.gradle.ByteBuddyTask.apply(ByteBuddyTask.java:132)
        at jdk.internal.reflect.GeneratedMethodAccessor538.invoke(Unknown Source)
   ...
   Caused by: java.nio.file.NoSuchFileException: /Users/robert/git/byte-buddy-test/empty-inc-bytebuddy-gradle-build-test/build/classes/java/raw
         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
        at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
        at java.base/java.nio.file.Files.copy(Files.java:1295)
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor528.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.bytebuddy.utility.Invoker$Dispatcher.invoke(Unknown Source)
        at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForStaticMethod.invoke(JavaDispatcher.java:950)
        at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1142)
        at net.bytebuddy.utility.$Proxy108.copy(Unknown Source)
        at net.bytebuddy.utility.FileSystem$ForNio2CapableVm.copy(FileSystem.java:150)
        at net.bytebuddy.build.Plugin$Engine$Target$ForFolder.retain(Plugin.java:3354)
        at net.bytebuddy.build.Plugin$Engine$Default.apply(Plugin.java:4456)
        at net.bytebuddy.build.gradle.AbstractByteBuddyTask.doApply(AbstractByteBuddyTask.java:423)
        ... 125 more
   ```

**Comment by raphw** [comment]
Could you try building master of Byte Buddy and see if my recent commit fixed this issue? I am note quite sure how the source can detect files if the source folder does not even exist. It should already fail when attempting an iteration.

**Comment by rmlekus** [comment]
After checking out  [byte-buddy/commit/c253ad2c05628820cf12c7597cb3283af991e452](https://github.com/raphw/byte-buddy/commit/c253ad2c05628820cf12c7597cb3283af991e452)  and ensuring that gradle would refresh it's SNAPSHOT dependencies  in the test project via https://github.com/rmlekus/empty-inc-bytebuddy-gradle-build-test/commit/f1b875f56e809122fe9d87a733c4f6d776ed2874 the error still occurs:

Debug Log: [build.log](https://github.com/raphw/byte-buddy/files/7664038/build.log)

**Comment by rmlekus** [comment]
> After checking out [byte-buddy/commit/c253ad2c05628820cf12c7597cb3283af991e452](https://github.com/raphw/byte-buddy/commit/c253ad2c05628820cf12c7597cb3283af991e452) and ensuring that gradle would refresh it's SNAPSHOT dependencies in the test project via [rmlekus/empty-inc-bytebuddy-gradle-build-test@f1b875f](https://github.com/rmlekus/empty-inc-bytebuddy-gradle-build-test/commit/f1b875f56e809122fe9d87a733c4f6d776ed2874) the error still occurs:
> 
> Debug Log: [build.log](https://github.com/raphw/byte-buddy/files/7664038/build.log)

A quick check reveals, that the changes in  [byte-buddy/commit/c253ad2c05628820cf12c7597cb3283af991e452](https://github.com/raphw/byte-buddy/commit/c253ad2c05628820cf12c7597cb3283af991e452)  did not affect the issue because the affected build is an incremental build running through 

` ByteBuddyTask_Decorated(ByteBuddyTask).apply(InputChanges) line: 120	 `

resulting in source pointing to the non existent "raw" directory:
![image](https://user-images.githubusercontent.com/2836548/144937623-d9c1c17f-dd18-4a19-af91-36d2f9eb13ff.png)

```shell
$ ls -ld /Users/robert/git/byte-buddy-test/empty-inc-bytebuddy-gradle-build-test/build/classes/java/raw
ls: /Users/robert/git/byte-buddy-test/empty-inc-bytebuddy-gradle-build-test/build/classes/java/raw: No such file or directory
```

**Comment by rmlekus** [comment]
After modifying the calculation of `source` in
```
iff --git a/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/ByteBuddyTask.java b/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/ByteBuddyTask.java
index 2cd3fd81c6..9a48747f92 100644
--- a/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/ByteBuddyTask.java
+++ b/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/ByteBuddyTask.java
@@ -118,11 +118,13 @@ public abstract class ByteBuddyTask extends AbstractByteBuddyTask {
         Plugin.Engine.Source source;
         if (inputChanges.isIncremental() && getIncrementalResolver() != null) {
             getLogger().debug("Applying incremental build");
-            source = new IncrementalSource(source(), getIncrementalResolver().apply(getProject(),
+            source = source().exists()
+                    ? new IncrementalSource(source(), getIncrementalResolver().apply(getProject(),
                     inputChanges.getFileChanges(getSource()),
                     source(),
                     target(),
-                    classPath()));
+                    classPath()))
+                    : Plugin.Engine.Source.Empty.INSTANCE;
         } else {
             getLogger().debug("Applying non-incremental build");
             if (getProject().delete(getTarget().getAsFileTree())) {
```

the gradle comileJava and byteBuddy tasks completed without any exception, but at the end the .class files for the two `.java` files deleted remained in the `build/classes/java/main/` folder where they were generated by the `byteBuddy` in the preceding build (before removing `HelloByteBuddy3.java and HelloByteBuddy2.java` as of [test-incremental-builds.sh#L45[https://github.com/rmlekus/empty-inc-bytebuddy-gradle-build-test/blob/f1b875f56e809122fe9d87a733c4f6d776ed2874/test-incremental-builds.sh#L45)

```shell
$ find src/main build/classes -name \*.java -o -name \*.class 
build/classes/java/test/IncrementalByteBuddyTest.class
build/classes/java/main/HelloByteBuddy3.class
build/classes/java/main/HelloByteBuddy2.class
```

**Comment by raphw** [comment]
Can you try the latest master? I added an explicit check for the incremental resolver.

What I do not understand is that the incremental resolver returns any files if all files are removed. I would not expect entries with `ADDED` or `MODIFIED` then. If you have an opportunity, please check the resolver for what entries are returned. This might just be a bug in Gradle.

**Comment by rmlekus** [comment]
Actually the changes forwarded to `net.bytebuddy.build.gradle.IncrementalResolver.ForChangedFiles` really look incorrect:

Setting a break point at [net/bytebuddy/build/gradle/IncrementalResolver.java#L58](https://github.com/raphw/byte-buddy/blob/9b477f578ae44d43ce7b05d4285ae28d06f91fcc/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/IncrementalResolver.java#L58) when running step 6 of my test script [test-incremental-builds.sh#L61](https://github.com/rmlekus/empty-inc-bytebuddy-gradle-build-test/blob/e5e6b510e3467545ed41a74e69105cc7f1541c8a/test-incremental-builds.sh#L61) :

- previous build performed with two source code files `HelloByteBuddy2.java`, and `HelloByteBuddy3.java` in  the main source set of the build
- removing the two Java source code files from the main source set (leaving the project with an "empty" source set
- executing an (incremental) gradle build 

provided the following changes:

```
[
Input file /Users/robert/git/empty-inc-bytebuddy-gradle-build-test/build/classes/java/raw has been removed., 
Input file /Users/robert/git/empty-inc-bytebuddy-gradle-build-test/build/classes/java/raw/HelloByteBuddy2.class has been removed., 
Input file /Users/robert/git/empty-inc-bytebuddy-gradle-build-test/build/classes/java/raw/HelloByteBuddy3.class has been removed., 
Input file /Users/robert/git/empty-inc-bytebuddy-gradle-build-test/build/classes/java/raw has been added.
]
```

The first 3 (removed raw folder - as compileJava did actually delete the former raw output folder, as well as the two removed .class files are as one would expect.

The question is why there is the final/additional added "Input file"  for the raw folder which no longer does exist!?

# PS:

1. With the last patch (causing the last added raw folder to be ignored", the little test program starts to work as expected.

2.  Compiling master currently triggers:
```
net.bytebuddy.build.gradle.IncrementalResolverForChangedFilesTest > testIncrementalChange FAILED
    java.lang.AssertionError at IncrementalResolverForChangedFilesTest.java:34

6 tests completed, 1 failed
```

![image](https://user-images.githubusercontent.com/2836548/145007464-da2fb6f2-f3b1-46c2-97a7-d037d11a1054.png)

so I actually disabled (quick hack) unit testing in both maven and gradle builds for byte-buddy + the byte-buddy-gradle-plugin

**Comment by rmlekus** [comment]
> Actually the changes forwarded to `net.bytebuddy.build.gradle.IncrementalResolver.ForChangedFiles` really look incorrect:

Tests were performed with gradle wrapper 7.3 (distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-bin.zip)
and 7.3.1 (release Dec 1st, 2021 - https://gradle.org/releases/)

**Comment by raphw** [comment]
Tests should work now, by the way. Thanks for verifying.
