### ISSUE TITLE
Record component attribute read fails when using multiple annotations

### ISSUE THREAD

**Issue by 0utplay** [raphw/byte-buddy#1175]
Hello,

when using Mockito (4.1.0) in combination with the inline generator, re-transforming a record will cause an exception if there are two parameter types which are annotated (unsure if the exception is caused because of ByteBuddy or asm). Platform: `temurin 17.0.1` @ `Windows 11`.

This will pass;
```java
package com.example;

import org.jetbrains.annotations.NotNull;

public record ChannelTest(@NotNull String test) {
}
``` 
as well as:
```java
package com.example;

import org.jetbrains.annotations.NotNull;

public record ChannelTest(String test, @NotNull String test2) {
}
```

But if we add `@NotNull` to the first and second parameter OR we're annotating just the first parameter like this:
```java
package com.example;

import org.jetbrains.annotations.NotNull;

public record ChannelTest(@NotNull String test, String test2) {
}
```
or
```java
package com.example;

import org.jetbrains.annotations.NotNull;

public record ChannelTest(@NotNull String test, @NotNull String test2) {
}
```

the retransform will fail with:
![grafik](https://user-images.githubusercontent.com/60936899/146040433-26287317-9a50-46fa-a106-acc80f5cdc01.png)

I was unsure if this is an asm or ByteBuddy issue. Hope someone can give me more information about that.
Thanks in advance!

**Comment by raphw** [comment]
What Java compiler (ejc or javac) are you using? I tried it with:

        RecordComponent[] c = AnnotatedRecordSample.class.getRecordComponents();
        System.out.println(Arrays.toString(c[0].getAnnotations()));
        System.out.println(Arrays.toString(c[1].getAnnotations()));

        ClassReader cr = new ClassReader(AnnotatedRecordSample.class.getName());
        cr.accept(new ClassVisitor(Opcodes.ASM9) {
        }, 0);

And I do not get any errors. Try updating Byte Buddy to the latest version and use a recent build of Java 17.

**Comment by derklaro** [comment]
Can confirm that updating mockito from 4.1 to 4.1.1-SNAPSHOT resolves the issue.

**Comment by derklaro** [comment]
> What Java compiler (ejc or javac) are you using? I tried it with:
> 
> ```
>     RecordComponent[] c = AnnotatedRecordSample.class.getRecordComponents();
>     System.out.println(Arrays.toString(c[0].getAnnotations()));
>     System.out.println(Arrays.toString(c[1].getAnnotations()));
> 
>     ClassReader cr = new ClassReader(AnnotatedRecordSample.class.getName());
>     cr.accept(new ClassVisitor(Opcodes.ASM9) {
>     }, 0);
> ```
> 
> And I do not get any errors. Try updating Byte Buddy to the latest version and use a recent build of Java 17.

I tried it with 
```
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

and i can confirm that there is no issue when running the code you provided. However, I run into the same problem problem when i try to call 
```java
byteBuddy.redefine(TestRecord.class, ClassFileLocator.Simple.of(TestRecord.class.getName(), classfileBuffer)).make();
```

(This is the code Mockito uses in the `InlineBytecodeGenerator`.) I'm using Mockito 4.1.1-SNAPSHOT which uses the latest Bytebuddy Version.

**Comment by raphw** [comment]
The following code works for me with Mockito 4.1.1-SNAPSHOT:

        AnnotatedRecordSample mock = mock(AnnotatedRecordSample.class);
        System.out.println(mock);

I am using a recent Java 17 for this.

**Comment by derklaro** [comment]
After trying some stuff out it turn out that using
```java
@Target({ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER, ElementType.LOCAL_VARIABLE, ElementType.TYPE_USE})
```
will not work. If I remove `ElementType.TYPE_USE`, it passes 🤔

Record:
```java
public record TestRecord(@TestAnno String helloWorld, @TestAnno String anotherString) {

}
```
Annotation:
```java
@Documented
@Retention(RetentionPolicy.CLASS)
@Target({ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER, ElementType.LOCAL_VARIABLE})
public @interface TestAnno {

}
```

**Comment by raphw** [comment]
With or without the *TYPE_USE* element type, this does not trigger an exception for me. I think this likely is related to your toolchain.

**Comment by derklaro** [comment]
I'm testing using gradle 7.3.1, junit 5.8.2 and mockito 4.1.1 on Java 17.0.1+12-LTS-39

**Comment by raphw** [comment]
Just tried with vanilla Java (17.0.1+12) and cannot reproduce this.

**Comment by derklaro** [comment]
Thats really strange, the only thing i did was switching to mockito-inline and converting my class to a record. I changed nothing else on the test or gradle setup... 🤔

**Comment by raphw** [comment]
Could you create a minimal reproducer as a zip file, ideally with a simple shell to run it, and a pointer to a given distribution of the JDK that reproduces this issue?

**Comment by derklaro** [comment]
The project is available on GitHub. [Here](https://github.com/CloudNetService/CloudNet-v3/blob/java-migration-refactor/driver/src/test/java/de/dytanic/cloudnet/driver/event/DefaultEventManagerTest.java#L76) is the test which is failing, and here [the build output](https://github.com/CloudNetService/CloudNet-v3/runs/4536825241?check_suite_focus=true) from actions (running on Java 17.0.1+12 (Temurin-Hotspot))

**Comment by raphw** [comment]
Hmm, this seems to be Kotlin, though.

Could you boil this down to a simple reproduction with only the minimal code to reproduce the error as you describe it in this ticket?

**Comment by derklaro** [comment]
I've created [a repository](https://github.com/derklaro/byte-buddy-1175) with just one simple test to show it off. It fails there for me as well.

**Comment by raphw** [comment]
Thanks, I only had to change to mockito-inline from core. This seems to be an ASM issue to me: https://gitlab.ow2.org/asm/asm/-/issues/317959

Maybe the JVM does not resolve the class file correctly, too. We will hopefully find out.
