### ISSUE TITLE
byte-buddy 1.12.4 causes compilation warnings without JSR305 on classpath

### ISSUE THREAD

**Issue by facboy** [raphw/byte-buddy#1176]
Compiling against byte-buddy 1.12.4 causes a lot of `unknown enum constant` warnings if some version of `jsr305` is not on the classpath:

```
[WARNING] /home/xyz/git/bytebuddy-jsr305/src/main/java/org/facboy/bytebuddy/DoNothing.java: unknown enum constant javax.annotation.meta.When.MAYBE
```
test project:

https://github.com/facboy/bytebuddy-jsr305

can i ask why you've decided to incorporate jsr305 when a lot of projects seem to be phasing it out because of the problems it causes with java modules?

**Comment by raphw** [comment]
I needed something Java 5 compatible and it's supported by spotbugs which has the same issue.

Spring also seems to use it. What's the alternative?

**Comment by raphw** [comment]
Alright, I found out that Spring uses their own alias annotations for this purpose, and I now did the same in Byte Buddy. Since you never get in touch with these annotation annotations, the warnings are never issued.

I will make a new release such that people can avoid this problem.

**Comment by raphw** [comment]
Fixed in release 1.12.5.

**Comment by facboy** [comment]
not sure if it's intended, but if project code uses eg the `@MaybeNull` annotations then the warnings come back (presumably because those annotations themselves refer to `jsr305`).

**Comment by raphw** [comment]
They are not intended for that. See javadoc.
