### ISSUE TITLE
ByteBuddy-Thread.currentThread().getId() occur circulation

### ISSUE THREAD

**Issue by kc910521** [raphw/byte-buddy#1178]
java 1.8.0_292
byte buddy  1.12.6

configurations:
```java
ElementMatchers.nameStartsWith(....)
builder.method(methodDescriptionJunction).intercept(Advice.to(InvokeChain.class));
AgentBuilder.Default().type(namedElementJunction).transform(transformer).with(listener).installOn(inst)

// ....

    @Advice.OnMethodEnter
    public static void before(@Advice.Origin Method method){
         Thread th = Thread.currentThread();
         // circulate happened here
         th.getId();

```
===
but when i try to invoke ：
th.getName();
everything be OK.

**Comment by raphw** [comment]
What do you mean by "circulate"? A recursive call? If your advice instruments Theead.getId this would indeed be a problem. Byte Buddy only copies your code to a target. It is your responsibility to avoid circularities just as with regular Java code.

**Comment by kc910521** [comment]
yes, A recursive call.
i already sloved this problem by adding every package path that used in agent's method (eg 'java.lang') to ignore case.
