### ISSUE TITLE
Extracting parameter names

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#118]
I'm trying to extract parameter names with `NamedElement.WithRuntimeName#getName` with inside a `Advice.DynamicValue`. Even though I've compiled my classes with `-g:source,lines,vars` I only get names like `arg0`. Am I doing something wrong or is there a limitation in Byte Buddy?

See also https://github.com/stagemonitor/stagemonitor/commit/057c4674379f18d36a273b17202c4d85df120600

**Comment by raphw** [comment]
You have two possibilities:

1. Either you compile your code with `-parameter` such [that the parameter names are attached as meta data](https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html). 
2. Or you [use the `TypePool.Default.ReaderMode.EXTENDED`](http://bytebuddy.net/javadoc/1.3.17/net/bytebuddy/pool/TypePool.Default.ReaderMode.html) where Byte Buddy also parses the debugging information of any (non-abstract, non-native) Java method for parameter names. This information is then available for non-loaded types.

**Comment by felixbarny** [comment]
Thank you! Works like a charm.
