### ISSUE TITLE
agentmain  how  I  retransformClasses  all  i  want  loaded Class

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1180]
When  I   write  agentmain  to hook   matched  classes:

```
new AgentBuilder.Default().ignore(
                        nameStartsWith("net.bytebuddy.")
                // 声明使用redefine
                .with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
            .with(AgentBuilder.TypeStrategy.Default.REDEFINE);.type(nameStartsWith("com.xxx"))).transform(new AgentBuilder.Transformer() {
            @Override
            public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
//to  do  matched class.
return builder;
}
   )).installOn(instrumentation);

//retransform
retransform(instrumentation);
```

because  agentmain   attach ,many  class   has loaded ,  so   I    use   

```

public static void retransform(Instrumentation inst) {
        Class[] loadedClasses = inst.getAllLoadedClasses();
        for (Class clazz : loadedClasses) {
            //logger.info("loaded class: "+clazz.getName());
            if (inst.isModifiableClass(clazz) && clazz.getName().startsWith("com.xxx")) {
                logger.info("all matched class: " + clazz.getName());
                try {
                    inst.retransformClasses(clazz);
                } catch (UnmodifiableClassException e) {
                    e.printStackTrace();
                }
            }
        }

    }
```

but  this  not  work  as  I  predicate ,how  i   solve it?

**Comment by raphw** [comment]
When using a redefinition strategy, Byte Buddy takes care of transforming previously loaded classes. You can follow up on this by registering a listener. Normally, you want to invoke disableClassFormatChanges in the DSL as most VMs do not support that.

**Comment by cor0ps** [comment]
new AgentBuilder.Default().ignore(
                        nameStartsWith("net.bytebuddy.")
                                .or(nameStartsWith("org.slf4j."))
                                .or(nameStartsWith("sun.reflect.")))
                // 声明使用redefine
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE);   mybe  I  use  RETRANSFORMATION  is  good   and  I  also  matched  I  want  class   on registering  a listener ????

**Comment by raphw** [comment]
Retransformation is typically what you want, but only supported on JVMs version 6+. Do not specify both as one overrides the other.

**Comment by cor0ps** [comment]
@Override
    public void onTransformation(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module, boolean loaded, DynamicType dynamicType) {


        logger.info("onTransformation: "+typeDescription.getCanonicalName() +" ");
    }

i  foud   many   typeDescription.getCanonicalName()  has  null   but    I  dump this  null  name  but  class  is  not empty！！！

javap -c   null.class

com.xxxxxx.RegisterSvcTask$1

com.xxxxxx.xxxx$1

maybe  is  inner class  but  I  think  this  is  a  bug

![image](https://user-images.githubusercontent.com/13083624/147334001-fdd1ce09-4b9f-4184-a25a-2e63df1fb980.png)


how to  solve  it?

**Comment by raphw** [comment]
Canonical names are null for certain types of classes such as anonymous classes, please refer to the javadoc. There are other name types that sre never null.

**Comment by cor0ps** [comment]
yes  this  problem  i  know，but  when   I   use  premain  can hook  all  I  want class,like match  return "com.xxx" classes,but  I    use  agentmain   I  found   we lose  many   classes。
```
 new AgentBuilder.Default().ignore(
                        nameStartsWith("net.bytebuddy.")
                                .or(nameStartsWith("org.slf4j."))
                                .or(nameStartsWith("sun.reflect.")))
                // 声明使用redefine
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE).with(new FlowListener());.type(nameStartsWith("com.xxx").or(nameStartsWith("org.joychou").or(nameStartsWith("com.range")))).transform(new AgentBuilder.Transformer() {
            @Override
            public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {

                return builder;
            }
        }).installOn(instrumentation);

listener:
public class FlowListener implements AgentBuilder.Listener {
    static org.apache.log4j.Logger logger = Logger.getLogger(FlowListener.class);
    String clazzName;

    @Override
    public void onDiscovery(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded) {
        String clazzMd5 = Utils.generateHash(clazzName);
        if ((typeName.startsWith("com.huawei") || typeName.startsWith("org.joychou")) && transformationClassess.containsKey(clazzMd5))
            logger.info("onDiscovery: " + typeName + " " + loaded);
    }

    @Override
    public void onTransformation(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module, boolean loaded, DynamicType dynamicType) {
        clazzName = typeDescription.getCanonicalName();

        if (clazzName != null) {

            String clazzMd5 = Utils.generateHash(clazzName);
            logger.info("onTransformation: " + clazzName + " " + loaded + " hash: " + transformationClassess.containsKey(clazzMd5));

            if (!transformationClassess.containsKey(clazzMd5)) {
                 byte[] bytes = dynamicType.getBytes();
                if (bytes.length > 0) {
                    try {
                        Utils.OutPutClazz(bytes, typeDescription.getCanonicalName());
                       
     
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                transformationClassess.put(clazzMd5, clazzName);
            }
        }
    }
}



maybe   use  agentmain   attach ,some class  loaded   and  I   use  instrumention.retransformClasses(clazz) but  this  problem  not  works

**Comment by raphw** [comment]
Try removing `.with(AgentBuilder.TypeStrategy.Default.REDEFINE)`. I am however not sure what your exact problem is: as said, it is very much expected that many classes do not have canonical names.

**Comment by cor0ps** [comment]
The way I want to run through all the data is simple,I  want to save  jvm  runtime  loaded  class bytes  .and Does this approach make any practical sense?

**Comment by cor0ps** [comment]
> Try removing `.with(AgentBuilder.TypeStrategy.Default.REDEFINE)`. I am however not sure what your exact problem is: as said, it is very much expected that many classes do not have canonical names.

The way I want to run through all the data is simple,I want to save jvm runtime loaded class bytes .and Does this approach make any practical sense?

**Comment by raphw** [comment]
You wanted to extract the class file bytes without applying the transformation? You can do this the easiest by registering a [decorator](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/agent/builder/AgentBuilder.java#L268) for the registered class file transformer. You can then receive the intercepted bytes and return `null` to abort the transformation from the decorator.

**Comment by cor0ps** [comment]
decorator  function  is  great  a  way  to  extract  the  class file  bytes, but  also  I   want  use   AsmVisitorWrapper  to  parse this  class file bytes  use asm  api,for example when  I 
 want  matches class matches like start with "com.sun",these way only extract little class download.  Maybe  I    think  RedefinitionStrategy is  wrong? or   these way  is wrong?

```
 AgentBuilder agentBuilder = new AgentBuilder.Default()
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(new FlowListener())
             
                .with(new AgentBuilder.TransformerDecorator() {
                    @Override
                    public ResettableClassFileTransformer decorate(ResettableClassFileTransformer classFileTransformer) {
                        System.out.println("zzzz " + classFileTransformer);
                        return classFileTransformer;
                    }
                })
                .disableClassFormatChanges()
                .ignore(ElementMatchers.<TypeDescription>none().and(ElementMatchers.nameStartsWith("com.taint")))
                .type(ElementMatchers.nameMatches(Configuration.getStartWithRegex())).transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        AsmVisitorWrapper asmWrapper = new ASMWrapper(discoveredClasses,discoveredMethods,typeDescription);
                        if(!typeDescription.getCanonicalName().contains("$$")) {

                            builder = builder.visit(asmWrapper);
                        }
                        return builder;
                    }
                });

        agentBuilder.installOn(instrumentation);
```

**Comment by raphw** [comment]
If you wanted the class files during a transformation, you can also register an `AgentBuilder.Listener` where the bytes are present via the `DynamicType` value of the `onTransform` method. You'd still need to make sure to wrap the transformer and return `null` for any retransformation, if you do not want them to take effect.

**Comment by cor0ps** [comment]
oks
