### ISSUE TITLE
Question: How to write an interceptor that can access all fields?

### ISSUE THREAD

**Issue by hjohn** [raphw/byte-buddy#1183]
Edit: Just realized I should have asked this on StackOverflow or the mailing list.  I can move it there.

My problem: I am generating a class with Byte Buddy for which I'm defining multiple fields.  The amount of fields depends on another class, so is not known in advance and can vary with each class I generate.  The class I'm generating will serve as a Factory for a second class (the Product) which has need of an unspecified number of parameters which I'm storing in fields of the generated factory.  It looks a bit like this:

     for(int i = 0; i < numberOfFields; i++) {
          builder = builder.defineField("__binding" + i + "__", TypeFactory.parameterizedClass(Provider.class, binding.getType()), Visibility.PRIVATE);
     }

The class is then later passed to an injection framework (of my own making).  This framework will inject all these private fields and I've confirmed this works.  So far so good.

My problem is that I also define an interceptor:

        .method(ElementMatchers.returns(productType).and(ElementMatchers.isAbstract()))
        .intercept(MethodDelegation.to(new Interceptor(productType, productFactory, productBindings, parameterNames)));

This interceptor needs to access all the fields that were defined, gather them into a `List` and pass them on to the injection framework again to create the Product of my generated Factory.  In order to do that I would like to pass to this interceptor (in its constructor) all the fields that I defined earlier (as `java.lang.reflect.Field`) -- but the Byte Buddy class hasn't been created yet at the time when I need to specify the interceptor.

I know how I can have the interceptor be supplied with the value of a single field, like this:

    @RuntimeType
    public Object intercept(@FieldValue(INSTANTIATOR_FIELD_NAME) Instantiator instantiator, @AllArguments Object[] args);

...but what about intercepting an unknown amount of fields?

I've been looking into `@This` which gives me an instance that I could examine with Reflection -- but I would have to do this each time the interceptor is called as I can't pass the `Field` instances in the constructor of my interceptor.

I suppose I could make my interceptor a mutable class and just pass it all the fields it needs after construction of the Byte Buddy class. However, I'm not that familiar with Byte Buddy, so I was wondering if I'm missing an obvious alternative solution -- perhaps something like intercepting the values set to the fields (by the injection framework) and gathering them somehow? :)  Or perhaps also generating the Interceptor with Byte Buddy? :)

**Comment by raphw** [comment]
The easiest and most performant way would be to write your own binding. You can do so via `MethodDelegation.withCustomBinding().bind(MyAnnotation.class, ...)`.

You can have a look at the bindings that ship with Byte Buddy in the `AllArguments` and the `FieldValue` bindings and tweak these implementations after your custom demands. As a result, you would get an array with all fields, if that is what you needed.

**Comment by hjohn** [comment]
Thanks, the odd thing is, I don't have the `withCustomBinding` method (in `net.bytebuddy.implementation.MethodDelegation`) even though I'm on the latest version (`net.bytebuddy:byte-buddy:1.12.6`). I'm using Byte Buddy to implement an interface or abstract class, not changing existing classes via an agent.

**Comment by raphw** [comment]
Sorry, wrong API name: https://github.com/raphw/byte-buddy/blob/aaf0017b1a867396d4a1ef62815f5bb2894fba0c/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/MethodDelegation.java#L600

**Comment by ThielemannSe** [comment]
I'm currently trying to implement the binding mentioned above. @hjohn have you been able to implement this functionality until now?
