### ISSUE TITLE
How to get the field value of the application service class in other classloader (com.xxx.RelaunchClassLoader) from bytebuddy agent (sun.misc.Launcher$AppClassLoader)

### ISSUE THREAD

**Issue by his1devil** [raphw/byte-buddy#1186]
In the process of using bytebuddy agent, the startup way is -javaagent, when the interception logic class try to get other classloader's field, find out classloader is different, tried to custom classloader to load interceptor logic, still got nothing, details:

>
``` java
// agentbuilder
DynamicType.Builder<?> newClassBuilder = new AgentBuilder
    .visit(Advice
        .withCustomMapping()
        .bind(AdviceInterceptorName.class, new TextConstant(interceptorName), String.class)
        .bind(AdviceInterceptorIndex.class, IntegerConstant.forValue(interceptorIndex), int.class)
        .to(dispatcher)
        .on(elementMatcher));
```

```java
// Advice
public class InstanceMethodAdvice {

    @Advice.OnMethodEnter
    public static <T> T beforeMethod(@AdviceInterceptorName String interceptorName, @AdviceInterceptorIndex int interceptorIndex, @Advice.This Object target, @Advice.Origin Method method, @Advice.AllArguments Object[] args, @Advice.Local("localValue") Object localValue) {
        T t = null;
        try {
            InstanceMethodInterceptor<T> interceptor = InterceptorLoader.getInterceptor(interceptorIndex);
            t = interceptor.beforeMethod(target, method, args);
        } catch (Throwable throwable) {
        }
        return t;
    }

    @Advice.OnMethodExit(onThrowable = Exception.class)
    public static <T> void afterMethod(@AdviceInterceptorName String interceptorName, @AdviceInterceptorIndex int interceptorIndex, @Advice.Enter T t, @Advice.Local("localValue") Object localValue, @Advice.Return(typing = Assigner.Typing.DYNAMIC) Object originResult, @Advice.Thrown Throwable throwable) {
}

```

```java
// Interceptor logic
public class ApiInfoInterceptor implements InstanceMethodInterceptor<String> {

    @Override
    public String beforeMethod(Object target, Method method, Object[] args) {
        try {
            // try get EagleEye(like skywalking tracing system) EagleEye.getTraceId == null, but in services interceptor can get this traceId
           // EagleEye.class.getClassLoader()  == sun.misc.Launcher$AppClassLoader, should be "eagleeye-core's ModuleClassLoader", may be this way getTraceId == null
            System.out.println("SDK: ThreadId=" + Thread.currentThread().getId() + " | " + EagleEye.class.getClassLoader() + " | traceId: " + EagleEye.getTraceId());

        } catch (Exception e) {
            e.printStackTrace();
        }
        String traceId = EagleEye.getTraceId();
        logger.info("HsfInfoInterceptor: method: {}, args: {}, traceId: {}", method.getName(), args, traceId);
        return StringUtils.EMPTY;
    }

    @Override
    public void afterMethod(String packet, Object originResult) {
    }
}
```

in comments above, how can i get EagleEye.getTraceId(load by ModuleClassLoader) ?
try to load this interceptor in ModuleClassLoader, but still be "sun.misc.Launcher$AppClassLoader"

any suggestions ?

thanks @raphw 
BR.

**Comment by raphw** [comment]
I am not sure if I understand your question. Do you want to only instrument classes of a given class loader, or exclude a class loader? In this case, I suggest that you add an ignore matcher that excludes a class loader. Otherwise, `@Advice.Origin` can be used on a `Class<?>` parameter on which you can call `.getClassLoader()`.

**Comment by his1devil** [comment]
> I am not sure if I understand your question. Do you want to only instrument classes of a given class loader, or exclude a class loader? In this case, I suggest that you add an ignore matcher that excludes a class loader. Otherwise, `@Advice.Origin` can be used on a `Class<?>` parameter on which you can call `.getClassLoader()`.

Sorry about my poor English ;(

The question is agent try to instrument classes of a given app classloader(ModuleClassLoader of instrumented class), and need access instrumented class's field in intercepor logic class which is loaded by agent classloader(system classloader),
so when interceptor logic class try to access other classloader's class field, return null.

```
AgentInterceptor instrument RelaunchClassLoader.ClassA,
and invoke ModuleClassLoader.ClassB.getTraceId() innner RelaunchClassLoader.ClassA
```
(ClassA can get ClassB.getTraceId, the RelaunchClassLoader and ModuleClassLoader is loaded by framework)

**Comment by his1devil** [comment]
when i use classloader matcher, can get instrumented ClassA classloader = RelaunchClassLoader, but when i call ClassB.getTracedId(loaded by ModuleClassLoader) in InterceptorClass, got null

**Comment by raphw** [comment]
No worries, let's figure this out.

If I understand you correctly, you want to have some way of accessing a class from all class loaders? This can be done by injecting a dedicated dispatcher into the bootstrap class loader. This can be done via the `Instrumentation` API. Simply choose a dedicated package. All classes in this package will be available to any class in your application, agent and others.

**Comment by raphw** [comment]
You want to access the agents class loader and the instrumented class's class loader? In this case, you would need to create a new class loader and make both loaders a parent of this loader. This is more complicated to accomplish but I blogged about it with Felix from Elastic who run the same approach for their agent: https://www.elastic.co/blog/embracing-invokedynamic-to-tame-class-loaders-in-java-agents

Elastic APM is open source, so check it out if you wanted to go into this direction.

**Comment by his1devil** [comment]
> You want to access the agents class loader and the instrumented class's class loader? In this case, you would need to create a new class loader and make both loaders a parent of this loader. This is more complicated to accomplish but I blogged about it with Felix from Elastic who run the same approach for their agent: https://www.elastic.co/blog/embracing-invokedynamic-to-tame-class-loaders-in-java-agents
> 
> Elastic APM is open source, so check it out if you wanted to go into this direction.

i read this blog, it seems it's not a same issue, i drawed a pic, it's not about let serviceCode to access agents, it's agent's interceptor can access user's code by different classloader, but with multiple different classloaders.

![image](https://user-images.githubusercontent.com/1657654/148731118-401e6166-945d-4e02-9b05-6ccc290d61ed.png)

**Comment by raphw** [comment]
I think I understand now. This is strange behavior, I assume the `ARMClass.getTraceId` method is call sensitive in some form and understand from where it is called. Did you look into the code of the method, to see if you can call it differently, to get the behavior you expected?

Alternatively, have a look at `Advice` which allows you to inline code into a target method. This way, the `getTraceId` method cannot tell from where it is invoked.

**Comment by his1devil** [comment]
> I think I understand now. This is strange behavior, I assume the `ARMClass.getTraceId` method is call sensitive in some form and understand from where it is called. Did you look into the code of the method, to see if you can call it differently, to get the behavior you expected?
> 
> Alternatively, have a look at `Advice` which allows you to inline code into a target method. This way, the `getTraceId` method cannot tell from where it is invoked.

In `beforeMethod` of  interceptorClass, i try to get all classLoaders by `instrumentation.getAllLoadedClasses()`.
Through iterated classloaders array, and use `classloader.loadClass("ARMClass")`,then invoke `getTraceId` by reflection, it is solved.
Thank you Raphw, learned a lot ;)

**Comment by his1devil** [comment]
> I think I understand now. This is strange behavior, I assume the `ARMClass.getTraceId` method is call sensitive in some form and understand from where it is called. Did you look into the code of the method, to see if you can call it differently, to get the behavior you expected?
> 
> Alternatively, have a look at `Advice` which allows you to inline code into a target method. This way, the `getTraceId` method cannot tell from where it is invoked.

In `beforeMethod` of  interceptorClass, i try to get all classLoaders by `instrumentation.getAllLoadedClasses()`.
Through iterated classloaders array, and use `classloader.loadClass("ARMClass")`,then invoke `getTraceId` by reflection, it is solved.
Thank you Raphw, learned a lot ;)
