### ISSUE TITLE
java.lang.VerifyError when use FieldValue advice classs

### ISSUE THREAD

**Issue by 98DE9E1F** [raphw/byte-buddy#1187]
byte-buddy version 1.10.22

Caused by: java.lang.VerifyError: Illegal type at constant pool entry 152 in class redis.clients.util.Pool

![image](https://user-images.githubusercontent.com/16440825/148635643-964c157c-52c1-4b7a-b11e-0912ae6b0060.png)

code

![image](https://user-images.githubusercontent.com/16440825/148635662-7f037242-9186-4bda-9a1f-a921e60adadf.png)

![image](https://user-images.githubusercontent.com/16440825/148635814-e3b7b444-b521-49e1-aa1a-8e7dcbca6c51.png)

**Comment by raphw** [comment]
Please try with the latest version first, this might have been fixed in the mean time.

**Comment by 98DE9E1F** [comment]
> Please try with the latest version first, this might have been fixed in the mean time.

i try with 1.11.22 、1.12.6 ,but also got the same error, has any other suggestion?

**Comment by raphw** [comment]
Ah, I see. Register a [`TypeConstantAdjustment`](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/asm/TypeConstantAdjustment.java) as a first visitor.

By the way: if you wanted to decorate the existing method, you need to use `Advice` within a `visit` method.

**Comment by 98DE9E1F** [comment]
I found out that the problem was caused by the wrong usage

 before Java 8, The method descriptor of an invokestatic must refer a CONSTANT_Methodref_info entry

 but the enhanced  byte code like this 
```
Compiled from "Pool.java"
   public abstract class redis.clients.jedis.util.Pool<T extends java.lang.Object> extends java.lang. Object implements java.io.Closeable
   ...
   major version: 51
   ...
Constant pool:
   ...
   #161 = InterfaceMethodref #157.#160     // com/tuya/boot/actuator/bean/BeanExporter.             getPlatformExporter:()Lcom/tuya/boot/actuator/bean/BeanExporter;

   public void initPool(org.apache.commons.pool2.impl.GenericObjectPoolConfig, org.apache.commons.  pool2.PooledObjectFactory<T>);
     Code:
         19: invokestatic  #161                // InterfaceMethod com/tuya/boot/actuator/bean/      BeanExporter.getPlatformExporter:()Lcom/tuya/boot/actuator/bean/BeanExporter;
```


 Ref https://stackoverflow.com/questions/34360718/invokestatic-on-static-method-in-interface
