### ISSUE TITLE
Unable to cast method parameters of hooked method

### ISSUE THREAD

**Issue by sides-flow** [raphw/byte-buddy#1192]
I have opened an [issue](https://github.com/netty/netty/issues/12023) about this on `netty` because it seemed more like a problem with their code classes, but they suggested I open an issue here instead...

I'm using `bytebuddy` to "hook" the following method:
https://github.com/netty/netty/blob/d34212439068091bcec29a8fad4df82f0a82c638/transport/src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java#L347

Inside the hook, I get a reference to the method's parameters as `Object`.
Therefore, I'm trying to cast the first and only parameter to `ByteBuf`, but `arguments[0] instanceof ByteBuf` returns `false` and `(ByteBuf)arguments[0]` outputs: `java.lang.ClassCastException: io.netty.buffer.PooledUnsafeDirectByteBuf cannot be cast to io.netty.buffer.ByteBuf`
After checking the code a few times, I made sure `PooledUnsafeDirectByteBuf` extends `ByteBuf` (after a long inheritance chain).
Here is the relevant code:
```
System.out.println("Parameter: " + arguments[0]);
System.out.println("instance? " + (arguments[0] instanceof io.netty.buffer.ByteBuf));
b = (io.netty.buffer.ByteBuf) arguments[0];
```

### Expected behavior
`arguments[0] instanceof ByteBuf` should return `True` since `arguments[0]` is of type `PooledUnsafeDirectByteBuf` (or other type that extends from `ByteBuf`)

### Actual behavior
```
Parameter: PooledUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 2048)
instance? false
java.lang.ClassCastException: io.netty.buffer.PooledUnsafeDirectByteBuf cannot be cast to io.netty.buffer.ByteBuf
```

### Steps to reproduce
The steps to reproduce are a bit complicated, If it is really necessary I will upload the smallest code I manage to make that includes a `bytebuddy` builder that hooks the `doReadBytes` method.

### Netty version
I'm using this line in my build.gradle:
`    implementation "io.netty:netty-all:4.1.73.Final"`

### JVM version (e.g. `java -version`)
```[ec2-user@ip-********** netty]$ gradle -version

------------------------------------------------------------
Gradle 7.3.2
------------------------------------------------------------

Build time:   2021-12-15 11:22:31 UTC
Revision:     26c186eb63b2b02e68d83b0dbc6ec69ab118653a

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_312 (Red Hat, Inc. 25.312-b07)
OS:           Linux 5.10.75-79.358.amzn2.x86_64 amd64
```

### OS version (e.g. `uname -a`)
I'm using the new AWS linux image:
`[ec2-user@ip-******** netty]$ uname -a
Linux ip-*********.us-east-2.compute.internal 5.10.75-79.358.amzn2.x86_64 #1 SMP Thu Nov 4 21:08:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

# Thanks for your help!

**Comment by sides-flow** [comment]
[# Original issue on netty](https://github.com/netty/netty/issues/12023)

**Comment by raphw** [comment]
I answered in the original ticket.

**Comment by sides-flow** [comment]
I have [posted](https://github.com/netty/netty/issues/12023#issuecomment-1017516001) in the original ticket a summary of how I managed to work around the problem, only to realize I didn't need to transform this method at all.
Thanks so much for the help, Rafael!
