### ISSUE TITLE
Intercept(to(<unloadedType's TypeDescription>)) - Is this supposed to work?

### ISSUE THREAD

**Issue by Olipro** [raphw/byte-buddy#1193]
So I've got a bit of a chicken-and-egg style problem;

I'm loading a 3rd party class file that I've modified so that its method(s) parameter(s) are annotated with `@This`, `@SuperMethod`, `@Argument`, `@DynamicMethod` etcetera as it's going to be intercepting from another class's methods.

However, the intercepting class knows about the type of the interceptee which means if I just call `.load()` after preparing the interceptor class, rebasing the interceptee will fail (unsurprisingly since loading the interceptor caused it to be loaded)

I *hoped* that using the overload of `TypeDescription.to(TypeDescription)` would solve the problem since I can provide a TypeDescription without loading it - however, if I do that, Bytebuddy then considers the method ineligible.

I tested this out with my own class where I had it accept `Object` for `@This` and simply loaded it, passing the `Class` instance instead of a `TypeDescription`, since it doesn't reference the interceptee's type as a param any more, the interceptee doesn't get loaded - however, as soon as I attempt to `intercept()` without it being loaded first, it fails, without changing the interceptor class at all.

**Comment by Olipro** [comment]
Well, looks like I missed a very important footgun:

Retrieving the `TypeDescription` of a `.make()`'d class does **not** reflect the mutations and you have to completely reload it by feeding the byte array into a ClassFileLocator (unless there's a better way)

I'll leave this issue open as a suggestion that perhaps there should be some runtime/type safety around that as it's super easy to miss that important little note.

**Comment by raphw** [comment]
You can always get a `TypeDescription` by `DynamicType.Builder::toTypeDescription`. What's not included are changes by `visit` methods. You can however create your own `InstrumentedType` or `TypeDescription.Latent` and provide such an instance to override Byte Buddy's validation.

**Comment by raphw** [comment]
I mean that you can do something like:

    DynamicType.Builder<?> b = new ByteBuddy().subclass(Object.class);
    TypeDescription td = b.make().getTypeDescription();
    // use partially built td as input to other builders

You can continue to use the builder even after materializing a temporary state and use it as input to other bits of your code.

**Comment by Olipro** [comment]
hm, perhaps I'm just being obtuse but that was my original problem no?

I **can't** use `.make().getTypeDescription()` because the type has been `visit()`'ed in order to add annotations (only annotations, no code changes) and ByteBuddy doesn't know about them (and it needs to, because they're ByteBuddy annotations)

**Comment by raphw** [comment]
How are you adding those annotations? Are you not using the builder API?

Alternatively, you could build a `TypeDescription` by creating an `InstrumentedType.Default`.
