### ISSUE TITLE
How to avoid System.currentTimeMillis()being optimized by JIT?

### ISSUE THREAD

**Issue by lucas-myx** [raphw/byte-buddy#1195]
We're using bytebuddy mock `java.lang.System#currentTimeMillis`, 

The purpose is to make it return the time stamp we specified, so as to meet some business scenarios

During the pressure test, the first hundreds of calls currentTimeMillis return the timestamp after mock (i.e. a certain time in the past), but the subsequent calls return the current time (the real time). I know this is not a bytebuudy problem. It should be that the JVM has made some optimization, because if I add `-Djava.compiler=NONE` or `-Xint` parameter When starting the JVM, after turning off JIT, we can always return the timestamp of mock.

I would like to ask whether we can avoid JIT optimization through code?

I've also tried to add random numbers to the `currentTimeMillis` method or print them out, but it didn't help......

So besides setting JVM parameters, is there any other way to prevent currenttimemillis from being optimized by JIT?

Any suggestion will be appreciated. Thanks!

**Comment by raphw** [comment]
No, you can only disable this via command line parameters.

Alternatively, you can use `MemberSubstitution` to replace calls to `System.currentTimeMillis` and replace those calls with a fixed value.

**Comment by lucas-myx** [comment]
Thank you very much for your reply.
I think `MemberSubstitution` is a good suggestion. I'll try it
