### ISSUE TITLE
Get the runtime class name

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#120]
Inside a `@Advice.OnMethodEnter` method, I want to obtain the runtime class name of the method. For example class `A` declares method `foo` and `B extends A`. When executing `B#foo` I don't want to get `A` as the class name but `B`. The obvious thing would be to inject the this `@Advice.This` reference and call `thiz.getClass()` but that only works for non-static methods.

One solution would be to ehnance `@Advice.This` with `@Advice.This#nullIfNotAvailable` and use `@Origin Class<?> clazz` or `@Origin("#t") String className` if `thiz == null`.

Of course it would be possible to create another advice which is applied solely to static methods and to not use `@Advice.This` in it but this would lead to a bit of code duplication and most importantly, the method and type matchers would have to be executed twice which leads to more overhead.

See [org.stagemonitor.requestmonitor.AbstractMonitorRequestsTransformer#monitorStart](https://github.com/stagemonitor/stagemonitor/blob/057c4674379f18d36a273b17202c4d85df120600/stagemonitor-requestmonitor/src/main/java/org/stagemonitor/requestmonitor/AbstractMonitorRequestsTransformer.java#L27) for context.

**Comment by raphw** [comment]
Fixed on *master* by the `optional` attribute.
