### ISSUE TITLE
[Question] Is it possible to change AgentBuilder.Default().type(typeMatches) dynamic in Runtime ?

### ISSUE THREAD

**Issue by his1devil** [raphw/byte-buddy#1202]
Hi ~ @raphw 
I have a few questions about changing typeMatches in Runtime, when i started agentbuilder with -javaagent

```
// demo code
AgentBuilder agentBuilder = new AgentBuilder.Default().disableClassFormatChanges()
.ignore(not(ElementMatchers.nameStartsWith("com.a.b"))).transform(xxx);
ResettableClassFileTransformer classFileTransformer;
classFileTransformer = agentBuilder.installOn(inst);
```

can i eable to change ElementTypeMatchers.nameStartsWith("com.b.d") dynamic ?
like use some configuration to change it in Runtime by reinstallOn classFileTransformer?

**Comment by raphw** [comment]
You can create a new builder and then use the `patchOn` functionality on the next builder. You would need to define a `RedefinitionStratregy` for this purpose.

**Comment by his1devil** [comment]
> You can create a new builder and then use the `patchOn` functionality on the next builder. You would need to define a `RedefinitionStratregy` for this purpose.

Can i just use original builder instead of creating new builder, just use patchOn the older one ? if it can, is there any performance or stability influence issue ?

**Comment by raphw** [comment]
You can transform something:

    AgentBuilder builder = new AgentBuilder.Default().disableClassFormatChanges();
    ResettableClassFileTransformer transformer = builder.type(ElementMatchers.nameStartsWith("com.a.b")).transform(xxx).installOn(inst);
    transformer = builder.type(ElementMatchers.nameStartsWith("com.a.c")).transform(xxx).patchOn(inst, transformer);

The builders are immutable and compared to the instrumentation, creating a new builder is negligible.

**Comment by his1devil** [comment]
> 



> You can transform something:
> 
> ```
> AgentBuilder builder = new AgentBuilder.Default().disableClassFormatChanges();
> ResettableClassFileTransformer transformer = builder.type(ElementMatchers.nameStartsWith("com.a.b")).transform(xxx).installOn(inst);
> transformer = builder.type(ElementMatchers.nameStartsWith("com.a.c")).transform(xxx).patchOn(inst, transformer);
> ```
> 
> The builders are immutable and compared to the instrumentation, creating a new builder is negligible.

I see, last question ;) 
after call
```
transformer = builder.type(ElementMatchers.nameStartsWith("com.a.c")).transform(xxx).patchOn(inst, transformer);
```

the pre 
```
ResettableClassFileTransformer transformer = builder.type(ElementMatchers.nameStartsWith("com.a.b")).transform(xxx).installOn(inst); 
```
is still work ? can i remove the old ElementMatchers's packages ?
