### ISSUE TITLE
Repackaged ASM tree api is missing

### ISSUE THREAD

**Issue by vipcxj** [raphw/byte-buddy#1205]
I want to impl the AsmVisitorWrapper myself. The interface require the repackaged asm node, so it seems that I can use my own asm dependency. However, repackaged asm tree api is missing, As a result, I can use the asm tree api.

**Comment by raphw** [comment]
You can use `byte-buddy-dep` where ASM is not shaded such that you can include your own dependencies. Make however sure to then shade Byte Buddy or load it on an isolated class loader.
