### ISSUE TITLE
Get additional methods when methods enhanced by ByteBuddy

### ISSUE THREAD

**Issue by SeanInShanghai** [raphw/byte-buddy#1207]
In my code, I have two classess JsonStringProcessData and StringProcessData.  JsonStringProcessData is a sub class of StringProcessData. 

`public class StringProcessData {
    
    public void process(String data) {

    }

    public String filterData(String data) {
        return data;
    }
}`

`public class JsonStringProcessData extends StringProcessData {

    public String parseToJSONString(String data) {
        return data;
    }
}`

ByteBuddy enhanced JsonStringProcessData's methods  by MethodDelegation. 
Before enhanced by ByteBuddy, the result of JsonStringProcessData.class.getDeclaredMethods()  is public java.lang.String com.pdd.service.trade.doomdemo.service.impl.JsonStringProcessData.parseToJSONString(java.lang.String) 。
After enhanced by ByteBuddy, the result contains methods from parent class and Bytebuddy.  The following img is the enhanced result of JsonStringProcessData.class.getDeclaredMethods().
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/2471164/154643968-cb47c226-47f3-4501-b0f0-1643507acb55.png">

So, how to get the origin methods without parent methods and deletaged methods .

Thanks .

**Comment by raphw** [comment]
That's an adjustment that BB needs to make. If you want a reference to the original method, you can use `@SuperMethod` on a parameter of your delegation.
