### ISSUE TITLE
How to access an injected static field in Advice?

### ISSUE THREAD

**Issue by FrankChen021** [raphw/byte-buddy#1208]
Hello @raphw , I want to inject a static field, whose name is dynamically generated, to some classes, and how could I access this dynamic injected field in Advice class?

The code piece is as below:

```java
String delegatorName; // holds a dynamic generated static field name 
builder
    .defineField(delegatorName, target, Ownership.STATIC, Visibility.PRIVATE)
    .initializer(new LoadedTypeInitializer() {
        @Override
        public void onLoad(Class<?> type) {
            try {
                Field field = type.getDeclaredField(delegatorName);
                field.setAccessible(true);
                field.set(null, Class.forName(interceptor, false, null).getConstructor().newInstance());
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }

        @Override
        public boolean isAlive() {
            return true;
        }
    })
    .visit(Advice.to(MyAdviceClass.class))


public class MyAdviceClass {
    @Advice.OnMethodEnter
    public static boolean onEnter() {
         // how could I access the injected static field here???
    }
}

```

**Comment by raphw** [comment]
There's `@Advice.FieldValue` that can already bind a field. Have you tried using that?

**Comment by FrankChen021** [comment]
@raphw , Thanks for yoru response. I know the `FieldValue` annotation. but since the field name in my case is dynamic, how can I use it in the Advice class?

**Comment by raphw** [comment]
In this case, you would need to register your own OffsetBinding and resolve a field value dynamically. Have a look at the existing offset bindings for an example.

**Comment by FrankChen021** [comment]
The comment here I think did the right thing. https://github.com/raphw/byte-buddy/issues/1208#issuecomment-1045792392
