### ISSUE TITLE
Performance could be improved by lazily getting parameter annotations

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#121]
Hi Rafael,

as you probably know, in stagemonitor, I have an [InstrumentationPerformanceTest](https://github.com/stagemonitor/stagemonitor/blob/c512d3c5fa7237cdcb66d38c948c408114612eda/stagemonitor-benchmark/src/test/java/org/stagemonitor/InstrumentationPerformanceTest.java) where I just apply all transformers to `org.elasticsearch.*` and then start Elasticsearch to see how much overhead the instrumentation imposes. Without instrumentation Elasticsearch starts in about 2s and with in about 14s.

I've used the jVisualVM sampler to see whats the bottleneck. As you can see in the exported snapshot ([InstrumentationPerformanceTest.nps.zip](https://github.com/raphw/byte-buddy/files/243664/InstrumentationPerformanceTest.nps.zip)), `java.lang.reflect.Method.getParameterAnnotations()` which is called by
`net.bytebuddy.description.method.ParameterDescription$ForLoadedParameter$OfMethod.getDeclaredAnnotations()` accounts for a lot of time, even though I don't access method parameter annotations. When modifying Byte Buddy to just return `new AnnotationList.Empty()` from this method, Elasticsearch starts within about 6s.

<img width="825" alt="getparameterannotations" src="https://cloud.githubusercontent.com/assets/2163464/14936939/18910282-0ef9-11e6-947d-c55bab9ff040.png">

The backgroud for my investigation is that I've recently added stagemonitor to an Eclipse RCP application with a quite large codebase and the startup time increased quite considerably.

**Comment by raphw** [comment]
Byte Buddy already reads any property that is resolved lazily by the JVM's core reflection - such as annotations or generic type information - lazily for this exact reason. The performance of parsing meta information is not ideal. 

But in contrast to what you said: yes you do (implicitly) access the parameter annotations when you are using the `Advice` component which needs to read the parameter annotations for resolving its method-to-method mapping. I think that the problem is that the `Advice.to` call happens from within the `AgentBuilder.Transformer` which is invoked **for each applied transformation**, i.e. all classes that are defined by Elasticsearch. 

Normally, you would not apply the `Advice.to` method that many times. Most agents only instrument a handfull of classes. If you really need to avoid this performance overhead, simply store a reference of the `Advice.to` instances outside of the `AgentBuilder.Transformation` instance that you register.

**Comment by felixbarny** [comment]
> simply store references of the Advice.to instances outside of the AgentBuilder.Transformation that you register to reuse it

Thx, this worked great and cut down the startup time in half.

> Outside of a benchmark, you would not apply the Advice.to method that many times.

Actually, this benchmark isn't that unrealistic. Stagemonitor offers a profiler which has to insert code to every method in the monitored project. Most codebases are not as large as Elasticsearch (especially since they shade a lot to the org.elasticsearch namespace) but fast startup times are really relevant to stagemonitor. Especially if you are monitoring a rich client application, because end users are affected if the startup time increases. So do you think there is any more potential to optimize (the use of) Byte Buddy in case that there are a lot of transformations?

**Comment by raphw** [comment]
Generally, do as little as possible within the transformers and the matchers and access as few properties on description objects as possible but precompute as much as possible. Especially meta data (annotations and generic types) and hierarchy traversals are expensive.

Ironically, Byte Buddy's type pool description are more efficient when accessing properties then going via the Java reflection API but the initial costs of parsing a class file is an initial cost that the type pool cannot avoid.

For performance reasons, always disable type validation in production as it accesses all meta data.

**Comment by felixbarny** [comment]
> The backgroud for my investigation is that I've recently added stagemonitor to an Eclipse RCP application with a quite large codebase and the startup time increased quite considerably.

To give you an update about this: The increased startup was caused by deactivating the type pool cache too early. I'll probably just clear the cache every minute and never deactivate it.

**Comment by raphw** [comment]
Thanks for the feedback. I am still thinking about how to solve this better but I think the best solution really is to install some cache as this is really about storing instances without a predefined life-cycle. I consider offering an integration with some caching solution in a seperate module.

**Comment by felixbarny** [comment]
Sounds like a good idea. But I think for me it is sufficient to just use a `WeakConcurrentMap` that is cleared every minute. I don't feel the necessity to pull in another dependency.

**Comment by CodingFabian** [comment]
We use https://github.com/jhalterman/expiringmap - which could be small enough to include.
