### ISSUE TITLE
Bytebuddy fails to discover classes loaded in different threads when attached at runtime 

### ISSUE THREAD

**Issue by sorabae** [raphw/byte-buddy#1213]
Hello,

I have faced an issue of classes being not discovered and thereby not transformed when an agent is attached at runtime. 

The classes were transformed successfully in the following scenarios:
- When an agent is attached at application startup 
```
...
[Byte Buddy] TRANSFORM com.mysql.cj.jdbc.ClientPreparedStatement [sun.misc.Launcher$AppClassLoader@18b4aac2, null, Thread[http-nio-9966-exec-3,5,main], loaded=false]
[Byte Buddy] TRANSFORM com.mysql.cj.jdbc.StatementImpl [sun.misc.Launcher$AppClassLoader@18b4aac2, null, Thread[http-nio-9966-exec-3,5,main], loaded=false]
```
-  When an agent is attached at runtime after classes have been loaded
```
...
[Byte Buddy] TRANSFORM com.mysql.cj.jdbc.ClientPreparedStatement [sun.misc.Launcher$AppClassLoader@2a139a55, null, Thread[Attach Listener,9,system], loaded=true]
[Byte Buddy] TRANSFORM com.mysql.cj.jdbc.StatementImpl [sun.misc.Launcher$AppClassLoader@2a139a55, null, Thread[Attach Listener,9,system], loaded=true]
```

However, Bytebuddy seems not picking up classes when an agent is attached at runtime before the classes have been loaded. I expected Bytebuddy to transform classes when they are loaded, similarly to when Bytebuddy is attached at application startup time, but it did not work as I expected. 

Could you please help me on this issue?

**Comment by raphw** [comment]
You have to activate this behavior explicitly as there are different constraints:

    .with(RedefinitionStrategy.RETRANSFORM).disableClassFormatChanges()

**Comment by sorabae** [comment]
The agent builder is already configured as follows: 
```
new AgentBuilder.Default()
    .disableClassFormatChanges()
    .with(RedefinitionStrategy.RETRANSFORM)
    .with(InitializationStrategy.NoOp.INSTANCE)
    .with(TypeStrategy.Default.REDEFINE)
    
    .type(...)
    .transform(new Transformer.ForAdvice()
        .include(...)
        .advice(...))

    .installOn(inst);
```

I found out that when a specific target class is already loaded and instrumented afterward, classes used within this class are not discovered by Bytebuddy. If I skipped instrumentation of the particular class, the other classes are successfully discovered. It needs more investigation though.

**Comment by sorabae** [comment]
I think it's relevant to `RedefinitionStrategy.DiscoveryStrategy.SinglePass`. I found out that when a loaded class is instrumented, it loads other classes that should be instrumented as well. But with the `SinglePass` strategy, classes thar are loaded during instrumentation are not passed to class file transformers. `RedefinitionStrategy.DiscoveryStrategy.Reiterating` seems a way to resolve this issue, but there is no `with` method that accepts `DiscoverStrategy`. Could someone let me know how to configure `DiscoverStrategy` or know other ways to instrument classes that are loaded during the initial instrumentation?

**Comment by sorabae** [comment]
Ah, I found it. It should be configured right after `.with(RedefinitionStrategy.RETRANSFORMATION)`. With the `Reiterating` strategy, all classes are now instrumented as expected. 

Just out of curiosity, do you know how much more runtime overhead the `Reiterating` strategy causes compared to `SinglePass`?

**Comment by raphw** [comment]
It depends on the total amount of classes that are loaded. When reiterating, all classes that are loaded during the instrumentation are discovered once again later. So it will be x-times what it takes to iterate over all classes.

**Comment by sorabae** [comment]
Would `Reiterating` instrument the same class more than once? I think it would instrument all loaded classes only once, including classes loaded during instrumentation, with some checking whether a class is instrumented in previous iterations. But, with "x-times what it takes to iterate over all classes", I'm not sure I understand `Reiterating` correctly.

**Comment by raphw** [comment]
No, the strategies that Byte Buddy offers make sure that any class is only instrumented once.

**Comment by sorabae** [comment]
I see, thank you very much for all the clarification and helps!

**Comment by dogourd** [comment]
> The agent builder is already configured as follows:
> 
> ```
> new AgentBuilder.Default()
>     .disableClassFormatChanges()
>     .with(RedefinitionStrategy.RETRANSFORM)
>     .with(InitializationStrategy.NoOp.INSTANCE)
>     .with(TypeStrategy.Default.REDEFINE)
>     
>     .type(...)
>     .transform(new Transformer.ForAdvice()
>         .include(...)
>         .advice(...))
> 
>     .installOn(inst);
> ```
> 
> I found out that when a specific target class is already loaded and instrumented afterward, classes used within this class are not discovered by Bytebuddy. If I skipped instrumentation of the particular class, the other classes are successfully discovered. It needs more investigation though.

Has this speculation been verified?
