### ISSUE TITLE
[Question] Inner class/method loading ?

### ISSUE THREAD

**Issue by Chaho12** [raphw/byte-buddy#1214]
First of all, thank you for creating such java agent library.

I am not that familiar with byte buddy or class loading, so please help me out.
I was wondering what config am I missing / or is it impossible to load class while advicing when modifying byte code.

My intent is to hook/advice Trino code, and load few class files that I created when building the byte buddy/java agent jar file.
1. When I create a function inside `HivePartitionManagerHookAdvice.class` file, I cannot call the function within `beforeHook` function. Why is that? Is it because only `beforeHook` code is loaded into the bytecode?
2. When I create another class and functions inside other class, lets say `Utils.class`, I cannot call any functions/class methods from that `Utils.class` despite that such class file is included when I create jar file via `mvn install`. Is this because it is not loaded ?

Here is my code.

HookAgent.java
```java
package com.naver.trino.hook;

import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.asm.Advice;
import net.bytebuddy.matcher.ElementMatchers;

import java.lang.instrument.Instrumentation;

/**
 * Java agent for Trino Hooking
 */
public class HookAgent {
    public static void premain(String arguments, Instrumentation instrumentation) {
        new AgentBuilder.Default()
                .type(ElementMatchers.named("io.trino.plugin.hive.HivePartitionManager"))
                .transform((builder, typeDescription, classLoader, module) -> builder
                        .method(ElementMatchers.named("getPartitionsAsList"))
                        .intercept(Advice.to(HivePartitionManagerHookAdvice.class)))
                .installOn(instrumentation);
    }
}
```
HivePartitionManagerHookAdvice.class (i've removed some code for security sake)
```java
package com.naver.trino.hook;

import io.trino.plugin.hive.HiveColumnHandle;
import io.trino.plugin.hive.HivePartition;
import io.trino.plugin.hive.HivePartitionResult;

import io.trino.spi.TrinoException;
import net.bytebuddy.asm.Advice;
import net.bytebuddy.implementation.bytecode.assign.Assigner;

import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import static io.trino.plugin.hive.HiveErrorCode.HIVE_EXCEEDED_PARTITION_LIMIT;

public class HivePartitionManagerHookAdvice {
    @Advice.OnMethodEnter
    static void beforeHook(
            @Advice.Origin String method,
            @Advice.AllArguments(readOnly = false, typing = Assigner.Typing.DYNAMIC) Object[] args) {
        if (!(args[0] instanceof HivePartitionResult)) return;

        HivePartitionResult partitionResult = (HivePartitionResult) args[0];

        int partitionSize = 0;
        String location = "";
        HivePartition partition;
        Iterator<HivePartition> iterator = partitionResult.getPartitions();
        while (iterator.hasNext()) {
            partition = iterator.next();
            if (location.isEmpty()) location = partition.getTableName().toString();
            partitionSize++;
        }

        Map<String, Map<String, String>> fieldMap = new HashMap<>();
        Map<String, String> logDate = Map.of(
            ...
        );
        fieldMap.put("log_date", logDate);

        List<HiveColumnHandle> partitionColumns = partitionResult.getPartitionColumns();
        for (HiveColumnHandle partitionColumn : partitionColumns) {
            String fieldName = partitionColumn.getName();

            if (!fieldMap.containsKey(fieldName)) continue;

            Map<String, String> testField = fieldMap.get(fieldName);
            int currentSize = ...;
            if (currentSize < partitionSize) {
                String logMsg = "...";
                System.out.println(logMsg);
                throw new TrinoException(HIVE_EXCEEDED_PARTITION_LIMIT, logMsg);
            }
        }
    }
}
```

**Comment by raphw** [comment]
The agent might live in a different class loader then the code that you are instrumenting. Note that Byte Buddy more or less copies the code in your advice and pastes it to the start/end of your method.

If you need other classes available in the target, you will have to inject them into this class loader.

**Comment by Chaho12** [comment]
Yeah, I understood that Byte Buddy does `{ run my method; run original method} except {}` in simplification.
When you say `inject them into this class loader`, what is this class loader? 
Do you mean that I need to add custom class loader like example below, MainClass.java code to `beforeHook` method?
- https://www.concretepage.com/java/custom-classloader-java-example

**Comment by raphw** [comment]
In the `transform` method, you receive a `classLoader`. You can use a `ClassInjector` to make helper classes available in this loader, but I normally recommend against it.

Another approach is to inject classes into the bootstrap loader which is available from anywhere.

**Comment by Chaho12** [comment]
Thx for explanation! I re-studied what classloader does and now understand what you mean by injected classes.
