### ISSUE TITLE
[Question] Can @Advice.OnMethodEnter got throwable's stacktrace ?

### ISSUE THREAD

**Issue by his1devil** [raphw/byte-buddy#1218]
Hi ~ @raphw 
when i use interceptor below to get constructor (like RuntimeException), the Object[] args only print single string message, not include stacktrace, and RuntimeException throws by jdk default, not  by app's code.
```
@Advice.OnMethodEnter
    public static <T> T beforeConstructor(@Advice.Origin Constructor<?> constructor, @Advice.AllArguments Object[] args) {
        try {
            System.out.println("Entered constructor: " + constructor + " | arg's length:" + args.length);
        } catch (Throwable e) {
            e.printStackTrace();
        }
        return null;
    }
```

Is there a way that can get Exception's stacktrace ?

BTW, matchers:
```
ElementMatchers.isSubTypeOf(Exception.class);
MethodMatchers.byConstructor(isConstructor());
```

**Comment by his1devil** [comment]
the code below would throw ArithmeticException, but the args only have [ / by zero], no stacktrace like where the code throws the exception
```
xxx
String s = String.valueOf(1 / 0);
xxx
```

**Comment by raphw** [comment]
An exception does not receive a stack trace in it's constructor. You would need to read an Exception type via @This and call the getStackTrace method. This is only possible from an exit advice!

**Comment by his1devil** [comment]
> An exception does not receive a stack trace in it's constructor. You would need to read an Exception type via @this and call the getStackTrace method. This is only possible from an exit advice!

Thank you raphw, it's worked.
BR
