### ISSUE TITLE
Allow matching annotations by name without locating annotation bytecode

### ISSUE THREAD

**Issue by laurit** [raphw/byte-buddy#1227]
Running [TypePoolDefaultLazyAnnotationListTest](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/test/java/net/bytebuddy/pool/TypePoolDefaultLazyAnnotationListTest.java) comment out all tests besides `testAnnotationIsPresent` in [AbstractAnnotationListTest](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/test/java/net/bytebuddy/description/annotation/AbstractAnnotationListTest.java). Add breakpoint to https://github.com/raphw/byte-buddy/blob/fbd78e1868c53b0c73b9528f821465bb3173794c/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/ClassFileLocator.java#L453 The breakpoint will hit 3 times for
```
net.bytebuddy.description.annotation.AbstractAnnotationListTest$Holder
net.bytebuddy.description.annotation.AbstractAnnotationListTest$Foo
net.bytebuddy.description.annotation.AbstractAnnotationListTest$Bar
```
Where `Holder` is the tested class and `Foo` and `Bar` are annotations on that class. It would be nice if it would be possible to do the match without locating `Foo` and `Bar`.

**Comment by raphw** [comment]
This is tricky, the annotation contract dictates that annotations with missing types are not to be rendered. So to speak, if
 
    net.bytebuddy.description.annotation.AbstractAnnotationListTest$Foo
    net.bytebuddy.description.annotation.AbstractAnnotationListTest$Bar

cannot be located, there will not be an error but the annotations would not be there. This is why the types need to be looked up.

**Comment by laurit** [comment]
From the api perspective it definitely makes sense to mimic what java annotation apis do and not return annotations with missing type. Though locating the bytes for the annotation class still has a non-zero cost. It would be nice if it would be possible to skip it without having to resorting to reflection to read `annotationTokens` from `LazyTypeDescription`.

**Comment by raphw** [comment]
If you wanted to avoid the lookup, you can create a custom `TypePool` where you return the annotation type without looking it up from disk. Would that be a solution?

**Comment by laurit** [comment]
I'm already using a custom `TypePool` so that is fine. How do I know that it is currently looking for an annotation?

**Comment by raphw** [comment]
That's impossible, you would need to register the names. You can however do so by maintaining a set of names that are looked up?

The look up is triggered after the check so it would be delayed until you populated the set with the name.

**Comment by raphw** [comment]
Alternatively, you could extend the type pool and ovverride the methods for reading annotations. The types are protected to type pool instances.

**Comment by laurit** [comment]
> Alternatively, you could extend the type pool and ovverride the methods for reading annotations. The types are protected to type pool instances.

what do you mean by methods reading annotations, `getDeclaredAnnotations` in `MethodDescription`?

> That's impossible, you would need to register the names. You can however do so by maintaining a set of names that are looked up?

You mean that I'd keep a set of annotation type names and based on that return a different result from `doDescribe`. How do I fill that list, how would I know which annotations current type uses?

**Comment by raphw** [comment]
Yes, you would have something like:

    Set<String> annotations = new HashSet<>();
    TypePool typePool = makePoolWithAssumedAnnotations(annotations);
    annotations.add("my.Annotation");
    assert typePool.describe("myType").resolve()getDeclaredAnnotations().filter(named("my.Annotation").size() == 1;

The pool would simply return a mocked up type description for an annotation type in the set if found.
