### ISSUE TITLE
Can not remote debug when using byte-buddy

### ISSUE THREAD

**Issue by wutingjia** [raphw/byte-buddy#1229]
I use byte-buddy like this：
```java
public class BwcActuatorInjection implements ServletContextListener {

    @Override
    public void contextInitialized(ServletContextEvent servletContextEvent) {
        ByteBuddyAgent.install();
        new ByteBuddy().redefine(xxx.class)
                .visit(Advice.to(BwcActuatorInterceptor.class).on(ElementMatchers.named("saveDraft").or(ElementMatchers.named("withdrawRecord"))
                .make()
                .load(xxx.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent())
                .getLoaded();
    }
```
Advice like:
```java
public class BwcActuatorInterceptor {

    private BwcActuatorInterceptor(){}

    @Advice.OnMethodEnter
    public static void OnMethodEnter(@Advice.Origin Method method, @Advice.Local("t") Transaction t) {
        
    }

    @Advice.OnMethodExit(onThrowable = Throwable.class)
    public static void onMethodExit(@Advice.Origin Method method, @Advice.Return BwcResultData<?> returnValue, @Advice.Thrown Throwable throwable, @Advice.Local("t") Transaction t) {

}
```
But In this case, I can not remote debug with IDEA.  As long as I try this, the service will down.
Is there some solution?

**Comment by raphw** [comment]
No, those bits are inlined code, they are not actually executed. You can only set a breakpoint in the instrumented method. There is an attribute on `@OnMethodEnter` to prepend the line number such that a breakpoint in the first line will stop for the enter advice. You can then step forward. Variables in the advice should be shown as unnamed.

**Comment by wutingjia** [comment]
> No, those bits are inlined code, they are not actually executed. You can only set a breakpoint in the instrumented method. There is an attribute on `@OnMethodEnter` to prepend the line number such that a breakpoint in the first line will stop for the enter advice. You can then step forward. Variables in the advice should be shown as unnamed.


Thanks~, I know whats you mean. I know I can use delegate mode instead of inline mode to debug my code locally. 
But my question is as long as I try to **remote debug** with IDEA, **the service will down** .It means I start my server in remote server，and using remote debug (with IDEA) attach remote jvm. Then make a request，the server will be broken.
If  I delete byte-buddy relevant code, it will not happen

**Comment by raphw** [comment]
I assume that IDEA does some Java agent fun itself. Can you check the command line and try to disable that? I assume that the IDEA agent does not like other agents being active. Alternatively, try running from the command line with remote attach from IDEA.

**Comment by wutingjia** [comment]
I'm not sure how to use the command line for remote debugging.I just do like this
![image](https://user-images.githubusercontent.com/33154970/162435368-60c34942-6a76-4052-91d7-211eab03f348.png)
In your opinion,this way will carry some IDEA agent feature?

**Comment by raphw** [comment]
You'd have to copy the line in that window and add it to the Java command. Then xonnect via the button.

**Comment by wutingjia** [comment]
I use jdb tool to test remote debug with breakpoint without IDEA. But it still not work.
Following is my step：
1、Using byte-buddy like above and start service in remote jvm
2、jdb -attach xxxxx:xxxx
3、stop at  instrument method:344
4、after a while jdb will be stopped because "internal error", remote service is down

5、without using byte-buddy like above and start service in remote jvm
6、everything is ok

So, I think its the problem byte-buddy,not IDEA. Could you give it a try？

**Comment by wutingjia** [comment]
I can not recur this problem in my the simplest springboot demo.
Maybe, it relevant to my company running env or private rpc framework.
If we don't have any ideas, forget this problem

**Comment by wutingjia** [comment]
yeah ,based on IDEA 2021 and jdk8.  I can not  recur this problem in my own env too. Just can recur in my company env (also IDEA 2021 and jdk8).So as I said above，Maybe, it relevant to my company running env or private rpc framework.
I suggest we just forget this problem, it seems a a very special case.

**Comment by raphw** [comment]
Seems to be environment related, yes. I am closing the ticket.
