### ISSUE TITLE
update byte buddy has exception

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#123]
i update version from  1.3.13  to 1.3.19
and run programmer throw exception 
`onError:com.dragon.study.bytebuddy.advice.AdviceProfiled
java.lang.IllegalStateException: Illegal annotation interface net.bytebuddy.asm.Advice$Thrown for java.lang.Throwable arg2
`
how can i slove this problem?

**Comment by raphw** [comment]
By default, the `Advice` component does no longer catch exceptions for `Advice.OnMethodExit`. You now have to specify the exception that is to be catched (if any) on the latter annotation in order to use `Advice.Thrown`.

**Comment by dragontree101** [comment]
thanks very much ,  i try it tomorrow  ：）
