### ISSUE TITLE
how can i use JSRInlinerAdapter in bytebuddy

### ISSUE THREAD

**Issue by 1057105012** [raphw/byte-buddy#1231]
I got an error when I came across the JSR and RET directives, I want to fix it, But I noticed that ByteBuddy does not provide a JSRInlinerAdapter

**Comment by raphw** [comment]
Byte Buddy does not use it internally but if you are using ASM, I recommend using byte-buddy-dep with your own ASM dependency.

You should then shade Byte Buddy or isolate it in a separate class loader.
