### ISSUE TITLE
ByteBuddy and JaCoCo ClassNotFoundException

### ISSUE THREAD

**Issue by boev** [raphw/byte-buddy#1233]
Hi, I would like to instrument and add validation to the constructors of my Record classes. To do that I would like to use ByteBuddy and  I think I have the soluton ready but....

I am facing the following problem: Caused by: `java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_b6258fc.Offline`

Using the following JaCoCO
```
<dependency>
      <groupId>org.jacoco</groupId>
      <artifactId>org.jacoco.agent</artifactId>
      <classifier>runtime</classifier>
      <version>0.8.8</version>
      <scope>test</scope>
    </dependency>
```

**Comment by raphw** [comment]
How does this error occur? Is there no log or anything?
