### ISSUE TITLE
Bytebuddy occupies too much memory 

### ISSUE THREAD

**Issue by 1057105012** [raphw/byte-buddy#1240]
I need interface staking, so I need to generate a Type description for each object, but there will be a lot of ByteBuddy objects during the bytecode conversion, and I want to use a way to make staking slow, but with a lower memory consumption, which exists, To avoid oom problems when memory is small

**Comment by raphw** [comment]
Are you caching these objects? A JIT should erase most allocations in BB anyways, I have not heard this to be a problem before.
