### ISSUE TITLE
Can I declare a local variable in Assigner?

### ISSUE THREAD

**Issue by luozhenyu** [raphw/byte-buddy#1241]
I want to declare a local variable with `Opcodes.ASTORE` in my custom assigner, but the return type is a `StackManipulation` which can not delare local variable size. I think I need a `ByteCodeAppender`. Could you give some adivce?

https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/bytecode/assign/Assigner.java#L44-L55

**Comment by raphw** [comment]
Unfortunately, that's not possible as the assignment does not necessarily happen in a context where the local variable is available.

What are you trying to do?

**Comment by luozhenyu** [comment]
@raphw I am writing a library and define a struct named `OuterClass`. The library wants to get some fields of the struct named `OuterClassImpl` which is generated by thrift compiler. They are similar but `OuterClassImpl` does not implement `OuterClass`. 

So my approach is generating a delegating class `OuterClassDelegate` with byte-buddy that implements `OuterClass` and delegates `OuterClassImpl`. It works well on basic types, but does not work on a nested type `InnerClass`.

Then I created a nested delegating class named `InnerClassDelegate` and the method `OuterClassDelegate::getInnerClass`. In this method, a local variable `innerClass` is used.

```java
public interface OuterClass {

    String getValue();

    InnerClass getInnerClass();

    interface InnerClass {
        int getValue();
    }
}

public static class OuterClassImpl {
    private final String value = "out class impl";
    private final InnerClassImpl innerClass = new InnerClassImpl();

    public String getValue() {
        return value;
    }

    public InnerClassImpl getInnerClass() {
        return innerClass;
    }

    public static class InnerClassImpl {
        private final int value = 100;

        public int getValue() {
            return value;
        }
    }
}

public static class OuterClassDelegate implements OuterClass {

    private final OuterClassImpl delegate;

    public OuterClassDelegate(OuterClassImpl delegate) {
        this.delegate = delegate;
    }

    public OuterClassImpl getDelegate() {
        return delegate;
    }

    @Override
    public String getValue() {
        return delegate.getValue();
    }

    @Override
    public OuterClass.InnerClass getInnerClass() {
        OuterClassImpl.InnerClassImpl innerClass = delegate.getInnerClass();
        if (innerClass == null) {
            return null;
        }
        return new InnerClassDelegate(innerClass);
    }

    public static class InnerClassDelegate implements InnerClass {
        private final OuterClassImpl.InnerClassImpl delegate;

        public InnerClassDelegate(OuterClassImpl.InnerClassImpl delegate) {
            this.delegate = delegate;
        }

        public OuterClassImpl.InnerClassImpl getDelegate() {
            return delegate;
        }

        @Override
        public int getValue() {
            return delegate.getValue();
        }
    }
}
```

**Comment by raphw** [comment]
An assigner would not really help you here, I think? You would need a jump instruction. Otherwise, I would just call the getter twice, rather then storing it in s variable.
