### ISSUE TITLE
How to intercept all the classes in a project which has isolated classloaders

### ISSUE THREAD

**Issue by all4you** [raphw/byte-buddy#1243]
Hi, I am using ByteBuddy to create my SDK to monitor the business logic, the SDK will be a dependency in other applications.
I have meet a problem that some application has isolated classloaders to load classes which cause the intercept failure.
I know that is a classLoader issue but I don't know how to solve it.

The application has isolated classloaders like blow:
![image](https://user-images.githubusercontent.com/6661305/165100052-dab66d02-955d-4242-963f-bbffe06cbb8a.png)
![image](https://user-images.githubusercontent.com/6661305/165100323-c0a2be75-7ad5-4bc8-a514-b2c24b011e5a.png)

The SDK runs within the application(not a agent way), and the application has a container that load the platform classes with ContainerClassLoader, and the container has some service jars, each jar has a ServiceClassLoader to load the classes in the jar.
The SDK classes is loaded by AppClassLoader or ContainerClassLoader.

My question is how to intercept all the classes in the Service jars in my SDK without IllegalAccessError.

**Comment by raphw** [comment]
That it was Advice is for, it inlines the code into the targeted class. You can the call out to a dispatcher, normally a class that is injected into the bootstrap loader.

If you look for my name on YouTube, I have introduced this solution in talks.

**Comment by all4you** [comment]
> 

Thank you, I will now go search the content in YouTube.

**Comment by all4you** [comment]
Hi,I have searched something that you shared in YouTube
![image](https://user-images.githubusercontent.com/6661305/165230763-ad5e5222-129d-442e-a67a-ae616082093c.png)
you suggest that use AgentBuilder.Transformer.ForAdvice to support System Classloader
but I have a more complex scene, I need to bind some customer annotations like blew:
![image](https://user-images.githubusercontent.com/6661305/165237695-45409454-0c42-4514-b169-a66d2d2e3014.png)
How do I do that?

**Comment by raphw** [comment]
Provide it to the constructor.

**Comment by all4you** [comment]
I have no idea about 'Provide it to the constructor', can you please show me some code? 
How to provide the parameters to `com.my.interceptor.MyInterceptor` ?
```java
builder.visit(new AgentBuilder.Transformer.ForAdvice()
             .include(MyPlugin.class.getClassLoader())
             .advice(elementMatcher, "com.my.interceptor.MyInterceptor")
)
```

**Comment by raphw** [comment]
AgentBuilder.Transformer.ForAdvice(Advice.withCustomConfiguration());

**Comment by all4you** [comment]
Thank you I will try it.
