### ISSUE TITLE
Extra pom.xml in released byte-buddy jar

### ISSUE THREAD

**Issue by mityayak** [raphw/byte-buddy#1245]
Byte-buddy jar which is pushed to maven repository, like https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.12.10/byte-buddy-1.12.10.jar contains pom.xml from byte-buddy-dep: META-INF/maven/net.bytebuddy/byte-buddy-dep/pom.xml

**Comment by raphw** [comment]
Indeed, it's fixed on master and will be resolved with the next release.
