### ISSUE TITLE
How could I intercept the Constructor of RuntimeException's subclasses with java agent ?

### ISSUE THREAD

**Issue by kav012375** [raphw/byte-buddy#1256]
here is my agent permain code :

```
public static void premain(String agentArgs, Instrumentation inst) {
        new AgentBuilder
            .Default()
            .disableClassFormatChanges()
            .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
            .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
            .with(Default.REDEFINE)
            .with(AgentBuilder.InjectionStrategy.UsingUnsafe.INSTANCE)
            .with(new NoOpAgentListener())
            .type(ElementMatchers.failSafe(ElementMatchers.isSubTypeOf(RuntimeException.class)))
            .transform(((builder, typeDescription, classLoader, module) ->
                builder
                    .visit(Advice.to(ExceptionAdvice.class)
                    .on(ElementMatchers.isConstructor()
                        .and(ElementMatchers.not(ElementMatchers.isSynthetic()))
                    ))
            ))
            .installOn(inst); 
}
```

and the following is my interceptor:

```
public class ExceptionAdvice {

    @Advice.OnMethodEnter
    public static void onMethodEnter(){
        System.out.println("- - - - - - - - - - -");
        System.out.println("enter！");
    }

    @Advice.OnMethodExit
    public static Object onMethodExit(
        @Advice.Origin Constructor<?> constructor,
        @Advice.AllArguments Object[] args,
        @Advice.This Object thisObj) throws Exception {
        System.out.println(" i am in now !");
        return thisObj;
    }
}
```

when I test it by using '-javaagent', it is doesn't work T_T ...
So, what should I do ?

**Comment by raphw** [comment]
Have you tried adding a listener to see what's happening? Looks correct at first glance!

**Comment by kav012375** [comment]
yeah, I already try. seems to be ok , but unfortunately it does not work. 
btw, I would like to intercept such like IllegalStateException, NullPointerException ...
with onComplete listener , I found that it's classLoader is null. Could these Exceptions were loaded by BootstrapLoader?
How could I intercept them which was loaded by Bootstrap ?

here is listen output :
onComplete --- type = java.lang.IllegalStateException, classLoader = null, loaded = true 
onComplete --- type = net.bytebuddy.jar.asm.ClassTooLargeException, classLoader = sun.misc.Launcher$AppClassLoader@18b4aac2, loaded = true

**Comment by raphw** [comment]
Ah, in this case you need to define an explicit `ignore` matcher. This can drastically reduce the efficiency of the agent as it needs to scan all boot classes but if you can exclude some packages still, it will not be a big problem.

**Comment by kav012375** [comment]
means that ,  I have to redefine the IllegalStateException ( for  ex ) with  a new ByteBuddy(), and then use ByteBuddyAgent.install() to make them exceptions load by system ?

**Comment by raphw** [comment]
No, simply add a line as ignore(none()), or more specific if you care for performance.
