### ISSUE TITLE
@Advice.OnMethodEnter and @Advice.OnMethodExit is thread safe ?

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#126]
i use @Advice.OnMethodEnter method return a  value and @Advice.OnMethodExit method receive the value by @Advice.Enter, if in concurrent env, the send value and receive value is thread safe ?

**Comment by dragontree101** [comment]
now in @Advice.OnMethodEnter return hashmap parameter, and in @Advice.OnMethodExit get hashmap parameter, use this way to pass parameter between in @Advice.OnMethodEnter and  @Advice.OnMethodExit is best way? or have any better way?  
thanks very much

**Comment by raphw** [comment]
Yes, it is thread-safe. A value that is returned from `OnMethodEnter` is stored on the operand stack where it can only be accessed by the executing thread. This is equivalent to

```java
void foo() {
Object value = onMethodEnter();
{ /* actual code */ }
onMethodExit(value);
}
```

Note that object allocation is not normally a problem here if you are not using primitives. The advice code is inlined (by default) where the JVM easily understands that the object does not escape the method by performing escape analysis. As a result, the object allocation is typically erased.

**Comment by dragontree101** [comment]
thanks!
