### ISSUE TITLE
Easy way to generate the descriptor string to use in an ElementMatchers.hasDescriptor(String)?

### ISSUE THREAD

**Issue by mpet** [raphw/byte-buddy#1261]
Hi,

I have the following code:

```
AnnotationDescription annotationDescription = AnnotationDescription.Latent.Builder.ofType((Class<? extends Annotation>) annotationClass).build();
		new ByteBuddy()
		  .redefine(clazz)
		  .visit(new MemberAttributeExtension.ForMethod()
		    .annotateMethod(annotationDescription)
		    .on(ElementMatchers.hasMethodName(methodName).and(ElementMatchers.hasDescriptor(descriptor))))
		  .make().load(clazz.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
````
to add an annotation to a existing class and it's method.

Is there a way to create the descriptor String? We are going from javaassist to bytebuddy where we could do:

```
String descriptor = Descriptor.ofMethod(CtClass.intType, new CtClass[] { CtClass.intType, CtClass.intType });
```

//mike

**Comment by raphw** [comment]
I'd use a matcher as:

takesArguments(int.class, int.class).and(returns(int.class))

Descriptors can be resolved via ASMs Type class.

**Comment by mpet** [comment]
Yes I could use matchers but I have a method that should take a string as input ( that is the descriptor).
Is it possible to use ASM to generate a descriptor as String?

**Comment by raphw** [comment]
Either use `Type.getDescriptor` or use `MethodDescription.SignatureToken.getDescriptor`.

**Comment by mpet** [comment]
So this class is the one?
import aj.org.objectweb.asm.Type;

**Comment by raphw** [comment]
Within net.bytebuddy package. That's probably another shade.

**Comment by mpet** [comment]
![image](https://user-images.githubusercontent.com/1445826/171827931-81a2dd9c-6153-44b1-93e2-063ceb57e396.png)

Which one to use for Type?

**Comment by mpet** [comment]
Found it: 
net.bytebuddy.jar.asm.Type.getMethodDescriptor(method)
Not sure why it is in jar?
