### ISSUE TITLE
How to remove an annotation easily

### ISSUE THREAD

**Issue by mpet** [raphw/byte-buddy#1262]
Hi,

I found the following code:

new ByteBuddy()
		  .redefine(clazz)
		  .visit(new MemberRemoval().

![image](https://user-images.githubusercontent.com/1445826/171792994-46336c27-242a-4581-9b67-d467eeb69da7.png)

but no stripAnnotation? Is there any plans for it? I would make my life easier :-)

//mike

**Comment by raphw** [comment]
Looking at it, I now remember why this is not an option. Annotations are visited by their descriptor and only then it is possible to abort the writing, before paring the entire annotation. Therefore, Byte Buddy normally shortwires annotations, for efficiency reasons.

What you need to do is to configure Byte Buddy to replay annotations: `new ByteBuddy().with(AnnotationRetention.DISABLED)`, and then you can register a `Transformer` where you change fields or methods to contain certain annotations or not. Then these annotations are written as is.
