### ISSUE TITLE
Provide a bill of materials (BOM)

### ISSUE THREAD

**Issue by bjmi** [raphw/byte-buddy#1264]
I figured that there is a number of byte-buddy artifacts, so it might be useful to provide a BOM (Bill Of Materials) that lists all versions of all artifacts in a central place.
 
Such a thing could then be consumed in a Maven multi project build through
 
```
<dependencyManagement>
    <dependency>
        <groupId>net.bytebuddy</groupId>
        <artifactId>byte-buddy-bom</artifactId>
        <version>${byte-buddy.version}</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
    [...]
</dependencyManagement>
```

and this could be referenced in individual module files like so:

```
<dependencies>
    <dependency>
      <groupId>net.bytebuddy</groupId>
      <artifactId>byte-buddy</artifactId>
    </dependency>
    <dependency>
        <groupId>net.bytebuddy</groupId>
        <artifactId>byte-buddy-agent</artifactId>
    </dependency>
    [...]
</dependencies>
```

Examples:
* [Mockito BOM](https://search.maven.org/remotecontent?filepath=org/mockito/mockito-bom/4.6.1/mockito-bom-4.6.1.pom) - [#2321](https://github.com/mockito/mockito/issues/2321)
* [Jackson BOM](https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/jackson-bom/2.13.3/jackson-bom-2.13.3.pom)
* [JUnit Jupiter BOM](https://search.maven.org/remotecontent?filepath=org/junit/junit-bom/5.8.2/junit-bom-5.8.2.pom)
* [Log4J2 BOM](https://search.maven.org/remotecontent?filepath=org/apache/logging/log4j/log4j-bom/2.17.2/log4j-bom-2.17.2.pom)

Creating and publishing such a BOM would help a lot. Thanks!

**Comment by raphw** [comment]
You are right, that's a convenient extra. You will be able to import *byte-buddy-parent* as a BOM starting with the next release.
