### ISSUE TITLE
”MethodDelegation“ Non execution of delegation

### ISSUE THREAD

**Issue by shixiaoxianga** [raphw/byte-buddy#1268]
Hello, author. I am a novice byte buddy. 

I use "methoddelegation" to intercept method inputs. However, the specified "myinterceptor" is not executed, and no error is reported in the listener Solution Looking forward to your reply!
version: 1.12.10

` 

 public static void premain(String arg, Instrumentation instrumentation) {

        new AgentBuilder.Default()

                .ignore(ElementMatchers.nameStartsWith("java."))
                .ignore(ElementMatchers.nameStartsWith("sun."))
                .ignore(ElementMatchers.nameStartsWith("agent."))
                .type(ElementMatchers.nameStartsWith("com.danduola"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder,
                                                            TypeDescription typeDescription,
                                                            ClassLoader classLoader,
                                                            JavaModule module) {
                        System.out.println("=========================transform====================="+typeDescription.toString());
                        builder
                                .method(ElementMatchers.any())
                                .intercept(MethodDelegation.withDefaultConfiguration().to(MyInterceptor.class));
                        return builder;
                    }
                })
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(new AgentBuilder.RedefinitionStrategy.Listener() {
                    @Override
                    public void onBatch(int index, List<Class<?>> batch, List<Class<?>> types) {
                        types.forEach(clazz->{
                            System.out.println("onBatch"+clazz.getName());
                        });
                        batch.forEach(clazz->{
                            System.out.println("onBatch"+clazz.getName());
                        });
                    }

                    @Override
                    public Iterable<? extends List<Class<?>>> onError(int index, List<Class<?>> batch, Throwable throwable, List<Class<?>> types) {
                        System.out.println("重新定义失败："+index+"----"+throwable.toString());
                        System.out.println(throwable.getMessage());
                        types.forEach(clazz->{
                            System.out.println("onError"+clazz.getName());
                        });
                        batch.forEach(clazz->{
                            System.out.println("onError"+clazz.getName());
                        });
                        return null;
                    }

                    @Override
                    public void onComplete(int amount, List<Class<?>> types, Map<List<Class<?>>, Throwable> failures) {

                    }
                })
                .with(new AgentBuilder.Listener() {
                    @Override
                    public void onDiscovery(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded) {
                    }

                    @Override
                    public void onTransformation(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module, boolean loaded, DynamicType dynamicType) {
                        try {
                            dynamicType.toJar(new File(System.getProperty("user.dir")+"/java.class"));
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                        System.out.println("转型目标："+typeDescription.toString());
                    }

                    @Override
                    public void onIgnored(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module, boolean loaded) {
                    }

                    @Override
                    public void onError(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded, Throwable throwable) {
                        System.out.printf("错误:%s name: %s",throwable.toString(),typeName);
                        System.out.printf(throwable.getMessage());
                    }

                    @Override
                    public void onComplete(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded) {
                    }
                })
                .installOn(instrumentation);
    }`

MANIFEST.MF

`

Manifest-Version: 1.0
Project-name: agent-test1
Premain-Class: com.agent.test.Agent
Archiver-Version: Plexus Archiver
Built-By: xxxx
Can-Redefine-Classes: true
Can-Retransform-Classes: true
Project-version: 1.0-SNAPSHOT
Created-By: Apache Maven
Build-Jdk: 1.8.0_171
Main-Class: com.agent.test.Agent

`

`

package com.agent.test;

import net.bytebuddy.implementation.bind.annotation.Origin;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;
import net.bytebuddy.implementation.bind.annotation.SuperCall;

import java.lang.reflect.Method;
import java.util.concurrent.Callable;

public class MyInterceptor {

    /*        @RuntimeType
            public Object intercept(@Origin Method method,
                                    @SuperCall Callable<Object> callable) throws Exception {
                System.out.println("方法："+method.getName());
                Object call = callable.call();
                System.out.println("方法："+method.getName()+"结束了");
                return call;

            }*/
    @RuntimeType
    public static Object intercept(@RuntimeType Object value) {
        System.out.println("Invoked method with: " + value);
        return value;
    }
}

`

**Comment by gitxzw** [comment]
I feel that the "intercept()" function is not effective.

**Comment by raphw** [comment]
`MethodDelegation` does not normally work in combination with redefinition. I would recommend you to use `Advice` instead via `visit`. Is there no output indicating an error? Are the classes in question shown as ignored or as transformed?

Also, your chaining of `ignore` is incorrect where each call will replace the latter configuration. You would need to set `or` after the first `ignore`.

**Comment by shixiaoxianga** [comment]
The wrong "return" is used in the "transform" method. In addition, change "new myinterceptor" to "myinterceptor.class". Why is that?

**Comment by raphw** [comment]
What do you expect to be injected in your interceptor?

I would also recommend you to set `.disableClassFormatChanges()`.

**Comment by shixiaoxianga** [comment]
I want to intercept some methods. What is the recommended method

**Comment by raphw** [comment]
I'd recommend you to use `Advice` and `OnMethodEnter` and `OnMethodExit`. Register it via `builder.visit(Advice.to(...).on(...))` using `.disableClassFormatChanges()`. This would likely be the best approach.

**Comment by shixiaoxianga** [comment]
> 我建议您使用`Advice`and`OnMethodEnter`和`OnMethodExit`。`builder.visit(Advice.to(...).on(...))`通过使用注册它`.disableClassFormatChanges()`。这可能是最好的方法。

OK, thanks
