### ISSUE TITLE
The intercepted method does not match the actual interceptor.

### ISSUE THREAD

**Issue by shixiaoxianga** [raphw/byte-buddy#1269]
Hello author, I encountered a problem when calling the following code :
```
Dynamictype.builder <? >#return builder
. method(ElementMatchers.named(“A”)）
. intercept(MethodDelegation.to(new ClassEnhanceInterceptor(“A”)));
```

Here is one of my actual codes. The places marked with comments are looped

        AgentBuilder builder = new AgentBuilder.Default()
                .with(new AgentListener());
                // My actual code loops here
        builder = builder.type(ElementMatchers.named(classEnhance.getClassName()))
                .transform(new Transformation(classEnhance));
                // Here the cycle ends
        builder.installOn(instrumentation);

This is my real code. The following "agentbuilder" method is the above code

        AgentBuilder builder = new AgentBuilder.Default()
                .with(new AgentListener());
        for (Class<?> aClass : enhanceClass) {
            try {
                AbstractClassEnhance classEnhance = (AbstractClassEnhance) aClass.newInstance();
                builder = agentBuilder(builder, classEnhance);
            } catch (Exception e) {
                log.error("init classEnhance error :{}", e.toString());
            }
        }
        builder.installOn(instrumentation);

    public static class Transformation implements AgentBuilder.Transformer {

        public AbstractClassEnhance classEnhance;

        public Transformation(AbstractClassEnhance classEnhance) {
            this.classEnhance = classEnhance;
        }

        @Override
        public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder,
                                                TypeDescription typeDescription,
                                                ClassLoader classLoader,
                                                JavaModule module) {
            return builder
                    .method(classEnhance.buildMethodMatchers())
                    .intercept(MethodDelegation.to(new ClassEnhanceInterceptor(classEnhance)));
        }
    }

The intercepted method does not match the actual interceptor.

When I intercept method "A", Construction parameter obtained in interceptor is not 'A', but the construction parameter "B" of my last interceptor instance“. I expect that the value in the constructor in the A interceptor is also A

Can you help me see what's wrong or some guidance.

Is the assigned interceptor a singleton?

Looking forward to the author's reply

**Comment by raphw** [comment]
If two matchers match the same method, the last matcher will be applied. Ideally, you group all interceptions to a single dispatcher and resolve the argument by the input method via some generic argument. Adding many indiviual interceptors is normally more expensive.
