### ISSUE TITLE
Instrumenting in different JVM 

### ISSUE THREAD

**Issue by MadMan0708** [raphw/byte-buddy#127]
Hi Rafael,
 first, thanks for great library!

I'm using ByteBuddy in the following way ( it's kinda complicated, but desired approach in my case).

I have one JVM running with attached native agent in C++. This native agent sends bytecode of each class which is about to be loaded to another JVM ( I call it Instrumentor JVM) where the bytecode is transformed and after that send back to the native agent and at the end loaded in the original JVM.

The method I use for the transformation in the Instrumentor JVM looks like

```   
 public byte[] instrument(String className, final byte[] bytecode) throws IllegalClassFormatException{
        String nameAsInJava = className.replace("/",".");

        return new AgentBuilder.Default()
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .disableBootstrapInjection()
                .type(ElementMatchers.named(nameAsInJava))
                .transform(TransformersManager.transformers.get(nameAsInJava)).makeRaw().transform(cl, className, null, null, bytecode);
    }
```

If I try to instantiate the transformed class in the Instrumentor JVM it all works fine, however when I try it in original JVM it ends up with error that bytebudy classes could not be found. If I add bytebudy jar on the classpath of the original JVM, it ends up with error that class with the interceptor could not be found.

It looks like that the transformed bytecode references ByteBuddy and interceptors and because these  classes are not available in the original JVM, it ends up with the problem described above.

Do you please know if I can set ByteBuddy somehow in order to make this work?

I can always add ByteBuddy jar on the classpath of the original JVM and load somehow store and load desired interceptor class dynamically using some classloader in the original JVM, but I was wondering if there's any better way.

I hope this make sense, Thanks a lot for your time and help!

**Comment by raphw** [comment]
Hello,

when Byte Buddy creates a class for you using an interceptor, the generated class is similar to the following. Assuming the original class `Foo`:

```java
class Foo {
  String bar() {
    return "bar"; 
  }
}
```

An interception to some interceptor object `Qux` would result in the following redefined version:

```java
class Foo {
  static Qux $interceptor;
  String bar() {
    return $interceptor.intercept(); 
  }
}
```

Obviosuly, for this to work the class `Qux` must be known to your target machine that executes the code. This is however not sufficient. Additionally, the `$interceptor` field must be set which Byte Buddy does by adding a class initializer block to the class (`static { ... }`) where the field is set. It is impossible to set this field during the instrumentation where the class is not yet loaded.

If you are running the class on the same JVM that generates it, Byte Buddy takes care of all of this for you but in your case, this does not work. You can however configure this behaviour:

1. Byte Buddy lets you choose an initialization strategy that determines the (optional) creation of a class initializer block. You can define a no-op strategy but read the `LoadedTypeInitializer` using an `AgentBuilder.Listener` in the `onTransformed` method. You can serialize this instance (given that your `Qux` class is serializable) and send it to the machine that loads your class. Also, using this listener, you can find out if there are auxiliary classes that need to be loaded by the target VM. Auxiliary classes are helper classes that need to be loaded to make the instrumentation work. Auxiliary classes are proxies such as the `@SuperCall` classes.

2. You can avoid using an instance of `Qux` but delegate to `Qux` as a class. This way, it suffices to load the class `Qux` by the target VM as the `LoadedTypeInitializer` does not need to be run (it is "not alive" in Byte Buddy terminology.

3. You can replace the interception API with the `Advice` instrumentation which inlines the byte code of your methods into the class file. This way, you can avoid changes to the class file altogether and you guarantee that the class can be loaded directly. The downside of this API is that the `Advice` component only allows for *around advice*. You still need to disable self-initialization; you can call `.disableClassFormatChanges()`.

PS: Bootstrap injection is disabled by default, you do not need to call the method in the above example.

**Comment by MadMan0708** [comment]
Hi,
  thanks a lot for great explanation! I'll have a look on it today.

Kuba

**Comment by MadMan0708** [comment]
Sorry to open this one again.

I went through your response one more time. The Byte Buddy framework is therefore needed in case of option 1 and 2, but if I get it right, when using `Advice`  component there's no need for Byte Buddy framework to be available on the JVM where the class is loaded, or am I wrong ?

Are there any plans to support inlining the code in the the class file also without `Advice` component ? It would be great given this use case.

Thanks, Kuba

**Comment by raphw** [comment]
Hi Kuba,
No problem. Please always ask.

The Advice component will be the only one to support inlining. The delegation model cannot be inlined in the general case which is why it idnotsupported.

You can avoid Byte Buddy on the target machine by delegating to a named field (if that is the component you use). You then need to make sure to set that field on the target machine manually before using the class.

**Comment by MadMan0708** [comment]
Hi,
thanks! Just to clarify my understanding about the difference between option 1 and option 2 you mentioned in the first reply. Option 2 represents the case when we do delegation `MethodDelegation.to(Foo.class)`, where `Foo` has static methods acting as interceptors, right ? Is in this case is Byte Buddy framework needed as well or  not and the instrumented class looks like:

```
class Foo {

  String bar() {
    return Interceptor.staticMethod()
  }
}
```
I suppose it isn't like that, because otherwise you would probably mention that already. If this would be the case, all what had to be done was to send load the interceptor class to target machine and load it there. 


 I've been playing with the solution using named field. I have really super simple transformer and interceptor for now.

My `Transformer` looks like
```
public class SimpleTransformer implements AgentBuilder.Transformer {
    @Override
    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader) {
        return builder.method(ElementMatchers.nameEndsWith("print"))
                .intercept(MethodDelegation.toInstanceField(SimpleInterceptor.class, "interceptor").andThen(SuperMethodCall.INSTANCE));
    }
}
```
is the delegation `toInstanceField` what you meant by named field please ?

The Interceptor like 
```public class SimpleInterceptor {
    public void print(){
        System.out.println("Method print was instrumented ");
    }
}
```

If I understand it well the `named field` is static field in the instrumented class so in order to set it I could do in target machine: 
``` InstrumentedClass.namedField = new Interceptor()```, or am I wrong ?

Thanks again!

**Comment by raphw** [comment]
You are right both times and the fact that you name the instance field made me call this "named field" whithout the latter being official terminology. 

Note that you still needto declare annotations on the delegation target. However, the target machine still does not need to know about Byte Buddy as the JVM supresses unknown annotation types.
