### ISSUE TITLE
Gradle plugin version 1.12.11 doesn't seem to work with Gradle 7.3

### ISSUE THREAD

**Issue by feliperuiz** [raphw/byte-buddy#1272]
When upgrading from 1.12.10 to 1.12.11, I was faced with this error from Gradle:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':foo:byteBuddy' (type 'ByteBuddyTask').
  - In plugin 'net.bytebuddy.byte-buddy-gradle-plugin' type 'net.bytebuddy.build.gradle.ByteBuddyTask' property 'discoverySet' has @Input annotation used on property of type 'FileCollection'.
    
    Reason: A property of type 'FileCollection' annotated with @Input cannot determine how to interpret the file.
    
    Possible solutions:
      1. Annotate with @InputFile for regular files.
      2. Annotate with @InputDirectory for directories.
      3. If you want to track the path, return File.absolutePath as a String and keep @Input.
```

As far as I could tell, it refers to this bit of code, though I don't know enough about the project and/or Gradle's plugin architecture to comment on the possible solutions suggested by Gradle itself.

Are there any suggested workarounds?

**Comment by raphw** [comment]
Indeed, could you build BB from master and see if the annotation change fixed the issue?

**Comment by feliperuiz** [comment]
Reporting back after trying it out with `1.12.12-SNAPSHOT`, it worked! At least I didn't get the error message.
