### ISSUE TITLE
Fieldref and Methodref declaration

### ISSUE THREAD

**Issue by binis2** [raphw/byte-buddy#1273]
Hello, I'm evaluating ByteBuddy and trying to create a inner class of some other class. Works fine. But I don't seem to find a way or at least an example how to define Fieldref and Methodref in method table so I can give access to some of the parents fields and methods. Is this possible with ByteBuddy? And if it is, please give me an example.

**Comment by raphw** [comment]
well, it's possible via accessor methods or nestmates. but this would require you to alter the host class, something that's not possible using redefinition.

note that inner classes are just synthetic sugar. You need to implement them as if they were s seperate class.

**Comment by binis2** [comment]
Thanks for the response. I'm kinda lost thou. Any fast example that I can look into?

Also browsing thru the code it seems like calling ClassWriter.newField with the right arguments is just what I need. Is there any convenient way to call this method during the make or load phase?

**Comment by raphw** [comment]
With the Byte Buddy DSL you should simply call defineField. What did you try?

**Comment by binis2** [comment]
`
public class Test {

    private static final Map<String, Object> CNST;

    static {
        CNST = new HashMap<>();

        CNST.put("asd", new Nested() {
            @Override
            Object get() {
                return null;
            }
        });
    }

    private static abstract class Nested {

        Nested() { //One of the obstacles I face is that if there is no explicitly defined constructor the default one is private.
            super();
        }

        abstract Object get();

    }

    //This is the class I'm trying to generate
    public static class Access extends Nested {

        Map getMap() {
            return CNST;
        }

        Object get() {
            return null;
        }
    }

}
`

Well this is the case I have.    A private nested class inside a class. So I want to create another nested class that sublclasses Nested and replace the instance inside the map. So while playing with it and trying to figure out if I can pull something like that I noticed that inside the symbol table of the Access class there is this reference to the host's field explicitly defined. 

`
   #7 = Fieldref           #8.#9          // net/binis/example/service/Test.CNST:Ljava/util/Map;    
   #8 = Class              #10            // net/binis/example/service/Test    
   #9 = NameAndType        #11:#12        // CNST:Ljava/util/Map;    
`

So I was wondering if I can define it should I be able to actually access the field. I tried to use .defineField() routine but it didn't find a way to be able to specify an owner of field that is not the object I'm creating. This why I think that ClassWriter.newField() method will let me do just that.

Here is my the code I came up with

`
    public interface GimmeAccess {
        Map getActionMap();
    }

    private static void init() {
        var cls = Arrays.stream(Test.class.getDeclaredClasses()).filter(c -> c.getName().endsWith("Nested")).findFirst();
        if (cls.isPresent()) {
            var objectName = "net.binis.example.service.Test$Access";
            var objectDesc = "net/binis/example/service/Test$Access";
            var c = new ByteBuddy()
                    .subclass(cls.get())
                    .modifiers(Opcodes.ACC_PUBLIC)
                    .name(objectName)
                    .innerTypeOf(Test.class)
                    .implement(GimmeAccess.class)
                    .defineField("parent", cls.get())
                    .defineConstructor(Opcodes.ACC_PUBLIC).withParameter(cls.get()).intercept(new CodeImplementation() {
                        @Override
                        public ByteCodeAppender.Size code(MethodVisitor methodVisitor, Implementation.Context implementationContext, MethodDescription instrumentedMethod) {
                            methodVisitor.visitVarInsn(Opcodes.ALOAD, 0);
                            //methodVisitor.visitInsn(Opcodes.ACONST_NULL);
                            methodVisitor.visitMethodInsn(Opcodes.INVOKESPECIAL, "net/binis/example/service/Test$Nested", "<init>", "()V", false);
                            methodVisitor.visitVarInsn(Opcodes.ALOAD, 0);
                            methodVisitor.visitVarInsn(Opcodes.ALOAD, 1);
                            methodVisitor.visitFieldInsn(Opcodes.PUTFIELD, objectDesc, "parent", "Lnet/binis/example/service/Test$Nested;");
                            methodVisitor.visitInsn(Opcodes.RETURN);
                            return new ByteCodeAppender.Size(2, 2);
                        }
                    })
                    .defineMethod("getActionMap", Map.class, Opcodes.ACC_PUBLIC).intercept(new CodeImplementation() {
                        @Override
                        public ByteCodeAppender.Size code(MethodVisitor methodVisitor, Implementation.Context implementationContext, MethodDescription instrumentedMethod) {
                            methodVisitor.visitFieldInsn(Opcodes.GETSTATIC, "net/binis/example/service/Test", "CNST", "Ljava/util/Map;");
                            methodVisitor.visitInsn(Opcodes.ARETURN);
                            return new ByteCodeAppender.Size(1, 1);
                        }
                    });

            var l = c.make().load(cls.get().getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                    .getLoaded();

            var instance = (GimmeAccess) l.getDeclaredConstructors()[0].newInstance(new Object[]{null});

            var map = instance.getActionMap();
        }

`

**Comment by raphw** [comment]
Unfortunately, what you try is not possible. If you define an inner class, javac adds accessor methods or nest mates to that hosting class. Only these attributes allow access to the targeted class, it cannot be patched into a class once it was loaded.

Without this class, you would need to define a class the same way that you would define a new class in the same package in Java, with the same restrictions that apply there.
