### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by shixiaoxianga** [raphw/byte-buddy#1275]
java.lang.IllegalStateException: Could not locate class file for com.xxx.xxx.xxx.http.HttpURLConnectionMethodInterceptor

Error reported in this line,
`
 .intercept(Advice.to(new AntWorkingClassLoad().loadClass(classEnhance.interceptorClass())));
`

**Comment by raphw** [comment]
I assume your `AntWorkingClassLoad` does not correctly resolve resources. Byte Buddy needs the byte code to process the inlining. Look into overriding `getResourceAsInputStream` to return the class file from there.

**Comment by shixiaoxianga** [comment]
> I assume your `AntWorkingClassLoad` does not correctly resolve resources. Byte Buddy needs the byte code to process the inlining. Look into overriding `getResourceAsInputStream` to return the class file from there.

InputStream Convert to class？

**Comment by shixiaoxianga** [comment]
> java.lang.IllegalStateException: Could not locate class file for com.xxx.xxx.xxx.http.HttpURLConnectionMethodInterceptor
> 
> Error reported in this line, `.intercept(Advice.to(new AntWorkingClassLoad().loadClass(classEnhance.interceptorClass())));`

This exception was thrown by bytebuddy.

Antworkingclassload can load classes normally

**Comment by shixiaoxianga** [comment]
The problem is solved. Thank the author

**Comment by shixiaoxianga** [comment]
Now there is a problem. The proxy application calls the intercepted method and reports an error java lang.NoClassDefFoundError: com/xxx/xxx/xxx/xxx/HttpURLConnectionMethodInterceptor

**Comment by raphw** [comment]
Do you reference the class in your advice? Note that the code in it is copy pasted to the target. It's not given that the class even sees your advice class.

**Comment by shixiaoxianga** [comment]
> Do you reference the class in your advice? Note that the code in it is copy pasted to the target. It's not given that the class even sees your advice class.

The previous problem was solved. The interception class was successfully loaded in the getresourceasstream method. Now, there is a problem that using the intercepted method in the enhanced application will report an error, saying that the interceptor cannot be found

`java.lang.NoClassDefFoundError: com/antworking/plugin/jdk/http/HttpURLConnectionMethodInterceptor`

This class refers to the external jar package and is loaded by using the custom class loader, that is,` Antworkingclassloader`

```

public class HttpURLConnectionMethodInterceptor {
  private static final Logger log = LoggerFactory.getLogger(HttpURLConnectionMethodInterceptor.class);

  @Advice.OnMethodEnter
  public static void enter() throws Throwable {
    log.info("test http");
  }

  @Advice.OnMethodExit
  public static void exit() throws Throwable {

  }
}

```

Now the Agentlistener does not report an error when the program starts. When intercepting the method, it will throw an exception and cannot find the class

**Comment by shixiaoxianga** [comment]
Caused by: java.lang.NoClassDefFoundError: com/antworking/core/interceptor/HttpURLConnectionMethodInterceptor
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java)
