### ISSUE TITLE
intercept jdk

### ISSUE THREAD

**Issue by shixiaoxianga** [raphw/byte-buddy#1277]
Hello, author, I want to intercept classes in JDK. First, I need to inject the interceptor into the boot class loader. What can I do next? Can you give me some suggestions or provide some ideas.Thank you very much.It's best to have examples

**Comment by shixiaoxianga** [comment]
Can classes in JDK intercept construction methods？

**Comment by raphw** [comment]
Yes, you can intercept constructors just as methods with minor limitations. By default, Byte Buddy ignores all JDK types. You need to define a custom *ignore* matcher on your agent builder. Note that this will impact performance and you should try to exclude as many JDK packages as possible.

**Comment by shixiaoxianga** [comment]
@raphw Should the classes referenced by the interceptor also be injected into the boot class loader?
