### ISSUE TITLE
does any other way to use my agent without use javaagent command?

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#128]
i now use byte buddy is

first: in myagent project pom.xml dependency byte buddy's jar

second: in myagent's premain method add some my code to interceptor some method
``
new AgentBuilder.Default().type(..).transform(..).installOn(instrumentation);
`` 
third: other projects run jar with  java -javaagent:/path/to/myagent.jar -jar xxx.jar

other projects does any other way to use myagent.jar without -javaagent=/path/to/myagent.jar command?

**Comment by raphw** [comment]
Yes and no. It is possible if you run on a JDK but not a regular JVM. You can have a look at the byte-buddy-agent project that offers APIs for attaching onto the current VM or a remote VM by process id.
