### ISSUE TITLE
Can byte-buddy use in java application chaos engineering

### ISSUE THREAD

**Issue by sigezhao** [raphw/byte-buddy#1280]
I'm learning chaos enginneering, and want to inject delay/exception/timeout failure to java application in runtime without edit source code or restart the application, Can byte-buddy do this

**Comment by raphw** [comment]
You can write a Java agent with its AgentBuilder API that does all that, yes.

**Comment by sigezhao** [comment]
will it conflict with other java agent, such as skywalking, jvm-sandbox; or conflict with java agent use byte-buddy

**Comment by raphw** [comment]
No, Byte Buddy retains (by default) other class file changes.

**Comment by raphw** [comment]
Yes, of course. (2) is not really Byte Buddy specific, but you can research Java agents in general for this. As for the rest, think of a Byte Buddy agent of copy-pasting code anywhere in your application. Cheers, Rafael
