### ISSUE TITLE
Show thrown exceptions in Advice.Origin

### ISSUE THREAD

**Issue by aoli-al** [raphw/byte-buddy#1281]
I'm trying to monitor all methods that may throw exceptions using Advice and I want to get the type of exceptions thrown by the method. E.g.

```
public void foo() thrown DataFormatException;
```

Is there a good way to extract that information? Otherwise, I'm happy to submit a patch in Advice.Origin.

**Comment by raphw** [comment]
You'd want to extract that information during matching, I think? It's available from the method description.

**Comment by aoli-al** [comment]
When I use Advice to instrument methods, I would like to collect the method name and type of thrown exceptions of each method. The Advice.Origin does not contain the type of thrown exceptions of the method. I managed to get this information through reflection. 

Could you please explain more about how I can get this information from the method description?

**Comment by raphw** [comment]
You can inject a Method type via origin and get the exception types from there. If you have particular needs, you can also bind a custom annotation and express the needed information in any suitable way.

**Comment by aoli-al** [comment]
Ah, I see, thanks for clarifying. It works.
