### ISSUE TITLE
How to write a method ElementMatcher only include declared method ？

### ISSUE THREAD

**Issue by BlackBAKA** [raphw/byte-buddy#1282]
For example，there are two class：
`
public class Father {
    public void hi () {}
}

public class Son extends Father {
    public void bye () {}
}

`

How to build a ElementMatcher<MethodDescription> only include Son#bye(), thanks for your help.

**Comment by raphw** [comment]
You'd need a matcher for the type (assuming you are using an agent builder) and then match the method. If you know the names, you can match both by name.
