### ISSUE TITLE
MultipleParentClassLoader does not work if used as parent

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#129]
The reason for that is that in
https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/MultipleParentClassLoader.java#L51
only loadClass(name) is implemented. If the MPCL is used as parent of an other classloader is used, it will only ever get loadClass(name, resolve) invoked.
As @raphw suggested via e-mail maybe it should even implement findClass instead.

**Comment by raphw** [comment]
Fixed on master.

**Comment by CodingFabian** [comment]
you mean by master? Thanks!
