### ISSUE TITLE
custom native method strategy and class pre match.

### ISSUE THREAD

**Issue by jaaaar** [raphw/byte-buddy#1291]
1. Currently only the native method strategy can be set via enable and disable. Is it better to provide a with(NativeMethodStrategy) method?
2. is it possible to privide a matcher before the typeDescription created to avoid read the classfile.(It seems now that both descriptionStrategy and ignoreMatcher are required to achieve this)

**Comment by raphw** [comment]
As for (1), what would this custom strategy do? You can only use a given prefix.

As for (2), by default, descriptions are resolved lazily. Only if you need a complex property, a class file will be looked up.

**Comment by jaaaar** [comment]
thanks for the reply.

For (1), the **disable strategy** uses the `RandomString` and the `RandomString` uses `java.util.Random`(I have enhanced by bytebuddy) internally. This causes `java.util.Random` to perform a lot of enhancement logic during instrumentation.
So I would like to be able to customize the strategy so that I can add blocking logic inside the strategy to make sure that the augmentation logic doesn't execute. the **enable strategy** , It looks like it might throw an exception, I don't dare to use it.

For (2), When I use **xjar** to encrypt the jar package, byte-buddy will process some intermediate encrypted bytecode files at runtime, and a lot of exceptions appear in ClassReader (I used `ElementMatchers#isSynthetic` in ignoreMatcher), these classes I have Knowing will never enhance it, so hopefully I can skip reading these bytecodefiles, currently I find it is more elegant to use `descriptionStartegy` and `ignoreMatcher` to get it, I will try this.

**Comment by raphw** [comment]
`Random` is required multiple cases in Byte Buddy. Why are you enhancing it? Worst case, you would need to add a thread local or something that disables your instrumentation intermediately.

**Comment by jaaaar** [comment]
In my current project, `Random` is defined as unsafe. When it is called, I need to report to the server that an unsafe random number call has occurred. Now I do disable the logic through thread local, but after byte-buddy uses `Instrumentation.addTransformer` to add the `ExecutingTransform`, the subsequent class loading behavior will still be handled by `NativeMethodStrategy` and the Thread local value cannot be easily set at this time. In this case, if there is no custom strategy, maybe I can only do it by instrumenting `sun.instrument.TransformerManager` or `java.lang.ClassLoader`?

**Comment by raphw** [comment]
You can register a class file transformer decorator. it will allow you to set the thread local before and after any instrumentation.

Does the VM not call random values itself?

**Comment by jaaaar** [comment]
Cool! The `TransformerDecorator` is exactly what i need.
