### ISSUE TITLE
how to navigate to the generated class

### ISSUE THREAD

**Issue by rainman-code** [raphw/byte-buddy#1292]
how to navigate to the generated class？ think

**Comment by raphw** [comment]
Could you elaborate on this question?

**Comment by rainman-code** [comment]
![image](https://user-images.githubusercontent.com/53501828/182012664-1dfd03d9-f65d-498c-9dc1-a9ac93af21e2.png)
click【导航】，no effect；maybe， how to find the generated class，thank

**Comment by raphw** [comment]
From an interceptor? You can use the `@Origin` annotation for a `Class` type.

**Comment by rainman-code** [comment]
I just want find the generated auxiliary class，and have a look at it

**Comment by raphw** [comment]
If you want to inspect the class file, it will be part of the created DynamicType.
