### ISSUE TITLE
Templating with the byte-buddy-maven-plugin

### ISSUE THREAD

**Issue by Mom0aut** [raphw/byte-buddy#1294]
Hello,

i would like to generate Classes during a maven build with the given plugin. 
How can i tell the build plugin, which class should be generated?

Is there any Templating for such generation(Members, Fields, etc...)?

Maybe i use the plugin not correct, is there any example on how u should use the plugin ( i found the readme in the sub-folder).

Ty Mom0

**Comment by raphw** [comment]
You want to create a fully new class? You can use `ByteBuddy` instances for this. Simply create a plugin and add them to the target location. With the latest release, look at `Plugin.WithInitialization` for this.

**Comment by Mom0aut** [comment]
Thank you i will look into it.
