### ISSUE TITLE
v1.12.13 has an API breaking change

### ISSUE THREAD

**Issue by pjfanning** [raphw/byte-buddy#1297]
Thanks for doing the release. This is not a big deal - I just thought I'd log this for information purposes.

An example build failure: https://github.com/apache/poi/runs/7632410373?check_suite_focus=true

This compile failure happened after upgrading from v1.12.12 to v1.12.13.

AgentBuilder.Transformer.transform now requires a 5th parameter - a ProtectionDomain.

Generally semantic versioning requires that APIs maintain backward compatibility in minor releases.

There doesn't appear to be a mention of the breaking change in the release notes for the release.

**Comment by raphw** [comment]
Yeah, that was a mix of an oversight and a backthought that agents need to shield Byte Buddy from a potential class-path version. I normally want to avoid these and I configured a binary compatibility check now to fail the build in the future if I broke it again.
