### ISSUE TITLE
Add Ability to Generate Java Bean from an Interface

### ISSUE THREAD

**Issue by saden1** [raphw/byte-buddy#13]
Given the following interface I would like to be able to generate a bean with minimal effort using ByeBuddy. Ideally, I would like to simply give ByteBuddy an interface with getter and setter pairs and have it take care of doing the analysis on the interface and create a dynamic java bean.

```java
public interface UserConfig {

    String getName();

    void setName(String name);

    int getAge();

    void setAge(int age);

}
```

**Comment by raphw** [comment]
I decided against an explicit API. From my experience with cglib, this can be better solved by an external library which is specialized in handling exceptions. However, I decided to add some convenience methods to make adding methods from reflection results more easy. I hope you can live with this compromise.

Thank you again for using Byte Buddy and your feedback!

**Comment by Flamenco** [comment]
Thanks for the example above,  @raphw.  You might want to rename toLowerClase to toLowerCase though.
