### ISSUE TITLE
how to catch thread Exception?

### ISSUE THREAD

**Issue by Oldjie** [raphw/byte-buddy#1306]
Hi，author
   i want use byte-buddy for  catch code Exception,but my code  use new Thread ,byte-buddy cannot catch new Thread
“Cooker" Obejct:
```
public class Cooker {
    public void hello() {
        System.out.println("+ method name : public void hello();");
        new Thread(new Task()) .start();
    }
}
```
Task Object:
```
public class Task implements Runnable{
    @Override
    public void run() {
        System.out.println("jay");
        int a = 1/0;
    }
}
```
Advice Object:
```
public class AdviceLogic {
    @Advice.OnMethodExit(onThrowable = Throwable.class)
    public static void exit(@Advice.Thrown Throwable thrown) {
        if (thrown != null){
            System.out.println("- - - - -exception - - - - - -");
            System.out.println("exit！"+ thrown.getClass().getName());
        }
    }
}
```
TestAdvice Object:
```
public class TestAdvice {
    public static TestAdvice INSTANCE = new TestAdvice();

    ClassLoader classLoader;

    public void initClassLoader() {
        classLoader = new ByteArrayClassLoader.ChildFirst(getClass().getClassLoader(),
                ClassFileLocator.ForClassLoader.readToNames(Cooker.class),
                ByteArrayClassLoader.PersistenceHandler.MANIFEST);
    }
    public void modifyTarget() throws Exception {
        ByteBuddyAgent.install();
        new AgentBuilder.Default()
                .with(AgentBuilder.PoolStrategy.Default.EXTENDED)
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
                .type(ElementMatchers.is(Cooker.class), ElementMatchers.is(classLoader)).transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        return builder.visit(Advice.to(AdviceLogic.class).on(ElementMatchers.not(ElementMatchers.isConstructor()).and(ElementMatchers.any())));
                    }
                })
                .installOnByteBuddyAgent();
    }
    public void print() throws Exception {

        Class<Cooker> cookerType = (Class<Cooker>) classLoader.loadClass(Cooker.class.getName());
        Object Cooker = cookerType.getDeclaredConstructor().newInstance();
        cookerType.getDeclaredMethod("hello").invoke(Cooker);


    }
    public static void main(String[] args) throws Exception {
        INSTANCE.initClassLoader();
        INSTANCE.modifyTarget();
        INSTANCE.print();
    }
}
```
i want to catch the exception in the task  ,but i cant

**Comment by raphw** [comment]
That's a JVM restriction, unfortunately. One cannot use *onThrowable* within a constructor.

**Comment by Restlol** [comment]
> That's a JVM restriction, unfortunately. One cannot use _onThrowable_ within a constructor.

Is there a way to catch the exception of the thread inside the method？

**Comment by raphw** [comment]
you could instrument the method that calls the constructor.

**Comment by Oldjie** [comment]
> you could instrument the method that calls the constructor.

sorry sir,I don't understand too much. Can you elaborate on it

**Comment by raphw** [comment]
If you need to catch an exception thrown from a constructor, with advice, you cannot instrument the constructor itself. But if the constructor is called from a method, for example a static factory, you can instrument this factory.

**Comment by Oldjie** [comment]
sorry i am a litter confused. if I don't know  that there are threads in the code, but I need to catch exceptions including thread stack exception
like this：
`public class Cooker {
    public void hello() {
        System.out.println("+ method name : public void hello();");
        //more Thread
//        Thread thread1 = new Thread(new Task());
//        Thread thread2 = new Thread(new Task());
//        Thread thread3 = new Thread(new Task());
//        Thread thread4 = new Thread(new Task());
       
    }
}
`
How should I do it?

**Comment by raphw** [comment]
You could instrument the Task.run method, for instance. If an exception was thrown, advice would capture it.

**Comment by Oldjie** [comment]
> You could instrument the Task.run method, for instance. If an exception was thrown, advice would capture it.
If the thread accepts a lambad, the lambad cannot be instrument？

**Comment by Oldjie** [comment]
> You could instrument the Task.run method, for instance. If an exception was thrown, advice would capture it.

If the thread accepts a lambad, the lambad cannot be instrument？

**Comment by raphw** [comment]
No, lambdas cannot normally be instrumented.

**Comment by Oldjie** [comment]
> No, lambdas cannot normally be instrumented.

I see, thank you sir
