### ISSUE TITLE
missing exported package from byte-buddy

### ISSUE THREAD

**Issue by bokken** [raphw/byte-buddy#131]
The net.bytebuddy.jar.asm.* packages are not exported in the manifest for byte-buddy 1.3.19.

**Comment by CodingFabian** [comment]
This might be from a time where there was no access to ASM exposed. Are you trying to us any specifc functionality, or is you bundler complaining?
As I assume @raphw has no intentions of wrapping the complete asm api, i think we should just add an export for the 3 asm packages

**Comment by CodingFabian** [comment]
The bundling uses explicitly a handcrafted list:
https://github.com/raphw/byte-buddy/blob/master/byte-buddy/pom.xml#L120

**Comment by bokken** [comment]
@CodingFabian, I am using net.bytebuddy.jar.asm.MethodVisitor as part of implementing a custom net.bytebuddy.implementation.bytecode.ByteCodeAppender implementation for a custom net.bytebuddy.implementation.Implementation implementation.

**Comment by raphw** [comment]
The export is missing on purpose. If you are using the ASM API directly, please shade Byte Buddy as I cannot guarantee API compatibility for a third party project. Please refere to the readme for information. Alternatively, if you only compose existing appenders, use the ByteCodeAppender.Simple implementation for composition.

**Comment by bokken** [comment]
I certainly understand your concern about the passivity of asm. 

This raises some questions for me about the intended use of ByteCodeAppender. It is an interface which defines only a single method which includes a MethodVisitor parameter. Is the intention that only the bytebuddy project provide implementations of ByteCodeAppender?

The [documentation](http://bytebuddy.net/#customization) does provide examples of providing custom implementations of this. Are you saying this should not actually be done?

**Comment by bokken** [comment]
Perhaps there is a easier/better way to accomplish what I am trying to do. I am wanting to define a class with 3 final member variables and a constructor which takes 3 parameters and populates the 3 variables.
In some cases, I need to call a super constructor with 1 of the parameters. 

The only way I found to do this was to write a custom implementation with this appender implementaiton:

```
        public ByteCodeAppender appender(final Target implementationTarget)
        {
            return new ByteCodeAppender()
            {                        
                @Override
                public ByteCodeAppender.Size apply(final MethodVisitor methodVisitor, final Context implementationContext, final MethodDescription instrumentedMethod)
                {
                    final FieldList<InDefinedShape> fields = implementationTarget.getInstrumentedType().getDeclaredFields();
                  
                    final List<StackManipulation> stack = new ArrayList<StackManipulation>(16);
                    stack.add(MethodVariableAccess.REFERENCE.loadOffset(0));
                    if (stringConstructor)
                    {
                        stack.add(MethodVariableAccess.REFERENCE.loadOffset(1));
                        stack.add(MethodInvocation.invoke(new TypeDescription.ForLoadedType(proxyClass)
                                                                             .getDeclaredMethods()
                                                                             .filter(ElementMatchers.isConstructor().and(ElementMatchers.takesArguments(String.class)))
                                                                             .getOnly()));
                    }
                    else
                    {
                  
                        stack.add(MethodInvocation.invoke(new TypeDescription.ForLoadedType(proxyClass.isInterface() ? Object.class : proxyClass)
                                                                             .getDeclaredMethods()
                                                                             .filter(ElementMatchers.isConstructor().and(ElementMatchers.takesArguments(0)))
                                                                             .getOnly()));
                    }
                  
                    stack.add(MethodVariableAccess.REFERENCE.loadOffset(0));
                    stack.add(MethodVariableAccess.REFERENCE.loadOffset(1));
                    stack.add(FieldAccess.forField(fields.filter(ElementMatchers.named(AUTHORITY_VAR_NAME)).getOnly()).putter());
                  
                    stack.add(MethodVariableAccess.REFERENCE.loadOffset(0));
                    stack.add(MethodVariableAccess.REFERENCE.loadOffset(2));
                    stack.add(FieldAccess.forField(fields.filter(ElementMatchers.named(INTERCEPTORS_VAR_NAME)).getOnly()).putter());
                  
                    stack.add(MethodVariableAccess.REFERENCE.loadOffset(0));
                    stack.add(MethodVariableAccess.REFERENCE.loadOffset(3));
                    stack.add(FieldAccess.forField(fields.filter(ElementMatchers.named(ACTUAL_VAR_NAME)).getOnly()).putter());
                  
                    stack.add(MethodReturn.VOID);
                  
                    final StackManipulation manipulation = new StackManipulation.Compound(stack);
                  
                    final StackManipulation.Size size = manipulation.apply(methodVisitor, implementationContext);
                  
                    return new ByteCodeAppender.Size(size.getMaximalSize(), instrumentedMethod.getStackSize());
                }
            };
        }
```

Is there a different approach I should be taking?

**Comment by CodingFabian** [comment]
@bokken No you can use this API, it is not restricted to byte buddy. But because this is not an API provided by bytebuddy, but by ASM, what you should do is to build your own bytebuddy distribution which repackages ASM. that way you have an asm which is under your control in your namespace. If you use it in OSGi (which I assume because you are asking about the export) you then need to export the package when building your distribution.

**Comment by bokken** [comment]
@CodingFabian, while that certainly /can/ be done, in my specific use, that provides no actual additional passivity safety. I simply need the class definition as an import. I call no methods on it. If something were to change about it, it would require changes to the ByteBuddy "public" api, which would be non-passive regardless of how I interact with asm.

**Comment by CodingFabian** [comment]
@bokken I can cite the documentation

> However, this imposes one possible problem when relying onto Byte Buddy as a project dependency and making use of the exposed ASM API. The authors of ASM **require** their users to repackage the ASM dependency into a different name space. This **is necessary** because one cannot anticipate changes in the Java class file format what can lead to API incompatibilities of future versions of ASM. Because of this, each version of Byte Buddy is distributed in two different packaging formats:
>A no-dependency version that repackages the ASM dependency from its org.objectweb.asm into Byte Buddy's own namespace net.bytebuddy.jar.asm. Doing so, the ASM dependency is also contained within Byte Buddy's jar file. By using this version, you do not need to worry about possible ASM version clashes which might be caused by the use of ASM by both Byte Buddy and other libraries. If you do not plan to use ASM, do not know what ASM is or what this is all about, this is the version you want to use. The artifact ID of this packaging format is byte-buddy.
A version with an explicit dependency on ASM in its original org.objectweb.asm namespace. This version must only be used for repackaging Byte Buddy and its ASM dependency into your own namespace. Never distribute your application while directly relying on this dependency. Otherwise, your users might experience version conflicts of different ASM versions on their class path. The artifact ID of this packaging format is byte-buddy-dep.
Normally, you would use the first, no-dependency version. However, if you are using Byte Buddy and **making use of the exposed ASM API**, **you must use the second version** of Byte Buddy and repackage it into your own name space as suggested. This is in particularly true when you plan to redistribute your code for the use by others. Future versions of Byte Buddy will update their ASM dependency to newer version what will then lead to version clashes between different ASM versions that were repackaged by Byte Buddy, if you have not follow this recommendation! In contrast, the Byte Buddy API itself will only apply version compatible changes.

It is pretty clear that it is nothing _optional_, that _can be done_. It is a requirement that must be done when using ASM. And you are not "only" using it as api. MethodVisitor is an abstract class carrying behaviour.

**Comment by bokken** [comment]
@CodingFabian, I found that paragraph/section this morning. The last sentence or 2 provides warnings of what happens if you do not follow the guidance.

I am simply trying to point out that in my specific use (which I included above), my code only references the MethodVisitor and takes it from byte buddy code (specifically, whatever it is which calls the ByteCodeAppender.apply method) and gives it to byte buddy code (specifically the StackManipulation.apply method). The code I am providing does not call any methods on the MethodVisitor. The only way I could be impacted by a change in asm is if the change were so dramatic as to cause byte buddy to change the method signatures of either of those 2 methods. If that were to occur, I would be impacted regardless if I shaded (can I use that as a verb?) asm or not, as this would be a non-passive change to the public byte buddy api.

Since I /cannot/ be impacted by any asm change which allows byte buddy to keep byte buddy's apis passive, I would prefer not to be required to shade byte buddy just be able to run in an osgi container.

**Comment by raphw** [comment]
I am currently on vacation but I will consider your use case once I am back!

**Comment by raphw** [comment]
This can be easily expressed without making any use of the ASM API by using an `ByteCodeAppender.Simple`:

```java
@Override
public ByteCodeAppender appender(final Target implementationTarget) {
  final FieldList<FieldDescription.InDefinedShape> fields = implementationTarget
         .getInstrumentedType()
         .getDeclaredFields();

  final List<StackManipulation> stack = new ArrayList<StackManipulation>(16);
  stack.add(MethodVariableAccess.REFERENCE.loadOffset(0));
  if (stringConstructor) {
    stack.add(MethodVariableAccess.REFERENCE.loadOffset(1));
    stack.add(MethodInvocation.invoke(new TypeDescription.ForLoadedType(proxyClass)
            .getDeclaredMethods()
            .filter(ElementMatchers.isConstructor().and(ElementMatchers.takesArguments(String.class)))
           .getOnly()));
  } else {
    stack.add(MethodInvocation.invoke(new TypeDescription.ForLoadedType(proxyClass.isInterface() 
        ? Object.class : proxyClass)
            .getDeclaredMethods()
            .filter(ElementMatchers.isConstructor().and(ElementMatchers.takesArguments(0)))
            .getOnly()));
}

stack.add(MethodVariableAccess.REFERENCE.loadOffset(0));
stack.add(MethodVariableAccess.REFERENCE.loadOffset(1));
stack.add(FieldAccess.forField(fields.filter(ElementMatchers.named(AUTHORITY_VAR_NAME)).getOnly()).putter());

stack.add(MethodVariableAccess.REFERENCE.loadOffset(0));
stack.add(MethodVariableAccess.REFERENCE.loadOffset(2));
stack.add(FieldAccess.forField(fields.filter(ElementMatchers.named(INTERCEPTORS_VAR_NAME)).getOnly()).putter());

stack.add(MethodVariableAccess.REFERENCE.loadOffset(0));
stack.add(MethodVariableAccess.REFERENCE.loadOffset(3));
stack.add(FieldAccess.forField(fields.filter(ElementMatchers.named(ACTUAL_VAR_NAME)).getOnly()).putter());

stack.add(MethodReturn.VOID);
return new ByteCodeAppender.Simple(stack);
    }
```

**Comment by bokken** [comment]
Yes, that works. It took me a bit to realize that you added the constructor to ByteCodeAppender.Simple which takes a List in 1.3.20.
