### ISSUE TITLE
SuperMethodCall for overriden methods with a covariant return type

### ISSUE THREAD

**Issue by homedirectory** [raphw/byte-buddy#1311]
I have been trying to create a subclass with ByteBuddy that overrides its parent method to modify the return type, making it narrower. According to [The Java Tutorials](https://docs.oracle.com/javase/tutorial/java/IandI/override.html):
> The overriding method has the same name, number and type of parameters, and return type as the method that it overrides. An overriding method **can also return a subtype of the type returned by the overridden method**. This subtype is called a *covariant return type*.

Consider the following example:

```java
class Person {
    private String name;
    public Person setName(String name) {
        this.name = name;
        return this;
    }
}
```

What I'd like to do is to generate a dynamic type that would be equal to the following:
```java
class Child extends Person {
    public Child setName(String name) {
        super.setName(name);
        return this;
    }
}
```

Here is my attempt:
```java
new ByteBuddy().subclass(Person.class)
    .name("Child")
    .defineMethod("setName", TargetType.DESCRIPTION, Visibility.PUBLIC)
    .withParameter(String.class, "name")
    .intercept(SuperMethodCall.INSTANCE.andThen(FixedValue.self()))
```

And here is what I get:
```
java.lang.IllegalStateException: Cannot call super (or default) method for public Child Child.setName(java.lang.String)
	at net.bytebuddy.implementation.SuperMethodCall$Appender.apply(SuperMethodCall.java:133)
	...
```

After tracing the exception I found the following:

`SubclassImplementationTarget.invokeSuper(...) -> SubclassImplementationTarget.invokeMethod(...)`

[`SubclassImplementationTarget.invokeMethod(SignatureToken)`](https://github.com/raphw/byte-buddy/blob/987318b66d8f900554e6ec2733ff8ee3d6b7ba6e/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/scaffold/subclass/SubclassImplementationTarget.java#L91) attemps to locate the super method for the given one (in my case `Child setName(String)`). The problem is that this process disregards *covariant return types* and simply test for equality of types using [`MethodGraph.Compiler.Default.Key.equals`](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/scaffold/MethodGraph.java#L959), where the last line of code compares `identifiers`.

In my example the implementaion of `Key` used was `MethodGraph.Compiler.Default.Key.Detached` where:
```java
private final Set<MethodDescription.TypeToken> identifiers;
```

Furthermore, [`MethodDescription.TypeToken.equals`](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/description/method/MethodDescription.java#L2178) does:
```java
return returnType.equals(typeToken.returnType) && parameterTypes.equals(typeToken.parameterTypes);
```

Consider an alternative implementation of [`MethodGraph.Compiler.Default.Key.Store.Graph.locate(SignatureToken)`](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/scaffold/MethodGraph.java#L1844) that checks whether the return type is a covariant one, rather than strictly equal:

```java
public Node locate(MethodDescription.SignatureToken token) {
    Node node = entries.keySet().stream()
        .filter(key -> key.getIdentifiers().stream()
            .anyMatch(tt -> tt.getParameterTypes().equals(token.getParameterTypes()) &&
                            // here test for covariance
                            tt.getReturnType().isAssignableFrom(token.getReturnType())))
        .findFirst().map(key -> entries.get(key)).orElse(null);
    return node == null
        ? Node.Unresolved.INSTANCE
        : node;
}
```

**Comment by raphw** [comment]
This is already the current behaviour. The default method graph compiler only considers the parameter types; there is another one that also considers the return type.

The reason that you cannot simply invoke the super method is the `return this` bit which is not specified. You can use the super method invocation, but you'd need to chain something using `andThen` to return the instance itself. It's a rather easy `Implementation` to write, but I think Byte Buddy should offer one, so I included `SelfReturn` on master. You can copy it until there is a new release.

**Comment by homedirectory** [comment]
Strange... I'm stepping through the code with a debugger and there is no call to the method graph that only considers parameter types. And by the way, why consider only the parameter types when trying to determine a super method? The return typer also matters.

Regarding `SelfReturn`, in my example i am chaining the implementation with `FixedValue.self()`, which to me looks exactly like `SelfReturn`. What am I missing?

**Comment by homedirectory** [comment]
Okay, I just experimented a bit with Java bytecode and it turns out that you can have a method call its super method despite having an incompatible return type. The compiler, of course, wouldn't permit that. Is this the correct explanation for:
> The default method graph compiler only considers the parameter types;

**Comment by raphw** [comment]
You are of course right about self-invocation, I both forgot about it and overlooked it in your code. Wouln't this work, though:

        new ByteBuddy().subclass(Person.class)
                .name("Child")
                .defineMethod("setName", TargetType.DESCRIPTION, Visibility.PUBLIC)
                .withParameter(String.class, "name")
                .intercept(MethodCall.invoke(Person.class.getMethod("setName", String.class)).onSuper().withAllArguments().andThen(FixedValue.self()))
                .make();

**Comment by homedirectory** [comment]
Hm, I haven't seen this particular implementation until now. Thanks for your reply, I will look into it later and let you know whether it worked.

**Comment by homedirectory** [comment]
I integrated this implementation with my code and it does exactly what I need. Thanks again, @raphw.
