### ISSUE TITLE
Some classes may not be processed by ClassFileTransformer when obtaining parent class and interface information

### ISSUE THREAD

**Issue by dogourd** [raphw/byte-buddy#1312]
When `TypeDescription#getSuperClass` and `TypeDescription#getInterfaces` are called recursively in a **TypeMatcher** implementation, Some classes may not be processed by ClassFileTransformer even using `RedinitionStrategy.RETRANSFORMATION`.
It is certain that these classes are already present in `Instrumentation#getAllLoadedClasses`,
The missing class in my case is `com.mysql.cj.jdbc.StatementImpl`. 
1. Sometimes it is also handled correctly, but with a lower probability.  
2. If I manually make it slower, like adding a conditional breakpoint in **TypeMatcher**, the probability of success becomes higher.   
3. If I manually call retransformClasses(StatementImpl.class) again, it will be processed by ClassFileTransformer.  

I don't know why this is happening, isn't this a correct usage?

**Comment by raphw** [comment]
Are you using reiteration in your discovery strategy? It is true that classes being loaded for the first time might be missed out upon, if this loading happens during any activity of the agent. This is to protect against using the agent on itself which will lead to a class circularity error.

**Comment by dogourd** [comment]
> 

No, the discovery strategy is **SinglePass**. I've tried adding some breakpoints.
1. `ForRetransformation#doApply`
```java
protected void doApply(Instrumentation instrumentation,
                                       List<Class<?>> types) throws UnmodifiableClassException {
                    if (!types.isEmpty()) {
                        circularityLock.release();
                        try {
                            DISPATCHER.retransformClasses(instrumentation, types.toArray(new Class<?>[0])); // add breakpoint here
                        } finally {
                            circularityLock.acquire();
                        }
                    }
                }
```
2. `ExecutingTransformer#transform`
```java
public byte[] transform(ClassLoader classLoader,
                                    String internalTypeName,
                                    Class<?> classBeingRedefined,
                                    ProtectionDomain protectionDomain,
                                    byte[] binaryRepresentation) {
                if (circularityLock.acquire()) { // add breakpoint here
                    try {
                        return doPrivileged(new LegacyVmDispatcher(classLoader,
                                internalTypeName,
                                classBeingRedefined,
                                protectionDomain,
                                binaryRepresentation), accessControlContext);
                    } catch (Throwable ignored) {
                        return NO_TRANSFORMATION;
                    } finally {
                        circularityLock.release();
                    }
                } else {
                    return NO_TRANSFORMATION;
                }
            }
```

For (1),`com.mysql.cj.jdbc.StatementImpl` is not included in `types` every pass
For (2), neither internalTypeName is `com/mysql/cj/jdbc/StatementImpl`

Not only the ExecutingTransformer in bytebuddy, as long as I call the getSuperClass and getInterfaces in typeMatcher(`AgentBuilder#type(RawMatcher)`), other transformers will not process `com.mysql.cj.jdbc.StatementImpl` eighter, 
I added a ClassFileTransform just to record the passed classes, the class `com.mysql.cj.jdbc.StatementImpl` is not printed.
If I don't call getSuperClass and getInterfaces in typeMatcher, the target class can always be printed.

I'd be happy to provide a demo if needed

**Comment by raphw** [comment]
Have you tried if reiterating solves it?

**Comment by dogourd** [comment]
> Have you tried if reiterating solves it?

Yes, it does work. I will do a few more verifications tomorrow.
BTW, I didn't find a convenient API when I replaced the discovery strategy, I ended up using reflection to do the replacement. Like this:
```java
AgentBuilder builder = new Default().with(RedefinitionStrategy.RETRANSFORMATION);
Field f = builder.getClass().getDeclaredField("redefinitionDiscoveryStrategy");
// set accessible and remove the final modifier.
// set the field value.
builder.installOn(instrumentation);
```
Am I missing some shortcuts for modification provided by byte-buddy？What should be the recommended approach when it is necessary to modify the discovery strategy?

**Comment by raphw** [comment]
If you set the redefinition strategy, you'll get a nore refined build step where you can set it.

**Comment by dogourd** [comment]
thank you very much
