### ISSUE TITLE
Is it possible to get previous method name in instrumented code?

### ISSUE THREAD

**Issue by hi120ki** [raphw/byte-buddy#1314]
Hi, thank you for the maintenance of this project. This project is so helpful for me.

I'm trying to instrumented code by `MethodDelegation.to` like this

```java
public class Agent {

  public static void premain(String agentArgs, Instrumentation inst) {
    new AgentBuilder.Default()
        .type(
            ElementMatchers.named(
                "org.springframework.web.servlet.DispatcherServlet"))
        .transform((builder, type, classLoader, module) -> builder
            .method(ElementMatchers.named("doDispatch"))
            .intercept(MethodDelegation.to(InstrumentInterceptor.class)))
        .installOn(inst);
  }
}
```

And I'd like to get previous method name (name of the method that called intercept method) in instrumented code, then chenge action by previous method name.

I have searched [annotation packages](https://github.com/raphw/byte-buddy/tree/master/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/bind/annotation), but there is no such annotation.

I'd like to do like this code

```java
public class InstrumentInterceptor {

  @RuntimeType
  public static Object intercept(
      @PreviousMethodName String peviousMethodName,
      @SuperCall Callable<?> callable) {
    System.out.println(request.getMethod());
    try {
      if (peviousMethodName.equals("<method name like org.springframework.web.servlet.DispatcherServlet>")) {
        <some action>
      }
      return callable.call();
    } catch (Exception e) {
      return null;
    }
  }
}
```

Could you tell me is it possible to get previous method name in instrumented code?

Thank you.

**Comment by raphw** [comment]
Have you looked into @Origin? It should do what you are looking for.

**Comment by hi120ki** [comment]
Thank you!

I successfully get previous method name by `@Origin` annotation.

I appreciate your great comment!

**Comment by hi120ki** [comment]
@raphw sorry about reopening this issue.
`@Origin` annotation shows the method name that is intercepted and implemented by javaagent.
But I want to get the method name that calls the method that `@Origin` annotation shows.

In some cases, method `A` calls method `C`, and method `B` also calls method `C`. 
Then I'd like to detect which method `A` or `B` calls method `C` by intercepted and implemented codes.

I inject code by byte-buddy in method `C` (`@Origin` annotation shows method name `C`), and I'd like to get which mathod `A` or `B` calls method `C`.

Could you tell me is there annotation like this or someway to get previous method name?
Thank you.

**Comment by raphw** [comment]
This cannot be done in byte code, the caller hierarchy is not transported via methods. You can however use `StackWalker` which was introduced in Java 9. Before, browsing exception stack traces is the only solution.
