### ISSUE TITLE
How to add okhttp custom interceptor at runtime using bytebuddy?

### ISSUE THREAD

**Issue by gouravkrosx** [raphw/byte-buddy#1316]
I want to add my interceptor at runtime in okhttpclient, I am making Agent using bytebuddy in premain class. And i am trying to intercept the constructor of **"okhttp3.OkHttpClient.Builder"** to add my interceptor in the interceptors list. But the problem is that the type() method is unable to find my class, I've tried different ways for eg: ElementMatchers .is(), .nameStartsWith(), .nameContains(), named() etc. but couldn't find the class.

I know that okhttp uses Kotlin & java adds $ in the namespace to invoke some methods, so for my case i changed it to **"okhttp3.OkHttpClient$Builder"**, but again it was not finding the matching class.

I also want to know my approach that am i doing the right way to add the custom interceptor.

Agent:

```java
public static void premain(String arg, Instrumentation instrumentation) {

    new AgentBuilder.Default()           
          .type(ElementMatchers.named("okhttp3.OkHttpClient.Builder"))
          .transform((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
                    System.out.println("Transformer: adding custom okhttpinterceptor using agent: " + typeDescription.getName());
                    return builder.constructor(ElementMatchers.takesArgument(1, OkHttpClient.class))
                            .intercept(MethodDelegation.to(ConstructorInterceptor.class));
                })
          .installOn(instrumentation);
    }
```

Constructor Interceptor:

```java
public class ConstructorInterceptor {

         public static void doProceed(
            @SuperCall
            Callable<?> client,
            @Argument(0)
            OkHttpClient okHttpClient, @Origin String method) throws Exception {

        System.out.println("Constructor Interceptor was called for: " + method);
        client.call();
        okHttpClient.interceptors().add(new HttpInterceptor());
    }
}
```

HttpInterceptor:

```java
public class HttpInterceptor implements Interceptor{

      @NotNull
      @Override
      public Response intercept(@NotNull Interceptor.Chain chain) throws IOException {
        Request request = chain.request();

        String reqBody = getRequestBody(request);

        System.out.println("Inside HttpInterceptor before next()");

        Response response = chain.proceed(request);

        System.out.println("Inside HttpInterceptor after next()");

        return response;
    }
 }
```

**Comment by raphw** [comment]
As posted on StackOverflow: "okhttp3.OkHttpClient$Builder" is the correct binary name. You can also check this by calling getName on the class.

**Comment by gouravkrosx** [comment]
Sure, i will try with listener also (as you said on stackoverflow) and get back to you.

**Comment by gouravkrosx** [comment]
I tried with listener also but i found "okhttp3.OkHttpClient$Builder" nowhere.
I've added logs inside my [repo](https://github.com/gouravkrosx/OkHttpInterceptor_ByteBuddy/tree/master) as withListernerLogs.txt. Please have a look. 
Thanks!!!

**Comment by raphw** [comment]
It looks like that you are loading the class before the agent is registered. This won't work as the class is already present. Avoid any references to okhttp in your agent code, or, if using Advice, use a `Transformer.ForAdvice` where Byte Buddy will avoid class loading for you.

**Comment by gouravkrosx** [comment]
Again it's not working, i've made changes in the same [repo](https://github.com/gouravkrosx/OkHttpInterceptor_ByteBuddy/tree/master) as you suggested, add an advice class and also used  `Transformer.ForAdvice`.

**Comment by raphw** [comment]
Make sure that you do not import the client anywhere as it will load it: https://github.com/gouravkrosx/OkHttpInterceptor_ByteBuddy/blob/master/OkHttpInterceptor_ByteBuddy/Agent/src/main/java/org/example/agent/OkHttpAgent.java#L58

**Comment by gouravkrosx** [comment]
Sorry to reply this late, i was stuck somewhere.
So, as far as the above problem is concerned after removing every reference i was able to get the **okhttp3.OkHttpClient$Builder** but again i was unable to add my custom interceptor. you can see my changes on the same [repo](https://github.com/gouravkrosx/OkHttpInterceptor_ByteBuddy/tree/master). 

You can take **_logs.txt_** files as reference 

I've also tried `new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED));` from [this](https://github.com/raphw/byte-buddy/issues/764) issue.

**Comment by raphw** [comment]
So you do now see `okhttp3.OkHttpClient$Builder` in the logs, but it is not instrumented? Are you saying that is still ignored by Byte Buddy or that it is instrumented but your interceptor is not triggered?

**Comment by gouravkrosx** [comment]
Yes, I can see `okhttp3.OkHttpClient$Builder` in the logs. I've added a print statement in the transformer. So as i understood that as soon as bytebuddy finds the desired class using `type` parameter, and when same class is triggered from anywhere, it first enters the transformer class and get transformed with the help of  `builder...`.

Now in my case, flow reaches to the transformer but doesn't go to any **advice** or **interceptor**. 

And with the help of listener, I found this:


`
[Byte Buddy] ERROR okhttp3.OkHttpClient$Builder [jdk.internal.loader.ClassLoaders$AppClassLoader@7ad041f3, unnamed module @51521cc1, Thread[main,5,main], loaded=false]
`


`
java.lang.IllegalStateException: Illegal method name class okhttp3.OkHttpClient$Builder for public final okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.-addInterceptor(kotlin.jvm.functions.Function1)
`

To avoid this i've also used `new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED))`, but then error doesn't come and flow doesn't go to the interceptor.

To give you more clarity about what I am exactly trying to do is below:

In the main function i am making a  okhttp client and firing a request. Since i want to record the request and response and add some custom logic that's why i am using the interceptor. But for this custom logic i don't want to add the interceptor directly rather i want to add it at runtime.

`OkHttpClient client = new OkHttpClient.Builder().addInterceptor(new MyOkInterceptor()).build();
`
So, for this i am intercepting secondary constructor of the `okhttp3.OkHttpClient$Builder` which has `OkHttpClient` as argument.

```kotlin
internal constructor(okHttpClient: OkHttpClient) : this() {
      this.dispatcher = okHttpClient.dispatcher
      this.connectionPool = okHttpClient.connectionPool
      this.interceptors += okHttpClient.interceptors
      this.networkInterceptors += okHttpClient.networkInterceptors
      this.eventListenerFactory = okHttpClient.eventListenerFactory
      this.retryOnConnectionFailure = okHttpClient.retryOnConnectionFailure
      this.authenticator = okHttpClient.authenticator
      this.followRedirects = okHttpClient.followRedirects
      this.followSslRedirects = okHttpClient.followSslRedirects
      this.cookieJar = okHttpClient.cookieJar
      this.cache = okHttpClient.cache
      this.dns = okHttpClient.dns
      this.proxy = okHttpClient.proxy
      this.proxySelector = okHttpClient.proxySelector
      this.proxyAuthenticator = okHttpClient.proxyAuthenticator
      this.socketFactory = okHttpClient.socketFactory
      this.sslSocketFactoryOrNull = okHttpClient.sslSocketFactoryOrNull
      this.x509TrustManagerOrNull = okHttpClient.x509TrustManager
      this.connectionSpecs = okHttpClient.connectionSpecs
      this.protocols = okHttpClient.protocols
      this.hostnameVerifier = okHttpClient.hostnameVerifier
      this.certificatePinner = okHttpClient.certificatePinner
      this.certificateChainCleaner = okHttpClient.certificateChainCleaner
      this.callTimeout = okHttpClient.callTimeoutMillis
      this.connectTimeout = okHttpClient.connectTimeoutMillis
      this.readTimeout = okHttpClient.readTimeoutMillis
      this.writeTimeout = okHttpClient.writeTimeoutMillis
      this.pingInterval = okHttpClient.pingIntervalMillis
      this.minWebSocketMessageToCompress = okHttpClient.minWebSocketMessageToCompress
      this.routeDatabase = okHttpClient.routeDatabase
    }
```
So, i am trying to add my interceptor using this OkHttpClient, because interceptors is a mutable list.

`internal val interceptors: MutableList<Interceptor> = mutableListOf()`

**Comment by raphw** [comment]
If you instrument the constructor of the builder, it should be easy to use advice to add it. But I assume that you are loading the class during instrumentation. How does the log change once you disable validation? There should be something there after the change?

**Comment by gouravkrosx** [comment]
1. **If you instrument the constructor of the builder, it should be easy to use advice to add it.**
-> This worked, i just added a @Advice.This inside the Exit method's argument and got access to the `okhttp3.OkHttpClient$Builder` class and used its addInterceptor() method to add my custom interceptor.

2. **How does the log change once you disable validation?**
-> Then the `java.lang.IllegalStateException` did not show up.

One Last question before closing this issue:

```java
  new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED))
//                .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
                .type(named("okhttp3.OkHttpClient$Builder"))
                .transform(((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
                    System.out.println("Inside Merged Transformer (Builder constructor)");
                    return builder
                            .constructor(isDefaultConstructor()).intercept(Advice.to(TypePool.Default.ofSystemLoader().describe("org.example.advice.OkHttpAdvice").resolve(), ClassFileLocator.ForClassLoader.ofSystemLoader()))
                            
                            .method(ElementMatchers.named("build")).intercept(MethodDelegation.to(TypePool.Default.ofSystemLoader().describe("org.example.BuildInterceptor").resolve()));
                })).installOn(instrumentation);
```


In the above code snippet i want that if bytebuddy finds the 'build' method then it doesn't go to find the constructor, 
I am asking this because it is executing both the statements. But according to the official documentation.

```java
class Foo {
  public String bar() { return null; }
  public String foo() { return null; }
  public String foo(Object o) { return null; }
}
 
Foo dynamicFoo = new ByteBuddy()
  .subclass(Foo.class)
  .method(isDeclaredBy(Foo.class)).intercept(FixedValue.value("One!"))
  .method(named("foo")).intercept(FixedValue.value("Two!"))
  .method(named("foo").and(takesArguments(1))).intercept(FixedValue.value("Three!"))
  .make()
  .load(getClass().getClassLoader())
  .getLoaded()
  .newInstance();
```
My assumption is that as soon as it finds the perfect match considering (Byte Buddy organizes rules for overriding methods in a stack form.) that it should execute only once.

The reason why i am doing this is that okHttp offers 3 ways to make its Client.

1. `OkHttpClient client = new OkHttpClient().newBuilder().build();`
-> In this case if i only use Advice on constructor to add my custom interceptor, `okhttp3.OkHttpClient$Builder` default constructor is getting called twice internally so as my Advice.

2. `OkHttpClient client = new OkHttpClient.Builder().build();`
-> It's working fine using Advice on constructor.

3. `OkHttpClient client = new OkHttpClient(); `
-> It's also working fine using Advice on constructor. but not with the Interception on build method because it doesn't have one.

Below is the stack trace, its printing three times since its using both the builders and flow goes in Interceptor as well as in Advice.
```shell
Hello from premain
Hello OkHttpClient!
Inside Merged Transformer (Builder constructor)
Inside OnMethodEnter advice-> public okhttp3.OkHttpClient$Builder()
Inside OnMethodExit advice -> public okhttp3.OkHttpClient$Builder()
Inside OnMethodEnter advice-> public okhttp3.OkHttpClient$Builder()
Inside OnMethodExit advice -> public okhttp3.OkHttpClient$Builder()
Build Interceptor was called for: public final okhttp3.OkHttpClient okhttp3.OkHttpClient$Builder.build()
Inside HttpInterceptor before next()
Inside HttpInterceptor before next()
Inside HttpInterceptor before next()
Inside HttpInterceptor after next()
Inside HttpInterceptor after next()
Inside HttpInterceptor after next()
Response Response{protocol=h2, code=201, message=, url=https://reqres.in/api/users}
Body {"id":"281","createdAt":"2022-09-14T13:48:04.947Z"}
```

Thanks for your replies, you won't believe but i am learning alot from your library, Thanks alot!

**Comment by raphw** [comment]
You get handed a `typeDescription` in the `Transformation`. You can query it for all methods that are defined on the instrumented type.

**Comment by raphw** [comment]
You can navigate from a type description to the declaring or declared classes. That way you should be able to check one class from the other's transformer.

**Comment by gouravkrosx** [comment]
By using `typeDescription.getDeclaringType()` in 
```java
.type(named("okhttp3.OkHttpClient$Builder"))
                .transform(((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
                    System.out.println("Inside Merged Transformer (Builder constructor)");
                    return builder
                            .constructor(isDefaultConstructor()).intercept(Advice.to(TypePool.Default.ofSystemLoader().describe("org.example.advice.OkHttpAdvice").resolve(), ClassFileLocator.ForClassLoader.ofSystemLoader()));
                }))
```

I am getting `okhttp3.OkHttpclient` as typedescription in both cases, whether I apply the nested transformer or not.
 
This ` typeDescription.getDeclaredTypes()` gives empty array.

Along with these two, I've checked most of the other methods of typedescription, but none of them gave the clarity to use in my case.

Btw, really appreciated the efforts you are putting to answer queries in a very short turnaround time. Thanks a lot!

**Comment by raphw** [comment]
I'm not sure if I follow? The builder should be a declared type of the client and the client should be the declaring type of the builder.

Isn't it that you want to access the type information of one type from the other?

**Comment by gouravkrosx** [comment]
Basically, I want only one of the rules to execute. Currently, both of them are run and applied at the same time. 

```
        new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED))
//                .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
                
                // RULE #1
                .type(named("okhttp3.OkHttpClient"))
                .transform(((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
                    System.out.println("[" + Instant.now().getEpochSecond() + "]:Inside Merged Transformer (Builder interceptor)");
                        return builder.method(named("newBuilder").and(returns(named("okhttp3.OkHttpClient$Builder")))).intercept(MethodDelegation.to(TypePool.Default.ofSystemLoader().describe("org.example.BuilderInterceptor").resolve()));
                }))
                
                // RULE #2
                .type(named("okhttp3.OkHttpClient$Builder"))
                .transform(((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
                    System.out.println("[" + Instant.now().getEpochSecond() + "]:Inside Merged Transformer (Builder constructor)");
                    return builder
                            .constructor(isDefaultConstructor()).intercept(Advice.to(TypePool.Default.ofSystemLoader().describe("org.example.advice.OkHttpAdvice").resolve(), ClassFileLocator.ForClassLoader.ofSystemLoader()));
                }))
                .installOn(instrumentation);
```

**Comment by raphw** [comment]
You would need to implement your own `ElementMatcher` where you first match the type name and then some condition on the linked class. For example:

    named("okhttp3.OkHttpClient$Builder").and(declaredMethod(named("newBuilder"))

Then do the same for the other matcher, only that you check the declared types and see if the `Builder` type declares the method. This way, only one matcher would ever hit.

**Comment by gouravkrosx** [comment]
After customizing `ElementMatcher`, Both of them are still running and executing at the same time.
```java
                // RULE #1
                .type(named("okhttp3.OkHttpClient").and(declaresMethod(named("newBuilder"))))
                .transform(((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
                    System.out.println("[" + Instant.now().getEpochSecond() + "]:Inside Merged Transformer (Builder interceptor)");
                    return builder.method(named("newBuilder").and(returns(named("okhttp3.OkHttpClient$Builder")))).intercept(MethodDelegation.to(TypePool.Default.ofSystemLoader().describe("org.example.BuilderInterceptor").resolve()));
                }))
                // RULE #2
                .type(named("okhttp3.OkHttpClient$Builder").and(declaresMethod(named("build"))))
                .transform(((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
                    System.out.println("[" + Instant.now().getEpochSecond() + "]:Inside Merged Transformer (Builder constructor)");
                    return builder
                            .constructor(isDefaultConstructor()).intercept(Advice.to(TypePool.Default.ofSystemLoader().describe("org.example.advice.OkHttpAdvice").resolve(), ClassFileLocator.ForClassLoader.ofSystemLoader()));
                }))
//
```
Here:
-> `newBuilder` method is only in `okhttp3.OkHttpClient` and not in `okhttp3.OkHttpClient$Builder`.
-> `build` method is only in `okhttp3.OkHttpClient$Builder` and not in `okhttp3OkHttpClient`.

Can you please help spot what I'm missing?

**Comment by raphw** [comment]
Well, if both conditions are true, both of them are executed. Is there a scenario where either one of the two methods are missing?

My understanding is that different versions of OkHttp behave differently, and that's why you want to discriminate? In this case, you'd need to find out if there is a condition which is only true for either of the two matchers at all times.

**Comment by gouravkrosx** [comment]
I'm not trying different versions but different ways of initializing the okhttp client (currently for the latest version). To discriminate between the different initialization techniques I found that: 

-  `newBuilder` method is only in `okhttp3.OkHttpClient` and not in `okhttp3.OkHttpClient$Builder`.-> So when I call `OkHttpClient client = new OkHttpClient().newBuilder().build();`, only the first rule should execute. however, both are executed. 


But now I think I understand that this is expected behavior for bytebuddy. I was thinking that only 1 rule fires at a time if declared together or there was some DSL for ensuring only 1 rule fires (even though both are matched). 

Thanks for your time!

**Comment by raphw** [comment]
You can add `asTerminalMatcher` for any type, maybe that's what you are looking for.

**Comment by gouravkrosx** [comment]
Sorry, But I couldn't find `asTerminalMatcher` anywhere, but found a similar method `asTerminalTransformation`. Is this what you mean?

**Comment by raphw** [comment]
Yes

**Comment by gouravkrosx** [comment]
Same results after applying `asTerminalTrasformation` i.e both are getting executed.

```java
                // RULE #1
                .type(named("okhttp3.OkHttpClient").and(declaresMethod(named("newBuilder"))))
                .transform(((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
                    System.out.println("[" + Instant.now().getEpochSecond() + "]:Inside Merged Transformer (Builder interceptor)");
                    return builder.method(named("newBuilder").and(returns(named("okhttp3.OkHttpClient$Builder")))).intercept(MethodDelegation.to(TypePool.Default.ofSystemLoader().describe("org.example.BuilderInterceptor").resolve()));
                })).asTerminalTransformation()
//
                // RULE #2
                .type(named("okhttp3.OkHttpClient$Builder").and(declaresMethod(named("build"))))
                .transform(((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
                    System.out.println("[" + Instant.now().getEpochSecond() + "]:Inside Merged Transformer (Builder constructor)");
                    return builder
                            .constructor(isDefaultConstructor()).intercept(Advice.to(TypePool.Default.ofSystemLoader().describe("org.example.advice.OkHttpAdvice").resolve(), ClassFileLocator.ForClassLoader.ofSystemLoader()));
                })).asTerminalTransformation()
```

**Comment by raphw** [comment]
My bad, this does of course only apply on a "by type" basis.

**Comment by gouravkrosx** [comment]
It's absolutely fine.
By the way, Bytebuddy is an amazing library, got to know a lot about JavaAgent without having much prior knowledge of bytecode manipulation.
Thanks again, Really appreciated it!
