### ISSUE TITLE
 Instrumentation failed, constant pool error

### ISSUE THREAD

**Issue by 1057105012** [raphw/byte-buddy#1323]
Stack: [0x00007feedfd26000,0x00007feedfe26000],  sp=0x00007feedfe24750,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x848d0e]  MallocSiteTable::malloc_site(unsigned long, unsigned long)+0xe
V  [libjvm.so+0x849b93]  MallocTracker::record_free(void*)+0x193
V  [libjvm.so+0x905669]  os::free(void*, MemoryType)+0x9
V  [libjvm.so+0x6406bb]  InstanceKlass::release_C_heap_structures()+0x17b
V  [libjvm.so+0x6407da]  InstanceKlass::deallocate_contents(ClassLoaderData*)+0x3a
V  [libjvm.so+0x441643]  ClassLoaderData::free_deallocate_list()+0x273
V  [libjvm.so+0x441720]  ClassLoaderDataGraph::free_deallocate_lists()+0x20
V  [libjvm.so+0x49f77f]  ConcurrentMark::weakRefsWork(bool)+0x65f
V  [libjvm.so+0x4a3ca4]  ConcurrentMark::checkpointRootsFinal(bool)+0xb4
V  [libjvm.so+0xadac16]  VM_CGC_Operation::doit()+0xa6
V  [libjvm.so+0xada116]  VM_Operation::evaluate()+0x46
V  [libjvm.so+0xad844d]  VMThread::evaluate_operation(VM_Operation*) [clone .constprop.44]+0xcd
V  [libjvm.so+0xad8a33]  VMThread::loop()+0x3a3
V  [libjvm.so+0xad8e08]  VMThread::run()+0x78
V  [libjvm.so+0x90d8c2]  java_start(Thread*)+0x102

VM_Operation (0x00007fef10133e50): CGC_Operation, mode: safepoint, requested by thread 0x00007fef20064000

---------------  P R O C E S S  ---------------

Under the jdk.18 201 version, there are other probes such as skywalking, pinpoint, and a normal complex business. This error will occur in bytebuddy instrumentation, and the time of occurrence is uncertain. But it must occur

He seems to have something to do with these codes
          .visit(TypeConstantAdjustment.INSTANCE)
         .readerFlags(ClassReader.SKIP_FRAMES)
        .writerFlags(ClassWriter.COMPUTE_FRAMES);
how can i avoid it
But I don't have this problem using asm and javassist

**Comment by raphw** [comment]
This is a JVM crash. Did you get a crashdump file?

**Comment by 1057105012** [comment]
this is crash dump file  [https://github.com/1057105012/jdk_crash_dump/tree/main](url)

**Comment by raphw** [comment]
The dump suggests that the garbage collection failed somewhere. There's no Byte Buddy frames in the stack.
