### ISSUE TITLE
Intercept not working on windows with mac prebuild package.

### ISSUE THREAD

**Issue by i36lib** [raphw/byte-buddy#1324]
Hi raphw,
     I have wrote a trace tool base on byte-buddy. I package it using maven on my macbook pro, it work perfectly on Mac or Linux, but it doesn't work on windows and it doesn't raise any error. (I have shaded the byte-buddy package with another package name).

Do you have any idea about this issue ? Wish for your help.

**Comment by raphw** [comment]
Could you elaborate on "not working"? How do you install the agent?
