### ISSUE TITLE
Execution of Maven plugin in Eclipse broken since 1.12.13

### ISSUE THREAD

**Issue by odrotbohm** [raphw/byte-buddy#1328]
I have [a project](https://github.com/odrotbohm/tactical-ddd-workshop) that triggers the ByteBuddy transformation in Eclipse giving the following output (excerpt) when I change code in Eclipse:

```
27/09/2022, 08:28:34 CEST: [INFO] Resolved plugin: org.jmolecules.bytebuddy.JMoleculesPlugin
27/09/2022, 08:28:34 CEST: [INFO] Resolved entry point: REBASE
27/09/2022, 08:28:34 CEST: [INFO] Processing class files located in in: …/tactical-ddd-workshop/03-boilerplate/target/classes
27/09/2022, 08:28:34 CEST: [INFO] 
27/09/2022, 08:28:34 CEST: [INFO] □- de.odrotbohm.examples.ddd.persistence.Address
27/09/2022, 08:28:34 CEST: [INFO] ├─ JPA - Default constructor already present.
27/09/2022, 08:28:34 CEST: [INFO] └─ JPA - Not adding @j.p.Embeddable because type is already annotated with it.
27/09/2022, 08:28:34 CEST: [INFO] …
27/09/2022, 08:28:34 CEST: [INFO] 
27/09/2022, 08:28:34 CEST: [INFO] Transformed 10 types
```

For any version later than 1.12.12, the output changes to the following,

```
27/09/2022, 08:34:49 CEST: [INFO] Resolved plugin: org.jmolecules.bytebuddy.JMoleculesPlugin
27/09/2022, 08:34:49 CEST: [INFO] Resolved entry point: REBASE
27/09/2022, 08:34:49 CEST: [INFO] Processing class files located in in: …/tactical-ddd-workshop/03-boilerplate/target/classes
27/09/2022, 08:34:49 CEST: [INFO] No types were transformed during plugin execution but 11 class files were considered stale
```

even for full project builds. I have to resort to the command line and trigger a `mvn clean test-compile` before running tests, as the compilation step in the IDE does not trigger the ByteBuddy transformations anymore. I skimmed through the commit log but couldn't find anything suspicious.

**Comment by odrotbohm** [comment]
It seems to be caused by 658ddfe445fcb3109e65b5c1640988e2fd05bb7a. I am able to work around the problem by configuring `<staleMilliseconds>-1</staleMilliseconds>`.

**Comment by raphw** [comment]
Seems like Maven's build session, which is the only way to avoid duplicate instrumentation, does not play ball with the incremental build configuration.

I added an automated detection which would hopefully fix this. Can you give it a try?

**Comment by odrotbohm** [comment]
The output is the same on current `1.12.18-SNAPSHOT` (I built ByteBuddy locally). I guess it's worth adding that I am not using the incremental mode at all. Also, I have noticed that m2e apparently keeps some Maven state around (I had to refine the jMolecules plugin's [logging](https://github.com/xmolecules/jmolecules-integrations/issues/132) because of this). Looking at original changes, I wonder if that is causing the Mojo seeing the original instantiation time when it looks up `MavenExecutionRequest.getStartTime()`.

**Comment by raphw** [comment]
Hmm, that's annoying as I would not know how to know this context. The issue with direct Maven runs is that Maven will reapply the plugin even if the classes were not recompiled in case of a unchanged source directory. Otherwise, Maven only works with a clean build. I will try to see if there is a better solution to this.

**Comment by raphw** [comment]
I made another attempt by managing a custom file in the `maven-status` folder, similarly to the maven-compiler-plugin.

Can you give it a try?

**Comment by raphw** [comment]
Did you get a chance to try? Worked for me, it seems.

**Comment by odrotbohm** [comment]
Travelling currently. Will get to it on Friday.

**Comment by odrotbohm** [comment]
That seems to work fine on a locally built `1.12.18-SNAPSHOT`.
