### ISSUE TITLE
generated class implements interfaces disappear after retransform

### ISSUE THREAD

**Issue by zfyq124** [raphw/byte-buddy#1333]
[](url)I retransformed a class had enhance by open-telemetry agent(https://github.com/open-telemetry),  the generated class disappear some interface add by open-telemetry.
for example: the origin class code signature is:
![image](https://user-images.githubusercontent.com/5370955/193237335-e4b65b45-c252-4b76-b768-bd6e188c9966.png)
 
But the generated class code signature is:
![image](https://user-images.githubusercontent.com/5370955/193237025-30c0c64c-7ff6-4947-8ce0-0ff7b979d662.png)

The interface:io.opentelemetry.javaagent.bootstrap.VirtualFieldInstalledMarker,io.opentelemetry.javaagent.bootstrap.field.VirtualFieldAccessor$javax$servlet$Servlet$io$opentelemetry$javaagent$shaded$instrumentation$api$servlet$MappingResolver$Factory add by open-telemetry disappear.

The attachment is dump class, pls check.

[class.zip](https://github.com/raphw/byte-buddy/files/9682722/class.zip)

**Comment by zfyq124** [comment]
the byte-buddy version is 1.11.12
The issue work well on macos but not work on linux

**Comment by raphw** [comment]
Maybe the self-attachment does not work?

Have you tried updating to the latest version of Byte Buddy?

**Comment by zfyq124** [comment]
I had tried the latest version: 1.12.17 , the issue still exists.

I reupload the class dump with byte-buddy 1.12.17 and check it  in my local, can you recheck it? Thanks.

[class.dump.tar.gz](https://github.com/raphw/byte-buddy/files/9691765/class.dump.tar.gz)

**Comment by raphw** [comment]
How are you instrumenting? Byte Buddy retains any changes made by previous agents. Is this within the telemetry agent or in combination with an agent of yours?

**Comment by zfyq124** [comment]
My agent and telemetry is two separate agent. 

My agent worked like this: the agent use premain but do nothing when application start, just add a command hook to wait the server command. when the server send a command, Agent add a method matcher according to server command and add transform method.  Then invoke
```java
agentBuilder.installOn(instrumentation);
```

The advice code is like this:
```java
   @Advice.OnMethodEnter(suppress = CutoffException.class)
    public static <S, R, IR> IR atMethodEnter(@Advice.Origin Class<S> clazz,
                                              @Advice.Origin("#m#s") String methodSignature,
                                              @Advice.This(optional = true) S target,
                                              @Advice.AllArguments(readOnly = false, typing = Assigner.Typing.DYNAMIC) Object[] arguments,
                                              @InterceptorId int binderId) throws Throwable {
        InterceptorFactory<S, R, IR> interceptorFactory = (InterceptorFactory<S, R, IR>) InterceptorRegistry.getInterceptor(binderId);
        Object[] copy = arguments;
        IR ret = interceptorFactory.before(clazz, methodSignature, target, copy);
        arguments = copy;
        return ret;
    }

    @Advice.OnMethodExit(onThrowable = Throwable.class)
    public static <S, R, IR> void atMethodExit(@Advice.Origin Class<S> clazz,
                                               @Advice.Origin("#m#s") String methodSignature,
                                               @Advice.This(optional = true) S target,
                                               @Advice.AllArguments Object[] arguments,
                                               @Advice.Return(typing = Assigner.Typing.DYNAMIC) R retObj,
                                               @Advice.Thrown Throwable t,
                                               @Advice.Enter IR enterRet,
                                               @InterceptorId int binderId) throws Throwable {
        InterceptorFactory<S, R, IR> interceptorFactory = (InterceptorFactory<S, R, IR>) InterceptorRegistry.getInterceptor(binderId);
        try {
            interceptorFactory.after(clazz, methodSignature, target, arguments, retObj, t, enterRet);
        } finally {
            // do something
        }
    }
```
The biz logic is in InterceptorFactory, this may have nothing to do with this issue.

The enhance code like this:
```
    public <S, R, IR> void applyAdviceToMethod(final ElementMatcher<? super MethodDescription> methodMatcher,
                                               final String interceptorClassName,
                                               final String scopeName, final ExecutionPolicy executionPolicy,
                                               final Object... interceptorArgs) {
        InterceptorScope interceptorScope = ScopeFactory.getScope(scopeName);
        InterceptorFactory<S, R, IR> interceptorFactory = plugin.getInterceptorFactory(interceptorClassName,
                interceptorArgs, interceptorScope, executionPolicy);
        final int interceptorId = InterceptorRegistry.addInterceptor(interceptorFactory);
        agentBuilder = agentBuilder
                .transform(new AgentBuilder.Transformer
                        .ForAdvice(Advice.withCustomMapping().bind(InterceptorId.class, interceptorId))
                        .include(this.getClass().getClassLoader()) 
                        .withExceptionHandler(CutoffExceptionHandlers.defaultExceptionHandler())
                        .advice(methodMatcher, ByteBuddyAdvice.class.getName()));
    }
```

The AgentBuilder config is:
```java
        AgentBuilder agentBuilder =
                new AgentBuilder.Default()
                        .disableClassFormatChanges()
                        .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                        .with(new RedefinitionDiscoveryStrategy(agentConfig))
                        .with(new RedefinitionLoggingListener())
                        .ignore(agentIgnore())
                        .with(AgentBuilder.DescriptionStrategy.Default.POOL_ONLY)
                        .with(new TransformLoggingListener());
```

**Comment by zfyq124** [comment]
The telementry agent support retransformation. The dump class: org.springframework.web.servlet.DispatcherServlet-original.1664679756871.class has proved it.

By the way, this issue produce on linux，but work well for macos. Is there some difference for Byte-Buddy on these two platform?

**Comment by raphw** [comment]
No, not really, at least nothing in this area. Does your execution environment differ? Maybe there is another agent involved on Linux?

**Comment by zfyq124** [comment]
@raphw, I had found the root cause by according to debug.

When ClassWriter generate code,  instrumentType without the interface: io.opentelemetry.javaagent.bootstrap.VirtualFieldInstalledMarker,io.opentelemetry.javaagent.bootstrap.field.VirtualFieldAccessor$javax$servlet$Servlet$io$opentelemetry$javaagent$shaded$instrumentation$api$servlet$MappingResolver$Factory add by open-telemetry. So the laster class disappear the interface.

![Snipaste_2022-10-09_11-34-33](https://user-images.githubusercontent.com/5370955/194808979-357a0eb1-d16d-4336-a40c-f2a1cf4c84b9.png)

The instrumentType come from descriptionStrategy.apply(name, classBeingRedefined, typePool, circularityLock, classLoader, module),  Code as shown below.
 
```java
            private byte[] doTransform(JavaModule module,
                                       ClassLoader classLoader,
                                       String name,
                                       Class<?> classBeingRedefined,
                                       boolean loaded,
                                       ProtectionDomain protectionDomain,
                                       TypePool typePool,
                                       ClassFileLocator classFileLocator) {
                TypeDescription typeDescription = descriptionStrategy.apply(name, classBeingRedefined, typePool, circularityLock, classLoader, module);
                List<Transformer> transformers = new ArrayList<Transformer>();
                if (!ignoreMatcher.matches(typeDescription, classLoader, module, classBeingRedefined, protectionDomain)) {
                    for (Transformation transformation : transformations) {
                        if (transformation.getMatcher().matches(typeDescription, classLoader, module, classBeingRedefined, protectionDomain)) {
                            transformers.addAll(transformation.getTransformers());
                            if (transformation.isTerminal()) {
                                break;
                            }
                        }
                    }
                }

···
}
```

typePool is a cached pool, so the returned TypeDescription is initial class not the latest class retransformed by  telementry.

I have solved this issue by control the AgentCachingPoolStrategy make it return the latest TypeDescription.

Now, I have a question: why use instrumentedType.getSuperClass() and instrumentedType.getInterfaces() but not use
arguments: superClassInternalName, interfaceTypeInternalName when write class. Thanks.

**Comment by raphw** [comment]
This should normally be taken care of by the used `ClassFileBufferStrategy` where a `PoolStrategy` is informed about the name of the class. The `WithTypePoolCache` implementation of it discriminates for this name and avoids resolving the description from the cache.

The behavior you are describing is available when using `TypeStrategy.DECORATE`.
