### ISSUE TITLE
Advice with custom mapping and bindDynamic generates incorrect bytecode

### ISSUE THREAD

**Issue by bgaraude** [raphw/byte-buddy#1334]
If i use an advice with custom mapping and the bindDynamic method, and that the dynamically bootstrapped value is a type that takes no argument, it works fine (in byte buddy's unit tests, it generates Callable<String>, in my attached test, it generates a Supplier<String>, and works as wel).

But if the dynamically bootstrapped value is a type that takes arguments, e.g. Function<String, String>, it fails to generate the class with: java.lang.VerifyError: Bad type on operand stack.

I'm not sure if there are constraints on the dynamically bootstrapped value type?

It happens on 1.12.17.
Here is a test case reproducing the issue: https://gist.github.com/bgaraude/4cc3cb4d462ab423e3256ec786a7dfa9

**Comment by raphw** [comment]
Looks like you found a bug. There's a SAM locator that is probably not needed as the bootstrap method's arguments are confused with the bound type's method's arguments. I'll have a look and try to fix this.

**Comment by raphw** [comment]
Found it and fixed on master.
