### ISSUE TITLE
Facing issue with obfuscated javaagent

### ISSUE THREAD

**Issue by amar1019** [raphw/byte-buddy#1335]
Getting the following error in bytebuddy listener log

**java.lang.IllegalStateException: public static boolean com.FileAdvice.before(java.io.File) dropped 1 implicit frames**

I have excluded all the bytebuddy and advice classes from obfusction. Tried with 1.12.10 bytebuddy version. I have checked the decompiled code after obfuscation. It is exactly the same without obfuscation.

Any idea?

**Comment by raphw** [comment]
That's a typical sign of obfuscation. Did you check the advices bytecode to be unaltered?

**Comment by amar1019** [comment]
Yes. It is unaltered

**Comment by raphw** [comment]
But the issue does not occur without obfuscation?

**Comment by amar1019** [comment]
Till now, there is no issue. Only when we add obfuscation this happens.

**Comment by amar1019** [comment]
After adding -dontpreverify flag in the proguard.conf, i am able to instrument other classes but still the classes which are preloaded before the agent, i am not able to instrument.

**Comment by raphw** [comment]
The exception you are getting would mean that the stack map frames in the advice code are no longer fully consistent. This is allowed by the JVM if some variables are no longer used after the inconsistency. But for Byte Buddy, to inline the code, this is not possible if the code is used as a template.

I'd compare the advice class's byte code before and after obfuscation and verify that nothing has changed. This should solve your issue.

**Comment by amar1019** [comment]
I am not seeing that exception now. But preloaded classes are not getting instrumented unless we explicitly try to reload that class using inst.retransformClasses(new Class[]{Class.forName("java.io.FileInputStream")});

Looks like the following strategies are not working if we obfiscate.

.with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
.with(AgentBuilder.TypeStrategy.Default.REDEFINE)

**Comment by raphw** [comment]
Are there any exceptions reported to a listener?

**Comment by amar1019** [comment]
It didn't report any errors. I feel it didn't try to redefine the class
which is why I didn't see any errors

**Comment by raphw** [comment]
Strange. Maybe the obfuscator does something with class loading? It's hard for me to make suggestions here. One thing I can think of is the possibility of a changed loading order. Try registering a more lenient `ReiterationStrategy` in the agent builder.

**Comment by amar1019** [comment]
ReiterationStrategy didn't work. I can stick with inst.retransformClasses(). but AgentBuilder.RedefinitionStrategy.RETRANSFORMATION and AgentBuilder.TypeStrategy.Default.REDEFINE does anything extra ?

**Comment by raphw** [comment]
Retransformation is a more modern way where you do not need to provide an initial byte array (something that Byte Buddy handles for you if you use redefine. Redefine is basically only needed if you wanted to support Java 5.

**Comment by dogourd** [comment]
Maybe you should check if `RedefinitionStrategy.Listener` is set, this can catch exceptions that occur during `retransformClasses` calls, which are not normally caught by `AgentBuilder.Listener` by default. 
If this is the case, you may need to continue setting the `BatchAllocator` and override the `RedefinitionStrategy.Listener.onError` method to try to solve it.

**Comment by 1057105012** [comment]
I encountered this problem, I suggest that you upgrade bytebuddy and progurad to the latest version, which can solve this problem. I think this problem is a bug of proguard, which has been fixed
