### ISSUE TITLE
ByteBuddy does not intercept public method

### ISSUE THREAD

**Issue by rgb1380** [raphw/byte-buddy#1338]
I have posted this on stackoverflow, as I am not sure if this is a bug or misconfiguration on my part. Will be great if this can be triaged. 

https://stackoverflow.com/questions/73969523/bytebuddy-does-not-intercept-public-method

**Comment by raphw** [comment]
Did you get anywhere with this? If so, please comment to reopen. I had original reached out to you on StackOverflow.
