### ISSUE TITLE
How can i return Future<T> using returns method in Bytebuddy?

### ISSUE THREAD

**Issue by Sarthak160** [raphw/byte-buddy#1340]
I am intercepting a method which returns Future<T> where i know that ‘T’ is subclass of ‘E’.
How can i use returns() method of `net.bytebuddy.matcher.ElementMatchers` to achieve that?
I want something like `returns(Future<isSubtypeOf(E.class)>)`.

**Comment by raphw** [comment]
You can implement an `ElementMatcher<MethodDescription>` yourself, which is the easiest. Byte Buddy offers methods on the `TypeDescription.Genric` API which allows you to read all type information. Otherwise, `ElementMatchers` has factory methods for `returnsGeneric` where you can match a parameterized type as well.

**Comment by Sarthak160** [comment]
So, should I write like the below code if I want to return `Future<T>`?
```java
 ElementMatcher.Junction<MethodDescription> methodDescriptionJunction = returnsGeneric(type -> {
                        boolean b1 = type.asErasure().represents(Future.class);
                        boolean b2 = type.getSort().isParameterized();
                        boolean b3 = type.getTypeArguments().get(0).asErasure().represents(T.class);
                        return b1 && b2 && b3;
                    });
```

And please also tell me about below two situations.

1. What if T extends E, then where should it put `isSubTypeOf(E.class)`.

2. If I want to take a generic argument should i write like this 
```java
takesGenericArgument(0,type -> {
                        boolean b1 = type.asErasure().represents(Future.class);
                        boolean b2 = type.getSort().isParameterized();
                        boolean b3 = type.getTypeArguments().get(0).asErasure().represents(T.class);
                        return b1 && b2 && b3;
                    })
```

**Comment by raphw** [comment]
`represents` only works for erasures. You would need to check if the type argument has a super type that is a type variable named `E`. As for your example code. If `b2` is `false`, the code for `b3` would throw an exception, so rather chain the calls instead of having them on separate lines.
