### ISSUE TITLE
Is it possible to add more values ​​after ByteBuddy.makeEnumeration()?

### ISSUE THREAD

**Issue by JPPlaysGamer** [raphw/byte-buddy#1344]
Assuming I want to create an enumeration. So I did...
```java
new ByteBuddy().makeEnumeration(predefinedValues).name(nameOfNewType);
```

Where `predefinedValues` are `"TEST1"` and `"TEST2"`. But if I wanted to add `"TEST3"` after `makeEnumeration()`, is it possible? Especially if the enumeration has a constructor?

**Comment by raphw** [comment]
That's tricky, an enumeration is a composite of many elements. In Java, the language, it looks much simpler. 

You might just define a new enum and give it the same name as the one you want to change. Then replace the class, if it is that simple.
