### ISSUE TITLE
how to ignore custom class？

### ISSUE THREAD

**Issue by Oldjie** [raphw/byte-buddy#1346]
Hi，author,i have a question,
this is my code 
```
  AgentBuilder agentBuilder = new AgentBuilder.Default()
                .disableClassFormatChanges()
                .with(RETRANSFORMATION)
                .ignore(none())
                .ignore(ElementMatchers.nameStartsWith("com.example.MyFirstFuzzTarget.agent.bytebuddy.AdviceLogic"))
                .disableClassFormatChanges()
                .with(RETRANSFORMATION)
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
                .with(AgentBuilder.TypeStrategy.Default.REBASE);
        
        agentBuilder.type(ElementMatchers.nameMatches("java.io.File")
                        .or(ElementMatchers.nameMatches("java.net.URL")))
                .transform((builder, typeDescription, classLoader, module) ->
                        builder.visit(Advice.to(AdviceLogic.class)
                                .on(isConstructor())))
                .installOn(install);

        URI uri = new URI("https://www.google.com/");
        URL url = uri.toURL();
        URLConnection connection = url.openConnection();
        connection.connect();
        String referer = connection.getRequestProperty("Referer");
        String host = uri.getHost();
```
```
public class AdviceLogic {

    @Advice.OnMethodEnter
    public static void onMethodEnter(@Advice.Origin String methodName, @Advice.AllArguments Object[] args) throws URISyntaxException, IOException {

        System.out.println("methodName:"+methodName);
        // This can lead to repeated invoke
        URI uri = new URI("https://www.google.com/");
        URL url = uri.toURL();
        URLConnection connection = url.openConnection();
    }

}
```
I tried to ignore it 【com.example.MyFirstFuzzTarget.agent.bytebuddy.AdviceLogic】，but it didn't work

**Comment by raphw** [comment]
Not sure what you mean by *ignore* here. What are you seeing and what do you expect to see?

**Comment by Oldjie** [comment]
my bad ,i mean  when we use ”agentBuilder.type( )“ try hook somebody class. like this ` agentBuilder.type(ElementMatchers.nameMatches("java.net.URL")` ，But I just want to specify the call when the intercept is made
like this 
`package com.example.agent.bytebuddy;

import java.net.MalformedURLException;
import java.net.URL;

public class A {

    public A() {
    }

    public void  test() throws MalformedURLException {
        URL url = new URL("url");
    }
}


package com.example.agent.bytebuddy;

import java.net.MalformedURLException;
import java.net.URL;

public class B {

    public B() {
    }

    public void  test() throws MalformedURLException {
        URL url = new URL("url");
    }
}
`
I have two classes of A and B, They all trigger 【new URL()】,but I just want to intercept when A triggers, I wonder if this is ok.

(forgive me，my english is very bad)

**Comment by raphw** [comment]
Byte Buddy only inserts byte code. The only way to do this from regular code is to use `StackWalker` to see where a call is coming from. You can of course do this, but it might generate some overhead.

**Comment by Oldjie** [comment]
thanks! I tried to judge his source by calling the stack，is work, Although it may generate some overhead.
