### ISSUE TITLE
Class initialization deadlock with TypeDescription.ForLoadedType and TypeDescription.Generic

### ISSUE THREAD

**Issue by cushon** [raphw/byte-buddy#1347]
We started seeing infrequent deadlocks in code using bytebuddy after upgrading to a version of bytebuddy built targeting Java 8+ bytecode.

My colleague @jianglizhou figured out that this is do to a circular class initialization deadlock between `net.bytebuddy.description.type.TypeDescription$ForLoadedType` and `net.bytebuddy.description.type.TypeDescription$Generic` that manifests when there are two calls to `net.bytebuddy.ByteBuddy.subclass`, one for an interface, and one for a non-interface class:

https://github.com/raphw/byte-buddy/blob/eea667f8c5e3a95512119c585e233ab10b33f6e4/byte-buddy-dep/src/main/java/net/bytebuddy/ByteBuddy.java#L511-L516

This is a sample thread dump showing the deadlock:

```
"pool-1-thread-1@1152" prio=5 tid=0x11 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at net.bytebuddy.description.type.TypeDescription$ForLoadedType.asGenericType(TypeDescription.java:8913)
      at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:515)
      at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:483)
      at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:380)
      at net.bytebuddy.ByteBuddySubclassDeadlockTest$Tester$1.call(ByteBuddySubclassDeadlockTest.java:38)
      at net.bytebuddy.ByteBuddySubclassDeadlockTest$Tester$1.call(ByteBuddySubclassDeadlockTest.java:34)
      at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
      at java.util.concurrent.FutureTask.run(FutureTask.java:-1)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.lang.Thread.run(Thread.java:833)

"pool-1-thread-2@1157" prio=5 tid=0x12 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at net.bytebuddy.description.type.TypeDescription$Generic.<clinit>(TypeDescription.java:476)
      at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:512)
      at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:483)
      at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:380)
      at net.bytebuddy.ByteBuddySubclassDeadlockTest$Tester$2.call(ByteBuddySubclassDeadlockTest.java:48)
      at net.bytebuddy.ByteBuddySubclassDeadlockTest$Tester$2.call(ByteBuddySubclassDeadlockTest.java:44)
      at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
      at java.util.concurrent.FutureTask.run(FutureTask.java:-1)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
      at java.lang.Thread.run(Thread.java:833)
```

I have created a [unit test that reproduces the deadlock](https://gist.githubusercontent.com/cushon/99af432a70ff65049bdfb59e2f1e8d7c/raw/e3bd5b2fff76099607ed3b6c9ca767a884f27d37/ByteBuddySubclassDeadlockTest.java) on about 50% of test runs.

A possible workaround is to explicitly initialize one of the two classes in the `clinit` for `ByteBuddy`.

It's a little bit surprising that this only reproduces when bytebuddy is compiled with `-source 8 -target 8` or newer. From skimming the diff between the bytecode for the two versions, there were some changes around additional `checkcast`s and bridge methods, which could have caused one of the classes to be initialized more eagerly, and prevented the deadlock from happening.

**Comment by raphw** [comment]
I suspect that the JVM verifier does something funky here as it might resolve frame types and this locks up the loading here. It feels to me that this is a bug in the JVM rather than Byte Buddy. I cannot spot a circularity.

I agree that this needs fixing, but loading the types from `ByteBuddy` does not feel like the right approach. The classes in question can be entered from multiple locations. Ideally, one of the classes would initialize the other.

**Comment by raphw** [comment]
Could you investigate if https://github.com/raphw/byte-buddy/commit/5a809653d383454a2f196fc0366b2721c779871c does the trick?

**Comment by cushon** [comment]
> I cannot spot a circularity.

My understanding is that the circularity is:

* `Generic` is an indirect super interface of `OfNonGenericType.ForLoadedType`, so `OfNonGenericType.ForLoadedType` initialization causes `Generic` to be initialized
* `Generic`'s static initializer has a reference to `OfNonGenericType.ForLoadedType`, so when `Generic` is being initialized it triggers initialization of `OfNonGenericType.ForLoadedType`

> Ideally, one of the classes would initialize the other.
...
> Could you investigate if https://github.com/raphw/byte-buddy/commit/5a809653d383454a2f196fc0366b2721c779871c  does the trick?

It fixes the flakiness in the provided test, but I'm not sure I understand the approach. Should that change have modified `OfNonGenericType.ForLoadedType` instead of `TypeDescription.ForLoadedType`?

**Comment by jianglizhou** [comment]
> 

The problem occurs during running OfNonGenericType.ForLoadedType and Generic <clinit>s (which can be triggered by 'new', 'getstatic', etc) concurrently, after those classes are loaded.

Would it be possible to avoid referencing the child class (ForLoadedType) from Generic static initializer? That could also resolve the deadlock issue if possible.

**Comment by jianglizhou** [comment]
> I agree that this needs fixing, but loading the types from ByteBuddy does not feel like the right approach. The classes in question can be entered from multiple locations. Ideally, one of the classes would initialize the other.

Just some more clarifications, the proposed fix is to trigger 
 net/bytebuddy/description/type/TypeDescription$Generic (which would trigger ForLoadedType class initialization as well) class initialization in ByteBuddy class initializer, before any potential concurrent execution of ByteBuddy.subclass(). Following is the generated bytecode of @cushon's fix. 'getstatic #216' triggers net/bytebuddy/description/type/TypeDescription$Generic class initialization. Looking at https://github.com/raphw/byte-buddy/commit/5a809653d383454a2f196fc0366b2721c779871c, it's not too clear if that would enforce the same effect.

  static {};
    Code:
       0: getstatic     #216                // Field net/bytebuddy/description/type/TypeDescription$Generic.OBJECT:Lnet/bytebuddy/description/type/TypeDescription$Generic;
       3: putstatic     #657                // Field genericTypeDescription:Lnet/bytebuddy/description/type/TypeDescription$Generic;
       6: getstatic     #216                // Field net/bytebuddy/description/type/TypeDescription$Generic.OBJECT:Lnet/bytebuddy/description/type/TypeDescription$Generic;
       9: invokestatic  #660                // Method java/util/Objects.requireNonNull:(Ljava/lang/Object;)Ljava/lang/Object;
      12: pop
...

**Comment by raphw** [comment]
Alright, I gave it a try without breaking binary compatibility where the constants are now also deprecated. Can you check if this solves the problem for you?

**Comment by cushon** [comment]
> Can you check if this solves the problem for you?

I ran the repro 100000 times at 408736f5d9f2ae2611c5609045d102f16f987fcd and am not seeing any failures, so it still looks good to me, thanks!

**Comment by raphw** [comment]
Great, as you are building to a custom target, I assume you are not dependent on an official release? Otherwise, I can try to make one some time soon.

**Comment by cushon** [comment]
>  I assume you are not dependent on an official release?

Yep, I can pull in the latest changes without an official release, so there's no rush from my perspective.

Thank you for the quick fix!
