### ISSUE TITLE
can i use asm to interceptor interface?

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#135]
my code is
```
.type(named("javax.ws.rs.container.ContainerRequestFilter"))
 .transform(new RequestFilterAdviceTransformer())
```
i want to use asm to interceptor all filter which has implements ContainerRequestFilter interface

but has exception
```
java.lang.IllegalStateException: Cannot advice abstract or native method public abstract void javax.ws.rs.container.ContainerRequestFilter.filter(javax.ws.rs.container.ContainerRequestContext) throws java.io.IOException
```

and i change to 
```
.type(named("org.glassfish.jersey.server.spring.scope.RequestContextFilter"))
        .transform(new RequestFilterAdviceTransformer())
```
is ok and ```RequestContextFilter implements ContainerRequestFilter ```

i debug code, i found byte buddy think ```javax.ws.rs.container.ContainerRequestFilter``` is an abstract class, but i find ```ContainerRequestFilter``` is public interface, not an abstract class.

**Comment by raphw** [comment]
As the method suggests, it is not possible to apply `Advice` to an abstract or native method. Therefore, you need to instrument the super classes. In the current master for Byte Buddy, there exists a `hasSuperType` matcher that does exactly what you are trying to do:

```java
.type(hasSuperType(named("javax.ws.rs.container.ContainerRequestFilter")))
 .transform(new RequestFilterAdviceTransformer())
```

You can copy the code from GitHub. Make sure that your check in your transformer if a method is non-abstract as you can only apply the advice on such methods.

**Comment by dragontree101** [comment]
thanks, i will wait for you deploy the jar to maven.

**Comment by raphw** [comment]
Sure, please note that it might take me a while to release, I will probably merge the Jigsaw extensions soon and wait with release until then.

**Comment by dragontree101** [comment]
i update to 1.4.0 version, and use 
```
.type(hasSuperType(named("javax.ws.rs.container.ContainerRequestFilter")))
 .transform(new RequestFilterAdviceTransformer())
```
but also has the same exception
does my code error
but when i use
```
.type(isSubTypeOf(ContainerRequestFilter.class))
```
is ok

**Comment by raphw** [comment]
You have to specify in your element matcher for the advice that you are not interested in abstract or native methods because advice cannot be applied to them.

The reason that it works using the subtype matcher is the fact that using the constant triggers the loading of the classprior to the registration of the class file transformer such that the classes (abstract) methods are not attemptet to be advised.

**Comment by dragontree101** [comment]
so i can't use ```hasSuperType(named("javax.ws.rs.container.ContainerRequestFilter"))```  constant triggers  ?    or  other way to solve this?

**Comment by raphw** [comment]
Yes, you can. However, you cannot apply advice tk the interface type.

If your matcher on the advice constraints abstract and native methods, you are good.

For example, wrap your matcher by not(isAbstract().or(isNative()) - ill think about how to make this easier in the future.
