### ISSUE TITLE
How to intercept java.lang.*

### ISSUE THREAD

**Issue by cao0810** [raphw/byte-buddy#1354]
Not in effect：
        new AgentBuilder.Default().ignore(none())
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
                .with(TypeStrategy.Default.REDEFINE)
                .ignore(ElementMatchers.none())
                .type(named("java.lang"))
                .transform((builder, type, classLoader, module) ->
                        builder
                                .method(ElementMatchers.<MethodDescription>any())
                                .intercept(MethodDelegation.to(MonitorMethod.class))
                )
                .installOn(inst);
Excuse me, where did the problem arise?

**Comment by raphw** [comment]
This is probably an issue with the boot class loader not being able to see your interceptor. You need to add such code to the boot loader. The `Instrumentation` API offers a method for this purpose.

**Comment by cao0810** [comment]
Do you have a sample?

**Comment by raphw** [comment]
Simply check the javadoc of Instrumentation. The injected code is available on any class loader
