### ISSUE TITLE
Need dates greater than 1970 on packaged files

### ISSUE THREAD

**Issue by OxnardM** [raphw/byte-buddy#1355]
Please see this issue: https://github.com/spring-projects/spring-boot/pull/19595#issuecomment-974173112
when troubleshooting found the byte buddy jar and byte buddy agent jar version 1.12.18 are set with very old, on windows, year 1607 which is causing the bug 19595 to occur. 

Could you rebuild the jar with dates greater than 1970 and publish as a new version.

The functionality works fine as long as it is not in an uber jar

Thanks

**Comment by raphw** [comment]
This is necessary for repeatable builds: https://maven.apache.org/guides/mini/guide-reproducible-builds.html

If you are using a Byte Buddy version for 1.10.x, this won't be an issue, but for newer JVMs, you will need to update your Spring Boot version.
