### ISSUE TITLE
Classloading Issue When Using JDK > 8

### ISSUE THREAD

**Issue by noel-ternida** [raphw/byte-buddy#1356]
I have this setup where I am intercepting a method call:

` new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED))
                .with(new AgentBuilder.Listener.WithErrorsOnly(AgentBuilder.Listener.StreamWriting.toSystemOut()))
            .type(named("okhttp3.Request$Builder"))
            .transform(((builder, typeDescription, classLoader, javaModule) -> {
                return builder	.method(ElementMatchers.named("build")).intercept(Advice.to(TypePool.Default.ofSystemLoader().describe("com.tst.advice.BuildAdvice").resolve(), ClassFileLocator.ForClassLoader.ofSystemLoader()));
            })).installOn(inst);`

I loaded the helper classes within a jar to the bootstrap classloader search:

            `JarFile agentJar = new JarFile(javaagentFile, false);
            inst.appendToBootstrapClassLoaderSearch(agentJar);`

Everything works fine while using JDK 8 but fails with the following error when I switched to Java 11:

`Exception in thread "BatchLogProcessor_WorkerThread-1" java.lang.NoClassDefFoundError: org/ietf/jgss/Oid
        at com.jpmorgan.authagent.httputils.Utils.getGSSToken(Utils.java:483)`
		
The call happens within the jar that I loaded to the bootstrap classloader search. 

I did some debugging and the class could be loaded by the PlatformClassLoader. How do I specify that class loader within my jar?

**Comment by raphw** [comment]
That should not happen, unless when the module system is in place. Are you injecting the class prior to instrumentation? Each class name is only attempted to be resolved a single time.

**Comment by noel-ternida** [comment]
It works if I add the jar file to the system classloader search instead of the bootstrap classloader search. 

`inst.appendToSystemClassLoaderSearch(agentJar);`

Though it presents another problem for me, but at least this part is working.

Thanks for the tip on what should be working.
