### ISSUE TITLE
Byte-Buddy plugin in another module

### ISSUE THREAD

**Issue by esfomeado** [raphw/byte-buddy#1358]
Hello,

I have a Gradle project with two modules. On module A I have the byte-buddy plugin and on module B I have the code that I want to apply that plugin to.

This doesn't seem to work at all.

If I move the module A to an independent JAR or move the code to the `buildSrc` folder it works but I need to have the plugin in the module A since it contains classes that are common between both modules and I can't move them to a seperate project.

Is there any work around to get this to work  or is not possible at all to do this?

Thanks

**Comment by raphw** [comment]
You can specify a *discoverySet* and load plugins from there: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/ByteBuddyTaskExtension.java#L45

Such a set can be defined as a dependency set, which can also represent project coordinates. So it is my understanding that this should be possible?

**Comment by raphw** [comment]
You can define it in an extension:

```groovy
byteBuddy {
  discoverySet = sourceSet.myCollection
}
```

Where you would define a source set similar to `implementation` and so forth.
