### ISSUE TITLE
Why I can't hook the class Socket?

### ISSUE THREAD

**Issue by Restlol** [raphw/byte-buddy#1360]
Hi there, 
     I'm trying to hook the class Socket to intercepte the input  by @MethodEnter 、@MethodExit , but it doesn't work,Could u give me some suggestions. thank you.

Here is the code as following !

1. Socket demo
```
# this is socket server codes

 try {
            ServerSocket ss = new ServerSocket(8888);
            System .out.println("server starting....");
            Socket s = ss. accept ();
            System .out.println("client:"+s.getInetAddress().getLocalHost()+"has connected!");
            BufferedReader br = new BufferedReader(new InputStreamReader(s.getInputStream()));
            String   mess  = br.readLine();
            System .out.println("client send messages："+ mess );
            BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(s.getOutputStream()));
            bw. write ( "reply!,I'm server" +"\n");
            bw.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }
```
<hr/>

```

# this is socket client codes

  Socket s = new Socket("127.0.0.1",8888);
            InputStream is = s.getInputStream();
            OutputStream os = s.getOutputStream();

            BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(os));
            bw. write ("I'm client\n");
            bw.flush();
            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            String   mess  = br.readLine();
            System .out.println("server send messages："+ mess );
        } catch (UnknownHostException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

```
2. this is the Agent Codes
```
 new AgentBuilder.Default().type(ElementMatchers.hasSuperType(named("java.net.Socket")))
                .transform((builder, typeDescription, classLoader, module) -> {
            return builder.visit(Advice.to(MyAdvice.class).on(isMethod()));
        }).installOn(instrumentation);

```
<hr>

```
# this is the Advice codes
   @Advice.OnMethodEnter
    public static void enter(@Advice.Origin Method method, @Advice.AllArguments Object[] prams) throws NoSuchFieldException {
        System.out.println("enter-------" + method.getDeclaringClass());
    }
    @Advice.OnMethodExit(onThrowable = Throwable.class)
    public static void exit(@Advice.Thrown Throwable r,@Advice.Origin Method method){
        System.out.println("exit-------" + method.getDeclaringClass());
    }
```

<hr>

I find that if I add the code fragment  as below, it works !  but why ?
```
.disableClassFormatChanges()
.with(RETRANSFORMATION)
.ignore(none());
``` 

and I don't find any introduction about ***disableClassFormatChanges*** or other statements like this in official documents

Looking forward to your answer！

**Comment by raphw** [comment]
By default, Byte Buddy ignores JVM classes. You can change this by specifying a different `ignore` matcher where you specify different classes to ignore than JVM classes. If you specify a "by name" matcher, this should be fine, but be careful to add an expensive matcher here.

**Comment by Restlol** [comment]
> By default, Byte Buddy ignores (忽略) JVM classes. You can change this by specifying (指定) a different `ignore` matcher where you specify (指定) different classes to ignore (忽略) than JVM classes. If you specify a "by name" matcher, this should be fine, but be careful to add an expensive matcher here.



> By default, Byte Buddy ignores (忽略) JVM classes. You can change this by specifying (指定) a different `ignore` matcher where you specify (指定) different classes to ignore (忽略) than JVM classes. If you specify a "by name" matcher, this should be fine, but be careful to add an expensive matcher here.

THANKS A Million
