### ISSUE TITLE
Is there a way to get the return value other than @Advice.return?

### ISSUE THREAD

**Issue by arkenli** [raphw/byte-buddy#1362]
Hello,

Currently, I want to intercept two methods in a class like the following:
```
public class Example {
    
    public void method1() {
        //do something;
    }
    
    public String method2() {
        //do something
        return "result";
    }
}
```

And my MethodMatcher is 
```
@Override
    public ElementMatcher<? super MethodDescription> getMethodMatcher() {
        return not(isConstructor());
}
```

Since the return value is important for me, my onMethodExit is as follw:
```
@Advice.OnMethodExit
    public static void onMethodExit(@Advice.Return Object obj) {
        //do something;
}
```
However, since method 1 does not return a value and will therefore cause the match to fail and the enhancement to method 2 will not take effect either.  And the return value is important to me, I wonder if bytebuddy has such a way of getting the return value: when the return type is void, it gives null. when the method returns some other type, then it can return the correct return value.

Thanks for your contribution on bytebuddy.

**Comment by raphw** [comment]
You can set the `typing` property to `DYNAMIC`. Then `null` is assigned.

**Comment by arkenli** [comment]
Thanks, it works
