### ISSUE TITLE
Difference rebase and redefine

### ISSUE THREAD

**Issue by xiangtianyu** [raphw/byte-buddy#1364]
I read the tutorial and get the difference betweeen rebase and redefine, so i wrote program to verify it.
The base class
```java
package org.example.bytebuddy.test;

public class MyClassTest {
    public String test() {
        return "my test";
    }
}
```

redefine code :
```java
new ByteBuddy()
        .redefine(MyClassTest.class)
        .method(ElementMatchers.named("test"))
        .intercept(FixedValue.value("Hello World!"))
        .make()
        .saveIn(new File("result"));
```

redefine result:
```java
package org.example.bytebuddy.test;

public class MyClassTest {
    public MyClassTest() {
    }

    public String test() {
        return "Hello World!";
    }
}
```

rebase code
```java
new ByteBuddy()
        .rebase(MyClassTest.class)
        .method(ElementMatchers.named("test"))
        .intercept(FixedValue.value("Hello World!"))
        .make()
        .saveIn(new File("result"));
```
rebase result
```java
package org.example.bytebuddy.test;

public class MyClassTest {
    public MyClassTest() {
    }

    public String test() {
        return "Hello World!";
    }
}
```

It seems the same with rebase and redefine, the private method in rebase disappears. What's the problem?

**Comment by raphw** [comment]
The difference comes when you try to invoke an existing method, such as by `SuperMethodCall`. With rebase, the original method is treated as if it was declared by a super class. With redefine, it is as if the method did not exist.

**Comment by xiangtianyu** [comment]
In my example the method `test` will be rebased or redefined by new test.
The docs shows difference between rebase and redefine by this example :
```
class Foo {
  String bar() { return "bar"; }
}
class Foo {
  String bar() { return "foo" + bar$original(); }
  private String bar$original() { return "bar"; }
}
```
But in my example the result is same. I means in my rebase example, there is no private method like the Foo example, that's why?

**Comment by yaohwu** [comment]
When using `FixedValue.value("Hello World!")`, you do not need origin `test` method implement which return "my test" any more and it will be removed in rebase or redefine.
It's a quite simple demo so you can not get the difference.

You can get more info about the rebase and redefine strategy
https://bytebuddy.net/#/tutorial:~:text=Redefining%20and%20rebasing%20existing%20classes

Or just try using `SuperMethodCall.INSTANCE` instead of `FixedValue.value("Hello World!")`

**Comment by yaohwu** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/9320666/203691769-99c2dde9-5bcc-4563-b547-a75fae80f989.png">
The origin method shows.

But why can not the origin method be decompiled by IDEA or other decompile tools? 

for it as if the method of super class ?

**Comment by yaohwu** [comment]
```
        try {
            Object test = new ByteBuddy()
                    .rebase(MyClassTest.class)
                    .method(ElementMatchers.named("test"))
                    .intercept(FixedValue.value("Hello World!"))
                    .make().load(String.class.getClassLoader()).getLoaded().newInstance();
            // origin method
            Method originMethod = test.getClass().getDeclaredMethods()[0];
            System.out.println("method: " + originMethod.getName());
            originMethod.setAccessible(true);
            // origin method call
            System.out.println(originMethod.invoke(test));

            // origin method
            Method testMethod = test.getClass().getDeclaredMethods()[1];
            System.out.println("method: " + testMethod.getName());
            testMethod.setAccessible(true);
            // origin method call
            System.out.println(testMethod.invoke(test));

        } catch (IllegalAccessException | InvocationTargetException | InstantiationException e) {
            throw new RuntimeException(e);
        }
```

invoking both origin method and intercepted method works.

**Comment by xiangtianyu** [comment]
> <img alt="image" width="891" src="https://user-images.githubusercontent.com/9320666/203691769-99c2dde9-5bcc-4563-b547-a75fae80f989.png">
> 
> using `FixedValue.value("Hello World!")` works the same.
> 
> <img alt="image" width="913" src="https://user-images.githubusercontent.com/9320666/203704310-94946ee9-3e2e-4924-9229-c448ec437637.png">
> 
> The origin method shows.
> 
> But why can not the origin method be decompiled by IDEA or other decompile tools?
> 
> for it as if the method of super class ?

Maybe it‘s idea's bug, the class file shows in idea is broken

**Comment by raphw** [comment]
Many decompilation tools do not show private methods by default. Javap for example needs the -p switch.

**Comment by xiangtianyu** [comment]
> Many decompilation tools do not show private methods by default. Javap for example needs the -p switch.

I get it! Thanks!
