### ISSUE TITLE
Compatibility GRAAL VM

### ISSUE THREAD

**Issue by nexus061** [raphw/byte-buddy#1367]
Hi all, I use a library that packages bytebuddy, I'm trying the native compilation with the latest version of spring is I get an error "com.oracle.svm.core.jdk.UnsupportedFeatureError: No classes have been predefined during the image build to load from bytecodes at runtime." when trying to instantiate byte buddy, I changed the library to point to the latest version of bytebuddy but nothing changed; Do you have any suggestions?
[error.txt](https://github.com/raphw/byte-buddy/files/10099014/error.txt)

**Comment by raphw** [comment]
You can run an agent that collected dynamically generated classes, but it requires some setup. Here's an example of using Mockito (and therewith Byte Buddy) on Graal:

https://gist.github.com/raphw/e0f6864ddcad69630d839c2eebaad818
