### ISSUE TITLE
Improve the error reporting in case of external attachment failure

### ISSUE THREAD

**Issue by jeanbisutti** [raphw/byte-buddy#1368]
Hi,

I have recently investigated a problem with external attachment failure (lack of permission on ` /proc/{pid]/...` in my case).

[The message of the root cause is hidden today  by Byte Buddy](https://github.com/raphw/byte-buddy/blob/c912dcf40cd9c5df79f89c583ffca5fdfa73e9b3/byte-buddy-agent/src/main/java/net/bytebuddy/agent/Attacher.java#L79). Would it be possible to avoid this?

I made the following changes to Byte Buddy to be able to understand why the external attachment fails:

 * In `Attacher` class, removal of the try/catch
```java
       try {
       
        } catch (Throwable throwable) {
            System.exit(1);
        }
```
* In `ByteBuddyAgent` class, with this kind of code
```java
 private static void installExternal(...) throws Exception {
            ...
            Process process = new ProcessBuilde(...).start();
            int exitValue = process.waitFor();
            InputStream errorStream = process.getErrorStream();
            if (exitValue != SUCCESSFUL_ATTACH) {
                throw new IllegalStateException("Could not self-attach to current VM using external process " + System.lineSeparator() + toString(errorStream));
            }
            ....
```

It would be great to propagate the root cause message to ease the investigations. I can create a PR with the above changes.

**Comment by raphw** [comment]
the issue with this is that the process stream needs to be read asynchronously. Since the buffer might run full and block the process, this can introduce a whole different set of problems. How would you want to approach this?

**Comment by raphw** [comment]
The problem I see is that it requires additional privileges and the threading might have unexpected side-effects. I would rather communicate by status code.

What error did you encounter? There should be a very limited amount of things that can go wrong based on the error message.

**Comment by jeanbisutti** [comment]
The exception caught in the `Attacher` class and hidden by Byte Buddy is `com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/{pid}/{user}/tmp/.java_pid{pid}: target process {pid} doesn't respond within 10500m or HotSpot VM not loaded.` My problem was a lack of permission on  `/proc/{pid}/{user}`.  Would it be possible to add more information in the `IllegalStateException` that can be raised from the `installExternal` method to find the root cause of this kind of problem quickly?

**Comment by raphw** [comment]
I wonder if I would rather wrap this in a debugging property. Let me look into it.

**Comment by raphw** [comment]
I added a property `net.bytebuddy.agent.attacher.dump` that allows dumping the error message to a file location. Would that work for you? It is less invasive as for the actual process.

**Comment by jeanbisutti** [comment]
> I added a property `net.bytebuddy.agent.attacher.dump` that allows dumping the error message to a file location. Would that work for you? It is less invasive as for the actual process.

Yes, it could have helped me understand my problem's origin. Thank you!

If this property is not enabled, it may also be helpful to recommend it in the message of [this exception](https://github.com/raphw/byte-buddy/blob/810dcb131dc7421f50cc67716384f86b810a80a9/byte-buddy-agent/src/main/java/net/bytebuddy/agent/ByteBuddyAgent.java#L701).
