### ISSUE TITLE
unable to target java.sql.DriverManager class 

### ISSUE THREAD

**Issue by Sarthak160** [raphw/byte-buddy#1369]
I was trying to intercept registerDriver method in `java.sql.DriverManager` class by using Bytebuddy's agent in premain.
 
```java
      new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED))
       .with(new AgentBuilder.InitializationStrategy.SelfInjection.Eager())
       .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
       .type(named("java.sql.DriverManager"))
       .transform((builder, typeDescription, classLoader, javaModule, protectionDomain) -> {
             System.out.println("INSIDE REGISTER DRIVER TRANSFORMER !!!! ");
             try {
                    return builder.method(named("registerDriver").and(takesArguments(2)))
                   .intercept(FixedValue.value(new KDriver()));
                  } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }                    
        
          .intercept(MethodDelegation.to(TypePool.Default.ofSystemLoader()
         .describe("io.keploy.advice.ksql.RegisterDriverManagerAdvice").resolve()));
                }).installOn(instrumentation);
```

But i was unable to locate the DriverManager Class, when i used Listener i found that there is not a single class of `java.sql` package it was showing.
Any help would be appreciated.

**Comment by raphw** [comment]
You will explicitly need to define a different `.ignore(...)` matcher which excludes JVM classes by default. Ideally, you should add a good exclusion that uses a class's name. This is for efficiency reasons.

**Comment by Sarthak160** [comment]
So when i added `.ignore(none())` , it was able to find the `java.sql.DriverManager` Class, but the problem is that in the below advice class when i try to change the actual driver with my custom driver which is in my classpath, it's giving me `java.lang.NoClassDefFoundError`. I am guessing that it's due to the classloader, DriverManager Class is loaded by bootstrap classloader and the class i am accessing in the advice i.e `KDriver`, it has not been loaded yet because it is in application classPath.

RegisterDriverAdvice
```java

package io.keploy.advice;

import io.keploy.ksql.KDriver;
import net.bytebuddy.asm.Advice;

import java.lang.reflect.Method;
import java.sql.Driver;
import java.sql.SQLException;

public class RegisterDriverAdvice {
    @Advice.OnMethodEnter
    public static void enterMethod(@Advice.Origin Method method, @Advice.Argument(value = 0, readOnly = false) Driver driverName) throws SQLException {
        System.out.println("Inside register driver manager !!!");
        System.out.println("Entering method[" + method + "] with argument[" + driverName + "] from EnterAdvice");

        System.out.println("Here goes our Driver: " + driverName);
 
       ClassLoader classLoader = driverName.getClass().getClassLoader();
        System.out.println("ClassLoader of DriverClass :" + classLoader);

         KDriver.DriverName = driverName.getClass().getSimpleName();
         driverName = new KDriver();
    }

    @Advice.OnMethodExit
    public static void exitMethod(@Advice.Origin Method method) {
        System.out.println("exit advice -> " + method);
    }
}

```

Please! help I am stuck here.

**Comment by Sarthak160** [comment]
Okay, I found that I have to inject my `KDriver` in the bootstrap classloader, using `instrumentation.appendToBootstrapClassLoaderSearch(new JarFile(path_to_Jar_Containing_KDriver)`, But I have some queries...
1. Since my project is a multi-module project and this `KDriver` depends on some classes and dependencies present in different modules. So I have to add all those modules as jar in the bootstrap classloader,  is this the only way to do this?
2. Do I also have to add agent jar in the bootstrap classloader??

**Comment by raphw** [comment]
Each class loader will only be able to see the classes you inject into it or the classes that it has already loaded. Normally, it is a good approach to inject utilities for the instrumented code into the targeted class loader, keep the agent seperate and communicate state as string and integers between the two via a dispatcher class in the boot loader.
