### ISSUE TITLE
Adding a method invocation to a method body without using substitution?

### ISSUE THREAD

**Issue by orange0rca** [raphw/byte-buddy#1373]
How can I just add a method invocation to a method body (without the method invocation I want to include in the method body being the substitute for something in the method body)?  Thanks.

**Comment by raphw** [comment]
If you are rebasing, you can use `andThen` on the method call and add `SuperMethodCall`. Otherwise, have a look at `Advice` for decorating a class.

**Comment by orange0rca** [comment]
Thanks Rafael.  Can you give an example in code/pseudocode of how andThen and SuperMethodCall would be used in this case?

**Comment by raphw** [comment]
It would be: `MethodCall.invoke(...).andThen(SuperMetodInvocation.INSTANCE)`.

What did you try so far?
