### ISSUE TITLE
Is there any way to ensure that `net.bytebuddy.asm.Advice` is loaded by a specific classloader without using `inline=true`

### ISSUE THREAD

**Issue by dogourd** [raphw/byte-buddy#1374]
For example, I want to enhance the class `com.A` loaded by the class loader `ClassLoaderA`，and this class loader also loads classes `com.B` and `com.C`. My Advice looks like this:
```java
public class MyAdvice {
  @Advice.OnMethodEnter(inline=false)
  public static void before(@This Object a) {
      (Com.A) a.xxx();
      com.B.xxx();
      com.c.xxxx();
  }
}
```
I tried to use a custom `ByteArrayClassLoader.ChildFirst` class loader, this class loader will hold the class resource of `MyAdvice`, and `ClassLoaderA` as the parent loader.
The code for transform looks like this:
```java
public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
    // this class loader itself holds the class resource of `MyAdvice`, and takes `classloader` in the parameter as its parent
    ClassLoader myChildFirstClassLoader;
    Class<?> advice = myChildFirstClassLoader.loadClass("MyAdvice");
    ClassFileLocator classFileLocator = ClassFileLocator.ForClassLoader.of(myChildFirstClassLoader);
                                
    ASMVisitorWrapper visitor = Advice.to(advice, classFileLocator).on(ElementMatchers.named("targetMethod"));
    builder.visit(visitor);
    return builder;
}
```
But it is inconsistent with my expected results. When configuring **`inline=false`**, `MyAdvice` still cannot access `com.A` and `com.B` classes at runtime (`NoClassDefFoundError: com/B`).
It looks like the custom class loader is not working, is my usage wrong here? How can I make my custom class loader work?
Thanks!

**Comment by dogourd** [comment]
wow,I recently tried to use the `net.bytebuddy.asm.Advice.WithCustomMapping#bootstrap(java.lang.reflect.Method)` API provided in the class library, and imitated [elastic-apm-agent](https://github.com/elastic/apm-agent-java/blob/965c6567186b91c179314570270ebff62a46f130/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/IndyBootstrap.java#:~:text=private%20static%20ConstantCallSite%20internalBootstrap(MethodHandles.Lookup%20lookup%2C%20String%20adviceMethodName%2C%20MethodType%20adviceMethodType%2C%20Object%5B%5D%20args)%20%7B) to make an implementation, and now the effect is as expected , Is this the solution byte-buddy provides for this?

**Comment by raphw** [comment]
This is a possible approach, yes.

Otherwise, `Advice` provides an overload for a `TypeDescription` where you can create advice from an arbitrary class loader or `ClassFileLocator` which would allow for an alternative solution.
