### ISSUE TITLE
Automatic plugin discovery doesn't work when using Gradle

### ISSUE THREAD

**Issue by 0dinD** [raphw/byte-buddy#1378]
When using the `byte-buddy-gradle-plugin` (I am using plain Java, not Android), it seems like the automatic plugin discovery mentioned here doesn't work: https://github.com/raphw/byte-buddy/blob/d4b5cdbed4a94fccfe457daf4913dccc8c02a175/byte-buddy-gradle-plugin/README.md?plain=1#L28

By "doesn't work" I mean that nothing happens, the plugin (which is in the `discoverySet`) and its transformations are not applied. If I run Gradle with the `--debug` flag, I do find this:

```
[DEBUG] [org.gradle.api.Project] Not configuring task for source set 'main' as no transformations are defined
```

Which I think comes from here: https://github.com/raphw/byte-buddy/blob/d4b5cdbed4a94fccfe457daf4913dccc8c02a175/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/AbstractByteBuddyTaskConfiguration.java#L71

But I thought the whole point of the automatic discovery was that I shouldn't have to specify any transformations explicitly? So it seems like there is a bug in the `byte-buddy-gradle-plugin`?

To be clear, everything works as expected if I manually specify a `transformations { pluginName = "..." }` entry, but I'd like to avoid it since this is already declared in the `META-INF/net.bytebuddy/build.plugins` file. It's also worth mentioning that I tried the same thing using `byte-buddy-maven-plugin`, where automatic plugin discovery worked like a charm without having to specify any explicit transformation entries.

**Comment by raphw** [comment]
That's a bug indeed. Let me look into that!

**Comment by raphw** [comment]
This is an oversight as the plugin previously optimized to avoid adjusting the task graph if no plugin was configured. This does however no longer work with discovery which was added later. This is now fixed.

**Comment by 0dinD** [comment]
Thanks, I tried the master branch and it seems to work now!
