### ISSUE TITLE
Reduce Gradle plugin boilerplate

### ISSUE THREAD

**Issue by 0dinD** [raphw/byte-buddy#1379]
Assuming that I have a Byte Buddy build plugin with a valid `META-INF/net.bytebuddy/build.plugins` file, here is what the current boilerplate looks like for using said plugin in another project using Gradle (I am using plain Java, not Android):

```groovy
plugins {
	id "net.bytebuddy.byte-buddy-gradle-plugin" version "1.12.20"
}

configurations.register("byteBuddy")

dependencies {
	byteBuddy "org.example:my-byte-buddy-plugin:1.0.0-SNAPSHOT"
}

byteBuddy {
	discoverySet = configurations.byteBuddy
	transformation {
		pluginName = "org.example.MyByteBuddyPlugin"
	}
}
```

If #1378 is fixed, this can be reduced to:

```groovy
plugins {
	id "net.bytebuddy.byte-buddy-gradle-plugin" version "1.12.20"
}

configurations.register("byteBuddy")

dependencies {
	byteBuddy "org.example:my-byte-buddy-plugin:1.0.0-SNAPSHOT"
}

byteBuddy {
	discoverySet = configurations.byteBuddy
}
```

Now I'm wondering, wouldn't it be nice if we could reduce it to:

```groovy
plugins {
	id "net.bytebuddy.byte-buddy-gradle-plugin" version "1.12.20"
}

dependencies {
	byteBuddy "org.example:my-byte-buddy-plugin:1.0.0-SNAPSHOT"
}
```

That is to say, I would like the `byte-buddy-gradle-plugin` to automatically create the `byteBuddy` configuration and use it as the default `discoverySet`. Curiously, this feature seems to already exist for Android (but not for plain Java): https://github.com/raphw/byte-buddy/blob/d4b5cdbed4a94fccfe457daf4913dccc8c02a175/byte-buddy-gradle-plugin/android-plugin/README.md?plain=1#L7-L8

**Comment by raphw** [comment]
Is `configurations.register("byteBuddy")` really necessary? I thought that you could just declare new configurations.

Other than that, I think that it's good to have a convention over configuration approach here and add this feature. Would you want to try sending a PR?

**Comment by raphw** [comment]
I added a solution. Could you build Byte Buddy from master and check if it works out as you would expect it?

**Comment by 0dinD** [comment]
> Is `configurations.register("byteBuddy")` really necessary? I thought that you could just declare new configurations.

Yeah you could also do `configurations { byteBuddy }` which I think is the same as `configurations.create("byteBuddy")`. I was thinking along the lines of configuration avoidance (https://docs.gradle.org/7.6/userguide/task_configuration_avoidance.html). After looking at https://docs.gradle.org/7.6/dsl/org.gradle.api.artifacts.ConfigurationContainer.html#N16DBD, I thought it would be better to `register` than to `create` since I don't need the configuration immediately. But it probably doesn't matter, the Gradle docs only use configuration avoidance for tasks in their examples, not for configurations as far as I can tell.

> I added a solution. Could you build Byte Buddy from master and check if it works out as you would expect it?

I got the following error when running with the build from master:

```
> Task :byteBuddy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':byteBuddy'.
> Discovered plugin is not available: org.example.MyByteBuddyPlugin
```

Which I think comes from here: https://github.com/raphw/byte-buddy/blob/e577cf1d42ba378c7e997e2ddc69e2cab1e625f1/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/AbstractByteBuddyTask.java#L393

Which is probably because the class isn't loaded from the correct class loader: https://github.com/raphw/byte-buddy/blob/e577cf1d42ba378c7e997e2ddc69e2cab1e625f1/byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/AbstractByteBuddyTask.java#L388

The Maven plugin loads the class like this: https://github.com/raphw/byte-buddy/blob/e577cf1d42ba378c7e997e2ddc69e2cab1e625f1/byte-buddy-maven-plugin/src/main/java/net/bytebuddy/build/maven/ByteBuddyMojo.java#L410

So I tried changing `Class.forName(name)` to `Class.forName(name, false, classLoader)` in `AbstractByteBuddyTask`, rebuilt the plugin, and now it seems to work like expected using the third example (with minimal boilerplate)!

**Comment by 0dinD** [comment]
Also, I found when looking at the code changes you made that the type used for `discoverySet` is a bit inconsistent:

```
$ rg -i "discoverySet.*Configuration"
src/main/java/net/bytebuddy/build/gradle/AbstractByteBuddyTaskExtension.java
455:    protected abstract void discoverySet(Configuration configuration);

src/main/java/net/bytebuddy/build/gradle/ByteBuddyPlugin.java
116:                    extension.discoverySet(project.getConfigurations().create(name));

src/main/java/net/bytebuddy/build/gradle/ByteBuddySimpleTaskExtension.java
55:    protected void discoverySet(Configuration configuration) {
56:        discoverySet = configuration;

src/main/java/net/bytebuddy/build/gradle/ByteBuddyTaskExtension.java
66:    protected void discoverySet(Configuration configuration) {
67:        discoverySet = configuration;

src/main/java/net/bytebuddy/build/gradle/ByteBuddyJarTaskExtension.java
55:    protected void discoverySet(Configuration configuration) {
56:        discoverySet = configuration;
```

```
$ rg -i "FileCollection.*discoverySet"
src/main/java/net/bytebuddy/build/gradle/ByteBuddyTask.java
48:    private FileCollection discoverySet;
113:    public FileCollection getDiscoverySet() {
122:    public void setDiscoverySet(@MaybeNull FileCollection discoverySet) {

src/main/java/net/bytebuddy/build/gradle/ByteBuddyTaskExtension.java
46:    private FileCollection discoverySet;
121:    public FileCollection getDiscoverySet() {
130:    public void setDiscoverySet(@MaybeNull FileCollection discoverySet) {
```

```
$ rg -i "Iterable<File>.*discoverySet"
src/main/java/net/bytebuddy/build/gradle/ByteBuddySimpleTask.java
52:    private Iterable<File> discoverySet;
129:    public Iterable<File> getDiscoverySet() {
138:    public void setDiscoverySet(@MaybeNull Iterable<File> discoverySet) {
159:    protected Iterable<File> discoverySet() {

src/main/java/net/bytebuddy/build/gradle/ByteBuddyJarTask.java
52:    private Iterable<File> discoverySet;
130:    public Iterable<File> getDiscoverySet() {
139:    public void setDiscoverySet(@MaybeNull Iterable<File> discoverySet) {
160:    protected Iterable<File> discoverySet() {

src/main/java/net/bytebuddy/build/gradle/ByteBuddySimpleTaskExtension.java
37:    private Iterable<File> discoverySet;
72:    public Iterable<File> getDiscoverySet() {
81:    public void setDiscoverySet(@MaybeNull Iterable<File> discoverySet) {

src/main/java/net/bytebuddy/build/gradle/ByteBuddyTask.java
143:    protected Iterable<File> discoverySet() {

src/main/java/net/bytebuddy/build/gradle/AbstractByteBuddyTask.java
360:    protected abstract Iterable<File> discoverySet();
585:        protected static ClassLoader of(ClassLoader classLoader, @MaybeNull Iterable<File> discoverySet) {

src/main/java/net/bytebuddy/build/gradle/ByteBuddyJarTaskExtension.java
37:    private Iterable<File> discoverySet;
72:    public Iterable<File> getDiscoverySet() {
81:    public void setDiscoverySet(@MaybeNull Iterable<File> discoverySet) {
```

`Configuration` extends `FileCollection` which implements `Iterable<File>`, so maybe it makes sense to use `Iterable<File>` everywhere? Not that it really matters to me, but if someone wants to use something other than a `Configuration` for `discoverySet` it would help to have the more generalized types. And I haven't looked at the code in detail, so maybe there's a good reason to use `FileCollection` and/or `Configuration` in some places.

**Comment by raphw** [comment]
You are of course right, the plugin loading was a bug all along. I changed it now and made some other changes. Thanks for the quick feedback!

**Comment by 0dinD** [comment]
I tried your changes, and everything seems to work as expected now. Thanks for the quick fix!
