### ISSUE TITLE
Stack map does not match the one at exception handler

### ISSUE THREAD

**Issue by orange-buffalo** [raphw/byte-buddy#138]
Greetings Rafael,

I'm using Byte Buddy and its `AgentBuilder` + `Advice` features to install it on `Instrumentation` from my agent. I really appreciate your great work, the product is amazing! Recent migration from javassist improved performance of real-life instrumentation significantly, and introduced much better readability and code structure.  

There is an issue with running this agent in Tomcat v8.0.35 (with Oracle JDK 1.8.0_77 64-bit), namely verification error appears while loading class `org.eclipse.jdt.internal.compiler.lookup.InferenceContext18`:
```
java.lang.VerifyError: Stack map does not match the one at exception handler 307
``` 

There is a minimal test case to reproduce the problem, please find it in [attachment](https://github.com/raphw/byte-buddy/files/310828/byte-buddy-test.zip).

**Comment by raphw** [comment]
Thank you for the reproduction, this really makes things much easier to look into. I am currently at a conference but I will look at the problem first thing tomorrow. Thanks for that!

**Comment by raphw** [comment]
I have found and fixed the bug. I still have some clean-up to do, I had to change quite some bits in the ground model of the `Advice` component and I want to avoid that anything breaks that worked before.

**Comment by orange-buffalo** [comment]
Glad to here that this is fixed! Thank you!

**Comment by raphw** [comment]
Fixed on `HEAD` and to be released via 1.4.2.

**Comment by orange-buffalo** [comment]
I've tested this on 1.4.2 - works like a charm. Besides, I've discovered significant performance boost - instrumentation takes 10% less time to execute now.  
Thanks a lot for these changes!

**Comment by raphw** [comment]
Great to hear it works and boosts performance. I found some unnecessary allocations but I do not really understand how that could have such a strong effect. Great, though!
