### ISSUE TITLE
Intercepting in Android

### ISSUE THREAD

**Issue by moshere** [raphw/byte-buddy#1382]
Hi,
I would like to try the byte-buddy on Android
https://github.com/raphw/byte-buddy/tree/master/byte-buddy-android

I could run the above example, however I'm wonder if there is an option to wrap existing method with some logic or replace existing implementation. If yes - an example will be great.

Thanks

**Comment by moshere** [comment]
When I try 
` .intercept(MethodDelegation.to(new TimingInterceptor()))`

I'm always getting the following error:
`java.lang.IllegalArgumentException: Cannot resolve ambiguous delegation of`


This is the example
```
Class<XXX> dynamicType =
          new ByteBuddy()
              .subclass(XXX.class)
              .method(ElementMatchers.named("start"))
              .intercept(MethodDelegation.to(new TimingInterceptor()))
              .make()
              .load(getClass().getClassLoader(), strategy)
              .getLoaded();
```

**Comment by raphw** [comment]
This would mean that `TimingInterceptor` has several possible delegation methods. How does the class look like and how does the `start` method look like? Make sure that you are not using `Advice` annotations.
