### ISSUE TITLE
How to return result in @Advice.OnMethodEnter

### ISSUE THREAD

**Issue by LeePui** [raphw/byte-buddy#1386]
Hi.
I have the following requirement, on a method:
```
    @GetMapping("/insert")
    public String insert(String message) {
        db.insert(......);
        return xxx_result;
    }
```
I want to make some judgments on the parameter(message), like this：
```
    @GetMapping("/insert")
    public String insert(String message) {
        if ("xxx".equals(message)) {
            return InsertAdvice.beforeMethod(message);
        }
        db.insert(......);
        return xxx_result;
    }
```
`db.insert()` cannot be executed twice.

If I use the following code：
```
class InsertAdvice {
    @Advice.OnMethodEnter(inline = false)
    public static void beforeMethod(@Advice.AllArguments Object[] allArguments) {
        ...
    }
    @Advice.OnMethodExit(inline = false)
    public static void afterMethod(@Advice.Return Object ret) throws Throwable {
        ...
    }
}
-------------------------
AgentBuilder.Default()
                .type(ElementMatchers.<TypeDescription>named("class name"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        Advice to = Advice.withCustomMapping()
                                .to(InsertAdvice.class);
                        return builder.visit(to.on(ElementMatchers.named("insert")));
                    }
                })
```
It will generate the following code:
```
    @GetMapping("/insert")
    public String insert(String message) {
        InsertAdvice,beforeMethod();
        db.insert(......);
        InsertAdvice.afterMethod();
        return xxx_result;
    }
```
but it doesn't meet my needs. Is there any way  return result in @Advice.OnMethodEnter?
thanks!

**Comment by dogourd** [comment]
have a look at this 
1) [is-it-possible-to-return-from-a-method-using-advice-onmethodenter](https://stackoverflow.com/questions/50237592/is-it-possible-to-return-from-a-method-using-advice-onmethodenter).  
2) #819   

If that's not enough, maybe you should consider using `MethodDelegation`

**Comment by LeePui** [comment]
> have a look at this
> 
> 1. [is-it-possible-to-return-from-a-method-using-advice-onmethodenter](https://stackoverflow.com/questions/50237592/is-it-possible-to-return-from-a-method-using-advice-onmethodenter).
> 2. [How to return in @Advice.onMethodEnter  #819](https://github.com/raphw/byte-buddy/issues/819)
> 
> If that's not enough, maybe you should consider using `MethodDelegation`

thank you! This solved my problem.
