### ISSUE TITLE
Question about transformation on java.lang.Thread

### ISSUE THREAD

**Issue by FrankChen021** [raphw/byte-buddy#1387]
Hello @raphw ,

Happy new year! 

I ran into a problem about transformation on `java.lang.Thread` and I'm seeking your response.

I got following test case which works.

```java
static class AdviceTest {
        @Advice.OnMethodEnter
        public static void enter() {
            throw new RuntimeException("From Advice");
        }
    }

    @Test
    public void testAdviceThread_Work() {
        final Instrumentation instrumentation = ByteBuddyAgent.install();
        new AgentBuilder.Default()
            .with(AgentBuilder.Listener.StreamWriting.toSystemOut().withErrorsOnly())
            .with(AgentBuilder.InstallationListener.StreamWriting.toSystemOut())
            .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
            .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
            .type(ElementMatchers.named("java.lang.Thread"))
            .transform(new AgentBuilder.Transformer() {
                public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder,
                                                        TypeDescription typeDescription,
                                                        ClassLoader classLoader,
                                                        JavaModule module,
                                                        ProtectionDomain protectionDomain) {
                    return builder.visit(Advice.to(AdviceTest.class).on(ElementMatchers.named("start")));
                }
            })
            .installOn(instrumentation);
        Thread t = new Thread(new Runnable() {
            public void run() {
                System.out.println(1);
            }
        });
        t.start();
    }
```

However, if I made some changes to the `transform` method above to add a field to `java.lang.Thread` such as

```java
return builder.visit(Advice.to(AdviceTest.class).on(ElementMatchers.named("start")))
                       .defineField("str", String.class, Modifier.PUBLIC);  // <--- after adding this line, the `start` method is not intercepted
```

The `start` method is not intercepted. 
In such case, the transformat does not report any error and if we look at the generated class file, we can see not only the field `str` is added but also `start` method is changed. 
```java
   // disassemble from Thread.class

...
    public synchronized void start() {
        throw new RuntimeException("From Advice");
    }

...
```

My question is why in such case the `start` method is not intercepted during runtime while its method is changed?

**Comment by dogourd** [comment]
This is expected because the JVM does not allow you to add fields to already loaded classes,  exception is in thrown during `retransformClasses`, you need to add `RedefinitionStrategy.Listener` to see it.
```java
.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
.with(AgentBuilder.RedefinitionStrategy.Listener.StreamWriting.toSystemOut())
```

**Comment by FrankChen021** [comment]
Thank you @dogourd for the response.

Now the question is why does not byte-buddy throws the exception in such case by default instead of requiring users to install a listener to know this problem?

**Comment by dogourd** [comment]
here is my personal opinion:
In addition to `RedefinitionStrategy.Listener`, byte-buddy also provides `RedefinitionStrategy.BatchAllocator`, which allows you to divide all classes you care about into several batches when operating `retransformClasses`. Each batch has the possibility of success or failure. If an exception is thrown by default. A bad batch can affect subsequent good batches(Of course, it can also be independent of each other, but this requires the author to make more changes to the source code). byte-buddy provides enough flexibility here. Of course, this will increase the threshold of use, because the relevant instructions are all in the notes, not mentioned in the getting started document.
raphw probably thinks more about this, or just likes it. :)

**Comment by FrankChen021** [comment]
@dogourd That makes sense. Seems like you're very familiar with byte-buddy.
