### ISSUE TITLE
Latest bytebuddy incompatible with JDK 17

### ISSUE THREAD

**Issue by JoeJoe1989** [raphw/byte-buddy#1395]
Hi, 

I got an unit test error "java.lang.NoSuchMethodException: java.security.AccessController.reflected$doPrivileged(java.security.PrivilegedAction)
" when running in **JDK 17**, which was attributed to bytebuddy shaded by mockito. There was no such error when running in **JDK 11**.

The mockito version here is 5.0.0 which already uses the latest bytebuddy (1.12.22). Could you please take a look? Thanks. I initially raised the [question](https://github.com/mockito/mockito/issues/2885) in mockito.

![image](https://user-images.githubusercontent.com/6061826/214479380-ebba0b22-e8f5-4c66-ba38-eb2043aeb461.png)

**Comment by raphw** [comment]
Mockito already builds on Java 17 on each build. I assume this is caused by something else.

Are you running an EA release?

**Comment by JoeJoe1989** [comment]
> Mockito already builds on Java 17 on each build. I assume this is caused by something else.
> 
> Are you running an EA release?

Not EA, I am using the Microsoft Build of OpenJDK 17.0.5 LTS.

**Comment by raphw** [comment]
Does the same happen with a different distribution?

**Comment by JoeJoe1989** [comment]
I am working for LinkedIn/Microsoft, so I am using MSFT distribution only. However, I don't think that would make a difference since it is based on the OpenJDK 17.0.5 LTS.

**Comment by JoeJoe1989** [comment]
This error seems to be an known issue introduced in Java 16 https://github.com/highsource/maven-jaxb2-plugin/issues/201

**Comment by raphw** [comment]
I just built BB with Microsoft Java:

```cmd
~/workspace/oss/byte-buddy$ mvn -v
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /home/rafael/.sdkman/candidates/maven/current
Java version: 17.0.6, vendor: Microsoft, runtime: /home/rafael/Downloads/jdk-17.0.6+10
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-58-generic", arch: "amd64", family: "unix"
```

and the build went fine. This is likely related to your environment setup.

**Comment by JoeJoe1989** [comment]
Yep, the error I mentioned isn't critical and is not the root cause.
