### ISSUE TITLE
JDK 21 support

### ISSUE THREAD

**Issue by johanjanssen** [raphw/byte-buddy#1396]
Hi, I know I'm quite early :), but is support for JDK 21 already planned?

I ran the following example https://github.com/johanjanssen/JavaHiddenGems/tree/main/Examples/equalsverifier on an ea version of Java 21. It uses EqualsVerifier https://jqno.nl/equalsverifier/ which in turn uses Byte Buddy and produces the following error:

-> Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property

**Comment by raphw** [comment]
For now, please set -Dnet.bytebuddy.experimental=true

Then it will work. Proper support is coning soon.

**Comment by johanjanssen** [comment]
Yes, I'm using that now indeed. Thanks a lot for working on supporting Java 21 and the great work on Byte Buddy in general!

**Comment by kennymacleod** [comment]
With the release of JDK 20 yesterday, 21 LTS is next up. Do you have an updated target release of byte-buddy?

**Comment by raphw** [comment]
I'm waiting a bit on ASM here, unfortunately. The day they release support, I'll follow.

**Comment by kennymacleod** [comment]
ASM 9.5 is out in the wild. Aww yeah.

**Comment by raphw** [comment]
Releasing as we speak.

**Comment by ascopes** [comment]
@raphw random question, hope you don't mind me asking here.

Would specifying this flag enable JDK 21 build support for Mockito, given it uses ByteBuddy internally?

**Comment by raphw** [comment]
It is supported in the latest Byte Buddy version. Mockito should have picked that up?

**Comment by bergerdenes** [comment]
Java 21 was out a few weeks ago, please give an update on when it will be officially supported. Thanks!

**Comment by raphw** [comment]
It's been supported for a while, are you experiencing issues?

**Comment by OLibutzki** [comment]
@raphw The milestone assigned to this issue is misleading. As far as I can see it's not included in 1.12.22?

ASM has been updated with 1.14.3, so this is the version containg Java 21 support, right?

**Comment by alphaho** [comment]
@OLibutzki Cross checking the release timeline and the discussion in this issue, I think the JDK 21 support is from version [1.14.3](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.14.3)

**Comment by raphw** [comment]
I assume you are still using an outdated version.

**Comment by JavedAkramGit** [comment]
I updated it to 1.14.3 but faced a similar issue. Please assist in updating it in another way compatible with KeyCloak

**Comment by JavedAkramGit** [comment]
Not sure how am I gonna incorporate mockito while hosting keycloak on my local. The issue is that apparently keycloak requires an updated version of Byte-Buddy and the latest version from maven is 1.14 har file. Please assist with regards to that

**Comment by raphw** [comment]
You should be able to just update Byte Buddy which is published to Maven Central.

**Comment by antemo** [comment]
We are using Mockito 5.8.0 which brings in bytebuddy version 1.14.10
When trying to run tests on JDK 21 we get same error as mentioned before:

> Caused by: java.lang.IllegalArgumentException: Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property

How can we fix or avoid this issue?

**Comment by ascopes** [comment]
@antemo in my builds, I specify that flag on the Maven argline as a JVM property for the test runner.

```xml
<properties>
  <argLine>-Dnet.bytebuddy.experimental=true</argLine>
</properties>
```

I have stuff building on JDK 21 and JDK 22 EA, and haven't come across this issue.

I was meaning to remove that flag as it was a workaround from a while back but might leave it in if it is keeping builds stable.

**Comment by raphw** [comment]
Have you checked with your dependency manager if the version of Byte Buddy that is used is the right one? If another library then Mockito uses Byte Buddy, a different version might be resolved.

**Comment by listeningALF** [comment]
Where do I put this in? I am kinda lost.

> For now, please set -Dnet.bytebuddy.experimental=true
> 
> Then it will work. Proper support is coning soon.

**Comment by ascopes** [comment]
@listeningALF the JVM arguments for your test runner.

No idea about Gradle. In Maven you can just set a property called argLine.

**Comment by maxim5** [comment]
Shouldn't `mockito-inline` be updated in mvn central? It still depends on the old `bytebuddy`, hence doesn't work out of the box.

**Comment by listeningALF** [comment]
Hi

Cant follow, sry.

Freundlich grüsst

Alfred Nrejaj
079 606 06 36

Maxim Podkolzine ***@***.***> schrieb am Fr., 7. Juni 2024,
11:05:

**Comment by ascopes** [comment]
@FelixMarxIBM Mockito 5 uses the inline agent by default, so you need to just include mockito-core.

@listeningALF you need to set the JVM arguments for your test runner. I don't know what you are using so I can't provide further info, but you can most likely Google "<build system> set test JVM arguments" if you are not using Maven.

**Comment by rdwivedi** [comment]
> For now, please set -Dnet.bytebuddy.experimental=true
> 
> Then it will work. Proper support is coning soon.

saved my day. thanks a ton!!

**Comment by koraypeker** [comment]
@raphw it is working when set -Dnet.bytebuddy.experimental=true. But how can we solve this problem ? We are using spring-boot-starter-test 2.7.18 and we want to upgrade to java 21

**Comment by raphw** [comment]
I assume you have an old version of Byte Buddy on the class path. Newer versions support Java 21 without this flag.

**Comment by koraypeker** [comment]
> I assume you have an old version of Byte Buddy on the class path. Newer versions support Java 21 without this flag.

@raphw org.mockito.mockito-core:4.5.1 is using in spring-boot-starter-test 2.7.18 and net.bytebuddy.byte-buddy:1.12.9 is using in org.mockito.mockito-core:4.5.1

**Comment by iSE-Timur-Ugurlu** [comment]
Hey guys I am using Java21 with mockito-inline (latest version)
The experimental Flag can be used in Gradle like that:
```
tasks.named('test', Test) {
   jvmArgs("-Dnet.bytebuddy.experimental=true")
}
```

But I would like to not use this flag and use the latest bytebuddy version in mockito-inline

I can use this for example but it looks somehow ugly:
```
implementation ('org.mockito:mockito-inline:5.2.0'){
    exclude group: 'net.bytebuddy', module: 'byte-buddy'
}
implementation 'net.bytebuddy:byte-buddy:1.14.17'
```

**Comment by ascopes** [comment]
@iSE-Timur-Ugurlu for now the best bet is to use the flag. I've had it [set in my code](https://github.com/ascopes/java-compiler-testing/blob/main/pom.xml#L140) for ages now.

On Java 22, you'll also want to set `-XX:+EnableDynamicAgentLoading` to remove a warning about the deprecated behaviour of bytebuddy implicitly loading itself at runtime, as OpenJDK have plans to disable that ability without JVM flags by default in the future as well.

**Comment by raphw** [comment]
The Byte Buddy version is up to date in Mockito at least: https://github.com/mockito/mockito/blob/a1cdede8ffdc1e62b20daf32f36ccc49d6cf75a7/gradle/dependencies.gradle#L7

The enable dynamic loading must be enabled, this cannot be worked around.
