### ISSUE TITLE
Wrong method resolution with ArgumentTypeResolver

### ISSUE THREAD

**Issue by arnor2000** [raphw/byte-buddy#1397]
Hi,
I tried to create an implementation of `ByteBuffer` (which is excessively complex due to its closed design!) in a similar way of this [stackoverflow question](https://stackoverflow.com/questions/25864367/how-to-make-a-java-proxy-object-to-java-nio-bytebuffer-instance), but delegating to an object I instantiated:

```
final ChainedByteBufferInterceptor interceptor = new ChainedByteBufferInterceptor(left, right);

Class<? extends ByteBuffer> proxyType = new ByteBuddy()
        .subclass(ByteBuffer.class)
        .method(not(isDeclaredBy(Object.class))
                .and(not(isStatic()))
                .and(not(isPackagePrivate()))
                .and(not(isPrivate())))
        .intercept(MethodDelegation.to(interceptor))
        .make()
        .load(getClass().getClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
        .getLoaded();

return (ByteBuffer) ReflectionFactory.getReflectionFactory()
        .newConstructorForSerialization(proxyType, Object.class.getDeclaredConstructor())
        .newInstance();
```

I experienced exception `Cannot resolve ambiguous delegation of public abstract java.nio.ByteBuffer java.nio.ByteBuffer.putChar(int,char) to public java.nio.ByteBuffer com.lectra.data.revw.infra.buffer.ChainedByteBufferInterceptor.asReadOnlyBuffer() or public java.nio.ByteBuffer com.lectra.data.revw.infra.buffer.ChainedByteBufferInterceptor.compact()` where the method delegation miss the correct method `putChar(int,char)` in my `ChainedByteBufferInterceptor`.

I debugged the method delegation resolution mechanism to find out `ArgumentTypeResolver` (more precisely `PrimitiveTypePrecedence` in `resolveRivalBinding()`) prefers to select `putInt(int,int)`, discarding the correct `putChar(int,char)`.

Please take a look to this self explaining screenshot:
![2023-01-27-ArgumentTypeResolver-wrong-resolution](https://user-images.githubusercontent.com/5177793/215128629-785391e9-8f15-4413-a81e-40e1abddc525.png)

I solved my problem by changing the default order of resolvers which allows `MethodNameEqualityResolver` to select correct method before being discarded by `ArgumentTypeResolver`:
```
  .intercept(MethodDelegation
            .withEmptyConfiguration()
            .withResolvers(new MethodDelegationBinder.AmbiguityResolver.Compound(
                    BindingPriority.Resolver.INSTANCE,
                    DeclaringTypeResolver.INSTANCE,
                    MethodNameEqualityResolver.INSTANCE,
                    ParameterLengthResolver.INSTANCE,
                    ArgumentTypeResolver.INSTANCE))
            .withBinders(TargetMethodAnnotationDrivenBinder.ParameterBinder.DEFAULTS)
            .to(interceptor))
```

I don't know if something should be fixed in `ArgumentTypeResolver` or only the order of default resolvers like I did.

Anyway, thank you for your work!

**Comment by raphw** [comment]
How does `ChainedByteBufferInterceptor` look like? It seems to me that you might be looking for `MethodCall`, rather then `MethodDelegation`? This is if you are trying to redirect calls to another buffer instance.

**Comment by arnor2000** [comment]
If I understand correctly I can't use `MethodCall` because `ChainedByteBufferInterceptor` is not of type `ByteBuffer` (and cannot be because `ByteBuffer` constructors are package private) but have exactly same methods signatures, this is an extract:
```
public class ChainedByteBufferInterceptor {

    private final ByteBuffer left;
    private final ByteBuffer right;

    public ChainedByteBufferInterceptor(ByteBuffer left, ByteBuffer right) {
        this.left = left;
        this.right = right;
    }

    public int capacity() {
        return left.capacity() + right.capacity();
    }

    public int position() {
        return left.position() + right.position();
    }

    public byte get() {
        if (left.hasRemaining()) {
            return left.get();
        }
        return right.get();
    }

    public byte get(int index) {
        if (index < left.limit()) {
            return left.get(index);
        }
        return right.get(index - left.limit());
    }

[... 80 other methods of ByteBuffer...]
}
``` 
At the end, I want to have an object of type `ByteBuffer` but with the behavior of my `ChainedByteBufferInterceptor`, so I need to delegate all method calls (more than 80) to fake it.

Maybe I can use `MethodCall` and do the mapping myself but it is very convenient to use `MethodDelegation` and let ByteBuddy do the maping job!

**Comment by raphw** [comment]
You should be able to use `MethodCall` which offers a method using an `ElementMatcher`. Here, you would need to find a method of the targeted class that has a compatible signature (takes the same arguments).

**Comment by arnor2000** [comment]
I see, thank you for your explanations.
