### ISSUE TITLE
MemberSubstitution.Substitution.Chain always pushes the default value

### ISSUE THREAD

**Issue by I-Al-Istannen** [raphw/byte-buddy#1399]
Hey,

thanks for making ByteBuddy!

I am not quite sure if this is a *bug* per se, but I did not find it mentioned in the javadoc and it was a surprise to me. The `replaceWithChain` substitution is described as
> Replaces the matched byte code elements with a chain of substitutions that can operate on the same values as the substituted element.

However, before the chain is executed, parameters are stored on the stack (which isn't really intrusive) and then a default value is pushed on the stack. I am currently logging invocations and therefore replace certain invocations with "invoke logger method, then perform the original action". Due to the extra default-value push, the stacklayout is screwed up as there suddenly are *two* return values — one default pushed by ByteBuddy and the correct one.  
I am currently compensating this by checking the resulting type and explicitly pushing `pop`/`pop2` to undo ByteBuddys modification, but that feels like a bit of a hack.

What is the reason chains always push their parameters and default value on the stack? Pushing a default value sounds nice for stubbing, but I don't understand the utility with chains. If I understood the code correctly, a chain with no `StackManipulation` currently behaves the same as `stub()`, though with the side effect of storing the parameters in fresh stack slots?

I could also not find it in the docs. Did I just somehow miss that or is it currently not specified?

Have a nice day :)

**Comment by raphw** [comment]
The idea is that each chain element pushes a result value onto the stack and receives the previous. The first step receives the requested type and the last one needs to push it back. For example, A field read/write from the unit test is adjusted from:

    ALOAD 0
    ALOAD 0
    GETFIELD net/bytebuddy/asm/MemberSubstitutionTest$FieldAccessSample.foo : Ljava/lang/String;
    PUTFIELD net/bytebuddy/asm/MemberSubstitutionTest$FieldAccessSample.bar : Ljava/lang/String;
    RETURN

to:

    ALOAD 0
    ALOAD 0
    ASTORE 1
    ACONST_NULL
    POP
    ACONST_NULL
    PUTFIELD net/bytebuddy/asm/MemberSubstitutionTest$FieldAccessSample.bar : Ljava/lang/String;
    RETURN

This is by using:

    new MemberSubstitution.Substitution.Chain.Step.Simple(
                        NullConstant.INSTANCE,
                        TypeDescription.Generic.Sort.describe(String.class))

The chain stores away the aload 0 as the field is no longer read. It then pushes the default value of string (ACONST_NULL) for the first chain element. The chain element then pops the input value as the simple implementation does not care about it. It then pushes back a null constant as it is given as an argument. This concludes the substitution. If there was another step:

    new MemberSubstitution.Substitution.Chain.Step.Simple(
                        new TextConstant("foo"),
                        TypeDescription.Generic.Sort.describe(String.class))

We would end up with:

    ALOAD 0
    ALOAD 0
    ASTORE 1
    ACONST_NULL
    POP
    ACONST_NULL
    POP
    LDC "foo"
    PUTFIELD net/bytebuddy/asm/MemberSubstitutionTest$FieldAccessSample.bar : Ljava/lang/String;
    RETURN

Where the second step again ignores (pops) the argument to the chain and then pushes back a proper string.

**Comment by I-Al-Istannen** [comment]
Thank you for the *very* prompt response! :)

That makes sense. I missed that the simple chain step performs a removal for you, as I created my own `Step` and only used the `Simple` one as a `Resolution`. This of course does not result in `resolve` being called, leaving the value there.

WDYT about me making a PR adding something along the lines of your comment to the javadoc of `replaceWithChain` or the `Chain`? Your intent for the chain wasn't clear to me (I thought it was just meant as a way to replace it with a series of `StackManipulation`s). Maybe it would help others in the future too?

I am also totally fine with closing this issue and never speaking of it again, or you adding something yourself. Whatever you think is the easiest way forward for you :)

**Comment by raphw** [comment]
How did hou think? The stack manipulation must result in a vslue of the substituted type. Any stack manipulation on the chain is already able to leave the previous value on the stack.

Wouldn't it be a solution to not pop and to not push? Otherwise, you can dimply prepend a pop. That will be a trivial JIT-optimization.

**Comment by I-Al-Istannen** [comment]
I thought the chain was a way to compose a list of stackmanipulations, with you keeping track of the current top-of-stack yourself.

> Wouldn't it be a solution to not pop and to not push?

I do not push myself, my chain has a *single step* with a compound stack manipulation. This manipulation takes care of calling my logging method and then executing the original instruction. The value lying around on the stack is the default value pushed by the chain before it executes its steps.

> Otherwise, you can simply prepend a pop.

Yea, as said that's what I currently do. It felt a bit like a hack, but sounds fine now. The chain needs to push an initial value because it would need to special case the first step otherwise (and the user would need to know that the first step has no input).

I thought of the chain as a way to replace the invocation/write/read with a list of stackmanipulations of your choosing — not as a pipeline of independent steps which you gradually push the initial (default) value through.

**Comment by raphw** [comment]
I see, but in this case, you do not really need a `Step`, do you? Why not writing a regular substitution? Then you can either store the values on top of the stack or keep them there to simply invoke the method you wanted to call.

**Comment by raphw** [comment]
I added a few more standard steps to the implementation. If you look at the change sets and the unit tests for them, does it make more sense to you how I planned that this would be used?

**Comment by I-Al-Istannen** [comment]
> I see, but in this case, you do not really need a Step, do you? Why not writing a regular substitution? Then you can either store the values on top of the stack or keep them there to simply invoke the method you wanted to call.

Yea, that would have likely been nicer originally. The honest truth is probably that my IDE showed `Factory` as the parameter and I assumed it was the step factory and did not investigate further. Sorry for that.

> I added a few more standard steps to the implementation. If you look at the change sets and the unit tests for them, does it make more sense to you how I planned that this would be used?

Yea, they help a lot :) And they are quite nice building blocks.

I have replaced the method invocation instrumentation with this chain now:
```java
    return List.of(
        (assigner, typing, instrumentedType, instrumentedMethod) -> {
          boolean shouldTrace = mutationTraceTypes.contains(instrumentedType.getTypeName());
          if (!shouldTrace) {
            return new Nop();
          }
          return new ForInvocation(
              new ForLoadedMethod(TRACE_METHOD), Map.of(1, 0), assigner, typing
          );
        },
        OfOriginalExpression.INSTANCE
    );
```
Where `Nop` is a Step not doing anything and my misuse of your poor API to get a conditional step. That is still not the "thread one value through" usecase, but it is made up of multiple steps that should be sequenced. I think it's a lot nicer than what I did before.

The field one is a bit uglier, as I turn `(this.)foo = bar;` into a call like `log(this || null, this.foo, bar)`, i.e. `log(receiver, old, new)`. There is no real correspondence to `parameters` of the field write, so the `ForInvocation` step doesn't work here.
I am not sure if there is a nice way to make that one work, it sounds quite specialized. I've written my own and the chain looks alright:
```java
    return List.of(
        (assigner, typing, instrumentedType, instrumentedMethod) -> {
          boolean shouldTrace = mutationTraceTypes.contains(instrumentedType.getTypeName());
          if (!shouldTrace) {
            return new Nop();
          }
          return new TraceMethodStep(assigner, typing);
        },
        OfOriginalExpression.INSTANCE
    );
```

----

Thank you very much! You answered my question much more thoroughly than I expected or hoped for! :)
