### ISSUE TITLE
Gradle Plugin test classes include production classes (potential regression)

### ISSUE THREAD

**Issue by chemicL** [raphw/byte-buddy#1400]
In Project Reactor's debug agent, we're using ByteBuddy and have a gradle validation for proper source set instrumentation.

Starting from 1.12.21 our mock gradle setup started to fail.

Our test runs a mock gradle setup that validates that production instrumentation is applied, but the instrumentation does not happen for the test sources if not configured via appropriate ByteBuddy configurations (byteBuddy vs testByteBuddy).

https://github.com/reactor/reactor-core/blob/main/reactor-tools/src/buildPluginTest/java/reactor/tools/agent/ApplyingByteBuddyPluginGradleTest.java

The mock Gradle configuration is here: https://github.com/reactor/reactor-core/blob/main/reactor-tools/src/buildPluginTest/resources/mock-gradle/build.gradle

The class expected to be instrumented: https://github.com/reactor/reactor-core/blob/main/reactor-tools/src/buildPluginTest/resources/mock-gradle/src/main/java/demo/SomeClass.java

The class not expected to be instrumented: https://github.com/reactor/reactor-core/blob/main/reactor-tools/src/buildPluginTest/resources/mock-gradle/src/test/java/demo/SomeClassTest.java

Surprisingly, after running that configuration, the build output has both classes in the ../java/test/ output directory, as demonstrated by the screenshot:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/2554306/216653247-7fd5006f-5ae8-4a94-a3c3-de77fdd0fb97.png">

I would expect the runtime to use the ../java/main/ class and ../java/test not to contain the SomeClass.class file. The main directory contains a properly instrumented class file.

Thanks in advance for looking into this. If there is now a different way to configure this and it's not a bug, then apologies and I'd welcome an answer how to achieve what we had before.

**Comment by raphw** [comment]
I wonder if this has been an error that always existed but is caused by a different default, I am using Gradle `@InputFiles` as input to a task and it's those files that are considered. Maybe those input files contain production classes for test sources?

You can force the old behavior by setting `discovery = Discovery.NONE` in the `byteBuddy configuration.

**Comment by raphw** [comment]
Never mind. The plugin reuses the "raw" folder for the test classes. I have to create a different name for this folder which is based on the target name.

Also, this raises a question if the Maven defaults are meaningful for Gradle as the incremental compilation requires that Byte Buddy also applies the plugin if no transformations are configured for a goal.

**Comment by raphw** [comment]
Could you build Byte Buddy from master and try if the issue is solved?

**Comment by chemicL** [comment]
Thank you @raphw for the quick analysis and solution. I confirmed 1.12.23 does indeed work as expected with regards to our mock gradle setup. Great job 🥇
