### ISSUE TITLE
@Advice.AssignReturned.ToThrown is not working as expected

### ISSUE THREAD

**Issue by dogourd** [raphw/byte-buddy#1401]
I have an exit advice with `inline=false`, and I want to be able to discard specific exceptions thrown by the instrumented method (**javax.servlet.http.HttpServlet#service(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)**) here.   

Finally I found `@Advice.AssignReturned.ToThrown` this annotation, but it doesn't work as expected.   

Here is some information that I think is important.

1. **the Advice.AssignReturned post processor is explicitly registered.**
```java
adviceBuilder = adviceBuilder.with(new Advice.AssignReturned.Factory().withSuppressed(ClassCastException.class));
```
2. **The method signature and runtime debugging information of the exit advice.**
```java
@Advice.OnMethodExit(suppress = Throwable.class, onThrowable = Throwable.class, inline = false)
@Advice.AssignReturned.ToArguments(value = {
        @Advice.AssignReturned.ToArguments.ToArgument(value = 1, index = 0, typing = Assigner.Typing.DYNAMIC)
})
@Advice.AssignReturned.ToThrown(index = 1, typing = Assigner.Typing.DYNAMIC)
public static Object[] afterService(
        @Advice.Thrown Throwable thrown,
        @Advice.Argument(value = 0, typing = Assigner.Typing.DYNAMIC) HttpServletRequest request,
        @Advice.Argument(value = 1, typing = Assigner.Typing.DYNAMIC) HttpServletResponse response,
        @Advice.Enter(typing = Assigner.Typing.DYNAMIC) Object[] rs) throws IOException {
        // ....
        return result;
}
```
![image](https://user-images.githubusercontent.com/32627020/217244763-323e8449-7d41-44b2-b3a0-8c2fc3d89267.png)
3. **the exception doesn't go away.**
![image](https://user-images.githubusercontent.com/32627020/217245322-be7240a7-c806-4ba5-b6b9-ba98d6c9422d.png)

It is worth mentioning that `@Advice.AssignReturned.ToArguments` works great, exactly as expected.  
I found this problem on **`1.12.2`**, and got the same result on **`1.12.23`**.    
Using `inline=true` and internally assigning the `thrown` to null can achieve the purpose of eliminating exceptions, but I really need to use `inline=false` now

BTW, the javadoc for `@Advice.Assign Returned.ToThrow` is wrong, it looks like it belongs to `@Advice.AssignReturned.ToReturned`.

**Comment by dogourd** [comment]
I did some further investigation and found out that this might be a bug caused by copy code.
```java
class net.bytebuddy.asm.Advice.AssignReturned.ToThrown.Handler implements AssignReturned.Handler {
        public StackManipulation resolve(TypeDescription instrumentedType,
                                                         MethodDescription instrumentedMethod,
                                                         Assigner assigner,
                                                         ArgumentHandler argumentHandler,
                                                         TypeDescription.Generic type,
                                                         StackManipulation value) {
            if (instrumentedMethod.getReturnType().represents(void.class)) {
                return StackManipulation.Trivial.INSTANCE;
            }
            StackManipulation assignment = assigner.assign(type, TypeDefinition.Sort.describe(Throwable.class), typing);
            if (!assignment.isValid()) {
                throw new IllegalStateException("Cannot assign " + type + " to " + Throwable.class.getName());
            }
            return new StackManipulation.Compound(value,
                    assignment,
                    MethodVariableAccess.REFERENCE.storeAt(argumentHandler.thrown()));
        }
}

```
Here, the judgment of the return value of the instrumented method should be redundant.  
```java
if (instrumentedMethod.getReturnType().represents(void.class)) {
      return StackManipulation.Trivial.INSTANCE;
}
```

I added a custom annotation and copied the Handler implementation and removed the internal judgment on the return value, and now it works fine, but this should actually be a bug, right?

**Comment by raphw** [comment]
You are right, I fixed this on master!
