### ISSUE TITLE
ByteBuddy's `MemberSubstitution` rewrites invokespecial `super.foo()` to invokevirtual

### ISSUE THREAD

**Issue by I-Al-Istannen** [raphw/byte-buddy#1402]
Hey,

I am using `MemberSubstitution#OfOriginalExpression` to rewrite a method similar to:
```java
String foo() {
  return super.foo(); // this call is rewritten and replaced with the original expression
                      // this should be a no-op
}
```
The bytecode for this method will include an invoke special call
```java
        50: invokespecial #8                  // Method spoon/support/util/internal/ElementNameMap.put:(Ljava/lang/String;Lspoon/reflect/declaration/CtElement;)Lspoon/reflect/declaration/CtElement;
        53: checkcast     #5                  // class spoon/reflect/declaration/CtPackage
        56: areturn
```

The bytecode after modification, however, does not:
```java
        69: invokevirtual #8                  // Method spoon/support/util/internal/ElementNameMap.put:(Ljava/lang/String;Lspoon/reflect/declaration/CtElement;)Lspoon/reflect/declaration/CtElement;
        72: checkcast     #5                  // class spoon/reflect/declaration/CtPackage
        75: areturn
```

As far as I can tell this happens because `MethodInvocation#invoke` has no idea that this callsite was *statically* bound. It seems like this information was lost during `MemberSubstitution.Replacement.ForElementMatchers#bind` and the `Substitution`s no longer have any information about the invocation type.

----

I don't see an obvious way to work around that. Subclassing `MemberSubstitution` would allow me to change the replacement factory, but I would then need to re-implement the steps. I don't know if this is something you even want to support (maybe my usecase is a bit too low level), but it would be something nice to add to the `OfOriginalExpression` javadoc.

Maybe I was just stupid and missed something, but as far as I can tell this information is dropped too early for the Steps to access.

Have a nice day :)

**Comment by raphw** [comment]
This is indeed an oversight. I will have to see how I can retain this better. Currently, this information is not preserved as of now.

**Comment by raphw** [comment]
Alright, this needed some minor API changes, unfortunately, but the API is not widely spread according to some code search, so I think it's not a disaster to change it, comparing to it's current misbehavior.

**Comment by I-Al-Istannen** [comment]
Sorry it took me so long, but it seems to work nicely :)

Thank you!
