### ISSUE TITLE
Change parent of the class

### ISSUE THREAD

**Issue by charankamarapu** [raphw/byte-buddy#1403]
Hi , I have a class called Client, it is extending Connection class, I want to make a class called KConnection which extends Connection class, and I want that the parent of the Client should not be Connection but it should be KConnection using bytebuddy agent in the premain using AgentBuilder(). something like this 

```
new AgentBuilder.Default()
        .type(ElementMatchers.named("Client"))
        .transform(new AgentBuilder.Transformer() {
          @Override
          public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader) {
            return builder.superclass(KConnection.class);
          }
        })
        .installOn(inst);
```
Can anyone guide me over here..?

**Comment by skapral** [comment]
@charankamarapu Hi.

Writing here in response to your question in #691. Let me share here what I eventually ended up with.

https://github.com/skapral/pragmaticobjects/blob/master/oo-equivalence/equivalence-codegen/src/main/java/com/pragmaticobjects/oo/equivalence/codegen/ii/IIMarkAsEObject.java

The code above overrides a superclass of arbitrary class from `Object` to `EObject`. It's ugly, but it does the magic.

Hope it helps. Good luck.

**Comment by raphw** [comment]
Ehat problem do you experience with the suggested solution?

**Comment by charankamarapu** [comment]
In the solution suggested by @skapral  Class  X(super class - Object) is changed to Class X(super class - EObject) but my requirement is Class X(super class - Connection) is to be changed to Class X(super class - KConnection(super class - Connection)) . If I follow the approach given by @skapral I might end up with a recursive problem i.e super class of KConnection will be KConnection.

**Comment by raphw** [comment]
Of you change both classes superclass, how would you end up with a recursion? An agent will either instrument both classes at the same time (if retransformed) or once being loaded.

**Comment by charankamarapu** [comment]
Let’s take the same example currently I have 

Class BinaryClient extend Connection

now I am creating another class 

Class KConnection extends Connection

Now I want KConnection as parent of BinaryClient . So I follow the AsmVisitorWrapper solution which does nothing but wherever Connection is a super class it will be changed to KConnection .So what will be the parent of KConnection ? It will be KConnection again right which is not correct ? By the way I want the solution in AgentBuilder if possible.

**Comment by raphw** [comment]
You do of course need to ignore KConnection when you match classes. Do I miss something here?

**Comment by charankamarapu** [comment]
Got it . but If possible I want the solution in the AgentBuilder itself using transform ..?

**Comment by raphw** [comment]
You'd exclude the type there and apply the visitor within transform.

**Comment by charankamarapu** [comment]
Worked :) , Thanks @raphw and @skapral .
