### ISSUE TITLE
Can we support @AtInvoke like  aliibaba bytekit framework 

### ISSUE THREAD

**Issue by 98DE9E1F** [raphw/byte-buddy#1405]
add some Advice annotation to trace INVOKEVIRTUAL  information like  parameter、local variable 、return value

https://github.com/alibaba/bytekit/blob/master/bytekit-core/src/main/java/com/alibaba/bytekit/asm/interceptor/annotation/AtInvoke.java

**Comment by raphw** [comment]
I do not quite follow. What. is it you are tring to achieve?

**Comment by 98DE9E1F** [comment]
trace the outgoing call in method

**Comment by raphw** [comment]
You want to look into `AgentBuilder` and the JVM's support for Java agents.
