### ISSUE TITLE
Add JMH benchmark for cached creation of proxy classes

### ISSUE THREAD

**Issue by vlsi** [raphw/byte-buddy#141]
Current benchmarks examine `setUseCache(false)` mode. In other words, they examine the performance of "class generation".
Well, that does make sense, however in reality it makes much more sense to check how "cached" creation works.

In typical applications users tend to reuse generated classes (otherwise they'd end up in permgen/metaspace OOM), so the performance of "class reuse" is much more important.

As people read articles like https://zeroturnaround.com/rebellabs/testing-the-performance-of-4-java-runtime-code-generators-cglib-javassist-jdk-proxy-byte-buddy/ their immediate conclusion is "byte-buddy is 804.000/153.800 = 5.2 times faster than cglib when implementing an interface".

I think adding a `@Param{"true", "false"} boolean useCache` makes sense.

Having benchmark results for different number of `@Threads` would be good as well.

**Comment by raphw** [comment]
The benchmarks are exactly that: a measurement of class generation and a measurement of calling generated code. Byte Buddy does voluntarily not add a built-in cache as I consider this pattern flawed.

In most applications using Byte Buddy - e.g. Mockito - a key for a cached class can be generated easily and with minimal memory consumption as a mapping from the original class to its generated proxy. This simple cache is of course more efficient as the one built into cglib as it makes an assumption. (To be fair, Javassist only added the cache to supply an easy migration path from cglib and does not offer such a cache for the core Javassist API.) In more compley scenarios, using a fully fledged cache like Caffeine is again much more efficient and customizable so this should be the way to go.

Finally, I do not think such a benchmark would even make sense if there was something to compare. How many cache misses should I emulate? If the cache was for example always hit like for example by adding a `@Param` for triggering the built-in caches in the existing bechmarks, the JVM would probably create a fast-path for reading the previously generated class and erasing all other paths with uncommon traps. In the end, a benchmark is only as good as its interpretation and measuring cache efficiency is rather complex on this end.

As for my personal use of cglib before I created Byte Buddy, I always disabled the caches and replaced them by something different.

**Comment by vlsi** [comment]
>Byte Buddy does voluntarily not add a built-in cache as I consider this pattern flawed

You'd better make that explicit then. You never say "users should cache proxy classes on their own".
I've listened to your JFocus "making java more dynamic" and you suggest "new ByteBuddy()...etc" kind of stuff.

Proper caching is not something that can be added later as user realizes "(s)he needs to cache that".


https://github.com/mockito/mockito/blob/9c51378cee8d9e5173355d59eae8b5fcc0b906d8/src/main/java/org/mockito/internal/creation/bytebuddy/CachingMockBytecodeGenerator.java#L25

Is just plain old lock. It does not scale. Of course you could say Mockito does not need high performance from `CachingMockBytecodeGenerator.get` (I might agree), however, I would argue, it is not that easy to achieve read scalability & class unloading ability.


>Finally, I do not think such a benchmark would even make sense if there was something to compare. How many cache misses should I emulate? 

Here: https://youtu.be/80wCytGEY1g?t=2659 you compare "good approach for one library vs bad approach for another one". What sense does it make?
Can you make that more like an apple vs apple comparison?
What conclusion should regular user end up with after staring at that benchmark slide? I know you say something re 3b, but please refactor the slide.

> the JVM would probably create a fast-path for reading the previously generated class and erasing all other paths with uncommon traps

Of course there are unlimited number of benchmarks to make and unlimited amounts of paint to dry.
However, a mere "how fast does it take to create a single proxy bean" would make a lot more sense than "how long does it take to generate a class".
Note: you might even contrast that different libraries favor different approach, so "in order to create that proxy, you need this piece of code for BB, that for CGlib, etc".

**Comment by raphw** [comment]
Byte Buddy creates `Class` instances and is not a proxy `Object` factory like cglib is. I would not know why anybody would expect Byte Buddy to cache anything and it has never been a point of confusion in practice.

I agree that the Mockito solution can be improved but I do not have the time currently. There is no performance regression so we went for the easy solution and as you say, its not much of a requirement to scale.

See, I understand that you are invested in the cglib caches and props for that. I argue that the slide could be explained in greater detail but in the reality of a conference talk, you do not always have the time for everything. The idea is: Byte Buddy is much faster, especially the generated code when its runs. And I do not hear myself saying *good approach for one library vs bad approach for another one* in that video so I do not know what you mean by that.

**Comment by vlsi** [comment]
> I agree that the Mockito solution can be improved but I do not have the time currently

I wonder how other projects solve the problem.

> I agree that the slide could be explained in greater detail but in the reality of a conference talk, you do not always have the time for speaking out everything you try to say

Have you considered splitting the slide into several ones?
Having several charts would help to understand the meaning and reduce the time you talk the info through at the same time.

> Byte Buddy is much faster, especially the generated code when its runs.

Ah, that is the next comment: it would be great if you could add not just fact that "one is slower", but the justification on _why_ is it slow. It would be great if that is inherent to API that cglib uses (e.g. idioms from the past that never apply to modern world, yet you either support old APIs or make backward-incompatible change).

>I do not hear myself saying good approach for one library vs bad approach for another one in that video so I do not know what you mean by that.

Cglib had class cache for ages. What I did was just to make that cache scalable for read-heavy kind of workloads.
Lots of users adopted "use new Enhancer()....create()" as a factory. Note: I do not think many of them use `cglib.Factory` interface. They just rely on `new Enhancer()....create()` way to create objects.

The way you compare "how log does it take to generate class" is not fair from cglib's point of view. I mean lots of users would have `.create()` in mind as you mention cglib.
While the wording on the slide is exact, it is misleading, as it just does not reflect typical cglib usage pattern.

Here's how Spring Framework uses cglib: https://github.com/spring-projects/spring-framework/blob/183594207fbb447e1b59262b4469f2aefbb8a3ec/spring-aop/src/main/java/org/springframework/aop/framework/CglibAopProxy.java#L179-L203

They just leverage cglib's cache and it is good enough for them so they can skip implementing their own cache.

That is what I mean by "you compare wrong cglib approach with good ByteBuddy approach".

**Comment by vlsi** [comment]
> if I wrote a migration guide, I would mention this but again I did not yet have the time, its a free time project

I wonder if you are going to reuse the slides for your Jokerconf talk. If that is the case, please consider splitting the benchmark slide into several ones.

**Comment by raphw** [comment]
As a final answer to this, I can only summarize what I already said:

1. A benchmark is only as good as its hypothesis: if I compare how long it takes cglib to return an instance of a cached class to how long it takes Byte Buddy to create this class freshly every time, what would this benchmark prove? That using a cache is more efficient than not using one if you handle expensive objects? I think that is obvious.

2. Byte Buddy allows you to create a class of any property up to the creation of custom byte code. cglib does not. Therefore, there is no comparing "the wrong approach of cglib" with Byte Buddy. cglib is a different library - it creates proxies only - Byte Buddy can create any byte code pattern that javac emits (and more). For the benchmark, I extracted scenarios where all libraries do a very similar thing. In my eyes, this is the only type of benchmark that makes sense. (And even here the comparison is broken. Byte Buddy processes generic type information, type annotations, default interfaces etc. None of this is done by cglib and Javassist.)

3.The benchmark is there to look into the performance of the actual code generation and its runtime. The truth is, if you want a performant cache with explicit controls, you should use a library that specializes on that; even if you use cglib. This does not only allow you to chose proper eviction strategies (if needed) but also gives you the opportunity to choose a good enough hash key where cglib only offers a opt-out global cache. And if your application is simple, it is probably sufficient to stick previously created instances into a `ConcurrentMap`. 

Historically, cglib added the cache to mimic the Java proxies which have such trivial keys. Javassist only added the cache for its "migration API" but not to its standard API to ease the migration of cglib. When I created Byte Buddy I wanted to create a code generation library that does one thing and does it well. This is what the benchmark is for and nothing more. Again, I sympathise that you want to see your caching solution excell here, but this is not the point of this benchmark.

As for Jokerconf, I will change my slide set quite a bit as I was asked to talk a bit more about the performance implications of code generation libraries. I will also talk a bit more about what I think is wrong with cglib and Javassist which I used for years before creating Byte Buddy.

**Comment by vlsi** [comment]
> Again, I sympathise that you want to see your caching solution excel here, but this is not the point of this benchmark.

I'm afraid you don't get me. I don't say "cglib all the things".
Currently you claim "cglib is just slow" and use not that fair approach to compare.

It would be much better if you said "cglib is for proxies and cache keys only", and provided fair comparison for the cases you do compare.

>a code generation library that does one thing and does it well. This is what the benchmark is for and nothing more

The problem is end users require not just code generation, but they need something more high level. For instance they might need to implement `@Secure` that adds a security check right into user-provided class/interface. That kind of benchmark (+analysis) makes more sense than the one that measures "how fast can we call a method that always returns null".

**Comment by raphw** [comment]
I am afraid it is the other way round. What you suggest is a different thing. I am trying to compare base-overheads in my (micro!) benchmark, not "typical use cases". I am saying that cglib is slow because it is. In order to make a comparison, I would need to drag in a third-party cache and write a lot of code to implement some form of library. There would be a lot of screws to tweak this benchmark in favour of either one of the libraries and I do not think this is a valid approach to benchmarking.

Your argument basically is: if you use Byte Buddy exactly as you would use cglib, cglib is slower. My point is: this is not how you should use Byte Buddy. If you are using Byte Buddy correctly, however, you get better results. Again, this is something different than a microbenchmark where you look at something that is actually fair to compare.
