### ISSUE TITLE
How to run agent with 3rd denpendices or custom class?

### ISSUE THREAD

**Issue by Restlol** [raphw/byte-buddy#1410]
Thanks for your great work on this wonderful project!  
as title ,I use some 3rd jar  / custom java class in my `Advice`, it does not work well, the code as follows:

1.  the agent premain
```
AgentBuilder agentBuilder = new AgentBuilder.Default()
        .ignore(none())
        .with(RETRANSFORMATION);
        agentBuilder.type(nameMatches("java.io.File"))
        .transform((builder, typeDescription, classLoader, module) -> builder.visit(Advice.to(MyAdvice.class)
                    .on(isConstructor())))
        .with(new AgentBuilder.Listener() {
                    @Override
                    public void onDiscovery(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded) {}

                    @Override
                    public void onTransformation(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module, boolean loaded, DynamicType dynamicType) {}

                    @Override
                    public void onIgnored(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module, boolean loaded) {}

                    @Override
                    public void onError(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded, Throwable throwable) {
                        System.out.println("onError: " + typeName);
                        throwable.printStackTrace();
                    }

                    @Override
                    public void onComplete(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded) {}
                })
                .installOn(inst);
```
2.  the Advice
```
   @Advice.OnMethodEnter
    public static void onMethodEnter(@Advice.Origin String methodName, @Advice.AllArguments Object[] args) {
        new Gson();   //use Gson!
        System.out.println("methodName:" + methodName);
    }
```
3.  when i run my project the agent,it report exception:
![image](https://user-images.githubusercontent.com/68416238/221597154-61131835-5e7a-42af-9d77-01209a7178f0.png)

I guess the gson couldn't be accessible by bootstrap classloder?
so i add these code ,but it still does report exception
```
  JarFile jarFile = new JarFile("My agent's path");
   inst.appendToBootstrapClassLoaderSearch(jarFile);
```
,

I put that code  here:
```
    AgentBuilder agentBuilder = new AgentBuilder.Default()
                .ignore(none())
                .with(RETRANSFORMATION);
       // before installon
        JarFile jarFile = new JarFile("My agent's path");
        inst.appendToBootstrapClassLoaderSearch(jarFile);

        agentBuilder.type(nameMatches("java.io.File"))...
```
it shows :

![image](https://user-images.githubusercontent.com/68416238/221599739-1e5b1e92-9c99-4f26-b5da-f591ddca9fbd.png)

I put that code  here :
```
             ....
             })
                .installOn(inst);
        // after installon
        JarFile jarFile = new JarFile("My agent's path"); 
        inst.appendToBootstrapClassLoaderSearch(jarFile);
```
it shows:
```
onError: java.lang.Throwable$WrappedPrintStream
onError: java.lang.Throwable$PrintStreamOrWriter
onError: java.util.IdentityHashMap$KeySet
FATAL ERROR in native method: processing of -javaagent failed
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: com/google/gson/Gson
	at java.io.File.<init>(File.java:275)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at org.example.App.premain(App.java:46)
	... 6 more
Exception in thread "main" 
```
if i only use `appendToBootstrapClassLoaderSearch` with Gson's path, 
```
       JarFile jarFile = new JarFile("D:\\develop-tools\\mvn-repository\\com\\google\\code\\gson\\gson\\2.9.0\\gson-2.9.0.jar");
        inst.appendToBootstrapClassLoaderSearch(jarFile);
```
it will shows :

![image](https://user-images.githubusercontent.com/68416238/221749476-28139d13-8271-457b-ac96-9756b254785b.png)

BTW, I found a interesting thing that  I don't add the  `appendToBootstrapClassLoaderSearch` code, just use a JVM option : `-Xbootclasspath/a:/path/to/myAgent.jar`, it works well
I'm  confused,

**Comment by raphw** [comment]
By default, advice inlines code into the target class's class loader. This code will then only be able to see classes that are available on the class loader of the instrumented code.

As for your boot issue, this happens as you inject code into the boot loader after you already loaded some classes from the agent's loader, what can confuse class loading.

To get around this, add some few classes to the boot loader. You can then for example set a static field in these classes and reference this from the `Advice`. This way, you avoid all these issues while not breaking loader boundaries.

**Comment by Restlol** [comment]
> By default, advice inlines code into the target class's class loader. This code will then only be able to see classes that are available on the class loader of the instrumented code.
> 
> As for your boot issue, this happens as you inject code into the boot loader after you already loaded some classes from the agent's loader, what can confuse class loading.
> 
> To get around this, add some few classes to the boot loader. You can then for example set a static field in these classes and reference this from the `Advice`. This way, you avoid all these issues while not breaking loader boundaries.

**Comment by Restlol** [comment]
So happy to get your reply.
 I might not get  all your meaning since I'm a liitle  lack of JVM's knowledge . I 'll  describe what i've tried
first of all,  Please let me briefly describe my needs

1. enhance constrcutors of  the class `java.io.File`
2. use  3rd jars or my custom class doing  sth before or after calling the constructors 

> To get around this, add some few classes to the boot loader. You can then for example set a static field in these classes and reference this from the Advice. This way, you avoid all these issues while not breaking loader boundaries.

**How to add add some few classes to the boot loader ?**
still use `appendToBootstrapClassLoaderSearch`?  it's the only way i can think of..
1. i create an empty project as 3rd jar, and create a new class named `Foo` ,waiting to be refrenced  from  my `Advice`
2.
  ```
        JarFile jarFile = new JarFile("path:/loadByBootLoader.jar");
        inst.appendToBootstrapClassLoaderSearch(jarFile);
  ```
3. `Advice:`
```
Class.forName(`com.my.Foo`)
``` 
does my action accord with your meaning?

from the aspect of results , 
when i use command line `java -javaagent:my-agent.jar -jar target.jar ` it works well
when i use IDEA and add vm option ` -javaagent:my-agent.jar ` it reports exception:
![image](https://user-images.githubusercontent.com/68416238/222386316-f91838f0-30c5-4eb5-92a2-ca4ec5b98c04.png)

**Comment by raphw** [comment]
Is IDEA adding some form of agent to the command line? This seems like another tool interfering.

**Comment by Restlol** [comment]
What I've tried is right or not to add some few classes to the boot loader?  :)  or is there a better / general way?

**Comment by dogourd** [comment]
In IDEA 2022.3.2, try to open `Edit Configurations` and change the `shorten command line` option.
