### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by JimmyAndZzZ** [raphw/byte-buddy#1411]
hi，i want to deploy a springboot application，when i user fat jar it will report an exception

for example i want to proxy LoggingEvent's Construct，it will report java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.LoggingEvent

![image](https://user-images.githubusercontent.com/26839069/221790134-e64bc499-77cf-46ec-8932-a2d4d842de1d.png)

**Comment by raphw** [comment]
I am not sure if this is really related to Byte Buddy, are you running an agent?

It seems like you are missing some dependencies from the class path. If you run an agent, make sure you include all dependencies in a fat jar.

**Comment by JimmyAndZzZ** [comment]
@raphw sry i replied too late
i want to user  Byte Buddy finish agent in springboot fat jar, but i use provider scope in maven's dependency , when i start springboot application it will report this  error, but this class's dependency  lib in fat jar

so can i use agent in fat jar to reference applicaiton's lib class

**Comment by raphw** [comment]
You can, but you need to make sure that code is run from the correct class loader. For example, `Advice` inlines its code by default.
