### ISSUE TITLE
ClassNotFoundException: $ByteBuddy$ModuleSupport

### ISSUE THREAD

**Issue by JoeJoe1989** [raphw/byte-buddy#1412]
Hi,

I was testing bytebuddy 1.12.19 (supposed to be JDK 17 compatible according to release note) against Open JDK 17 runtime and got an ClassNotFoundException **net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport**. Such exception did not occur when testing against Open JDK 11 runtime. Just wonder if you have any idea? Thanks. Below is the stacktrace.

![image](https://user-images.githubusercontent.com/6061826/222804325-8c524e55-8afc-4c2d-af59-e48b7a7ddd35.png)

**Comment by raphw** [comment]
No issue I know of. Byte Buddy is built against JDK 17.
