### ISSUE TITLE
bytebuddy typepool memory leak

### ISSUE THREAD

**Issue by 1057105012** [raphw/byte-buddy#1413]
When I use bytebuddy, I found an extreme scenario, if typePool opens the cache, there will be two problems
1. During transform, ignore is executed after the typepool is acquired, so no matter whether ignore is executed or not, it will cause the cache to be occupied
2. When restransform collects classes, it will use typePool to encapsulate classes, which will also occupy the cache at this time
I think ignore can be preceded by these two steps in advance, such as simple matching of className and classloader does not require typePool support
This phenomenon will cause serious problems in special dynamic class loader scenarios, because the typePool will always grow slowly no matter whether it is ignored or not, and then trigger a fullGC, causing the application to freeze. If you add a cleanUp thread, you can solve this problem problem, but cleanUp will also cause some lock operations that should be avoided in the transform phase
I think it is better to adjust the execution position of bytebuddy ignore

**Comment by raphw** [comment]
Not sure if I follow.

The agent builder does not keep any references beyond a single class's transformation. You can install custom caches, what is recommended, but then you need to take care of sensible eviction.
