### ISSUE TITLE
`transform-runtime` should find ByteBuddy plugins declared in `provided` scope

### ISSUE THREAD

**Issue by odrotbohm** [raphw/byte-buddy#1414]
## Context

1. I would like to declare some plugin for ByteBuddy as an ordinary project dependency to be able to BOM-control its version. To not leak that plugin into the packaged application, I would like to declare it as `provided`.
2. There are some libraries that provide code the plugin weaves into the application's code. Ideally, I would like to be able to declare those in `runtime` scope, as it's code that developers should by default not code against themselves.

## Problem

I cannot get to a declaration arrangement that satisfies both criteria. I have tried two ways:

1. The standard `transform` goal does not see `runtime` scoped dependencies, i.e. misses the glue code to be woven into application code.
2. Using the `transform-runtime` goal misses my plugin dependency declaration in the first place, as that is declared `provided` and thus not present in `runtime` scope. That said, there's no other reasonable scope I could declare the plugin in to let it be included in the ByteBuddy transformation. The only option here would be to declare it as a dependency of the build plugin, but that would then require me to repeat the version of the artifact, which breaks requirement 1 above.

## Ideas

I wonder if the inspected scope for the *plugin* detection can be different from the classpath used for the transformation.
Ideally, the `transform-runtime` step would still try to find the plugin in the compile scope (and thus include `provided`-scoped dependencies), but then run the actual transformation against Maven's runtime classpath.

I know too little about the different levels of granularity that Maven exposes to find and run things, but do you think that could/would work?

**Comment by raphw** [comment]
I added a new goal, *transform-extended*. Maven's API does not offer a good API for this, but I see the need, so I reimplemented some of Maven's internal resolution logic. Let me know if this is what you were looking for, you'd need to build Byte Buddy from *master*.

**Comment by odrotbohm** [comment]
Works like a charm. Would be nice if you could add the new goal to the `lifecycle-mapping-metadata.xml` to keep Eclipse happy.

**Comment by raphw** [comment]
I added it. I'll do a release soon.
