### ISSUE TITLE
Cannot resolve symbol 'ByteBuddyAgent'

### ISSUE THREAD

**Issue by sherkat69** [raphw/byte-buddy#1415]
hi

I'm an absolute java beginner and i want to start using ByteBuddy.
I'm using ByteBuddy 1.14

currently i want to do this:
Instrumentation inst = ByteBuddyAgent.install();
Class[] loadedClasses = inst.getAllLoadedClasses();

but i get this error:
Cannot resolve symbol 'ByteBuddyAgent'

and there's no "net.bytebuddy.agent.ByteBuddyAgent" path in the ByteBuddy jar file.

**Comment by raphw** [comment]
It's a different jar, *byte-buddy-agent.jar*

**Comment by sherkat69** [comment]
i want to call a method from a loaded class of one app, from another app without making any new instances.
is it doable with byte buddy?

**Comment by raphw** [comment]
If I understand you correctly: you want to inject a code snippet into a target app where classes are only available in the targeted app. If this is the case, yes. But you need to target the relevant loader and bundle all of "your" dependencies in the injected jar.

**Comment by sherkat69** [comment]
is any source or tutorial to do this?

**Comment by raphw** [comment]
Not within the scope of Byte Buddy. I assume that your IDE or build is not setup correctly. If you choose the right imports and class path dependencies, everything should work out as expected. Otherwise, this would be a very known issue.
