### ISSUE TITLE
Consider providing a @Advice.AssignReturned.SkipOn annotation for use with enter advice

### ISSUE THREAD

**Issue by dogourd** [raphw/byte-buddy#1417]
ByteBuddy currently achieves the goal of skipping the target method by specifying the `skipOn` parameter to a specific type in the `@Advice.OnMethodEnter` annotation. However, this approach is not sufficient in certain special cases, such as when we need to meet the following requirements simultaneously:

1. We need to reallocate the parameter list of the target method, which can be accomplished using the `@Advice.AssignReturned.ToArguments` annotation, which requires us to return **an array**.
2. We need to perform some business logic in the enter advice and pass it to the exit advice, which can be accomplished using `@Advice.Enter`.
3. We need to skip the execution of the target method during business processing.

To address this, I can define a special type to store business processing data and set it to `skipOn`, but this cannot meet the requirement of returning **an array** type in condition 1. Alternatively, we can use `skipOn = Advice.OnDefaultValue.class` and return null, but this is not conducive to passing business data to the exit advice.

As a result, I would have to add additional advice definitions or add a WeakMap to save business data mappings.

An ideal solution would be to provide an `@Advice.AssignReturned.SkipOn` annotation with `index` and `onType` attributes, allowing us to determine whether to skip the target method by judging a certain index in the array.

**Comment by raphw** [comment]
Fair point. I will address this!

**Comment by raphw** [comment]
There is now a `skipOnIndex` and `repeatOnIndex` which can solve this.
