### ISSUE TITLE
Is there an API to get all instrumented methods?

### ISSUE THREAD

**Issue by FrankChen021** [raphw/byte-buddy#1418]
Hi @raphw 

By listening on `AgentBuilder.Listener#onTransformation`, we can know if the clazz has been instrusmented. But if I want to know which methods have been instrumented in this class, is there any API in byte-buddy to do so?

chatgpt suggests me to add a customer annotation to the target method during transformation, and then in the onTransformation method, we can check if the methods on the given type have been annotated by that customer annotation. I think it's less efficient, and want to know if there's a better way to do so?

**Comment by FrankChen021** [comment]
Thank you @raphw for the response. 

I don't know where did the chatGPT get the idea, and solution it suggested is really a little bit wired.

By looking through the byte-buddy API, I came across this solution.

before

```java
                    builder = builder.visit(Advice.withCustomMapping()
                                                  .to(MethodDecoratorAdvice.class)
                                                  .on(matcher);

```

after

```java
                    Advice advice = Advice.withCustomMapping()
                                          .to(MethodDecoratorAdvice.class);
                    builder = builder.visit(new AsmVisitorWrapper.ForDeclaredMethods().invokable(matcher,
                                                                                                 advice, 
                                                                                                 new Visitor()));

        static class Visitor implements AsmVisitorWrapper.ForDeclaredMethods.MethodVisitorWrapper {

            @Override
            public MethodVisitor wrap(TypeDescription instrumentedType,
                                      MethodDescription instrumentedMethod,
                                      MethodVisitor methodVisitor,
                                      Implementation.Context implementationContext,
                                      TypePool typePool,
                                      int writerFlags,
                                      int readerFlags) {

                // here the instrumentedMethod is what I want to get
                return methodVisitor;
            }
        }

```

**Comment by raphw** [comment]
Did you consider remembering all this in a map?

**Comment by FrankChen021** [comment]
> Did you consider remembering all this in a map?

Yes, above code is just an illustration.

**Comment by FrankChen021** [comment]
Hi @raphw , I'm adding this to my project, and there's a problem.

In my Advice, there're some customized annotations and resolvers, for example

```java
public class AfterAdvice {

    @Advice.OnMethodEnter
    public static void onEnter(
        @AdviceAnnotation.Name String name,
        @Advice.This(optional = true) Object target
    ) {
        ....
    }
}
```

and the corresponding resolver for above annotation is defined as 

```java
  public static class NameResolver implements Advice.OffsetMapping {
      private final String name;

      public NameResolver(String name) {
          this.name = name;
      }

      @Override
      public Target resolve(@Nonnull TypeDescription instrumentedType,
                            @Nonnull MethodDescription instrumentedMethod,
                            @Nonnull Assigner assigner,
                            @Nonnull Advice.ArgumentHandler argumentHandler,
                            @Nonnull Sort sort) {
          return new Target.ForStackManipulation(new JavaConstantValue(JavaConstant.Simple.ofLoaded(name)));
      }
  }
```


And now the above annotation and resolver is binded to an Advice

```java
    Advice advice = Advice.withCustomMapping()
                                   .bind(AdviceAnnotation.Name.class, new AdviceAnnotation.NameResolver(some_variable))
                                   .to(AfterAdvice.class);
    builder = builder.visit(new AsmVisitorWrapper.ForDeclaredMethods().invokable(matcher,
                                                                                             advice, 
                                                                                             new Visitor()));
```

Now the problem is, in the visitor, I want to access the `NameResolver` instance that is binded to the Advice class.
The NameResolver is kept in the `offsetMappings` field of Advice object, but there's no way to access this object directly.

```java
 static class Visitor implements AsmVisitorWrapper.ForDeclaredMethods.MethodVisitorWrapper {
    @Override
    public MethodVisitor wrap(TypeDescription instrumentedType,
                                MethodDescription instrumentedMethod,
                                MethodVisitor methodVisitor,
                                Implementation.Context implementationContext,
                                TypePool typePool,
                                int writerFlags,
                                int readerFlags) {

        // the question is how can I access the NameResolver instance here????
        return methodVisitor;
    }
}
```

The offsetMappings object can be accessed by following object access chain,
```
((Advice.AdviceVisitor.WithExitAdvice.WithoutExceptionHandling) methodVisitor).methodEnter.this$0.offsetMappings
```

But the problem is `AdviceVisitor` and its nested classes are defined as `protected` which is not visible outside of the package, and for `methodEnter`, it does not explicitely define a method to access its parent offsetMappings but has to access 

Now I can access the `offsetMappings` object by reflection. But I wonder if there's better way to do it? 
If we can define `AdviceVisitor` as public and keep a reference to `offsetMapping` to the `methodEnter` instance, I think we can do it by such code:

```
```

**Comment by raphw** [comment]
If you wanted that, you would need to implement a custom form of state propagation. For example, add the state to a map from the resolver and read it back from the visitor. I would not want to expose this as I consider it an implementation detail.

**Comment by FrankChen021** [comment]
You're absolute right. Actually from resolver, the instrumentedType and instrumentedMethod can be both accessed, that's enough to achieve the goal. I didn't realise this way. Thank you very much for this helpful advice.
