### ISSUE TITLE
Add ability to dump generated by ButeBuddy classes

### ISSUE THREAD

**Issue by vlsi** [raphw/byte-buddy#142]
It would be good if there was a system property that would trigger saving the generated classes in some debug location.

**Comment by raphw** [comment]
You can already store the classes using the `DynamicType` API. When using an `AgentBuilder`, you can register a `Listener` to access this dynamic type, If you really need this ability.

**Comment by vlsi** [comment]
What if I want to debug third-party application?

**Comment by raphw** [comment]
In this case, the `VerifierError` typically suffices for debugging purposes. Otherwise, I rather take a reproduction of the problem.

**Comment by vlsi** [comment]
That's a pity you mark debug-ability issue as wontfix.

Currently one can easily capture Spring's & Guice's generated classes via `-Dcglib.debugLocation=/...`
If they migrate to BB, class dump will be impossible.

**Comment by raphw** [comment]
I would probably use some different form of control, not a system property. I have thought about this but there are some problems with a simple "dump" that I need to think about first before committing myself to a solution.

**Comment by raphw** [comment]
Also, please do not think that I simply dismiss your solution, I appreciate the hint but I currently need to bundle my efforts to make sure I can continue to maintain this library which has gained quite some users over the last year. I am therefore always careful to add another debugging option as a simple class dump often does not expose a problem.

**Comment by vlsi** [comment]
Well, closing an unresolved issue that is likely to be resolved one day is something new for me in OSS development.

Typically, they leave "starter/for-newbies/easy" kind of tickets open so those who want to contribute can pick something easy up.

**Comment by raphw** [comment]
As I said, it is not trivial.

**Comment by raphw** [comment]
I decided to add this feature nevertheless. My main concern is to create an easy mechanism for an attacker to extract class files that Byte Buddy creates but I assume that in this case an attacker either controls the application where an attack is trivial or a security manager is in place.
