### ISSUE TITLE
What is the simplest way to reuse an existing Implementation with parameters computed based on matched methods?

### ISSUE THREAD

**Issue by ritzow** [raphw/byte-buddy#1421]
I'm currently using the following to generate an invokedynamic call:

```java
InvokeDynamic.bootstrap(method, List.of(classDataAt(1)))
```

(classDataAt is just a JavaConstant.Dynamic.bootstrap(...) call)

I would like to also pass an integer constant in the List.of(...) call above, based on the name or properties of the method currently being implemented (for example `List.of(classDataAt(1), JavaConstant.Simple.ofLoaded(Integer.toString(methodName.substring(1))))`). Is there any way to do that without reimplementing `InvokeDynamic.bootstrap(...)`?

**Comment by raphw** [comment]
Simply pass `1` as an argument? It is a constant pool value and can be passed to a bootstrap function.

**Comment by raphw** [comment]
Only if you match by both names and add two Implementations with each constant.

But why not pass the name to the bootstrap function and resolve it from there?
