### ISSUE TITLE
Would it be possible to consider opening up the `net.bytebuddy.asm.Advice.Delegator` API?

### ISSUE THREAD

**Issue by dogourd** [raphw/byte-buddy#1423]
I have recently been reading about the support for the `net.bytebuddy.asm.Advice.OnMethodEnter` annotation in byte-buddy, and I have noticed that it currently only supports the modification of **static methods**. This is likely because byte-buddy currently only provides two implementations of the `net.bytebuddy.asm.Advice.Delegator.Factory`:  
- `net.bytebuddy.asm.Advice.Delegator.ForDynamicInvocation.Factory`
- `net.bytebuddy.asm.Advice.Delegator.ForRegularInvocation.Factory`

Here are some thoughts on some use cases:    
- We need the advice to be loaded and executed by a specific class loader.  

From this issue [1374](https://github.com/raphw/byte-buddy/issues/1374), we already know that we can achieve this goal by using `Advice.bootstrap(xx)`. However, since the `invokedynamic` instruction was not introduced until java7, it seems that we cannot use byte-buddy to achieve this goal before java7 (or can we?).  

Given the above specific use case, could byte-buddy consider opening up the `net.bytebuddy.asm.Advice.Delegator` API? This would allow users to define a `Delegator.Factory` implementation that is similar to `net.bytebuddy.asm.Advice.Delegator.ForDynamicInvocation`. It would call a static method from a **bootstrap class**, but instead of returning a `CallSite`, it would return an advice instance object. This instance method could be loaded and instantiated by any class loader, and could be singleton or prototype, depending entirely on the implementation of the static method. After returning the advice instance object, we could then use `invokevirtual` to call our custom advice, and this would no longer require that `net.bytebuddy.asm.Advice.OnMethodEnter` must always annotate a static method.

Is this idea possible?

**Comment by raphw** [comment]
Traditionally, this is difficult as the inling mechanism was built around offset mappings that require static dispatch to have the offsets right. It would need loads of adjustment to open up for this. Then again, this could be interesting even for the invokedynamic dispatch, as it generally does not care about the invocation form either.

Then again, for your suggestion: couldn't you just emulate this via reflection? The instrumented class would otherwise even need to know the type of the dispatched method.

**Comment by dogourd** [comment]
Yes, I could add only one advice definition and internally call a custom API, such as an interceptor, via reflection. However, this would require me to unify the interceptor's parameter list allocation strategy, return value definition, and how the return value is reassigned to the instrumented method.

Considering that there are already a large number of scattered advice definitions in the project, each with different strategies for obtaining parameter lists and processing return values, refactoring would entail a huge amount of work.
Therefore, I had the idea above, hoping to make Byte Buddy continue to dynamically handle parameter allocation and reassignment operations while making as few changes as possible to the existing advice definitions.

It looks like it won't be easy to implement this now. I will gradually solve this problem through project refactoring in the future. 

Thank you for your answer!

**Comment by raphw** [comment]
What I wonder about if it really makes a difference to have this:

```java
class StaticIntercept {
  @OnMethodEnter
  static void staticMethod(@Argument(0) Object val) {
    State state = State.get();
    doSomething(state, val);
  } 
}
```

compared to:

```java
class StaticIntercept {
  State state = new State();
  @OnMethodEnter
  void nonStaticMethod(@Argument(0) Object val) {
    doSomething(state, val);
  } 
}
```

You could even implement a custom annotation to support the `State` object. I would assume that this yields the same result?

**Comment by dogourd** [comment]
Actually, I may not have expressed my question accurately earlier. 

The reason for my previous idea was that invokedynamic was not available before Java 7. If the target application uses Java 6 and I still want my aspect code to be executed under a specific class loader, I cannot use `WithCustomMapping.bootstrap()`. However, Java 6 does support `invokevirtual`, and `invokestatic` is also possible, this is not important. 

Based on these conditions, my idea is to extend `net.bytebuddy.asm.Advice.Delegator.Factory` to create an implementation similar to `net.bytebuddy.asm.Advice.Delegator.ForDynamicInvocation.Factory`, but it will not return a `CallSite`. 
Instead, it will return an `instance object`, which will then be used to invoke the advice through `invokevirtual`, or it will return a `Class<?>`, which will then be used to invoke the advice through `invokestatic`. The only thing to ensure is that the `instance object` or `Class<?>` is loaded by a custom class loader.

This way, I can still freely access the instrumented type's related classes and methods within the advice, without having to worry about class loading isolation issues (such as Tomcat), even when `inline=false` is set.

**Comment by raphw** [comment]
Ah, I get it now. Yes, that makes perfect sense. I look into that!

**Comment by raphw** [comment]
I gave this some thought and its unfortunately not that straight forward. The idea of invoke dynamic and method handles are their polymorphic signature. This concept is not available before Java 7. With reflection, I would need to wrap all arguments in an array and box primitives what requires additional work. I am playing with two ideas:

- Add a way of returning a `MethodHandle` instance from a static method. This still requires to use at least Java 7, but class files do not need to be of version 7. I think it's fair to assume that Java 6 JVMs are no longer in use.
- Allow returning a `Method` object with all the wrapping, but that's also weird in the way exceptions are propagated.

I tend to go for the first solution as the second one would unlikely be useful for many. I discarded the idea of virtual dispatch on actual types as it does not bring any advantage when it comes to class loading as the virtual type would need to be known to the targeted class, nothing is gained. Also, it would complicate the code by a lot.

What's your thought on this. Are you expecting to run on Java 6 JDKs?

**Comment by dogourd** [comment]
> I think it's fair to assume that Java 6 JVMs are no longer in use.

I completely agree, we should definitely say no to old projects that run on Java 6. It's just embarrassing that most enterprises don't see it that way.

I'll also spend some time trying to implement and verify feasibility. However, since I have limited knowledge of bytecode-related topics, it may take some time. I'll do my best to do it as soon as possible and provide my conclusion here. I'll close this issue when I have an update.

**Comment by dogourd** [comment]
I tried to use ASM to add some instructions to implement my idea, and here's a simple advice:

```java
public class com.dogourd.Advice {
    public void before() {
        System.err.println(this.getClass().getClassLoader());
    }
}

// generate: ((Advice) com.dogourd.BootstrapDispatcher.bootstrap("com.dogourd.Advice", DispatcherServlet.class)).before();
public void visitCode() {
  visitLdcInsn(adviceMethod.getDeclaringType().getName());
  visitLdcInsn(Type.getType(instrumentedType.getDescriptor()));
  visitMethodInsn(Opcodes.INVOKESTATIC, bootstrapMethod.getDeclaringType().getInternalName(),
          bootstrapMethod.getName(), bootstrapMethod.getDescriptor(), false);

  visitTypeInsn(Opcodes.CHECKCAST, adviceMethod.getDeclaringType().getInternalName());
  visitMethodInsn(Opcodes.INVOKEVIRTUAL, adviceMethod.getDeclaringType().getInternalName(), adviceMethod.getName(),
          adviceMethod.getDescriptor(), false);
  super.visitCode();
}

class com.dogourd.BoostrapDispatcher {
  Object bootstrap(String adviceName, Class<?> instrumentedType) {
    CustomClassLoader.from(instrumentedType.getClassLoader()).loadClass(adviceName).newInstance();
  }
}
```

In the above implementation, the `checkcast` instruction failed with `java.lang.ClassCastException: com.dogourd.Advice cannot be cast to com.dogourd.Advice`. It seems like my initial idea cannot be implemented this way, and reflection seems to be inevitable. However, this is definitely not something that Byte Buddy should be responsible for!
