### ISSUE TITLE
How to combine graalvm native-image with byte-buddy?

### ISSUE THREAD

**Issue by a364176773** [raphw/byte-buddy#1424]
I am using byte-buddy for proxy in my spring-native project, but I can't package it as native-image, can you give me a reference example? Thank you very much!

**Comment by raphw** [comment]
Byte Buddy generates byte code, not native code. Graal has an agent that keeps references on generated code. Did you try it?

**Comment by a364176773** [comment]
> Byte Buddy generates byte code, not native code. Graal has an agent that keeps references on generated code. Did you try it?

I'm sorry I haven't tried it, so I wish there was a byte buddy and graal combination sample or document that I could learn from

**Comment by raphw** [comment]
If you run the Graal agent, it has support for collecting "class-define-support": https://www.graalvm.org/22.1/reference-manual/native-image/ExperimentalAgentOptions/

If you enable this option, Byte Buddy recognizes it and adjusts its class loading behavior accordingly.

**Comment by a364176773** [comment]
> If you run the Graal agent, it has support for collecting "class-define-support": https://www.graalvm.org/22.1/reference-manual/native-image/ExperimentalAgentOptions/
> 
> If you enable this option, Byte Buddy recognizes it and adjusts its class loading behavior accordingly.

I mainly use the function intercept, is it handled the same way?

**Comment by raphw** [comment]
Yes, with the agent active, this should work if the class definition feature is enabled.

**Comment by a364176773** [comment]
@raphw Thank you very much
