### ISSUE TITLE
"java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method" occur when i transform a class which has been loaded.

### ISSUE THREAD

**Issue by luanwenfei-venus** [raphw/byte-buddy#1426]
Hi, when i attempt to use bytebuddy with agentmain, "java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method" occur，But I didn't add any methods. 
I found that bytebuddy adds the following static block of code for the class I want reTransform to be：
`
static {
        ClassLoader.getSystemClassLoader().loadClass("net.bytebuddy.dynamic.Nexus").getMethod("initialize", Class.class, Integer.TYPE).invoke((Object)null, StringBuilder.class, -1854685050);
    }
`
How can I avoid adding this static block of code and get my reTransform to work，thank u.

My bytebuddy version is '1.10.14'.

**Comment by luanwenfei-venus** [comment]
“disableClassFormatChanges”  doesn't seem to work in my program.

**Comment by raphw** [comment]
You can set the `-Dnet.bytebuddy.dump=/some/folder` property. With *javap*, you can diff the original version and the transformed version of the class, to see what method was added.

**Comment by luanwenfei-venus** [comment]
Thank you for your help.
