### ISSUE TITLE
Resolution.getDeclaredMethods() returns wrong methods

### ISSUE THREAD

**Issue by lujiajing1126** [raphw/byte-buddy#1429]
Currently in the SkyWalking, we are using a so-called WitnessMethod mechanism to determine whether a target class should be enhanced. Specifically, class `A` should be enhanced if and only if a method, let's say `B#a()` exist. `A` and `B` may be the same. `TypePool` is used to describe a resolution,

```java
public enum WitnessFinder {
    INSTANCE;

    private final Map<ClassLoader, TypePool> poolMap = new HashMap<ClassLoader, TypePool>();

    private TypePool.Resolution getResolution(String witnessClass, ClassLoader classLoader) {
        ClassLoader mappingKey = classLoader == null ? NullClassLoader.INSTANCE : classLoader;
        if (!poolMap.containsKey(mappingKey)) {
            synchronized (poolMap) {
                if (!poolMap.containsKey(mappingKey)) {
                    TypePool classTypePool = classLoader == null ? TypePool.Default.ofBootLoader() : TypePool.Default.of(classLoader);
                    poolMap.put(mappingKey, classTypePool);
                }
            }
        }
        TypePool typePool = poolMap.get(mappingKey);
        return typePool.describe(witnessClass);
    }

    public boolean exist(WitnessMethod witnessMethod, ClassLoader classLoader) {
        TypePool.Resolution resolution = getResolution(witnessMethod.getDeclaringClassName(), classLoader);
        if (!resolution.isResolved()) {
            return false;
        }
        return !resolution.resolve()
                .getDeclaredMethods()
                .filter(witnessMethod.getElementMatcher())
                .isEmpty();
    }
}
```

Before enhancing a class, `WitnessFinder.INSTANCE.exist(x, y);` is called. But the issue is, the `declaringClass` of the witness method used here may already be transformed once before.

And *sometimes*, calling `getDeclaredMethods()` gives wrong answer.

**Comment by lujiajing1126** [comment]
Another question is about the implementation of method interception:

Suppose we have a class A which extends class B. If we intercept methods, e.g. `a(), b(String)` in the base class B, will they become declared methods in class A?

**Comment by raphw** [comment]
The `MethodGraphCompiler` (can be configured in the `ByteBuddy` instance) will resolve methods to trees and merge bridge methods into the actual method. Byte Buddy takes care of all the infrastructure around this. Bridges are indeed not "actual" methods but those that are normally declared in source.

You should not intercept bridges as those can otherwise yield circularities.

**Comment by lujiajing1126** [comment]
Thanks. Quoted

> Suspect bridge method is being added from implementing a public methods from a non-public class.

from https://bugs.openjdk.org/browse/JDK-6815786, this is an expected behavior.

**Comment by raphw** [comment]
This is a visibility bridge. For Java reflection to being able to call a method, it must be public. To fulfil this constraint, a public bridge is added where appropriate.

**Comment by lujiajing1126** [comment]
In the SkyWalking context, we are now filtering synthetic methods by using an additional `.and(not(isSynthetic))` in https://github.com/apache/skywalking-java/pull/504

Thanks again for the explanation!
