### ISSUE TITLE
Internal JVM Class Redefining/Intecepting?

### ISSUE THREAD

**Issue by ChaosData** [raphw/byte-buddy#143]
Hi,

I'm not really sure if this is possible via the Instrumentation API for Java agents, but I've been trying to redefine/intercept on internal (OpenJDK) JVM classes, specifically things under `java.lang.management` (generally implemented under `sun.management`) such as `sun.management.RuntimeImpl`, `java.lang.management.ManagementFactory`, and `sun.management.VMManagementImpl`. From what I can tell, they're not actually in the boostrap class loader, and (at least some) instead appear to be buried within the implementation of `javax.management.loading.ClassLoaderRepository` ( as obtained from `ManagementFactory.getPlatformMBeanServer().getClassLoaderRepository()`).

In general, the `AgentBuilder.Default()` APIs don't seem to be able to find the classes (and are likely looking in normal-ish classloaders), so I've been trying to do this via `ByteBuddy.redefine`. However, I keep getting the following exception:

```
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:170)
	at net.bytebuddy.dynamic.loading.ClassReloadingStrategy$Strategy$1.apply(ClassReloadingStrategy.java:297)
	at net.bytebuddy.dynamic.loading.ClassReloadingStrategy.load(ClassReloadingStrategy.java:173)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4350)
```

Part of the annoyance with this is that it might be possible to get at `sun.management.VMManagementImpl` before it loads, but when I did, this caused problems with the native code in it. Getting there first results in the `System.LoadLibrary("management")` call in `sun.management.ManagementFactoryHelper` not actually having been performed yet, resulting in crashes due to failures to link. I've successfully managed to force it to load the library in an acceptable classloader, and have intercepted `System.loadLibrary(String)` to prevent invalid duplicate loads, but I continue to get the above exception when working on these classes.

Might you have any ideas for how to do such things with ByteBuddy (if it's actually do-able in the first place)?

**Comment by raphw** [comment]
The problem here is that most JVMs do not currently support adding methods or fields to classes that are redefined. To overcome this limitation, Byte Buddy adds a specific switch to the `AgentBuilder` API. You would need to set `disableClassFormatChanges()`.

After enabling this switch, Byte Buddy does no longer allow you to add fields or methods which does however imply that you cannot longer use the interception API without replacing the former code.

The solution to this is to use the `Advice` component instead of the standard API. This rather new API is not part of the documentation yet but the javadoc should cover most scenarios. The Advice API allows you to add before and after advice, including the change of a return value or handling an exception. For example, a simple instrumentation would be:

```java
new AgentBuilder.Default()
  .disableClassFormatChanges()
  .with(RedefinitionStrategy.RETRANSFORM)
  .type(is(ManagementFactory.class))
  .transfrom((td, builder, cl) -> builder.visit(Advice.to(MyAdvice.class).on(named("getMemoryMXBean")))
  .installOnByteBuddyAgent();

class MyAdvice {
  @OnMethodEnter
  static void foo() {
    System.out.println("foo");
  }
}
```

This advice adds the `System.out.println("foo")` to the beginning the `getMemoryMXBean` method without changing the class file.

**Comment by ChaosData** [comment]
I'm not sure that `AgentBuilder`, as used in your example, is able to find the classes I'm attempting to work with.

Is there a way to pass the `AgentBuilder` API a `ClassLoader` or `ClassFileLocator` to search?
Alternatively, is there a simple enough way to use the `Advice` API with the normal `ByteBuddy` API?

For reference, I'm attempting to use the following:
```
    new AgentBuilder.Default()
        .disableClassFormatChanges()
        .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
        .type(ElementMatchers.is(rmxb.getClass()))
        .transform((builder, _cl, _td) -> builder.visit(Advice.to(MyAdvice.class).on(ElementMatchers.named("getInputArguments"))))
        .installOnByteBuddyAgent();
```

Both `java.lang.management.ManagementFactory` and `sun.management.RuntimeImpl` (which I'm looking to hook), are loaded from separate classloaders that are separate from the main chain accessible from premain.

**Comment by raphw** [comment]
The `AgentBuilder` is built on top of the `Instrumentation` API which allows to read all classes that were  loaded by the VM. There are no classes skipped. The classes in question are however loaded by the bootstrap class loader and you need to be extra careful when instrumenting such classes as you can provoke loading circularities (a class is required for instrumenting a class while instrumenting the same class).

Therefore, you need to set `ignore(none())` in your case.

As for the `Advice`, you are already using the normal Byte Buddy API from within transform, but you are right that a direct use might be easier for your goal:

```java
new ByteBuddy()
  .with(Implementation.Context.Disabled.Factory.INSTANCE)
  .redefine(ManagementFactory.class)
  .visit(Advice.to(MyAdvice.class).on(ElementMatchers.named("getInputArguments")))
  .make()
  .load(ManagementFactory.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
```

**Comment by ChaosData** [comment]
Both of those work!

Given that I can get `java.lang.BootstrapMethodError` exceptions wrapping `java.lang.NoClassDefFoundError` when referencing things out of the Advice classes, they probably are loading in "bootstrap" class loaders. Though I can verify via `Instrumentation.getInitiatedClasses` that they're not in the "normal" bootstrap class loader, which is what threw me off.

Thanks!

**Comment by raphw** [comment]
The advice code is inlined into the instrumented code; if you reference any other method from the advice, it is indeed resulting in a NoClassDefFoundError if the bootstrap class loader cannot see these classes.

Glad it works for you!

**Comment by SergejIsbrecht** [comment]
Thank you @raphw, I had the same issue, because I was using the "Stream"-API in the Advice, which was currently not loaded by the bootstrapper. Removing the line helped a lot.
