### ISSUE TITLE
Using TypeStrategy.Default.DECORATE

### ISSUE THREAD

**Issue by laurit** [raphw/byte-buddy#1437]
Can `TypeStrategy.Default.DECORATE` be used instead of `TypeStrategy.Default.REDEFINE_FROZEN` when I'm only applying `Advice` and not doing class format changes? All of my tests passed with `TypeStrategy.Default.DECORATE`. I'm asking because the language in https://github.com/raphw/byte-buddy/blob/4e3ae3cdd4e1613c7f1afa28fc2b923dba97aecb/byte-buddy-dep/src/main/java/net/bytebuddy/ByteBuddy.java#L1077-L1084 hints that there are limitations to using it. I don't know whether the `standard transformations` mentioned there includes applying `Advice`.

**Comment by raphw** [comment]
Decorate is even cheaper, it obly allows visitors. frozen means that the class file format cannot be changed, something that many JVMs expext gor retransformation.

**Comment by laurit** [comment]
Thanks.
