### ISSUE TITLE
QUESTION: How to extract header when HttpServletRequest not in arguments?

### ISSUE THREAD

**Issue by yangmeili50** [raphw/byte-buddy#1440]
### Context
We are developping a java agent using bytebuddy to generate method call chains. It extracts `Trace-id` in request header to track the call chain. `Trace-id` is put in by the browser using a tool.
We go through all arguments by `@Advice.AllArguments` to extract the `HttpServletRequest`.
```JAVA
@Advice.OnMethodEnter()
    public static void enter(@Advice.AllArguments Object[] allArguments) {
            ......
            for (Object obj : allArguments) {
                    if (obj instanceof HttpServletRequest) {
                            HttpServletRequest request = (HttpServletRequest) obj;
                            String caseId = request.getHeader("Trace-id");
                            ......
                   }
            }
            ......
}
```

### Problem
The above usage requires the intercepted method(controller method) has `HttpServletRequest` param in method arguments.

As the following demos, the agent can extract headers from `demoApiI2`, becase it has `HttpServletRequest` in arguments. But cannot  extract headers from `demoApiI1`, becase it doesn't have `HttpServletRequest` in arguments. 

**If `HttpServletRequest` not in arguments,  how to get the request header by bytebuddy?**

```JAVA
@RestController
@RequestMapping("/demo")
public class DemoController {

@GetMapping("/api-1/{flag}/{requestUser}")
    public Result<Boolean> demoApiI1(
                                     @PathVariable("flag") int flag,
                                     @PathVariable("requestUser") String requestUser) {
        demoService.methodA(requestUser);
        boolean result = demoService.methodB(requestUser, flag);
        return Result.success(result);
    }

    @GetMapping("/api-2/{flag}/{requestUser}")
    public Result<void> demoApiI2(
                                     HttpServletRequest httpServletRequest,
                                    @PathVariable("flag") int flag,
                                    @PathVariable("requestUser") String requestUser) {
        demoService.methodW(flag);
        demoService.methodX(requestUser);
        return Result.success(void);
    }
}
```

**Comment by RTxin** [comment]
@yangmeili50 You can add `advice` at the service entrance to get the generated Request.This is not a problem that ByteBuddy needs to be solved. Turn the source code of "**Spring**" or "**Servlet**".
