### ISSUE TITLE
Bug: transform inner class error

### ISSUE THREAD

**Issue by YongwuHe** [raphw/byte-buddy#1441]
@raphw
The bytebuddy transform logic I understand is:
1. When `builder.installOn(instrumentation)`, get all the classes loaded in the current loader, match according to the defined transformer, and match the classes to form a mapping relationship: `className -> Instrumentation`.

2. When the class that is not loaded `after builder.installOn(instrumentation)` is completed is loaded, it will be matched by calling the classLoader transformer through classLoader defineClass, and the matched class will be modified.

I created an instrumentation TypeMatch is `hasSuperType(named("java.util.concurrent.ForkJoinTask"))`. But I found that it cannot transform the inner class(ex: `java.util.concurrent.ForkJoinTask$AdaptedCallable`). 

Through investigation, I found that this is the cause:

Before build.installOn,  the use of new CompletableFuture<>() caused the ForkJoinTask class to be loaded, but the innerClass did not (ex: java.util.concurrent.ForkJoinTask$AdaptedCallable).

When builder.installOn(instrumentation), due to the hasSuperType(named("java.util.concurrent.ForkJoinTask")) in ForkJoinTaskInstrumentation, when transforming ForkJoinTask.class, there is a getDeclareClass operation, which causes the subclass to be loaded, and because there is no such match in the mapping relationship: className -> Instrumentation in the first matching rule, the first one is not matched.

After builder.installOn(instrumentation), since the class has already been loaded, which causes fail to match the second rule, and eventually these internal classes are not transformed.

Is it possible to fix this situation.

**Comment by raphw** [comment]
You can use a POOL_FIRST description strategy.

If possible, use disableClassFormatChanges and register DECORATE as type strategy.

**Comment by YongwuHe** [comment]
According to your suggestion, the problem has been solved, thanks.
