### ISSUE TITLE
Minor: documentation for TypePool#describe(String) is incorrect

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#1447]
The [javadoc says](https://javadoc.io/static/net.bytebuddy/byte-buddy/1.14.4/net/bytebuddy/pool/TypePool.html#describe-java.lang.String-):

> The name is to be written as when calling [Object.toString()](https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Object.html?is-external=true#toString--) on a loaded [Class](https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Class.html?is-external=true).

But calling `toString()` on, for example, `Object.class` yields `class java.lang.Object`.

I think instead you must mean to say something like:

> The supplied name must be equal to the result of an invocation of the [`Class#getName()` method](https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Class.html?is-external=true#getName--) on some [Class](https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/Class.html?is-external=true) object.

**Comment by raphw** [comment]
Good catch, thanks!
