### ISSUE TITLE
 About the new requirements for the support of friends of native transform

### ISSUE THREAD

**Issue by 1057105012** [raphw/byte-buddy#1450]
I saw that the default implementation of bytebuddy is based on AgentBuilder, which seems to be no problem, but in the process of my practice, I found that the process based on third-party code is very uncontrollable, especially when encountering some special jvm architecture and special In some cases, such as the osgi environment, a small number of categories will fail to insert stubs, and the monitoring of bytebuddy is behind the typedescription. Sometimes some classes will not reach this step at all, and will fail when bytebuddy resolves This method looks normal, and it may not be a problem. Maybe we can't hook these classes at all, but the lack of prompt information will make us very confused about these extremely occasional phenomena, so I think bytebudy can Provide an equivalent support based on native transform, similar to javassit and asm, but retain the simplicity of bytebuddy

**Comment by raphw** [comment]
Not sure I follow.

maybe you are looking for agentbuilder.listener?
