### ISSUE TITLE
"Could not initialize inline Byte Buddy mock maker" error when maven.repo.local contains "="

### ISSUE THREAD

**Issue by AntoineLange** [raphw/byte-buddy#1457]
We notice after spring boot 3.1 upgrade (and use of byte-buddy through new mockito 5.x version), that builds on our CI fails with error:

```
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.

It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 17
JVM vendor name    : Azul Systems, Inc.
JVM vendor version : 17.0.6+10-LTS
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.6+10-LTS
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 5.15.0-73-generic

		at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<init>(InlineDelegateByteBuddyMockMaker.java:244)
		at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:23)
		... 74 more
	Caused by: java.lang.IllegalStateException: Could not self-attach to current VM using external process
```

We saw many of this error for different reason on byte-buddy and mockito project github. After investigation we noticed that our buids in our CI environment (dockers) was using a custom "-Dmaven.repo.local=/our/path" with an equal (=) in "/our/path". E.g: "-Dmaven.repo.local=/home/project=branch/repository". It looks like the bute buddy agent will parse the string and stop at this equal and cause the above error.

To reproduce, simply create a new spring boot 3.1.0 project from https://start.spring.io/ and add Spring web dependency. Then build using "mvn clean install -Dmaven.repo.local=/your/path-with-equal=fail/repository"

**Comment by AntoineLange** [comment]
After more investigation I can see error "Error opening zip file or JAR manifest missing: /your/path-with-equal" and the part after the equal (=) in the path is missing.

It looks like the problem in the javaagent parsing in the open jdk https://github.com/openjdk/jdk/blob/931625a9304ec2761ca9035d69fd33f6beadb124/src/java.instrument/share/native/libinstrument/InvocationAdapter.c#L68
and not in byte-buddy

**Comment by AntoineLange** [comment]
The -javaagent tail parsing is finally the problem. I can close this issue. At least maybe it's gonna help other persons if they have the same issue as me.

**Comment by roka-actico** [comment]
> The -javaagent tail parsing is finally the problem. I can close this issue. At least maybe it's gonna help other persons if they have the same issue as me.

@AntoineLange do you know, it this tail parsing problem is registed as bug at openjdk?

**Comment by AntoineLange** [comment]
@roka-actico I'm not sure if it was an open issue or a comment from a developer that I came across, but I can't seem to find any open issue at openjdk related to that matter.
