### ISSUE TITLE
How to enhance Annotation?

### ISSUE THREAD

**Issue by RTxin** [raphw/byte-buddy#1461]
hello,Rafael
I want to enhance the annotation `@Pattern`, but this annotation has different implementation in different frameworks, so I want to know if ByteBuddy has a plan that directly enhances the annotation
```java
import jakarta.validation.constraints.Pattern;
public class UserForm {
  @Pattern(regexp = "[a-z0-9-]*", message = "can only contain lowercase letters, digits, and -")
  private String username;
}
```

**Comment by raphw** [comment]
What is it you are trying to do?
