### ISSUE TITLE
Refactoring ASM code to use ByteBuddy

### ISSUE THREAD

**Issue by rupinder10** [raphw/byte-buddy#1462]
I have an existing instrumentation that I wrote several years ago using ASM. Its a fairly complex application so I want to make the minimal changes but remove ASM with ByteBuddy for obvious reasons. The oversimplied flow of the existing application is  as under. 

Obviously the getClassVisitor method is where I use ASM ClassVisitor pattern to modify the classes. The number of classes retransformed are less than 20.

I am looking for an equivalent with ByteBuddy where I only can make changes in the retransformClasses or the tranform method of the ClassFileTransformer so that the original product doesnt have to change much. Any pointers to get started would be very helpful. 

```
public static void retransformClasses(Instrumentation instrumentation, (Class<?>[] classesToRetransform, 
                                      AgentConfig agentConfig) {
  instrumentation.addTransformer(transformer, true);
  instrumentation.retransformClasses(classesToRetransform);
}

public class AgentClassTransformer implements ClassFileTransformer {	
  private AgentConfig agentConfig; 

  public AgentClassTransformer(AgentConfig agentConfig)  {
    this.agentConfig = agentConfig;
  }
	
  @Override
  public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, 
    ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
    
    ContextLoadingClassWriter writer = new ContextLoadingClassWriter(loader, className, ClassWriter.COMPUTE_FRAMES);
    ClassVisitor classVisitor = getClassVisitor(className, writer);
    ClassReader reader = new ClassReader(classfileBuffer);
    writer.setSuperClassName(reader.getSuperName());
    reader.accept(classVisitor, ClassReader.EXPAND_FRAMES);
    return writer.toByteArray();
  }
```

**Comment by raphw** [comment]
Have a look at `AsmVisitorWrapper` and its implementations. There you can register it into an `AgentBuilder`. But if you want to replace your vanilla ASM, you would normally look into the transformation DSL and possibly `Advice`.

**Comment by rupinder10** [comment]
Thanks. I am clear on the Advice aspect of it and can replace the ASM aspects. What I am not clear on is how to start at the top. How do I replace these two lines to use ByteBuddy ?

```
 instrumentation.addTransformer(transformer, true);
 instrumentation.retransformClasses(classesToRetransform);
```

**Comment by raphw** [comment]
This would happen via `agentBuilder.install(instrumentation)`. If a retransformation strategy is defined, it will trigger retransformation automatically.

**Comment by rupinder10** [comment]
Thanks. That answers my question
