### ISSUE TITLE
Add static method to class not working

### ISSUE THREAD

**Issue by beikov** [raphw/byte-buddy#1465]
Hi there,
I'm trying to add a static method to a newly created class but there seem to be method filters in place that prevent non-virtual methods to be compiled. This is how I create the method:

```java
builder = builder.defineMethod(
	"get_" + getter.getName(),
	TypeDescription.Generic.OfNonGenericType.ForLoadedType.of(
		getterType
	),
	Opcodes.ACC_PROTECTED | Opcodes.ACC_STATIC
)
.withParameter( clazz )
.intercept(new Implementation.Simple(new GetFieldOnArgument(getter)));
```

`net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.InstrumentableMatcher#resolve` and `net.bytebuddy.dynamic.scaffold.MethodGraph.Compiler.Default#compile` both create matchers that only handle methods which are virtual.

How am I supposed to add a static method to a class that I want to create?

**Comment by raphw** [comment]
I cannot reproduce this problem. Can you create an executable sample?

**Comment by raphw** [comment]
Those methods do sometimes exist for bridging calls with respect to generics. But it should indeed be more explicit if you define such methods explicitly. I will have a look if this can be improved.
