### ISSUE TITLE
Passing extra parameters to Advice class

### ISSUE THREAD

**Issue by rupinder10** [raphw/byte-buddy#1467]
I have an advice class simplified as below:

```
public class MyAdvice {
  @Advice.OnMethodEnter(suppress = Throwable.class)
  public static void onEnter(
      @Advice.Argument(0) Service service,
      @Advice.Argument(1) String name
      throws Throwable {
         System.out.println("Service:" + service.getName + ", Name:" + name);
  }
}
```

which is use in the transformer's transform method as below:

```
Builder<?> b = builder.visit(MyAdvice.class).on(ElementMatchers.named("process");
```

I would like to pass a couple of String as extra parameters into the Advice methods. For example, lets assume that the "Service:" and "Name:" strings were prefixes I want to pass in from the transformer. Is there a mechanism to do that in ByteBuddy ? Or hardcoding the values is the only way ?

**Comment by RTxin** [comment]
I guess you want to use `net.bytebuddy.asm.Advice.WithCustomMapping#bind(java.lang.Class<T>, java.lang.Object)`.

**Comment by rupinder10** [comment]
Thanks @RTxin. Unfortunately that works with only one constant. I have 2 and sometimes upto 4 values. So I would then have to declare 4 annotations and then bind multiple times. While that may work, I was hoping if there was a simpler way. I tried wrapping all the values into a String[] but then it gave me an error that the value was not a constant.

**Comment by raphw** [comment]
That array would need to be created on each read. You can create it for a binding and fill it with constants. But this requires you to create a custom stack manipulation for it.

**Comment by rupinder10** [comment]
I have 4 values which are all constants. And luckily, all are Strings too. Is there a sample you can point me to for the custom stack manipulation ?

**Comment by raphw** [comment]
If you look how a constant is bound in the `Advice` code, it uses a `StackManipulation` as things are now. You can use an `ArrayCreation` stack manipulation to wrap four such constants and bind it to an annotation. For performance reasons, I would however recommend you to use four annotations to bind the four values, as this avoids the allocation of the arrays.

**Comment by rupinder10** [comment]
If you recommend using 4 Annotations for performance reasons, then I am going to stick to that as I already have that in place. Thanks for the suggestions.
