### ISSUE TITLE
Unit testing - removeTransformer()

### ISSUE THREAD

**Issue by kctang** [raphw/byte-buddy#147]
Hi,

Based on this [stackoverflow question](http://stackoverflow.com/questions/35577485/junit-test-framework-for-javaagent-instrumentation-framework/35597908#35597908), I am able to unit test instrumented classes.

I think the `removeTransformer()` will stop transforming class definitions after it is called (e.g. newly loaded class definitions). However, existing classes are not "reverted".

So, this means if I have `MyTestClass` that was transformed for `UnitTestOne`... i cannot transformed `MyTestClass` again for `UnitTestTwo`'s use case.

How can I reuse `MyTestClass` to transform it differently for multiple test cases? Something that cross my mind is to have some kind of "per test" class loader - yet to explore this.

Any idea?

**Comment by raphw** [comment]
You have two possibilities:

1. You create class loaders to which you provide the byte code of the classes you want to test (via `ByteArrayClassLoader` and `ClassFileLocator.ForClassLoader::read`). You then can limit your instrumentation to this class loader and throw it away after the test.

2. You use `ClassReloadingStrategy::reset` after the test.
