### ISSUE TITLE
[Help wanted] Migrating from javassist to bytebuddy

### ISSUE THREAD

**Issue by xiangtianyu** [raphw/byte-buddy#1479]
Recently we are trying to migrate from javassist to bytebuddy. 

There's such a case: 
There is a "strategy interface" and then i use javassist to create "implementation class" by different type. And when i tried to use bytebuddy to rewrite the logic, i find that bytebuddy use 'intercept' to do this logic, and in my case, the "implementation class" is uncertain existence, so it's unpossible to use 'intercept' to implement.

Is there any solution to do this like javassist?

**Comment by raphw** [comment]
I am not sure I follow. You do not know the targeted class? In this case, you would need to delegate to a generic interceptor and then implement the actual delegation. Do you have an example of your current state of affairs?

**Comment by xiangtianyu** [comment]
I create an sdk for users. There's a custom logger interface in the sdk, and i want to create a dynamic implementation when the app is running. I will try to get the log sdk in my app, if the user use logback, i will create logback implementation and use logback api. And the same for log4j and so on. But i cannot determine which sdk the user use, and the log sdk will not exist in my sdk, how can i create the implementation

**Comment by raphw** [comment]
Can you give some examples on how Javasisst is used by you today?

**Comment by xiangtianyu** [comment]
Since the real code is sensitive, i made a demo.

```
public interface LogStrategy {

    void funcA(Object o) throws Exception;

}

ClassPool pool = new ClassPool(true);
pool.appendClassPath(new LoaderClassPath(getClassloader()));

CtClass cc = pool.makeClass("LogbackStrategy_Proxy");
cc.addInterface(pool.get(LogStrategy.class.getName()));

StringBuilder sb = new StringBuilder();
sb.append(" public String funcA(Object o) throws Exception {");
sb.append("    return ch.qos.logback.classic.Logger.funcA(o);");
sb.append(" }");
CtMethod mthd1 = CtNewMethod.make(sb.toString(), cc);
cc.addMethod(mthd1);
sb.setLength(0);

cc.toClass();
```

**Comment by raphw** [comment]
You would use a `ByteBuddy` instance and subclass the `LogStrategy` interface. You would then intercept the method and possibly use `Advice` to invoke the method in question.
