### ISSUE TITLE
Reflection-based injection is not available on the current VM

### ISSUE THREAD

**Issue by yswdqz** [raphw/byte-buddy#1488]
Hi !

I tried to compile my application using GraalVM and native-image and got this error, is this normal? If so, how can I change it?

<img width="1255" alt="image" src="https://github.com/raphw/byte-buddy/assets/74546965/a61d8591-2a64-42e2-900e-5e18f19df24d">

**Comment by raphw** [comment]
On Graal, this strategy will not work. But neither will Java agents, normally. Byte Buddy supports Graal to some degree, but it requires a preexecution and is highly experimental at this point. It also needs to be supported by the agent developer and is non-trivial to accomplish, and will neither work for all execution attempts.

**Comment by yswdqz** [comment]
> Byte Buddy supports Graal to some degree, but it requires a preexecution and is highly experimental at this point. 

Thank you! I'd like to implement this feature anyway though. Would you be able to give me more details about bytebuddy's support for graal?

**Comment by raphw** [comment]
For an agent, you have to instrument the code during image creation. But you need to make sure there is no randomness in your created code.

**Comment by yswdqz** [comment]
> For an agent, you have to instrument the code during image creation. But you need to make sure there is no randomness in your created code.

Yes, I'm just wondering what I should choose if reflect-strategy is not available.

**Comment by raphw** [comment]
Byte Buddy can resolve an implicit strategy if a class is preloaded. Check the `DynamicType.Unloaded.load` method to see how it is done in Byte Buddy when Graal is detected.
