### ISSUE TITLE
Illegal default value

### ISSUE THREAD

**Issue by erikhakansson** [raphw/byte-buddy#149]
Hello!

I'm using ByteBuddy to rebase pretty much every class in my classloader. However, I've found what I believe is a bug. Consider this:

```java
TypeDescription typeDescription = typePools.get(classLoader).describe(className).resolve();
        return new ByteBuddy().rebase(typeDescription, ClassFileLocator.Simple.of(className, classBytes))
//.implement(ProxyInterface.class)
//.method(ElementMatchers.isPackagePrivate().and(ElementMatchers.not(ElementMatchers.isStatic())))
//.intercept(MethodDelegation.to(PackagePrivateInterceptor.class))
        .make().load(
                        (ClassLoader) classLoader, ClassLoadingStrategy.Default.INJECTION.withProtectionDomain(classLoader.getClass().getProtectionDomain())).getLoaded();
 ```
where `className = "com.google.gson.annotations.SerializedName`
I've commentd out my interceptor, but that makes no difference.

As can be seen in the Gson source [here](https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/annotations/SerializedName.java), the [annotation] method alternate() has a default value of {} and a return type of String[]. I.e., the default value is an empty String array.

However, this throws an exception:

<pre>
Caused by: java.lang.IllegalStateException: Illegal default value [Ljava.lang.String;@6f4a47c7for public abstract java.lang.String[] com.google.gson.annotations.SerializedName.alternate()
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:871)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:530)
	at net.bytebuddy.dynamic.scaffold.inline.RebaseDynamicTypeBuilder.make(RebaseDynamicTypeBuilder.java:182)
</pre>

The exception is thrown due to this method return false:
https://github.com/raphw/byte-buddy/blob/833f44864c143052b4451208105043ea00ada66d/byte-buddy-dep/src/main/java/net/bytebuddy/description/method/MethodDescription.java#L582

I'm not entirely sure what that method is supposed to do, but it seems to me that besides the present checks for primitivies, String, Class, Annotation and Enum, a check for an array of each of those should also be present. E.g. in my case
`returnType.represents(String[].class) && value instanceof String[]`

Trying that manually while debugging shows it would return true.

I can submit a pull request for this minor change, but since I'm not really sure what the method should do, I don't know what impact that would have.

Any ideas?

**Comment by raphw** [comment]
You are right, this is a bug and another argument for writing a unit test for really everything. I just fixed it myself as I chose to extend the check and also add a unit test. Good catch, thank you.

You can deactivate type checks by `new ByteBuddy.with(TypeValidation.DISABLED)` until the next release.

**Comment by erikhakansson** [comment]
Thank you! It works with TypeValidation.DISABLED.

I did however find another issue, but I'll open a new one for that.
