### ISSUE TITLE
how to use byte-buddy to handle annotation

### ISSUE THREAD

**Issue by SuperDubbo** [raphw/byte-buddy#1494]
Regarding the use of byte-buddy, I have 2 questions, which are as follows:
1. How to remove the annotation above the class;
2. How to change the attribute value in the annotation of the class attribute;
In order to avoid that I did not make it clear, I will give the corresponding example below.
Example 1:
I just want to remove the @Aspect annotation on class A.
before
```
@Aspect
@Slf4j
Class A{

}
```
after
```
@Slf4j
Class A{

}
```

Example 2:
I want to change the value of name in the @Resource annotation of attribute a in class B from a to b
before
```
Class B{
    @Resource(name="a")
    private A a;
}
```
after
```
Class B{
    @Resource(name="b")
    private A a;
}
```

**Comment by SuperDubbo** [comment]
By the way, I see that many issues of byte-budyy are about how to use it. Have you considered some typical usage instructions or examples? I believe this will be liked by many developers, and it will also be a good promotion for the promotion and use of the byte-buddy project. @raphw

**Comment by SuperDubbo** [comment]
Referring to this [issue](https://github.com/raphw/byte-buddy/issues/917), I found a solution, but the solution time of the above issue is in 2020. With the recent upgrades, is there a simpler and more suitable alternative?

**Comment by SuperDubbo** [comment]
![image](https://github.com/raphw/byte-buddy/assets/20811216/b798f625-dfc2-4ef8-abda-7d74d3536de1)

**Comment by raphw** [comment]
As pointed out, removal is not currently well-supported.
