### ISSUE TITLE
Create inner class for already loaded classes

### ISSUE THREAD

**Issue by P3ridot** [raphw/byte-buddy#1498]
Can I create inner classes for already loaded classes (without using custom java-agent)? 

I actually need this to call private constructors and fields, but maybe there is better way to do that...
Or it's could be just impossible

**Comment by raphw** [comment]
It does not help to add an inner class property as this is merely cosmetic. What would help would be to manipulate the nestmates attribute, but that is not possible after loading a class.

**Comment by P3ridot** [comment]
Thank you for information
