### ISSUE TITLE
AST and Code Level Manipulation through JANINO (janino.net)

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#15]
Is it possible to extend support in Byte Buddy to manipulate source code / AST through something like Janino with similar interface?

**Comment by raphw** [comment]
Hi Sinirath, 

Byte Buddy is built arround the assumption to manipulate Java byte code at runtime. This assumption is pretty crucial as it for example allows to directly load the manipulated code etc. Also, working with byte code assures that the library remains language agnostic.

Therefore, Byte Buddy has no concept of an AST, it simly provides some *glue* between precompiled components to wire them together or allows to inject any custom byte code into a class.

Best regards, Rafael
