### ISSUE TITLE
Should `jdk.attach` be transitive required under JPMS?

### ISSUE THREAD

**Issue by arjenzhou** [raphw/byte-buddy#1500]
While using mockito for testing, bytebuddy is including as well.
Under the condition of JPMS, module-info.java must require  `jdk.attach` then bytebuddy agent can attach JVM, or `No compatible attachment provider is available` will be thrown.
For this sake, should `jdk.attach` be transitive required under JPMS?

**Comment by arjenzhou** [comment]
https://github.com/mockito/mockito/issues/2952#issuecomment-1660614051

**Comment by raphw** [comment]
It should be, but we struggled to build Mockito with a module-info in place. I did not have time to look into that yet.
