### ISSUE TITLE
[NOOB question] How to replace entire method?

### ISSUE THREAD

**Issue by marlester-dev** [raphw/byte-buddy#1501]
I know how to advice, but how to replace entire method?
I usually install agent with         ByteBuddyAgent.install();
        CLASS_RELOADING_STRATEGY = ClassReloadingStrategy.fromInstalledAgent();

**Comment by raphw** [comment]
Normally, you would use a Java agent. Look into AgentBuilder and it's documentation.

**Comment by raphw** [comment]
From Minecraft, you could try to self-attach using `ByteBuddyAgent.install()`.

Then, you can simply `new ByteBuddy().redefine(...)`. From there, you can mock the method by intercepting it and returning a `FixedValue`.

**Comment by raphw** [comment]
Annotate the method with RuntimeType. However, this will make the method return null.
