### ISSUE TITLE
how to  hook   some not  same classes and method  at once 

### ISSUE THREAD

**Issue by cor0ps** [raphw/byte-buddy#1503]
1、 I   want  transformer   two  classes:
     a.   org.springframework.web.servlet.DispatcherServlet  doDispatch
     b.   org.apache.http.client.CloseableHttpClient   execute

2、 I  user bytebuddy :

```
AgentBuilder.Transformer dispatcherServletTransformer = (builder, typeDescription, classLoader, javaModule, protectionDomain) -> builder
                //拦截任意方法
                .method(ElementMatchers.nameContainsIgnoreCase("doDispatch"))
                //委托
                .intercept(Advice.to(HttpRequestRecord.class));


        AgentBuilder.Transformer httpClientTransformer = (builder, typeDescription, classLoader, javaModule, protectionDomain) -> builder
                //拦截任意方法
                .method(ElementMatchers.nameContainsIgnoreCase("execute"))
                //委托
                .intercept(Advice.to(HttpClientRequest.class));


        new AgentBuilder.Default()
                .type(ElementMatchers.nameContainsIgnoreCase("org.springframework.web.servlet.DispatcherServlet"))
                .transform(dispatcherServletTransformer)
                .type(ElementMatchers.hasSuperClass(ElementMatchers.nameContainsIgnoreCase("org.apache.http.client.CloseableHttpClient")))
                .transform(httpClientTransformer)
                .installOn(instrumentation);
````

all  ways  this  only transformer     org.springframework.web.servlet.DispatcherServlet.doDispatch  works and transformer org.apache.http.client.CloseableHttpClient.execute not works  ，when I  remove org.springframework.web.servlet.DispatcherServlet.doDispatch  ,then org.apache.http.client.CloseableHttpClient.execute  works。

how  can  I   solve  this

**Comment by raphw** [comment]
That should not be an issue unless one class is loaded while the other instrumention is applied.

Did you add a listener to see if there is an error?

**Comment by cor0ps** [comment]
thanks  this way  is right,I  debug it my write problem.but  now     I have new problem now，when class  not loaded  ，i transform this class but  not works。
```
  new AgentBuilder.Default()   
                .type(ElementMatchers.nameContainsIgnoreCase("com.xxxxxx.FilterHttpServletRequest"))
                .transform(wsfFilterTransformer)
                .with(new FlowListener())
                .installOn(instrumentation);
```

FlowListener  I  write class  to file.  but  FilterHttpServletRequest always  not works  and  this file  not create.  how  can  I  solve it

**Comment by cor0ps** [comment]
i solve it
