### ISSUE TITLE
Samples: Why some methods are not exists?

### ISSUE THREAD

**Issue by Bizarrus** [raphw/byte-buddy#1511]
I've tried to use byte-buddy with their examples. But why some methods are not available?

![image](https://github.com/raphw/byte-buddy/assets/1371300/cfb0004d-40db-4b35-8200-805955c071cc)

```!java
import net.bytebuddy.*;
import net.bytebuddy.dynamic.*;
import net.bytebuddy.dynamic.loading.*;
import net.bytebuddy.implementation.*;
import net.bytebuddy.pool.*;

class Foo {
  public String bar() { return null; }
  public String foo() { return null; }
  public String foo(Object o) { return null; }
}

public class Test {
	public Test() {
		try {
			Foo dynamicFoo = new ByteBuddy()
			  .subclass(Foo.class)
			  .method(isDeclaredBy(Foo.class)).intercept(FixedValue.value("One!"))
			  .method(named("foo")).intercept(FixedValue.value("Two!"))
			  .method(named("foo").and(takesArguments(1))).intercept(FixedValue.value("Three!"))
			  .make()
			  .load(getClass().getClassLoader())
			  .getLoaded()
			  .newInstance();
		} catch(Exception e) {
			e.printStackTrace();
		}
		
	}
	
	public static void main(String[] args) {
		new Test();	
	}
}
```

**Comment by raphw** [comment]
What do you mean by that? There are no methods invoked in your sample, you only construct the instance.

**Comment by Bizarrus** [comment]
Please use the simple samples on the website.
Create a new project in `eclipse`, add `byte-bussy` & `ASM` libs and create the class above in the question.

You will see that some methods like `isDeclaredBy` or `names` not exists.

**Comment by raphw** [comment]
They are static imports by ElementMatchers.

**Comment by Bizarrus** [comment]
Please explain yor answer.

On the site only following informations are available:

> Byte Buddy is a light-weight library and only depends on the visitor API of the Java byte code parser library [ASM](https://asm.ow2.org/) which does itself [not require any further dependencies](https://search.maven.org/remotecontent?filepath=org/ow2/asm/asm/4.2/asm-4.2.pom).

For that, i have cloned the `byte-buddy` repo, build it with `nvm package` and packed the builded `.jar` and the `.jar` from ASM in my project folder.

**Comment by Bizarrus** [comment]
I had tried it with `IntelliJ` (`Gradle`), here the same Problem:

![image](https://github.com/raphw/byte-buddy/assets/1371300/76a61881-7a62-44f9-878d-c1131d1fb5c7)

**Comment by raphw** [comment]
In Java, you need to inport symbols. Normally, your IDE gives you suggestions in the context menu.
