### ISSUE TITLE
None of [] allows for delegation from static org.spiderflow.aop.HttpConnection$Response org.spiderflow.aop.HttpConnection$Response.execute(org.jsoup.Connection$Request) throws java.io.IOException

### ISSUE THREAD

**Issue by 365code365** [raphw/byte-buddy#1515]
the method  like this, method without public、private、protected
![image](https://github.com/raphw/byte-buddy/assets/102890485/96394d97-6774-48a8-908e-d31b8e98c431)

 public void init() {
        TypePool typePool = TypePool.Default.ofSystemLoader();

        new ByteBuddy()
                .redefine(typePool.describe("org.jsoup.helper.HttpConnection$Response").resolve(),
                        ClassFileLocator.ForClassLoader.ofSystemLoader())
                .method(ElementMatchers.isStatic()
                        .and(ElementMatchers.named("execute")))
                .intercept(MethodDelegation.to(new Interceptor()))
                .make()
                .load(ClassLoader.getSystemClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                .getLoaded();

    }

**Comment by raphw** [comment]
How does your interceptor look like?
