### ISSUE TITLE
Bump maven version to avoid known vulnerability

### ISSUE THREAD

**Issue by joycebrum** [raphw/byte-buddy#1524]
Hi, I'd like to suggest that byte-buddy bump the maven version used to avoid the known vulnerability [GHSA-2f88-5hg8-9x2x](https://osv.dev/vulnerability/GHSA-2f88-5hg8-9x2x) that was fixed in the 3.8.1 version.

I'm suggesting together with this issue a PR bumping the version, let me know if you have any concerns.

Thanks!

Disclosure:
I'm Joyce from Google and I'm working with the OpenSSF to improve the supply-chain security in many open source projects.

**Comment by raphw** [comment]
All Maven dependencies are only *provided* meaning that they will normally be supplied by Maven, but not by the created artifact. This choice is to allow older Maven versions to use Byte Buddy, too. It is however up to the user to keep their Maven version up to date.
