### ISSUE TITLE
Questions on instrumenting HttpURLConnection (part of Android SDK) api calls using byte buddy android plugin

### ISSUE THREAD

**Issue by surbhiia** [raphw/byte-buddy#1526]
As the Android SDK classes like HttpURLConnection can’t be instrumented, an alternative is to instrument all calls to HttpURLConnection APIs which are in android application code itself. For that, it will be required to visit all application code classes and visit all methods and visit all instructions of a method to identify if any of it is a method call to HttpURLConnection APIs. I plan to use byte buddy android plugin and Advice API to do it. But I want to wrap a particular bytecode instruction ( invokevirtual calls to any of the HttpURLConnection APIs ) with before / after / throw methods. I do not want to wrap a particular method. I did not find a way to do that. Is it possible with any other byte buddy APIs? If I create a custom ClassVisitor, can I wrap it into an AsmVisitorWrapper so it can be supplied to DynamicType.Builder<?> builder.visit() inside apply method of my plugin so I can use this plugin with Byte buddy android plugin library to do compile time instrumentation. 

One other concern I had was that as this plugin would apply to all application code classes, it might increase build time. Have you come across any such byte buddy android plugin usage where a plugin applies to all classes and would you know the performance impact of that? Any suggestions to prevent a huge increase in build time while still looking at all classes? 

Thanks a lot!

**Comment by raphw** [comment]
The functionality you are looking for is called `MemberSubstitution`, where you can replace all interactions with a different method of your choice. Byte Buddy also supports Android builds: https://github.com/raphw/byte-buddy/tree/master/byte-buddy-gradle-plugin/android-plugin

**Comment by surbhiia** [comment]
Thanks @raphw! Sorry, I did not link to all the things I was referring to in my question. By planning to use byte buddy android plugin - I did mean the same repo that you referred to above. I will look into MemberSubstitution API you linked above and get back to you with more questions if any.

**Comment by surbhiia** [comment]
Hi @raphw, I’m trying to use MemberSubstitution APIs to replace **connection.getResponseCode()** instruction with **replacementForResponseCode(connection)**.  “replacementForResponseCode(connection)” is not present in android application code which calls “connection.getResponseCode()” but it is present in a separate instrumentation library codebase which android application depends on as shown below. There are a few issues I’m facing, it would be really helpful if you could suggest some things I can try to resolve these. Thanks a lot! 

**Issues**
1. Byte buddy plugin is unable to find calls like **connection.getResponseCode()** [it was successfully able to find calls like **getResponseCode()** - which are not invoked on a connection object instance, when I used _**.method(named(“getResponseCode”)**_)]
2. It is unable to find **replacementForResponseCode** method from the instrumentation library codebase. 
3. I also want to pass the connection object to the replacement method. so I want to effectively call “replacementForResponseCode(connection)” . Is that possible? 
4. I have a list of around 10 methods like “connection.getResponseCode()” which need to be replaced with 10 other methods like “replacementForResponseCode(connection)”. Is it possible to do this in one byte buddy plugin or I will need 10? 

**Byte buddy Plugin apply code**

```
try {
    return builder.visit(MemberSubstitution.strict()
            .method(is(**HttpURLConnection.class.getDeclaredMethod("getResponseCode")**))          //Issue 1
            .replaceWith(**ReplacementMethods.class.getDeclaredMethod("replacementForResponseCode")**)     //Issue 2
            .on(isMethod()));
} catch (NoSuchMethodException e) {
    throw new RuntimeException(e);
}
```

**Another library artifact that contains replacement methods**

```
class ReplacementMethods {

public void replacementForResponseCode(URLConnection connection){
	//Before
	connection.setRequestProperty(“Custom Header”, “DummyValue”);
	
	//Actual surrounded by throw
	try {
		String responseCode = connection.getResponseCode();
	} catch(IOException e){
		reportError();
	}

	//After
	reportSuccess();       
}}
```

**Android Application activity code that is instrumented**

```
URL url = new URL("http://httpbin.org/headers");
HttpURLConnection httpURLConnection = (HttpURLConnection) url.openConnection();
String responseCode = httpURLConnection.getResponseCode();
String responseMessage = httpURLConnection.getResponseMessage();
```

**Android Application gradle dependencies**
```
bytebuddy(…plugin containing artifact)
implementation(… library artifact containing replacement methods class)
```

**Comment by raphw** [comment]
I would assume your replacement method should be static? Is there no exception or anything? Worst case, intercept the visitMethod method in the MemberSubstitution with a debugger to see why the methods are not matched.

**Comment by surbhiia** [comment]
Thanks @raphw for your suggestions. Changing to static did not work. I debugged to get to the exact error. It is - The replacement class (containing replacement method) is not assignable to the class that contains the method call to be replaced (attaching screenshots). It is coming on MemberSubstituion line 1269 as shown in screenshot below. 

But I think the replacement class should be assignable to “java.lang.Object” but that check fails. It checks that in TypeDescription line 7767 (attached screenshot) but that gives false and if condition is not executed.  

(Ignore the okhttp3 word in package names in below screenshots. I was using an old setup to test for HttpURLConnection use case.)

**Exception string**
<img width="1317" alt="Screenshot 2023-10-16 at 3 35 50 PM" src="https://github.com/raphw/byte-buddy/assets/138259843/6ef2c531-f602-4f39-939f-595a0429ecbe">

**Exception string continued**
<img width="835" alt="Screenshot 2023-10-16 at 3 38 22 PM" src="https://github.com/raphw/byte-buddy/assets/138259843/88196f68-1371-4221-bc87-e7fcf792da0d">

**MemberSubstitution Line 1269 where error occurs**
<img width="1288" alt="Screenshot 2023-10-16 at 4 38 39 PM" src="https://github.com/raphw/byte-buddy/assets/138259843/958c8e12-250a-4ce9-ac26-9fd304fbe23b">

**Debug values for MemberSubstitution Line 1269 when error occurs**
<img width="1034" alt="Screenshot 2023-10-16 at 4 39 56 PM" src="https://github.com/raphw/byte-buddy/assets/138259843/cf9d556f-13c3-4ed7-8ff7-611f4830b9ae">

**Type Description Line 7767 which I think should have matched and no error should have occurred**
<img width="966" alt="Screenshot 2023-10-16 at 4 39 31 PM" src="https://github.com/raphw/byte-buddy/assets/138259843/e6b4f989-c1d5-4a4e-9e60-1ebb7de0c703">

**Comment by raphw** [comment]
This does not look right from the error message. Was it not `replacementForResponseCode` you wanted to substitute with?

**Comment by surbhiia** [comment]
@raphw Actually what I put in the code snippets here in my previous comment was a representation of what I was doing but the names in my actual code are different. I assure you there's no issues with the method naming. In my actual code the method name is surbhiReplacementMethod()

**Comment by raphw** [comment]
Can you try with a trivial class:

    public class Sample {
      public static int replacementForResponseCode(URLConnection connection) {
        return 0;
      }
    }

That is what should do the trick.

**Comment by surbhiia** [comment]
Thanks a lot @raphw. Super grateful for your help! I tried a trivial class like you suggested and it worked! I was even able to add other parts of my code to this class and test and it worked. Not sure what was going wrong with the previous class. 

It solved issues 1 - 3! The only question I have now is - 
I have a list of around 10 methods like “connection.getResponseCode()” which need to be replaced with 10 other methods like “replacementForResponseCode(connection)”. Is it possible to do this in one byte buddy android plugin or I will need 10?

**Comment by raphw** [comment]
You can stack them. This is the most effective way anyways.

**Comment by mmgzentertainment** [comment]
can bytebuddy instrument telephonyManager.networkOperator directly within an app?

**Comment by surbhiia** [comment]
@raphw I tried looking for ways to stack byte buddy plugins but didn't find any. Can you please elaborate how to do that or point me to any available examples. Thanks!

**Comment by surbhiia** [comment]
@raphw I tried to look for ways I can stack multiple byte buddy plugins into one, but didn't find any. Can you please elaborate or point out any available examples to do so? Did you mean using the StackManipulation APIs to define a series of transformations in one DynamicType.Builder.visit method? If so, can you please share a way to stack let's say the below two: 

**Replacing getResponseCode**
`  return builder.visit(MemberSubstitution.strict()
                    .method(is(HttpURLConnection.class.getDeclaredMethod("getResponseCode")))
                    .replaceWith(Sample.class.getDeclaredMethod("replacementForResponseCode", URLConnection.class))
                    .on(isMethod()));`

**Replacing getResponseMessage**
```
return builder.visit(MemberSubstitution.relaxed()
                    .method(is(HttpURLConnection.class.getDeclaredMethod("getResponseMessage")))
                    .replaceWith(Sample.class.getDeclaredMethod("replacementForResponseMessage", URLConnection.class))
                    .on(isMethod()));
```

**Comment by raphw** [comment]
Have a looke at the replacement chain where you can add methods with custom arguments,  based on annotation.
