### ISSUE TITLE
Hooking native function succeeds in some cases and fails in others.

### ISSUE THREAD

**Issue by dre4merp** [raphw/byte-buddy#1536]
I want to use `enableNativeMethodPrefix` to hook Native methods,
There is no problem with the following code under jdk8 and jdk19
But under jdk9 and jdk11, if the `java.lang.ProcessImpl` class **has been loaded**, the listener will not report an error, but the `java.lang.StackOverflowError` error will appear when executing the modified code.

``` java
    //java.lang.UNIXProcess
    ElementMatcher<? super TypeDescription> classMatcher = advice.getClassMatcher();
    //forkAndExec(I[B[B[BI[BI[B[IZ)I
    ElementMatcher<? super MethodDescription> methodMatcher = advice.getMethodMatcher();

   AgentBuilder nativeAgentBuilder = new AgentBuilder.Default()
        .enableNativeMethodPrefix("foo")
        .ignore(ElementMatchers.none())
        .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
        .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
        .with(AgentBuilder.TypeStrategy.Default.REBASE);

    AgentBuilder.Transformer transformer;
    ResettableClassFileTransformer resetAgentBuilder;

    transformer = (builder, typeDescription, classLoader, module, protectionDomain) -> builder
        .method(methodMatcher)
        .intercept(net.bytebuddy.asm.Advice.to(MethodInterceptors.class));
    resetAgentBuilder = nativeAgentBuilder
        .type(classMatcher)
        .transform(transformer)
        .installOn(instrumentation);
```
Here is the Error
``` text
java.lang.StackOverflowError
	java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	org.apache.jsp._004_002dcommand_002d2_jsp._jspService(_004_002dcommand_002d2_jsp.java:144)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:465)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:383)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:331)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
```

I would like to ask if there is a problem with my code, or is it caused by different jdk differences?

I saw in this issue [#1439](https://github.com/raphw/byte-buddy/issues/1439) that you mentioned that the hook cannot be performed if the class is already loaded, but after testing, it can work normally in the jdk8 environment.I want to know how to make it work in other versions of jdk as well

**Comment by raphw** [comment]
Not sure how your `MethodInterceptors` looks like, but normally, you want to apply `Advice` as visitor, not as interceptor.

**Comment by dre4merp** [comment]
Here is the `MethodInterceptors` . I'm sorry for that can't show more code. But it runs normally in jdk8 and jdk19, and the reason why `StackOverflowError` appears when I debug seems to be that the bytecode becomes NULL, which has nothing to do with the code of `onMethodEnter`.

``` java
public class MethodInterceptors {

    @OnMethodEnter
    public static void onMethodEnter(
        @This(optional = true) Object instance,
        @Origin Method method,
        @AllArguments Object[] parameters) {
       
         // foo

    }

    @OnMethodExit(onThrowable = RuntimeException.class)
    public static void onMethodExit(
        @This(optional = true) Object instance,
        @Origin Method method,
        @AllArguments Object[] parameters,
        @Thrown Throwable thrown,
        @Return(typing = Assigner.Typing.DYNAMIC) Object result) {

        // foo

    }

}
```

The crux of the problem is that it works fine under jdk8 and jdk19, but cannot work under jdk9 and jdk11. I want to know why this problem occurs.

**Comment by dre4merp** [comment]
> Not sure how your `MethodInterceptors` looks like, but normally, you want to apply `Advice` as visitor, not as interceptor.

I know that advice is often used together with visit, but for native functions, it does not work. On the contrary, using the interceptor, I can normally hook the function to execute my code and continue to call the original code of the function.

**Comment by raphw** [comment]
Did you try to extract the byte code for the different JDKs and compare it with javap? If it is identical, there's likely a JDK bug. This feature is poorly tested.

You cannot use visit with native method prefixes as the method needs to be replaced.

**Comment by dre4merp** [comment]
I have found the problem, which is caused by me modifying a class multiple times. Sorry for wasting your time.
