### ISSUE TITLE
[performance] Regarding bytecode instrumentation performance optimizations

### ISSUE THREAD

**Issue by dogourd** [raphw/byte-buddy#1546]
During bytecode instrumentation, we can add `IgnoreMatcher` to avoid processing some class files. This can effectively avoid some performance overhead, but there is still room for improvement.

One obvious issue is that `IgnoreMatcher` takes a `TypeDescription` from ByteBuddy's internals, which is expensive to obtain when the javaagent uses DescriptionStrategy.POOL_ONLY for good compatibility.

In reality, most `IgnoreMatcher`s only care about typename and classLoader. This information is already provided in `ClassFileTransformer`, parsing the type is unnecessary in most cases, so skipping it could bring significant performance gains.

I've read ByteBuddy's code for supporting class file transformations. Currently I can think of two ways to improve this:

1. Add a custom `DescriptionStrategy`. When checking if a type should be ignored, create a special `TypeDescription` for it. Do further checking in `IgnoreMatcher` and `TypeMatcher` to ignore it. The advantage is ByteBuddy itself doesn't need changes. The downside is performance is not maximized, because some logic around `ResubmissionEnforcer`, `ClassFileBufferStrategy`, `PoolStrategy` cannot be skipped - they always run before `DescriptionStrategy`.
2. Add a custom `TransformerDecorator` and do simple checking internally to ignore some types, skipping the transformation logic entirely. This maximizes performance, but requires some modifications to ByteBuddy itself. Because `IgnoreMatcher` is still needed during the redefinition phase to decide which types to redefinition,  currently we cannot "slim down" the `IgnoreMatcher` unless `AgentBuilder.installOn` allows passing a custom `RawMatcher` to decide which types to redefinition.

Does ByteBuddy have a more recommended approach for this? Would overloading `AgentBuilder.installOn` with this be worthwhile?

**Comment by dogourd** [comment]
This is strange. During testing, I did see significant performance gains after moving some matching logic inside `DescriptionStrategy`. Specifically, what originally took **16 seconds** for a full transformation could now complete in **12 seconds** after moving it. I will investigate further and provide an update here or close this issue.

**Comment by dogourd** [comment]
I think I've found it. In the `DescriptionStrategy` implementation, classes get passed to `TypePool.describe(String name)`, which leads to a lot of `LazyTypeDescription` instances being created and TypePool cache(`TypePool.CacheProvider`) accesses, even if those TypeDescriptions are not used. 
For each type, these operations are negligible, but as the processing scale grows, their impact on performance becomes noticeable.

When I implement a blacklist in `DescriptionStrategy` to match on type names and avoid calling `TypePool.describe` on matching types, the whole process becomes much faster. In my environment, it went from 16 seconds down to 12 seconds, reducing 4 seconds (about 25% performance gain). This should correlate to the size of the blacklist - the more classes matched and avoided, the more significant the gains.

Does ByteBuddy have a standard way to do this? Should I return a specially marked `TypeDescription` instance from `DescriptionStrategy`? Or throw a NoSuchTypeException here? Or is there a more standard API to accomplish this?

**Comment by raphw** [comment]
Good point. I might move the caching below the lazy type description level. I'll consider this as an improvement.

You can filter by name in a wrapper for the class file transormer otherwise where raw values are passed before delegation.

**Comment by dogourd** [comment]
If filtering is implemented internally in the `ClassfiletransformerDecorator`, should BB consider overloading `installOn` to allow users to pass in a custom `RawMatcher`?

In the current implementation, ignoreMatcher is used in `ExecutingTransformer` to decide if a type should be ignored during transformation, and also in `RedefinitionStrategy` to decide if a type should be retransformed. So to ensure `RedefinitionStrategy` is consistent with previous behavior, we need to retain the ignoreMatcher config and essentially reimplement the matching logic again in the `ClassfileTransformerDecorator`. This results in expected types (name, classloader, etc - basic info available in `ClassfileTransformer`) being matched twice - **once in the decorator** and **once in ExecutingTransformer**.

If `installOn` allowed passing in a `RawMatcher` (`AgentBuilder.installOn(Instrumentation inst, RawMatcher redefinitionMatcher)`), we could slim down the ignoreMatcher in `ExecutingTransformer` to avoid an extra matching action. Do you think this would be appropriate and worthwhile to do?

**Comment by dogourd** [comment]
This approach should be ineffective when using `DescriptionStrategy.POOL_FIRST`. Internally, POOL_FIRST uses the `resolution.isResolved()` method, which still causes `LazyFacade` to **immediately** access the TypePool. 

In theory, `LazyFacade` should have a significant effect for `POOL_ONLY`, but unfortunately in my test project it had little impact, improving only by milliseconds. This is vastly different from the 4 seconds improvement gained by directly modifying the `DescriptionStrategy`.

**Comment by raphw** [comment]
Did you try the default `HYBRID`?

The idea of pool first is that the resolution is attempted eagerly.

**Comment by dogourd** [comment]
I'm afraid I don't want to use `HYBRID`, since I switched from `HYBRID` to `POOL_FIRST`. `HYBRID` is more likely to eagerly load some types compared to `POOL_FIRST`, which is not the behavior I want.

I've done some further observation of where time is spent, and in my project the main hot path is :  
`RedefinitionStrategy#make` -> `Collector#consider` -> `DescriptionStrategy#apply` -> `TypePool`.   
Due to some legacy reasons, I'm using the `DiscoveryStrategy.Reiterating` strategy, which exacerbates the performance impact of this execution path.

I'm considering adding a custom `DescriptionStrategy` that internally uses some simple blacklist matching to skip `TypeDescription` instance creation and frequent `TypePool` accesses.

**Comment by raphw** [comment]
I see! I would suggest that you'd go for your solution, I do not want to break contracts from the current API. Most people will use HYBRID, I assume and for those, the current change is a good improvement. Thanks for pointing it out!
