### ISSUE TITLE
the new Version of AgentBuilder.Transformer.transform()  can't support current application with byte-buddy of 1.10.21

### ISSUE THREAD

**Issue by ljqseu** [raphw/byte-buddy#1551]
our applications use the byte-buddy of  version 1.10.21, it has four parameters in the AgentBuilder.Transformer.transform().
However ,in the version 1.14.8, it has five parameters in the AgentBuilder.Transformer.transform().
The new parameter of ProtectionDomain is useless for us ,but the application have to restart to reload the new transform,which is very ugly for user.

so , can you  reserve  the  transform method with four parameters in the new version ,which is very kind for the current application.thank you very much.

![image](https://github.com/raphw/byte-buddy/assets/50127039/dee4f675-ea6a-4a9f-9f8a-30054d0e4785)

**Comment by raphw** [comment]
Not sure I follow? If you dynsmically reload your agent with a new version of Byte Buddy, why can't you reload the linked code?

**Comment by ljqseu** [comment]
已收到阁下邮件，谢谢!                                   刘家强

**Comment by ljqseu** [comment]
in our program ,the linked code is reload into bootstrap classloader .When reload the agent ,it will use last transform method, not the new one.
Could you please add Transformer.transform() with four paramenters in the new version.

**Comment by raphw** [comment]
No, the method is part of a functional interface.

By adding Byte Buddy to the boot loader, it's not updateable anyways, though

**Comment by ljqseu** [comment]
已收到阁下邮件，谢谢!                                   刘家强
