### ISSUE TITLE
Does not work in Databricks Container Services

### ISSUE THREAD

**Issue by mondal-alex** [raphw/byte-buddy#1552]
Hi Byte Buddy community,

My team builds a java application that uses byte buddy (brought in as a transitive dependency of hibernate-core).

We use our application in the Databricks cloud, with Docker container services. However, byte-buddy is breaking the environment: we cannot access any of our java objects (not found error). As soon as byte buddy is removed, everything works as expected.

We contacted Databricks support, and they said we need to reach out to you all.

Perhaps the issue we are seeing is related to this thread (Docker): https://github.com/raphw/byte-buddy/issues/1469. What I am looking for is instructions and documentation of how to get byte buddy to work in Docker containers.

Thanks 🙂

**Comment by raphw** [comment]
Byte Buddy in itself is just a library when used via Hibernate. If you remove it, you'd have a different app. I can't see how BB breaks your environment. It's likely the code that is removed with it.
