### ISSUE TITLE
AgentBuilder.RedefinitionStrategy.RETRANSFORMATION will cause method lost parameter names

### ISSUE THREAD

**Issue by yangrubing** [raphw/byte-buddy#1562]
## Description 
I am using ByteBuddy 1.12.13 to do bytecode enhancement , and it works well in most cases. Recently , our colleage report their app cann't get methods' parameter's name (they need parameter name to parse SpEL and already compiled their app with `-parameters`). 
Then, I checked our instrumentation code like below .
```java 
    protected ResettableClassFileTransformer buildClassFileTransformer(Instrumentation inst) {
        final ByteBuddy byteBuddy = new ByteBuddy().with(TypeValidation.of(false));
        InstrumentationListener instrumentationListener = new InstrumentationListener();
        AgentBuilder agentBuilder = new AgentBuilder.Default(byteBuddy)
                .ignore(getAgentBuilderIgnoreCondition())
                .with(new AgentBuilder.CircularityLock.Default())
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(new AgentBuilder.InjectionStrategy.UsingUnsafe.OfFactory(ClassInjector.UsingUnsafe.Factory.resolve(inst)))
                .with(new AgentBuilder.InitializationStrategy.SelfInjection.Eager())
                .with(instrumentationListener)
                .disableClassFormatChanges();

        ElementMatcher.Junction<Object> typeMatcher = getTypeMatcher();
        if (typeMatcher == null) {
            logger.info("Element type matcher for {} is null, will not do the transform", this.getClass());
            return null;
        }
        ResettableClassFileTransformer transformer = agentBuilder.type(typeMatcher).transform(getTransformer()).installOn(inst);
        instrumentationListener.outputLog(true);
        return transformer;
    }
``` 
And , I tested in my laptop the parameter name seems did lost
```java
    @GetMapping("/param")
    public String param(String test) {
        try {
            return HelloController.class.getMethod("param", String.class).getParameters()[0].getName(); 
        } catch (NoSuchMethodException e) {
            throw new RuntimeException(e);
        }
    }

// OUTPUT: arg0  , should return test
```
And above code return `arg0` which means the parameter names are lost . 
**And I tried to modify our instrumentation code , only change the  `.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)` to `.with(AgentBuilder.RedefinitionStrategy.REDEFINITION)` make our code work and the test code return 'test' correctly.**

## Ask for  help 
- What's the difference between `AgentBuilder.RedefinitionStrategy.RETRANSFORMATION` and `.with(AgentBuilder.RedefinitionStrategy.REDEFINITION`?And why `AgentBuilder.RedefinitionStrategy.RETRANSFORMATION` behavior differenly ?
- Is it OK to use `AgentBuilder.RedefinitionStrategy.REDEFINITION` instead of `AgentBuilder.RedefinitionStrategy.RETRANSFORMATION`?

**Comment by yangrubing** [comment]
I compared the REDEFINITION and RETRANSFORMATION approaches and use jad to decopile the enhanced classes, and found the generated code are the same , even more confused now

**Comment by raphw** [comment]
This is unfortunately a bug in the JDK which forgets reconstruction of parameter names in some builds.

The difference is wether `Instrumentation.redefineClasses` or `Instrumentation.retransformeClasses` is used.

**Comment by raphw** [comment]
It's only the call to the VM. Since Java 6, retransformation is the preferred way.

**Comment by yangrubing** [comment]
Very helpful, thanks a lot, you are doing a great job👍

**Comment by yangrubing** [comment]
Sorry to reopen this again because I am more confused now , here is my code 
<img width="1010" alt="image" src="https://github.com/raphw/byte-buddy/assets/12846398/699a30b3-dd73-494f-aa78-3b1b65b7f714">
The `param` method is my target method , and my `ResettableClassFileTransformer`
<img width="1258" alt="image" src="https://github.com/raphw/byte-buddy/assets/12846398/52d15f77-3f95-413c-af3b-a7388084fcb3">
My `interceptor` class
<img width="612" alt="image" src="https://github.com/raphw/byte-buddy/assets/12846398/a42a01fa-6c00-4b53-ba20-997b91c3b652">

And I dumped class generated by bytebuddy by using `-Dnet.bytebuddy.dump` , and I got two class in my directory 
<img width="1099" alt="image" src="https://github.com/raphw/byte-buddy/assets/12846398/333a0037-4cf4-4744-9489-4338b373725e">
And then I executed `javap -v ` for both classes, and both the class file don't have `MethodParameters` table in the output 
<img width="440" alt="image" src="https://github.com/raphw/byte-buddy/assets/12846398/6ad088d6-b486-4d0c-97bb-5a3c357f026b">

**Even the original class doesn't have MethodParameters ** 

And I can confirm I compiled the class with `-parameters` as the class generated by my IDE indicated the `MethodParameters` exists  as show below .
<img width="470" alt="image" src="https://github.com/raphw/byte-buddy/assets/12846398/856af760-8a64-4c4a-8748-595ec40a8728">

<img width="808" alt="image" src="https://github.com/raphw/byte-buddy/assets/12846398/8a67aff8-913a-467d-8f9f-67dd3eb8325b">
So could you please help make this clear, why even the  origin class don;t have `MethodParameters` in the class file , thank you in advance.

**Comment by raphw** [comment]
This is a JVM bug. In Mockito, we work around it like this: https://github.com/mockito/mockito/blob/757b37a1445be3abd08238c0da62a9a9e635f1ba/src/main/java/org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator.java#L398

**Comment by yangrubing** [comment]
Thanks , tried the solution and it works now ,BTW , will this issue be fixed in later bytebuddy release ?

**Comment by raphw** [comment]
This is already fixed in newer JVM versions, I hope this just dies off.

**Comment by yangrubing** [comment]
Thanks.
