### ISSUE TITLE
Instrumenting two methods with the same Advice class

### ISSUE THREAD

**Issue by rupinder10** [raphw/byte-buddy#1568]
I have a class with two similar methods but with a different set of arguments. For example these are two methods:

```
public static void sendMessage(String id, String message)
public static void sendMessage(String message)
```

The Advice class for instrumenting the first method is:
```
 @Advice.OnMethodEnter(suppress = Throwable.class)
  public static void onEnter(@Advice.Argument(1) String message) throws Throwable {
        //TODO: Instrumenting logic here
  }
``` 

The instrumenting logic is the same for the second method but the argument number is 2 instead of 1. Is there a way for me to use the same Advice class for both methods or do I have to duplicate the code with just a different argument number ?

**Comment by rupinder10** [comment]
Did you mean Advice.withCustomMapping() ?
________________________________

**Comment by raphw** [comment]
Yes, indeed.
