### ISSUE TITLE
VerifyError: Expected stackmap frame at this location

### ISSUE THREAD

**Issue by orange-buffalo** [raphw/byte-buddy#157]
Hi,

I am facing verification error when using  `@OnMethodExit` Advice:
```
java.lang.VerifyError: Expecting a stack map frame
Exception Details:
  Location:
    org/h2/jdbc/JdbcPreparedStatement.setArray(ILjava/sql/Array;)V @7: goto
  Reason:
    Expected stackmap frame at this location.
```
I have prepared a reproducible [test sample for this case](https://github.com/raphw/byte-buddy/files/380439/byte-buddy-test.zip). 

The error appeared after upgrade from 1.4.6 to 1.4.14, on old version the problem did not exist.

**Comment by raphw** [comment]
Thanks for the report. This is a problem with a recently added optimization for methods that cannot return regularly, i.e. always `throw` an exception. I will fix this with the next release.

**Comment by raphw** [comment]
Fixed on master.

**Comment by orange-buffalo** [comment]
Cool, thank you!
