### ISSUE TITLE
What is the best way to create setters and getters by field name?

### ISSUE THREAD

**Issue by PavelTurk** [raphw/byte-buddy#1570]
I am working on project that needs to set and get values to/from instances of different classes by field name automatically. For example:

Let's suppose we have class Person:

```
public class Person {

   private String name;

   private String surname;
   + setters and getters
}
```
And we have row with data:

```
name     | surname
---------|---------
John     | Black
```
And it is necessary to load these data to instance  `var person = new Person()` automatically. 

This is just a small example. Real situation - about 50 classes with 8 - 15 fields in every class.

The only solution I found (using byte-buddy of course) is to create dynamically classes for every field. I mean, for Person.name the following class is created:

```
public class PersonName implements SetterGetter<Person, String> {

    public void set(Person p, String value) {
             p.setName(value);
    }

    public String get(Person p) {
          return p.getName();
    }
}
```
So, when we have `name` in data we take instance of `PersonName` and pass data and instance of `Person` to it. This solution works and it is very fast. However, such solution needs to create too many classes and it confuses me. I feel, that I am doing something wrong. 

Could anyone say what is the best strategy to solve such problems?

**Comment by raphw** [comment]
I would use `MethodHandle`s for this and not code generation. Handles are as fast as regular code, more or less, as long as you keep the handles cached. I assume you are on Java 8+.
