### ISSUE TITLE
Cannot resolve `In` from class `zio.cache.Cache$$anon$1`

### ISSUE THREAD

**Issue by jxnu-liguobin** [raphw/byte-buddy#1577]
This is Scala, since the minimum reproduction code is uncertain at this point, a guess would be something like this:
```scala
abstract class Cache[-Key, +Value]:

  def get(key: Key): Value

object Cache:

  def make[In, Key, Value](keyBy: In => Key) = new Cache[In, Value]:
    override def get(in: In): Value = ???
```

The full code is here
https://github.com/zio/zio-cache/blob/series/2.x/zio-cache/shared/src/main/scala/zio/cache/Cache.scala

**Comment by raphw** [comment]
I would assume that there is an issue in the Scala compiler here. Did you try to resolve the type variables using Java reflection? It would normally result in the same error.

**Comment by jxnu-liguobin** [comment]
> I would assume that there is an issue in the Scala compiler here. Did you try to resolve the type variables using Java reflection? It would normally result in the same error.

Are you referring to the get method for reflecting Cache instances? But what I got was the Object

**Comment by raphw** [comment]
If you get hold of zio.cache.Cache$$anon$1 Class representstion, and call methods for getting generic types on it, I'd assume it yields similar exceptions.
