### ISSUE TITLE
Verify Error on Byte Buddy generated class

### ISSUE THREAD

**Issue by gmondelli-hub** [raphw/byte-buddy#1589]
I created this maven library project in spring-boot for creating excel and csv reports.
The project uses the **Byte Buddy library** to generate runtime dynamic classes necessary for the purpose of the project.

I tested the correct functioning of this library as a dependency of spring-boot projects having datasource configurations and only with embedded tomcat servers provided by the Spring Tool Suite IDE (version: 3.9.12.RELEASE).

The problem, as shown in the screenshots, is if I try to start the Spring application from the command line (java -jar) or with different IDEs I get a **VerifyError for corrupt bytecode**:

![image](https://github.com/gmondelli-hub/quick-generated-report/assets/159120392/5220530b-7040-4e56-8203-a0896e438752)

In the error shown in the figure, the **ViwSanVerextStatoFornReportRow class is the ReportRow class generated** from the ViwSanVerextStatoForn JPA Entity component.

Are there any suggestions or reasons for this kind of problem? 

Issue already created here: [issue](https://github.com/gmondelli-hub/quick-generated-report/issues/1)

**Comment by raphw** [comment]
It seems like a constructor is instrumented incorreclty. This is a user error. Constructors must not use `this` other than for setting fields before the super constructor is invoked.
