### ISSUE TITLE
type(named(...))  is invalid

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#159]
i update version to 1.4.15 and 
```
new AgentBuilder.Default().with(DebugListener.getListener())
.type(named("redis.clients.jedis.Connection"))
.transform(new RedisAdviceTransformer())
.installOnByteBuddyAgent();
```

is invalid,   does has changed usage in new verison?

now i found i need request my redis connection, byte buddy can interceptor this method

can i only startup my app(not to request redis) byte buddy interceptor this method?

**Comment by raphw** [comment]
What do you mean by *invalid*? There are no changes that should make a difference in your example. What version were you using previously?

**Comment by dragontree101** [comment]
previously version is 1.3.19,  previous i startup app it can intercept, but i use 1.4.15 it intercept when i call method.

**Comment by raphw** [comment]
Please have a look at the release notes and try incrementing Byte Buddy's version step by step. If you found the release version where you experience changed behavior, I might be able to tell you more.

**Comment by dragontree101** [comment]
i means in ```1.4.15``` version ，  
```
public class AdviceProfiledTransformer  implements AgentBuilder.Transformer{
  @Override
  public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder,
      TypeDescription typeDescription, ClassLoader classLoader) {
  }
}
```
will be call when i new AdviceProfiled() object ,  and 1.3.19 version call transform method when application startup

**Comment by raphw** [comment]
Byte Buddy is transforming your classes on demand. As long as the interception works, I do not think there is anything wrong here. If you migrate version-by-version and find the exact version number where things changed for you, I might be able to help you about what exactly it is that changed.

**Comment by dragontree101** [comment]
thanks, i am try which version.

**Comment by raphw** [comment]
Byte Buddy is not persuing any active life cycle. It is up to you to your application to load classes. The agent rather serves as a callback into the `defineClass` method of any `ClassLoader`.
