### ISSUE TITLE
why is the byte-buudy AgentBuilder source code so long ?

### ISSUE THREAD

**Issue by jiangyunpeng** [raphw/byte-buddy#1596]
No offense meant  , why is the byte-buudy AgentBuilder source code so long  ?  it's 12000+ line.  Is there any special reason for it?

**Comment by raphw** [comment]
It's because Byte Buddy uses nested classes for additional expressiveness. This way, it is `AgentBuilder.Default`, for example instead of `DefaultAgentBuilder`. This allows your IDE to give you additional help.

**Comment by jiangyunpeng** [comment]
thanks
