### ISSUE TITLE
Create Interface (not class)

### ISSUE THREAD

**Issue by DALDEI** [raphw/byte-buddy#16]
I have looked at a lot of ASM type libraries and was just starting on cglib when I ran into an issue with it and found your post about byte-buddy.  Trying this out, I really like it, although its a bit of a learning curve to figure out model so I can do what I think is obvious - but has a different representation in bb.

One thing I am stuck on.  I dont need this 100% but it would be very useful.  Most ASM tools assume (many with comments saying so) that there is no use for creating interfaces, only classes.
I would like to be able to create interfaces, ideally root (not derived) interfaces.
With cglib that was in fact the first thing I tried and got to work (although I dont like that it derives from an internal interface,   its not a top level one - but it is an interface)

I have tried about 20 ways to do to this with BB and scanned most of the source and and the web and cant find it.   Two strategies that got close were

interface I {} ;
... 
    new ByteBuddy().subclass(I.class, no-constrors ).name(...)... 

I got that to produce something that 'worked' but its a not an interface,  its 
   class name extends Object implements I

I see in the code where its switching the subclass to Object ... 

The other attempt is to use variations on this
 new ByteBuddy()
          .withModifiers(TypeManifestation.INTERFACE)
          .subclass(Object.class,ConstructorStrategy.Default.NO_CONSTRUCTORS)
                .name(name);

but that ends up crashing with null pointer exceptions in various places ... 
the superclass isnt null but its contents are uninitialized.

Is this possible ? I cant find anywhere that constructs a Builder for either an iterface,
or (related probably) without a superclass.

The Annotation support looks like its close ... 

I am curious if this is a fundamental difficulty with the JVM or ASM or if its simply something that noones ever asked for or thought of ..

I can live without it by making an abstract class but it seems a huge hole where the rest of the product has incredible depth.

-David

**Comment by raphw** [comment]
Hi David, your aproach is correct. If it throws a NullPointerException, you found a bug. ByteBuddy should never do this. I will test it later and might ask for a more detailed description. Expect a bugfix realease at the end of next week

**Comment by raphw** [comment]
Interfaces do not add the super flag which, until now, were always added to subclasses, including interfaces. Also, the default implementations of `ConstructorStrategy` did not consider the possibility of interfaces where the super classes are considered `null`. Both was fixed.

**Comment by raphw** [comment]
Byte Buddy 0.5.2 is released and it fixes the bug you found. Note that interface methods must be public. Also, implementations are only allowed on from Java 8.

**Comment by DALDEI** [comment]
Could you explain the last bit "Also, implementations are only allowed on from Java 8." ?
For various reasons I need to stay on Java 7 for a while more.

**Comment by raphw** [comment]
I mean a default method implementation. When you define an interface method, it needs to be abstract as long as the byte code version is not 52 (Java 8).

**Comment by DALDEI** [comment]
Ah yes of course !  Cant create bytecode for a JVM version thats compatible with the running one.
Just tried the new code, works perfect !
Took a few mistakes (mine) to get it right ... (missed at first that the function(Type...) could take no args) and then copy pasted the wrong code and put a field instead of a method.
But got it right! 
Thank you !

Future request ... (way future) ... validate builder operations as they occur 
as well as during make() /load().  By the time it gets to load the message has less
context so is harder to track down  - both by the exception itself and by the stack track.
In this case my mistake caused an 'incompatible change' ... yes.  which one ?
considering I had only 1 it wasnt too hard  ,  but catching that I'd added a field
to an interface during the build process would be more useful - and slower :(  :)
