### ISSUE TITLE
Android Sample Application

### ISSUE THREAD

**Issue by jasperblues** [raphw/byte-buddy#1626]
Is there a sample application for Android with the various parts in place? This would greatly speed up getting started. 

_(Especially for folks like myself, who don't regularly develop for Android, but nonetheless need bytecode instrumentation on this platform)_.

**Comment by raphw** [comment]
Yes, it is part of the project.

**Comment by raphw** [comment]
https://github.com/raphw/byte-buddy/tree/master/byte-buddy-android-test

**Comment by jasperblues** [comment]
I saw this! However, it didn't seem to match the documentation on Gradle usage here: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-gradle-plugin/android-plugin/README.md

The above guide talks about setting up a separate build target for an instrumentation module, and then applying that via a plugin during compilation. 

Nonetheless thank you, I will check out the sample more closely.

**Comment by jasperblues** [comment]
Ah I see. There is a sample for both the compile time instrumentation and runtime usage. 

I'm happy with the answer, shall I close the issue?

**Comment by raphw** [comment]
If your question is answered, yes.

**Comment by jasperblues** [comment]
Cool. Closed, and thank you.  Although it took me a while to get my head around the Gradle plugin. 

Possibly a stand-alone app + tutorial would help. . If I get time, I'll write a blog post for this.
