### ISSUE TITLE
how to enhance thread construct method 

### ISSUE THREAD

**Issue by githubcheng2978** [raphw/byte-buddy#1627]
how to enhance thread construct method ?

**Comment by githubcheng2978** [comment]
<img width="1551" alt="image" src="https://github.com/raphw/byte-buddy/assets/22095448/adb32d07-20b8-4fec-98b8-eb82714c8454">
 it is not work~

**Comment by raphw** [comment]
The Thread class will already be loaded, so you likely will need to apply retransformation. Typically, you'd also disable class format changes doing so. There's steps for both in the DSL.

**Comment by githubcheng2978** [comment]
Thank you very much for your answer.because lambda Runnable didn’t can be interceptor,  so I want interceptor  Thread construct method,then delegate lambda .

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Rafael Winterhalter ***@***.***>
发送时间: Tuesday, April 30, 2024 12:46:10 AM
收件人: raphw/byte-buddy ***@***.***>
抄送: githubcheng2978 ***@***.***>; Author ***@***.***>
主题: Re: [raphw/byte-buddy] how to enhance thread construct method (Issue #1627)


The Thread class will already be loaded, so you likely will need to apply retransformation. Typically, you'd also disable class format changes doing so. There's steps for both in the DSL.

―

**Comment by githubcheng2978** [comment]
So, what should I do to intercept the thread's constructor？
Can you give me a dmeo?

**Comment by raphw** [comment]
You can intercept a constructor just as any method. Intercept via `ElementMatchers.isConstructor()`.

**Comment by githubcheng2978** [comment]
<img width="1182" alt="image" src="https://github.com/raphw/byte-buddy/assets/22095448/4b2aecee-2fcf-4b8f-a9e9-88af8ef95625">
it is not work~~~

**Comment by raphw** [comment]
skip the explicit `retransformClasses`.

Also, add `.wtih(RetransformationStrategy.RETRANSFORM).disableClassFormatChanges()`.
