### ISSUE TITLE
Can ByteBuddy add synchronized to intercepted setters?

### ISSUE THREAD

**Issue by jimshowalter** [raphw/byte-buddy#1632]
We're using ByteBuddy to track which fields in persistence entities are set.

To do that, we write the field name and value to a map.

To ensure backward-compatibility, we also call the super's setters, which set fields in the base class.

At runtime, the modified methods look like this:

```
public void setFoo(Long var1) {
    SetterInterceptor.interceptSetter(cachedValue$jbu0XnWD$qevi042, var1, this);
    super.setFoo(var1);
}
```

But that means they are no longer atomic. Two threads calling the same setter on the same instance of the entity could wind up with different values in the map vs. the original field.

Is there a way to add synchronized to the generated setters in the subclass?

**Comment by raphw** [comment]
Sure, you can register a `Transformer.ForMethod.withModifiers(...)` which allows you to add the synchronized flag.

**Comment by jimshowalter** [comment]
Thank you!
