### ISSUE TITLE
Can ByteBuddy make a non-static field be final?

### ISSUE THREAD

**Issue by jimshowalter** [raphw/byte-buddy#1634]
After using ByteBuddy to add a Set to our entities to track which fields are set, and calling newInstance, the resulting code looks like this:

`public class Foo$ByteBuddy$Te6Wfjue extends Foo {
    private Set<String> _modified$Fields$Tracker;`

We then use reflection to set the Set:

`public class Foo$ByteBuddy$Te6Wfjue extends Foo {
    private Set<String> _modified$Fields$Tracker = new HashSet<>();`

This is almost conformant with our coding standards, but "final" is missing from the Set.

Is there a way to declare non-static fields final in classes generated by ByteBuddy?

If not, is there a way to set fields to final post-construction?

**Comment by raphw** [comment]
Sure. Use `.subclass(..., ConstructorStrategy.Defaults.NONE)`.

Byte Buddy will then not create implicit constructors. Instead, you create them explicitly. I assume your proxy has only a default constructor? If so:

`MethodCall.invoke(subclass.getConstructor()).onSuper().andThen(MethodCall.invoke(HashSet.class.getConstructor()).setField("_modified$Fields$Tracker")`

**Comment by jimshowalter** [comment]
This is almost perfect. Is there a way to make the fields tracker final?

**Comment by jimshowalter** [comment]
Where does the call to MethodCall.invoke go? It doesn't fit in the new ByteBuddy().builder chain, or if it does I don't see how.

**Comment by jimshowalter** [comment]
This doesn't compile. What am I doing wrong?:

`// The weird name is just to avoid collisions with other classes.
private static final String MODIFIED_FIELDS_TRACKER_SUBCLASS_SUFFIX = "$Setter$Tracking$ByteBuddy$Subclass";

private static final NamingStrategy
  MODIFIED_FIELDS_TRACKER_SUBCLASS_NAMING_STRATEGY =
      new NamingStrategy() {
        @Override
        public @NotNull String subclass(TypeDescription.Generic superClass) {
          return superClass.getTypeName() + MODIFIED_FIELDS_TRACKER_SUBCLASS_SUFFIX;
        }

        @Override
        public @NotNull String redefine(@NotNull TypeDescription typeDescription) {
          return "";
        }

        @Override
        public @NotNull String rebase(@NotNull TypeDescription typeDescription) {
          return "";
        }
      };

// The weird name is just to avoid collisions with other fields.
static final String MODIFIED_FIELDS_TRACKER_FIELD_NAME = "_modified$Fields$Tracker";

static DynamicType.Unloaded<?> setterTrackingEntityType(Class<?> entityClass) throws NoSuchMethodException {
  return new ByteBuddy()
    .with(MODIFIED_FIELDS_TRACKER_SUBCLASS_NAMING_STRATEGY)
    .subclass(entityClass, ConstructorStrategy.Default.NO_CONSTRUCTORS)
    .defineField(
        MODIFIED_FIELDS_TRACKER_FIELD_NAME,
        TypeDescription.Generic.Builder.parameterizedType(Set.class, Method.class).build(),
        Visibility.PRIVATE)
    .constructor(
        MethodCall.invoke(entityClass.getConstructor())
            .onSuper()
            .andThen(
                MethodCall.invoke(HashSet.class.getConstructor())
                    .onField(MODIFIED_FIELDS_TRACKER_FIELD_NAME)))
    .method(ElementMatchers.isSetter())
    .intercept(MethodDelegation.to(SetterInterceptor.class).andThen(SuperMethodCall.INSTANCE))
    .transform(Transformer.ForMethod.withModifiers(SynchronizationState.SYNCHRONIZED))
    .make();
}`

Is there a fully-working example somewhere to look at?

**Comment by jimshowalter** [comment]
I'll post an updated example tomorrow. Had to back out changes for other reasons.

**Comment by jimshowalter** [comment]
[byte-buddy-ctor.zip](https://github.com/raphw/byte-buddy/files/15269167/byte-buddy-ctor.zip)

**Comment by jimshowalter** [comment]
There's a README.me in the root of that project.

The closest I got was AddConstructorSecondAttempt, but it fails with "
  static Constructor<?> getConstructor(Class<?> classToConstruct) {
    try {
      return classToConstruct.getConstructor();
    } catch (NoSuchMethodException e) {
      throw new IllegalStateException(
          "Unable to get public default constructor for " + classToConstruct);
    }
  }

    MethodCall.invoke(getConstructor(entityClass))
        .onSuper()
        .andThen(
            MethodCall.invoke(getConstructor(Object.class))
                .onField(MONACO_PERSISTENCE_INSTANCE_LOCK_FIELD_NAME),
            MethodCall.invoke(getConstructor(HashSet.class))
                .onField(MONACO_PERSISTENCE_MODIFIED_FIELDS_TRACKER_FIELD_NAME));

    // Ignore Sonar warning about incorrect synchronization. We want to prevent setters from being
    // called while
    synchronized (instance) {

Exception in thread "main" java.lang.IllegalStateException: Cannot invoke public java.util.HashSet() on private final java.util.Set org.foo.bytebuddyctor.Entity2$Setter$Tracking$ByteBuddy$Subclass._modified$Fields$Tracker".

It (and the third attempt) is based on your answer posted above.
