### ISSUE TITLE
Release missing of version 1.14.15

### ISSUE THREAD

**Issue by rickie** [raphw/byte-buddy#1636]
Hi, I noticed the GitHub release of Byte Buddy 1.14.15 is missing. 

We link those in the commit messages for upgrades of dependencies. 

Do you plan on still creating the release?
Maybe this is missing on purpose, or it could be a small oversight :).

**Comment by raphw** [comment]
Yes, I was just a bit late out. The Maven indices need to sync and I need to update the internal Byte Buddy version which is the last release.
