### ISSUE TITLE
Complete Java 9 compatibility

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#164]
Java 9 compatibility is not yet fully provided due to:
- [x] It is no longer required to fallback to requesting class files from modules, files ending with `.class` are now universially visible.
- [x] The `Instrumentation` API changed its method for module manipulation.
- [x] It is no longer possible to make members accessible if they belong to a different package (Add `Unsafe` fallback).
- [x] ASM needs to be released in version 6 to support reading Java 9 class files.

**Comment by raphw** [comment]
Currently not up to date:
- [ ] It is no longer required to fallback to requesting class files from modules, files ending with `.class` are now universially visible.
- [ ] The `Instrumentation` API changed its method for module manipulation.

**Comment by liuchang0403** [comment]
wow, when can asm to be released ? it is so slowly. ha ha ha

**Comment by don-vip** [comment]
ASM6 beta has been released: https://mail.ow2.org/wws/arc/asm/2017-07/msg00002.html

**Comment by liuchang0403** [comment]
yeah, i have see it, it have not update to maven repository

**Comment by don-vip** [comment]
It seems it has finally reached Maven Central: http://repo1.maven.org/maven2/org/ow2/asm/asm/6.0_BETA/

**Comment by raphw** [comment]
Fixed and released.
