### ISSUE TITLE
Is it possible to lazily instantiate AllArguments?

### ISSUE THREAD

**Issue by dogourd** [raphw/byte-buddy#1643]
I have a more general Advice that looks like this:
```java
public class Advice {
    @OnMethodEnter
    public static void before(@AllArguments Object[] args) {
         if (xxxx) {
             return;
         }
         if (xxxx) {
             return;
         }
         // use the args.
         Arrays.toString(args);
    }
}
````
There are many logical branches inside Advice that do not pay attention to parameters information, but the generated bytecode will always copy the original parameter list into an array and assign it to the `args` parameter. 

Can I use bytebuddy to implement lazy instantiation of AllArguments? Make sure I only actually create the target array when I'm actually going to use it.

**Comment by raphw** [comment]
Sorry, I missed that. The arguments are only virtual and therewith lazy by definition. Each read will create a new array. The following expression would therefore be false:

    args == args
