### ISSUE TITLE
InjectionStrategy.UsingUnsafe.OfFactory

### ISSUE THREAD

**Issue by githubcheng2978** [raphw/byte-buddy#1651]
I wrote ClassInjector.UsingUnsafe.Factory factory = ClassInjector.UsingUnsafe.Factory.resolve(instrumentation);
factory.make(null, null).injectRaw(classesTypeMap);
Then the code agentBuilder.with(new AgentBuilder.InjectionStrategy.UsingUnsafe.OfFactory(factory)) seems redundant

**Comment by raphw** [comment]
Not sure what you mean. The agent builder uses the factory to inject auxiliary types. Of course you can also use it directly.
