### ISSUE TITLE
How to call method self when use Advice

### ISSUE THREAD

**Issue by twogoods** [raphw/byte-buddy#1660]
```
    @Advice.OnMethodEnter(skipOn = Advice.OnNonDefaultValue.class)
    public static boolean enter(@Advice.Origin Method method, 
                                         @Advice.This(typing = Assigner.Typing.DYNAMIC) Object obj) {
               method.invoke();
}
```
if method is private，you can't use obj.xxx()
reflection can do this，decompile source code it looks like `A.class.getMethod(xxx).invoke()`
can has some optimization let code looks like `this.xxx()`

**Comment by raphw** [comment]
You can create a static fake method with the same signature and then use MethodSubstitution to replace the method with the actual one.

**Comment by twogoods** [comment]
> You can create a static fake method with the same signature and then use MethodSubstitution to replace the method with the actual one.

[sample like this?](https://stackoverflow.com/questions/57808499/can-a-method-call-be-instrumented-with-bytebuddy-instead-of-the-called-method)
like retry to invoke method，so I want to call method self in Advice api，I prefer Advice api ,dont add new class、method、field
In my case `method.invoke` can translate to `this.xxx()` in bytecode？or add some @advice.xxx to describe method call to help bytebuddy translate method call to `this.xxx()`

**Comment by twogoods** [comment]
And I have another question
can Advice api provider `@Advice.AllFields` struct like map<name,value>
```
    @Advice.OnMethodEnter(skipOn = Advice.OnNonDefaultValue.class)
    public static boolean enter(@Advice.AllArguments(typing = Assigner.Typing.DYNAMIC, readOnly = false) Object[] allArguments){
        method m=findChangeFunctionById();
        allArguments =m.invoke();
}
```
the code can be a tmp code to change the arguments value，but if I want to change the field I must to write every `@Advice.FieldValue(value = "name", readOnly = false)`
