### ISSUE TITLE
Return value if matches condition or call original method

### ISSUE THREAD

**Issue by KinComet** [raphw/byte-buddy#1663]
Hi. I want to introduce a cache system here but I cannot find a way to inject my code.
```java
    public static class Inject {
        @Advice.OnMethodEnter(skipOn = String.class)
        public static String met() {
            if (System.currentTimeMillis() > 0) { // If has cache (matches condition)
                return "inject";
            }
            // Call original method, else
            return null;
        }
    }
```
using
```java
        ByteBuddyAgent.install(ByteBuddyAgent.AttachmentProvider.DEFAULT);
        new ByteBuddy().redefine(Source.class)
                .visit(Advice.to(Inject.class).on(ElementMatchers.named("test")))
                .make().load(Main.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
        System.out.println(new Source().test()); // returns null but not the value inject method returns
```
 Also tried `MethodDelegation`, but `@SuperCall` and `@DefaultCall` gives null, so I cannot call original method

**Comment by raphw** [comment]
Have you tried to set `-Dnet.bytebuddy.dump=/some/folder`?

You can then investigate the generated class to see if it actually contains the new code using `javap`. If you set `@Advice.OnMethodEnter(skipOn = String.class, inline = false)` you might also be able to set a break point. If it never triggers, something else is wrong.

**Comment by KinComet** [comment]
> Have you tried to set `-Dnet.bytebuddy.dump=/some/folder`?
> 
> You can then investigate the generated class to see if it actually contains the new code using `javap`. If you set `@Advice.OnMethodEnter(skipOn = String.class, inline = false)` you might also be able to set a break point. If it never triggers, something else is wrong.

Looked into the dump, it's
```java
    public String test() {
        if ((System.currentTimeMillis() > 0 ? "inject" : null) instanceof String) {
            return null;
        }
        return "test";
    }
```
It returns null, but not `inject` String.

**Comment by KinComet** [comment]
I could add a `OnMethodExit`, but it needs two times of condition check. It will take more time. If all things can be done in `OnMethodEnter` or something like that, it would be great.

**Comment by raphw** [comment]
Indeed, now I understand what you are trying to do. You would need to add the following:

```java
@Advice.OnMethodExit
static void exit(@Advice.Enter String enter, @Advice.Return(readOnly = false) String returned) {
  if (enter != null) {
    returned = enter;
  }
}
```

Otherwise, you will not assign the returned value.

**Comment by KinComet** [comment]
This works! Thank you so much.
