### ISSUE TITLE
Cannot deserialize class after Advice instrumentation

### ISSUE THREAD

**Issue by orange-buffalo** [raphw/byte-buddy#167]
Consider the following case:
1. There is a source of serialized instance of `ClassA`. At the moment of serialization there was no instrumentation applied to `ClassA`.
2. Application where instrumentation (`AgentBuilder` with `Advice API`) _is_ applied to `ClassA` is trying to read the instance from the source.

When object is read in the second step, deserialization fails because calculated `SerialVersionUID` does not match the one from the source. 

```
java.io.InvalidClassException: ...; local class incompatible: stream classdesc serialVersionUID = 7202975262074323281, local class serialVersionUID = -5345459948958055686
```

My expectation is that `SerialVersionUID` should not be changed as `Advice` only changes method body and should not modify anything that is used to calculate the `SerialVersionUID`, like fields, methods / constructors signatures, static initializers etc. 

I have prepared a [reproducer for this case](https://github.com/raphw/byte-buddy/files/405054/byte-buddy-test.zip).

Could you please advise if my expectation is reasonable?

**Comment by raphw** [comment]
You need to enable the *disableClassFormatChanges* option on tge agent builder.

**Comment by orange-buffalo** [comment]
Setting this option solved the problem. Thank you!
