### ISSUE TITLE
Can byte-buddy modify bytecode in parallel?

### ISSUE THREAD

**Issue by 601724080** [raphw/byte-buddy#1681]
There are too many classes that need to be modified, and the modification time is now about 20 minutes, Can byte-buddy modify bytecode in parallel?

**Comment by 601724080** [comment]
Sorry， My PC don‘t work until today。
It's roughly written like this:

```
agentBuilder.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(new RedefinitionListener())
                .type(pluginFinder.buildMatch())
                .transform(new BaseTransformer(pluginFinder))
                .with(new TransformListener())
                .installOn(instrumentation);
```
And the BaseTransformer implements AgentBuilder.Transformer。

**Comment by raphw** [comment]
Any class will be transformed in the thread loading the class. If parallel class loading is supported, Byte Buddy will also modify classes in multiple threads.

**Comment by 601724080** [comment]
I‘ll have a try, thank you.
