### ISSUE TITLE
Questions about alternatives to the LocalVariablesSorter class obsoletization

### ISSUE THREAD

**Issue by zhangzhen91** [raphw/byte-buddy#1691]
First off - thanks for an awesome library.

The new version of the LocalVariablesSorter class has been deprecated. What is the alternative?

Looking forward to your reply. 
Thanks!

**Comment by raphw** [comment]
That's an ASM class and it does not seem to be deprecated? https://gitlab.ow2.org/asm/asm/-/blob/master/asm-commons/src/main/java/org/objectweb/asm/commons/LocalVariablesSorter.java

**Comment by zhangzhen91** [comment]
Thank you for your answer. I think you misunderstood what I meant. What I mean is that the old version of bytebuddy also has this class similar to asm, but it is not found in the new version. I would like to ask if it is deprecated? What are the alternatives? Looking forward to your response.

**Comment by zhangzhen91** [comment]
byte-buddy-0.6.12 net.bytebuddy.jar.asm.commons.LocalVariablesSorter

**Comment by raphw** [comment]
You can add asm-utils which contains this visitor. You can add it using: `ClassVisitorFactory` to map between the namespaces.

**Comment by zhangzhen91** [comment]
ok. I roughly understand how to do it. Thank you very much.
