### ISSUE TITLE
EntryPoint property breaks gradle build

### ISSUE THREAD

**Issue by breedx-splk** [raphw/byte-buddy#1699]
Hi. It looks like [this commit](https://github.com/raphw/byte-buddy/commit/1d35b8ad9990a0b742ddb7afa3380836ef762f2e) that added the ability to override the `entryPoint` property has broken our gradle build since `1.14.19`.

You can see our [build automation log output failing here](https://github.com/open-telemetry/opentelemetry-android/actions/runs/10429344749/job/28886630511#step:6:1296), but I'll quote the TL;DR here: 

```
* What went wrong:
A problem was found with the configuration of task ':instrumentation:httpurlconnection:testing:debugBytebuddyTransform' (type 'ByteBuddyLocalClassesEnhancerTask').
  - In plugin 'net.bytebuddy.build.gradle.android.ByteBuddyAndroidPlugin' type 'net.bytebuddy.build.gradle.android.ByteBuddyLocalClassesEnhancerTask' property 'entryPoint' doesn't have a configured value.

    Reason: This property isn't marked as optional and no value has been configured.

    Possible solutions:
      1. Assign a value to 'entryPoint'.
      2. Mark property 'entryPoint' as optional.

    For more information, please refer to https://docs.gradle.org/8.10/userguide/validation_problems.html#value_not_set in the Gradle documentation.
```

Because the implementation uses `getOrElse()`, marking it optional seems like the way to go.

**Comment by raphw** [comment]
Indeed, missed that. I am working on introducing several properties similar to the regular plugin. I will release this fix together with that change.
