### ISSUE TITLE
[Question] Does byte-buddy use any encryption libraries?

### ISSUE THREAD

**Issue by sf-sbalain** [raphw/byte-buddy#1706]
I see from this [issue #1606](https://github.com/raphw/byte-buddy/discussions/1606)  that byte-buddy and agent libraries are considered FIPS compliant since they _do not implement encryption_.
Question: Why does byte-buddy download crypto library`com.google.com.tink` [here](https://github.com/raphw/byte-buddy/blob/8e1acc6e1e2d45cd8b2777767f2c3fe5e38a0100/byte-buddy-gradle-plugin/gradle/verification-metadata.xml#L1602) though it does not use it?
Byte-buddy also refers to  `net.i2p.crypto:eddsa` [here](https://github.com/raphw/byte-buddy/blob/8e1acc6e1e2d45cd8b2777767f2c3fe5e38a0100/.mvn/checksums.sha256#L831C1-L831C21) but again I find no reference to it. 

NOTE: **Net.i2p.crypto.eddsa** is a Java implementation of EdDSA, a digital signature scheme that uses a variant of elliptic curve cryptography based on Twisted Edwards curves.

**Comment by raphw** [comment]
That's part of the Maven and Gradle builds for uploading and signing artifacts, but not of Byte Buddy itself.

**Comment by sf-sbalain** [comment]
Thanks.
