### ISSUE TITLE
Don't Use Synchronization on a Method Parameter

### ISSUE THREAD

**Issue by fazledyn-or** [raphw/byte-buddy#1714]
Hi,

While triaging your project, our bug fixing tool found an issue that generated the following message:

> In file: <span class='original_filename'>[TypeCache.java](https://github.com/raphw/byte-buddy/tree/byte-buddy-1.14.13/byte-buddy-dep/src/main/java/net/bytebuddy/TypeCache.java#L189)</span>, method: <span class='function_name'>findOrInsert</span>, there is a synchronized block on a parameter. iCR suggested the block to be synchronized on a private and final field, not on a parameter. To learn more check <a href='https://cwe.mitre.org/data/definitions/412' target='_blank'>CWE-412</a> and <a href='https://wiki.sei.cmu.edu/confluence/display/java/LCK00-J.+Use+private+final+lock+objects+to+synchronize+classes+that+may+interact+with+untrusted+code' target='_blank'>CERT Secure coding standard LCK00-J</a>.

## Notes from Triage Team

On first look, it looks like a method parameter called `monitor` of `Object` type is passed to the method `findOrInsert`. This doesn't feel right since synchronization should be performed on a fixed or an static object.

The problem with synchronizing on a method parameter is that it's not thread-safe. Imagine two threads calling this method with different values of monitor. Each thread will think it has its own private lock on the object, which leads to unexpected behavior when they try to access the same shared resource.

As a result, we think that synchronization shouldn't be done on a method parameter.

Please let us know whether you think our assumption is wrong.

## Sponsorship and Support
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security.

The bug is found by running the Intelligent Code Repair (iCR) tool by OpenRefactory and then manually triaging the results.

(This issue may look like automated, generated by a bot. But actually it isn't)

**Comment by raphw** [comment]
This is intended.
