### ISSUE TITLE
Advice should preserve/fake line number

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#172]
When the advice code walks the stack up, it will see the adviced method, however that method will not have a line number attached to it.
It would be beneficial if bytebuddy could "fake" that and claim that its instrumentation code is running on the first line which has a line number attached to it.
Most likely it is sufficient to take the line number of the next line.

In theory this could be done for the exit of an advice as well, but I can only see reasonable usecases for having the line number on the entry.

**Comment by raphw** [comment]
Fixed on master.
