### ISSUE TITLE
About ClassInjector

### ISSUE THREAD

**Issue by zyk17** [raphw/byte-buddy#1736]
Hi, when i use ClassInjector, inject a class to BootStrap ClassLoader, it's value of field gone.

```
public class Tests {

    @org.junit.Test
    public void test2() throws Exception {
        Instrumentation inst = ByteBuddyAgent.install();

        MyClassTransformer.c = "abc";   // can't work
        ClassInjector injector = ClassInjector.UsingInstrumentation
                .of(Files.createTempDirectory("tmp").toFile(), ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, inst);
        injector.inject(Collections.singleton(TypeDescription.ForLoadedType.of(MyClassTransformer.class)),
                        ClassFileLocator.ForClassLoader.of(MyClassTransformer.class.getClassLoader()));

        inst.addTransformer(new MyClassTransformer(), true);
        for (Class<?> c : inst.getAllLoadedClasses()) {
            if (c.getName().equals("java.net.InetAddress")) {
                inst.retransformClasses(c);
            }
        }
        System.out.println(InetAddress.getLocalHost().getHostName());
    }

    public static class MyClassTransformer implements ClassFileTransformer {
        public static String c;// = "abc";      // can work

        @Override
        public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
            if (classBeingRedefined == null) return null;
            return new ByteBuddy()
                    .redefine(classBeingRedefined)
                    .visit(Advice.to(GetHostNameAdvice.class).on(named("getHostName").and(takesArguments(0))))
                    .make().getBytes();
        }

        static class GetHostNameAdvice {
            @Advice.OnMethodEnter
            static void enter() {
                System.out.println(MyClassTransformer.c);   // null
            }
        }
    }
}
```

here is generated class file

```
package java.net;

import com.zyk.Tests.MyClassTransformer;
public class InetAddress implements Serializable {
    // ...
    public String getHostName() {
        System.out.println(MyClassTransformer.c);
        return this.getHostName(true);
    }
    // ...
}
```

**Comment by raphw** [comment]
What do you mean by gone? If it's final, it would be copied. If not, maybe the field was not set?

**Comment by zyk17** [comment]
> What do you mean by gone? If it's final, it would be copied. If not, maybe the field was not set?

thank you for answer. 
i add more output, here it is: 
    in public java.lang.String java.net.InetAddress.getHostName() visit MyClassTransformer.c: null
    the method return: zyk
    in my class direct visit MyClassTransformer.c: abc
if i set field MyClassTransformer.c = "abc"; in MyClassTransformer it will work;
but if i set field MyClassTransformer.c = "abc";  in other place before i inject MyClassTransformer to BootStrap class loader the value will not be seted.

**Comment by zyk17** [comment]
i find a way to slove the problem, it is use injector.inject(map(type, classBytes)).
but i'm wonder why `ClassFileLoader` has no way no load newest Class infometion, it's scanner classpath: xx.class.

the code is flowing
```java
public class Tests {

    @org.junit.Test
    public void test2() throws Exception {
        Instrumentation inst = ByteBuddyAgent.install();

        MyClassTransformer.c = "abc";   // can't work
        byte[] bytes = new ByteBuddy()
                .redefine(MyClassTransformer.class)
                .field(named("c")).value("cde")
                .make().getBytes();

        ClassInjector injector = ClassInjector.UsingInstrumentation
                .of(Files.createTempDirectory("tmp").toFile(), ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, inst);
        injector.inject(Collections.singletonMap(
                TypeDescription.ForLoadedType.of(MyClassTransformer.class),
                bytes)
        );

        inst.addTransformer(new MyClassTransformer(), true);
        for (Class<?> c : inst.getAllLoadedClasses()) {
            if (c.getName().equals("java.net.InetAddress")) {
                inst.retransformClasses(c);
            }
        }
        System.out.println("the method return: " + InetAddress.getLocalHost().getHostName());
        System.out.println("in my class directly visit MyClassTransformer.c: " + MyClassTransformer.c);
    }

    public static class MyClassTransformer implements ClassFileTransformer {
        public static String c ;//= "abc";      // can work

        @Override
        public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
            if (classBeingRedefined == null) return null;
            return new ByteBuddy()
                    .redefine(classBeingRedefined)
                    .visit(Advice.to(GetHostNameAdvice.class).on(named("getHostName").and(takesArguments(0))))
                    .make().getBytes();
        }

        static class GetHostNameAdvice {
            @Advice.OnMethodEnter
            static void enter(@Advice.Origin String origin) {
                System.out.printf("in %s visit MyClassTransformer.c: %s\n",
                        origin, MyClassTransformer.c);
            }
        }
    }

}
```

**Comment by raphw** [comment]
If you inject the class, it will be duplicated. If it was already loaded by a child class loader, the field will be duplicated and the field value will only be set on the non-boot instance. Ideally, you hide the class file from regular class loafers before you inject.

**Comment by zyk17** [comment]
but i dont hide that class. i directly` MyClassTransformer.c = "abc";  ` before `injector.inject()`。

**Comment by raphw** [comment]
Then `MyClassTransformer` will already be loaded by the system loader. When you inject it to the boot loader, it will exist there, too. With the same name, but they will be different classes.

**Comment by zyk17** [comment]
Sorry for the unclear description, I know this through the output. my problem is when I injectet that into the bootstrap class loader, the static field value disappeared

**Comment by raphw** [comment]
When you set the field and then call `MyClassTransformer.class.getClassLoader()` thereafter. What value is returned? If it is not `null`, then the class is loaded on the system loader in addition, and you are setting the value on the wrong instance of the class.

**Comment by zyk17** [comment]
ok, 👍 thank you for answer

**Comment by zyk17** [comment]
I mean could there be a strategy here to load the class information from the memory snapshot, such as using reflection to get the latest class information. for ClassFileLocator. Because the existing strategy is to scan files
 
<img width="738" alt="截屏2024-12-18 10 34 14" src="https://github.com/user-attachments/assets/b20c70ad-2079-4b76-86f1-0c8d1070d319" />

**Comment by raphw** [comment]
There is no API to read class file data from memory. The closes you'd get would be using instrumentation, but that is not exactly cheap either.
