### ISSUE TITLE
can i add an other agent by byte-buddy-agent in runtime?

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#175]
i use byte buddy 
```
ByteBuddyAgent.install();
new AgentBuilder.Default().
type(....).transform(...)
.installOnByteBuddyAgent();
```
replace 
```
-javaagent:my_agent.jar
```
in programmer starting 

now i want to add an other agent to my programmer, 
but i don't want to use ```-javaagent:another-agent.jar``` 
could i use byte-buddy's API add another agent jar into my programmer to replace in command ```-javaagent```?

thanks

**Comment by raphw** [comment]
Any such agent defines a `premain(String, Instrumentation)` method. You need to call this method via reflection from your agent and you can expect the same behavior.

**Comment by dragontree101** [comment]
yes,  that agent has ```premain(String, Instrumentation)``` method.

but i don't know how to call it's ```premain(String, Instrumentation)```  method in my code ,

could you give me an example?

**Comment by raphw** [comment]
The JVM makes a reflective call itself. It looks at the manifest file, finds the premain class there and does something like:

```java
Class.forName("some.pre.Main").getDeclaredMethod("premain", String.class, Instrumentation.class).invoke(null, "", inst)
```

**Comment by dragontree101** [comment]
i need use byte-buddy's ```inst``` by ```ByteBuddyAgent.getInstrumentation()```

**Comment by raphw** [comment]
Yes, that is most likely what you need to go for.

**Comment by dragontree101** [comment]
thanks very much， i will try it， hope it will success!
