### ISSUE TITLE
Make TypeDescription implement Serializable

### ISSUE THREAD

**Issue by jakubhava** [raphw/byte-buddy#180]
Hi Rafael,
 I'm using byte buddy to implement a distributed instrumentation tool. I'm in advance state, but there is really tine thing to solve yet.

What I would like to do it is to create instances of `TypeDescription` for each class in one JVM, then serialise it, send it over network to a JVM where byte-buddy is running and let byte-buddy decide whether this class should be instrumented based on the provided TypeDescription. In case the class should be instrumented, this JVM will ask the second one for the bytecode for this class and run the instrumentation.

I have implemented all the steps above and it works, however I needed to create custom byte-buddy release where is `TypeDescription` declared as
`public interface TypeDescription extends TypeDefinition, ByteCodeElement, TypeVariableSource, Serializable {`, ie, it implements `Serializable` too because I need to serialise it as byte array.

I was wondering if there is anything what would prevent you making this class `Serializable` also in the main release branch ? In that case I wouldn't have to fork and maintain another custom version of byte-buddy, which would help a lot :)

Thanks for help and great tool!

Kuba

**Comment by jakubhava** [comment]
Actually when thinking about it more I would need to make more types serialisable ( all not serialisable types depending used in `TypeDescription`) such as `TypeList`, `AnnotationsList` and so on, so I'm not sure whether this is still suitable change for you.

**Comment by raphw** [comment]
I cannot make `TypeDescription` serializable, because it is not serializable for all implementations. For example, a `TypePool` often looks up type descriptions lazily from a class loader. You cannot serialize a class without retaining this reference but a class loader is neither serializable.

What I can do is make `TypeDescription.ForLoadedType` serializable.

**Comment by raphw** [comment]
Made `TypeDescription.ForLoadedType` serializable on master.

**Comment by jakubhava** [comment]
Sorry Rafael,
 I got sick and forgot to respond you since then.

I have already found an easier workaround where I can use unchanged bytebuddy release.

Thanks for great help and effort.

Sorry again,

Jakub

**Comment by raphw** [comment]
No worries, glad you found a better solution, serialization is almost never a good choice. I will still retain `Serializable` to align this better with the Java API. Thanks for your feedback.
