### ISSUE TITLE
Allow repeating of method from exit advice.

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#186]
Similarly to the entry advice being allowed to skip a method by providing a return value, the exit advice should be allowed to repeat a method call by a `goto startOfMethod` command depending on its return value.

**Comment by Dynarev** [comment]
I would think this could have the potential to accidentally cause some serious loop and thread unsafe situations. Seems to me a little bit cleaner way to repeatedly call a method would be to use an executor then just hook that method at timed increments.

**Comment by raphw** [comment]
Repeating a method call from an exit advice is nothing more then executing a loop. If you mess up the terminal condition, it will run infinitely. The behavior is an explicit opt-in and now available on master.
