### ISSUE TITLE
Create component for method call / field access substitution

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#187]
Create a visitor that allows the substitution of field access / method calls by invoking another method or by delegating to a bootstrap method (replacing the access with an _invokedynamic_ call site).

This should allow for an API similar to this one:

``` java
Method bootstrap = ...
AsmVisitorWrapper wrapper = Substitute.with(bootstrap).on(named("foo"));
```

**Comment by wu-sheng** [comment]
👍

**Comment by ZachHerridge** [comment]
Has there been any progress on this feature? This is the main thing stopping us from upgrading from JavaAssist.

**Comment by raphw** [comment]
There is some progress in the `MemberSubstitution` component. I want to extend its capabilities but for now it is perfectly capable to replace a field or method access with another field or method access.

**Comment by raphw** [comment]
This is `MemberSubstitution`, in case anybody is wondering.
