### ISSUE TITLE
Write class with costum JVM bytecode with ASM and load it on Andirod.

### ISSUE THREAD

**Issue by yuwenhuisama** [raphw/byte-buddy#188]
Will Bytebuddy also allow the loading of dynamically created classes with **costum JVM bytecode witten by ASM?**

**Comment by raphw** [comment]
Yes, you can register an AsmClassVisitorWrapper to create the byte code and then load the type using the AndroidClassLoadingstrategy.

**Comment by yuwenhuisama** [comment]
Thank you, it's healpful for me to write the JIT on Andriod for my DSL!

**Comment by raphw** [comment]
Note that you cannot redefine or retransform classes on Android but only create subclasses.
