### ISSUE TITLE
Openjdk9 version is not recognized by VersionLocator

### ISSUE THREAD

**Issue by TimvdLippe** [raphw/byte-buddy#191]
I am working on building Mockito on jdk 9, but our test suite currently fails because ByteBuddy does not detect openjdk9 as valid. The error is:

```java
org.mockitousage.spies.SpyingOnInterfacesTest > shouldAllowSpyingOnDefaultMethod FAILED
    java.lang.IllegalStateException: This JVM's version string does not seem to be valid: 9-internal
        at net.bytebuddy.ClassFileVersion$VersionLocator$ForLegacyVm.locate(ClassFileVersion.java:397)
        at net.bytebuddy.ClassFileVersion.ofThisVm(ClassFileVersion.java:160)
        at org.mockitousage.spies.SpyingOnInterfacesTest.shouldAllowSpyingOnDefaultMethod(SpyingOnInterfacesTest.java:88)
```

**Comment by raphw** [comment]
The version locator is adapted for the latest build of OpenJDK. I only support the latest EA builds as there are too many moving parts. Your version must be outdated (older than b138).

**Comment by TimvdLippe** [comment]
Yes that could be true, since I am using the openjdk9 version available on the ppa: https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa

Do you maybe know how I can upgrade to a new version?

**Comment by raphw** [comment]
That build is ancient. I do not know if it is possible to download the pre-build directly and unpack it on the CI, but I doubt it as it requires accepting a license.
