### ISSUE TITLE
Can I automatically calculate operand stack size and local variable array size with ASM?

### ISSUE THREAD

**Issue by yuwenhuisama** [raphw/byte-buddy#192]
ASM can automatically calculate these information using `new ClassWriter(ClassWriter.COMPUTE_FRAMES)` and it's convenient for me. And how can I use this feature when I implement an `Implementation` without `Size`?

**Comment by raphw** [comment]
You can but I assume that you are trying to implement a method using ASM? Have a look at `AsmVisitorWrapper` which allows you better access to methods. It is also capable of resolving ASM flags such as `ClassWriter.COMPUTE_FRAMES`.
