### ISSUE TITLE
Explore options for warming up a class file transformer to avoid circularities.

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#193]
If any class used within a class file transformer is loaded outside of a Byte Buddy-created agent, the current circularity lock mechanism does not suffice to prevent `ClassCircularityError`s. To avoid that these errors occure without explicit class loading, the `AgentBuilder` should offer some form of warm-up that triggers all classes to be loaded until the ignore matcher is executed.

**Comment by raphw** [comment]
Does not seem to be problematic in practice.

**Comment by raphw** [comment]
What is possible is to invoke the `ClassFileTransformer` with some sample inputs before it is applied. I need to look into this further, it might be helpful. This can be done rather easily manually, but it would be nice to have a convenience that for example disables the listener from begin triggered for such classes.

**Comment by raphw** [comment]
I can reopen this for further investigation, if I find the time, I can add something.

**Comment by kriegaex** [comment]
Let me know if you need a reproducer. I forked the StackOverflow OP's repository and locally mavenised the project already (he uses makefiles) and also re-structured it in order to be more granular (dependency classes called by the advice in a separate module which gets included into and extracted by the springboard agent).

**Comment by kriegaex** [comment]
The reproducer is [here](https://github.com/kriegaex/JavaAgent). I also added a read-me explaining how to build and run it. For the manual warm-up stuff, see these sections:
  * [`Transformer.java#L22-L26`](https://github.com/kriegaex/JavaAgent/blob/ae5fb8fc63367fd0291e5017a44f275e4b58c4f2/agent/src/main/java/org/acme/agent/Transformer.java#L22-L26)
  * [`Transformer.java#L91-L97`](https://github.com/kriegaex/JavaAgent/blob/ae5fb8fc63367fd0291e5017a44f275e4b58c4f2/agent/src/main/java/org/acme/agent/Transformer.java#L91-L97)

**Comment by raphw** [comment]
I added an API on master that allows you to specify classes to `warmUp`. These classes will then be transformed as if the transformer was already installed, but within a single thread. This should allow for classes to load before an actual transformation in order to avoid many circularities. Could you give this a try?

**Comment by kriegaex** [comment]
Something seems to be wrong with the Maven configuration on master. I am getting this error when running `mvn clean`:

```text
[ERROR] Failed to execute goal on project byte-buddy-gradle-plugin: Could not resolve dependencies for project net.bytebuddy:byte-buddy-gradle-plugin:jar:1.11.13-SNAPSHOT: The following artifacts could not be resolved: net.bytebuddy:byte-buddy:jar:1.11.13-SNAPSHOT, net.bytebuddy:byte-buddy-dep:jar:1.11.13-SNAPSHOT: Could not find artifact net.bytebuddy:byte-buddy:jar:1.11.13-SNAPSHOT -> [Help 1]
```

**Comment by kriegaex** [comment]
> I added an API on master that allows you to specify classes to `warmUp`. (...) Could you give this a try?

Huh?! Now even without my own warm-up, the problem no longer occurs with the latest BB release. It looks as if one of my latest changes before posting the example project accidentally fixed something, whyever. Let me find out how to reproduce the original problem with 1.11.12, then try 1.11.13-SNAPSHOT instead.

**Comment by kriegaex** [comment]
OK, it seems as if my excludes list was "too clean". I added some exceptions on purpose

```patch
-    nameStartsWith(AGENT_PACKAGE)
+    (nameStartsWith(AGENT_PACKAGE).and(not(nameContains("TraceStackInfo"))).and(not(nameContains("CompleteSTE"))))
```

which provokes `ClassCircularityError`s when commenting out my home-brew warm-up:

```patch
-    warmUpPlatformClassLoader();
+//    warmUpPlatformClassLoader();
```

Replacing with the new BB warm-up fixes the problem:

```patch
+      .warmUp(TraceStackInfo.class, CompleteSTE.class)
```

The complete patch when applied to the sample repository's master branch:

```patch
Index: agent/src/main/java/org/acme/agent/Transformer.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/agent/src/main/java/org/acme/agent/Transformer.java b/agent/src/main/java/org/acme/agent/Transformer.java
--- a/agent/src/main/java/org/acme/agent/Transformer.java	(revision Staged)
+++ b/agent/src/main/java/org/acme/agent/Transformer.java	(date 1628929514989)
@@ -9,6 +9,7 @@
 
 import java.lang.instrument.Instrumentation;
 import java.util.Arrays;
+import java.util.Collections;
 import java.util.List;
 
 import static net.bytebuddy.agent.builder.AgentBuilder.RedefinitionStrategy.RETRANSFORMATION;
@@ -26,7 +27,7 @@
   );
 
   private static final ElementMatcher.Junction<TypeDescription> IGNORED_TYPES =
-    nameStartsWith(AGENT_PACKAGE)
+    (nameStartsWith(AGENT_PACKAGE).and(not(nameContains("TraceStackInfo"))).and(not(nameContains("CompleteSTE"))))
       .or(nameStartsWith(BYTEBUDDY_PACKAGE))
       .or(nameStartsWith("com.sun.proxy"))
       .or(nameStartsWith("java.instrument."))
@@ -78,7 +79,7 @@
       .and(not(named("valueOf")));
 
   public static void init(Instrumentation inst) throws ClassNotFoundException {
-    warmUpPlatformClassLoader();
+//    warmUpPlatformClassLoader();
     installTransformer(inst);
     System.out.println("Transformer installed");
   }
@@ -103,6 +104,7 @@
       .with(RedefinitionStrategy.Listener.StreamWriting.toSystemError())
       .with(AgentBuilder.Listener.StreamWriting.toSystemError()/*.withTransformationsOnly()*/)
       .with(AgentBuilder.InstallationListener.StreamWriting.toSystemError())
+      .warmUp(TraceStackInfo.class, CompleteSTE.class)
       .ignore(none())
       .ignore(IGNORED_TYPES)
       .type(any())
Index: pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pom.xml b/pom.xml
--- a/pom.xml	(revision Staged)
+++ b/pom.xml	(date 1628928797390)
@@ -13,7 +13,7 @@
       <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
       <maven.compiler.source>1.8</maven.compiler.source>
       <maven.compiler.target>1.8</maven.compiler.target>
-      <bytebuddy.version>1.11.12</bytebuddy.version>
+      <bytebuddy.version>1.11.13-SNAPSHOT</bytebuddy.version>
     </properties>
 
   <modules>
```

While this certainly is not an exhaustive real-life test, for now I can say: Thank you, @raphw. The new feature seems to be very useful. 😊

**Comment by raphw** [comment]
Brilliant, I will write some more tests in BB to avoid future regressions but this makes perfect sense as a feature as this likely avoids circularity issues for many agents that instrument boot classes. I'll publish it as part of the next release. Thanks for your feedback and validation!

**Comment by raphw** [comment]
Implemented on master.
