### ISSUE TITLE
A section for libraries using ByteBuddy

### ISSUE THREAD

**Issue by cemo** [raphw/byte-buddy#196]
Hi @raphw, 

It might be a good idea to have a section for libraries using ByteBuddy project's homepage on github. 

Thanks for the awesome library.

**Comment by raphw** [comment]
Good idea, I will add a wiki or something!

**Comment by raphw** [comment]
I added a [wiki page](https://github.com/raphw/byte-buddy/wiki/Projects-using-Byte-Buddy) for projects using Byte Buddy and linked it at the relevant places. Feel free to add your own project to the list!
