### ISSUE TITLE
[Question] Inner static class loading / method intercept possible?

### ISSUE THREAD

**Issue by originx** [raphw/byte-buddy#199]
Hello, I am trying to adapt a library (port it) from cglib to ByteBuddy so I can run it on Android Dalvik/dex, and I am having issues with method delegation and IllegalAccessException.
ByteBuddy seems to fail with IllegalStateException in case of a inner static class declaration with following error:

> java.lang.IllegalAccessException: Class com.tngtech.jgiven.impl.StandaloneScenarioExecutor can not access a member of class com.tngtech.jgiven.report.text.PlainTextReporterTest$FormattedSteps$ByteBuddy$7UgEFvgC with modifiers ""
>	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
>	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
>	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
>	at java.lang.reflect.Constructor.newInstance(Constructor.java:413)

Note if I change the class modifier to public it works fine:
```java
static class FormattedSteps { <-- **fails**
public  static class FormattedSteps { <-- **works**
```

This is a snippet of interception setup:
```java
 return new  ByteBuddy()  
  .subclass(stepsClass)
  .method(any())
  .intercept(MethodDelegation.to(methodInterceptor))
  .make()
  .load(getClass().getClassLoader())
  .getLoaded()
  .newInstance();
```

Then a snippet from the MethodInterceptor.class
```
 @RuntimeType
 @BindingPriority(BindingPriority.DEFAULT * 3)
 public Object interceptSuper( 
        @SuperCall final Callable<?> zuper,
        @This final Object receiver,
        @Origin Method method, 
        @AllArguments final Object[] parameters)
        throws Throwable {
      Invoker invoker = new Invoker() {
        @Override
        public Object proceed() throws Throwable {
          return zuper.call();
        }
      };
      return doIntercept( receiver  , method, parameters, invoker );
    }

    @RuntimeType
    @BindingPriority(BindingPriority.DEFAULT * 2)
    public Object interceptDefault(
        @DefaultCall final Callable<?> zuper,
        @This final Object receiver,
        @Origin Method method, 
        @AllArguments final Object[] parameters)
        throws Throwable {
      Invoker invoker = new Invoker() {
        @Override
        public Object proceed() throws Throwable {
          return zuper.call();
        }
      };
      return doIntercept( receiver  , method, parameters, invoker );
    }

    @RuntimeType
    public Object intercept( 
      @This final Object receiver,
      @Origin final Method method, 
      @AllArguments final Object[] parameters) throws Throwable {
    // this intercepted method does not have a non-abstract super method
    Invoker invoker = new Invoker() {
      @Override
      public Object proceed() throws Throwable {
        return null;
      }
    };
    return doIntercept( receiver  , method, parameters, invoker );
  }
```

Am I doing something wrong here, code works fine with cglib so I presume I misconfigured the interceptor?

**Comment by raphw** [comment]
I assume that `getClass().getClassLoader()` is not the same as the class loader of your `stepsClass`. If a class is package-private (all inner non-public and non-protected classes are), it is defined to be package-private. A package-private class can only be subclasses if the subclass is also within the same package.

A package at runtime needs to be defined by the same class loader in order to be equal at runtime. This is a limitation enforced by the JVM. (This should also not work with cglib, so to speak.)

**Comment by originx** [comment]
Thank you for the fast reply I will look into it.
I am doing the migration on a fork of JGiven library:
https://github.com/originx/JGiven

You can reproduce the issue if you run ./gradlew :jgiven-core:test

Although I am unsure it is run in a different class loader I have to check it.

**Comment by raphw** [comment]
I see now what is going on. Byte Buddy mimics the constructors of its super class but it does not change their visibility. Therefore, you would need to set the constructor to be accessible before creating an instance. You can change that by using `ConstructorStrategy.Default.IMITATE_SUPER_CLASS_OPENING` upon subclassing.

**Comment by originx** [comment]
Really nice, never saw a library dev so responsive. Kudos and thank you for quick assistance, works fine now.
