### ISSUE TITLE
instrument classes in the bootstrap classpath

### ISSUE THREAD

**Issue by sevensecondsaway** [raphw/byte-buddy#200]
If I may ask a question please - how does one go about to instrument classes that are in the bootstrap classpath, or at least classes that implement or extend classes in the bootstrap classpath. In previous versions of byte-buddy, I had successfully used a construct like 

>     .type(
            new SubTypeMatcher<TypeDescription>(
                    new TypeDescription.Latent(
                            "org.myClassName",
                            Modifier.PUBLIC,
                            TypeDescription.Generic.OBJECT,
                            new ArrayList<>())) {
                @Override
                public boolean matches(TypeDescription target) {
                    boolean b = false;
                    try {
                        b = super.matches(target);
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
                    return b;
                }
         )

This doesn't work anymore, it's probably because I'm missing the right incantations with AgentBuilder's options or maybe I need to make sure the transform class is appended (or prepended?) to the bootstrap classpath, maybe? My apologies if this was answered before, if you can point me in the right direction, I would be most grateful.

Thanks!

**Comment by raphw** [comment]
If you want to instrument classes on the bootstrap class path, you have to set a different ignore-matcher. By default, Byte Buddy does no longer include bootstrap classes as most people do not intend to instrument these classes but do so accidentally. This also improves performance a lot.

You can set a different ignore matcher by `ignore(none())`, for example.

As for your matcher, it seems like your method matcher is not specific enough. Can you show me the code that specifies the matcher and instrumentation? You would typically say something like `myMatcher.and(takesArguments(Object.class, 1))` to express that you want to match all classes that match your matcher and that take `Object` as their first argument.

**Comment by sevensecondsaway** [comment]
Indeed that was I was missing, thank you! My use case is pretty simple, I'm trying to log sql statements as part a our QA test suite, and maybe also some timing info. I'm basically starting from scratch here, given than byte-buddy has evolved quite a bit since the last time I looked into building similar agents.

I do have some follow up questions:
- what's the performance impact of ignore(none)? is it in startup, runtime or both? What would you consider to be best practice here? I'm asking this because byte-buddy is really a fantastic Swiss army knife code generation lib but it's lack of documentation makes its learning curve rather steep, hence limits its adoption. Especially since the API is evolving.
Maybe this is something that someone can sponsor or crowdfund through something like patreon.com?
- Along the same lines, would it be possible for you to provide example code on how to go about building what you'd consider to be common use cases of byte-buddy? The tests are great but they too lack documentation.

thanks!

**Comment by raphw** [comment]
By default, Byte Buddy resolves `TypeDescription`s lazily. If you can exclude the entire bootstrap class path, Byte Buddy only needs to check if `classLoader == null` and does not even need to parse a class file. If your only type matcher says something like `isSubtypeOf(Foo.class)`, Byte Buddy needs to check every single bootstrap class for this super type, i.e. needs to parse all classes.

Generally, it is the most efficient to exclude classes by:
1. A class loader.
2. Its name (does not require parsing a class file).
3. Its properties like an annotation. (Requires parsing only the single type.)
4. Its linked properties like super types. (Requires I/O to process additional type information.)

If you set `ignore(none())`, the performance impact depends therefore on your subsequent matchers. If you are not even interested in transforming classes of the bootstrap loader, it does however improve performance quite a bit.

As for a general use case agent, the GitHub page showcases a simple agent. I know that documentation could be improved but I lack some time unfortunately. Byte Buddy evolves a bit by the direction of my customers asking me to improve bits and then I cannot typically write documentation in my paid time. That is of course a shame but a consequence of the OS-based business model.

**Comment by sevensecondsaway** [comment]
Thank you, this is exactly what I was looking for. I understand the business situation, and I know you're very proactive in addressing questions, bugs and requests from the community. I can't promise anything, but I'll put a request with my management to look into you contracting with us. I first need to build a solid business case :)
