### ISSUE TITLE
Problem with method advice containing lambda expression

### ISSUE THREAD

**Issue by jakubhalun** [raphw/byte-buddy#207]
Hi,
I have an agent instrumenting Spring Boot application. Few weeks ago I have another issue with that agent and ask you a question here: http://stackoverflow.com/questions/40202027/incompatibleclasschangeerror-when-instrumenting-running-springboot-application-w

Here is current version of agent:
[https://github.com/jakubhalun/tt2016_byte_buddy_agent_demo/blob/ca1509d9cf4bb1bd0373a46e87bb1e231073f1c2/src/main/java/pl/halun/demo/bytebuddy/logging/LoggingAgent.java](code)
Here is advice:
[https://github.com/jakubhalun/tt2016_byte_buddy_agent_demo/blob/83190ab5aaca7a770fe68b513e78589c80404195/src/main/java/pl/halun/demo/bytebuddy/logging/LoggingAdvice.java](code)

I was trying the change for loop into lambda expression in LoggingAdvice class:
`Arrays.stream(allArguments).forEach(
				arg -> logger.info("Method {}, parameter type {}, value={}",
						method.getName(), arg.getClass().getSimpleName(),
						arg.toString()));`

but that causes IllegalAccessError when advice is called:
[LoggingAdvice.lambda_IllegalAccessError.txt](https://github.com/raphw/byte-buddy/files/573325/LoggingAdvice.lambda_IllegalAccessError.txt)

I have also written much simpler application for testing without dependencies to Spring, but my Advice does not work for it either. There was no Error, instead the code from advice has just not been called. After removing lambda from advice it worked again.

**Comment by raphw** [comment]
Technically, there is no problem with lambda expressions using the `Advice` class. However, there is a caveat which is the way lambda expressions are compiled.

A lambda

```java
class Foo {
  void bar() { Consumer<String> c = s -> System.out.println(s); }
}
```

is syntactic sugar for an explicit reference such as: 
```java
class Foo {
  void bar() { Consumer<String> c = Foo::lambda$1; }
  private static void lambda$1(String s) { System.out.println(s); }
}
```
The lambda method is created by *javac* and is defined as private.

After applying the advice method, the lambda is referenced from outside the class. This does however require that the advice class is visible to the instrumented class.

Of course, Byte Buddy could copy the lambda methods to the target class. In this case, it would however no longer be possible to use `Advice` for redefinitions which is the main purpose of `Advice`. Therefore, you either have to make the lambda methods explicitly visible by defining them to be public manually or you have to use the "old" APIs without streams.
