### ISSUE TITLE
MethodDelegation.to() refuses to delegate to subclass of a public enumeration

### ISSUE THREAD

**Issue by ghost** [raphw/byte-buddy#209]
```java
public enum Foo {
    BAR {}
}
```

`MethodDelegation.to(Foo.BAR)` throws an IllegalStateException (Foo$1 is not visible to...)

Foo.bar is public however.

**Comment by raphw** [comment]
But the type is not. You probably need to do `MethodDelegation.to(Foo.bar, Foo.class)` to indicate delegation to the correct type.
