### ISSUE TITLE
It is possible to subclass types on runtime on ART (Android 5.0+)?

### ISSUE THREAD

**Issue by horaciojcfilho** [raphw/byte-buddy#211]
I am wondering if is possible to create classes (subclassing) at runtime on ART using this library. Is it slow? Thanks a lot :D

**Comment by raphw** [comment]
It is possible. I have however not measured any performance impact. It should however not make a big impact, as these dynamic dex files are also compiled: https://www.youtube.com/watch?v=EBlTzQsUoOw

Do note that Google already abandoned the idea of AOT compilation for future versions of Android.

**Comment by horaciojcfilho** [comment]
@raphw Thanks a lot for the fast answer, but I was not able to catch any info regarding AOT compilation abandonment for future versions, can you send some link about that? 

Thanks a lot :D

**Comment by raphw** [comment]
Glad I could help, here is what I meant: https://www.infoq.com/news/2016/03/android-n-aot-jit
