### ISSUE TITLE
Simple java agent doesn't work

### ISSUE THREAD

**Issue by bsideup** [raphw/byte-buddy#218]
Hi!

I'm trying to replace javassist with ByteBuddy, but it's not that intuitive :(

You can see it here:
https://github.com/bsideup/javaagent-boilerplate/tree/bytebuddy/src/main/java

If you have Docker installed, you can run it with `./gradlew test` to see it in action.

Basically, I just want to add 1 method call on the argument, so I do:

```java
public static void premain(String args, Instrumentation instrumentation) {
    new AgentBuilder.Default()
            .type(named("spark.webserver.JettyHandler"))
            .transform((builder, typeDescription, classLoader) ->
                    builder
                            .method(named("doHandle"))
                            .intercept(
                                    MethodDelegation.to(JettyHandlerInterceptor.class)
                                            .andThen(SuperMethodCall.INSTANCE)
                            )
            )
            .installOn(instrumentation);
}
```

Where JettyHandlerInterceptor looks like this:
```java
import net.bytebuddy.implementation.bind.annotation.AllArguments;

import javax.servlet.http.HttpServletResponse;

public class JettyHandlerInterceptor {

    public static void doHandle(@AllArguments Object[] args) {
        System.out.println("!!!!!!!!!!!");
        System.out.println("!!!!!!!!!!!");
        ((HttpServletResponse) args[3]).setHeader("X-My-Super-Header", "header value");
    }
}
```

But it fails at runtime with:
```
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletResponse
at spark.webserver.JettyHandlerInterceptor.doHandle(JettyHandlerInterceptor.java:12)
```

What I'm doing wrong?

Thanks!

**Comment by raphw** [comment]
So, the problem here is that `MethodDelegation` does an actual delegation where the code is probably run in another class loader as you are using an application container to deploy. A Java agent is always run in the application class loader whereas the web application is most likely running in a Jetty application class loader.

You have two ways of going around this. One is to make sure that your interceptor is running in the right class loader. The easier way - since you are migrating away from Javassist - is probably to use the advice component instead:

```java
 builder
  .method(named("doHandle"))
  .intercept(Advice.to(JettyHandlerAdvice.class))
```
with
```java
@Advice.OnMethodEnter
public static void doHandle(@Advice.AllArguments Object[] args) {
  System.out.println("!!!!!!!!!!!");
  ((HttpServletResponse) args[3]).setHeader("X-My-Super-Header", "header value");
}
```
In the latter case, Byte Buddy inlines the code into the target method such that your code is run in the applicaion code's class loader. This way, you do however no longer have access to the agent's class loader if the code you instrument is not a child of it.

**Comment by bsideup** [comment]
@raphw thanks! Now I understand.... more or less :D 

However, Is it possible to use ByteBuddy's sexy "no ByteBuddy-related classes in your file" approach? 

I don't really like the AOP style :)

**Comment by raphw** [comment]
The advice class only serves as a template, no reference to it is added to the existing class. You can validate this by setting a break-point in it which will not be triggered when calling the instrumented method. As the method is however defined, you are still able to unit test it.

**Comment by bsideup** [comment]
@raphw FYI example with `@Advice.Argument(value = 3, typing = Assigner.Typing.DYNAMIC)` doesn't work. Tried the following:

```
    @Advice.OnMethodEnter
    public static void doHandle(@Advice.Argument(value = 3, typing = Assigner.Typing.DYNAMIC) HttpServletResponse response) {
        System.out.println("!!!!!!!!!!!");
        System.out.println("!!!!!!!!!!!");
        response.setHeader("X-My-Super-Header", "header value");
    }
```

but no instrumentation is performed.

Is it possible to enable some debug logging to understand what's happening?

**Comment by raphw** [comment]
With the `AgentBuilder` you need to register a logger as the instrumentation API suppresses any exception.
```java
builder.with(AgentBuilder.Listener.StreamWriting.toSystemErr())
```

**Comment by bsideup** [comment]
@raphw thanks! Now I see that it fails when I use `@Advice.Argument(value = 3, typing = Assigner.Typing.DYNAMIC)` with:
```
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletResponse
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.getDeclaredMethods(Class.java:1975)
at com.exmaple.net.bytebuddy.description.method.MethodList$ForLoadedMethods.<init>
at com.exmaple.net.bytebuddy.description.type.TypeDescription$ForLoadedType.getDeclaredMethods(TypeDescription.java:7824)
at com.exmaple.net.bytebuddy.asm.Advice.to(Advice.java:302)
at com.exmaple.net.bytebuddy.asm.Advice.to(Advice.java:289)
at com.exmaple.net.bytebuddy.asm.Advice.to(Advice.java:266)
at com.exmaple.net.bytebuddy.asm.Advice.to(Advice.java:255)
at com.example.superagent.Agent$1.transform(Agent.java:39)
```

Looks like the same issue.

**Comment by raphw** [comment]
It looks similar, but the issue is different. You are supplying the advice class as a loaded type. In order to find the advice method, Byte Buddy needs to use the reflection API which eagerly resolves all types within method signatures. This causes the no class found error as the signature references a servlet API type that is unknown to the system class loader.

To avoid this, you can avoid referencing such application-specific types in method signatures, e.g. use `Object` and cast in the method body. A nicer approach is however the usage of Byte Buddy's type pools (similar to Javassist's class pools but without the overhead of retaining implementation information) where you can describe types using a combination of class loaders:
```java
builder = builder.transform((builder, typeDescription, classLoader) ->
  ClassFileLocator locator = new ClassFileLocator.Compound(
    new ClassFileLocator.ForClassLoader(classLoader),
    new ClassFileLocator.ForClassLoader(ByteBuddy.class.getClassLoader())
  );
  Advice advice = Advice.to(TypePool.Default.of(locator.locate("pkg.JettyHandlerAdvice").resolve(), locator);
  // ...
);
```
This way, Byte Buddy can inline the advice method without ever loading the advice class.

**Comment by bsideup** [comment]
Tried your example (had to change it a bit because it wasn't compiling, I guess you're using some not-yet-released code), but got the same issue with NoClassDefFoundError.

I know how it sounds like, but..... I guess I'll keep Javassist for my simple example app, at least for now :D

It's way too complex, I like the ideas of ByteBuddy, but I already got lost, sorry :(

**Comment by raphw** [comment]
Its not really that complex. You can have a look at: https://github.com/stagemonitor/stagemonitor to see an example of it in action.

**Comment by bsideup** [comment]
@raphw I'll take a look, thanks!

**Comment by shelajev** [comment]
@raphw can you please edit the example code you gave, I think that didn't compile indeed. The differences are minor, but for the sake of completeness: 
```
builder = builder.transform((builder, typeDescription, classLoader) -> {
  ClassFileLocator locator = new ClassFileLocator.Compound(
                       ClassFileLocator.ForClassLoader.of(classLoader),
                       ClassFileLocator.ForClassLoader.of(ByteBuddy.class.getClassLoader())
                     );
                     Advice advice = Advice.to(
                     TypePool.Default.of(locator).describe("pkg.JettyHandlerAdvice").resolve(),
                       locator
                     );
  return builder.method(named("doHandle")).intercept(advice);
});
```

**Comment by raphw** [comment]
Sure thing, should learn my own API ;)

Thanks for the update!

**Comment by raphw** [comment]
Just FYI, I finally found some time to add an out-of-the-box API for this pattern, see #220.

You can now use the advice that you wanted by:
```java
builder = builder.transform(new AgentBuilder.Transformation.ForAdvice()
  .include(getClass().getClassLoader()) // must be able to see "pkg.JettyHandlerAdvice"
  .advice(named("doHandle"), "pkg.JettyHandlerAdvice"));
```
Let me know if you are still trying this out and have any questions.

**Comment by bsideup** [comment]
@raphw wow, great, thanks!I will check it :)

**Comment by raphw** [comment]
Its not in the release version yet, but you can build Byte Buddy yourself in the mean-time if you want to try it.

**Comment by bsideup** [comment]
yeah, already did, thanks to http://jitpack.io :)

**Comment by bsideup** [comment]
@raphw much better now:
https://github.com/bsideup/javaagent-boilerplate/commit/8f05d4d9ef8428a10c1afce9495da21b9206bad0?diff=unified

Thanks!
