### ISSUE TITLE
NoClassDefFoundError with Lambdas

### ISSUE THREAD

**Issue by thma** [raphw/byte-buddy#219]
I'm getting a NoClassDefFoundError when using the AgentBased resolution on Lambdas defined by Method references.

in test doesNotFail() I'm using `Runnable runnable = () -> new VoidMethods().print1();` to create the lambda. Instrumentation and later invocation of the Lambda works great.

in test shouldNotFail I'm using `Runnable runnable = new VoidMethods()::print1;` to create the Lambda.
here I'm getting the NoClassDefFoundError in calling runnable.run() after calling the instrumentation based code.

I'm using ByteBuddy 1.5.6 and the Oracle SDK 1.8.0_112.

Am I doing something wrong or is this an issue?

```java
import net.bytebuddy.agent.ByteBuddyAgent;
import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.ClassFileLocator;
import org.junit.Test;

import java.io.IOException;

/**
 * Created by thma on 22.11.2016.
 */
public class ReproduceByteBuddyIssue {

    static {
        new AgentBuilder
                .Default()
                .with(AgentBuilder.LambdaInstrumentationStrategy.ENABLED)
                .installOn(ByteBuddyAgent.install());
    }

    private byte[] getByteCodeOf(Class<?> c) throws IOException {
        ClassFileLocator locator = ClassFileLocator.AgentBased.of(ByteBuddyAgent.getInstrumentation(), c);
        TypeDescription.ForLoadedType desc = new TypeDescription.ForLoadedType(c);
        ClassFileLocator.Resolution resolution = locator.locate(desc.getName());
        return resolution.resolve();
    }
    
    @Test
    public void doesNotFail() throws IOException {
        Runnable runnable = () -> new VoidMethods().print1();
        Class clazz = runnable.getClass();
        byte[] bytecode = getByteCodeOf(clazz);
        runnable.run();
    }

    @Test
    public void shouldNotFail() throws IOException {
        Runnable runnable = new VoidMethods()::print1;
        Class clazz = runnable.getClass();
        byte[] bytecode = getByteCodeOf(clazz);
        runnable.run();
    }
}
```

with class VoidMethods defined as:

```java
public class VoidMethods {
    void print1() {
        System.out.println("1");
    }
}
```

Here comes the original stacktrace:

> java.lang.NoClassDefFoundError: ReproduceByteBuddyIssue$$Lambda$ByteBuddy$2
> 	at ReproduceByteBuddyIssue$$Lambda$ByteBuddy$2/733943822.run(Unknown Source)
> 	at ReproduceByteBuddyIssue.doesFail(ReproduceByteBuddyIssue.java:47)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
> Caused by: java.lang.ClassNotFoundException: ReproduceByteBuddyIssue$$Lambda$ByteBuddy$2
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 28 more

**Comment by raphw** [comment]
Seems like Byte Buddy is not properly wiring the call site. I need to investigate this a bit, thanks for reporting.

**Comment by mofleury** [comment]
Hello,
Sorry for digging up this old issue, but I stumbled upon it while trying to apply instrumentation on lambdas. I am not sure if I have the same error, but I also have a ClassNotFoundException.

I noticed that the JDK bug seems to have been fixed in 2016, does that mean that lambda instrumentationis supposed to work with recent versions of Java 8?

Thanks :)

**Comment by raphw** [comment]
No, not all issues are backported by the OpenJDK team. Only signigicant ones or you can order a backport on a paid support contract.

**Comment by mofleury** [comment]
Ok, too bad.

Thank you for the quick answer! I suppose I'll have to work around lambda instrumentation for my use case then.

Keep up the good work!
