### ISSUE TITLE
How to define multi-method-delegations, target to different constructors?

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#223]
This is my code to delegate a class's constructors, with different args. And add a field.
like this:
```java
newClassBuilder = newClassBuilder.defineField(contextAttrName, EnhancedClassInstanceContext.class, ACC_PRIVATE).constructor(any()).intercept(SuperMethodCall.INSTANCE
                .andThen(MethodDelegation.to(new ClassConstructorInterceptor(constructorInterceptor)).appendParameterBinder(FieldProxy.Binder.install(FieldGetter.class, FieldSetter.class))));
```

Could I add different delegation to different constructors? Can you demonstrate for me?

**Comment by raphw** [comment]
Yes, you can use `MethodCall.invoke(Constructor)` or `MethodCall.invoke(MethodDescription)`. If the method is yet to be defined, you can use a `MethodDescription.Latent` for its representation.

**Comment by wu-sheng** [comment]
Is there any demos for `MethodCall.invoke(Constructor)` or `MethodCall.invoke(MethodDescription)`?

I only used method().intercept(), like this:
```java
newClassBuilder.method(matcher).intercept(MethodDelegation.to(classMethodInterceptor))
```

`MethodCall`.anything is unfamiliar to me.

**Comment by raphw** [comment]
`MethodCall` is just another implementation such as `MethodDelegation`. You can implement:

```java
newClassBuilder.constructor(matcher).intercept(MethodCall.invoke(otherConstructor())
```

Do I understand you correctly that you want to implement a constructor to invoke another constructor?

**Comment by wu-sheng** [comment]
Unfortunate no :( ,  let's say like this:
I have a class
```java
Class A{
     // 1st constructor
     public A(int a){...}
     // 2nd constructor
     public A(String b){...}
}
```

I want to use different interceptors for 2 constructors, such as Class `Interceptor1st` for 1st constructor, `Interceptor2nd` for 2nd constructor.

Is this clear enough?

**Comment by raphw** [comment]
Yes, this is perfectly possible:

```
newClassBuilder
  .constructor(takesArguments(int.class)).intercept( ... )
  .constructor(takesArguments(String.class)).intercept( ... )
```

The matchers are applied in the order last to first.

**Comment by wu-sheng** [comment]
Ohye, that is. thank you.
