### ISSUE TITLE
How can I use ElementMatcher to match a arg type, but this type is not existed in the current classloader?

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#224]
I use byte-buddy in a javaagent. As you know,  I can use this code to intercept instructor:
```java
newClassBuilder = newClassBuilder.constructor(constructorInterceptPoint.getConstructorMatcher())
```

And this is a problem of building match:
1. Javaagent is loader by boot classloader, and target class in other classloader(assumed WebAppClassLoader)
2. target class constructor's methods have a arg, which is not in boot classloader
such as in Jedis, HostAndPort is in WebAppClassLoader.
```java
public JedisCluster(HostAndPort node, int connectionTimeout, int soTimeout,
      int maxRedirections, final GenericObjectPoolConfig poolConfig) {
```
3. When I want to intercept this specific constructor. I do like this:
```java
 public ElementMatcher.Junction<MethodDescription> getConstructorMatcher() {
         return not(takesArgument(0, Set.class));
}
```

This can work just because first arg in this class's constructors are either set or HostAndPort. If there is two type, I can't use in javaagent, I don't know what to do.

**Comment by wu-sheng** [comment]
I inject my interceptor instance to target classloader, in order to make sure it will work.
But this is define for interceptor, I am not sure which is the right way.

**Comment by wu-sheng** [comment]
This is the target class to intercept
```java
   public Jedis() {
    super();
  }

  public Jedis(final String host) {
    super(host);
  }

  public Jedis(final String host, final int port) {
    super(host, port);
  }

  public Jedis(final String host, final int port, final int timeout) {
    super(host, port, timeout);
  }

  public Jedis(final String host, final int port, final int connectionTimeout, final int soTimeout) {
    super(host, port, connectionTimeout, soTimeout);
  }

  public Jedis(JedisShardInfo shardInfo) {
    super(shardInfo);
  }

  public Jedis(URI uri) {
    super(uri);
  }

  public Jedis(final URI uri, final int timeout) {
    super(uri, timeout);
  }
```

**Comment by raphw** [comment]
The easiest solution is to implement a custom `ElementMatcher`:
```java
new ElementMatcher<MethodDescription>() {
  @Override
  public boolean matches(MethodDescription m) {
    return m.getParameters().size() == 1 
      && m.getParameters().get(0).getTypes().asErasure().getName().equals(typeName);
  }
}
```

**Comment by wu-sheng** [comment]
Ohye, I like this solution.

**Comment by wu-sheng** [comment]
Is any other way, if target a noexisted abstract class or interface?

**Comment by wu-sheng** [comment]
What is `.getTypes().asErasure()` means?

**Comment by raphw** [comment]
The matcher will be invoked for any discovered method by Byte Buddy. The reason for the `asErasure` is that any type is first represented in its generic form. For example, a parameter might have a type `List<String>` where the erasure is `List`. You want to probably compare the erasure, not the generic type. Generally, this is also more runtime efficinet,

**Comment by wu-sheng** [comment]
Is any method like getType(), but get all parent abstract class, interface type,  maybe as a list?

**Comment by raphw** [comment]
The difference is the representation of `TypeDescription.Generic` and `TypeDescription`. The former can be a non-generic type like `String` but its a different representation.
