### ISSUE TITLE
Allow for generic field access similar to method call

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#225]
Currently, a `FieldAccessor` only allows for reading or writing fields of the instrumented type or static fields.

**Comment by Jezza** [comment]
Would this include setting fields from MethodCalls?

**Comment by raphw** [comment]
Possibly, I have not yet looked into all possibilities.

**Comment by raphw** [comment]
In the DSL, it should be possible to define a value for a field, similar to setting an argument.

**Comment by raphw** [comment]
Implemented on master.
