### ISSUE TITLE
Pipe generated subclass overriding default methods

### ISSUE THREAD

**Issue by kostislav** [raphw/byte-buddy#226]
When you use java.util.Function as a target for the @Pipe annotation, the generated subclass overrides not only `apply`, but also `compose` and `andThen`, all with the same body.
It looks like it should be enough to add .and(isAbstract()) to line 300 in net.bytebuddy.implementation.bind.annotation.Pipe

I could make a pull request, but unfortunately I am not sure how to test this properly without depending on Java 8.

**Comment by raphw** [comment]
Yes, you are right. This is a bug and your suggested fix is the solution. This will be fixed in the next version of Byte Buddy. Thanks for reporting and looking into!
