### ISSUE TITLE
Define a field with initial value

### ISSUE THREAD

**Issue by ascrutae** [raphw/byte-buddy#227]
I want to define a field with initial value. Is byte-buddy support this?

**Comment by raphw** [comment]
This depends very much on what you want to do. You can set an initial constant value easily using the `defineField` or `field` API of the `DynamicType.Builder`. If you want to set a field from a constructor, have a look at the `FieldAccessor` API. If you want to define a static field with a value, you can register a `LoadedTypeInitializer` that does so or intercept the type initializer by `ElementMatchers::isTypeInitializer`.

**Comment by ascrutae** [comment]
Thanks for your advise. I want to set a complex object to the field. could you show some example?

**Comment by raphw** [comment]
You cannot set a complex value this way, the Java class file format does not support this. You would need to either intercept constructors to do this or define a loaded type initializer.

**Comment by rajesh-bandarupalli** [comment]
Hi @raphw,

I would like to initialize a  instance field for the dynamically created class, from builder API, with .**defineField("name", String.class, Opcodes.ACC_PRIVATE).value("SOMETHING")** it's not initializing the field and not generating getter and setter methods. And if i use **.defineProperty("name", String.class)** doesn't allow me to initialize the field, but it generates getter and setter methods.

i should be able to create a class at run time with a field initialized along with getter and setter methods for that particular field something like this.

```
public class Sample {
	private String name = "SOMETHING";
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
}
```

How do we generate above piece of code with byte-buddy?

**Comment by raphw** [comment]
The `value` assignment sets the constant value of the field which is not the runtime value.

This might be confusing (and it is) but this regards compiler semantics. If you referred the field in another Java class and compiled it using javac, it would assume this value as the compiler copies such constants. But if this value should be set at runtime, you need to implement or adjust any constructor to set the field's value within the constructor.
