### ISSUE TITLE
Cannot make bootstrap injection to java.lang.Thread to work

### ISSUE THREAD

**Issue by michele-mancioppi** [raphw/byte-buddy#228]
Hi, I am pretty stumped with getting to work a simple injection into `java.lang.Thread`. I am trying to do it into a custom agent, which I am guessing is bringing its particular brand of "fun" with the bootstrap. But it might be I am also missing something completely obvious 💃 

The agent code is the following:

<pre>
package test.agent;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.ClassFileLocator;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.dynamic.loading.ClassInjector;
import net.bytebuddy.implementation.Implementation;
import net.bytebuddy.implementation.bind.annotation.SuperCall;

import java.io.File;
import java.lang.instrument.Instrumentation;
import java.nio.file.Files;
import java.util.Collections;
import java.util.concurrent.Callable;

import static net.bytebuddy.implementation.MethodDelegation.to;
import static net.bytebuddy.matcher.ElementMatchers.named;

public class Main {

    public static void premain(final String args, final Instrumentation instrumentation) {
        final File tempFolder;

        try {
            tempFolder= Files.createTempDirectory("brave-agent-bootstrap").toFile();
        } catch (Exception e) {
            System.err.println("Cannot create temp folder for bootstrap class instrumentation");
            e.printStackTrace(System.err);
            return;
        }

        ClassInjector. //
                UsingInstrumentation.of(tempFolder, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation) //
                .inject(Collections.singletonMap(new TypeDescription.ForLoadedType(ThreadStartInterceptor.class), //
                        ClassFileLocator.ForClassLoader.read(ThreadStartInterceptor.class).resolve()));

        final ByteBuddy byteBuddy = new ByteBuddy().with(Implementation.Context.Disabled.Factory.INSTANCE);
        new AgentBuilder.Default() //
                .with(byteBuddy) //
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE) //
                .with(AgentBuilder.RedefinitionStrategy.REDEFINITION) //
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE) //
                .enableBootstrapInjection(instrumentation, tempFolder) //
                .type(named("java.lang.Thread")) //
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(final DynamicType.Builder<?> builder,
                                                            final TypeDescription typeDescription,
                                                            final ClassLoader classLoader) {
                        try {
                            return builder.method(named("start")).intercept(to(ThreadStartInterceptor.class));
                        } finally {
                            System.out.println("Instrumentation installed");
                        }
                    }
                }) //
                .installOn(instrumentation);
    }

    public static void agentmain(String args, Instrumentation inst) {
        premain(args, inst);
    }

    public static class ThreadStartInterceptor {

        public static void intercept(@SuperCall Callable<Void> superCall) throws Exception {
            System.out.println("Thread '" + Thread.currentThread().getName() + "' started");
            superCall.call();
        }
    }

}
</pre>

**Comment by michele-mancioppi** [comment]
For completenss, I have am trying to applying the agent code above to this trivial test app.

<pre>
package test.app;

import java.util.concurrent.CountDownLatch;

public class ThreadMain {

    public static void main(String ... args) throws Exception {
        final CountDownLatch latch = new CountDownLatch(1);

        final Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(500l);
                } catch (final Exception e) {
                    System.err.println(e);
                } finally {
                    latch.countDown();
                }
            }
        });

        thread.setName("TestThread");

        thread.start();
        latch.await();
        System.out.println("Job done!");
    }

}
</pre>

The expected output is:

<pre>
Instrumentation installed
Thread 'TestThread' started
Job done!
</pre>

However, only <pre>Job done!</pre> is printed to `System.out`.

**Comment by raphw** [comment]
The first problem is that you need to explicitly opt-in for instrumenting bootstrap classes. For most people, this does not make sense as this generates quite some overhead. In order to shortcut the process, you should find another ignore matcher that does not include all bootstrap classes but for a general test, it should work like:
```java
builder = builder.ignore(ElementMatchers.none());
```
You are however suffering a second problem. You can debug agents by registering a listener that prints all actions by:
```java
builder = builder.with(Listener.StreamWriting.toSystemOut());
```
When redefining a class, you can only replace a method but you cannot rebase it what you attempt with using a `MethodDelegation`. You want to rather enhance a method. For this purpose, Byte Buddy offers a similar but eventually different API called `Advice`. You should approach this as follows:

```java
class ThreadStartAdvice {
  @Advice.OnMethodEnter
  static void intercept() {
    System.out.println("Thread '" + Thread.currentThread().getName() + "' started");
  }
}
```
and use it via:
```java
builder = builder.visit(Advice.to(ThreadStartInterceptor.class).on(named("start")));
```
Now everything should work as expected.

**Comment by michele-mancioppi** [comment]
For the next time someone tries and fails to instrument something like `java.lang.Thread`:

<pre>
package test.agent;

import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.asm.Advice;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.DynamicType;

import java.io.File;
import java.lang.instrument.Instrumentation;
import java.nio.file.Files;

import static net.bytebuddy.matcher.ElementMatchers.is;
import static net.bytebuddy.matcher.ElementMatchers.named;
import static net.bytebuddy.matcher.ElementMatchers.noneOf;

public class Main {

    public static void premain(final String args, final Instrumentation instrumentation) {
        final File tempFolder;

        try {
            tempFolder= Files.createTempDirectory("agent-bootstrap").toFile();
        } catch (Exception e) {
            System.err.println("Cannot create temp folder for bootstrap class instrumentation");
            e.printStackTrace(System.err);
            return;
        }

        new AgentBuilder.Default() //
            .disableClassFormatChanges() //
            .ignore(noneOf(Thread.class)) //
            .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE) //
            .with(AgentBuilder.RedefinitionStrategy.REDEFINITION) //
            .with(AgentBuilder.TypeStrategy.Default.REDEFINE) //
            .enableBootstrapInjection(instrumentation, tempFolder) //
            .type(is(Thread.class)) //
            .transform(new AgentBuilder.Transformer() {
                @Override
                public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader) {
                    return builder.visit(Advice.to(ThreadStartInterceptor.class).on(named("start")));
                }
            }) //
            .installOn(instrumentation);
    }

    public static void agentmain(String args, Instrumentation inst) {
        premain(args, inst);
    }

    public static class ThreadStartInterceptor {

        @Advice.OnMethodEnter
        static void intercept() {
            System.out.println("Thread '" + Thread.currentThread().getName() + "' started");
        }
    }

}
</pre>

And, by the way, the `java.lang.Thread` name that will be printed out is the one where `start` is invoked, not where the `java.lang.Runnable#run()` will be executed ;-)
