### ISSUE TITLE
"after_success" step fails in Travis

### ISSUE THREAD

**Issue by Godin** [raphw/byte-buddy#229]
Looks like `after_success` step fails in Travis for a quite long time. I checked last 5 builds (see for example [latest build 1930](https://travis-ci.org/raphw/byte-buddy/jobs/182235379#L8425)), but stats in [coveralls](https://coveralls.io/github/raphw/byte-buddy) were not updated since September 1st.

FWIW I'm able to reproduce this failure locally when running ```mvn clean cobertura:cobertura``` but not when running ```mvn clean package```, so assume that cause might be Cobertura. And actually came across this while preparing pull-request #230 with proposal of switch to JaCoCo.

Also I'm wondering why command in `after_success` simply is not part of `script`? In this case such failure will be visible immediately - quoting https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build :
> The exit code of after_success, after_failure, after_script and subsequent stages do not affect the build result.

**Comment by raphw** [comment]
Thanks, I just completed the migration. CI build time went down by a bunch! Thanks for the work.

**Comment by Godin** [comment]
You're welcome!
I added ByteBuddy to a page [Projects that use JaCoCo](https://github.com/jacoco/jacoco/wiki/Projects%20that%20use%20JaCoCo) 😉
