### ISSUE TITLE
how can we new proxied object and set it into a field?

### ISSUE THREAD

**Issue by lysu** [raphw/byte-buddy#23]
Hi~

I want to use byte-buddy to generate a proxy-class at compile stage...

e.g. input file like

     public class Rule {
        
        @AnRule
         public void doRule1() {
         }

        @AnRule
         public void doRule2() {
         }

     }

and want to generate a proxy 

     public class RuleInvoker implement Invoker {
         
         private Rule rule;

         public RuleInvoker() {
             this.rule = new Rule();
         }

         public void invoke() {
              this.rule.doRule1();
              this.rule.doRule2();
         }
 
     }
 

now, I can generate `RuleInvoker` with `rule` field, and I create a constructor..

But...how can I new a `Rule` then set it to `rule` field at constructor...

I try this..

     final Constructor constructor = rawRuleClazz.getConstructor();

     final DynamicType.Unloaded<Invoker> invokerType = new ByteBuddy()
                    .subclass(Invoker.class, ConstructorStrategy.Default.NO_CONSTRUCTORS)
                    .defineField("rule", new TypeDescription.ForLoadedType(rawRuleClazz),
                            Visibility.PRIVATE, FieldManifestation.FINAL)
                    .defineConstructor(Collections.<Class<?>>emptyList(), Visibility.PUBLIC)
                    .intercept(new Instrumentation() {
                        @Override
                        public InstrumentedType prepare(InstrumentedType instrumentedType) {
                            return instrumentedType;
                        }

                        @Override
                        public ByteCodeAppender appender(final Target instrumentationTarget) {
                            return new ByteCodeAppender() {
                                @Override
                                public boolean appendsCode() {
                                    return true;
                                }

                                @Override
                                public Size apply(MethodVisitor methodVisitor,
                                                  Context instrumentationContext,
                                                  MethodDescription instrumentedMethod) {
                                    StackManipulation.Size size = new StackManipulation.Compound(
                                            MethodVariableAccess.REFERENCE.loadOffset(0),
                                            MethodInvocation
                                                    .invoke(new TypeDescription.ForLoadedType(
                                                            TestRule.class)
                                                            .getDeclaredMethods()
                                                            .filter(isConstructor()
                                                                    .and(takesArguments(0)))
                                                            .getOnly()),
                                            MethodVariableAccess.REFERENCE.loadOffset(0),
                                            MethodConstant.forMethod(
                                                    new MethodDescription.ForLoadedConstructor(
                                                            constructor)),
                                            FieldAccess.forField(
                                                    instrumentationTarget.getTypeDescription()
                                                            .getDeclaredFields().get(0))
                                                    .putter(),
                                            MethodReturn.VOID
                                    ).apply(methodVisitor, instrumentationContext);
                                    return new Size(size.getMaximalSize(),
                                            instrumentedMethod.getStackSize());
                                }
                            };
                        }
                    })
                    .make();

It seems that doest do `invokespecial` , has any short-cut to do this? 

- - sorry I try to found it on document or TestCase, but doesn't found it..so create this 'question issue'~ 

^ ^ thx~

**Comment by raphw** [comment]
Currently, you can use the `MethodCall` instrumentation which is composable. For field access, there is no short cut way to do explicit instrumentations yet. Note that you need to call the super constructor in any constructor. It seems like you use a `MethodConstant` where you probably want to invoke a constructor. This you can do via a `MethodInvocation`.

**Comment by renjie-rm** [comment]
I would like to add the following code snippet to a class

public String traceId = ContextUtil.get(DidiContextEnum.TRACE_ID.name);
Can it be done?
@raphw

**Comment by raphw** [comment]
You would need to define a field via `defineField` and then set the field via any constructor. You can for example use `Advice` to add this code to the end or beginning of each constructor.

**Comment by renjie-rm** [comment]
@raphw
First defineField,
then enhanced before and after the constructor is executed？

**Comment by renjie-rm** [comment]
I can't define fields and specify initialization code blocks? for example
`new AgentBuilder.Default()
            .type(named("com.Template"))
            .transform((builder, typeDescription, classLoader, module) -> {
                DynamicType.Builder.FieldDefinition.Optional.Valuable<?> name = builder.defineField("name", String.class, Modifier.PUBLIC);
                // initialization code blocks

                return name;
            })
            .installOn(inst);
`

**Comment by raphw** [comment]
You can do both, but a non-static field must be initialized in a constructor.

For example, use `Advice` as follows:

```
static void exit(@FieldValue(value = "name", readOnly = false) String name) {
  name = ContextUtil.get(DidiContextEnum.TRACE_ID.name);
}
```

and then apply the visit method with `Advice.to(MyAdvice.class).on(isConstructor())`.

**Comment by renjie-rm** [comment]
ByteBuddyAgent.install();
        new ByteBuddy()
            .redefine(Source.class)
            .defineField("name", String.class, Modifier.PUBLIC)
            .make()
            .load(Source.class.getClassLoader());

Exception in thread "main" java.lang.IllegalStateException: Class already loaded: class com.example.a.Source
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.load(ByteArrayClassLoader.java:307)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$WrappingDispatcher.load(ClassLoadingStrategy.java:357)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:143)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5686)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5675)
	at com.example.a.Main.main(Main.java:19)

@raphw

**Comment by raphw** [comment]
Do you want to add the field or create a new class? If you are doing the latter, you should rename the class. For the former, look into Java agents.

**Comment by renjie-rm** [comment]
I thought this would add fields to the original class

**Comment by renjie-rm** [comment]
Instrumentation install = ByteBuddyAgent.install();
    new AgentBuilder.Default()
        .type(ElementMatchers.is(Source.class))
        .transform((builder, typeDescription, classLoader, javaModule) ->
            builder.defineField("name", String.class, Modifier.PUBLIC))
        .installOn(install);

Instrumentation install = ByteBuddyAgent.install();
    new AgentBuilder.Default()
        .type(ElementMatchers.named("com.example.a.Source"))
        .transform((builder, typeDescription, classLoader, javaModule) ->
            builder.defineField("name", String.class, Modifier.PUBLIC))
        .installOn(install);

Don't these two codes do the same thing?@raphw

**Comment by raphw** [comment]
Once you load a class via `ElementMatchers.is(Source.class)`, its layout is set and the JVM does no longer allow adding fields to it.

You would need to add a matcher that does not load the class, for example via `named("...")`. Additionally, you'd need to run this code before you load the class in other code.

**Comment by renjie-rm** [comment]
> You can do both, but a non-static field must be initialized in a constructor.
> 
> For example, use `Advice` as follows:
> 
> ```
> static void exit(@FieldValue(value = "name", readOnly = false) String name) {
>   name = ContextUtil.get(DidiContextEnum.TRACE_ID.name);
> }
> ```
> 
> and then apply the visit method with `Advice.to(MyAdvice.class).on(isConstructor())`.

Instrumentation install = ByteBuddyAgent.install();
        new AgentBuilder.Default()
            .type(ElementMatchers.named("com.example.a.Source"))
            .transform((builder, typeDescription, classLoader, javaModule) ->
                builder.defineField("name", String.class, Modifier.PUBLIC)
                    .visit(Advice.to(MyAdvice.class).on(MethodDescription::isConstructor)))
            .installOn(install);

@raphw There is something wrong with this code

**Comment by raphw** [comment]
Have you imported the correct `@FieldValue` annotation? It needs to be the `Advice` related one. You can register an `AgentBuilder.Listener.StreamWriting.toSystemOut()` in the agent builder. Otherwise, you will not see any error messages.

**Comment by renjie-rm** [comment]
public class MyAdvice {

    static void exit(@Advice.FieldValue(value = "name", readOnly = false) String name) {
        name = "andre";
    }
}

**Comment by renjie-rm** [comment]
public class MyAdvice {

    static void exit(@Advice.FieldValue(value = "name", readOnly = false) String name) {
        name = "andre";
    }
}

**Comment by renjie-rm** [comment]
@GetMapping
    public Source test() {
        return new Source();
    }

before I didn't add this code. Visit (Advice to (MyAdvice. Class.) on (MethodDescription: : isConstructor))
curl localhost.  return {"id":null,"name":null}

add this code Visit (Advice to (MyAdvice. Class.) on (MethodDescription: : isConstructor))
curl localhost.  return {"id":null}

**Comment by raphw** [comment]
What does your error log say? You can add it as I suggested.

**Comment by renjie-rm** [comment]
What I mean by that is that adding this code
```
.visit(Advice.to(MyAdvice.class).on(MethodDescription::isConstructor))
```
 causes the new words not to be added to the Source class, no error log

**Comment by renjie-rm** [comment]
I didn't add @advice. OnMethodExit to the exit method,
java.lang.IllegalArgumentException: No advice defined by class
I can only initialize the name variable after the constructor, right？
@rephw

**Comment by raphw** [comment]
You can write to fields in an enter advice if that's what you mean.

**Comment by renjie-rm** [comment]
```
@Advice.OnMethodEnter
    static void exit( @Advice.FieldValue(value = "name", readOnly = false) String s) {
        s = "andre";
    }
```
java.lang.IllegalStateException: Cannot access non-static field before calling constructor: public com.example.a.Source()

**Comment by raphw** [comment]
You are right. It's technically legal, but since reading is not allowed, it's fully forbidden. You would need to create your own offset mapping which does not have this restriction.

**Comment by renjie-rm** [comment]
thank you!@raphw
