### ISSUE TITLE
Byte Buddy 1.5.11 does not published to Maven Central Repository

### ISSUE THREAD

**Issue by t-tsutsumi** [raphw/byte-buddy#234]
Probably the cause is a timestamp inconsistency of the artifact files.
Time will tell?

#### maven-metadata.xml in [Maven Central Repository](https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/)

```xml
<metadata modelVersion="1.1.0">
  <groupId>net.bytebuddy</groupId>
  <artifactId>byte-buddy</artifactId>
  <versioning>
    <latest>1.5.11</latest>
    <release>1.5.11</release>
    <versions>
      [...]
      <version>1.5.10</version>
      <version>1.5.11</version>
    </versions>
    <lastUpdated>20161220163144</lastUpdated>
  </versioning>
</metadata>
```

#### Timestamp of artifact files in [Sonatype OSSRH Release Repository](https://oss.sonatype.org/content/repositories/releases/net/bytebuddy/byte-buddy/)

```
byte-buddy-1.5.10.pom: Tue Dec 20 16:30:33 UTC 2016
byte-buddy-1.5.11.pom: Tue Dec 20 13:26:17 UTC 2016
```

**Comment by raphw** [comment]
I just resyncned, thanks for reporting.

**Comment by t-tsutsumi** [comment]
I was able to get an artifact from Maven Central Repository.
Thank you for your response.
