### ISSUE TITLE
"detailed in-code documentation" link is broken

### ISSUE THREAD

**Issue by abhijithtn** [raphw/byte-buddy#235]
In "Where to go from here" section in the documentation in the github repo home page, there is a link to javadoc "detailed in-code documentation", which is broken. The link points to "bytebuddy.net/javadoc" where as the actual link is "bytebuddy.net/javadoc/1.5.10/index.html". May be we must have something like "bytebuddy.net/javadoc/latest/index.html" to point to the latest javadoc always.

**Comment by raphw** [comment]
Thanks, I fixed the link.
