### ISSUE TITLE
confuse for class loader

### ISSUE THREAD

**Issue by ascrutae** [raphw/byte-buddy#238]
I wrote this [example](https://gist.github.com/ascrutae/30d27b55d191c2b38a07b68be4e56def),  the result makes me confuse. here is the result.
```
classLoader : sun.misc.Launcher$AppClassLoader@18b4aac2
Intercepted!
classLoader : null
Intercepted!
classLoader : null
Intercepted!
GET
```
Why the class loader are different?  what should I do if I want to get only one of them?

**Comment by raphw** [comment]
Your interceptor exists twice after injection. It is included by both the Javaagent (added to the class path) and injected by you into the bootstrap loader. The typical way to solve this problem would be to make sure that you inject the interceptor class before loading it. As the agent is executed on the system class loader which always asks its parent to load a class first, you need to inject the class without ever referring to the loaded `.class`.

A common way of solving this problem would be to extract the interceptor into a seperate jar file which you only ever refer to as `provided` in your project, i.e. you do not add it to the final agent jar. As a first step of your agent's setup, you extract this jar file from somewhere where it is not available to your agent's class loader and call `Instrumentation::appendToBootstrapSearch`. Afterwards, the class is available to all of your classes as it is now and will only ever be loaded once.
