### ISSUE TITLE
ASM ClassVisitor Wrapper

### ISSUE THREAD

**Issue by dpsoft** [raphw/byte-buddy#243]
Greetings Rafael,

We are using Byte Buddy and is amazing!!!.

Currently we are working in a feature that permits merge a class into other (Mixin) and for example we can add interfaces to the target type.

The code that we are using is something like this and you can observe the use of ASM Tree API.

```java
 ...
private MixinClassVisitor(MixinDescription mixin, String className, ClassVisitor classVisitor) {
      super(Opcodes.ASM5, classVisitor);
      this.mixin = mixin;
      this.type = Type.getObjectType(className);
}

    ....
@Override
public void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
        cv.visit(version, access, name, signature, superName, addInterfaces(mixin, interfaces));
}

@Override
public void visitEnd() {
      ClassReader cr = new ClassReader(mixin.getMixinClass());
      ClassNode cn = new ClassNode();
      cr.accept(cn, ClassReader.EXPAND_FRAMES);

      ((List<FieldNode>) cn.fields).forEach(fieldNode -> fieldNode.accept(this));
      ((List<MethodNode>) cn.methods).stream().filter(isConstructor()).forEach(mn -> {
          String[] exceptions = new String[mn.exceptions.size()];
          MethodVisitor mv = cv.visitMethod(mn.access, mn.name, mn.desc, mn.signature, exceptions);
          mn.accept(new MethodRemapper(mv, new SimpleRemapper(cn.name, type.getInternalName())));
      });
      super.visitEnd();
  }
}

```

this class is wrapped using an AsmVisitorWrapper:

```java
public class MixinClassVisitorWrapper implements AsmVisitorWrapper {
...
@Override
public ClassVisitor wrap(TypeDescription instrumentedType, ClassVisitor classVisitor, Implementation.Context implementationContext, TypePool typePool, int writerFlags, int readerFlags) {
        return  MixinClassVisitor.from(mixin, instrumentedType.getInternalName(), classVisitor);
   }
}

```
and then
```java
    return (builder, typeDescription, classLoader) -> builder.visit(new MixinClassVisitorWrapper(...));
```
  We have noticed that if we try to use a single agent (a single AgentBuilder) where first applying the mixins and then a ByteBuddy Advice and assuming that the mixin was applied, for example adding the Interface to a target class. The issue that we are experimenting is like this:

  Cannot assign class [the target class] to interface [injected interface]. Class loader: sun.misc.Launcher$AppClassLoader.

  But if we run this in separated agents (2 agents builders) all works ok!!.

  The issue can be related to the ASM Tree API? or we are losing something?

  Cheers,
  Diego

**Comment by raphw** [comment]
Thanks for using Byte Buddy, great that you like it!

Byte Buddy's high-level APIs are not aware of what the low level-APIs are doing. If you choose to write manual ASM then Byte Buddy's `Advice` does not parse the code to integrate it into its meta description. This is however done when a type is parsed for the first time using a `TypePool` where no on-the fly modifications are applied.

What you can do: Use Byte Buddy's API to implement an interface using Byte Buddy's API but you would also apply a `MethodVisitor where you remove the duplicate interface before it is applied to the `ClassWriter`. Otherwise, Byte Buddy has no chance to know about it.
