### ISSUE TITLE
Please make Advice.DynamicValue.ForSerializedValue API public

### ISSUE THREAD

**Issue by orange-buffalo** [raphw/byte-buddy#246]
Hello,

Currently it is possible to bind a serialized value to advice annotation via `Advice.WithCustomMapping#bindSerialized`. But at the moment of execution of this method the value to bind should be defined. There is a scenario when this is a significant limitation: when value to bind depends on the instrumented type/method (this is useful to calculate something only once during instrumentation and inject calculated value for advice method execution).

In order to implement this case now, one should define a `DynamicValue` which is very similar to (if not a copy of) `Advice.DynamicValue.ForSerializedValue`. It would help a lot if this class (or some similar API to dynamically calculate a `Serializable` value in `resolve` method) would be accessible for `Advice` clients. 

Thanks,
Bogdan

**Comment by raphw** [comment]
I will look into it, should not be a big thing so I can do this.

**Comment by raphw** [comment]
Instead of making this API public, I created a public class `SerializedConstant` which is a `StackManipulation`. Using this manipulation, a custom binding is very easy to implement; the constant is now also used by the dynamic binding.

**Comment by orange-buffalo** [comment]
Thanks a lot!
