### ISSUE TITLE
Add API for defining outer and inner classes

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#247]
Currently, Byte Buddy does not allow adding inner and outer classes. This should be made possible by an API.

**Comment by liuchang0403** [comment]
does asm can do this ?

**Comment by raphw** [comment]
Yes, ASM allows this. Have a look at the `ClassVisitor` that you can apply via a wrapper.

**Comment by Dynarev** [comment]
One solution I have used in the past to get around this is to make my own class using the same package declaration so i can access more things. Then target a method and have that call my new class to instance it, Dirty but works. Some type of expression editor, again right up my issue alley.

**Comment by raphw** [comment]
This has become more urgent in order to support nestmates.

**Comment by raphw** [comment]
Done on master.

**Comment by sravanthy** [comment]
Can we add nested classes using byte buddy for java 8 version .

**Comment by raphw** [comment]
Yes, it is possible by using the type builder DSL.

**Comment by sravanthy** [comment]
Hey can you please share any code snippet 
Currently I'm able to generate a class with fields and methods using 

   Class<?> dynamicType = new ByteBuddy()
                .subclass(Object.class)
                .method(named("toString")).intercept(FixedValue.value("Hello World!"))
                .make();

**Comment by rajeshb-anthem** [comment]
```

@Test
	public void testCreateInnerClass() throws Exception {
		TypeDescription sampleInner = new TypeDescription.Latent("foo.Outer$Inner", Opcodes.ACC_PUBLIC, TypeDescription.Generic.OBJECT) {
			@Override
			public String getSimpleName() {
				return "Inner";
			}

			@Override
			public boolean isAnonymousType() {
				return false;
			}

			@Override
			public boolean isMemberType() {
				return true;
			}
		};

		DynamicType.Unloaded<?> outerClazz = new ByteBuddy()
				.subclass(Object.class)
				.name("foo.Outer")
				.declaredTypes(sampleInner)
				.make();

		Class<?> outer = outerClazz.load(getClass().getClassLoader(), ClassLoadingStrategy.Default.CHILD_FIRST.opened()).getLoaded();

		DynamicType.Unloaded<?> innerClazz = createPlainWithoutValidation()
				.name(sampleInner.getName())
				.innerTypeOf(outer).asMemberType()
				.make();

		Class<?> type = innerClazz.load((InjectionClassLoader) outer.getClassLoader(), InjectionClassLoader.Strategy.INSTANCE).getLoaded();

		innerClazz.saveIn(new File("target/generated-sources"));
		outerClazz.saveIn(new File("target/generated-sources"));
		assertThat(type.isMemberClass(), is(true));
	}
```
We can generate inner class with the above code, but only Outer.class file is getting saved in the given directory. why Outer$Inner.class is not getting saved?
What is the best way to generate multiple static nested inner classes dynamically at runtime including Outer class?

**Comment by raphw** [comment]
Using the DSL is already the best way.

I cannot reproduce this problem. Could you check a little what is going on on your system? Does the class get overridden, i.e. is it stored if you only store inner class? Otherwise, set some breakpoints in *saveIn* to see if something unexpected happens, maybe your file system is confused over *$*.

**Comment by rajeshb26** [comment]
@raphw Thanks for your response. My bad, i could see the generated Outer$Inner.class. It's working perfectly fine. All inner classes from my project were not shown in my workspace.

I want to generate .class files directly using byte buddy like the way how java compiler generates .class files for below java code snippet. ( i will be getting the metadata like class name and its field's names from an api/database) 

```
public class Outer {
    private Inner1 inner1;
    public static class Inner1 {
        private Inner2 inner2;
    }
    public static class Inner2 {
        private Inner3 inner3;
    }
    public static class Inner3 {
    }
}
```
@raphw Can you please suggest Should i use the same approach as the above example [](https://github.com/raphw/byte-buddy/issues/247#issuecomment-461634190)

**Comment by raphw** [comment]
I'd iterate over all inner classes and once you generate all of them, generate the outer class that is required to reference all of its inner classes.
