### ISSUE TITLE
How to redefine core JDK classes using ByteBuddy

### ISSUE THREAD

**Issue by Aleishus** [raphw/byte-buddy#250]
Is it possible to redefine core JDK classes(e.g. java.*) using byteBuddy agent ? If so ,would you show me some code example. Thank you in advance!

**Comment by raphw** [comment]
Yes, please see this issue: https://github.com/raphw/byte-buddy/issues/236

**Comment by Aleishus** [comment]
It's works, byte buddy is awesome!

**Comment by raphw** [comment]
Great, glad you like the library!

**Comment by raphw** [comment]
Have a look at the `Advice` component. With this component, you can define `OnMethodEnter` advice where you use the `Argument` annotation where you can set a property `readOnly = false`. This way, you can change the value.

**Comment by Aleishus** [comment]
Here is my code , is this right?
           
              @Advice.OnMethodEnter
              public static void before( @Advice.This(typing = Assigner.Typing.DYNAMIC) Object self,
                     @Advice.AllArguments(typing = Assigner.Typing.DYNAMIC) Object[] originals,
                     @Advice.AllArguments(readOnly = false) Object[] wraps )

**Comment by raphw** [comment]
I would not recommend you to read all arguments if you only need to change the first one:
```java
@Advice.OnMethodEnter
static void before(@Advice.Argument(value = 0, readOnly = false) Runable task) {
  task = myInterceptedWrapMethod(task);
}
```

**Comment by Aleishus** [comment]
I see,thx! 😀

**Comment by raphw** [comment]
You do not seem to specify the advice in your transform method. You have to register it, of course.

**Comment by raphw** [comment]
you have to set the annotation property readOnly to false for that.

**Comment by raphw** [comment]
In this case I would need a small reproduction of your problem. From what I have it is difficult to tell what goes wrong and where.

**Comment by arjunsawhney** [comment]
Step 1: 
I instrument the log method of the Logger.class in java.util.Logging which is the following method:
public void log(Level var1, String var2) {
        if (this.isLoggable(var1)) {
            LogRecord var3 = new LogRecord(var1, var2);
            this.doLog(var3);
        }
    }

Step 2:
I instrument this method in my agent class Agent.java in this fashion:

private static void install(Instrumentation instrumentation) {
   logAdvice().installOn(instrumentation);
}

private static AgentBuilder logAdvice() {
return new AgentBuilder.Default().disableClassFormatChanges()
.ignore(ElementMatchers.none())
.with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
.with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
.with(AgentBuilder.TypeStrategy.Default.REDEFINE)
.type(ElementMatchers.named("java.util.logging.Logger"))
.transform(new AgentBuilder.Transformer.ForAdvice().include(MyAgent.class.getClassLoader())
.advice(ElementMatchers.nameEndsWith("log"),"ABC"));
}

Step 3:
This java agent is attached to an application that performs a log using java.util.logging.Logger in the following fashion:
log.info("12345");

The agent is attached using java -javaagent

Step 4:
I am able to instrument the log method of java.util.logging.Logger and I am able to advice it in ABC.java
Then inside ABC.java I perform the following:
@Advice.OnMethodEnter
public static void enterFilter(@Advice.AllArguments(readOnly = false, typing=Assigner.Typing.DYNAMIC) Object[] allArguments, @Advice.Origin Method method) {
String message = (String) allArguments[1];
System.out.println(message); //o/p is 12345
message="*****";
System.out.println(message); //o/p is *****
System.out.println(allArguments[1]); //o/p is 12345
allArguments[1] = message;
System.out.println(allArguments[1]); //o/p is still 12345
// Expected o/p for last print statement is *****
}

I hope this makes sense. Any help would be greatly appreciated, thank you.

**Comment by wangkaijin** [comment]
I encountered the same problem

**Comment by raphw** [comment]
You probably have to set your own `.ignore` matcher that does not exclude system types.

**Comment by wangkaijin** [comment]
Thanks
