### ISSUE TITLE
Can I use byte-buddy to manipulate code inside a methods.

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#251]
This requirement seems a little strange, but it is real.

Let's say a method is like this:
```java
public void getAndPrint(Context context){
     long offset = context.getOffset();
     long mod = this.mod;
     System.out.println(offset / mod);
}
```

Here is the thing, which I want to do.
I want to inject codes to change `mod`, but this instance is use in many threads, if I go to change `this.mod`, other threads go wrong.

How can I inject codes between `long mod = this.mod;` and `System.out.println(offset / mod);`. Is this possible?

**Comment by raphw** [comment]
You can, using an `AsmVisitorWrapper`. You do however need to write your own ASM. In the future, I might supply a better mechanism but generally, I do not recommend writing instrumentation against a method's implementation as such implementations can change easily.

**Comment by wu-sheng** [comment]
I think your API is better than the asm ^^. I prefer your mechanism rather than asm's. 
So you have schedules to implement this, please, let me know. 

Looking forward.

**Comment by raphw** [comment]
Thanks, I appreciate it. I am planing to write this component at some point: https://github.com/raphw/byte-buddy/issues/187

It would allow you to substitute any field or method access within a method with a row of field or method accesses. If you have a commercial project that requires this sort of thing and you do not want to wait for me to find some free time, please get in touch and I could develop it for you in paid time.

**Comment by wu-sheng** [comment]
It's just for my open source tracer project. It can wait, ha.

**Comment by karthikraobr** [comment]
Thanks for this amazing library. Just checking if this was implemented, since I too need something similar. TIA!

**Comment by raphw** [comment]
I have layed the foundation for this with the `MemberSubstitution` component that already is a part of Byte Buddy which I plan to extend at some point to allow for arbitrary replacements. Unfortunately, I currently lack the time to work on this as Java 9 support has drained my ressources and I have a little kid at home.

If you need this for a commercial project, please get in touch and I can offer you a (reasonable) quota for developing this feature.

**Comment by Hasunemiku2015** [comment]
> I have layed the foundation for this with the MemberSubstitution component that already is a part of Byte Buddy.

Is it implemented now? For the above example by wu-sheng, would you mind giving a quick example on how to modify the code within a method implementation?

**Comment by raphw** [comment]
`MemberSubstitution` offers the *chain* semantics. It is still pretty low level, but definetly works quite well for that. Have a look at `MemberSubstitutionTest` to see some examples.
