### ISSUE TITLE
Add proxy annotation for invoking specific method

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#252]
Similar to the `@SuperCall` and `@MethodCall` annotations, there should be an annotation to invoke a specific method with a given signature.

**Comment by Dynarev** [comment]
I think this may be similar to my issue, or at least contained within it if you would like to combine them

**Comment by raphw** [comment]
After considering such an API, from a type-safety perspective it is basically impossible to implement this without requiring any preconfiguration. It would therefore be easiest to implement a custom annotation binding which is probably already sufficiently covering this use case.
