### ISSUE TITLE
Improve lazy resolution for class redefinition/rebasement and subtyping

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#258]
Currently, some super type properties are required by Byte Buddy even if they are not used, such as parameterized argument properties when resolving type signatures (owner type) or super class methods (for creating constructors).

This should be improved to not require any navigation as type parsing is often an expensive operation or even might be impossible.

**Comment by raphw** [comment]
With a first change, super constructor resolution is lazy. It should be investigated if this should be linked to the required method graph such that the overhead of looking up the structure for any constructor can be avoided.

**Comment by Dynarev** [comment]
A way to get an instance of the classPool and pull out the class you want rather than trying to search for classes, Do you think this would be a better/less overhead solution?

**Comment by raphw** [comment]
Added a decorator mode and lazy type hierarchies.
