### ISSUE TITLE
LoggerInterceptor for final method not working

### ISSUE THREAD

**Issue by popkutty** [raphw/byte-buddy#26]
Hi, I have a class where I have a final method. I used LoggerInterceptor as mentioned in you example. I cannot able to see the log for it. If I remove the final quantifier, I can able to see the log.

**Comment by raphw** [comment]
Are you subclassing a class with a `final` method? It is not possible to override such a method, you would need to use a Java agent or some other sort of class redefinition. I once blogged about this: http://mydailyjava.blogspot.no/2015/01/make-agents-not-frameworks.html

**Comment by popkutty** [comment]
I don't do such. Have look at my code pls.
public class Hello {
public final  String sayHello(){
	return "hello";
}
}

That's it. I cannot use byte-buddy to log this 'sayHello' function

**Comment by raphw** [comment]
Can you post a running example that uses Byte Buddy to instrument your class?

**Comment by popkutty** [comment]
Ya here is that. I have these 3 classes in 3 different files.

Main class - To create bytebuddy class and run it.

import static net.bytebuddy.matcher.ElementMatchers.named;
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.implementation.MethodDelegation;
public class ByteEx {
	public static void main(String[] d) throws Exception{
		new ByteEx().loadclassDD();
	}
	
	public void loadclassDD() throws Exception{
		Hello loggingDatabase = new ByteBuddy()
		  .subclass(Hello.class)
		  .method(named("sayHello")).intercept(MethodDelegation.to(LoggerInterceptor.class))
		  .make()
		  .load(getClass().getClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
		  .getLoaded()
		  .newInstance();
		System.out.println(loggingDatabase.sayHello());
	}
}

//Logger class. - This will return upper case of original string data if my method is called.
import java.util.concurrent.Callable;
import net.bytebuddy.implementation.bind.annotation.SuperCall;

public class LoggerInterceptor {
	public static String log(@SuperCall Callable<String> zuper)
		      throws Exception {
		    System.out.println("Calling database");
		    try {
		      return  zuper.call().toUpperCase();
		    } finally {
		      System.out.println("Returned from database");
		    }
		  }
	}

Target class which have a method will return lower case data
public class Hello {
public final  String sayHello(){
	return "hello";
}
}

**Comment by raphw** [comment]
Hi, as I said, it is not possible to **subclass* and override a `final` method. Not with Byte Buddy and not on the Java platform in general. You would need to use a Java agent and redefine the class as I described in the linked blog posting.

**Comment by popkutty** [comment]
You mean to say I should remove the final from the class?
 I've seen the blog, but still this cannot be achieved for final method right?

**Comment by raphw** [comment]
No, it is simply not possible to override a final method, any (generated) class that would override such a method would be rejected with a verification error by the Java virtual machine. For this reason, Byte Buddy does not even consider overriding such a class.

**Comment by popkutty** [comment]
OK. Ya I think you are correct. I tried couple of interceptor, but no luck. OK. Thanks for the response. Good luck for your project. It's really awesome and simple.

**Comment by raphw** [comment]
Thanks!
