### ISSUE TITLE
[Question] how to transform returns on a list of named objects

### ISSUE THREAD

**Issue by MarcMagnin** [raphw/byte-buddy#262]
Hi,
Thanks a lot for that awesome library!
I wanted to implement an agent and handle a method that returns a `Set` of objects
How can I use `returns()`?

ie :
```java
returns(named("Set<well.known.object>"))
```
just like that?:
```java
returns(Set.class)
```
As well I might use a lot of `new AgentBuilder.Default().with(byteBuddy)` in order to hook to multiple methods. Is there is any perf consideration to take? 

Many thanks!

**Comment by MarcMagnin** [comment]
As well can you hook onto an interface?

**Comment by raphw** [comment]
Byte Buddy exposes a generic description of types. You can use the `returnsGeneric` matcher and implement any custom logic for it. For example:

```java
returnsGeneric(type -> type.asErasure().represents(Set.class) 
  && type.getSort().isParameterized()
  && type.getTypeArgument().get(0).asErasure().getName("well.known.Object");
```

Would cover your use case.

**Comment by MarcMagnin** [comment]
Cheers! 
Thanks for that quick reply. 
About the interface bit, I would like to instrument type that I don't know in advance (classes that would be implemented later on). How could I manage that?
Many many thanks!

**Comment by raphw** [comment]
You can implement your own `ElementMatcher` where you can decide for any `TypeDescription` if you want to instrument this type. The API is similar to the reflection API.
