### ISSUE TITLE
Change static field value at runtime

### ISSUE THREAD

**Issue by PureSpider** [raphw/byte-buddy#266]
I am trying to modify a class from the java standard runtime, specifically `sun.awt.windows.WTrayIconPeer` and trying to change the values of the static fields `TRAY_ICON_WIDTH` and `TRAY_ICON_HEIGHT`.
I can't find any information on how to change values of fields, only on how to define fields at runtime.
How would I go on doing this?

This is what I got so far - this of course gives me a `java.lang.IllegalStateException: Duplicate field definition`:
```java
ByteBuddyAgent.install();

TypePool typePool = TypePool.Default.ofClassPath();
new ByteBuddy() //
	.redefine(typePool.describe("sun.awt.windows.WTrayIconPeer").resolve(), ClassFileLocator.ForClassLoader.ofClassPath()) //
	.defineField("TRAY_ICON_WIDTH", int.class, Visibility.PACKAGE_PRIVATE, FieldManifestation.FINAL, Ownership.STATIC) //
	.defineField("TRAY_ICON_HEIGHT", int.class, Visibility.PACKAGE_PRIVATE, FieldManifestation.FINAL, Ownership.STATIC) //
	.make() //
	.load(ClassLoader.getSystemClassLoader());
```

**Comment by raphw** [comment]
For chaning values of existing fields, you rather have to change values using the `.field(ElementMatcher` API. While this allows you to change the fields, you will be out of luck. `final` values of primitives are compile-time constants that are inlined whereever the field is referenced. Thus, the values are set whereever they are used.
