### ISSUE TITLE
[Question] How can I test a new ElementMatcher?

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#268]
In my agent, I create a `ElementMatcher` implementation to judge all `Object.class`'s methods. It is like this: https://github.com/wu-sheng/sky-walking/blob/d0bb872553924575adfb08e2915204340c42979b/skywalking-sniffer/skywalking-api/src/main/java/com/a/eye/skywalking/plugin/bytebuddy/AllObjectDefaultMethodsMatch.java

And I want to build a test case for it. How can I do? And does `byte-buddy` have a `test-tools` for build byte-buddy object?

**Comment by raphw** [comment]
Byte Buddy does not offer any test-tools but matchers can be tested the easiest by creating types that fit the specification. These types can then represented via `TypeDescription.ForLoadedType`. By my experience, this is the most reliable way and also type-safe.

**Comment by wu-sheng** [comment]
Can you give me a demo about `TypeDescription.ForLoadedType`? I have no idea how to use.

**Comment by raphw** [comment]
Like this:

```java
class Foo { }
TypeDescription d = new TypeDescription.ForLoadedType(Foo.class);
assert matcher.matches(d) == true;
```
