### ISSUE TITLE
young gc where cause rpc server timeout exception

### ISSUE THREAD

**Issue by dragontree101** [raphw/byte-buddy#269]
i use byte-buddy as agent and use zipkin to recode my thrift rpc trace, i found my rpc client has timeout exception(i set timeout is 500ms in thrift client) when rpc server has young gc, and young gc time bigger than 100ms

my rpc server logic only less than 10ms in normal and young gc will spend 100 ms to do gc work,  i think rpc server should not timeout, i don't know what's problem will cause timeout exception.

does i use byte buddy will cause young gc spend more time to do gc work?

**Comment by raphw** [comment]
Byte Buddy puts some preasure on the young GC but if you retain objects (everything is immutable), it should not put problems onto your system. I used Byte Buddy in high performance environments without problems.
