### ISSUE TITLE
Potentially replace argument List with Collection, Iterable, or Set: ByteBuddy#makeInterface, possibly other methods

### ISSUE THREAD

**Issue by rgoldberg** [raphw/byte-buddy#27]
Why is there `ByteBuddy#makeInterface(List)` instead of either:

1. `ByteBuddy#makeInterface(Collection)` if you want to allow more argument types

2. `ByteBuddy#makeInterface(Iterable)` if you want to allow even more argument types, but not necessarily have a `size()` method to improve `ByteBuddyCommons#join(...)` performance

3. `ByteBuddy#makeInterface(Set)` if you want to indicate that each super-interface `Class` should only be specified once

Is there a need to preserve the ordering of the input `Class` elements?

I have a `Set<Class>` that I'd like to pass in as an argument, but, with the existing `makeInterface` methods, I need to convert it to either an array, or a `List`, which seems unnecessary.

It's possible that `List` arguments of other methods could also be converted, but I haven't looked over the whole Byte Buddy API.

**Comment by raphw** [comment]
This choice was made as the order in which the interfaces are declared is exposed via the reflection API. Because of this, it may affect code that uses reflection.  Requiring lists should reflect this consequence.

Let me however think about it, I might adapt a different signature.

**Comment by rgoldberg** [comment]
If a `List` is passed as the argument to `ByteBuddy#makeInterface(Collection)`, any iteration done inside the method will still be performed in the `List` order.  So, as long as the method doesn't use any `List` methods that don't exist in `Collection`, then a `(Collection)` method should be equivalent for a `(List)` argument.

The JavaDoc doesn't specify that the super interfaces will be declared in the order of their occurrence in the `List`, and it doesn't say how duplicates are handled (I would assume that an interface will be declared in the order of the first occurrence of each interface).  The same would hold true if you change the signature to `(Collection c)`, and just specify that an interface will be declared in the order of the first occurrence of the interface in `c.iterator()`, which, for `List`, is obviously exactly the same as the order in the `List` itself.

If I, as the caller, don't care about the order of the interface declarations (or if I care about the order, but just want to specify it via some other `Collection`, like a `SortedSet`), why should `makeInterface(...)` care?

**Comment by raphw** [comment]
I have adopted your suggestion with some additional validation of the input which was meaningful for lusts that can contain duplicates even though it would not be allowed. I will soon push an updated version. Thanks for your input.

**Comment by rgoldberg** [comment]
Thanks for updating the API so quickly.

One additional `makeInterface` method might be useful.

Right now, you have:

    makeInterface(Collection<? extends TypeDescription> typeDescriptions)

It would be simpler for a caller who just has `Collection<Class<?>>` to be able to call:

    makeInterfaceFromClassCollection(Collection<Class<?>> classColl)

You can probably come up with a better name than `makeInterfaceFromClassCollection`; I just had to pic something that was different from `makeInterface` to avoid a duplicate method signature due to type erasure.

**Comment by raphw** [comment]
You are right. Initially, I did not want to do it because I wanted to avoid polluting the API with additional method names. However, I will now add overloaded methods based on `Iterable`:

```java
makeInterface(Iterable<? extends Class<?>> types)
```

**Comment by raphw** [comment]
The changes are now in place.

**Comment by rgoldberg** [comment]
Thanks.
