### ISSUE TITLE
Where did MethodDelegation.filter go?

### ISSUE THREAD

**Issue by YoannBuch** [raphw/byte-buddy#271]
I'd like to filter the target methods of my interceptor using [MethodDelegation.filter](http://bytebuddy.net/javadoc/1.5.0/net/bytebuddy/implementation/MethodDelegation.html#filter-net.bytebuddy.matcher.ElementMatcher-)

However it was removed in version 1.6+. Although it is still mentioned in the class javadoc: 

> The potential targets of the method delegation can further be filtered by applying a filter.

What's the new way of doing it?

Thanks

**Comment by raphw** [comment]
You can configure a delegation prior to spplying it by MethodDelegation.withDefaultConfiguration. this way, Byte Buddy can optimize much better if you reuse the instance.

**Comment by YoannBuch** [comment]
Thanks!
