### ISSUE TITLE
#question#How to invoke method ON the return value of another method call?

### ISSUE THREAD

**Issue by jujusharp** [raphw/byte-buddy#275]
Now, I wanna to generate a class like:

     public Object someMethod(){
           return getSomeProperty().callOtherMethod();
     }

I can generate the code call with "field" in the class with:

     MethodCall.invoke(otherMethod).onField("someField")

and here is the code generated:

     public Object someMethod(){
           return someField.callOtherMethod();
     }

I found `WithoutSpecifiedTarget`.on() support call with **class instance**, **argument** and **field**, but can't support `method return value`. Is there any way to do this?

**Comment by raphw** [comment]
Unfortunately, there is currently no good way of doing so. You can generate such more complex code by defining a custom `ByteCodeAppender`. I consider adding something viable in the future.

**Comment by jujusharp** [comment]
Got it, Thanks!

**Comment by liuchang0403** [comment]
i think it is not nesseray. byte buddy is a easy lib compare to ASM, i think it is enough now.

**Comment by raphw** [comment]
Captured by #321
