### ISSUE TITLE
How to shrink javaagent's dependencies that already provided in host JVM

### ISSUE THREAD

**Issue by zhongl** [raphw/byte-buddy#278]
I have wrote a javaagent with bytebuddy to probe all HTTP calls in a spring boot application.

```java
public class Agent {

    public static void premain(String args, Instrumentation inst) {
        new AgentBuilder.Default()
          .disableClassFormatChanges()
          .type(isSubTypeOf(AbstractClientHttpRequest.class))
          .transform(new Transformer() {
            @Override
            public Builder<?> transform(Builder<?> b, TypeDescription td, ClassLoader cl, JavaModule m) {
              return b.visit(Advice.to(Probe.class).on(named("executeInternal")));
            }
        }).installOn(inst);
    }

    static class Probe {
        @Advice.OnMethodExit(onThrowable = Throwable.class)
        static void exit(
          @Advice.Origin String name, 
          @Advice.This ClientHttpRequest request, 
          @Advice.Return ClientHttpResponse response
        ) {
            try {
                System.out.printf("%s\t%d\t%s\n" , 
                  request.getMethod(), 
                  response.getRawStatusCode(), 
                  request.getURI());
            } catch (Exception ignore) {
            }
        }
    }
}
```

> [Here](https://github.com/zhongl/explore-bytebuddy/tree/master/experiment/javaagent-dependencies) is the runnable code.

It works fine, but the required dependency `spring-web` (and it's transitive dependencies) enlarge the final package size, which has already provided in host JVM.

I've tried to set the scope of dependency to `provided`, but it didn't works because of `ClassNotFoundException`.

Is there a way to shrink the dependencies in my case ?

**Comment by nickgrealy** [comment]
I see you're using maven, and `provided` sounds like it's logically equivalent, but I'll share anyway...

I was doing something similar, and I used [`compileOnly`](https://docs.gradle.org/2.12/release-notes.html#support-for-declaring-compile-time-only-dependencies-with-java-plugin) (Gradle) - and that worked for me. Dependencies weren't packaged in the end artifact, it relied on them being present in the "host" project.

**i.e.**
```
dependencies {
    compileOnly "org.springframework:spring-web:4.3.7.RELEASE"
}
```

**Comment by zhongl** [comment]
@nickgrealy thank you for sharing, but it didn't help.

Normally, it works only if javaagent and spring classes shared the same `ClassLoader`. 

But in my case,  a spring boot application will load class from a customized `ClassLoader` named `LaunchedURLClassLoader` in runtime. Without dependency of `spring-web` , the `ClassLoader` of javaagent , which is `SystemClassLoader`, could not find the spring classes.

**Comment by raphw** [comment]
You still need to be able to locate these classes at runtime for Byte Buddy to work. A Java agent is loaded by the system class loader but this is not necessarily true for your application classes.

As a convenience, Byte Buddy offers `AgentBuilder.Transformer.ForAdvice` as a builder for creating an advice transformer that looks up both your agent and the transformed class loader and creates advice by resolving classes from both class loaders.

**Comment by zhongl** [comment]
@raphw thanks for reply, it helps a lot. A new version of code is:

```java
public static void premain(String args, Instrumentation inst) {
   final ForAdvice transformer = new ForAdvice().advice(named("executeInternal"), Probe.class.getName());

   new AgentBuilder.Default()
           .disableClassFormatChanges()
           .type(new RawMatcher() {
               @Override
               public boolean matches(TypeDescription td, ClassLoader cl, JavaModule m, Class<?> cbr, ProtectionDomain pd) {
                   try {
                       final String name = "org.springframework.http.client.AbstractClientHttpRequest";
                       final Class<?> c = cl.loadClass(name);
                       return isSubTypeOf(c).matches(td);
                   } catch (Exception e) {
                       return false;
                   }
               }
           })
           .transform(new Transformer() {
               @Override
               public Builder<?> transform(Builder<?> b, TypeDescription td, ClassLoader cl, JavaModule m) {
                   return transformer.include(cl).transform(b, td, cl, m);
               }
           }).installOn(inst);
}
```

> [Here](https://github.com/zhongl/explore-bytebuddy/pull/1) is the more details.

I'm not sure this the best way to do that, but it works now.

As you see, i had wrote a new `RawMatcher` for matching sub type of `AbstractClientHttpRequest`. Is there another convenience for `isSubTypeOf("org.springframework.http.client.AbstractClientHttpRequest")`?

**Comment by raphw** [comment]
Write your matcher as `hasSuperType(named("org.springframework.http.client.AbstractClientHttpRequest"))`.

**Comment by zhongl** [comment]
Thank you so much.
