### ISSUE TITLE
Change method modifiers with agent

### ISSUE THREAD

**Issue by glamarre360** [raphw/byte-buddy#281]
I have an java agent and I install an AgentBuilder.Transformer on the Instrumentation for a specific type. Now I need to change the modifiers on a specific method of that type and I don't understand how I do that.

**Comment by raphw** [comment]
Have a look at the `Transformer` API. Alternatively, you can fallback to the underlying ASM API. Note that you can only change modifiers prior to loading a class.

**Comment by glamarre360** [comment]
In terms of code I have an agent builder that apply transformers like that:
```java
agentBuilder = agentBuilder
    .type(transformer.getMatcher())
    .transform(transformer.getTransformer())
    .asDecorator();
```
and then install it on the instrumentation with `agentBuilder.installOn(instrumentation);`

The get transformer code look like that:

```java
public AgentBuilder.Transformer getTransformer() {
    return new AgentBuilder.Transformer() {

        @Override
        public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader) {
            //This is where I need to change the modifiers of a specific method
            return builder;
        }
    };
}
```

**Comment by raphw** [comment]
Have a look at `Transformer.ForMethod.withModifiers`.

**Comment by glamarre360** [comment]
I see that transformer can probably do what i want but how do I apply this transformer on a method because the agent builder apply it on a type.

**Comment by glamarre360** [comment]
I have found the way to apply it on a field but for a method it seems like I need to redefine it to ba able to apply a transformer to it. Am I correct?

**Comment by raphw** [comment]
Yes, this is correct, unfortunately. I hope to improve this at some time. Consider using a method visitor for now.

**Comment by glamarre360** [comment]
I have seen the MethodVisitor but I dont quite understand how to change the modifiers with it.

**Comment by raphw** [comment]
They take the modifiers as an argument.

You can also supply `SuperMethodCall.INSTANCE` as an implementation.

**Comment by glamarre360** [comment]
The Method I want to intercept is Final and i want to remove that Final modifiers on it so I can redefine it in a class I generate at runtime. But any intercept on the method wont work because its final so i cant change the modifiers?

**Comment by glamarre360** [comment]
I've finally succeed in applying the #107 solution but in my use case my super call takes parameters and i don't see how to call the super with parameters in my interceptor.

**Comment by raphw** [comment]
If you are using the `@SuperCall` annotation, it retains the original arguments. Alteranatively, have a look at the `@Morph` annotation.
