### ISSUE TITLE
[Question]How can I get the line num(startline - endline) of the intercepted method?

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#283]
Right now, I have interceptors like this:
```java
    /**
     * Intercept the target instance method.
     * @param obj target class instance.
     * @param allArguments all method arguments
     * @param method method description.
     * @param zuper the origin call ref.
     * @param instanceContext the added field of enhanced class.
     * @return the return value of target instance method.
     * @throws Exception only throw exception because of zuper.call()
     *          or unexpected exception in sky-walking ( This is a bug, if anything triggers this condition ).
     */
    @RuntimeType
    public Object intercept(@This Object obj, @AllArguments Object[] allArguments, @Origin Method method, @SuperCall Callable<?> zuper,
            @FieldValue(ClassEnhancePluginDefine.contextAttrName) EnhancedClassInstanceContext instanceContext) throws Throwable {
```

And I used a `matcher` and `MethodDelegation.to` to intercept the target method. I want to know the line num, startline num and endline num, in order to match the Java stack.

Is there any solutions? And can you give me a demo codes?

**Comment by raphw** [comment]
That is not really possible. The origin method is synthetic, i.e. it does not have a representation in the source code; there is no line number Byte Buddy can provide. Can you give an example of what you are trying to achieve?

**Comment by wu-sheng** [comment]
I am sure it is possible in theory. We can decompile the class file to the source code with line number, and these are line number in Exception. Also, I have seen using asm's`visitline`(maybe this) in commercial product to get linenum, can not share it.

I will explain why I need this.

As you known, I am APM product developer, I want to give serval snapshots to the thread, getting thread stacks by that. I want to match the stack element to the intercept point. In an intercept point, I known the class name and method signature, but in stack element, these is only method name and line number. By all these, still have a mismatch issue. This is background story. Hope you can help on this.

**Comment by raphw** [comment]
The line number information can in theory be extracted using Java 9's stack walker API or by creating an exception and reading its stack trace. The information is contained in a class file and it is available using ASM but it is not exposed in the delegation API as there is no guarantee this information exists (either because it is not included or because you are creating a subclass).
