### ISSUE TITLE
Performance improvement advice requested 

### ISSUE THREAD

**Issue by cliviu** [raphw/byte-buddy#284]
Hi,
  I have used byte-buddy to instrument creation of a RequestSpecificationDecorated in serenity-rest-assured. I have pretty big performance problems after switching to this implementation. Here is the class which is using byte-buddy : https://github.com/serenity-bdd/serenity-core/blob/master/serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestSpecificationFactory.java
  So, instead of directly creating instances of RequestSpecificationDecorated and ResponseSpecificationDecorated now the RestSpecificationFactory is used for creating new instances of the above mentioned objects.  Can you give any advice how can I improve the performance in this case  ?
  Thanks ..

**Comment by raphw** [comment]
Hi, with your linked approach you are creating a new class every time such a method is invoked. This is very expensive. You should of course cache the classes you are generating. Byte Buddy offers such a facility by the `TypeCache` class.

Instead of delegating to an instance, you should rather delegate to a field and explicitly set the field value for every instance of this cached class.  You can initialize the field either by reflection or by implementing setters via some interface that you implement using `FieldAccessor`.

**Comment by cliviu** [comment]
Hi, Thanks for your answer... My problem is that I cannot cache because I have every time different instances to delegate to... Normally, the delegate instance should be the cache key but since this is everytime different... I cannot take advantage from the TypeCache. 

What do you mean by delegating to a field ? Field of which class ? I do not want to implement inside the class all methods of the three interfaces but to automatically delegate any calls belonging to the mentioned interfaces to the specific instance that I pass in the constructor .. The goal is not to implement the new interface methods from the three interfaces when a new version of the interfaces is released but to automatically delegate to the instance above mentioned ...

**Comment by cliviu** [comment]
Thanks, I got now the trick with delegation to the field :-)

**Comment by cliviu** [comment]
Thank you very much, I have made the change, the  performance improved almost twice but is still two times slower as the creation of  the non-instrumented objects. Can you please take a look at 
https://github.com/serenity-bdd/serenity-core/blob/master/serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestSpecificationFactory.java , see if this is what you meant ?

**Comment by cliviu** [comment]
Hi, thanks again for your hints. I have the changes that you have suggested and the performance improved but is still two times slower as by directly instantiating the objects. Can you please shortly look at https://github.com/serenity-bdd/serenity-core/blob/master/serenity-rest-assured/src/main/java/net/serenitybdd/rest/utils/RestSpecificationFactory.java to check is this is what you meant with your advices or if there is any other possible improvement that you see ?  Thanks a lot !

**Comment by raphw** [comment]
Looking up a constructor is a rather expensive operation. Better reuse the constructors that you retreive via `getConstructor`. To avoid the reflective call, you can also implement a factory, e.g. by some interface

```java
interface MyFactory {
  RequestSpecificationDecorated make(RequestSpecificationImpl rsi); 
}
```
After creating the classes, you can implement the interface as a factory using `MethodCall` and avoid reflection alltogether.

**Comment by cliviu** [comment]
Thanks ! Reusing the constructors already brought some extra seconds. Unfortunately I was not able to follow you at avoiding the reflective call part. How should I bring the MethodCall in ? How to use My Factory to create new instances ?

**Comment by raphw** [comment]
You can create a type-safe factory like the following:

```java
MyFactory factory = new ByteBuddy()
  .subclass(MyFactory.class)
  .method(isDeclaredBy(MyFactory.class))
  .intercept(MethodCall.construct(requestSpecificationDecoratedClass.getConstructor(RequestSpecificationImpl.class)
           .withArgument(0))
  .make()
  .load(requestSpecificationDecoratedClass.getClassLoader())
  .newInstance();
```

Given this instance, you can avoid reflection alltogehter

**Comment by cliviu** [comment]
Hi, Thanks for your answer. I've done the changes as you suggested but still no big improvement. Are there any performance penalties when invoking methods of instrumented objects ? 
[RestSpecificationFactory.zip](https://github.com/raphw/byte-buddy/files/906750/RestSpecificationFactory.zip)
I attached the file with the changes. 
By making a performance test, the test with the instrumented objects finished in 3 minutes 30 secs in comparison with the test without instrumentation which finished in 1 minute 50 secs.

**Comment by raphw** [comment]
Judging from your code, I doubt that Byte Buddy is the issue here. I assume that it has something to do with the logic you implement in `ResponseSpecificationDecorated::core`. Try stripping your interceptor to a no-op and see if you still observe the issues. Alternatively, maybe you are creating too many objects using this approach and put too much preasure on garbage collection.

**Comment by cliviu** [comment]
I have found some problem somewhere else in the code by profiling. Nevertheless your performance improvements advices were very important and helped me a lot. Thank you very much for you support !  Byte Buddy rocks :-)
