### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Simisage** [raphw/byte-buddy#285]
Hey, I have decent knowledge about Javassist but I moved onto this library and I'm loving it so far, however I have no knowledge about bytecodes ect so I have no experience with ASM.
Anyway is there a way to inject code easily to the start/end/set the body of a method using annotations? For example...

Injecting this at the instance (Before class is loaded)
public class InjectCow extends Cow {

    @Inject(place=Enum.start)
    public static void noise() {
         System.out.println("Rawrr");
    }
}

Into this
public class Cow {

    public static void noise() {
         System.out.println("Moo");
    }
}

**Comment by raphw** [comment]
Yes, have a look at the `AgentBuilder` API which can be used to instrument classes. You can specify this behavior by:

```java
new AgentBuilder.Default()
  .type(named("InjectCow"))
  .transform((builder, type, cl, module) -> builder.method(named("noise")).intercept( ... ))
  .installOn(instrumentation);
```

The above code would create an agent that intercepts your method. Have a look at the `MethodDelegation` API to do so. Alternatively, you can also look into the `Advice` instrumentation.
