### ISSUE TITLE
how to defineMethod body like this?

### ISSUE THREAD

**Issue by juaby** [raphw/byte-buddy#286]
TypeDescription.Generic genericSuperClass =
                TypeDescription.Generic.Builder.parameterizedType(MessageMapper.class, messageClass).build();
        DynamicType.Unloaded<?> dynamicType = null;
        DynamicType.Unloaded.Builder dynamicTypeBuilder = new ByteBuddy()
                .subclass(Object.class)
                .implement(genericSuperClass)
                .name(messageClass.getCanonicalName() + MessageMapper.class.getSimpleName());

        dynamicTypeBuilder.defineMethod("toDomain", messageClass, Visibility.PUBLIC)
                .withParameters(DynamicMessage.class) // how to wirte methodBody?
                ;

        dynamicTypeBuilder.defineMethod("toDynamicMessage", DynamicMessage.class, Visibility.PUBLIC)
                .withParameters(messageClass)  // how to wirte methodBody?
                ;

        Class mapperClass = dynamicType.load(ConverterTool.class.getClassLoader())
                .getLoaded();

    new MessageMapper<Persons>() {

            @Override
            public Persons toDomain(DynamicMessage dynamicMessage) {
                final DynamicMessage msg = dynamicMessage;
                Persons domain = ConverterTool.newInstance(service, msg.getDescriptorForType().getName());
                for (Map.Entry<Descriptors.FieldDescriptor, Object> entry : msg.getAllFields().entrySet()) {
                    String filedName = entry.getKey().getName();
                    Object fieldValue = entry.getValue();
                    if (fieldValue instanceof DynamicMessage) {
                        DynamicMessage subMsg = (DynamicMessage) fieldValue;
                        Person person = ConverterTool.dynamicMessageToDomain(service, subMsg);
                        domain.setPerson(person);
                    } else {
                        if ("id".equals(filedName)) {
                            domain.setId((Integer) fieldValue);
                        } else if ("name".equals(filedName)) {
                            domain.setName((String) fieldValue);
                        }
                    }
                }
                return domain;
            }

            @Override
            public DynamicMessage toDynamicMessage(Persons domain) {
                DynamicMessage.Builder msgBuilder = schema.newMessageBuilder("Persons");
                Descriptors.Descriptor msgDesc = msgBuilder.getDescriptorForType();
                for (Descriptors.FieldDescriptor fieldDesc : msgDesc.getFields()) {
                    Descriptors.FieldDescriptor.Type type = fieldDesc.getType();
                    String filedName = fieldDesc.getName();
                    if (type == Descriptors.FieldDescriptor.Type.MESSAGE) {
                        if ("person".equals(filedName)) {
                            DynamicMessage subMsg = ConverterTool.domainToDynamicMessage(service, domain.getPerson());
                            msgBuilder = msgBuilder.setField(msgDesc.findFieldByName("person"), subMsg);
                        }
                    } else {
                        if ("id".equals(filedName)) {
                            msgBuilder = msgBuilder.setField(msgDesc.findFieldByName("id"), domain.getId());
                        } else if ("name".equals(filedName)) {
                            msgBuilder = msgBuilder.setField(msgDesc.findFieldByName("name"), domain.getName());
                        }
                    }
                }
                return msgBuilder.build();
            }

        }

**Comment by juaby** [comment]
maybe like javasist? CtMethod.make(methodSetDef.toString(), mCtc);
bytebuddy how to use string join method body to load?

**Comment by raphw** [comment]
Byte Buddy uses compiled code to implement a method. Maybe you want to use templates? In this case, have a look at the `Advice` class where you would implement your code. Simply provide a static method annotated with `OnMethodExit` to implement your logic. Otherwise, you can use simple delegation using a `MethodDelegation`.

The [tutorial](http://bytebuddy.net) is a good point to start.
