### ISSUE TITLE
How to instrumentation multi class or method by one agent builder?

### ISSUE THREAD

**Issue by LaughingVzr** [raphw/byte-buddy#288]
I want transform multi class in java instrumentation premain method. But I can't get these class that i want transform this time,so I can't use `ElementMatchers.anyOf()` method to filter target class。

if I want to use advice transform class at instrumentation premain.how to get a right implement perform?

**Comment by raphw** [comment]
You can implement any matcher yourself by implementing the `ElementMatcher` interface. You can also compose any number of matchers by the `or` and `and` methods. You can for example match types by their name and then chain them using `or`: `named("foo.Bar").or(named("qux.Baz"))`.

**Comment by LaughingVzr** [comment]
Thanks!I will try the first way.
