### ISSUE TITLE
Cant get example to work

### ISSUE THREAD

**Issue by Kevin-Codes** [raphw/byte-buddy#291]
For the timer example you did i am using :

public class HelloTimed {
	
	public static void sayHello() {
		System.out.println("Hello");
	}
}

with the java-agent implemented yet its not printing the methods execution time, have i done anything wrong?

**Comment by raphw** [comment]
How does your setup look like? This is too little information to help you. The agent does work, the documentation is unit tested.

**Comment by Kevin-Codes** [comment]
Hopefully this is sufficient, just say if u need more: 
Main class: https://gyazo.com/979b1b1d55d6fca6fe97b39844b89776
Manifest: https://gyazo.com/19e6619d6e2ac8db096556eb54bf46dd
VM Arguments: https://gyazo.com/4621c1b44a5f527842a5dd8740be5144

and its executed as HelloTimed.sayHello();

**Comment by raphw** [comment]
There are a few things wrong with your example. First of all, to activate a Java agent, you need to set the `Premain-Class` attribute. Also, there is no `*Timed` class in your example from what I can tell. You do not need a `main` method in your agent unless it is both the agent and the run application.
