### ISSUE TITLE
java.lang.StackOverflowError , is there a way to avoid recursive calls ?

### ISSUE THREAD

**Issue by basu76** [raphw/byte-buddy#293]
In the advice I am calling a similar method as what is instrumented , this results in a circular call to the advice and finally java.lang.StackOverflowError . Is there any way to prevent it ?

with aspectJ i had used cFlow to prevent this from happening...

```
transform(
              new AgentBuilder.Transformer.ForAdvice()
.include(JettyHandlerAdvice.class.getClassLoader())
.advice(named("**addFilterWithMapping**").and(ElementMatchers.takesArgument(0,named("org.eclipse.jetty.servlet.FilterHolder"))),JettyHandlerAdvice.class.getName())
                        )
```
```
@Advice.OnMethodEnter
    private static void before(@Advice.AllArguments Object[] args,  @Advice.Origin("#m") String methodName, @Advice.This Object thiz) {          
        FilterHolder filterHolder = ((org.eclipse.jetty.servlet.ServletHandler)thiz).**addFilterWithMapping**(XYZFilter.class, "/*", EnumSet.of(javax.servlet.DispatcherType.REQUEST));
    }
```

**Comment by basu76** [comment]
I was able to overcome this by attaching my Filter using advice that is called OnMethodExit.

```
new AgentBuilder.Default()
                    .type(named("org.eclipse.jetty.servlet.ServletHandler"))
                    .transform(
                            new AgentBuilder.Transformer.ForAdvice()
                                    .include(JettyHandlerAdvice.class.getClassLoader())
                                    .advice(**isConstructor()**,JettyHandlerAdvice.class.getName())
                    )
                    .installOn(instrumentation);
```
The issue now is - **java.lang.IllegalStateException: class com.foo.XYZFilter is not a javax.servlet.Filter**

Is it something to do with OSGI ?

**Comment by raphw** [comment]
I assume, the `Filter` class is probably defined by an OSGi bundle in its own class loader and is therefore not compatible accros modules.

As for the circularity, this is something you have to take care of yourself. Byte Buddy basically copy-pastes the code for you. One way to handle this would be to create a flag property that you set before you call a method and check this flag from the called code to avoid the circular segment.

**Comment by basu76** [comment]
Hi Rafael,
Thank you. I figured a way to get around this, though not neat.  This is something related to class loading and I am not able to figure it out.

Get this exception now. The reason I am suspecting this is wrt classloader is - this had worked with aspectj weaver in the past. I am looking at using byte-buddy as weaving is painful with OSGI

java.lang.illegalstateexception com.foo.XYZFilter is not a javax.servlet.Filter

**Comment by raphw** [comment]
This might be a result of not using `AgentBuilder.Transformer.ForAdvice` if you use loaded advice classes where your Java agent is loaded with a different class loader.

What does your complete stack trace look like?

**Comment by basu76** [comment]
I have used this - new AgentBuilder.Transformer.ForAdvice() within transform call. Code pretty much looks like the one in the first port for this thread. I am unable to get full stack trace for this as the other code is just printing this one line. java.lang.IllegalStateException: class com.foo.XYZFilter is not a javax.servlet.Filter. Here is what I have observed, with multiple cases (tried other cases, which does not involve servlet filters).

Here is an observation. The class file is accessible (for eg : javax.servlet.Filter to read and use methods.). If I want to create an instance based of it or want to create an instance of a concrete class, it throws java.lang.NoClassDefFoundError. Once I include the jar file ClassDefFoundError goes away , but the other one surfaces.

In My Advice, I have methods that refer to this same class and print out values - it works perfectly fine, without including the jar file.

Once I want to create an instance of this class, then I get NoClassDefFoundError. What could I do to overcome this ?

thank you

**Comment by raphw** [comment]
What you are experiencing is definetly an issue of class loaders. I do not understand why you require the `Filter` class in your agent, it should be obsolete when using the `Advice` class.

Have you tried to use string constants instead of `JettyHandlerAdvice.class.getClassLoader()`? Maybe you are triggering class loading. Do you have a stack trace of the `NoClassDefFoundError`?
