### ISSUE TITLE
PowerMock and ByteBuddy

### ISSUE THREAD

**Issue by thekingnothing** [raphw/byte-buddy#296]
Hi @raphw, 

First of all, I'd like thank you for such good framework. 

I'm PowerMock maintainer and I'm working on migrating PowerMock to ByteBuddy from Javassist. Main goal of migration it is decrease count of frameworks which are used in PowerMock for class instrumenting. Now they are: CgLib (for EasyMock and Mockito), ByteBuddy (partially for Mockito2) and Javassist (for class instrumenting to enable PowerMock features). Further, I'd like to increase performance and support on-fly JaCoCo class instrumentation.  

I've tried implement some of PowerMock feature with using ByteBuddy and come to conclusion that it will be better to ask you first instead wasting time and searching what possible implement with ByteBuddy and for what I'll need use ASM API or even ASM. 

PowerMock does the following things with a class: 
- Remove final modifier from a class, enum, static methods, methods and inner classes
- Remove final modifier from 
- Make all constructor public 
- Add additional constructor with specific parameter 
- Clear static initialiser body 
- Add body for native methods 
- Set modifier to public for non-system package-private classes    
- Insert calling mock repository for static methods
- Replace calling to fields by call to mock repository 
- Replace constructor call by call to mock repository 
- Replace call to system classes by call to mock repository 
- Check size of method body after modification and replace method body by throwing exception if method body size more than  allowed in java [specification](http://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.3) 

I hope, I didn't forgot anything. Could you please clarified what from list is possible to implement with ByteBuddy API, what with using ByteBuddy custom instrumentation?

**Comment by raphw** [comment]
Hello,
generally, Byte Buddy can do anything that ASM can as it supports the use of visitor wrappers (`ASMVisitorWrapper`). If you transform a class, you can also register a `Transformer` to change modifiers of classes, methods or fields. The removal of modifiers alone without changing a method implementation is however a bit of a blind spot that should be easier.

Adding a constructor is not difficult. You can use `ByteBuddy().redefine(...).defineConstructor(...)` to do so.

Clearing an initializers buddy on the other side is not really supported as Byte Buddy makes sure that all changes are additive. Instead, you can however create another `AsmVisitorWrapper` to simply clear the initializer manually.

Replacing a method's entire implementation with a call to a mock repository is easy by using the dynamic type builder API. Using `rebase`, Byte Buddy automatically retains the original implementation and makes it accessible, too. It is however more difficult to replace calls to methods and field access within a method body which is currently only possible by using ASM. I really want to add this functionality and track it by https://github.com/raphw/byte-buddy/issues/187 - currently I do have my hands full with supporting modules.

Summarizing, Byte Buddy is not yet too powerful when it comes to changing the insides of a method but rather offers ASM to change those parts. This is however a part I prioritize and especially the later mentioned component could really improve this in the future. Also, I need to look into adding an out of the box `AsmVisitorWrapper` for changing modifiers, I will look into this, too and created this ticket: https://github.com/raphw/byte-buddy/issues/299

**Comment by raphw** [comment]
Quick update, I see this lack in functionality and just added means to remove members (such as the static initializer) and to easily change modifiers of all members.

I have also started working on a component that can replace any access to a member with access to another member. This latter component will take a few days or weaks but it will be ready some time in the near future.

**Comment by raphw** [comment]
How does the call to your MockRepository normally look like? How did you retain the original arguments or did you discard them?

**Comment by thekingnothing** [comment]
Thank you for good news. I'll start implement code transformers with using version from master. 

About call to mock repository. Here examples from current Javassist version

Replacing call to constructor 

'''
        String code = "Object instance =" +
                          MockGateway.class.getName() +
                          ".newInstanceCall($type,$args,$sig);" +
                          "if(instance != " + MockGateway.class.getName() + ".PROCEED) {" +
                          "	if(instance instanceof java.lang.reflect.Constructor) {"
                          +
                          "		$_ = ($r) sun.reflect.ReflectionFactory.getReflectionFactory().newConstructorForSerialization($type, java.lang.Object.class.getDeclaredConstructor(null)).newInstance(null);" 

'''
Where 

'$type' - 'java.lang.Class' represent result class after being instrumented
'$arg' - array of actual method/constructor arguments 
'$sig' - array of 'java.lang.Class' method/constructor parameters types. 

These parameters are used to find mock object and mock invocation. 

Also, in case of method return parameter is used to cast mock result to required class. 


[full source](https://github.com/powermock/powermock/blob/powermock-byte-buddy/powermock-core/src/main/java/org/powermock/core/transformers/javassist/support/PowerMockExpressionEditor.java)

**Comment by thekingnothing** [comment]
I've faced with following issue: in old implementation  when a new constructor with specific parameters is added to a class, the constructor is called default constructor of a super class. If default constructor is not accessible, then a new constructor also is added to supper class recursively. 
I don't have idea how to implement this with ByteBuddy. 

I have chain of transformers, where each transformer is responsible for a small part of class instrument: remove modifier, set modifier, add constructor and so on. 

When class loader loads a class, then class loader looks for class description specific to framework (`CtClass` in Javassist case and `TypeDescription`) create wrapper (for ByteBuddy a new `Builder` is created) and send it to chain of transformer. 

Javassist allows to get super class when it's required and modify it. Whole classes hierarchy will be rebuilt later. As I understand, there is no way to do same thing with ByteBuddy. Any thoughts?

**Comment by raphw** [comment]
No, this is not possible with Byte Buddy. You can invoke a method of the super class if it is not yet added by creating an instance of `MethodDescription.Latent`. You would however need to remember that you invoke this method on the super class and add the constructor to the super class once you transform it. Alternatively, you could assume that this constructor exists for any relevant class and also always add it to them.
