### ISSUE TITLE
[Question] Usage for [at]Unused and [at]StubValue

### ISSUE THREAD

**Issue by Wreulicke** [raphw/byte-buddy#297]
This issue is only a question.
Could you help me?

* Usage for `Advice.Unused` and Advice.StubValue

Why these annotation is introduced?
What each annotation is aim to?
Could you show examples for me? (if possible)

If this issue annoy to you, reject this issue, please.

**Comment by raphw** [comment]
The `@StubValue` annotation value can be used for example to override a return value. For primitive values, like `int`, it is not legal to assign `null` but only `0`. By using this value, a null pointer exception is avoided.

The `@Unused` value can be used to annotate a parameter that is not required for an advice method but which cannot be removed to retain binary compatibility of a program.

**Comment by Wreulicke** [comment]
Thanks, @raphw :)
