### ISSUE TITLE
ArgumentType ambiguity resolver merges wrongly in case of int and long parameters

### ISSUE THREAD

**Issue by roeltje25** [raphw/byte-buddy#298]
I have an interface which I am wrapping in bytebuddy. The object of this interface is embedded as a delegate and I transfer all calls to the delegate using MethodDelegation.toField(). So far so good. 
The interface has two calls however as follows:
bookCorrection(int, int, Object)
bookCorrection(long, long, Object)
The problem now is that the ArgumentTypeResolver returns that a call to bookCorrection(int,int,Object cannot be resolved. 

Looking at the code it seems that merging the resolution in ArgumentTypeResolver.resolve at line 107 is wrongly assuming that a resolution of RIGHT which is merged with UNKNOWN is AMBIGUOUS, which I reckon should instead be: RIGHT merged with UNKNOWN is  RIGHT.

Let me explain. you see that the two options have their first two paramteres different. the result is resolved to option RIGHT when I do debug stepping. However, the third argument is the same and yields UNKNOWN on line ArgumentTypeResolver:108 in resolveRivalBinding. The merge yields AMBIGUOUS, which is not what I expect.

Am I misunderstanding this?

**Comment by raphw** [comment]
You are right, this is a bug. A merge of `RIGHT` with `UNKNOWN` should yield `RIGHT`. I will fix this in the upcoming release.

**Comment by roeltje25** [comment]
great. glad to have been of help

**Comment by raphw** [comment]
Fixed on master.
