### ISSUE TITLE
Add AsmVisitorWrapper for transforming modifiers

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#299]
In order to change modifiers without changing a method implementation and without matching a field, Byte Buddy should add an `AsmVisitorWrapper` and corresponding field and method visitors.

**Comment by raphw** [comment]
Added on master.

**Comment by thekingnothing** [comment]
I think, better to add one more set of methods to `ModifierAdjustment` to enable working with constructor. Methods `withMethodModifiers(...)` ignore constructor, because matchers compare pattern with actual name. I found the following ways to change constructor modifier, when I don't have loaded class: 
- use `ElementMatchers.any()`
- filter method `typeDefinitions().getDeclaredMethods()` to find constructor by internal name and use `ElementMatchers.any()`
- implement custom `ClassVisitor` 

```
    private static class ConstructorModifiersClassVisitor extends ClassVisitor {
        
        private final Visibility visibility;
        
        private ConstructorModifiersClassVisitor(final ClassVisitor classVisitor, final Visibility visibility) {
            super(Opcodes.ASM5, classVisitor);
            this.visibility = visibility;
        }
        
        @Override
        public MethodVisitor visitMethod(int modifiers, String internalName, String descriptor, String signature, String[] exception) {
            if (MethodDescription.CONSTRUCTOR_INTERNAL_NAME.equals(internalName)) {
                modifiers = (modifiers & ~visibility.getRange()) | visibility.getMask();
            }
            return super.visitMethod(modifiers, internalName, descriptor, signature, exception);
        }
    }
```

**Comment by raphw** [comment]
Did you look at the `isConstructor()` matcher for doing this? I will look into improving this!

**Comment by thekingnothing** [comment]
Nope, I missed this matcher. I'll use it.
On 1 May 2017, at 22:16, Rafael Winterhalter <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you look at the isConstructor() matcher for doing this? I will look into improving this!

**Comment by raphw** [comment]
I decided to slightly refine the API. The naming `method` is not really intuitive when working with Java and not thinking of constructors as methods.

**Comment by thekingnothing** [comment]
I was looking for such kind of matcher, somehow I missed it. But I agree that, for Java is more conventional have separate methods in API for constructors and  methods. 

I'd like to suggest one more changes in API . As I see, now it possible only to set a modifiers for method/field/type. Sometime it's required to modify existed modifier. What do you think about this?

**Comment by raphw** [comment]
What do you mean by the latter? The component is chainable and you can set all three properties to change the modifiers of all components by chaining them together.

**Comment by thekingnothing** [comment]
I mean that if for example I'd like to remove `final` modifier from all fields then I have to write something like this
```
new ModifierAdjustment()
    .withFieldModifiers(isTransient(), FieldManifestation.TRANSIENT)
    .withFieldModifiers(isVolatile(), FieldManifestation.VOLATILE);
```

Maybe, it will be better to write something like this 

```
   new ModifierAdjustment(). withFieldModifiers(new Resolver(){
         public int resolve(int modifiers) {
               return modifiers ^ FieldManifestation.FINAL.getMask();
         }
   });
```

**Comment by raphw** [comment]
No, Byte Buddy automatically merges the modifiers. Only the spectrum of the specified modifier will be changed. To remove final field modifiers, you would:

```java
new ModifierAdjustment().withFieldModifiers(isFinal(), FieldManifestation.PLAIN)
```

**Comment by thekingnothing** [comment]
But if this case all other modifier will be removed also and for example this test fails 

```
@Test
    public void should_remove_only_final_modifier_but_keep_transient() {
    
        Class<? extends SupportClasses> aClass = new ByteBuddy()
                                                     .redefine(SupportClasses.class)
                                                     .visit(new ModifierAdjustment().withFieldModifiers(ElementMatchers.<InDefinedShape>isFinal(), FieldManifestation.PLAIN))
                                                     .make()
                                                     .load(ClassLoadingStrategy.BOOTSTRAP_LOADER, Default.WRAPPER)
                                                     .getLoaded();
    
        Field finalTransientStaticField = WhiteboxImpl.getField(aClass, "finalTransientField");
    
        assertThat(Modifier.isTransient(finalTransientStaticField.getModifiers())).isTrue();
    
    }
```

```

 public static class SupportClasses {  
        private static final Object finalStaticField = new Object();
        private transient final Object finalTransientField = new Object();
  }

```

**Comment by raphw** [comment]
That is actually a bug in Byte Buddy where the `transient` modifier is wrongfully added to the `final`/`volatile` family. Normally, a `ModifierContributor` should describe what modifiers it conflicts with (a final volatile field is for example forbidden).

**Comment by thekingnothing** [comment]
Are you going to fix it in near future or better implement workaround on my side?

On 3 May 2017, at 12:53, Rafael Winterhalter <notifications@github.com<mailto:notifications@github.com>> wrote:


That is actually a bug in Byte Buddy where the transient modifier is wrongfully added to the final/volatile family. Normally, a ModifierContributor should describe what modifiers it conflicts with (a final volatile field is for example forbidden).

**Comment by raphw** [comment]
I will push it onto master tonight.

**Comment by thekingnothing** [comment]
> I will push it onto master tonight. I will release a new version once I implemented the mentioned support for MemberSubstitution.

Thank you for such quick fix! For me it's okay right now work with master.

> I did all other changes but I am still need to extend the API of the MemberSubstitution to allow replacing method calls with method consuming different arguments. I am still uncertain if I should go for an explicit API such as .replaceBy(method).replacedMethod().allArgumentsAsArray().this() or a target-site API where all parameters are annotated to indicate their value. Any thoughts?

Sorry, I misses it before. My thoughts that, for library developers, like me, better approach with `allArgumentsAsArray()` and have access to an array of arguments and method parameter types. 
But for other developers, preferable way to have target-site API where all parameters are annotated like in Spring/Camel and other popular libraries.  

By the way, I have question about bridge methods and handling the following case in ByteBuddy. If in Javaasist I instrument `SubClass` and insert code at the beginning of `SubClass.sayYes(SomeInterface s)` then variable `$sign` contains `[Object.class]`. As result, mocking with Mockito matchers like `when(subClass.sayYes(any(SomeInterface.class))).thenCallRealMethod();` is failed, because PowerMock cannot find suitable method with required signature.  Can ByteBuddy provide correct parameter type in this case? May it possible to provide link to original method? 

```

public class SuperClass<T> {
    public String sayYes(T o){
        return "Yes!";
    }

    public Number calculate(Integer i){
        return i + 10;
    }
}
public class SubClass extends SuperClass<SomeInterface>{

    @Override
    public String sayYes(SomeInterface s) {
        return "Yes, " + s;
    }

    @Override
    public Integer calculate(Integer i) {
        return i + 10;
    }
}

```

**Comment by raphw** [comment]
Byte Buddy handles bridge methods transparently. If you create a generic class [as described in this example](http://stackoverflow.com/questions/43747013/how-to-dynamically-generate-a-java-subclass-with-generics/43752662#43752662), any overridden generic method is automatically promoted to its new erasure with the required bridge methods being added.
