### ISSUE TITLE
javadoc for Pipe is not valid

### ISSUE THREAD

**Issue by bokken** [raphw/byte-buddy#302]
In the class javadoc for Pipe, it gives instructions on how to register a Pipe.Binder with a MethodDelegation. The documentation shows how this worked prior to the 1.6.0 release.

http://bytebuddy.net/javadoc/1.6.9/net/bytebuddy/implementation/bind/annotation/Pipe.html

**Comment by raphw** [comment]
Thanks, will fix in the next release!

**Comment by raphw** [comment]
Fixed on master.
