### ISSUE TITLE
LambdaInstrumentationStrategy can cause JVM errors when converting a Method Reference to a Runnable

### ISSUE THREAD

**Issue by paulconnell** [raphw/byte-buddy#303]
`class C {
        void foo() {

        }

        Object bar() {
            return null;
        }

        public <T> void callable(Callable<T> callable) throws Exception {
            callable.call();
        }

        public void runnable(Runnable runnable) {
            runnable.run();
        }
    }

    @Test
    public void foobar() throws Exception {
        C c = new C();
        c.runnable(c::foo);
        c.callable(c::bar);
        c.runnable(c::bar); //this line
    }`

The commented line causes an error if ByteBuddy Agent has been configured with Lambda instrumentation.
    [junit] call site initialization exception
    [junit] java.lang.BootstrapMethodError: call site initialization exception
    [junit] 	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
    [junit] 	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
    [junit] 	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
...
    [junit] Caused by: java.lang.VerifyError: Method expects a return value
...
Reason:
    [junit]     Type 'java/lang/Object' (current frame, stack[0]) is not assignable to top (from method signature)
    [junit]   Current Frame:
    [junit]     bci: @7
    [junit]     flags: { }
    [junit]     locals: { '$$Lambda$ByteBuddy$6' }
    [junit]     stack: { 'java/lang/Object' }
    [junit]   Bytecode:
    [junit]     0x0000000: 2ab4 000c b600 12b0                    
    [junit] 
    [junit] 	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
    [junit] 	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java)
    [junit] 	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)

Without ByteBuddy's lambda instrumentation, the code works.

Thanks

**Comment by raphw** [comment]
The lambda factory does not currently check for the return type of the lambda but of the invoked method when rendering the return opcode. This is an easy fix, thanks for reporting!

**Comment by raphw** [comment]
Fixed on master.
