### ISSUE TITLE
Hot to change the argument value

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#305]
Hi @raphw , I use a method/constructor delegate in my project like this:
```java
newClassBuilder.method(not(isStatic()).and(instanceMethodsInterceptPoint.getMethodsMatcher())).intercept(MethodDelegation.to(classMethodInterceptor));
```

In classMethodInterceptor
```java
    /**
     * Intercept the target instance method.
     *
     * @param obj             target class instance.
     * @param allArguments    all method arguments
     * @param method          method description.
     * @param zuper           the origin call ref.
     * @param instanceContext the added field of enhanced class.
     * @return the return value of target instance method.
     * @throws Exception only throw exception because of zuper.call() or unexpected exception in sky-walking ( This is a
     *                   bug, if anything triggers this condition ).
     */
    @RuntimeType
    public Object intercept(@This Object obj, @AllArguments Object[] allArguments, @Origin Method method,
                            @SuperCall Callable<?> zuper,
                            @FieldValue(ClassEnhancePluginDefine.CONTEXT_ATTR_NAME) EnhancedClassInstanceContext instanceContext) throws Throwable {
```

In this method, I want to change the arguments values. For now, I have tried to assign new value, e.g. ` allArguments[0] =  allArguments[0] + "(be intercepted)";`, but seem not work.

Can you give me some solution?

**Comment by raphw** [comment]
This is not possible by simple assignment. Instead, you need to use the `@Morph` annotation instead of `@SuperCall` where you can explictly supply the arguments. In this case, changing the array value and then supplying the array to `@Morph` would work. Note that you need to explicitly install the `Morph.Binder` for the annotation to be available.

Alternatively, have a look at the `Advice` class where this is even easier as the code gets inlined where a simple assignment is sufficient.

**Comment by wu-sheng** [comment]
> Note that you need to explicitly install the Morph.Binder for the annotation to be available

How to install? I am hardly to find any document about how to useing `@Morph`. Just find a description before.

> supplying the array to @Morph would work.

How to supply?

`@Morph` annotation is also for a Callable argument? like `@SuperCall Callable<?> zuper`?

**Comment by wu-sheng** [comment]
Here is my interceptor:
```java
    @RuntimeType
    public Object intercept(@This Object obj, @AllArguments Object[] allArguments, @Origin Method method,
                            @Morph(defaultMethod = true) Callable<?> zuper
                            ) throws Throwable {
        System.out.println("entering intercept");
        allArguments[0] =  allArguments[0] + "(be intercepted)";
        return zuper.call();
    }
```

**Comment by wu-sheng** [comment]
It doesn't work. This method doesn't invoke.

**Comment by raphw** [comment]
You need to set something like `MethodDelegation.withCustomConfiguration().with(Morph.Binder.install(YourType.class))`.

**Comment by wu-sheng** [comment]
Thanks. It works now :) 

BTW, How can I contact you in private? I am discussing with my team, about building a commercial APM, different with sky-walking open source version, based on byte-buddy.  But maybe we need some your support in paid time. 

It this feasibility? Be a technical supporter in Java codes generation and manipulation field, develop some features for our APM?

**Comment by wu-sheng** [comment]
Thanks. I just delete the prev comment. : ) Get in touch.

**Comment by wu-sheng** [comment]
This works when facing methods. But today I run a test for change  arguments of constructor, it failed. How should I interceptor constructor and change the arguments

* The Builder
```java
builder = builder.constructor(ElementMatchers.<MethodDescription>any()).intercept(
                MethodDelegation.withDefaultConfiguration().withBinders(
                        Morph.Binder.install(Morpher.class),
                        FieldProxy.Binder.install(FieldGetter.class, FieldSetter.class)
                )
                        .to(new PrintClassConstructorInterceptor()));
```

* The `PrintClassConstructorInterceptor`
```java
public class PrintClassConstructorInterceptor {
    @RuntimeType
    public void intercept(@This Object obj,
                          @FieldProxy("dynamicField") FieldSetter accessor,
                          @AllArguments Object[] allArguments,
                          @Morph Morpher morpher) {
        accessor.setValue("new field with value");
        morpher.invoke(allArguments);
    }
}
```

* The `Morph`
```java
public interface Morpher {
    Object invoke(Object[] args);
}
```

**Comment by wu-sheng** [comment]
Is this because `super()` must invoke first? Is there any chances to do such things?

My error is:
```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/huawei/test/simple/print/PrintClass.<init>()V @9: invokespecial
  Reason:
    Type uninitializedThis (current frame, stack[4]) is not assignable to 'com/huawei/test/simple/print/PrintClass'
  Current Frame:
    bci: @9
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { 'com/huawei/devcloud/tools/disgnosis/plugins/test/printclass/PrintClassConstructorInterceptor', uninitializedThis, uninitialized 4, uninitialized 4, uninitializedThis }
  Bytecode:
    0x0000000: b200 2a2a bb00 2c59 2ab7 002f 03bd 0004
    0x0000010: bb00 3159 2ab7 0032 b600 38b1          

	at com.huawei.test.simple.print.Main.main(Main.java:8)

```

**Comment by raphw** [comment]
Constructors in Java are a bit particular, they must hard-code an invocation of another constructor inside of the method which makes it obligatory to use `SuperMethodCall` either before or after the delegation. If you use the delegation before the call, you cannot access the `this` instance which is considered uninitialized at that point what leads to the above exception.

**Comment by wu-sheng** [comment]
I used `SuperMethodCall.INSTANCE` before, but in this scenario, I want to change the arguments rather than just access it.

How can I do this?

**Comment by raphw** [comment]
The easiest way would probably be using `Advice` where the code gets inlined around the original call.

**Comment by wu-sheng** [comment]
Can you show me some codes or  a gist to do so?

**Comment by wu-sheng** [comment]
I just found the advice on method, not constructor. And it didn't change the arguments.
https://github.com/raphw/byte-buddy/blob/b521c38ddfb9b418f7cc1b691c707403569f7f23/byte-buddy-dep/src/test/java/net/bytebuddy/asm/AdviceTest.java

**Comment by wu-sheng** [comment]
I wrote codes like this:
```java
        builder.visit(Advice.to(AdviceInterceptor.class).on(ElementMatchers.<MethodDescription>any()).readerFlags(ClassReader.SKIP_DEBUG));
```

And trigger a compile error, `jdk.internal.org.objectweb.asm` not found in maven, why?
```
[ERROR] /D:/IdeaProjects/AppDiagnosis/app-diagnosis-agent/src/main/java/com/huawei/devcloud/tools/disgnosis/plugins/test/printclass/PrintClassWeaver.java:[4,38] 程序包jdk.internal.org.objectweb.asm不存在
[ERROR] /D:/IdeaProjects/AppDiagnosis/app-diagnosis-agent/src/main/java/com/huawei/devcloud/tools/disgnosis/plugins/test/printclass/PrintClassWeaver.java:[22,115] 找不到符号
```

**Comment by raphw** [comment]
You imported the wrong namespace, the JDK bundles ASM itself as an internal API.
