### ISSUE TITLE
How to match a class with certain annotation

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#306]
Right now, I use `public class SimpleMatcher<T extends NamedElement> implements ElementMatcher.Junction<T>` to match class with certain class name.

But I need to match a group of classes with certain runtime annotation. What should I do?

These are in my agent premain:
```Java
  new AgentBuilder.Default().type(new SimpleMatcher().and(not(isInterface()))).transform(new AgentBuilder.Transformer() {
            public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
```

**Comment by wu-sheng** [comment]
And the annotation is not part of agent codes. How should I declear it? You teach me to implement an `ElementMatcher` for similar scenario in parameter type:

```java
public class ArgumentTypeNameMatch implements ElementMatcher<MethodDescription> {
    @Override
    public boolean matches(MethodDescription target) {
        ParameterList<?> parameters = target.getParameters();
        if (parameters.size() > index) {
            return parameters.get(index).getType().asErasure().getName().equals(argumentTypeName);
        }

        return false;
    }
```

**Comment by raphw** [comment]
You can use the `isAnnotatedBy` matcher. If you want to check all classes down the hierarchy, you can nest a `hasSuperType` and the previous matcher.
