### ISSUE TITLE
bytecode manipulation api is still not expressive enough

### ISSUE THREAD

**Issue by testn** [raphw/byte-buddy#311]
It would be nice if we can generate some bytecode with something other than field access, method call etc. Good examples are try-catch block, if else, switch, for-loop, etc. 

Currently, if we need to do those, we would need to use MethodVisitor API directly. I was thinking if we have something like expression tree, it would be awesome.

**Comment by raphw** [comment]
It would be but this sort of functionality is not trivial to implement. There is no better way of creating custom byte code than ASM for those who need it. I do not plan to implement a feature like you suggest in the near future.

That said, by working with `StackManipulation`s and `ByteCodeAppender`s you can already encapsulate blocks of code. Would this be a way to go?
