### ISSUE TITLE
Is there any way to intercept a toString method and get all field's value and name?

### ISSUE THREAD

**Issue by Aleishus** [raphw/byte-buddy#313]
For example, I want to override toString method and use some filter to handle the fields . If 
 I use the  `@FieldValue` annotation ，I must know the field's name , actually I want to get all the filed name and value like a Map result. Is there any way ?

**Comment by raphw** [comment]
You would need to implement a custom Binder and register it with the interceptor. You can chain together a constructor call to create a map, then you would iterate over the fields, read the values and names and put those into the map.
