### ISSUE TITLE
Custom BindingResolver is never called

### ISSUE THREAD

**Issue by qdolan** [raphw/byte-buddy#319]
I am attempting to test the BindingResolver functionality added recently to MethodDelegation (1.7.2-SNAPSHOT) but it doesn't get called.

My method delegate is constructed like this:

```java
MethodDelegation toProxyDelegate = MethodDelegation
	.withDefaultConfiguration()
	.withBindingResolver(MatchingBindingResolver.INSTANCE)
	.to(ProxyDelegate.class);
```

Using a debugger I can see that my resolve() method is not called, instead BindingResolver.Default.resolve(..) is called.

On initial inspection it appears that the call to MethodDelegation.WithCustomProperties.to(Class<?> type) to obtain the MethodDelegation instance calls the protected MethodDelegation constructor and discards the currently set BindingResolver.

**Comment by raphw** [comment]
You are right, I did not properly set the field. The few times I do not write a test, I get it wrong, sorry for that.

**Comment by qdolan** [comment]
No problem.. saves me having to wait for another release before I can push my changes that use it.

**Comment by raphw** [comment]
Fixed on master.
