### ISSUE TITLE
Can't instantiate type when a parent method uses a non public type in signature

### ISSUE THREAD

**Issue by bric3** [raphw/byte-buddy#32]
This is a followup of mockito issues https://github.com/mockito/mockito/issues/233 and PR https://github.com/mockito/mockito/issues/234

The fix 6f223d93ee57b199abf0e7abaf4837df6d041f41 here don't handle _compilation_, so bytecode is can be generated, but cannot be instantiated (`IllegalAccessError`).

The issue is probably there `MethodRegistry.Default.Compiled#getInstrumentedMethods` does not check if methods are visible, like other components of 6f223d93ee57b199abf0e7abaf4837df6d041f41.

I'm guessing that the implementation should be something like : 

```java
@Override
public MethodList getInstrumentedMethods() {
    return new MethodList.Explicit(new ArrayList<MethodDescription>(implementations.keySet())).filter(not(isTypeInitializer()).and(isVisibleTo(instrumentedType)));
}
```

**Comment by raphw** [comment]
Hi, I already identified the actual issue. Refactoring gone wrong. I fixed the problem and just released version 0.6.10 where the visibility is appropriately resolved.

**Comment by bric3** [comment]
ok, great :)

**Comment by bric3** [comment]
It indeed fixes the issue :)

**Comment by raphw** [comment]
Great! This time I actually cloned Mockito and tested it and then reproduced the problem in my tests. I think I knew the issue and did not test it properly. Moved to fast. 

I really hope there will not be too many of these corner cases coming up to the surface. Mockito is the first large-scale user of Byte Buddy, there will probably be one or two things I have not thought off.

**Comment by bric3** [comment]
No problem this is no small piece of development you crafted.

I'm excited by possibilities now :)
Just need time to work on it.

Also I think there's another issue with ByteBuddy or the way Mockito uses ByteBuddy.
The test in this commit hightlight an issue some are facing : https://github.com/bric3/mockito/commit/7f2beb8d0e4819f8dfa6a0fedb0236cec8f4b168

I didn't have time to dive in here yet, this probably have to do with a feature add in mockito lately that can generated partial mocks, so mocked types may be instantiated with the constructor instead of objenesis. So not sure it's a bytebuddy issue.

**Comment by raphw** [comment]
When you mock a class, you delegate all invocations to an instance field:

```java
.method(any()).intercept(toInstanceField(MockMethodInterceptor.class, "mockitoInterceptor")
                                                          .filter(isDeclaredBy(MockMethodInterceptor.class)))
```

If the field is not yet set (during a constructor call), a null pointer exception is thrown.

To avoid this, you can for example delegate to a static interceptor which then checks if the interceptor is already set and only delegates a method if the interceptor is already set: https://gist.github.com/raphw/8789f5ef08240008efc8

**Comment by bric3** [comment]
Yeah that's somehow what I suspected. Thanks for the tip.
