### ISSUE TITLE
How to match a classes with  certain interfaces

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#322]
In sky-walking agent, I want to match classes with certain interfaces or super classes, how to build a ElementMatcher. I have the interface names (String[])
```java
new AgentBuilder.Default().type()
```

I have known when I face the annotation, I can do this:
```java
isAnnotatedWith(named(annotationName))
```

But for interfaces, I just found `isSubTypeOf` method, but it need **TypeDescription** as a parameter,  I didn't know how to build it by the given string.

**Comment by wu-sheng** [comment]
Here is I did for annotation match: 
https://github.com/wu-sheng/sky-walking/blob/feature/high-performance-agent/apm-sniffer/apm-agent-core/src/main/java/org/skywalking/apm/agent/core/plugin/match/AnnotationMatch.java

**Comment by wu-sheng** [comment]
I want to finish the interface match like this:
https://github.com/wu-sheng/sky-walking/blob/feature/high-performance-agent/apm-sniffer/apm-agent-core/src/main/java/org/skywalking/apm/agent/core/plugin/match/HierarchyMatch.java

No implementation yet, because can't build **TypeDescription**, :(

**Comment by raphw** [comment]
Have a look at ElementMatchrs::hasSuperType.

**Comment by wu-sheng** [comment]
@raphw Great to have this. I will test this later.

**Comment by wu-sheng** [comment]
Do I have a way to match a class when the class has a method with certain annotation?

**Comment by raphw** [comment]
hasSuperType(declaresMethod(whereAny(declaresAnnotation(...))))

**Comment by wu-sheng** [comment]
How powerful....

**Comment by raphw** [comment]
Itsa rather expensive matching, though. Ideally, prepend a cheaper criteria like a name suffix.

**Comment by wu-sheng** [comment]
How name suffix match? example?

**Comment by raphw** [comment]
For example: nameStartsWith("foo.").and(...)

**Comment by wu-sheng** [comment]
Is name suffix or regax match popular?
