### ISSUE TITLE
Method interception not working on some conditions

### ISSUE THREAD

**Issue by lucaseverini** [raphw/byte-buddy#323]
Hello,

First of all my compliments for this great software and the fact that is freely available.
I don't consider myself a java expert but I'm writing software, mostly on Apple platform, for almost thirty years, from c/c++ going down (toward the bare metal...).

What I'm trying to do is to intercept the execution of some class methods so I can make them execute my code before continuing the normal execution. A so-called head-patch.
I can't control when/how an object of the intercepted class gets instantiated.

My problem is that while the intercept works fine here:
.method(named("method1")).intercept(FixedValue.value("Method1 intercepted !!"))

it doesn't work here:
.method(named("method2")).intercept(MethodDelegation.to(interceptor))
.method(named("method3")).intercept(MethodDelegation.to(interceptor))

It doesn't return any error/exception.
It just does nothing. It doesn't even execute the original code.
Something is happening (those methods get modified), but not what I'd like...

Running the example the output is:
Method1 intercepted !!
Interceptor@16f7c8c1
Interceptor@16f7c8c1

But I would expect something like:
Method1 intercepted !!
Method intercepted !!
-XXXX-
Method intercepted !!
-XXXX-

Is it my fault (probably) or is some issue in Byte Buddy?

Below you can find the full code.
I'd like to avoid to use agents or change the loading of code in any way.
Thank you so much in advance for any comment/suggestion!

Luca Severini

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.ClassFileLocator;
import net.bytebuddy.implementation.FixedValue;
import net.bytebuddy.implementation.MethodDelegation;
import static net.bytebuddy.matcher.ElementMatchers.named;
import net.bytebuddy.pool.TypePool;

// --------------------------------------------------------------------------------
public class MainClass 
{
	public static void main(String[] args)
	{		
		// Patch the class SomeClass
		doPatch();

		// Instantiate the patched class
		SomeClass c = new SomeClass();
				
		// Call the methods of patched class...
		System.out.println(c.method1());		
		System.out.println(c.method2());		
		System.out.println(c.method3(null));
	}
	
	public static void doPatch()
	{
        String className = "SomeClass";
        TypePool typePool = TypePool.Default.ofClassPath();
        TypeDescription typeDescription = typePool.describe(className).resolve();
        ClassFileLocator locator = ClassFileLocator.ForClassLoader.ofClassPath();
		Interceptor interceptor = new Interceptor();
				
		new ByteBuddy()
			.redefine(typeDescription, locator)
			.method(named("method1")).intercept(FixedValue.value("Method1 intercepted !!"))
			.method(named("method2")).intercept(MethodDelegation.to(interceptor))
			.method(named("method3")).intercept(MethodDelegation.to(interceptor))
			.make()
			.load(ClassLoader.getSystemClassLoader());
	}

}

// Patched class
// --------------------------------------------------------------------------------
public class SomeClass 
{
    public String method3(Object argument) 
	{
        System.out.println("Method3 called");
				
		return "-Method3-";
    }

	public String method2() 
	{
        System.out.println("Method2 called");
		
		return "-Method2-";
    }

    public String method1() 
	{
        System.out.println("Method1 called");
		
		return "-Method1-";
    }
}

// Interceptor class
// --------------------------------------------------------------------------------
import java.lang.reflect.Method;
import net.bytebuddy.asm.Advice.AllArguments;
import net.bytebuddy.asm.Advice.Origin;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;

public class Interceptor 
{
	@RuntimeType
	public Object intercept(@AllArguments Object[] args, @Origin Method method) throws Exception 
	{
		System.out.println("Method intercepted");

		return "-XXXX-";
	}
}

**Comment by raphw** [comment]
Seems like you imported the wrong annotation. The Advice class offers a similar mechanism for delegation but with code inlining. Those annotations are not understood by the delegation mechanism.

As a result, your interceptor method cannot be mapped and the toString method is choosen instead. This only works as all your methods return a string.

If your interceptor is stateless, I recommend you using a static method with class delegation. If you only want to prepend code, chain the delegation with a super method call using andThen. This way, your delegator can return void without runtime type adoption.

**Comment by raphw** [comment]
I am closing this issue, please reopen it if you have further questions.
