### ISSUE TITLE
Byte Buddy Maven Plugin: to add an ability to suppress failures during transformation.

### ISSUE THREAD

**Issue by skapral** [raphw/byte-buddy#328]
Right now, Byte Buddy Maven plugin executes a set of `net.bytebuddy.build.Plugin`s on the project's code, class-by-class. If some plugin is failed (throws an exception), then it terminates immediately.

I propose an enhancement to the plugin - to have some boolean parameter like `suppressTransformationFailures`, defaulted to `false`. When it is set up to `true`, maven plugin behavior is changed in the following way:

1. When some plugin fails on some class, instead of failing the build immediately, the exception is logged in Maven logs and transformation goes on for the next class in queue.
2. When all the classes pass the transformation process, the build is failed if there were some failures logged.

The purpose: such mode gives the opportunity to hit and collect all the transformation issues in project at one build iteration. Currently, it only detects the first one and fails, which is rather inconvenient.

**Comment by raphw** [comment]
Good idea, I already added the property.

**Comment by skapral** [comment]
Thank you 👍

**Comment by raphw** [comment]
Released as 1.7.2.
