### ISSUE TITLE
I am translating the tutorial into Chinese. Could you add the link to website?

### ISSUE THREAD

**Issue by diguage** [raphw/byte-buddy#329]
I am translating the tutorial into Chinese. 

Could you add the link to website?

[Byte Buddy 教程 http://notes.diguage.com/byte-buddy-tutorial/](http://notes.diguage.com/byte-buddy-tutorial/)

**Comment by raphw** [comment]
Wow, this is great, thanks for your efforts. I will of course add a link, give me a few days!

**Comment by raphw** [comment]
I added links to the readme and webpage, thanks again!

**Comment by diguage** [comment]
@raphw I used the HTTPS for the Chinese page, so the home page was changed to <https://notes.diguage.com/byte-buddy-tutorial/>. Please update the url.

**Comment by raphw** [comment]
I updated the link, thanks!
