### ISSUE TITLE
Hooking of instances and instrumentation of code alteration in a more readable way

### ISSUE THREAD

**Issue by Dynarev** [raphw/byte-buddy#330]
The inferior in every other way code generator I have used for years does this. It did it building on top of ASM so its ready to be done here. i know  a lot of work, no rush, this is more a suggestion/feature need than an issue. Thanks
If I get some free time I may look into trying to help put some code in for this. I am not a top of the line coder though. I feel a need to contribute to open source however.
I.E. Enhancement.

**Comment by raphw** [comment]
I am not sure what you mean by that. Could you explain this with an example?

**Comment by Dynarev** [comment]
Well I started to try to just give you an example but it is not a long page you can get a full understanding of the part of javassist i use more than anything else right here.

https://jboss-javassist.github.io/javassist/tutorial/tutorial2.html#runtime

It tells you everything you can do with the expression editors and the class pool stuff. Which is to say pretty much whatever  you want. In fact it is so powerful you have to be careful to use it the right way lol. Cause it will likely do its thing the wrong way and  you won't know till your application throws and error mid operation. Once you understand it though it is so dreamy. Over the last 2 years we have further hooked into it for our purposes and added constants and interfaces directly to it so that we can do most things with just a few lines.  I feel like if bytebuddy had this, everything else would just be obsolete.

**Comment by Dynarev** [comment]
Well other than that one other thing I mentioned. Controlling class loaders myself and loading the classes when I wan't to as the application launches.

**Comment by Dynarev** [comment]
If  you would like to glance at our implementation for a runtime loading system using javassist. It is not on my repository. I am a contributor and work more with the creation of mods for it, and helping other mods learn to use it. For some reason the branch leader keeps forgetting files though so its really best to grab his release and decompile it (procyon does nice) https://github.com/ago1024/WurmServerModLauncherhttps:/
