### ISSUE TITLE
Byte Buddy Maven Plugin "continueOnFailedPlugin" option: to fail if there were failures in transformations

### ISSUE THREAD

**Issue by skapral** [raphw/byte-buddy#331]
The issue is created from https://github.com/raphw/byte-buddy/issues/328. Original issue states that:

> When all the classes pass the transformation process, the build is failed if there were some failures logged.

In fact the plugin is just always pass, despite the fact that some transformations are not done properly. The idea of the original issue was to give user the overview of all issues happened during transformation (not just one), but the fact remains - the build with transformation errors cannot be considered as successful.

**Comment by raphw** [comment]
You are right, I fixed this on master.

**Comment by skapral** [comment]
Thank you.
