### ISSUE TITLE
Invalid MAXLOCALS size

### ISSUE THREAD

**Issue by geoand** [raphw/byte-buddy#336]
Hi,

I have been looking into ByteBuddy lately and so far I have been really enjoying it!

While writing some sample code, I came across the following issue, that I will try to describe using some simple classes/interfaces with no real value.

Say we have interface `Setter` that we would like to implement dynamically. The interface is defined as follows:

    public interface Setter {
        void set(Object o1, int ind, int val) throws IOException;
    }

Furthermore, we have a class named `Node`, that is defined like so:

    public class Node {
        public int value;
    }

For the sake of testing, let's say we want to implement the `set` method of `Setter` like so:

    public void set(Object o1, int ind, int val) throws IOException {
        Node n = (Node)o1;
        n.value=val;
    }

Had I compiled this hand-written method with javac, I would get the following byte-code for the method implementation:
```
public set(Ljava/lang/Object;II)V throws java/io/IOException
  ALOAD 1
  CHECKCAST test/ByteBuddyTest$Node
  ASTORE 4
  ALOAD 4
  ILOAD 3
  PUTFIELD test/ByteBuddyTest$Node.value : I
  RETURN
  MAXSTACK = 2
  MAXLOCALS = 5
```

If I wanted to use ByteBuddy to generate a class that implements the `set` method in the manner described above, I would write the following code:

    public enum SetImplementation implements Implementation {
        INSTANCE;

        @Override
        public InstrumentedType prepare(InstrumentedType instrumentedType) {
            return instrumentedType;
        }

        @Override
        public ByteCodeAppender appender(Target implementationTarget) {
            return SetAppender.INSTANCE;
        }
    }

    public enum SetAppender implements ByteCodeAppender {
        INSTANCE;

        @Override
        public Size apply(MethodVisitor methodVisitor,
                          Implementation.Context implementationContext,
                          MethodDescription instrumentedMethod) {

            final TypeDescription.ForLoadedType nodeTypeDefinition = new TypeDescription.ForLoadedType(Node.class);

            final StackManipulation.Size operandStackSize = new StackManipulation.Compound(
                    MethodVariableAccess.REFERENCE.loadFrom(1),
                    TypeCasting.to(nodeTypeDefinition),
                    MethodVariableAccess.REFERENCE.storeAt(4),
                    MethodVariableAccess.REFERENCE.loadFrom(1),
                    MethodVariableAccess.INTEGER.loadFrom(3),
                    FieldAccess.forField(nodeTypeDefinition.getDeclaredFields().filter(named("value")).getOnly()).write(),
                    MethodReturn.VOID
            ).apply(methodVisitor, implementationContext);

            return new Size(operandStackSize.getMaximalSize(), instrumentedMethod.getStackSize());
        }
    }

    public static void main() throws IOException {
        final DynamicType.Builder<?> builder =
                new ByteBuddy()
                        .subclass(Setter.class)
                        .modifiers(Visibility.PUBLIC, TypeManifestation.FINAL);

        builder.method(named("set")).intercept(SetImplementation.INSTANCE).make().saveIn(new File("/tmp/bbtest"));
    }

Not the byte-code that is produced for the implementation is the following:
```
public set(Ljava/lang/Object;II)V throws java/io/IOException 
    ALOAD 1
    CHECKCAST test/ByteBuddyTest$Node
    ASTORE 4
    ALOAD 4
    ILOAD 3
    PUTFIELD test/ByteBuddyTest$Node.value : I
    RETURN
    MAXSTACK = 2
    MAXLOCALS = 4
```

As one can see, this byte-code is exactly the same as the byte-code from the hand-written version, with one exception:  the `MAXLOCALS = 4` line. In the hand-written version, where we see that `MAXLOCALS = 5`. 
This is most likely a bug, is it not?

Forgive me if I have missed something obvious here :)

Thank you for your time, George

**Comment by raphw** [comment]
A `StackManipulation` does not track the size of the local variable array. If you want to assign such values, you have to increase the value manually via the `ByteCodeAppender`. By default, Byte Buddy only reserves space for the variables implicit to a method.

**Comment by geoand** [comment]
Thank you very much for the clarification!

**Comment by raphw** [comment]
You are welcome!
