### ISSUE TITLE
Question: migrating from DynamicValues to OffsetMappings

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#340]
I'm trying to update from Byte Buddy 1.6 to 1.7. I find it quite hard to wrap my head around the OffsetMappings.

Could you help me out for example how to convert https://github.com/stagemonitor/stagemonitor/blob/0.82.0/stagemonitor-tracing/src/main/java/org/stagemonitor/tracing/AbstractTracingTransformer.java to `OffsetMapping`s?

No offense, but why have `DynamicValues` be removed completely? Couldn't they be bridged to `OffsetMappings`? Isn't that a backwards incompatible change that would require a new major version? I think in the [release notes](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.7.0), you confused `DynamicValues` with `CustomValue`. It would be really helpful if you could add a breaking changes section in the release notes. Ideally with some hints on how to migrate to the new concepts.

**Comment by raphw** [comment]
I had to do the change mostly to increase the flexibility and a bit for performance purposes. They were a redundant specialization of the already existing general API and it should be rather easy to express the one as the other. Sorry for the work that imposes on you. Using the old API, it was for example impossible to bind a writable value.

For loading a constant value using the more general API,  you do:
```java
OffsetMapping.Target.ForStackManipulation.of( <constant value> )
```

You can create this value from a `OffsetMapping.Factory` that provides you with the annotation. You should do all possible heavy work from within the factory as it is reused for any advice application.

**Comment by felixbarny** [comment]
Thx for you help! But I still don't quite get it to work.

This is my current attempt:

```java
public static class ParameterNamesDynamicValue implements Advice.OffsetMapping.Factory<ParameterNames> {

	@Override
	public Class<ParameterNames> getAnnotationType() {
		return ParameterNames.class;
	}

	@Override
	public Advice.OffsetMapping make(ParameterDescription.InDefinedShape target,
									 AnnotationDescription.Loadable<ParameterNames> annotation,
									 AdviceType adviceType) {
		StringBuilder params = new StringBuilder();
		for (ParameterDescription param : target.getDeclaringMethod().getParameters()) {
			params.append(param.getName()).append(',');
		}
		return Advice.OffsetMapping.Target.ForStackManipulation.of(params.toString());
	}
}
```

But I get a compile error:
```
Incompatible types:
Required: net.bytebuddy.asm.Advice.OffsetMapping
Found: net.bytebuddy.asm.Advice.OffsetMapping.Target
```

**Comment by raphw** [comment]
You are missing one step:

```java
    public static class ParameterNamesDynamicValue implements Advice.OffsetMapping.Factory<ParameterNames> {
   @Override
   public Class<ParameterNames> getAnnotationType() {
     return ParameterNames.class;
   }
   @Override
   public Advice.OffsetMapping make(ParameterDescription.InDefinedShape target,
                                         AnnotationDescription.Loadable<ParameterNames> annotation,
                                         AdviceType adviceType) {
   final StringBuilder params = new StringBuilder();
    for (ParameterDescription param : target.getDeclaringMethod().getParameters()) {
      params.append(param.getName()).append(',');
    }
    return new Advice.OffsetMapping() {
      @Override
      public Target resolve(TypeDescription instrumentedType,
                                      MethodDescription instrumentedMethod,
                                      Assigner assigner,
                                      Context context) {
        return Advice.OffsetMapping.Target.ForStackManipulation.of(params.toString());
      }
    };  
  }
}
```

The idea is the following:
1.  The `OffsetMapping.Factory` lives for itself and can be registered in different `Advice` classes.
2. The `Advice` classes use this factory to create an `OffsetMapping` once the factory is supplied for a given advice class.
3. For every time a type is instrumented, the `OffsetMapping` resolves a `Target` for this particular target type.

I am therefore wondering if you want to get the names of the `instrumentedMethod` rather than those of the method that is the advice class.

**Comment by felixbarny** [comment]
Thx a lot, I think I get it now. So it helps to improve performance in case the OffsetMapping.Target does not only depend on the actual instrumented method but rather on the advice method like annotation type?

In other words, the `OffsetMapping.Factory#make` method refers to the `@Advice.OnMethodEnter` annotated advice method and `Advice.OffsetMapping#resolve` refers to the actual instrumented methods?

One more question: how can I bind offset mapping factories?

I tried:

```java
List<Advice.OffsetMapping.Factory<?>> dynamicValues = getDynamicValues();
Advice.WithCustomMapping withCustomMapping = Advice.withCustomMapping();
for (Advice.OffsetMapping.Factory<?> dynamicValue : dynamicValues) {
	withCustomMapping = withCustomMapping.bind(dynamicValue.getAnnotationType(), dynamicValue);
}
return withCustomMapping;
```

But got the following exception:

```
Caused by: java.lang.IllegalStateException: Not a constant value: org.stagemonitor.tracing.profiler.ProfilingTransformer$ProfilerDynamicValue@51f8f916
	at net.bytebuddy.asm.Advice$OffsetMapping$ForStackManipulation$Factory.of(Advice.java:3165)
	at net.bytebuddy.asm.Advice$WithCustomMapping.bind(Advice.java:8347)
	at org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer.registerDynamicValues(StagemonitorByteBuddyTransformer.java:131)
	at org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer.getAdvice(StagemonitorByteBuddyTransformer.java:117)
	at org.stagemonitor.core.instrument.StagemonitorByteBuddyTransformer.getTransformer(StagemonitorByteBuddyTransformer.java:100)
	at org.stagemonitor.core.instrument.AgentAttacher.initByteBuddyClassFileTransformer(AgentAttacher.java:163)
	at org.stagemonitor.core.instrument.AgentAttacher.performRuntimeAttachment(AgentAttacher.java:85)
	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:360)
	at org.stagemonitor.core.Stagemonitor.reset(Stagemonitor.java:342)
	at org.stagemonitor.core.Stagemonitor.init(Stagemonitor.java:62)
	... 39 more
```

**Comment by raphw** [comment]
Yes, you are correct with your summary: the factory is supplied with information regarding the advice method (the parameter that is annotated), the offset mapping is supplied with the instrumented method and the resulting target is used as a dispatcher whereever the instrumented method refers to the annotated value.

The error hints that javac has not invoked the correct overloaded method. You do not need the `dynamicValue.gerAnnotationType` part as the annotation is already supplied. You only need to supply the annotation if you are binding an `OffsetMapping` directly where Byte Buddy creates the factory for you. This might be sufficient for your use case as you are not doing any precomputation on the factory level?

You can do:
```
withCustomMapping.bind(dynamicValue.getAnnotationType(), offsetMapping);
```
or
```
withCustomMapping.bind(offsetMappingFactory);
```
For your case, Byte Buddy resolves to the best match which is attempting to bind the provided value as a constant (string, serializable or number) what is impossible.

**Comment by felixbarny** [comment]
Currently, the signature is `bind(OffsetMapping.Factory<? super T> offsetMapping)` shouldn't it be `bind(OffsetMapping.Factory<? extends T> offsetMapping)`? 

While I can bind a single `OffsetMapping.Factory`, I can't add them to a `List<Advice.OffsetMapping.Factory<? super Annotation>>` first, only a `List<Advice.OffsetMapping.Factory<? extends Annotation>>` from where it's not possible to do the following:

```java
for (Advice.OffsetMapping.Factory<? extends Annotation> offsetMappingFactory : dynamicValues) {
	withCustomMapping = withCustomMapping.bind(offsetMappingFactory);
}
```

**Comment by raphw** [comment]
You are right, this should actually be simply be `bind(OffsetMapping.Factory<? extends Annotation> offsetMapping)` as the specific annotation type is entirely irrelevant for the signature.

Feel free to include this in your PR or I will fix it myself some time soon. You can cast to a raw factory in the mean time if you want to get past this.

**Comment by felixbarny** [comment]
> Feel free to include this in your PR or I will fix it myself some time soon.

I'll make a pull request

> You can cast to a raw factory in the mean time if you want to get past this.

That's what I currently do

**Comment by raphw** [comment]
I will release a new version some time this week. Its JavaZone so I am a bit busy but first thing I find a few minutes. I hope this resolves all of your problems? Please reopen this, if not.

**Comment by felixbarny** [comment]
It does. Also, there are workarounds for everything, so no need to hurry.
