### ISSUE TITLE
*any* doesn't match methods matched by *named*

### ISSUE THREAD

**Issue by softboysxp** [raphw/byte-buddy#341]
Hi,

I'm writing a simple Java Agent to record all invocations to methods within a class. Here's *premain* for the Agent:

```java
public static void premain(String args, Instrumentation instrumentation) {
	new AgentBuilder.Default()
			.type(nameEndsWith("CloseableHttpClient"))
			.transform((builder, typeDescription, classLoader, module) -> builder.method(any()).intercept(MethodDelegation.to(Interceptor.class).andThen(SuperMethodCall.INSTANCE)))
			.installOn(instrumentation);
}
```

where *Interceptor* simply prints out the method being intercepted:
```java
public class Interceptor {
	@RuntimeType
	public static void intercept(@AllArguments Object[] args, @Origin Method method, @SuperCall Callable<?> callable) throws Exception {
		System.out.println(method);
	}
}
```

with the following test app, no methods are being intercepted:

```java

import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.util.EntityUtils;

public class Test {
	public static void main(String[] args) {
		try (CloseableHttpClient client = HttpClientBuilder.create().build()) {
			HttpGet httpGet = new HttpGet("http://google.com/");
			System.out.println(EntityUtils.toString(client.execute(httpGet).getEntity()));
		} catch (IOException ex) {
			ex.printStackTrace();
		}
	}
}
```

However, if I change the *any* matcher to *named* in the agent:
```java
builder.method(named("execute"))
```

then I can intercept the method with specified name:

```
public org.apache.http.client.methods.CloseableHttpResponse org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest) throws java.io.IOException,org.apache.http.client.ClientProtocolException
public org.apache.http.client.methods.CloseableHttpResponse org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest,org.apache.http.protocol.HttpContext) throws java.io.IOException,org.apache.http.client.ClientProtocolException
<output from original app>
```

I suspect this has something to do with the fact that *CloseableHttpClient* is an abstract class but I'm not sure.
Also seeing that *any* is a boolean matcher that simply returns true it baffles me that *any* wasn't matching methods more strict matchers are.

Your help is very much appreciated. Thank you!

**Comment by raphw** [comment]
You can register a listener to get notified on instrumentation events, including errors.

From the top of my head, matching any method includes abstract methods without a super method available such that Byte Buddy rejects the instrumentation attempt.

**Comment by softboysxp** [comment]
Hi @raphw, thank you very much for the fast reply and the suggestion to use a Listener.

Output from the Listener helped me find the real issue:

```
[Byte Buddy] ERROR org.apache.http.impl.client.CloseableHttpClient [sun.misc.Launcher$AppClassLoader@18b4aac2, null, loaded=false]
java.lang.IllegalStateException: Cannot call super (or default) method for public abstract org.apache.http.params.HttpParams org.apache.http.client.HttpClient.getParams()
	at net.bytebuddy.implementation.SuperMethodCall$Appender.apply(SuperMethodCall.java:97)
	at net.bytebuddy.implementation.bytecode.ByteCodeAppender$Compound.apply(ByteCodeAppender.java:134)
...
```

Like you suggested, an unrelated method *getParams* that was not implemented by this abstract class and the interface does not have a default method either. I guess this interrupted the process of transforming the target class before the intended target methods were transformed.

Thanks again for helping me figure this out, been bothering me for a whole day!
