### ISSUE TITLE
#question#How to record current instance of a particular class?

### ISSUE THREAD

**Issue by devstress** [raphw/byte-buddy#345]
I wonder how I could use ByteBuddy to intercept a class to let it stores its instance.
For instance, I want to redefine FileOutputStream's constructor to let DataStore stores the current instance of FileOutputStream.
From:

```java
public FileOutputStream(File file, boolean append) {
        ...
}
```
To:
```java
public FileOutputStream(File file, boolean append) {
        ...
        if (file.getPath().contains("abc.txt")) {
               DataStore.store(this);    //DataStore.store(FileOutputStream stream) is a static method.
        }
}
```
Kind regards,

**Comment by raphw** [comment]
Have a look at the `Advice` class which allows you to inline code. The `Advice` would look like:

```java
class MyAdvice {
  @OnMethodEnter
  static void exit(@Advice.Argument(0) File file, @Advice.Argument(1) boolean append) {
    if (file.getPath().contains("abc.txt")) {
      DataStore.store(this);
    }
  }
}
```

In order to make this work, the `DataStore` class needs to be injected into the class path.
