### ISSUE TITLE
"is inconsistent for 'this' reference" error

### ISSUE THREAD

**Issue by orange-buffalo** [raphw/byte-buddy#346]
While instrumenting code with Advices, I am facing this error:
```
 java.lang.IllegalStateException: public org.springframework.util.MimeType(java.lang.String,java.lang.String,java.util.Map) is inconsistent for 'this' reference: org/springframework/util/MimeType
```
it appears not only for class mentioned in the message, but for hundreds others too, be it Spring framework classes, Apache Tomcat or anything else. I did not face this on version 1.6, it looks like this appeared after migration to 1.7.5. 

Is it really the problem in bytecode of all those classes? 

I am attaching [the project to reproduce the problem](https://github.com/raphw/byte-buddy/files/1328345/reproducer.zip).

**Comment by raphw** [comment]
I think that is a problem with Byte Buddy validating the constructor incorrectly where the frame is not existant before involking the super constructor. I will have a look, thanks for reporting!

**Comment by raphw** [comment]
I found the issue and already fixed it on master. I will do a release this weekend. Thanks for reporting!

**Comment by orange-buffalo** [comment]
Many thanks for the quick resolution!
