### ISSUE TITLE
API changes review for Byte Buddy

### ISSUE THREAD

**Issue by lvc** [raphw/byte-buddy#349]
The review of API changes for the Byte Buddy library since 0.6.15 version: https://abi-laboratory.pro/java/tracker/timeline/byte-buddy/

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by the https://github.com/lvc/japi-compliance-checker tool.

Thank you.

![byte-buddy-2](https://user-images.githubusercontent.com/1517837/31002874-07f538b6-a4fe-11e7-9c71-a5e9bedecabf.png)
![byte-buddy-1](https://user-images.githubusercontent.com/1517837/31002873-07e98674-a4fe-11e7-8543-71664acb9fde.png)

**Comment by raphw** [comment]
Thanks, I will look into how to make this information available somewhere.

**Comment by raphw** [comment]
With my model of many nested classes, I found that this metric is rather an approximation. Thanks for sharing it anyways, it motivated me to a journey through my code's history!
