### ISSUE TITLE
Can Agent add fields ?

### ISSUE THREAD

**Issue by benwimpory** [raphw/byte-buddy#353]
Hi,

I have a Java Agent working with advice to capture method entry and exit as per code below.

Is it possible using an agent builder to define new fields on classes too ?

```java
new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED))
            .with(myListener)
            .disableClassFormatChanges()
            .type(nameEndsWith("MyClass"))
            .transform((builder, typeDescription, classLoader, javaModule) ->
                builder
                    .visit(to(MyInterceptor.class).on(named("myMethod")))
```

Thanks,

Ben

**Comment by raphw** [comment]
It can normally but by `disableClassFormatChanges` you explicitly forbid it.

Since you are using this option and `Advice`, I assume that you are redefining classes that are already loaded? In this case, you cannot add fields as the JVM explicitly forbids it.

**Comment by benwimpory** [comment]
Thanks for the fast feedback.  I am not redefining classes that are already loaded, I just want to add fields to classes from another module before they are loaded.

After removing the disableClassFormatChanges() from the AgentBuilder I can now:

1. Define a field on an existing class (MyClass) with `buiilder.defineField("x", long.class)`
2. Add a constructor interceptor on MyClass the that uses Field advice so I can set the new field value with: 

`
public static class ConstructorInterceptor {
    @Advice.OnMethodExit
    public static void intercept(@Advice.This Object thiz, @Advice.FieldValue(value="x",readOnly=false) long x) throws Exception {
        x = 3;
    }
}
`

3. Add non-constructor interceptor to MyClass and access the field with:

`
@Advice.OnMethodEnter
public static void intercept(@Advice.This Object thiz, @Advice.FieldValue("x") long x) throws Exception {      
        System.out.println(x);
    }
`

BUT....

...these transforms only get applied by the agent if I transform a single type.

eg.

**This works fine**

`.type(nameEndsWith("MyClass")
 .transform(....)  // define new field
 .transform(...)   // add interceptor
`

**but adding a second type with transforms means it does not**

`.type(nameEndsWith("AnotherClass")
  .transform(.....)
 
  .type(nameEndsWith("MyClass")
 .transform(....)  // define new field
 .transform(...)   // add interceptor
`
**Question**
Why would a set of transforms work fine when applied in isolation, but not work if applied with other types ?  Re-ordering the transforms made no difference.

**Comment by raphw** [comment]
I assume that an error occurs somewhere. Have you registered an `AgentBuilder.Listener` to keep track of errors-

**Comment by benwimpory** [comment]
I have a listener registered for all events and see no errors at all.  I print a stack trace if there is an error and see nothing in the log,

The onTransformation() callbacks are logged and only show one class being transformed: `AnotherClass`.  I only apply method enter/exit advice to this class.

Would the fact that `AnotherClass` creates instances of `MyClass` be an issue here ?  Could it be that the application of transforms to `AnotherClass` causes `MyClass` to be loaded and prevents the builder applying the transforms to `MyClass` as it has already been loaded ?

To re-iterate, both sets of types/transforms work fine if used in isolation.  It's chaining them across different types that causes an issue.

**Comment by benwimpory** [comment]
With both sets of type/transform applied, when I debug into the `installOn()` call at the very end, I can only see the last set of transforms and elementMatcher applied in the `AgentBuilder$Default$Transforming transformer variable`

Looks like the first set of type/transforms are being lost by the builder before they are ever applied.

**Comment by raphw** [comment]
Yes, this might be an issue . If you load a type during a transformation, the type is not instrumented as it is already loaded. If you cannot see the type being logged at all, this is probably the case. What you can do would be to only reference a type within the method body which is loaded lazily. You can then use a generic type such as `Object` in combination with `@DynamicType`.

**Comment by benwimpory** [comment]
I am not referencing / importing the problematic class in the interceptors or agent though so don’t think my agent code is loading the type prematurely.

Essentially I have application classes A and B and want to apply transforms to both.

Is this supported in ByteBuddy if A depends on B ? eg. Imports it, creates an instance ?

Will carry on debugging, but last point I got to was I could see both types and associated transforms being passed into the InstrumentationImpl class. So the AgentBuilder didn’t look like it was dropping any info with the chaining.

Ben

**Comment by raphw** [comment]
Well, of course it does work in general and this is tested on many occasions. I would need a more detailed example or even reproduction to look into this. Could you provide such a reprodction? In this case, I am happy to have a look!

**Comment by benwimpory** [comment]
Ok great :-) I will create an example and post it for you to review.

Ben

**Comment by benwimpory** [comment]
Ok, my bad.  I **was** referencing the uninstrumented class in the interceptor's method's argument - sorry!

```
@Advice.OnMethodEnter
public static void entry(MyClass myclass)
{
    System.out.println(myClass.getMyField());
}
```
I have now removed this and replaced with Object and both classes are being transformed :-)

I was able to use casting inside the method to still access the method as per below...

```
@Advice.OnMethodEnter
public static void entry(Object object)
{
    MyClass myClass = (MyClass) object;
    System.out.println(myClass.getMyField());
}
```

What does the `@DynamicType` add to this use case ?

**Comment by raphw** [comment]
This would only be relevant for a return type and when using `MethodDelegation`, therefore, never mind the dynamic type.

By the way, you can also use a `TypePool` to describe the class and represent it as a `TypeDescription` where the method signature types are not loaded and this problem does not occur. But this is probably a lot of unneccessary work and if the current solution works for you without too many troubles, this is what you should go for.

**Comment by benwimpory** [comment]
Thanks for your help and quick responses. All working nicely for me now. Great library!
