### ISSUE TITLE
External attachment fails without arguments on Windows

### ISSUE THREAD

**Issue by dmac100** [raphw/byte-buddy#355]
When using `ByteBuddyAgent.attach(agentJar, processId);` with the current process under Windows 7, Oracle JDK-9, then it produces an exception with "Could not self-attach to current VM using external process".

I traced the issue to the `ProcessBuilder` used in `ByteBuddyAgent.installExternal`. There is a bug in the JDK where empty arguments are not handled correctly. See http://bugs.java.com/view_bug.do?bug_id=6518827

This then causes an `ArrayIndexOutOfBounds` exception in `Attacher.main`

**Comment by raphw** [comment]
Thanks for the hint, I fixed this on master just now.
