### ISSUE TITLE
Feature request: API to replacing native methods

### ISSUE THREAD

**Issue by thekingnothing** [raphw/byte-buddy#358]
PowerMock provides ability to mock/stub native methods. To achieve it, PowerMock has to replace native with a new  one with body. 

I have how I can do it with current ByteBuddy API, but solution looks dirty for me, because I had to copy code from ByteBuddy and then a bit change the copied code and use reflection to get internal state. 

The change that I have to implement are: 

- implement `AsmVisitorWrapper`
- implement `ClassVisitor`
- use reflection to get  `ClassWriter` from `net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor`. 

As you may see, my solution is fragile and I do not want to continue in such way. Maybe you can provide an API to work with native methods like with other and delegate calls to Advice?

**Comment by raphw** [comment]
This should work already? You can simply rebase native methods where the original methods are renamed. You can then use `Instrumentation` to define a native method prefix.

Maybe you meant to work this in another way? Can you show me the code you wrote such that I can get a direction?

**Comment by thekingnothing** [comment]
It doesn't work for me, either with rebase nor with redefine

I tried the following: 

```
    private ForDeclaredMethods instanceMethods() {
        return Advice.withCustomMapping()
                     .bind(MockMethodAdvice.Identifier.class, identifier)
                     .to(MockMethodAdvice.class)
                     .on(
                         isMethod().and(
                             not(
                                 ElementMatchers.<MethodDescription>isStatic().or(ElementMatchers.<MethodDescription>isSynthetic())
                             )
                         )
                     );
    }

```

And a test is falling 

```
java.lang.UnsatisfiedLinkError: powermock.test.support.MainMockTransformerTestSupport$NativeMethodsTestClass.nativeReturnMethod(Ljava/lang/String;)Ljava/lang/String;

	at powermock.test.support.MainMockTransformerTestSupport$NativeMethodsTestClass.nativeReturnMethod(Native Method)
```

I committed the code to branch [2.x/powermock-byte-buddy-native](https://github.com/powermock/powermock/tree/2.x/powermock-byte-buddy-native), so you may try to debug. 
Test: `org.powermock.core.transformers.NativeMethodsMockTransformerTest` 
Class: `org.powermock.core.transformers.bytebuddy.MethodMockTransformer`

Change from rebase to redefine or vice verse you may in this method 
`org.powermock.core.classloader.bytebuddy.ByteBuddyMockClassLoader#createByteBuddyBuilder`

**Comment by raphw** [comment]
When using the `Advice` component as a visitor, it applies inlining into the existing method what is impossible for native methods as those methods do not define any byte code.

In order to rebase a method, you have to implement it where Byte Buddy moves the native method to a new signature. This is done using the `.method(...).intercept(...)` API. Using the `Advice` as visitor guarantees that the class file format is not altered making it suitable for redefining agents.

Alternatively, you can redefine the call sites of such methods. For this, I plan to extend the `MemberSubstitution` component for what I did not have the time yet.

**Comment by thekingnothing** [comment]
Hi, I have finally find a time to continue work on it. I replaced an advice to using `.method(...).intercept(...)`. Now, tests are falling with `java.lang.NoClassDefFoundError` for auxiliary's classes in case if the class is loaded by `PowerMockClassLoader` when a native method is called with reflection. Could you guide me where to look? 

> Alternatively, you can redefine the call sites of such methods. For this, I plan to extend the MemberSubstitution component for what I did not have the time yet.

I was thinking about the approach. PowerMock mocks constructor in such way. But it will confuse users, instead preparing for test a class which you want to mock, you will have to prepare a class which is used. It's also not good, because a class under test will be modified. I want to minimise change in a class which is being tested.

**Comment by raphw** [comment]
About the auxiliary classes. Byte Buddy typically injects the auxiliary classes before the instrumented type to avoid exactly this. Byte Buddy offers an `Injector` to push a class file into some class loader. I assume that you have to do something in this direction, too?

**Comment by thekingnothing** [comment]
Thank you for help. I guess the issue due to not standard using ByteBuddy. I use it as wrapper on ASM within class loading operation. I modify bytecode of a class and then I get bytes to define a new class in the class loader. I’ll look at `Injector`

Best regrads,
Arthur Zagretdinov

On 2 Dec 2017, at 20:33, Rafael Winterhalter <notifications@github.com<mailto:notifications@github.com>> wrote:


About the auxiliary classes. Byte Buddy typically injects the auxiliary classes before the instrumented type to avoid exactly this. Byte Buddy offers an Injector to push a class file into some class loader. I assume that you have to do something in this direction, too?

**Comment by raphw** [comment]
Yes, Byte Buddy injects the auxiliary classes first such that they are available once the actual class is loaded. The best order does however depend a bit on the type of reference you can find in a class - if class A references B in a field or method signature, then B should be loaded first. The classes in byte code are typically loaded lazily.

**Comment by thekingnothing** [comment]
I resolved the issue with using ClassLoadingStrategy and defining all classes what have to be loaded. I'm only doubting that loading and the get byte to define a class is a good idea. It was done for comb ability with current solution with using Javassist.

```
                   bytebuddyAfterTransformation
                   .make()
                   .load(this, new MockClassLoadingStrategy(protectionDomain))
                   .getBytes()
```

```
private class MockClassLoadingStrategy implements ClassLoadingStrategy<ByteBuddyMockClassLoader> {
        private final ProtectionDomain protectionDomain;
    
        private MockClassLoadingStrategy(final ProtectionDomain protectionDomain) {
            this.protectionDomain = protectionDomain;
        }
        
        @Override
        public Map<TypeDescription, Class<?>> load(final ByteBuddyMockClassLoader classLoader,
                                                   final Map<TypeDescription, byte[]> types) {
            final Map<TypeDescription, Class<?>> result = new HashMap<TypeDescription, Class<?>>();
            
            for (Entry<TypeDescription, byte[]> entry : types.entrySet()) {
                final TypeDescription typeDescription = entry.getKey();
                final Class<?> loaded = defineClass(typeDescription.getName(), protectionDomain, entry.getValue());
                result.put(typeDescription, loaded);
            }

            return result;
        }
    }
```
