### ISSUE TITLE
Match only if another class is accessible on the classloader's classpath

### ISSUE THREAD

**Issue by tylerbenson** [raphw/byte-buddy#364]
I would like to write instrumentation that is only applied if certain classes are available on the classpath.

Basically, want to I write an `Advice` that has a `provided`/`compileOnly` dependency on a class and I only want that instrumentation to be applied if that class is accessible on the classpath.

Any suggestions on how to do this? Would this be too expensive?

Thanks!

**Comment by raphw** [comment]
You could for example write a matcher that uses a `ClassFileLocator.ForClassLoader` for looking up the existance of a class file. If you are certain that you would never instrument the class in question, you can also use `Class.forName` to look it up. In any case, you should implement some caching logic to remember a prior lookup if the matcher's first conditions are not too fine-grained (e.g. mention a particular class).

Other than that, Byte Buddy has no special powers to know if a class exists or not before it is loaded. It only offers some mechanisms to interact with class files.

**Comment by tylerbenson** [comment]
Ok, that's helpful, thanks.

Semi related question... if a transformation doesn't modify the structure of the class, is there any benefit (performance or otherwise) in allowing the initial transform through without modification, adding it to a list for retransform, and modifying the class the next time it comes through?

It seems like this might be beneficial for matchers like `hasSuperType` or `isAnnotatedWith` where the classes to analyze are now loaded and easier to inspect.

**Comment by raphw** [comment]
No, Byte Buddy does not care about modifications, only the VM. It limits your options, though, what makes redefinition sometimes unattractive (for example, you cannot override a method from a super type).

Generally, it is often beneficial to drop the ability to change the layout as you can for example use a less intrusive method graph compiler.

**Comment by tylerbenson** [comment]
To be clear, I'm working from the context of an `AgentBuilder`, so by forgoing class structure modifications the first time, I'm limited in what I can do in future retransformations. (This is something I'm ok with.) I believe I'm explicitly choosing this by defining my `AgentBuilder` like this:
```java
new AgentBuilder.Default().disableClassFormatChanges()
```

Can you explain more about what you mean by `a less intrusive method graph compiler`?  How would I configure that?

**Comment by raphw** [comment]
An `AgentBuilder` can operate on loaded classes by using a`RetransformationStrategy`. You can use a `RawMatcher` to detect if you are matching a loaded class or not.

Once a class is defined for the first time most JVMs - including HotSpot - do not allow changing the structure of a class. By enabling the above option, you are making sure that Byte Buddy detects any such change if you define it by accident and throws an exception, thus aborting the transformation process.

By default, Byte Buddy resolves the entire graph of virtual methods for any type. To do so, it needs to navigate the entire type hierarchy what can be costly. If this is not necessary, you should configure the `ByteBuddy` instance used by your `AgentBuilder` to use a less intrusive compilation strategy, typically: http://bytebuddy.net/javadoc/1.7.8/net/bytebuddy/dynamic/scaffold/MethodGraph.Compiler.ForDeclaredMethods.html

**Comment by tylerbenson** [comment]
Regarding that last point there `navigate the entire type hierarchy what can be costly`, does it make a difference in the speed if the class has already been loaded and thus each type is accessible from the classloader?

**Comment by raphw** [comment]
Yes, in order to resolve all methods, Byte Buddy has to get hold of `Method` objects when operating on a loaded type what is rather expensive as it involves security checks and other overhead. Also, the algorithm to resolve methods down a hierarchy (including several type of bridges and visibilities) is quite expensive in itself. If you can avoid it, it is a win.

**Comment by raphw** [comment]
Closing, please reopen if this is still relevant.
