### ISSUE TITLE
Android SDK build tools 26

### ISSUE THREAD

**Issue by lhunath** [raphw/byte-buddy#366]
`dx.jar`'s `DxOptions` no longer has a `targetApiLevel` property and `CfTranslator.translate` has gained a `Context` parameter.  As a result, byte-buddy-android is no longer compatible.

**Comment by raphw** [comment]
Thank you for the information, I will try to update some time soon.  It is too bad that this API breaks all of the time...

**Comment by raphw** [comment]
It does not seem like there are any newer versions out on Maven Central. How did you encounter a newer version in the first place? Did you update it manually?

**Comment by lhunath** [comment]
Pretty sure I just got it off Android's SDK manager.

**Comment by raphw** [comment]
I will have a look but typically, this should not be an issue when running
on Android where this bundle is not available.

Its an issue for me to not have these things available on Maven Central as
it breaks my usage of CI.

2017-11-27 15:26 GMT+01:00 Maarten Billemont <notifications@github.com>:

**Comment by tiwieso** [comment]
Hi! Are there any news on this topic?

**Comment by raphw** [comment]
Sorry for not taking this on sooner, was not even a large thing. I just adjusted the API use on master with a fallback for older API versions.
