### ISSUE TITLE
Dynamically wrap advice instrumentation with try/catch

### ISSUE THREAD

**Issue by tylerbenson** [raphw/byte-buddy#371]
I would like to ensure that advice code I write never throws an exception for the code being instrumented.  Is there a way to do this dynamically or do I need to write the try/catch directly into my instrumentation?

**Comment by raphw** [comment]
You can use the `suppress` property for this in both the enter and exit advice. By default, the suppression happens silently but you can also register a handler in the `Advice` class.

**Comment by tylerbenson** [comment]
Cool.  Does the `suppress = Throwable.class` have to be added to each (enter and exit) `@Advice` annotation, or does registering an exception handler via `withExceptionHandler` on advice somehow change the default behavior?

Just to be clear, I believe this will not cause any exception thrown by the original code to be caught, just the `Advice` code.

**Comment by raphw** [comment]
Yes, it does. The handler is only invoked if the suppression mechanism kicks in. As said, by default the exception is silently dropped but you can trigger any byte code to process the exception as for example logging it to some API.
