### ISSUE TITLE
android example

### ISSUE THREAD

**Issue by huaxiaolin** [raphw/byte-buddy#372]
I am an Android developer and can give a complete example of Android

**Comment by raphw** [comment]
Hi, examples are more then welcome. If you wanted to extend the tutorial to include a section on Android, this is very welcome!

**Comment by huaxiaolin** [comment]
#  **when i run your android example ,show this erro ,why ?  so i want you help me**  


java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/dx/dex/DexOptions;
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at net.bytebuddy.android.AndroidClassLoadingStrategy$DexProcessor$ForSdkCompiler.makeDefault(AndroidClassLoadingStrategy.java:197)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at net.bytebuddy.android.AndroidClassLoadingStrategy$Wrapping.<init>(AndroidClassLoadingStrategy.java:321)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at main.java.net.bytebuddy.android.test.TestActivity$StrategyCreator$Wrapping.make(TestActivity.java:183)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at main.java.net.bytebuddy.android.test.TestActivity$TestRun.onClick(TestActivity.java:135)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at android.view.View.performClick(View.java:5207)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at android.view.View$PerformClick.run(View.java:21177)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at android.os.Handler.handleCallback(Handler.java:742)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at android.os.Looper.loop(Looper.java:154)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at android.app.ActivityThread.main(ActivityThread.java:5527)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at java.lang.reflect.Method.invoke(Native Method)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
11-10 14:10:18.387: W/net.bytebuddy(16069): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.dx.dex.DexOptions" on path: DexPathList[[zip file "/data/app/net.bytebuddy.android.test-1/base.apk"],nativeLibraryDirectories=[/data/app/net.bytebuddy.android.test-1/lib/arm64, /vendor/lib64, /system/lib64]]
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-10 14:10:18.387: W/net.bytebuddy(16069): 	... 13 more
11-10 14:10:18.387: W/net.bytebuddy(16069): 	Suppressed: java.lang.ClassNotFoundException: com.android.dx.dex.DexOptions
11-10 14:10:18.387: W/net.bytebuddy(16069): 		at java.lang.Class.classForName(Native Method)
11-10 14:10:18.387: W/net.bytebuddy(16069): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-10 14:10:18.387: W/net.bytebuddy(16069): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-10 14:10:18.387: W/net.bytebuddy(16069): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-10 14:10:18.387: W/net.bytebuddy(16069): 		... 14 more
11-10 14:10:18.387: W/net.bytebuddy(16069): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by huaxiaolin** [comment]
thanks ,i have resolve  this error  .

**Comment by raphw** [comment]
You probably missed the dexmaker dependency.
