### ISSUE TITLE
Injecting classes used by advice onto classloader

### ISSUE THREAD

**Issue by tylerbenson** [raphw/byte-buddy#377]
When writing a java agent it is common for my advice code to need to reference another class.  That class contains references to classes that are not on the system classpath, but instead only a child classpath (see spring boot jars).  I've been working around this by preventing the class from being added to the system classpath, and then injecting the class into the child classloader using `defineClass`.

It seems that byte buddy already does something like this with `ClassLoadingStrategy.Default.INJECTION` but I can't figure out how to use it on specific classes.  What is the correct way to handle this with byte buddy?

Thanks!

**Comment by tylerbenson** [comment]
Perhaps something to do with `net.bytebuddy.dynamic.loading.ClassInjector`?

**Comment by raphw** [comment]
Yes, you can use for example `ClassInjector.UsingReflection` to do that.

**Comment by tylerbenson** [comment]
Is there a way for that to happen automatically, or do I need to inject each class individually?
Are there any examples on how to do this?

**Comment by raphw** [comment]
By automatically you mean: Can Byte Buddy detect what classes to inject?

If this is your question the answer is no as Byte Buddy cannot know what classes to expect on the target class path before the instrumentation is complete at what point Byte Buddy has no longer a choice to make this decision. You have to name all classes you want to inject into a target class loader, ideally those are not too many.

I would suggest you to do this as a seperate step of the instrumentation cycle: `.type(...).transform(<inject>).transform(<redefine>)`.

This way you can assure that the types are available during instrumentation if you reference them in any signatures.
