### ISSUE TITLE
Question: How to resolve java.lang.VerifyError for IBM JDK?

### ISSUE THREAD

**Issue by natfitz** [raphw/byte-buddy#379]
I am working on a java agent that is leveraging byte-buddy for byte code instrumentation to implement open tracing around RPC's. One of the requirements is for this to work on IBM WAS running JDKs 1.6-1.8. The below code is working correctly against oracle JDK and openJDK but I'm running into an issue using the advice api when it runs on an IBM JDK. Any info on how to resolve this would be greatly appreciated.

```
java.lang.RuntimeException: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.VerifyError: JVMVRFY012 stack shape inconsistent; class=javax/net/ssl/HttpsURLConnection, method=<init>(Ljava/net/URL;)V, pc=11
```
 The advice transformer

```java 
public class HttpURLConnectionTransformer implements AgentBuilder.Transformer {

    public HttpURLConnectionTransformer(Instrumentation instrumentation) {

        new AgentBuilder.Default()
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
                .type(ElementMatchers.isSubTypeOf(java.net.HttpURLConnection.class))
                .transform(this)
                .installOn(instrumentation);
    }

    @Override
    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
        return builder.visit(Advice.to(HttpURLConnectionAdvice.class).on(ElementMatchers.isConstructor()));
    }
} 
```

Advice method

```java 
@Advice.OnMethodEnter
    private static Object enter(@Advice.Origin Constructor constructor, @Advice.AllArguments Object[] args) {
        Object advice = null;
        try {
            System.out.println("Test out advice");
        } catch (Exception e) {
            //DO NOTHING
        } finally {
            return advice;
        }

    } 
```

**Comment by raphw** [comment]
This seems to be a bug related to the IBM JDK which can even occure without byte code modification: https://www.ibm.com/developerworks/community/forums/html/topic?id=7f616d94-a4ec-4e32-9ccc-3406ee063a6f

I would like to look further into it. Can you run your application with `-Dnet.bytebuddy.dump=/some/folder and attach the class file of the non-verified class? I assume that J9 does not accept the try-catch block in the entry of a constructor. This is nothing that javac allows but legitimate from the JVM specification. 

One work around would be to move the code from the advice to another class, inject that class into the bootstrap class loader and invoke that method from the advice. This might avoid this error.

**Comment by natfitz** [comment]
Thanks for your quick response. We were able to work around the issue by capturing around the getInputStream, getOutputStream, and connect methods. As a result this also resolved a problem we were seeing with duplicating instrumentation on RestTemplate.
