### ISSUE TITLE
Question: Can I define a class that references itself?

### ISSUE THREAD

**Issue by theangrydev** [raphw/byte-buddy#380]
For example,
```
class Node {
     String name;
     Node[] children;
}
```

**Comment by theangrydev** [comment]
I was hoping there is a magic lazy `TypeDefinition` somewhere I could use that is interpreted as the class being built.

**Comment by raphw** [comment]
Yes, have a look at the `TargetType` class which is used as a placeholder for self-references.

**Comment by theangrydev** [comment]
Thanks!
