### ISSUE TITLE
Do I have the chance to output the changed/intrumented classes into files?

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#381]
For improving skywalking debugging capability, after I returned the **Builder** in `transform` method, can I have the result of class in byte[] format?

I haven't found the way, and `AgentBuilder.Listener#onComplete` didn't include it yet.

So, is there any chance I can do this?

**Comment by raphw** [comment]
In the `onTransformation` call, you receive an instance of `DynamicType` which has a reference to the byte code by `getBytes`. The `onComplete` method is also called for types that are ignored, therefore, the method does not carry a byte array.

**Comment by wu-sheng** [comment]
Thanks.
