### ISSUE TITLE
Question about  intercept Constructor

### ISSUE THREAD

**Issue by ascrutae** [raphw/byte-buddy#382]
I Found that the byte-buddy generate another constructor that the last parameter type is generated inner class in the intercepted class when I enhance the constructor. Is that byte-buddy provider that the byte-buddy only modify the byte code without generate another constructor?

Thanks 

xin

**Comment by ascrutae** [comment]
Thanks for your response. 

There is `NoSuchMethodException` exception on my console when I interceptor the class has one constructor with parameters.   The exception message show that spring framework cannot found the default constructor. I debug the spring framework code and found that the the return for the method {@link org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor#determineCandidateConstructors(Class, String)  contains three cases:
case 1. Constructors with annotation `autowired type`
case 2. The bean class only has one constructor with parameters
case 3. The bean has constructor without parameters

but the code intercepted constructor cannot in case 2, because the agent generate an new constructor.

Here is the spring code snippet : [go~](https://github.com/spring-projects/spring-framework/blob/4.3.x/spring-beans/src/main/java/org/springframework/beans/factory/annotation/AutowiredAnnotationBeanPostProcessor.java#L332-L352)

So I want to that  byte-buddy provide an way to not generate an new constructor. 

Thanks 

Xin

**Comment by raphw** [comment]
Unfortunately, the creation of a constructor is necessary to retain the byte code's validity.

However, Byte Buddy does mark the constructor as synthetic which you can check using reflection. I wonder if Spring is not considering a non-synthetic constructor for usage. Maybe the Spring project can consider such a use case? There are plenty compilers, including javac, that add synthetic constructors.

**Comment by ascrutae** [comment]
oh. I see.

I found that the spring framework has consider a non-synthetic constructor for usage in the latest version when I read the spring framework source code. but it doesn't works in the current release  version.

Thanks for you response.

Xin
