### ISSUE TITLE
Allow to override method with different sub-class as return type

### ISSUE THREAD

**Issue by flozano** [raphw/byte-buddy#383]
I'm trying to achieve generating B:
```java
abstract class A { 
   abstract Exception get();
}

class B extends A {
    @Override
    RuntimeException get() {
       return something;
    } 
}
```
(using Exception just because it's well-known hierarchy map)

If I use `defineMethod` for the `get`, I get two methods when I invoke the getClass().getDeclaredMethods(): both `Exception get()` and `RuntimeException get()`. If I use `method` to match the existing abstract method and intercept it to do what I need, I can implement the `get()` from A in B and it works... but with reflection I get that the type of the method is `Exception` and not `RuntimeException`.

**Comment by raphw** [comment]
That Byte Buddy adds the second method is required by the JVM spec, the second method is a bridge for the first method and it is marked as such in the class file. You can check this property using the reflection API. If you create the same class using javac, you get the same method added.

You can however shut down this behavior by registering a different `MethodGraph.Compiler`. By default, the Java type system is used for determing hierarchies but you can choose to use the JVM type hierarchy which however makes your generated code difficult to use from other Java code.

**Comment by flozano** [comment]
Ah... you are right. If I do the same by compiling java code, both methods are there. My apologies for opening this issue, many thanks for your explanation.
