### ISSUE TITLE
byte-buddy-maven-plugin: Missing ClassFileLocator failure upgrading from 1.7.8 to 1.7.9

### ISSUE THREAD

**Issue by sbabcoc** [raphw/byte-buddy#384]
I tried to upgrade to the latest release (1.7.9) of byte-buddy-maven-plugin, but my project fails to build with this release. Here's the error I get...

[ERROR] Failed to execute goal net.bytebuddy:byte-buddy-maven-plugin:1.7.9:transform-test (default) on project junit-foundation: Execution default of goal net.bytebuddy:byte-buddy-maven-plugin:1.7.9:transform-test failed: A required class was missing while executing net.bytebuddy:byte-buddy-maven-plugin:1.7.9:transform-test: net/bytebuddy/dynamic/ClassFileLocator
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.bytebuddy:byte-buddy-maven-plugin:1.7.9
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/bb8d/.m2/repository/net/bytebuddy/byte-buddy-maven-plugin/1.7.9/byte-buddy-maven-plugin-1.7.9.jar
[ERROR] urls[1] = file:/C:/Users/bb8d/.m2/repository/net/bytebuddy/byte-buddy/1.7.9/byte-buddy-1.7.9.jar
[ERROR] urls[2] = file:/C:/Users/bb8d/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[3] = file:/C:/Users/bb8d/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[4] = file:/C:/Users/bb8d/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[5] = file:/C:/Users/bb8d/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.0.M1/org.eclipse.sisu.inject-0.3.0.M1.jar
[ERROR] urls[6] = file:/C:/Users/bb8d/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[7] = file:/C:/Users/bb8d/.m2/repository/org/eclipse/aether/aether-util/1.1.0/aether-util-1.1.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.nordstrom.tools:junit-foundation:3.1.3-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------: net.bytebuddy.dynamic.ClassFileLocator

**Comment by raphw** [comment]
The class is still part of Byte Buddy 1.7.9 so I do not know why you are getting this error. Can you check the jar file in: C:/Users/bb8d/.m2/repository/net/bytebuddy/byte-buddy-maven-plugin/1.7.9/byte-buddy-maven-plugin-1.7.9.jar to make sure it is not corrupted?

**Comment by sbabcoc** [comment]
I suppose it's possible that the 1.7.9 release is corrupted in our corporate Nexus. How would I figure this out, though? The archive itself appears to be undamaged, at least as far as 7-Zip is concerned. The 'jar' utility seems happy with it, too.

**Comment by sbabcoc** [comment]
Ah! The real issue wasn't with the plugin... it was the main Byte Buddy JAR was corrupted. I deleted this from my local archive, and everything is happy with the fresh copy Maven pulled down.

**Comment by raphw** [comment]
Glad this resolved itself. Probably a partial download where only parts of the jar were copied.
