### ISSUE TITLE
Trying to subclass non static inner class with annotated parameter in constructor fails

### ISSUE THREAD

**Issue by SeriyBg** [raphw/byte-buddy#385]
Here is the test for this issue:

```
    class NonStatic {
        public NonStatic(@Deprecated final String id) {
        }
    }

    @Test
    public void testMakeSubclass() {
        final ByteBuddy bytBuddy = new ByteBuddy().with(TypeValidation.DISABLED);
        final DynamicType.Unloaded<NonStatic> make = bytBuddy.subclass(NonStatic.class).make();
    }
```

This test fails with:
```
java.lang.ArrayIndexOutOfBoundsException: 1

	at net.bytebuddy.description.method.ParameterDescription$ForLoadedParameter$OfConstructor.getDeclaredAnnotations(ParameterDescription.java:490)
	at net.bytebuddy.description.method.ParameterDescription$TypeSubstituting.getDeclaredAnnotations(ParameterDescription.java:883)
	at net.bytebuddy.description.method.ParameterDescription$AbstractBase.asToken(ParameterDescription.java:146)
```

This error does not appear if removing `@Deprecated` (it is related to any other annotations) annotation or if make the inner class `static`.

**Comment by raphw** [comment]
javac adds a synthetic parameter to the constructor for implementing the package-private visibility. I assume that this is not reflected in the annotation API while getParameterLength returns `2`.

What Java version are you using?

I am sure Byte Buddy can work around this somehow.

**Comment by SeriyBg** [comment]
I'm using `java 1.8.0_112`.
Yes, indeed as it's not static class, the first parameter in the constructor became the instance of the parent class.

**Comment by raphw** [comment]
Fixed on master.
