### ISSUE TITLE
get all specific annotations from method param and return value

### ISSUE THREAD

**Issue by xiaoxinba** [raphw/byte-buddy#387]
In a method , some param and return value have specific annotation,  some params are pojo class(some properties also the annotations),;

Then i want to get all param value which have the specific annotation, how do!!

**Comment by raphw** [comment]
If you get hold of a `MethodDescription`, you can invoke `getAnnotations` and `getReturnType` as well as `getParameters` to get descriptions for these objects which define annotations by themselves.

**Comment by xiaoxinba** [comment]
If the method param include POJO class that some properties also the specific annotation, how can i get the properties' values ;
 
for example:

public class Person{
    @annotation
    private String uuid;
    private STATE state;
} 
public void test（Person person, @annotation String str){}

how can i get the annotation's values;

**Comment by raphw** [comment]
Based on a `TypeDescription`? The API is fairly similar to the Java reflection API.

**Comment by raphw** [comment]
I am closing this question, please reopen it if you need further help.
