### ISSUE TITLE
How to define a genetic method in a non-generic class?

### ISSUE THREAD

**Issue by julianrz** [raphw/byte-buddy#388]
E.g. 
```java
interface X {
 <T> void m(){}
}
```
`ByteBuddy().makeInterface().name().typeVariable("T")` is not appropriate and works differently: makes T a parameter of X. How to define a type variable on method?

**Comment by raphw** [comment]
You can define a type variable during the definition step:

```java
new ByteBuddy()
  .makeInterface()
  .defineMethod("m", void.class, Visibility.PUBLIC)
  .typeVariable("T")
  .withoutCode()
  .make()
```

**Comment by julianrz** [comment]
My confusion was that this still makes T a class-level variable:
```
new ByteBuddy()
  .makeInterface()
  .defineMethod("m", void.class, Visibility.PUBLIC)
  .withoutCode()
  .typeVariable("T")
  .make()
```
Felt like after withoutCode we are still on method level, but apparently we are back to class level

**Comment by raphw** [comment]
Yes, after defining the implementation, you are back on class level. If you define it before the code, it is a method-level variable.
