### ISSUE TITLE
Calling a method with another method's result as a parameter

### ISSUE THREAD

**Issue by Jezza** [raphw/byte-buddy#389]
For the life of me, I can't work out how to do this, and after about 2 hours of googling and looking through the code base, I'm assuming it's not.

What I'm trying to achieve is something like:
```
@Override
public void writeExternal(ObjectOutput out) throws IOException {
	out.writeUTF(id());
}

@Override
public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
	base = assertBase(in.readUTF());
}
```

**Comment by Jezza** [comment]
As a side-note: I also can't work out how to set a field from a MethodCall.

**Comment by raphw** [comment]
You would most likely use a `MethodDelegation`: `MethodDelegation.to(MyInterceptor.class)`

```java
class MyInterceptor {
  static void writeExternal(@Argument(0) ObjectOutput oo, @This YourBean self) {
    out.writeUTF(self.id());
  }
  static void readExternal(@Argument(0) ObjectInput in, @This YourBean self, @FieldProxy("base") YourProxy proxy) {
    base.set(assertBase(in.readUTF()));
  }
}
```

You have to install an interface for your proxy yourself in the `MethodDelegation`.

If you want to avoid such proxies, have a look at `Advice`.

**Comment by Jezza** [comment]
Yeah, that's exactly how I worked around it.

```
public static final class Serialiser {
	public static void write(BaseInterface base, ObjectOutput out) throws IOException {
		out.writeUTF(base.id());
	}

	public static void read(Setter setter, ObjectInput in) throws IOException, ClassNotFoundException {
		setter.baseSet(assertRawBase(in.readUTF()));
	}
}
```

The only problem with that is the class's footprint is bigger than it would otherwise be.
It adds about 20 bytes, which, granted, isn't much, but I also wanted to avoid it given an option, hence the question.

**Comment by Jezza** [comment]
![selection_007](https://user-images.githubusercontent.com/4224088/34664836-12e49690-f45e-11e7-819f-febcdd51abb7.png)

That's how I write the class, but ideally, I would want to generate a class that would be as if I had written the facade myself. (eg, don't need to delegate it off to another class)

**Comment by raphw** [comment]
If this is of importance, use the `Advice` adapter:

```java
public static final class SerializeAdvice {
  @OnMethodEnter
  public static void write(@Advice.This BaseInterface base, @Advice.Argument(0) ObjectOutput out) throws IOException {
    out.writeUTF(base.id());
  }
}
class DeserializeAdvice {
  @OnMethodEnter
  static void intercept(@Advice.Field(value = "name", readOnly = false) FieldType field, @Advice.Argument(0) ObjectInput in) throws IOException, ClassNotFoundException { 
   field = baseSet(assertRawBase(in.readUTF());
  }
```

This way, Byte Buddy inlines your byte code.

**Comment by Jezza** [comment]
`Advice` works nicely, so I've switched to it.
Thanks!

Would still be nice if I had a bit more control over what the methods did.

**Comment by raphw** [comment]
Please do! Thanks for your feedback.
