### ISSUE TITLE
How can i call multi-static-method in definedMethod

### ISSUE THREAD

**Issue by a1e1c1f5** [raphw/byte-buddy#390]
`new ByteBuddy().subclass(Object.class)
                .defineMethod("check", void.class, Visibility.PUBLIC)
                .intercept(MethodCall.invoke(CheckUtils.class.getMethod("method1"))).make().saveIn(file);`
How can I call two static method in the "check" method. 
 I can't work out how to do this.
And my english is poor, I hope you don't mind。

**Comment by raphw** [comment]
You can chain two method calls using the `andThen` method:
```java
MethodCall.invoke(CheckUtils.class.getMethod("method1")).andThen(MethodCall.invoke(...))
```

**Comment by a1e1c1f5** [comment]
I really appreciate your help. Thank you ！
