### ISSUE TITLE
Constructing a lambda expression dynamically?

### ISSUE THREAD

**Issue by Ps-Pencil** [raphw/byte-buddy#391]
I am wondering if it is possible to construct the following method without hardcoding the lambda expression:

`public static <T>
          Function<T,T> f() { return x->x; }`

I am trying to compile another functional language to Java Virtual Machine and thus the body of lambda expressions need to be generated dynamically. This is why I cannot hard code the lambda expression and delegate the method call. 

I am wondering if there is a way to do that without digging deep into the class file format for lambda expressions.

**Comment by raphw** [comment]
Yes, it is possible. What you need to do is that you define a dynamic method in some class and then you would need to link this call site to the `LambdaMetafactory` in the JVM. Byte Buddy has currenctly support for creating dynamic call sites via the `InvokeDynamic` class but it lacks support for binding these expressions to the named factory. I will definetly look into this and provide it as a feature in a future version.

**Comment by raphw** [comment]
I added a convenience method via `InvokeDynamic.lambda`.
