### ISSUE TITLE
Slow String.format for Implementation.Context.Default.CacheValueField

### ISSUE THREAD

**Issue by KnutHR** [raphw/byte-buddy#393]
I am creating some subclasses with ByteBuddy, it was quite slow so I profiled it, creating a subtype can take over 500ms on my computer, and I found that 90%+ of the time was spent in String.format from a single location. Here's it's [Stack trace](https://i.imgur.com/KsC8nDP.png).

I guess it depend on the number of fields/methods in the class, (have a few hundreds). Anyway looks like a good spot to be squishing in performance to me. It seems the name is always generated from the hash on each access, and FieldDescription.equals is run a lot for checking if the fields exist in some map.

Maybe use a faster formatting method, and if the same field is compared many times, you could speed it up by just cashing the name in a field like this in Implementation.Context.Default.CacheValueField:

```
private String name = null;
@Override
public String getName() {
    if(name == null) {
        name = String.format("%s$%s$%s", FIELD_CACHE_PREFIX, suffix, RandomString.hashOf(hashCode));
    }
    return name;
 }
```

**Comment by raphw** [comment]
Good catch, I will definetly fix that. I have not thought about the fact that the field name is part of the hash code function, it probably would be best to eagerly compute the name here.

Could you change the method, build the project and see if it makes a real impact? Sometimes such measurements are biased by savepoints.

**Comment by KnutHR** [comment]
I haven't gotten it built, but a friend of mine said the [call graph](https://i.imgur.com/UO2bAlT.png) shows that the time is spent in String.format. At least usually I see that overhead is spread over the callers in the hierarchy

**Comment by raphw** [comment]
Fixed on master.
