### ISSUE TITLE
Support retransformation in SkyWalking

### ISSUE THREAD

**Issue by wu-sheng** [raphw/byte-buddy#395]
Apache SkyWalking is using ByteBuddy as the core byte codes manipulate lib since beginning. Now we have a solid plugin mechanism based on ByteBuddy match/intercept/etc.

e.g. https://github.com/apache/incubator-skywalking/blob/master/apm-sniffer/apm-agent/src/main/java/org/apache/skywalking/apm/agent/SkyWalkingAgent.java#L74-L97 

For further usages, I am considering about adding **retransform**. And I just find a [stackoverflow answer](https://stackoverflow.com/questions/35968530/retransform-classes-with-byte-buddy) from you. But I still need more helps.

* Do I need a new AgentBuilder for retransformation? based on your response.
```
you can use the AgentBuilder API for enabling retransformation. Upon installing the agent, Byte Buddy will retransform all classes that are already loaded. You can enable retransformation like this:

AgentBuilder builder = new AgentBuilder.Default()    
  .with(RedefinitionStrategy.RETRANSFORMATION)
  .with(InitializationStrategy.NoOp.INSTANCE)
  .with(TypeStrategy.Default.REDEFINE);
```
* How to target the explicit classes by matches?
* What are the difference between transformation and retransformation? e.g. What happen for an object(already init, construct invoked) when its class is going to be retransformed?

**Comment by wu-sheng** [comment]
FYI @ascrutae

**Comment by raphw** [comment]
Once you turn on the option, Byte Buddy will transform all loaded classes and there is nothing you need to change. For most JVMs, you probably also want to turn on the `.disableClassFormatChanges()` option as this is a restrictions imposed by most VMs and also HotSpot.

This requires you to not change the class file, i.e. not to add fields or methods what is something that some instrumentations do. Generally, you want to use `Advice` for such agents and avoid `MethodDelegation`.

**Comment by wu-sheng** [comment]
Do you have an example for a quick run? I want to prepare this feature. Never use advice and retransform before.

Need more helps.😃

**Comment by raphw** [comment]
`Advice` has a quite extensive javadoc. Do you know Stagemonitor? They use this mechanism for APM. Here is the discussion with some code examples: https://github.com/raphw/byte-buddy/issues/110

Hope it helps!

**Comment by raphw** [comment]
Closing this for now, please reopen if this is still relevant.
