### ISSUE TITLE
Unable to enhance sun.net.www.protocol.http.HttpURLConnection when using bytebuddy

### ISSUE THREAD

**Issue by haofeiL** [raphw/byte-buddy#396]
Hello, when I was using bytebuddy, I found that I could not enhance the native classes in jdk7. For example: sun.net.www.protocol.http.HttpURLConnection, I hope you can tell me how I should enhance it. Thank you very much.Here is my example.
```
new AgentBuilder.Default()
                .type(ElementMatchers.named("sun.net.www.protocol.http.HttpURLConnection"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public Builder<?> transform(Builder<?> builder,
                                                TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        return builder.method(ElementMatchers.named("connect"))
                                .intercept(MethodDelegation.to(...));
                    }

                })
                .installOn(instrumentation);
```

**Comment by wu-sheng** [comment]
This class is loaded by bootstrap class loader. See Raphew' s example here: https://gist.github.com/raphw/34c0e2fffe2ee7b4f02f

**Comment by raphw** [comment]
Some people write to generic matchers and then intercept bootstrap loader classes by mistake. Therefore, you have to setup a specific ignore matcher that does not exclude the bootstrap loader if you want to make use of this possibility.

**Comment by raphw** [comment]
Closing for now, please reopen if this is still relevant.

**Comment by shixiaoxianga** [comment]
> 

链接失效了

**Comment by shixiaoxianga** [comment]
Link failed
