### ISSUE TITLE
Findbugs is now Spotbugs can switch for next release

### ISSUE THREAD

**Issue by wltjr** [raphw/byte-buddy#401]
For consideration, Findbugs is now [Spotbugs](https://github.com/spotbugs/spotbugs). It should be a drop in replacement. I have been [building](https://github.com/Obsidian-StudiosInc/os-xtoo/commit/60e813c50b63a59a9450096eaba4918663886996#diff-100e12cf9d1ac2028e31d25fa899f4c3) it with Spotbugs without issue. Specifically just [spotbugs-annotations](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spotbugs-annotations%22).

**Comment by raphw** [comment]
I am already using Spotbugs (see https://github.com/raphw/byte-buddy/blob/master/pom.xml#L194) which can process the findbugs annotations.

**Comment by wltjr** [comment]
Ok cool, I just noticed the [findbugs dep](https://github.com/raphw/byte-buddy/blob/master/pom.xml#L86) when messing with AutoValue replacing Lombok. I did not see spotbugs was already in use else where :)

**Comment by wltjr** [comment]
Seems like findbugs is still used for some [annotation](https://github.com/raphw/byte-buddy/blob/master/pom.xml#L125) stuff? Not sure just saw it in there thus opened issue I have no needs there either way so pretty moot to me. Just like to always see things using the latest of other stuff.

**Comment by raphw** [comment]
I keep the Findbugs dependency for building with Java 6 what Spotbugs does not support.

**Comment by wltjr** [comment]
Ah ok, not sure what to say about that stuff. AutoValue and AutoCommon seem to be >=1.8. Though I know a number of projects keep support for older JDKs. It is one thing that does cause issues for moving things in the other direction. Which is where my interest always lie. I care less about older JDKs. I guess I am on an indirect mission to get the Java world to update and kick legacy ways and habits. Not sure what things will be like when 10 comes out, and then 11, etc. How many previous versions they will keep supporting. Many are having to update some things due to dropping 1.5 support, even binaries no longer run. Finally some clients of my own will have to update... Legacy support seems to be the biggest issue with Lombok as well.

I think maybe by the time 10 comes out, may be worth considering only >=1.8. It maybe a bit much to support 5 different versions. I think 3 tends to be most practical, which 6 would technically be the 4th with Java 9, 7th would be 3rd and oldest. I know its been a problem also for icedtea, as they spend most time backporting and fixing older jdk and little to no time for current or upcoming. I think Oracle is seeking to change all of this with 4 releases of Java per year, each quarter. Seems like at least 1 older version will be dropped per year or something.

Anyway not sure how you want to handle this. Lombok seems to be troublesome for > 1.8. No clue when it will build under 9. It does have legacy support still. Other stuff Spotbugs, Auto*, etc seems to be requiring newer. Thus up to you on what all you want to support. I guess the build system will need to be modified for the various versions and switch dependencies or something. Not to mention handling that in the files themselves. Changing imports based on jdk and dependencies, I think is a bit much.

IMHO I would suggest maybe with 1.8 release saying only >=1.8. The rest of the Java world is being forced to move forward either way. Anyone who needs to run under older JDK could just use an older byte-buddy, <=1.7.9 or something.

Either way up to you. I will modify things for my needs. Just like to work with upstreams on moving stuff forward when I can. Though having just packaged Gradle. Its still using an ancient Guava, with stuff that's been in JDK since like 1.6... Really think all need to help get rid of legacy Java cruft. But thats my viewpoint. Having clients running older code I did in 1.4 years, I understand there is cost to updating. Not practical for all.

**Comment by raphw** [comment]
For me, it is still important to support older Java versions as Byte Buddy is a fairly wide-spread dependency and especially in the enterprise, a lot of people are stuck with older versions.

I still hope to find a better solution for the Lombok parts, maybe by opening up for less strict rules for equality of objects, but for now, I think that there is no better way.

However, I just updated Lombok to the latest release that claims to be fully Java 9 compatible and even builds on Java 9. I hope to release a new version next week. Could you check against the latest master to check if this works for you?

At some point, I will surely update to Java 1.8 but at this moment staying backwards compatible is a decision that I think is in the interest of the wider Java community while I fully understand your point of view.

**Comment by wltjr** [comment]
@raphw I think Oracle is seeking to change how the enterprise world operates. Plus all the growing interest around like OpenJDK, IBM releasing J9, for [OpenJ9](https://github.com/ibmruntimes/openj9-openjdk-jdk9). All assumptions, but seems Oracle maybe looking to disrupt others legacy Java business and move everything to a newer different model. Not sure, they are donating Netbeans to Apache. Netbeans seems to be the official IDE for OpenJDK 8 per [Wikipedia](https://en.wikipedia.org/wiki/NetBeans), not sure its relation to 9+ or if that is an accurate statement. Many still make money off supporting older Java, which includes Oracle but not limited to them. Seems like they may want to change that, IMHO.

I am really not a fan of Lombok. I am actually quite impressed AutoValue thus far seems to be a drop in replacement for Lombok. I am using sed to make the change after unpack, before compile. That seems to be enough and builds fine, and other things that need it build against it. I haven't seen any runtime issues, or exceptions in Netbeans 9 thus far. Though I cannot confirm 100% if byte-buddy-dep is being used yet at runtime. Definitely in use at build time after having been built with AutoValue vs Lombok. AutoValue has considerable less dependencies, and no issues building.

In fact you could build the Auto* stuff for an older JDK I believe. It is just the binaries put on Maven and Gradle repos that were built with target 1.8, thus the byte code is to new for < 1.8. If byte-buddy-dep say builds those from source. Then it could replace Lombok for older, I believe. I haven't built them under older so I cannot confirm. What ever supports annotation processing, so I think 1.6, or at least 1.7. I suspect 1.6 will be dropped sometime in 2018, from Java 11 or 12, not sure.

Lombok for sure does not build under Java 9. I can checkout from Git, but the [file I have issues with has not changed since almost a year ago](https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/javac/apt/Javac9BaseFileObjectWrapper.java). It maybe useable as a binary but not from source. At least [building Lombok under Java 9 for me fails](https://github.com/rzwitserloot/lombok/issues/1562). Nothing byte-buddy can do to fix upstream build issues with Lombok. Unless you know how to fix that issue.

I have to double check, but I believe keeping Java 1.8 support for Lombok is problematic. I am removing support for that along with 6 and 7. Its just troublesome for me all around. byte-buddy-dep I haven't had any issues with thus far. It is just what I need to build it from source, and building those dependencies from source as well. Its a unique requirement.

I think the entire Java community is going through growing pains with 9. IMHO that is a good thing, a much needed kick in the rear. I think all will need to start having better > support vs < than going forward. Only time will tell...
