### ISSUE TITLE
Programmatic remove byte-buddy added method interceptor

### ISSUE THREAD

**Issue by zone1511** [raphw/byte-buddy#403]
Does byte-buddy provide api to remove method interceptor added by byte-buddy agent? If yes, any sample to refer to? If not, does this feature on road map?

**Comment by raphw** [comment]
Any transformation returns a `ResettableClassFileTransformer` that offers an API for resetting the applied transformation. You can also add another transformation on top of a previous one. If you know how to implement the original logic using Byte Buddy, you can simply redefine the methods to their original intend.

**Comment by raphw** [comment]
Closing, please reopen if this is still relevant.

**Comment by zone1511** [comment]
@raphw If I have multiple method intercepted added to many classes, is there any possible to remove just some of them of I have to remove all and add back those I want to keep?

**Comment by raphw** [comment]
No, unfortunately.
