### ISSUE TITLE
How to use ByteBuddy intercept JDK class, eg: java.io.FileInputStream

### ISSUE THREAD

**Issue by sustbeckham** [raphw/byte-buddy#404]
I found java.io.FileInputStream is loaded first than agent jar. So how can I do this ?

**Comment by raphw** [comment]
Did you set a custom ignore matcher for `AgentBuilder`? By default, Byte Buddy ignores all classes on the bootstrap path.

**Comment by sustbeckham** [comment]
I have no customer ignore matcher.  below code not work correct.  System.out.println is not work correct either. help ...

ByteBuddyAgent.install();
        new AgentBuilder.Default().type(is(FileInputStream.class)).transform(new AgentBuilder.Transformer() {
            @Override
            public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription,
                                                    ClassLoader classLoader, JavaModule module) {
                System.out.println("--->" + typeDescription.getName());
                return builder.visit(Advice.to(MyAdvice.class).on(named("open")));
            }
        });

**Comment by raphw** [comment]
Closing, please reopen if this is still relevant.
