### ISSUE TITLE
byte-buddy-maven-plugin should use ${maven.compiler.target} as default ClassFileVersion for ByteBuddy

### ISSUE THREAD

**Issue by DiabolusExMachina** [raphw/byte-buddy#405]
Hi, 

I was spending all day to trying to figure out the cause of java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version in my application. 

In one of our project we use the byte-buddy-maven-plugin to intercept some methods during the maven build. The Project is java 6 and the maven compiler plugin is set to java 6 as well. However the generated Classfiles from ByteBuddy will default to java 8. 

I could fix this with writing an own Entrypoint and setting the classlevel myself. 

However I think it would be much more comfortable if ByteBuddy would choose the Java ClassFileVersion version by looking at the source level of the project.

**Comment by raphw** [comment]
You are absolutely right. I will have a look. If you want to speed up the process, feel free to send a PR. The plugin should check the `code.level` property or something similar and set the class file version accordingly.

**Comment by DiabolusExMachina** [comment]
So I had a look at the code and it' s not obvious for me how to implement this.  You really seem to like Enums btw ;-). 


So either I have to Copy Paste some code of the EntryPoint.Default Enum or I refactor the EntryPoint.Default Enum itself to use some kind of factory to create the ByteBuddy instance. And this factory would have a method do set the desired Java Version from outside. 

I like the second approach more but then the PR will affect the byte-buddy-dep module as well as the byte-buddy-maven-plugin. What is your opinion?

**Comment by raphw** [comment]
I thought about this and I think this mandates an API change. This might break the plugin for some people but as it is now, the unexpected result that varies with the JVM that is used is a pretty severe bug. I rather have the build fail for that reason. I pushed a commit to a branch where I drafted a solution but I need to do a similar thing for the Gradle plugin where I do not yet know how to get hold of the Java version. Feel free to continue, I am currently on parental leave and a bit time constrained.

**Comment by DiabolusExMachina** [comment]
Sure. I will have a look. I've never used Gradle before but I found this 
https://stackoverflow.com/questions/28061044/how-to-check-java-version-when-running-gradle

**Comment by raphw** [comment]
I already made a few adjustments and merged them to master! Please try them.

**Comment by DiabolusExMachina** [comment]
I tried but it seems not to work for my usecase. I think the problem is that ${maven.compiler.target} is set in a somewhere in a parent of the project that uses the byte-buddy-maven-plugin. 

I will test more tomorrow and try to create a PR to fix this issue. 

Btw. I think instead of changing the API of EntryPoint we could also use a SPI https://docs.oracle.com/javase/tutorial/sound/SPI-intro.html to change the default class version. What's your opinion on that?

**Comment by DiabolusExMachina** [comment]
Hello again. I have working solution. I will create a PR. 

But it will break the ByteBuddyMojo Test and I'm currently not sure how to fix it.

**Comment by raphw** [comment]
Fixed on master.
