### ISSUE TITLE
Standard class-loading strategy is the one that doesn't support anonymous classes

### ISSUE THREAD

**Issue by kutschkem** [raphw/byte-buddy#410]
See https://stackoverflow.com/a/48880437/1319284

The standard class-loading strategy when using ClassReloadingStrategy.fromInstalledAgent() ist Strategy.REDEFINITION, which is not what the comment on the method suggests it should be and which, according to the comments in your code, creates issues with anonymous classes.

My suggestion would be to introduce an overloaded version of fromInstalledAgent which takes a Strategy to be used.

**Comment by raphw** [comment]
You are right, I have already fixed this on master and added the overloaded version you suggest.

**Comment by kutschkem** [comment]
For the record, in commit db481c6bb6ba1eb58f3f7e5f554af11db18491e1
