### ISSUE TITLE
Migrate from cglib to ByteBuddy

### ISSUE THREAD

**Issue by cdancy** [raphw/byte-buddy#411]
In diagnosing an issue for the `gradle-docker-plugin` library, of which I'm the current maintainer, I'm banging my head trying to get cglib to load a class into the specified custom classloader. It creates the class/object well enough but the class itself can't be found within the actual classloader and the code ends up throwing a ClassNotFoundException. After spending way too much time with this a colleague recommended using `byte-buddy` instead. Looks like a very cool library but after searching the internets I couldn't find a "migrating from cglib to byte-buddy" doc anywhere. My apologies as I haven't read through the docs in great length yet (due to the time sink of the above) but was just wondering if you had a doc like that so that I can convert the below groovy snippet into something for byte-buddy.

```
        final def delegate = dockerClientObjectFactory.create(dockerClientClassLoader, "${COMMAND_PACKAGE}.LogContainerResultCallback");
        final def enhancer = dockerClientObjectFactory.create(dockerClientClassLoader, 'net.sf.cglib.proxy.Enhancer');
        enhancer.setClassLoader(dockerClientClassLoader)
        enhancer.setSuperclass(delegate.getClass())
        enhancer.setCallback([

            invoke: { Object proxy, java.lang.reflect.Method method, Object[] args ->
                if ("onNext" == method.name && args.length && args[0]) {
                        // some crazy stuff we do here
                    }
                }
                try {
                    method.invoke(delegate, args)
                } catch (InvocationTargetException e) {
                    throw e.cause
                }
            }

        ].asType(loadClass('net.sf.cglib.proxy.InvocationHandler')))

        def callback = enhancer.create()
```

**Comment by raphw** [comment]
Hey, the problem you encounter is that cglib relies on its own types to work, meaning that cglib must be visible to the class loader you are injecting a class into.

There is no such guide, you are correct and I should find the time to write one some day. Let me keep this issue open for a reminder. The most used capability of cglib is probably the enhancer that you are using which should be easy enough to document.

For a rough version, there is no direct equivalent but there are several options. For you, the easiest way might even be the `InvocationHandlerAdapter`:

```
new ByteBuddy()
  .subclass(delegate.getClass())
  .method(any()).intercept(InvocationHandlerAdapter.of((proxy, method, args) -> {
    // put your code here
  }).make().load(dockerClientClassLoader);
```

The resulting class does not have any type dependencies outside of the JDK and the delegate class such that you should not have any issues.

**Comment by cdancy** [comment]
@raphw thanks for the point in the right direction and the detailed response! Using your example above I put together this snippet:
```
        def delegate = getDelegateClassFromCustomClassLoader()
        new ByteBuddy()
                .with(new PrefixingRandom("helloworld"))
                .subclass(delegate.getClass())
                .method(ElementMatchers.any())
                .intercept(InvocationHandlerAdapter.of(new InvocationHandler() {
                    @Override
                    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
                        if ("onNext" == method.name && args.length && args[0]) {
                            def frame = args[0]
                            switch (frame.streamType as String) {
                                case "STDOUT":
                                case "RAW":
                                    logger.quiet(new String(frame.payload).replaceFirst(TRAILING_WHIESPACE, ''))
                                    break
                                case "STDERR":
                                    logger.error(new String(frame.payload).replaceFirst(TRAILING_WHIESPACE, ''))
                                    break
                            }
                        }
                        try {
                            method.invoke(delegate, args)
                        } catch (InvocationTargetException e) {
                            throw e.cause
                        }
                    }   
                }))
                .make()
                .load(dockerClientClassLoader, Default.CHILD_FIRST)
                .getLoaded()
                .newInstance();
```
The whole idea here is to load this byte-buddy instance into our custom class-loader (using [JCL](https://github.com/kamranzafar/JCL) which in turn has other java classes/libraries that we need to segregate from the greater code-base. However, and when using the example above, it appears that the class is not actually getting loaded into the class-loader. In putting together some test code I print out the entire contents of the classloader before and after and still the class is not found.

Another interesting point is the use of `Default.CHILD_FIRST`. Without this the process just fails complaining that it cant find the class (which makes sense because it's not in the class-loader so far as I can tell) yet when I add the child-first argument, the class is still not found, but the process is able to find the class ... that's a bit odd to me but OK.

Going further, and while things get off the ground, the entire process ultimately fails due to garbage collection/tenured space issues which I can't make head or tails of. Created a gist [HERE](https://gist.github.com/cdancy/e73129d24d9c404335288b5299bd288b) with the stacktrace. As you are more an expert in this area do you think this may be more due to something I'm misconfiguring or the JCL library itself or something else? My hunch is that this is has something to do with the fact that the class can't be found in the classloader I just can't figure out why. The code in question, if you're up for taking a look, can be found [HERE](https://github.com/bmuschko/gradle-docker-plugin/blob/d280402966526b2e49a95078a391f42d66a9de2c/src/main/groovy/com/bmuschko/gradle/docker/utils/DockerThreadContextClassLoader.groovy).

**Comment by raphw** [comment]
Why are you using `ClassLoadingStrategy.Default.CHILD_FIRST` and not `ClassLoadingStrategy.Default.INJECTION`? With child first, the class is loaded in a new class loader with the specified class loader as a parent but with child first class loading semantics. Using injection, Byte Buddy will use Java reflection to inject a class into `dockerClientClassLoader` from the outside.

In order to debug the memory issues, you would probably need to look at a heap dump. But I am wondering if you create a lot of new classes? Note that Byte Buddy creates a new class every time that you run the above code. If you want to reuse the class, you should probably create a class that you can reuse:

```java
TypeCache<Class<?>> cache = new TypeCache<Class<?>>(Sort.SOFT);
ByteBuddy byteBuddy = new ByteBuddy().with(new NamingStrategy.PrefixingRandom("helloworld"));
InvocationHandler invocationHandler = ...
Object proxy = cache.findOrInsert(dockerClientClassLoader, delegate.getClass(), () -> byteBuddy
  .subclass(delegate.getClass(), ConstructorStrategy.Default.NO_CONSTRUCTORS)
  .defineField("invocationHandler", InvocationHandler.class, Visibility.PRIVATE)
  .defineConstructor(Visibility.PUBLIC)
  .withParameters(InvocationHandler.class)
  .intercept(MethodCall.invoke(delegate.getClass().getDeclaredConstructor())
                                .andThen(FieldAccessor.ofField("invocationHandler").setsArgumentAt(0)))
  .method(ElementMatchers.any())
  .intercept(InvocationHandlerAdapter.toField("invocationHandler"))
  .make()
  .load(dockerClientClassLoader, ClassLoadingStrategy.Default.INJECTION)
  .getLoaded()).getDeclaredConstructor(InvocationHandler.class).newInstance(invocationHandler);
```

This way, you only create a single class in case that you create many such proxies.

**Comment by raphw** [comment]
I wrote a tutorial : https://mydailyjava.blogspot.no/2018/04/jdk-11-and-proxies-in-world-past.html?m=1

**Comment by cdancy** [comment]
Very awesome and easy to understand and read. Thanks!
