### ISSUE TITLE
[Q]How to intercept a method using multiple interceptors

### ISSUE THREAD

**Issue by hao117** [raphw/byte-buddy#416]
one method is intercepted by multiple interceptors

**Comment by raphw** [comment]
The `MethodDelegation` class can be chained using `.andThen`.

**Comment by raphw** [comment]
If I was not Java 6 compatible, I could try to evolve the interface. But in reality, I would probably need to extend it a bit different and overload it using some `Composable andThen(Composable impl)` to allow further chaining.

From a DSL perspective, this would be of course much better but I need to see how I can realize that. Unfortunately, I think that I would need to add some implementations to all subclasses.

**Comment by raphw** [comment]
Actually, it was quite simple. I like the idea and added it to master: https://github.com/raphw/byte-buddy/commit/3e680ca0f2e0fccb58b800d2619e29d12a5f26cb
