### ISSUE TITLE
Filter output stream events to only show ERROR

### ISSUE THREAD

**Issue by robross0606** [raphw/byte-buddy#421]
Is there anything built into the API to filter the AgentBuilder.Listener.StreamWriting output?  I'm only interested in looking at ERROR events.

**Comment by robross0606** [comment]
Nevermind, I think I figured this out.  Thanks!

**Comment by raphw** [comment]
I think I will just add a convenience method to control what output is shown. Thanks for the suggestion.

**Comment by raphw** [comment]
Convenience methods are added since 1.8.3.
