### ISSUE TITLE
NoClassDefFound when instrumenting JDK class

### ISSUE THREAD

**Issue by robross0606** [raphw/byte-buddy#422]
I'm try to use ByteBuddy and ByteBuddyAgent to instrument the [javafx.scene.Parent#layout()](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Parent.html#layout--) method.  I am able to do this using Advice to at least do a System.out.println() call successfully.  However, if I try to inject any Class from the rest of the project, I seem to get a NoClassDefFound exception on anything that is not part of the standard JDK.

Here is the gist of my AgentBuilder setup:
```
  Instrumentation instrumentation = ByteBuddyAgent.install();
  new AgentBuilder.Default()
            .type(ElementMatchers.is(new TypeDescription.ForLoadedType(clazz)))
            //.transform(new FxParentLayoutInterceptor())
            .transform(new MethodCallbackTransformer(() -> {}, () -> {}, transformedMethod, extraTransformedMethods))
            .with(new ErrorStreamLogger())
            .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
            .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
            .installOn(instrumentation);
```
And here is the MethodCallbackTransformer class:
```
public class MethodCallbackTransformer implements Transformer
{
    private final Runnable methodEnterCallback;
    private final Runnable methodExitCallback;
    
    private final String[] transformedMethods;

    public MethodCallbackTransformer(Runnable methodEnterCallback, Runnable methodExitCallback, String transformedMethod, String... extraTransformedMethods)
    {
        if (transformedMethod == null)
        {
            throw new IllegalArgumentException("transformedMethod cannot be null");
        }

        this.methodEnterCallback = methodEnterCallback;
        this.methodExitCallback = methodExitCallback;
        
        this.transformedMethods = new String[extraTransformedMethods.length + 1];
        
        this.transformedMethods[0] = transformedMethod;
        for(int i=0; i < extraTransformedMethods.length; i++ )
        {
            this.transformedMethods[i+1] = extraTransformedMethods[i];
        }
    }

    @Override
    public Builder<?> transform(Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module)
    {
        Junction<NamedElement> methodMatches = ElementMatchers.named(transformedMethods[0]);
        for(int i=1; i < transformedMethods.length; i++)
        {
            methodMatches = methodMatches.or(ElementMatchers.named(transformedMethods[i]));
        }
        
        final AsmVisitorWrapper methodsVisitor = Advice.to(EnterAdvice.class, ExitAdviceMethods.class)
                                                       .on(ElementMatchers.isMethod().and(methodMatches));

        return builder.visit(methodsVisitor);
    }

    static private class EnterAdvice
    {
        @Advice.OnMethodEnter
        static long enter(@Advice.Origin final Executable executable)
        {
            LoggingUtils.log("#" + executable.getName() + "() started!");
            return System.nanoTime();
        }
    }

    static private class ExitAdviceMethods
    {
        @Advice.OnMethodExit(onThrowable = Throwable.class)
        static void exit(@Advice.Origin final Executable executable, @Advice.Enter final long startTime, @Advice.This final Object instance, @Advice.Thrown final Throwable throwable)
        {
            final long duration = System.nanoTime() - startTime;

            // ### Throws NoClassDefFound exception ###
            LoggingUtils.log("#" + executable.getName() + "() completed in " + duration + " nanos!");
        }
    }
}
```

**Comment by raphw** [comment]
I assume that your classes are not visible to the class loader that loads JavaFX.

In this case, you would need to inject your utilities into the JavaFX class loader or any of its parent class loaders.

**Comment by robross0606** [comment]
Not sure how exactly this is the case when the "agent" is being injected at runtime by ByteBuddy.  Everything is running from a single code base.  I am not even injecting the agent via a "-javaagent" CLI argument.  Any quick way you know of to debug this?

**Comment by raphw** [comment]
The agent is on the system class path.

If you run javafx.scene.Parent.class.loadClass("pkg.LoggingUtils") do you get an error?

**Comment by robross0606** [comment]
Yes, as I would expect to since the class loaders are clearly out of whack.  The question is why.  I used a short block of code in an entry point to my regular application where I know the full classpath is available to print the class loader chain:
```
-----------------------------------------------------------------
sun.misc.Launcher$ExtClassLoader@7637f22
--- delegation ---
sun.misc.Launcher$AppClassLoader@18b4aac2 **Current ClassLoader**
-----------------------------------------------------------------
```
Then again I put the same block of code in the spot where the JVM complains that it does not not have the full class path.  The resulting output is:
```
-----------------------------------------------------------------
sun.misc.Launcher$ExtClassLoader@7637f22
--- delegation ---
sun.misc.Launcher$AppClassLoader@18b4aac2 **Current ClassLoader**
-----------------------------------------------------------------
```
I'm wondering if there might be some type of bug with using ByteBuddyAgent to inject instrumentation into the same code base as the application from which the agent was injected.

**Comment by raphw** [comment]
Shouldn't be as that applies to hundrets of unit tests, too.

Could you try a Class.forName where the error occurs and catch any exception from the call? This way, you could validate any visibility constraints by printing the result.

**Comment by robross0606** [comment]
Interesting.  So, the Thread's Context Class Loader always looks consistent across everything.  However, the individual Class's ClassLoaders seem to be different:

```
JavaFX Application Thread---MainTabs---------------------------
sun.misc.Launcher$ExtClassLoader@5c647e05
--- delegation ---
sun.misc.Launcher$AppClassLoader@6d06d69c **Current ClassLoader**
-----------------------------------------------------------------
```
vs
```
JavaFX Application Thread---Content---------------------------
sun.misc.Launcher$ExtClassLoader@5c647e05 **Current ClassLoader**
-----------------------------------------------------------------
```

**Comment by robross0606** [comment]
Given that this is indeed what appears to be happening, is there any way to change the classloader delegation chain for one or more classes?

**Comment by robross0606** [comment]
Looks like maybe you covered this already in https://github.com/raphw/byte-buddy/issues/377?

**Comment by robross0606** [comment]
The only solution I'm seeing is to manually inject each individual class as byte[] into the System classloader.  We have literally thousands of classes that build and interact off each other.  Having to manually hunt down and manually inject all the necessary ones could be a major PITA.  Is there any way to simply inject/change the classloader used by the transformed class(es)?

**Comment by raphw** [comment]
You can use the instrumentation API to append a jar to the bootstrap class loader. This makes the classes universally visible.

**Comment by raphw** [comment]
Closing, please reopen if this is still relevant.

**Comment by robross0606** [comment]
My issue is that, for reasons I can't really explain here, the application is self-instrumenting in order to hook into JavaFX methods that are poorly written.  So I'm not quite sure what "JAR" to append to the bootstrap classloader.
