### ISSUE TITLE
creating body of the complex method

### ISSUE THREAD

**Issue by lapots** [raphw/byte-buddy#423]
Does `Byte Buddy` allow to create complex, composite methods? I mean for example such return statement

    public boolean when() {
        return  count != 0 && service.isAllowed(parameter)
    }

that includes method invocations and checks. Or I should dig into some string templates and others? Because I want to generate `.class` that later will be used by a classloader.

**Comment by raphw** [comment]
You can use code templates from Java classes. Have a look at `Advice`.

**Comment by raphw** [comment]
Closing, please reopen if this is still relevant.
