### ISSUE TITLE
Inability to use Mocks in mockito-Kotlin, seems to originate from byte buddy

### ISSUE THREAD

**Issue by paulgerlich-wf** [raphw/byte-buddy#425]
When trying to instantiate mocks in Mockito for Kotlin, we are experiencing the following error:

```
__TESTNAME__(__TEST__)  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker
	at __TEST__.<init>(__TEST__.kt:148)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@26c8a6b3
Caused by: org.mockito.exceptions.base.MockitoInitializationException:

Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : null
JVM vendor name    : null
JVM vendor version : null
JVM name           : null
JVM version        : null
JVM info           : null
OS name            : null
OS version         : null

Caused by: java.lang.IllegalStateException: No compatible attachment provider is not available
```

We at one point were able to get successful test runs, but now instantiating mocks fails every time. When running tests in debug mode through the intellij IDEA IDE the tests will pass. We're assuming that, since our dependencies have not changed, there is a race condition within the byte-buddy agent when it attempts to connect to and read information about the JVM.

Does this make any sense? We're digging through the byte-buddy and byte-buddy-agent code now but have not been able to pin anything down.

Any help would be greatly appreciated! Our development has kind of halted as this is happening for us across the board. I could provide a 'mvn dependency:list' if that would be helpful.

**Comment by raphw** [comment]
What JVM are you using for this? Byte Buddy needs to install an agent. That all values are `null` seems very strange to me, those are essential properties.

**Comment by paulgerlich-wf** [comment]
Thanks for the quick reply! 

We were just able to discover the issue and it was unrelated to byte buddy, of course :)

We introduced a pretty aggressive system environment variable cleanup utility to assist with our testing process. That led to the JAVA_HOME and other variables getting cleaned up and is what we believe broke byte buddy's initialization logic.
