### ISSUE TITLE
byte-buddy no longer runs on JDK11 b6

### ISSUE THREAD

**Issue by sdfelts** [raphw/byte-buddy#428]
Unsafe.defineClass was removed.
        Caused by: 
        java.lang.UnsupportedOperationException: Cannot define class using  
reflection 
            at  
net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Unavail 
able.defineClass(ClassInjec 
tor.java:821) 
            at  
net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInject 
or.java:185) 

The quick fix to get a running jar again is to remove the JDK9 logic in src/main/java/net/bytebuddy/dynamic/loading/ClassInjector.java

@@ -9,7 +9,6 @@ import net.bytebuddy.dynamic.DynamicType; 
 import net.bytebuddy.dynamic.scaffold.subclass.ConstructorStrategy; 
 import net.bytebuddy.implementation.FixedValue; 
 import net.bytebuddy.implementation.MethodCall; 
-import net.bytebuddy.utility.JavaModule; 
 import net.bytebuddy.utility.JavaType; 
 import net.bytebuddy.utility.RandomString; 
 import org.objectweb.asm.Opcodes; 
@@ -298,9 +297,10 @@ public interface ClassInjector { 
                 @SuppressFBWarnings(value = "REC_CATCH_EXCEPTION",  
justification = "Exception should not be rethrown but trigger a fallback") 
                 public Initializable run() { 
                     try { 
-                        return JavaModule.isSupported() 
-                                ? Dispatcher.Indirect.make() 
-                                : Dispatcher.Direct.make(); 
+                        return // JavaModule.isSupported() 
+                                // ? Dispatcher.Indirect.make() 
+                                // : 
+                               Dispatcher.Direct.make(); 
                     } catch (Exception exception) { 
                         return new Unavailable(exception);

**Comment by sdfelts** [comment]
Better stack trace:
                Caused by:
                java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String, [B, int, int, java.lang.C
lassLoader, java.security.ProtectionDomain)
                    at java.base/java.lang.Class.getMethod(Class.java:2067)
                    at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$CreationAction.run(ClassInject
or.java:1260)
                    at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$CreationAction.run(ClassInject
or.java:1248)
                    at java.base/java.security.AccessController.doPrivileged(Native Method)
                    at net.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe.<clinit>(ClassInjector.java:1127)
                    ... 27 more

**Comment by AlanBateman** [comment]
Unsafe.defineClass has been terminally deprecated since JDK 9.

For proxy classes, then maybe the user of Byte Buddy can get the class bytes and use Lookup.defineClass to inject the class (as that is the only supported API for injecting classes).

**Comment by raphw** [comment]
Mockito is one of the cases where class file injection is still essential and no good alternative is offered. Mockito often needs to define a class within another package in order to allow mocking of package-private classes and mocking of protected methods. Without Unsafe, this is not currently possible in such a general scope.

**Comment by sdfelts** [comment]
The current state is that byte-buddy doesn't work on JDK11 - there is no work-around because it's calling a method that doesn't exist.
By removing the JDK9 approach and using the pre-JDK9 code, the software works.
Even if JDK11 were locked down, there would be a work-around by using JVM options to open packages.
At this time, that seems to be the best approach.

**Comment by AlanBateman** [comment]
@raphw The OpenJDK mailing lists are the right place to bring up additional use-cases. The question of java agents instrumenting classes with references to auxiliary classes is something to bring to serviceability-dev as it's beyond the use-cases that the java.lang.instrument API was intended for. There may be a connection to the work in JEP 181 on nest based access control.

**Comment by raphw** [comment]
@AlanBateman Is that really the right mailing list given that Mockito is more of a code testing tool and less about "debugging, profiling, monitoring, and management"? I have mentioned this topic on various OpenJDK mailing lists in the past but never got a proper response. My suggestion still is to add `defineClass` and `allocateInstance` methods to the `Instrumentation` interface. Java agents can always get hold of the `jdk.internal.misc.Unsafe` instance and open the package to access it, this does therefore not add any security holes, quite the contrary, as Java agents are loaded on the class path in the unnamed module, having these methods available might reduce future security issues.

I find it unfortunate that this method is taken away just like that, especially with the wide use of Java agents that currently rely on this method to implement javac-like behavior. Right now, Mockito does not work at all and the only idea I have is to use a Java agent to overcome this what would just imply more hacks that break in the future. With only these two methods, I do not think `Unsafe` would be needed anymore.

**Comment by mlchung** [comment]
I have created https://bugs.openjdk.java.net/browse/JDK-8200559 to provide a replacement API for Unsafe::defineClass for java instrumentation agent.

**Comment by raphw** [comment]
Build does now work again. Mockito is also fixed.
