### ISSUE TITLE
Loading Advice Classes from Child ClassLoaders for Hotswap

### ISSUE THREAD

**Issue by ChaosData** [raphw/byte-buddy#430]
Hi,

I'm attempting to transform loaded classes at runtime with Advice code that can be "replaced" at runtime. I'm trying to be careful with this by keeping the Advice code in a separate JAR loaded via a URLClassLoader, and `reset()`-ing all hooks with the original `Instrumentation` object from `agentmain` used to set up the instrumentations (via `installOn`); the unhooking via `reset()` works fine (and worked fine when the Advice code was in the same classloader as the main agent code). However, now that it is loaded from a separate JAR, it appears that the Advice code can no longer be referenced leading to immediate NPEs on method invocations that were Advice'd. I assume that the only way to handle that is to use some sort of `ClassLoadingStrategy` for this, but I am concerned that if I do, that will lead to issues where the original loaded version of the Advice code will continue to be used even after `reset()`-ing and attempting to instrument using separate versions of the Advice code under different child ClassLoaders.

Is it feasible to use the Advice APIs to do this?

**Comment by raphw** [comment]
Yes, advice classes are merely templates, you cannot expect them to have the same class loader scope as the instrumented types. Imagine that Byte Buddy goes into the advice class and copy pastes the method's code to the instrumented class.

You should seperate all classes that you reference in advice classes into their own classes and then use a `ClassInjector` to inject another class into the class loader of the instrumented class.

**Comment by ChaosData** [comment]
Is there a way to get a handle on the advice class that exists in the class loader of the instrumented class so that I can inject values into its static fields?

**Comment by raphw** [comment]
You can use reflection after injecting the class, the injector returns the injected class. If you want to execute code in the scope of the instrumented class, you can also instrument the class initializer via .invokeable(isTypeInitializer()).

**Comment by ChaosData** [comment]
I went with the former, that seemed to work for that.

Now I appear to be hitting a limitation(/design choice?) due to my attempt at loading/unloading `URLClassLoader`s. Because the code that sets up the instrumentation is within the classes I inject via the `ClassInjector`, this leads to an interesting quirk whereby subsequent loads of those classes from any JAR (after the initial one is `close()`-d) will use the injected class itself, which now either resides in the system classloader, or the bootstrap one (the `null` classloader) and therefore fails to resolve Byte Buddy itself. It's kind of funny actually.

I'll try to refactor the code not to behave like that, but is there a (decent?) way to remove injected classes from either the system or bootstrap classloaders once one is "done" with them? Alternatively, do you recommend any ways to inject classes/JARs into arbitrary classloaders? I feel like I might have to go this route if I can't "update" those implementations after the initial injection anyway. Worse case, I was thinking of just doing some parent classloader switcheroo shenanigans to force them to resolve from within the classloader of the class being adviced.

**Comment by raphw** [comment]
No, system and bootstrap classes are forever. The only way to unload a class is to unload its class loader.

**Comment by ChaosData** [comment]
I was able inject the class into the bootstrap classloader and then update it though retransformation it with the raw `Instrumentation`/`ClassFileTransformer` APIs. Obviously that limits the modifications that can be made, but it works well enough for now. Thanks!

**Comment by raphw** [comment]
Glad I could help!
