### ISSUE TITLE
Consider sorting the comparison order when building equals method

### ISSUE THREAD

**Issue by vlsi** [raphw/byte-buddy#431]
https://github.com/raphw/byte-buddy/blob/74fa46f41eacf9fb13c58dd32989fee5a792f39d/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/EqualsMethod.java#L164

Certain field types are faster to compare (e.g. primitives, `String`), and certain types are heavy (e.g. `ArrayList.equals` is using iterator).
Please consider moving simpler fields first when generating `equals`.

There might be side effects if `equals` has side effects (e.g. https://youtrack.jetbrains.com/issue/KT-23184 ), however I believe one should not rely on the order of checks in the `equals` method.

**Comment by raphw** [comment]
Good idea, thanks!

I think, primitives first, then strings, the enums, then the rest. Within each group, I would retain declaration order.

**Comment by mibac138** [comment]
Why do you want to compare strings and then enums? I'm pretty sure comparing enums is faster.

**Comment by raphw** [comment]
I implemented this to allow sorting fields by their type which is either custom but with convenience for:

a) primitive types
b) enumeration types
c) primitive wrapper types
d) string types

The build plugin will typically sort fields in this order before any other type.
