### ISSUE TITLE
bytebuddy overuse of @EqualsAndHashCode

### ISSUE THREAD

**Issue by testn** [raphw/byte-buddy#432]
bytebuddy seems to heavily use Lombok @EqualsAndHashCode. A lot of time it causes the performance problem as it usually generates the hashcode and equal method which will perform a deep equal in which it's wrong or has a bad performance impact in various place. A good example is MethodCallProxy. It makes a several level of calls just to calculate the hash and it is not cached either.

**Comment by raphw** [comment]
`MethodCallProxy`s are cached in `Implementation.Context::register`. This is to avoid that to proxy classes are generated twice without to users needing to know of one another.

Did you do any measurement of the performance that led you to this? I have not found this to be a problem.

**Comment by raphw** [comment]
Closing, please reopen if this is still an issue.
