### ISSUE TITLE
Copyright Notice is Missing

### ISSUE THREAD

**Issue by simshawj** [raphw/byte-buddy#444]
I noticed that you are using the Apache 2.0 license, however, there is no notice, which includes the copyright notice, as stated in the appendix of the license.

**Comment by raphw** [comment]
I do not think this is a strict requirement and I found maintaining the header tedious, that is why there is none. Ref: https://softwareengineering.stackexchange.com/questions/270091/is-a-license-header-in-source-files-required-when-applying-the-apache-software-l

**Comment by ptseng** [comment]
@raphw Hi, just to confirm are you the copyright holder of this repository?  If so would it be fair to say that this codebase is copyright 2018 raphw?

**Comment by raphw** [comment]
Copyright 2018 Rafael Winterhalter.

**Comment by ptseng** [comment]
@raphw Thank Rafael 👍
