### ISSUE TITLE
Gradle Plugin Documentation

### ISSUE THREAD

**Issue by realark** [raphw/byte-buddy#448]
Is there any documentation for the Bytebuddy gradle plugin? I'd like to use it to transform classes at compile time but I can't find any examples or docs.

**Comment by realark** [comment]
Just found this: https://assets.ctfassets.net/oxjq45e8ilak/7Me2OZM1y0IsmoAEeKgWaW/941b640ae7af83adb5c4733b566313bf/Making_Java_more_dynamic.pdf

**Comment by raphw** [comment]
I added a readme to the Maven module just as there is one for the Maven plugin. This was really missing. Thanks for bringing it up!

**Comment by realark** [comment]
Thank you!
