### ISSUE TITLE
Is it possible to rebase System.currentTimeMillis

### ISSUE THREAD

**Issue by Tatera** [raphw/byte-buddy#451]
Hi,

I've spent a long time trying to figure out how to rebase System.currentTimeMillis. What I wanted is override this bootstrap class's method with another customized clock, which means I still need to call the original System.currentTimeMillis to get the actual time and have some transformation on it. I have already successfully redefine the method with following code on Java agent mode:-

```java
final ByteBuddy byteBuddy = new ByteBuddy().with(Implementation.Context.Disabled.Factory.INSTANCE);
new AgentBuilder.Default()
	.enableNativeMethodPrefix("test_native")
	.with(byteBuddy)
	.with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
	.with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
	.with(AgentBuilder.TypeStrategy.Default.REDEFINE)
	.ignore(none())
	.type(ElementMatchers.named("java.lang.System"))
	.transform(new AgentBuilder.Transformer() {
		@Override
		public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
					return builder.method(ElementMatchers.named("currentTimeMillis")).intercept(
						MethodDelegation.to(SystemTimeInterceptor.class));
				}
			}).installOn(inst);
```

Can you please kindly advise if it is ever possible to rebase that method? Any suggestion will be appreciated. Thanks!

**Comment by raphw** [comment]
What are you struggeling with? It works when I tried it. For a delegation, the `SystemTimeInterceptor` class must however be on the boostrap path. You can avoid that by using `Advice`. Doing so, you can however not invoke the original method:


```
class Foo {
    @Advice.OnMethodExit
    public static void millis(@Advice.Return(readOnly = false) long x) {
        x = 123;
    }

    public static void main(String[] args) {
        new AgentBuilder.Default()
                .enableNativeMethodPrefix("wmsnative")
                .with(new ByteBuddy().with(Implementation.Context.Disabled.Factory.INSTANCE))
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
                .with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
                .ignore(none())
                .type(ElementMatchers.named("java.lang.System"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        return builder.method(ElementMatchers.named("currentTimeMillis")).intercept(Advice.to(Foo.class).wrap(StubMethod.INSTANCE));
                    }

                }).installOn(ByteBuddyAgent.install());

        System.out.println(System.currentTimeMillis());
    }
}
```

**Comment by Tatera** [comment]
@raphw Sorry for bringing the confusion. My struggle is that I want to rebase System. currentTimeMillis so that I can call the original method in my override method. The "redefine" way is not enough as I cannot call original method in this way. I tried to replace the above code with:
`.with(AgentBuilder.TypeStrategy.Default.REBASE)`  
But it doesn't work. Can you please kindly share a "rebase" version against that?

**Comment by raphw** [comment]
I do not think that is possible. In order to rebase, you need to change the class file layout of the `System` class what is only possible if the system class is not yet loaded what it always is. This is not possible on the JVM. Your only way is to replace the method alltogether.

**Comment by Tatera** [comment]
I see. But what if I would consider to do some injection to the java rt.jar? I mean, if I use bytebuddy to rebase java.lang.System by modifying rt.jar by another Java program before starting the production system, will that be possible anyway?

**Comment by raphw** [comment]
In this case, this would unfortunately not help since the native bindings would not be changed just by adjusting the jar.

**Comment by Tatera** [comment]
Understood. I finally created a new class with a native method to get the real time. I wrote a simple C program to bind to the native method. And in the C program I just copied from Java's os_linux.cpp which calls system's function "gettimeofday". Indeed this way will bring os dependency while it meets my requirements as time being. I still use bytebuddy to take the redefine part. Thanks a lot for all suggestions. And appreciate for your owesome work in bytebuddy:)

**Comment by huangyoje** [comment]
Just ran into the same problem, put my solution here, hoping to help others.
If you need redefine `System. currentTimeMillis()`, there is another way to get the real time.

```java
   Process process = Runtime.getRuntime().exec("date +%s");
   BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
   System.out.println(reader.readLine());
```

**Comment by RockyLOMO** [comment]
My solution is to call nanoTime and currentTimeMillis once each before injecting and save the result, so that the current time can be calculated using
```java
 (System.nanoTime() - savedNanoTime) / 1000000L + savedCurrentTimeMillis
```
, and then then use ntp synchronized time to calculate the offset and change the savedCurrentTimeMillis value.
```java
 (System.nanoTime() - savedNanoTime) / 1000000L + savedCurrentTimeMillis + ntpOffset
```
