### ISSUE TITLE
Questions on `Advice.to()`

### ISSUE THREAD

**Issue by marko-bekhta** [raphw/byte-buddy#459]
Hi @raphw I have a couple questions around method advices. I'm new to ByteBuddy hence I might be missing something obvious, and I hope you could help. 

**Intro**
I'm experimenting on writing a validation agent using ByteBuddy and Hibernate Validator. To do this I'd need to cover 4 cases:
- validate constructor parameters
- validate constructor return value (constructed object)
- validate method parameters
- validate method return value

Hence I was thinking to use a combination of `@Advice.OnMethodEnter` and `@Advice.OnMethodExit`.
So far intercepting constructors works fine, but not methods. 

**Simplified test example**
Before writing the agent itself I wanted to try ByteBuddy and see how things will work. Here is a simplified test case that is failing to "validate" the method call (the expected exception is not thrown when a method is called on a constructed object in second `assertThatThrownBy`):
```java
@Test
public void test() throws Exception {
    Class<? extends BankAccount> loaded = new ByteBuddy()
            .subclass( BankAccount.class )
            .visit( Advice.to( ConstructorParametersValidationAdvice.class )
                            .on( ElementMatchers.isConstructor()
                                         .and( ElementMatchers.hasParameters( ElementMatchers.any() ) )
                                         .and( ElementMatchers.isAnnotatedWith( Validate.class ) ) )
            )
            .visit( Advice.to( ConstructorReturnValueValidationAdvice.class )
                            .on( ElementMatchers.isConstructor()
                                         .and( ElementMatchers.isAnnotatedWith( Validate.class ) ) )
            )
            .visit( Advice.to( MethodParametersValidationAdvice.class )
                            .on( ElementMatchers.isMethod()
                                         .and( ElementMatchers.hasParameters( ElementMatchers.any() ) )
                                         .and( ElementMatchers.isAnnotatedWith( Validate.class ) )
                            )
            )
            .visit( Advice.to( MethodReturnValueValidationAdvice.class )
                            .on( ElementMatchers.isMethod()
                                         // visit only non void methods
                                         .and( ElementMatchers.returns( ElementMatchers.not( ElementMatchers.is( void.class ) ) ) )
                                         .and( ElementMatchers.isAnnotatedWith( Validate.class ) ) )
            )
            .make()
            .load( VerySimpleByteBuddyValidationTest.class.getClassLoader() )
            .getLoaded();

    Constructor<? extends BankAccount> constructor = loaded.getConstructor( int.class );
    Constructor<? extends BankAccount> constructorWitoutValidation = loaded.getConstructor();

    // should fail as a constructor with @Validate is called
    assertThatThrownBy( () -> constructor.newInstance( -1 ) )
            .hasCauseInstanceOf( IllegalStateException.class );
    // should fail as a method with @Validate is called
    // BUT it's not throwing the exception and test is failing
    assertThatThrownBy( () -> constructorWitoutValidation.newInstance().add( 10 ) )
            .hasCauseInstanceOf( IllegalStateException.class );
}
```
where advice classes simply throw `IllegalStateException`:
```java
public static class ConstructorParametersValidationAdvice {
    @Advice.OnMethodEnter
    private static void exit(
            @Advice.AllArguments Object[] parameters,
            @Advice.Origin Constructor<?> constructor) {
        throw new IllegalStateException( "validation failed" );
    }
}

public static class ConstructorReturnValueValidationAdvice {
    @Advice.OnMethodExit
    private static void exit(
            @Advice.This Object currentBean,
            @Advice.Origin Constructor<?> constructor) {
        throw new IllegalStateException( "validation failed" );
    }
}

public static class MethodParametersValidationAdvice {
    @Advice.OnMethodEnter
    private static void exit(
            @Advice.This Object currentBean,
            @Advice.Origin Method method,
            @Advice.AllArguments Object[] parameters) {
        throw new IllegalStateException( "validation failed" );
    }
}

public static class MethodReturnValueValidationAdvice {
    @Advice.OnMethodExit
    private static void exit(
            @Advice.This Object currentBean,
            @Advice.Origin Method method,
            @Advice.Return Object returnValue) {
        throw new IllegalStateException( "validation failed" );
    }
}
```
And with the bean class:
```java
public static class BankAccount {
    private int num;

    @Validate
    public BankAccount(@Positive int num) {
        this.num = num;
    }

    public BankAccount() {
        this.num = 1000;
    }

    @Validate
    @Min(0)
    public int add(@Range(min = -100, max = 100) int num) {
        if ( this.num + num > -1 ) {
            this.num += num;
            return this.num;
        }
        return this.num + num;
    }
}
```
If you are interested - real advice classes are delegating the validation to Hibernate Validator (commit with such code can be found [here](https://github.com/marko-bekhta/hibernate-validator/commit/d6cd113daa4f1877922dcc33d91ac43d4e35789f#diff-c2ef31aa314c6eb88dc446dcfe3ccecd) ). 

**Questions**
1. What am I missing that method advices are not executed?
2. Is there a way of getting a "real" constructor in Advice parameters? From debugging it looks like a constructor from a new class is returned. If that's not possible would it be safe to assume that 
```java
/**
 * @param constructor a constructor created by ByteBuddy.
 * @return a {@link Constructor} from a superclass matching the created one.
 */
private static Constructor<?> findOriginalConstructor(Constructor<?> constructor) {
    try {
        return constructor.getDeclaringClass()
                .getSuperclass()
                .getConstructor( constructor.getParameterTypes() );
    }
    catch (NoSuchMethodException e) {
        throw new IllegalStateException( "Wasn't able to find constructor matching the proxied one." );
    }
}
```
would give the original constructor then?
3. Is there any other way of getting the annotation that was used for filtering methods (`@Validate`) then using reflection? That annotation has a `groups` parameter that is needed for validation purposes. Right now I just call:
```java
private static Class<?>[] getGroups(Executable executable) {
    Validate annotation = executable.getAnnotation( Validate.class );
    return annotation == null ? EMPTY_GROUPS : annotation.groups();
}
```
But it would be nice if reflection can be omitted.

Sorry for the long text :)

**Comment by raphw** [comment]
1. The question is: Are you trying to create a proxy subclass or do you want to enhance the existing class to include the validation. Currently, you are trying a mixture of both which is why you are experiencing this behavior.

By `new ByteBuddy().subclass(BankAccount.class)`, you are creating a subclass of `BankAccount` that declares constructors with the same signature of those of `BankAccount`. This is the default behavior, have a look at `ConstructorStrategy` for alternatives.

When using `Advice.to( ... ).on( ... )` you are creating a visitor that enhances all methods that are already declared by a class. In your case, since you subclassed `BankAccount`, no virtual methods are declared by your subclass as you do not declare any.

`Advice` is meant to enhance existing behavior what is very useful for Java agents to inline code into existing methods where the byte code is then executed in the appropriate class loader but for your case, you might want to use `MethodDelegation` if you need to call into the Hibernate Validator framework anyways.

If you want to use `Advice`, you do need to declare the methods in the subclass. `Advice` can be used as an implementation rather than a visitor by declaring a primary implementation that the advice should wrap around by `builder.method( ... ).intercept(Advice.to( ... ).wrap(SuperMethodCall.INSTANCE))`.

2. As for getting the actual constructor, this is a bit tricky as the constructor is not considered virtual. You do not override one, you just happen to declare one with the same signature that invokes its equivalent super constructor. Your code would therefore work, given that the constructor is declared `public`, otherwise, you would need to use `getDeclaredConstructor`. Alternatively, you can instructor Byte Buddy to only mimic public constructors by using the appropriate `ConstructorStrategy`.

3. You can register custom bindings for parameters of both `Advice` and `MethodDelegation`. You can read annotation values during the creation of the binding and read the `Class<?>[]` values to be written as constant values into the validated class. For an array, have a look at `ArrayFactory` where you could create an array of `ClassConstant` values and bind this array to an annotated parameter. Have a look at the javadoc for how to do this or ask a follow-up question once you have tried.

**Comment by marko-bekhta** [comment]
That was really helpful, thanks! Here are some additional comments and also a few code snippets (maybe somebody would find them useful when looking for similar solution).

1. I think it's more about the enhancing the existing classes as I would like the validation to work without the user writing any additional code. And your explanation on Advice behavior cleared how the things work.
2. "Constructor problem" seems to become obsolete when I actually moved the code to an agent. As in case of the agent I don't do subclassing.
```java
new AgentBuilder.Default()
    .type( ElementMatchers.any() )
    .transform( (builder, typeDescription, classLoader, module) -> builder
            .visit( Advice
                    .withCustomMapping().bind( Groups.ForGroups.Factory.INSTANCE )
                    .to( ConstructorParametersValidationAdvice.class )
                    .on( ElementMatchers.isConstructor()
                            .and( ElementMatchers.hasParameters( ElementMatchers.any() ) )
                            .and( ElementMatchers.isAnnotatedWith( Validate.class ) ) )
            )
            .visit( Advice
                    .withCustomMapping().bind( Groups.ForGroups.Factory.INSTANCE )
                    .to( ConstructorReturnValueValidationAdvice.class )
                    .on( ElementMatchers.isConstructor()
                            .and( ElementMatchers.isAnnotatedWith( Validate.class ) ) )
            )
            // .... other visitors 
    ).installOn( instrumentation );
```
3. I followed your instructions and also checked how the `@Advice.AllArguments` mapping was implemented and created an `OffsetMapping` for the groups:
```java
@Documented
@Retention(RetentionPolicy.RUNTIME)
@java.lang.annotation.Target(ElementType.PARAMETER)
public @interface Groups {

    class ForGroups implements Advice.OffsetMapping {

        /**
         * The component target type.
         */
        private final TypeDescription.Generic target;

        public ForGroups(TypeDescription.Generic target) {
            this.target = target;
        }

        @Override
        public Target resolve(TypeDescription instrumentedType,
                MethodDescription instrumentedMethod,
                Assigner assigner,
                Advice.ArgumentHandler argumentHandler,
                Sort sort) {
            Class<?>[] groups = instrumentedMethod.getDeclaredAnnotations().ofType( Validate.class ).loadSilent().groups();

            return new Target.ForArray.ReadOnly(
                    target,
                    Arrays.stream( groups )
                            .map( group -> ClassConstant.of( TypeDescription.ForLoadedType.of( group ) ) )
                            .collect( Collectors.toList() )
            );
        }

        // code for Advice.OffsetMapping.Factory<Groups> ....
}
```
and then in the `Advice` I just annotate one of the parameters with this new `@Groups` annotation:
```java
public static class ConstructorParametersValidationAdvice {

    @Advice.OnMethodEnter
    private static void exit(
            @Advice.AllArguments Object[] parameters,
            @Advice.Origin Constructor<?> constructor,
            @Groups Class<?>[] groups) {
        ValidationEntryPoint.validateConstructorParameters( constructor, parameters, groups );
    }
}
```
and it all seems to work nicely! Thanks again!

**Comment by raphw** [comment]
Glad I could help!
