### ISSUE TITLE
missing relocated package net.bytebuddy.jar.asm.tree in 1.8.10 release jar

### ISSUE THREAD

**Issue by andrej-alac** [raphw/byte-buddy#460]
Hi Rafael ,

I've tried to create jmod version of library and I've found -  package content of net.bytebuddy.jar.asm.tree package is missing in jar but sub packages are presented.

I'm not sure if missing content of package is something you did with intention or not. Snapshot version has the same issue also.  I'm using oracle jdk 10. Please, you can verify missing classes with `jdeps` cmd line tool. 

```
jdeps byte-buddy-1.8.10.jar |grep "not found"
byte-buddy-1.8.10.jar -> not found
   net.bytebuddy.jar.asm.commons       -> net.bytebuddy.jar.asm.tree         not found

```
To fix this issue it is necessary to remove exclude of `org.ow2.asm:asm-tree `in the 

> /byte-buddy-dep/pom.xml

rebuild project and than it is possible to generate module-info.java using
`jdeps --generate-module-info .   byte-buddy-1.8.10.jar`

file net.bytebuddy/module-info.java is generated
later just unzip jar, compile module-info.java and pack all classes as jmod.

Here are all steps to create jmod.
```
jdeps --generate-module-info .   byte-buddy-1.8.10.jar 
mkdir -p jmod/classes
cd jmod/classes
jar xvf ../../byte-buddy-1.8.10.jar
cd ../..
javac -p . -d jmod/classes net.bytebuddy/module-info.java
jmod create --class-path jmod/classes jmod/net.bytebuddy.jmod
```

best regards,
Andrej

**Comment by raphw** [comment]
I just adjusted the build to only include the classes from ASM commons that are really required by Byte Buddy. It is only a few but the commons jar drags in the entire tree API what was an overkill for Byte Buddy's purposes.

Could you checkout the project, build it and see if the problem persists? At some point, I hope to generate module-info files myself and include them.

**Comment by andrej-alac** [comment]
it is fixed, thank you.  

regarding module-info generation, there are several possibilities, I personally currently using following concept based on maven-antrun-plugin and maven-install-plugin, both are executed in package phase.

As result the same jar as before plus additional jmod artifact are produced.  I guess this can be easily integrated into your /byte-buddy/pom.xml .

```
<plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.8</version>
                <executions>
                    <execution>
                        <id>jmod-package</id>
                        <phase>package</phase>
                        <configuration>
                            <target>
                                <property name="p.module.name" value="net.bytebuddy"/>
                                <exec executable="${java.home}/bin/jdeps" dir="target" failonerror="true">
                                    <arg line="--generate-module-info . ${project.artifactId}-${project.version}.jar"/>
                                </exec>
                                <unzip src="target/${project.artifactId}-${project.version}.jar" dest="target/jmod/classes"/>
                                <delete dir="target/jmod/classes/META-INF"/>
                                <exec executable="${java.home}/bin/javac" dir="target" failonerror="true">
                                    <arg line="-p . -d jmod/classes ${p.module.name}/module-info.java"/>
                                </exec>          
                                <exec executable="${java.home}/bin/jmod" dir="target" failonerror="true">
                                    <arg line="create --class-path jmod/classes jmod/${project.artifactId}-${project.version}.jmod"/>
                                </exec>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>                       
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>2.5.2</version>
                <configuration>
                    <groupId>${project.groupId}</groupId>
                    <artifactId>${project.artifactId}</artifactId>
                    <version>${project.version}</version>
                    <packaging>jmod</packaging>
                    <file>target/jmod/${project.artifactId}-${project.version}.jmod</file>
                </configuration>
                <executions>
                    <execution>
                        <id>jmod-install</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin> 
        </plugins>
```

If you wish to manually create module-info.java and/or reduce visibility of exported packages, ant echo task will replace exec jdeps command.

**Comment by raphw** [comment]
Great, I will do a new release some time soon.

I will keep this issue open and hopefully integrate a modular artifact in the release at some point.
