### ISSUE TITLE
Is there a good to invoke the original version of an adviced method/constructor?

### ISSUE THREAD

**Issue by ChaosData** [raphw/byte-buddy#462]
Hi,

I was wondering if there was a proper way to get a handle for invoking the original functionality of an adviced method/constructor without running the advice code. Up to now, I've been very hackily having my advice code keep track of thread IDs to enable recursive calls to run more-or-less cleanly.

**Comment by raphw** [comment]
No, the adviced code is merged into the original code, there is no way to seperate the two programatically. The easiest way to only trigger advice for the first entrance would therefore be, as you suggest, a thread local switch.

**Comment by raphw** [comment]
Please reopen this issue if you have further questions.
