### ISSUE TITLE
Can byte-buddy hook a native method

### ISSUE THREAD

**Issue by tangyouyi1513** [raphw/byte-buddy#464]
**Can byte-buddy hook a native method?**

I want to hook a native method in java.io.UnixFile

**Comment by raphw** [comment]
Byte Buddy is a byte code instrumentation tool and does not hook into C code. It does give you the ability to rebase methods and to use a native method prefix for this rebasement but this only works for classes that are not loaded already when the agent is applies. the `UnixFile` class is loaded before the agent is applied what makes this impossible, unfortunately.
