### ISSUE TITLE
Runtime attachment to Application Container. (Is) Detachment needed after transformation.(?)

### ISSUE THREAD

**Issue by soberich** [raphw/byte-buddy#467]
@raphw what you do is amazing..
Despite # 459 I am not trying to wait for H Validator framework's solution because this may happen not so fast (though I believe they should have provide executable validation *reference implementation* long time ago), but I want to implement small set of that functionality in just a few lines of code myself. Without groups and validation of return values for now.
But also I don't want to have additional bindings, like annotations (like Marco did with `@Validated` or similar annotation in 459 ByteBuddy's issue)
Here is what I wrote today (first experience with instrumentation)
```java
@SuppressWarnings({ "unused", "unchecked" })
public class ValidatingAgent {

    public static final ValidatorFactory factory;

    static {
        factory = Validation.buildDefaultValidatorFactory();

        ByteBuddyAgent.install();
        new AgentBuilder.Default()
                .with(StreamWriting.toSystemOut())
                .disableClassFormatChanges()
                .with(RedefinitionStrategy.RETRANSFORMATION)
                .type(isPublic().and(nameStartsWith("my.project.package")))
                .transform(new Transformer.ForAdvice()
                        .include(MethodArgsAdvice.class.getClassLoader(), ConstructorArgsAdvice.class.getClassLoader())
                        .advice(isMethod().and(hasParameters(any())).and(ValidatingAgent::isMethodToValidate), MethodArgsAdvice.class.getName())
                        .advice(isConstructor().and(hasParameters(any())).and(ValidatingAgent::isConstructorToValidate), ConstructorArgsAdvice.class.getName())
                ).installOnByteBuddyAgent();
    }

    private static boolean isConstructorToValidate(final MethodDescription methodDescription) {
        //HERE ! At the end of this line..
        final Constructor<?> constructor = MethodDescription.ForLoadedConstructor.class.cast(methodDescription)....;
        if (constructor.getParameterTypes().length != 0)
            return null != factory.getValidator()
                    .getConstraintsForClass(constructor.getDeclaringClass())
                    .getConstraintsForConstructor(constructor.getParameterTypes());
        return false;
    }

    private static boolean isMethodToValidate(final MethodDescription methodDescription) {
        final Method method = MethodDescription.ForLoadedMethod.class.cast(methodDescription).getLoadedMethod();
        if (method.getParameterTypes().length != 0)
            return null != factory.getValidator()
                    .getConstraintsForClass(method.getDeclaringClass())
                    .getConstraintsForMethod(method.getName(), method.getParameterTypes());
        return false;
    }


    public static class MethodArgsAdvice {
        @Advice.OnMethodEnter
        private static void enter(
                @Advice.This final Object me,
                @Advice.Origin final Method method,
                @Advice.AllArguments final Object[] parameters) {
            final Set<ConstraintViolation<Object>> constraintViolations =
                    factory.getValidator().forExecutables().validateParameters(me, method, parameters);
            if ( ! constraintViolations.isEmpty() ) {
                throw new ConstraintViolationException(constraintViolations);
            }
        }
    }

    public static class ConstructorArgsAdvice {
        @Advice.OnMethodEnter
        private static void enter(
                @Advice.Origin final Constructor<?> constructor,
                @Advice.AllArguments final Object[] parameters) {
            final Set<ConstraintViolation<Object>> constraintViolations =
                    factory.getValidator().forExecutables().validateConstructorParameters(constructor, parameters);
            if ( ! constraintViolations.isEmpty() ) {
                throw new ConstraintViolationException(constraintViolations);
            }
        }
    }
}
```
As an input data - I use Wildfly mainly and such application servers like Payara and Glassfish.

1. Is this ok to implement that logic in static internalization block overall? Any concerns on that (like GC)?? Also, I understand that I can trigger these transformation very very simply by making any access to this class from other part of the application, but I aim this part to be independent, so that, for example I can deploy this jar to another running Application Server, so how to trigger loading and hence execution of the logic in static initializer block from here (this source file)? 
2. Once the transformations are done, nothing will probably need to be executed again from this agent. Is it worth to think about disabling it straight after it did its job? How to unload/detach agent... I know you plan Patch API, but still for now?)
3. There is a [`ForLoadedMethod::getLoadedMethod()`](https://github.com/raphw/byte-buddy/blob/5573997884da1d47a794e532c3936354cbabe1a1/byte-buddy-dep/src/main/java/net/bytebuddy/description/method/MethodDescription.java#L1034) in [`ForLoadedMethod`](https://github.com/raphw/byte-buddy/blob/5573997884da1d47a794e532c3936354cbabe1a1/byte-buddy-dep/src/main/java/net/bytebuddy/description/method/MethodDescription.java#L937) class,  but not equivalent in [`ForLoadedConstructor`](https://github.com/raphw/byte-buddy/blob/5573997884da1d47a794e532c3936354cbabe1a1/byte-buddy-dep/src/main/java/net/bytebuddy/description/method/MethodDescription.java#L829) 
How to get the `Constructor<?>` or at least `Class<?>` of currently Matching method which happen to be ctor (in this particular case I mean - see listing above)?
4. this is what I do to match 
```java
    factory.getValidator()
                    .getConstraintsForClass(constructor.getDeclaringClass())
                    .getConstraintsForConstructor(constructor.getParameterTypes());
```
It is very straightforward but if bytebuddy can't get constuctor (which I doubt, I might just don't know your API well), what is a workaround?

5. I saw Stagemonitor discus and looked through their code, as well as Apache SkyWalker, and I see they do stuff like caching classloaders, then evicting it and more stuff to avoid memory leaks and other heavy consequences... I don't know (didn't get time to get into) why they do it but my goal is - to deploy into the running JVM my that jar (together with Application or not -irrelevant), then transform just the classes which have validation annotations on parameters of constructors and methods, and after that wither stop the agent or not (depending as well on you advice) and that is it. Further transformation target's bundle(-s) (one or several Web apps) will be again transformed only after full class unloading / reloading (app-server restart). So, if those heavy consequences may still happen I would rather avoid doing all this at all. What are the consequences of deploying this source code above into the Application Container? Does this code already leak?

Thank you very much in advance.

**Comment by raphw** [comment]
1. I would avoid the usage of a static initializer block as the self-attachment can fail. `ByteBuddyAgent.install()` will unlikely work in a production environment as it only functions on a JDK-bundled JVM that comes with the attach API. Please read the javadoc for further details. To attach to a JVM in production you must either specify your agent as a Java agent on the command line using `-javaagent` or deploy an application with a JDK that can then again use `ByteBuddy.attach(pid, jar` where you again would need to bundle your application. You can however use `ByteBuddy.install()` in unit tests and test environments where you have JDK-VMs deployed.

2. On `installOn`, you receive a `ResettableClassFileTransformer`. Calling its `reset` method, undoes any transformation if this is possible. Otherwise, class transformation is applied upon loading a class what is done lazily upon the class's first usage. From an agent's perspective, you do not know when this stage is reached. You do neither know if another agent triggers retransformations where your transformer would still be required for reapplying the transformation. But there is no danger or disadvantage in keeping it registered.

3. You should not rely on these methods. The getter is exposed to speed up Byte Buddy's annotation handling where you need such a reference to access a loaded annotation's properties. These methods are side-effect free and typically accessible which is why this approach is chosen. For constructors, there is no need for this. To get the class, you can do `Class.forName` using the member's declaring type for which you do need a class loader. Byte Buddy describes types independently of a class loader as types can be unloaded.

4. You should be able to describe all matchers using Byte Buddy's `TypeDescription` and `MethodDescription` abstractions. It exposes all methods of the Java reflection API but without the invocation APIs.

5. The problem of these applications is that it makes sense to maintain a cache of type descriptions to enhance performance. This is important for a standalone tool that can be used within many applications but if you do not experience performance problems, there is no need for you to optimize. If you implement such caches, it is important that you do not retain class loader references as this can leak the class loader what does not seem to be relevant for your use case.

Glad you like the library!

**Comment by soberich** [comment]
JRE lunched ok, but currently I am experiencing troubles with matchers and API usage of `AgentBuilder`.
Yes, I am switching to matchers from directly querying Bean Validation framework, thank you.

```java
        val isNonGetter = hasParameters(any());

        val hasConstraints = isAnnotatedWith(isAnnotatedWith(javax.validation.Constraint.class));

        val hasConstrainedParameters = hasParameters(whereAny(hasConstraints));

        val isForParameterValidation = isNonGetter.and( hasConstraints.or(hasConstrainedParameters) );

        ByteBuddyAgent.install();
        new AgentBuilder.Default()
                .with(StreamWriting.toSystemOut().withTransformationsOnly())
                .disableClassFormatChanges()
                .with(RedefinitionStrategy.RETRANSFORMATION)
                .type(isPublic().and(nameStartsWith("org.javaee8")).and(declaresMethod(isForParameterValidation)))
                .transform(new Transformer.ForAdvice()
                        .include(MethodArgsAdvice.class.getClassLoader())
                        .advice(     isMethod().and(isForParameterValidation),      MethodArgsAdvice.class.getName())
//  this does not work at all   .advice(isConstructor().and(isForParameterValidation), ConstructorArgsAdvice.class.getName())
                )// this does not work as well
                /*.transform(new Transformer.ForAdvice()
                        .include(ConstructorArgsAdvice.class.getClassLoader())
                        .advice(isConstructor().and(isForParameterValidation), ConstructorArgsAdvice.class.getName())

                )*/.transform((builder, typeDescription, classLoader, module)
                            ->
                        builder.visit(
                                new AsmVisitorWrapper.ForDeclaredMethods()
                                        .writerFlags(ClassWriter.COMPUTE_FRAMES)
                                        .method(isConstructor().and(isForParameterValidation), Advice.to(ConstructorArgsAdvice.class))
                        )
                ).installOnByteBuddyAgent();
```

1. Does declaring chained advice on `Transformer.ForAdvice` supposed to work? Sequentially? 
Declaring `.advice(isConstructor().and(isForParameterValidation), ConstructorArgsAdvice.class.getName())`  in the listing above as a second advice, or as a second transformer (like `.transform(new Transformer.ForAdvice().include(..).advice(..)`) does not make constructor advice code to be injected / merged to targets, though Sysout log says that `Person` target class was transformed. So, as a result IF `.advice(     isMethod().and(isForParameterValidation),      MethodArgsAdvice.class.getName())` declaration is the first in the list - it works, as expected, but applying `.advice(isConstructor().and(isForParameterValidation), ConstructorArgsAdvice.class.getName())` as the first advice for that transformer breaks transformation on both.. It is not made (log says it's done - but it does not work as if nothing happend). As well as supplying  `ConstructorArgsAdvice` as a second transformer breaks both (either with or without duplicating `.type(isPublic()....` signature for second added transformer.
2. The working example for Constructors I found as listed in the last chain with `new AsmVisitorWrapper.ForDeclaredMethods()`. Why is that?? All other trials with `.advice(` and without direct call to `builder.visit(` simply results nothing is done to constructors (though logs says `TRANSFORMED`)

**Comment by raphw** [comment]
Please reopen this question if you have further questions.
