### ISSUE TITLE
Unspecified annotation elements spuriously written out with default values.

### ISSUE THREAD

**Issue by eliasvasylenko** [raphw/byte-buddy#480]
If I define an annotation using the `AnnotationDescription.Builder` and omit some element vales which have defaults, I'd expect an annotation to be written out that does not explicitly give values for those elements. Instead, the defaults are lifted into the annotation which is written out.

In other words if I do something like the following:

    byte[] bytes = new ByteBuddy()
              .makeAnnotation()
              .name("test.Test")
              .annotateType(
                  AnnotationDescription.Builder
                      .ofType(javax.xml.ws.BindingType.class)
                      .build())
              .make()
              .getBytes();

I'd expect to get bytecode describing the following class:

    package test;
    
    @javax.xml.ws.BindingType()
    public @interface Test {}

But instead I get:

    package test;
    
    @javax.xml.ws.BindingType(value="")
    public @interface Test {}

Which is wrong.

This may not be a problem for runtime retention annotations, as there is no mechanism (I think?) for even determining whether an instance specifies a value equal to a default or does not specify a value. But unfortunately annotation processors *can* determine this, and in some cases it affects their behaviour. It is also at best unnecessary class file bloat.

Is there a workaround for this? Can I write an annotation out without having the default values explicitly repeated?

**Comment by eliasvasylenko** [comment]
A workaround is to create a new `TypeDescription` to pass into the `AnnotationDescription.Builder.ofType()` invocation, containing only the elements you wish to provide values for, rather than passing in the loaded class.

**Comment by raphw** [comment]
The problem here is that Java does not offer an API to distinguish if a value comes from an annotation default or by explicitly setting it, as you said. 

You can therefore configure an `AnnotationValueFilter.Factory` on your Byte Buddy instance. Try

```java
new ByteBuddy()
  .with(AnnotationValueFilter.Default.SKIP_DEFAULTS)
```

and you should get the desired results. You can also filter the values manually by implementing your own factory.

**Comment by eliasvasylenko** [comment]
Sorry I'm probably missing something being unfamiliar with ByteBuddy and it's implementation/general philosophy, but I'm not seeing why it should matter that Java doesn't offer this API.

Ultimately from a user's perspective it looks like the bytecode is being generated from a `AnnotationDescription` not an annotation instance, and the user certainly feeds enough information into the builder to determine which values are explicit, so it's surprising to see that this information is discarded somewhere along the way.

Is it that you're materialising the `AnnotationDescription` into an actual instance of an annotation first and then generating bytecode from that? Otherwise I don't see why the `AnnotationDescription` can't retain this extra information regardless of whether the Java API does.

That said, for my purposes the `SKIP_DEFAULTS` filter should work great, so thanks for pointing me towards that!

**Comment by raphw** [comment]
`AnnotationDescription`s can define any type of annotation, a loaded one, a parsed one and a synthetic one that was created with a builder. The idea was that all of those representations are equivalent and since the loaded one - which is a fairly major case - does not support a distinction, there is not currently an API for it.

But you are right, this could be solved different and I will consider this case for a future version.

**Comment by eliasvasylenko** [comment]
Ah I understand, so it's about having parity between representations, that's reasonable. So the problem is the lack of parity between the things being represented. Do consider as another data point that the standard `TypeMirror` API for reflecting over unloaded types *does* give access to this information.

**Comment by raphw** [comment]
I think the type mirror parses code as files? The `TypePool.Default` could therefore access this information but for loaded type, a byte representation of a class file might not be available.

**Comment by eliasvasylenko** [comment]
Sure I realise that, but an `AnnotationDescription` is also supposed to be able to represent a parsed annotation, no? I do get the value of an abstraction only implementing the *intersection* of the features of its different forms rather than the *union*, if you can get away with it, but in this case I think making a best-effort to provide the extra information where available could still make for a pretty seamless abstraction over the lot.

Anyway I don't want to harp on about it, thanks for considering it for the future.

**Comment by raphw** [comment]
Yes, what I consider is adding a property such as `getValueType` that returns a value of `EXPLICIT`, `DEFAULT` or `UNKNOWN` then you can use the information if it is available.

I am tracking this here: https://github.com/raphw/byte-buddy/issues/482
