### ISSUE TITLE
Bytebuddy Gradle plugin fails on kotlin inline reified lambda

### ISSUE THREAD

**Issue by DALDEI** [raphw/byte-buddy#488]
First time trying the Bytebuddy gradle plug.  I copied the example, placed in my buildSrc/.. directory
and installed into build.gradle to see what happens.
`
> Cannot transform type: nexstra.portal.model.CampaignsService$$special$$inlined$makeCache$1
`

This is even if there are no targets to transform, it is failing searching for targets.
The culprit kotlin code is one of these 2 overloads.
```

  internal val client_cache = makeCache<Int, Client?> {
    _getClient(it)
  }

  internal val campaign_cache = makeCache<Int, Campaign?> {
    _getCampaign(it)
  }

```
which in turn call 
```
inline fun <reified K,reified V> makeCache(noinline loader: (K) -> V ): Cache<K, V> = object : Cache2kBuilder<K,V>() {}.init(loader)
```

Stack trace:

> 
> Caused by: org.gradle.api.GradleException: Cannot transform type: nexstra.portal.model.CampaignsService$$special$$inlined$makeCache$1
>         at net.bytebuddy.build.gradle.TransformationAction.processClassFile(TransformationAction.java:244)
>         at net.bytebuddy.build.gradle.TransformationAction.processDirectory(TransformationAction.java:199)
>         at net.bytebuddy.build.gradle.TransformationAction.processDirectory(TransformationAction.java:197)
>         at net.bytebuddy.build.gradle.TransformationAction.processDirectory(TransformationAction.java:197)
>         at net.bytebuddy.build.gradle.TransformationAction.processDirectory(TransformationAction.java:197)
>         at net.bytebuddy.build.gradle.TransformationAction.transform(TransformationAction.java:156)
>         at net.bytebuddy.build.gradle.TransformationAction.processOutputDirectory(TransformationAction.java:103)
>         at net.bytebuddy.build.gradle.TransformationAction.execute(TransformationAction.java:67)
>         at net.bytebuddy.build.gradle.TransformationAction.execute(TransformationAction.java:29)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
>         at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
>         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
>         ... 106 more
> Caused by: java.lang.IllegalStateException: size = 0
>         at net.bytebuddy.matcher.FilterableList$AbstractBase.getOnly(FilterableList.java:108)
>         at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$TypeContainment$WithinMethod.getEnclosingMethod(TypePool.java:2990)
>         at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription.getEnclosingMethod(TypePool.java:2706)
>         at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getEnclosingMethod(TypeDescription.java:7074)
>         at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:228)
>         at net.bytebuddy.ByteBuddy.rebase(ByteBuddy.java:814)
>         at net.bytebuddy.build.EntryPoint$Default$1.transform(EntryPoint.java:62)
>         at net.bytebuddy.build.gradle.TransformationAction.processClassFile(TransformationAction.java:242)
>         ... 124 more
> 
> 
> 

Triggered by the transformer call:
```

public class HookInstallingPlugin implements Plugin {

    @Override
    public boolean matches(TypeDescription target) {
        return target.getName().endsWith("Test");
    }

    @Override
    public Builder<?> apply(Builder<?> builder, TypeDescription typeDescription) {
        return builder.method(isAnnotatedWith(anyOf(Test.class, Before.class, After.class))
                .or(isStatic().and(isAnnotatedWith(anyOf(BeforeClass.class, AfterClass.class)))))
                .intercept(MethodDelegation.to(SampleInterceptor.class))
                .implement(Hooked.class);
    }
}
```

**Comment by DALDEI** [comment]
Update:  commenting out those 2 culprits just defered the crash until the next one .. 

This one burried too deeply in nested blocks, lambdas and synthetic methods to bother debugging :)

Caused by: org.gradle.api.GradleException: Cannot transform type: com.nexstra.portal.view.CampaignElemDetail$show$2$1$1$1$1
```

  fun show(ev : CampaignElemsView,
           cv : CampaignMessageView) {
,,,,, way way down from here ... 
  
```
one of these thingies ...


```
        button("View Message...",{
          window("Message Content") {
            setModal(true)
            isResizable = true


```

**Comment by raphw** [comment]
It seems like Kotlin is creating some buggy Java class files here.

Could you try, from your application, to call the following code:

```java
Class<?> c= Class.forName("nexstra.portal.model.CampaignsService$$special$$inlined$makeCache$1");
Method m = c.getEnclosingMethod();
```

I wonder if you are getting an exception from the reflection API, as well.

**Comment by DALDEI** [comment]
Yes, after I wrote this I did more experimenting. 
Kotlin is being very 'creative' with bytecode. Not exactly 'buggy' -- in that as far as I can tell its all 100% legit - but its *not* 100% like javac would (or could) do.    There is a lot of effort for java compatibility but mostly on integration points not on the entire internals.   I.e. 'normal' java can call kotlin code usually without any changes, and visa versa.  But -- 'normal' meaning generally 'not including fancy-pants stuff' 
for that there are a few @Annotations  to force compatibility at the expense of feature.   
A simple example is functions with default parameter values like

 fun  doit(  with: String = "Default String" )

if you use @JvmOverloads  then it will create 2 copies of 'doit'  
   doit()
  doit(  String: with ) 

otherwise java source code cant call it easily (it generates a hidden function with an extra argument holding a bitmask for the defaulted parameters)

Similar with 'zero arg' constructors, statics,  package and class namings etc ..

In this case the 'class' is a lambda function that has no obvious parent,  and calling reflection on it does throw an exception -- although you do have to be quite creative to *identify* the culprit to call reflection on it in the first place ... seeing as it has no name and not necessarily assigned to a property, you have to go digging with javap or catch a live one to examine it to figure out its fqn -- otherwise it 'just works' .. unless you start recursively reflecting on the entire bytecode 

Suggestion:  (s)
A) 'Dont Crash Please'  - if you run into 'bogus' JVM stuff, be it from kotlin, scala, some other bytecode factory or a V(n+1) java -- fail nicely and skip over it .. and yes that is ambiguous and not necessarily the correct behaviour.   I would personally prefer simply skipping unexpected cruft over crashing -- especillay in a build plugin where one typically does not have access to the innards - but of course there are good reasons to not blindly stomp on ...

B) Driver Error: "dont do that" -- i.e. I shouldn't be blindly copying sample code that merrily reflects on the entire classpath -- if I had targeted the classes I wanted instrumented the error would not occur.
But then the reason I'm blindly copying sample code is I *dont know any better* !!! so I start with WTF lets try the sample code for the build plugin and see what it does 
<CRASH>

C) Maybe use samples that don't do exhaustive classpath searching -- at least for nice 'out of the box' experience.  As it was I had to dig quite a bit to get the sample to even run as bits of it didn't exist 
(presumably 'obvious' -- but then if its *really obvious* there would be no need for a sample.  So if you do have samples (please please)  then making them self contained and as unobtrusive as possible leads to better first-time experiences.   For something as complex as bytebuddy I can attest that a good 'first time' experience makes the difference between "Ok lets keep trying" vs "OMG That hurt, not doing THAT Again" -- its highly unlikely I would continue trying to learn something more realistic/difficult if I can't figure out how to get a published sample of the basics to run at all or easily )

**Comment by raphw** [comment]
I agree that unresolvable errors should be suppressed rather then to break the library, especially if it is such a non-essential property. At the same time, Byte Buddy tries to imitate the Java reflection API which every Java class needs to adhere.

Did you try to invoke the same method in the Java reflection API? What does happen when calling:

```java
Class.forName("nexstra.portal.model.CampaignsService$$special$$inlined$makeCache$1").getEnclosedMethod()
```

**Comment by DALDEI** [comment]
I single stepped in the intellij debugger into a similar call and it produced a similar error.
I will try this one explictly and report back. As noted it is not the only example of this type of 'odd' bytecode.
Some ad-hoc research and I find its not unique (among non-java jvm) similar in concept to synthetic methods in that the particular method orr reference is not reachable by language constructs  which is true in this case as well - the enclosedMethod doesn't exist but there is no non-reflection path to access it in the languages (or none that compile successfully).  This case is a inlined lambda which does not refernce the declaration point's parent nor the injected/callee point's parent. 

I cant intelligently speculate whether the kotlin team considers this a bug, feature, or irrelevant.   In any case its currently ill-defined and subject to implementation change (or just 'dont do that' )

Given 2 conflicting goals ('do not throw errors on legitimate but ill-behaving reflection code'  +  'do what java API does')  -- they may not both be achievable in the same api/method -- which leads to "How should one use bytebuddy in this use case"  --  
I'd be happy with 'don't do that' -- except I have only a foggy understanding of the impact - where else will similar code pop up?  That leads to it being significant effort/pain to attempt and be prepared for the unexpected and then the workarounds for each as they arise.   That is likely to take a good deal of domain knowledge the JVM and Bytebuddy -- precisely the domain knowledge I am using bytebuddy to attempt to avoid having to learn (at least all at once upfront).  Even if this is the *only* case, the 'cloud of ignorance' is a big deterrent to even start the attempt, and a big risk if new code becomes dependant then later to uncover some critical but unsolvable case. 

A possible solution -- identify a use pattern that avoids this problem altogether.  For example , If I ONLY looked for annotations on public classes perhaps it would skip over the messy parts ?

Another nieve idea -- a kind of 'Safe Traversing' API designed to 'Do as good as reasonably possible but avoid the messy parts and just ignore or report errors but dont stop'

Those may be the same thing --

**Comment by DALDEI** [comment]
( seperate issue maybe - will open if I find more info.  I have a simple case of dynamically creating a 'bean' which is working well except for nullability I ran into the following which is slightly related)

A little research:  
https://discuss.kotlinlang.org/t/where-can-i-find-information-about-the-bytecode-generation/2282

Im looking at what it would take to detect and generate basic kotlin property semantics, particularly the existence of 'nullable' and var vs val (getter+setter vs getter) such that the generated java class as interpreted as a kotlin class would be a bit closer then I have now.  There is a magic metadata field created for most kotlin classes which contains additional type information.

**Comment by raphw** [comment]
If the reflection API fails on a class, it is never safe as many tools can process code on the JVM. Many Java agents do and also debugging tools as the one you got to fail. Therefore, I really hope that the Kotlin team does consider this a bug as this breaks with the JVMS.

For your case, you can work around the problem by adding a matcher by name first that excludes such classes, e.g. classes that contain a part of a name. These classes are not parsed before any property is accessed what avoids the error.

I have considered adding such "language specific" whitelistings before but there are unfortunately too many and Byte Buddy would become impossible to maintain. Therefore, I strictly adhere the rule of "works like the reflection API" what I find a fair baseline.
