### ISSUE TITLE
Obscure documentation

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#49]
Hi Rafael,
i just noticed that you use quite an obscure example in the 3-1 = 2 comparison example in the main readme.
It is correct, but it evokes a wtf moment when you see that it substracts hash codes. Is that intended, or shall I send a PR to make that less magical?

**Comment by raphw** [comment]
Hi Fabian, you are right. If you can think of a better example, please send
a pull request!
Am 02.08.2015 12:49 vorm. schrieb "Fabian Lange" <notifications@github.com>:
