### ISSUE TITLE
Question: Can byte-buddy instrument byte array representation of a class?

### ISSUE THREAD

**Issue by Matthewacon** [raphw/byte-buddy#495]
I have multiple classes whose bytecode is contained in respective byte arrays at runtime. Unfortunately, due to the nature of the application, I cannot use a custom classloader to define these classes at runtime as any symbols contained and referenced within these classes would be unresolved upon definition. Can byte-buddy instrument a class from strictly from its bytecode? For example:

**Comment by raphw** [comment]
Have a look at AgentBuilder and the Instrumentstion API. Is tgat what you are looking for?

**Comment by raphw** [comment]
I am closing this for now, please reopen if you have further questions.

**Comment by Matthewacon** [comment]
I am using the AgentBuilder and Java Instrumentation APIs for several things in a Java Agent at the moment, however, it is not what I am looking for. I've solved my problem by implementing a classloader that accepts a set of `byte[]`s and recursively attempts to define them as classes, with a 3-pass tolerance. However, this approach is slow and does not scale well for large sets of classes. Further, it requires that all dependencies of said classes be either present on the classpath, or accessible from the classloader. Compounded with the restrictions imposed by the JVM, such as disallowing changes to the schema of a class, the resulting solution to my problem turned out to be horrifically slow and all but a dysfunctional mess. For these reasons, I asked if byte-buddy was able to instrument classes that *are not defined on the target JVM instance* but rather represented by a `byte[]` at runtime. Searching through the `byte-buddy-dep` and `byte-buddy-agent` libraries yielded no such results, and I imagine that for a library written solely in Java, this is not possible, but I thought I'd still ask here. 

Diverging from the initial question a bit: if it is the case that this isn't possible, I'm considering expanding my JNI module to allow unrestricted changes to classes, including retransformations to existing classes, so long as the changes produce a valid class. Would you have any suggestions or recommendations?

Regards,
Matthewacon

**Comment by Vampire** [comment]
I don't think you got the question right and I would be interested too in an answer. :-)
Consider this:
```java
byte[] clazzBytes = classFileLocator.locate(name);
byte[] instrumentedClazzBytes = new ByteBuddy()
  . // what comes here?
defineClass(name, instrumentedClazzBytes, 0, instrumentedClazzBytes.length);
```

**Comment by Vampire** [comment]
Ah, I think I found it.
```java
ClassFileLocator simpleClassLocator = ClassFileLocator.Simple.of(name, clazzBytes);
byte[] instrumentedClazzBytes = new ByteBuddy()
  .redefine(TypePool.Default.of(simpleClassLocator).describe(name).resolve(), simpleClassLocator)
  .whatever()
  .make()
  .getBytes();
```
