### ISSUE TITLE
how can i retranfrom a class that loaded by bootstrap classloader

### ISSUE THREAD

**Issue by iaskwho** [raphw/byte-buddy#499]
**this is my code, but it doesn't work。 dont matched the class(java.lang.System)**
`  
final ElementMatcher.Junction<NamedElement> systemType = ElementMatchers.named("java.lang.System");
new AgentBuilder.Default()
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
                .type(systemType)
                .transform(new Transformer()) //my transformer
                .with(new Listener())
                .installOn(instrumentation);  

`

**Comment by iaskwho** [comment]
**when i added:**
 .ignore(none())
**it works**  but why.......

**Comment by raphw** [comment]
As Fabian said. Without any ignore matcher, you are likely to run into performance issues.

**Comment by iaskwho** [comment]
thank you , but how to include matching @CodingFabian

**Comment by raphw** [comment]
You have to define an ignore matcher that is differrent from the default:

```java
.ignore(ElementMatchers.any(), ElementMatchers.isBootstrapClassLoader())
```

You would have to define a similar matcher where the first instruction is less restrictive then `any()`.
