### ISSUE TITLE
Add OSGi manifest headers

### ISSUE THREAD

**Issue by mattbishop** [raphw/byte-buddy#5]
I'd like to use Byte Buddy in an OSGi application but cannot because the jar does not contain the necessary META-INF/manifest headers.

The easy way to add them is to use the maven-bundle-plugin.

**Comment by ui4j** [comment]
Hi,

We are unable to use bytebuddy for OSGi environments. Are you sure that Export-Package definition is correct?

```
Export-Package: !net.bytebuddy.jar.asm.*,net.bytebuddy.*
```

Related issue and comment:
https://github.com/ui4j/ui4j/issues/28#issuecomment-106741600

**Comment by raphw** [comment]
Not entirely sure. To be honest, I do not use OSGi, I only googled my way. I am going to have a look at it.

**Comment by CodingFabian** [comment]
I guys, i will fix this, but I want to get the requirements straigt. 
Right now only byte-buddy-agent produces valid osgi headers, however I assume this is not even included as bundle, because its a javaagent. This is not even a valid bundle (because it doesnt provide services) so I propose to remove it.
byte-buddy-dep and byte-buddy both do not produce osgi headers.

Could you please clarify which Classes you actually want to use form which jar?

**Comment by CodingFabian** [comment]
Update, i am building the 0.7 snapshot and the osgi headers are valid. i am able to load the bundle in karaf:
karaf@root()> bundle:install mvn:net.bytebuddy/byte-buddy/0.7-SNAPSHOT
Bundle ID: 53
53 | Active    |  80 | 0.7-SNAPSHOT   | Byte Buddy (without dependencies)
karaf@root()> bundle:info 53

Byte Buddy (without dependencies) (53)

**Comment by raphw** [comment]
The current version or your build?

**Comment by CodingFabian** [comment]
without my changes. It works, but as sent to you via skype, a really correct header is pretty long, due to the amount of packages and tangling you have there

**Comment by CodingFabian** [comment]
Here are the new manifest files my upcoming PR will produce. Would these work for you?
https://gist.github.com/CodingFabian/35f727056830156b2756

**Comment by raphw** [comment]
Version 0.6.7 should have correct OSGi headers. Thanks @CodingFabian for fixing this!

**Comment by raphw** [comment]
On second look, it seems like the shaded POM is not longer overriding the original POM. The dependency remains declared...

**Comment by raphw** [comment]
Okay, I had to tweak the build a bit. The shade plugin does not play nice with the bundle plugin. I had to list the exports explicitly. It works with version 0.6.8.
