### ISSUE TITLE
Move ClassFileExtraction to main package for external consumer to use

### ISSUE THREAD

**Issue by wuchenwang** [raphw/byte-buddy#503]
We want to use the class to assist our testing with bytebuddyagent class, but having to copy/paste the class as it's in test packages, can it be moved so that we can simply reference it in our own test?

https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/test/java/net/bytebuddy/test/utility/ClassFileExtraction.java

**Comment by raphw** [comment]
Use `ClassFileLocator.ForClassLoader.read(...).resolve()`. I am planing to remove this utility at some point.
