### ISSUE TITLE
Advice doesn't correctly check types [?]

### ISSUE THREAD

**Issue by Jezza** [raphw/byte-buddy#511]
I'm trying to create a mock system, and we have some weird stuff where we know an object is of two interfaces, but can't represent it with fields, obviously, the JVM has no union types.
The only thought I had was generics, as they're erased, and the usages get cast to the type they need.

Is it possible to do something similar in ByteBuddy?

![selection_020](https://user-images.githubusercontent.com/4224088/43761731-38883d7a-9a26-11e8-97db-d7213e3f6238.png)

As confusing as that image is, I'll try to summarise it.

We have one main interface called RepoModule.
Because we deal with a serialise web framework, and because the modules are stored statically, we basically just pass around facades of those module, when they get serialised, they just store their id, and pull it back out again.

We're prototyping a services system, and you specify an interface that you want the module to implement if it implements the service.
So this code just generates the same style facade.
It stores the module, and when serialised, it'll just store the id.
The problem is storing both the service interface and the module interface.
If I change the field type to the service interface they declare, then the serialisation advice check fails.
If I don't change it, the check confirming that the delegation is valid fails, because well, it's a different type.
It's understandable.

I can think of a workaround, and just make the generic service interface extend the RepoModule, but it won't be as simple as that, because the same interface we use for offering interface type services, you can also use to declare classes that can be created as services, meaning your services can have some state, such as a search query.

It might be possible to make the interface half of services to implement the RepoModule interface as well, but that seems... meh...

I'm just wondering if there's any way to insert automatic casts, or get around this problem.

**Comment by Jezza** [comment]
Weirdly, even though the service interface extends RepoModule, ByteBuddy still complains that the types can't be used together.

**Comment by Jezza** [comment]
`Cannot assign interface de.bps.onyx.repo.interfaces.RepoModule to private transient de.bps.onyx.repo.services.LicenseModuleService de.bps.proxy.LicenseModuleServiceFacade$$roiG8ws2.root`

LicenseModuleService implements RepoModule.

**Comment by Jezza** [comment]
Oh, wait, it's the other way around?
it's trying to assign the RepoModule to the field...
But where?
I commented out the internal code, just so it removes all of that stuff.

Ah, it definitely looks like it's trying to align the field type with the parameter type, as I told it to.
That makes sense.
And it's failing.

**Comment by raphw** [comment]
Do you have a stack trace?

**Comment by Jezza** [comment]
So, after mucking around with this for an hour or so, I can safely say, the exception that was thrown makes sense.

Just because I have `RepoModule`, it doesn't mean I have a `LicenseModuleService`.

I ended up solving it doing a shitty reflection hack with a super class, but I think a better solution would be dynamic advice.
Or something similar to it.
I have the type of field at the time of construction, but I can't give the advice that information.

If I could do something like, but instead of T, I could declare a placeholder that could be swapped out by ByteBuddy:

![selection_021](https://user-images.githubusercontent.com/4224088/43773679-cfc21a60-9a46-11e8-9dda-c628973c91fc.png)

**Comment by raphw** [comment]
You can always implement a custom annotation binding for a value and you can use dynamic typing in the annotation value where Byte Buddy simply attempts a type cast.

**Comment by Jezza** [comment]
Hm, I don't think I quite understand how to get that working.
I tried:

![selection_024](https://user-images.githubusercontent.com/4224088/43777947-97833158-9a54-11e8-94e5-af98d4c80922.png)

But that doesn't work.

So from what I could work out, I need to bind the first parameter to the type of the service AND I need to also bind it to the field.

I just realised that using the `FieldAccessor` is incorrect.
I don't know how to refer to the field that is inside of this class.

**Comment by raphw** [comment]
You can bind a field value via `Advice.withCustomConfiguration().bind(SomeAnnotation.class, ...)`. Then you can cast types etc. as long as your representation is possible in byte code.

Alternatively, you can configure `Assigner.Typing.DYNAMIC` for `@FieldValue` or `FieldAccessor` to make Byte Buddy apply a type cast.

**Comment by Jezza** [comment]
Using `Assigner.Typing.DYNAMIC` seems to have done the trick.
Thanks for the help.
