### ISSUE TITLE
Injecting created classes to provided classloader doesn't work (starting 1.8.4)

### ISSUE THREAD

**Issue by kwart** [raphw/byte-buddy#513]
We are upgrading from byte-buddy 1.6.12 to 1.8.17 due to #510 and we realized the injection of new classes to provided classloader stopped to work. The investigation shows the problem starts in byte-buddy version 1.8.4.

**Reproducer**
```java
public class App {
    public static void main(String[] args) throws ClassNotFoundException {
        ClassLoader classLoader = App.class.getClassLoader();
        Class<?> fooClass = new net.bytebuddy.ByteBuddy()
                .subclass(java.util.Map.class)
                .name("com.test.MyMap")
                .make().load(classLoader).getLoaded();
        classLoader.loadClass(fooClass.getName());
    }
}
```

**Expected result**
Program finishes without any issue. It's true up to 1.8.3.

**Actual result**
From 1.8.4 onwards we see CNF exceptions:
```
Exception in thread "main" java.lang.ClassNotFoundException: com.test.MyMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cz.cacek.test.App.main(App.java:11)
```

**Comment by raphw** [comment]
You do need to specify the injection strategy explicilty now (via `.load(classLoader, ClassLoadingStrategy.Default.INJECTION)`.

Oracle has made it clear that this strategy will no longer be supported on the long run, therefore Byte Buddy now defaults to loading the class in a new class loader.

The way to injection is to provide a method handle lookup on VMs Java 9+. I have blogged about this in the past: http://mydailyjava.blogspot.com/2018/04/jdk-11-and-proxies-in-world-past.html

**Comment by kwart** [comment]
Great! Thanks @raphw for the explanation. We'll fix the usage on our side.
