### ISSUE TITLE
Add convenience methods for LambdaMetaFactory to InvokeDynamic

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#518]
Similar to ConstantDyanmic, the JVM built-ins should be supported more easily.

**Comment by ncomet** [comment]
Just to avoid duplicates, isn't this the same issue as https://github.com/raphw/byte-buddy/issues/391 ?

**Comment by raphw** [comment]
Very much, have not thought of it. Thanks for pointing that out.
