### ISSUE TITLE
Advices for Advices

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#520]
Advices lets us inject code `OnMetodEnter` and `OnMethodExit` which basically enables to define behavior once and inject it to multiple locations.

But what if I want to do some generic handling in some of my `OnMetodEnter` and `OnMethodExit` advices? Is that currently possible? Can I apply `OnMetodEnter` and `OnMethodExit` advices to another `OnMetodEnter` advice, for example?

**Comment by felixbarny** [comment]
I guess you could probably use the Byte Buddy maven plugin to enhance all the advice methods which have a special annotation, for example.

**Comment by raphw** [comment]
Yes, this would work, but you can equally apply several advices per instrumented type with same results.

**Comment by felixbarny** [comment]
> you can equally apply several advices per instrumented type with same results

But applying an `OnMethodExit` advice to an `OnMetodEnter` advice i.e. clean up stuff after the `OnMethodExit` has been executed would probably not work then, right?

Even if you apply three `OnMetodEnter` advices, one for generic pre-processing one for the actual `OnMetodEnter` advice and one for generic post-processing of the actual `OnMetodEnter` advice, you can't make sure the generic post-processing is executed with finally semantics (in case the actual `OnMetodEnter` advice throws an exception).

**Comment by raphw** [comment]
You are right, if you want to guard something that happens in your advice methods, you can advice your advice.

This would best be done using the build plugin to avoid additional runtime overhead.
