### ISSUE TITLE
Allow using element matchers on MethodCall invocation target

### ISSUE THREAD

**Issue by mibac138** [raphw/byte-buddy#524]
For example the code below will fail with `IllegalStateException: class X does not define exactly one virtual method for name(equals(length))`. The desired result though is for the element matcher to search for `length` in `String`, not the current type. This enhancement applies to `onField`, `onArgument`, `onMethodCall` and others.

```java
new ByteBuddy()
    .subclass(Object.class)
    .defineField("string", String.class)
    .defineMethod("stringLength", int.class)
    .intercept(MethodCall.invoke(named("length")).onField("string"))
    .make();
```

I am willing to implement this given you approve of this.

**Comment by raphw** [comment]
Sure, sounds about right. Looking forward to a PR.
