### ISSUE TITLE
Adding a declaresMethod matcher to a AgentBuilder#type matcher makes method matchers fail

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#530]
I'd like to use `declaresMethod` matchers before `hasSuperType` matchers in order to pre-filter classes that don't declare the method I want to instrument before applying the `hasSuperType` matcher, which is more expensive.

Unfortunately, using the  `declaresMethod` matcher seems to mess with the method matcher (`net.bytebuddy.agent.builder.AgentBuilder.Transformer.ForAdvice#advice(net.bytebuddy.matcher.ElementMatcher<? super net.bytebuddy.description.method.MethodDescription>, java.lang.String)`)

Example:
https://github.com/elastic/apm-agent-java/blob/6d4a28535d822f731a227ec026e597d57629e801/apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/servlet/AsyncInstrumentation.java#L75-L77

When adding `.and(declaresMethod(any()))` after line 76, the test `co.elastic.apm.servlet.AsyncServletTest#testAsync` fails. The logs tell me that I still get a type match, but I don't get a method match anymore.

**Comment by raphw** [comment]
I just tried it using 

```java
return not(isInterface())  
  .and(nameContains("Request"))
  .and(declaresMethod(any()))
  .and(hasSuperType(named("javax.servlet.http.HttpServletRequest")));
```

and the tests still succeed. Could you investigate this a little closer?

**Comment by felixbarny** [comment]
Hey Rafael,

thanks a lot for having a look and sorry for the faulty instructions.

The error happens when you remove the `.and(nameContains("Request"))` matcher i.e.

```
return not(isInterface())
  .and(declaresMethod(any()))
  .and(hasSuperType(named("javax.servlet.http.HttpServletRequest")));
```

Some observations:

* When adding `org.eclipse.jetty.server.Request.class.getName();` to the first line of `co.elastic.apm.servlet.AsyncServletTest#setUp`, the test succeeds. This loads the class before registering the transformers, which makes Byte Buddy retransform this class (instead of transforming when it is loaded).
* Reading the methods of all classes by calling `and(declaresMethod(any()))` seems to mess up something.

Questions:

* When retransforming a class, Byte Buddy uses reflection instead of parsing the class byte array, right?
* What happens when calling something like `and(declaresMethod(named("startAsync"))`? I assume byte buddy lazily parses the class file to get the required information. But does it parse the whole bytecode of the method or just enough to get the method descriptor/method name?
* Would you consider prepending a `declaresMethod(named(...))` matcher before a `hasSuperType(named(...))` matcher a good idea in order to avoid super type lookups for types which don't declare the methods I want to instrument?

**Comment by raphw** [comment]
I see, the problem is class loading circularities. If you load a class during a class file transformation, this class will not be transformed. As a matter of fact, Byte Buddy has a mechanism for that, called a `CircularityLock` to suppress any class loading that occurs during a transformation. If it did not do this, the JVM would yield a `CircularityError` if the currently transformed class was reached via the load chain.

To avoid this, you need to avoid all class loading, for example by using Byte Buddy's pool-only descriptor strategy where the library parses byte code even if a loaded class is available.

**Comment by felixbarny** [comment]
What is the reason that Byte Buddy does not retransform those classes? Would that be too slow?

So using a `declaresMethod` might not be the best idea because it causes loading of classes during transformation and those classes can't be transformed then. Or would you suggest just using the pool-only descriptor strategy and do use `declaresMethod` before `hasSuperType`?

**Comment by CodingFabian** [comment]
ByteBuddy would. Its the instrumentation API implementation that doesn't trigger instrumentation of classes loaded during instrumentation.

**Comment by raphw** [comment]
Imagine what happened otherwise: the agent was loaded for the first time under transformation and TypeDescription was loaded. Doing so, TypeDescription was described as a type description recursively and things blew up.

**Comment by felixbarny** [comment]
I get that, but wouldn't it be possible to use `java.lang.instrument.Instrumentation#retransformClasses` to retransform the classes, which were loaded during a `java.lang.instrument.ClassFileTransformer#transform` invocation? The prerequisete would be calling `net.bytebuddy.agent.builder.AgentBuilder#disableClassFormatChanges`, of course.

**Comment by raphw** [comment]
Yes, but you would need to get hold of the information of whuch classes were loaded. This is not trivial since the transformer is not called. One way is to keep a reference on what classes were transformed and to check the list of all loaded classes occasionally.

This does however burn quite a lot of cycles.

**Comment by felixbarny** [comment]
Ok, makes sense, thanks.

Any advice (pun intended) in regards to whether you think using a `declaresMethod(named(...))` matcher before a `hasSuperType(named(...))` makes sense at all?

**Comment by raphw** [comment]
I would only add it if you are certain that a type is within a type hierarchy. Byte Buddy caches type descriptions if you set up your builder correctly (you did with Stagemonitor) so the parsing step in case of unloaded types is cheap. Hierarchy checks with loaded types are also dead-cheap so getting hold of delcared methods really only pay off if you can avoid (re)transforming types unneccesarily.

**Comment by felixbarny** [comment]
>  Byte Buddy caches type descriptions if you set up your builder correctly

I (or rather a customer) once ran into an OOME because of the type cache pool size, that's why I'm a bit cautious to set up that cache. Back then, I fixed it with prepending a matcher like `nameContains("Servlet")` but that can yield false negatives.

**Comment by raphw** [comment]
I see that can be a problem, especially in small environments, but in the end its a trade off between speed and memory as in any application.

**Comment by yaohwu** [comment]
> I see, the problem is class loading circularities. If you load a class during a class file transformation, this class will not be transformed. As a matter of fact, Byte Buddy has a mechanism for that, called a `CircularityLock` to suppress any class loading that occurs during a transformation. If it did not do this, the JVM would yield a `CircularityError` if the currently transformed class was reached via the load chain.
> 
> To avoid this, you need to avoid all class loading, for example by using Byte Buddy's pool-only descriptor strategy where the library parses byte code even if a loaded class is available.

Same problem happened to my project.
My solution is to call `target.getDeclaredTypes()` and `target.getDeclaredFields()` to load all the classes used by the target class during the matcher executing.
