### ISSUE TITLE
Plugin Gradle configuration: How to pass arguments to plugin?

### ISSUE THREAD

**Issue by quarante-2** [raphw/byte-buddy#538]
Is there a more elegant way? Thanks in advance!
```groovy
byteBuddy {
    transformation {
        plugin = 'FooPlugin'

        def arg = new net.bytebuddy.build.gradle.PluginArgument()
        arg.index = 0;
        arg.value = 'Foo'

        arguments = [arg]
    }
}
```

**Comment by raphw** [comment]
Good point, I will add a constructor that takes both arguments.

**Comment by raphw** [comment]
I added a constructor which would allow:
```groovy
new net.bytebuddy.build.gradle.PluginArgument(0, 'Foo')
```
I am not sure if this allows you to apply the instance as a closure. Any suggestions?

**Comment by quarante-2** [comment]
Good! But I think it cannot be applied as closure (I haven't tested it however). Following the current dsl style, I think it should look like:
```groovy
byteBuddy {
    transformation {
        plugin = 'FooPlugin'
        argument { value = 'Foo' }
        argument { index = 1; value = 'Bar' }
        argument {
            index = 2
            value = 'Baz'
        }
    }
}
```
I think that this could be supported by adding a method, that takes a closure and adds the argument to the list, in the `Transformation ` class. Similar to how it's done for the transformations in `ByteBuddyExtension `.
```java
   // Note that the list must be initialized and both getter/setter must be declared for it.
   public void argument(Closure<?> closure) {
        PluginArgument argument = (PluginArgument) project.configure(new PluginArgument(), closure);
        arguments.add(argument);
    }
```
Note that I'm not sure if that is the recommended way of doing this, I just looked at the transformation code.

Thanks!

**Comment by quarante-2** [comment]
It works - great! Note that direct assignments like `arguments = [...]` do not work anymore, but that's fine.

**Comment by raphw** [comment]
I think I prefer the style to be consistent throughout usages. I will release this within the next few weeks with the final ASM 7 version.
