### ISSUE TITLE
VerifyError:  Bad access to protected data in invokevirtual

### ISSUE THREAD

**Issue by pdoro** [raphw/byte-buddy#539]
I'm getting a java.lang.VerifyError when trying to subclass Spring's [RestTemplate](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html). My goal is to intercept the [postForEntity](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html#postForEntity-java.lang.String-java.lang.Object-java.lang.Class-java.lang.Object...-) method, for the rest of the methods I'm delegating them to a instance of RestTemplate

My byte buddy code looks like this:

```java
Class<? extends RestTemplate> clazz = new ByteBuddy()
                            .subclass(RestTemplate.class)
                            .method(isDeclaredBy(RestTemplate.class))
                            .intercept(MethodDelegation.to(bean, RestTemplate.class))
                            .method(
                                    named("postForEntity")
                                    .and(takesArgument(3, Object[].class))
                                    .and(isPublic())
                            )
                            .intercept(MethodDelegation.withDefaultConfiguration()
                                   .withBinders(Pipe.Binder.install(Function.class))
                                   .to(interceptor))
                            .make()
                            .load(getClass().getClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
                            .getLoaded();

clazz.newInstance();
```

And the interceptor in an instance of:

```java
@Slf4j
public class MyInterceptor extends AbstractBehaviouralInterceptor {

    private RestTemplate restTemplate;

    @RuntimeType
    public Object intercept( @Pipe Function<RestTemplate, Object> pipe ) 
    {
        log.debug("Intercepting call to restTemplate, applying {} behaviour", behaviour);

        switch ( behaviour ) {

            case TIMEOUT:
                throw new ResourceAccessException("Mocked timeout");

            case ERROR_RESPONSE:
                return new ResponseEntity<>(
                        new Object(...),
                        HttpStatus.CONFLICT
                );

            case DEFAULT_BEHAVIOUR:
                return pipe.apply(restTemplate);

            default:
                throw new IllegalStateException("Invalid behaviour") ;
        }
    }

    public void setRestTemplate(RestTemplate restTemplate) {
        this.restTemplate = restTemplate;
    }
}
```

As shown in the code I'm using a `@Pipe` to forward the call to the wrapped implementation and `@RuntimeType` to "avoid" the generic return type (`ResponseEntity<T>` where `T` is provided to the method as argument).
The error I'm seeing is this one:

```java
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restTemplate' defined in class path resource [com/ing/fontvella/backend/mobile/payment/configuration/SecurityConfig.class]: Initialization of bean failed; nested exception is java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    org/springframework/web/client/RestTemplate$ByteBuddy$jWyaTIyT.headersExtractor()Lorg/springframework/web/client/ResponseExtractor; @3: invokevirtual
  Reason:
    Type 'org/springframework/web/client/RestTemplate' (current frame, stack[0]) is not assignable to 'org/springframework/web/client/RestTemplate$ByteBuddy$jWyaTIyT'
  Current Frame:
    bci: @3
    flags: { }
    locals: { 'org/springframework/web/client/RestTemplate$ByteBuddy$jWyaTIyT' }
    stack: { 'org/springframework/web/client/RestTemplate' }
  Bytecode:
    0x0000000: b200 0fb6 0091 b0                      
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 27 common frames omitted
Caused by: java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    org/springframework/web/client/RestTemplate$ByteBuddy$jWyaTIyT.headersExtractor()Lorg/springframework/web/client/ResponseExtractor; @3: invokevirtual
  Reason:
    Type 'org/springframework/web/client/RestTemplate' (current frame, stack[0]) is not assignable to 'org/springframework/web/client/RestTemplate$ByteBuddy$jWyaTIyT'
  Current Frame:
    bci: @3
    flags: { }
    locals: { 'org/springframework/web/client/RestTemplate$ByteBuddy$jWyaTIyT' }
    stack: { 'org/springframework/web/client/RestTemplate' }
  Bytecode:
    0x0000000: b200 0fb6 0091 b0                      
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:99)
	at net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:162)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:81)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4247)
	at com.ing.fontvella.backend.mobile.payment.configuration.DebugConfig$1.postProcessAfterInitialization(DebugConfig.java:69)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	... 37 common frames omitted
  ```

I'm not used to this kind of error but it seems that when spring tries to assign ByteBuddy proxy instance to the `RestTemplate` bean if fails beacause of the [`headersExtractor`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html#headersExtractor--)
method which is protected. Oddly enough, the same code run smoothly on my local machine using:

> java version "1.8.0_171"
> Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

but failed when deployed on the server using Oracle jre 8. This same behaviour happened when I tried to intercept the overloaded method `postForEntity` using less element matchers (just by name)

Any idea?

**Comment by raphw** [comment]
I have to wrap my head around this but I think that the pipe should accept accept the original type, not the proxy type. Could you run your app with `-Dnet.bytebuddy.dump=/some/folder` and send me the outputs?

**Comment by raphw** [comment]
The bytecode of the failed method is
getstatic <field>
invokevirtual <method>
areturn

That is the code of the pipe proxy, it seems. When sending me the classes, please also reattach a stack trace such that I can map the message to the random suffixes.

**Comment by raphw** [comment]
Could you also double check that there is no other form of weaving on the server where the error occurs, maybe by a Java agent. You can make sure of this by specifying the method to delegate to on:

(MethodDelegation.withDefaultConfiguration()
                                   .withBinders(Pipe.Binder.install(Function.class))
                                   .filter(named("intercept").and(takesArguments(Function.class))
                                   .to(interceptor)

**Comment by pdoro** [comment]
I'm trying to get the dump for the environment where the exception ocurred but it might not be possible due to security restrictions. Meanwhile I'll attach the dumps that ByteBuddy produce on my local env hoping the will help you.

I don't get what you mean about the stack trace. Do you mean the stack trace of the thread that crashes? If so, the only stack I have is the one I posted before. If not, please explain me how I can get this stack trace.

[dump.zip](https://github.com/raphw/byte-buddy/files/2441924/dump.zip)

**Comment by raphw** [comment]
So it does crash on your local machine? I thought this only happened on the server.

**Comment by pdoro** [comment]
No, the crash only happens on the server but I might not be able to extract the dump for the server (k8s env with secured dockers) so I attached a dump from my local machine where it does run (maybe it shed some light)

**Comment by pdoro** [comment]
I guarantee you there is no external java agent weaving the code. The only bytecode generation apart from bytebuddy is the one performed by cglib and spring but that does not apply to RestTemplate

**Comment by raphw** [comment]
I fully understand, I am sure that I can find out either way. Thanks for the dump, I am pretty certain that it is connected to cglib adding something that distracts the location mechanism. Could you try out filtering all methods but the delegation target? If that works, I pretty much know where to look.

**Comment by pdoro** [comment]
What does you mean by accident? You mean that the protected call should be performed on the subclass implementation rather than on the provided bean?

**Comment by raphw** [comment]
No, it is simply not allowed to invoke a protected method on another instance of a super class. Consider:

```java
package foo;
public class Foo { protected void foo() { } }

package bar;
public class Bar extends Foo {
  public static void main(String[] args) { new Foo().foo(); }
}
```

The call in `Bar` is not allowed as it comes from a different package. You might argue that the proxy is in the same package but since you are using a wrapper strategy, the runtime packages will not be equal. If you choose to use the injection strategy, I am sure it would work, too.

The JVM is required to throw an `IllegalAccessError` what is spec compliant. Seems like the Docker container runs a version that has a bug violating the spec where a verifier error is thrown instead.

**Comment by pdoro** [comment]
Ok, now I get it. Is it possible for ByteBuddy to throw an exception if you try to delegate protected invocations to an object if the strategy selected does not allow this behaviour or the package doesn't match the original one?

**Comment by raphw** [comment]
As said, it is impossible to know for Byte Buddy what class loader is targeted. And there might even be an incompatible class change during generation and load. I will add something that throws an error if the method is at minimum package-private and in a different package what you can validate statically. Therefore, the best solution for you is to exclude protected methods from matching by setting `.method(isDeclaredBy(RestTemplate.class).and(isPublic()))`. Or you can use the injection strategy where the generated class would actually be capable of intercepting the protected methods.

**Comment by pdoro** [comment]
Ok then, thank you very much for your time and guidance. You can close the issue.

**Comment by raphw** [comment]
As a matter of fact, I already have a check for this, I just overlooked it.

The only reason that the delegation works is that the generated class and the base class are in the same compile-time package. The problem is that the runtime-packages are different where the JVM is supposed to throw an IllegalAccessError lazily but breaks in the verifier.

Out of curiosity, what exact JVM version are you running in the container?

**Comment by pdoro** [comment]
The JVM version is:

> java version "1.8.0_121"
> Java(TM) SE Runtime Environment (build 1.8.0_121-b31)
> Java HotSpot(TM) 64-Bit Server VM (build 25.121-b31, mixed mode)

**Comment by perlun** [comment]
See also https://github.com/raphw/byte-buddy/issues/1576, which discussed a similar (but not identical problem).
