### ISSUE TITLE
Byte Buddy is not working with PowerMock

### ISSUE THREAD

**Issue by juherr** [raphw/byte-buddy#54]
Using Byte Buddy and PowerMock throws a `ClassNotFoundException`

I uploaded the test case and the stacktrace on my gist https://gist.github.com/juherr/69b3f7604f03c1946207

I suppose the problem is liked to the `MockClassLoader` from PowerMock but  I've no idea how to fix it.

**Comment by raphw** [comment]
I am currently on vacation, but I will look at it first time I am back. First suspicion: Byte Buddy is not currently configured to keep a reference to the generated class'es byte code after it is first loaded. Try the manifest version of the wrapper strategy. I guess, power mock requires explicit access to the byte code!

**Comment by raphw** [comment]
I had a look at it. The error lies with Power Mock, in my opinion. During class loading, Byte Buddy's class loader is queried for the super class of the runtime generated class `SampleClass`. This is standard class loader behaviour and cannot be changed.

This class is however not longer available. The error breaks down to:

```java
@Test
public void testFoo() throws Exception {
  sample.getClass().getClassLoader().loadClass(sample.getClass().getName());
}
```

what causes the same error, even without using Byte Buddy. From PowerMock's `MockClassLoader` I can see that there are loading exceptions for specific libraries, like e.g. cglib or javassist to presumeable prevent the same problem. The would need to include Byte Buddy in this list, I assume.

**Comment by juherr** [comment]
On my side, I succeed to remove my dependency to PowerMock. So no more problem :)

Do you want I open a issue on PowerMock, or you take the point?

**Comment by raphw** [comment]
If you have the minutes, please report it to PowerMock. I am still officially on vacation, I can alternatively do it afterwards.
