### ISSUE TITLE
Use NIO2 for jar and file operations, if available.

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#540]
This would be especially beneficial for jar injection where only few items need to be replaced or inserted.

**Comment by breaklulz** [comment]
I am excited for this. I am having a hard time finding information on how to use Byte Buddy with jars

For example, how do you load a jar into the system class loader?

I've already figured out how to load a jar into a `TypePool` using a `ClassFileLocator`

I'm getting `Cannot resolve type description for java.lang.Object` errors when trying to do things with the jar's `TypePool`

**Comment by raphw** [comment]
I have decided to only use some NIO2. For jar files, this is sometimes simply impossible since the ZipFileSystem of NIO2 requires directory entries. For the MANIFEST.MF file, this does not work as it must be the first entry while NIO2 would place the directory entry first. I use it for file copies, though.

As for your questions, I have answered them on the mailing list.
