### ISSUE TITLE
Lost parameter annotation when byte-buddy is used to enhance a subclass.

### ISSUE THREAD

**Issue by nize1989** [raphw/byte-buddy#542]
byte-buddy version:1.9.1
I use this version to enhance my class, which extends other one. In the superclass，there is  a method which has a parameter annotation,**@RequestBody**.But when i use the way as fellow to enhance the subclass,something wrong happened.
![5](https://user-images.githubusercontent.com/31175234/46644790-67279800-cbb4-11e8-9a8c-7f0af1eefa9a.jpg)
![4](https://user-images.githubusercontent.com/31175234/46645010-5cb9ce00-cbb5-11e8-9305-231871dd10e8.jpg) 

The result of enhanced subclass:
![2](https://user-images.githubusercontent.com/31175234/46644819-87575700-cbb4-11e8-965f-eac609369cc1.jpg)
the superclass:
![1](https://user-images.githubusercontent.com/31175234/46644901-e4530d00-cbb4-11e8-9d76-0a4907e1b4bc.jpg)

the login method is not Override  by the subclass. but in the enhanced subclass the @RequestBody is lost.

**Comment by raphw** [comment]
Byte Buddy is doing what you are telling it to do. If a method is not declared by a class, it needs to be reimplemented. Java, by default, does not inherit annotations on virtual methods or subclasses, Byte Buddy mimics this behavior. You can either:

1. Decide to not override methods: Make your matcher more specific for that by also matchin `isDeclaredBy(typeDescription).and(...)`
2. Inherit annotations of overridden methods by `.attribute(AttributeAppender.ForInstrumentedMethod.INSTANCE`.

**Comment by nize1989** [comment]
thank you very mach, that's really very helpful.

**Comment by raphw** [comment]
Glad I could help.
