### ISSUE TITLE
NoClassDefFoundError when trying to load jar

### ISSUE THREAD

**Issue by breaklulz** [raphw/byte-buddy#543]
I am trying to load a jar into the system class loader, one of the interfaces the jar's main class implements fails to load

The jar's main class implements an interface lets say it's name is `testInterface`

When I attempt to `load()` the jar's main class I get these errors:

```
Exception in thread "main" java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
Caused by: java.lang.NoClassDefFoundError: testInterface
Caused by: java.lang.ClassNotFoundException: testInterface
```

Here's my code:

```java
ClassFileLocator locator = new ClassFileLocator.Compound(
	ClassFileLocator.ForJarFile.of(new File("path/to/jarfile")),
	ClassFileLocator.ForClassLoader.ofSystemLoader());

TypePool typePool = TypePool.Default.of(locator);
TypeDescription main = typePool.describe("main").resolve();

new ByteBuddy()
	.with(TypeValidation.DISABLED)

	.redefine(
		main,
		locator)

	.make()

	.load(
		ClassLoader.getSystemClassLoader(),
		ClassLoadingStrategy.Default.INJECTION)

	.getLoaded();
```

**Comment by raphw** [comment]
If the system class loader only gets the one class injected, then this will not work as the other classes are still missing from the system class path. You could rather create a new `URLClassLoader` that references the jar file and inject the class into this new class loader before loading any other class. Doing so, you are guaranteed to load the redefined class first without missing any references.

**Comment by breaklulz** [comment]
I like that idea. Here's my current attempt:

```java
URLClassLoader urlClassLoader = new URLClassLoader(new URL[] {
	new File("path/to/jarfile").toURL()
});

ClassFileLocator locator = ClassFileLocator.ForClassLoader.of(urlClassLoader);

TypePool typePool = TypePool.Default.of(locator);

new ByteBuddy()
	.with(TypeValidation.DISABLED)

	.redefine(
		typePool.describe("main").resolve(),
		locator)

	.make()

	.load(
		urlClassLoader,
		ClassLoadingStrategy.Default.INJECTION)

	.getLoaded();
```

Now I am getting these errors (remember `testInterface` is implemented by the `main` class):
```
java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
Caused by: java.lang.SecurityException: class "testInterface"'s signer information does not match signer information of other classes in the same package
```

The jar isn't signed..

**Comment by breaklulz** [comment]
I like that idea. I have a working prototype now. Had to use `ClassReloadingStrategy.Default.INJECTION`

Thanks for being patient with me
