### ISSUE TITLE
How do I replace certain things inside a method?

### ISSUE THREAD

**Issue by breaklulz** [raphw/byte-buddy#545]
This method I want to update doesn't return anything (it's a void)

Inside this method it sets variables inside other classes

I want to intercept it and tell it to set those variables to a hardcoded value

It can't be done with a `Target.class` delegation

I think I'm gonna need to use ASM for this part. I need to insert/update a local variable within the middle of the method I want to intercept

I guess what I'm asking is how do I use the ASM visitor with the Byte Buddy interceptor

**Comment by breaklulz** [comment]
```java
void test() {
/* stuff */

String thing = "";

if (case1) {
  thing = "case1"
}

if (case2) {
  thing = "case2"
}

if (case3) {
  thing = "case3"
}

if (thing.equals("")) {
  thing = "default";
}

/* I want to insert this code below with Byte Buddy */
thing = "Intercepted by Byte Buddy";

/* stuff */
}
```

The idea is I want to ignore all the `case1-3` so that `thing` is always what I tell Byte Buddy to set it as

But the `/* stuff */` at the top and bottom of the method cannot be removed

**Comment by raphw** [comment]
Advice cannot remove code somewhere in the method. Either, you have to reimplement that part in your advice or you need to use ASM.

**Comment by breaklulz** [comment]
With 
```java
field(named("foo")).value("hello")
```
there's no `value()` for anything other than primitive types. How would I use Byte Buddy to change the value of a field that isn't any of: `int` `long` `float` `double` `String` `boolean`

For example, say I have a field that holds a `File`
```java
public File test = null;
```
How do I make Byte Buddy set that to `new File("hello.txt")`

When working with method interceptors we have `FixedValue` which is really nice and can make a `File` returning method return with code as simple as this

```java
method(named("getFile")).intercept(FixedValue.value(new File("hello.txt")))
```

**Comment by raphw** [comment]
In this case, you have to instrument the constructors. The Java language differentiates between compile-time constants (set with the fields) and other field assignments which are done in byte code. You can instrument the constructors of a class and set a fixed value using a `FieldAccessor`.

**Comment by raphw** [comment]
Please reopen this if you have further question.
