### ISSUE TITLE
how to modify method use Advice

### ISSUE THREAD

**Issue by hao117** [raphw/byte-buddy#546]
MyObject  foo(){
     doSomething....
     return obj;
}
want to
MyObject foo(){
   doOtherthing...
   return obj2； 
}

**Comment by hao117** [comment]
I don't want the original code to execute.

**Comment by raphw** [comment]
Then you can either: Intercept the original code additionally to registering an advice and use `StubMethod.INSTANCE`. Or, register an enter advice where you skip the original method.

**Comment by hao117** [comment]
I solved it！ Thank you !
my code:
```
@Advice.OnMethodEnter(skipOn = Advice.OnDefaultValue.class)
public static boolean enter(@Advice.This Object ths){
    return false;
}

@Advice.OnMethodExit()
public static void exit(@Advice.Return(readOnly = false) BufferedReader reader,
                        @Advice.This Object ths){
    //doOtherthing...
    reader = new BufferedReader(...);
}
```
Thank you!

**Comment by raphw** [comment]
Glad I could help!
