### ISSUE TITLE
Plugin does not work for jar input with directory output

### ISSUE THREAD

**Issue by quarante-2** [raphw/byte-buddy#547]
It results in a `FileNotFoundException`. [Here](https://github.com/raphw/byte-buddy/blob/65a487f25d30335b67278d1279bb914e2dbc679b/byte-buddy-dep/src/main/java/net/bytebuddy/build/Plugin.java#L3011) `target` is a folder, causing the error. This happens because the `ForJarFile` source also produces elements that represent directories. I think it could be fixed by adding a directory check at the above location or by not producing directory elements.

On another note: I have to exclude some elements (classes/resources) as well as appending some. Would you consider exposing the `Sink` in the default `Engine`? And add a way to exclude elements? 
It is possible with the current API, but maybe it could be made easier. I think it would be generally useful.

Thanks!

**Comment by raphw** [comment]
Fixed on master.
