### ISSUE TITLE
Parameterize Advice Methods

### ISSUE THREAD

**Issue by AndreasMili** [raphw/byte-buddy#551]
In a nutshell, I want to change parameter values of several methods using the **same** `@Advice.OnMethodEnter` and `@Advice.OnMethodExit` advice methods.
Moreover, I want the advice methods to behave differently (change different parameters), depending on which method they instrument.

```
        new AgentBuilder.Default()
                .type(named("com.example.MyClass"))
                .transform((builder, typeDescription, classLoader, module) ->
                        builder
                                .visit(Advice.to(MyAdvice.class).on(named("doSomething1").and(...)))
                                .visit(Advice.to(MyAdvice.class).on(named("doSomething2").and(...)))
        );
```
Referring to the example, I want the `@Advice.OnMethodEnter` and `@Advice.OnMethodExit` method in `MyAdvice` to change different parameters for `doSomething1()` and `doSomething2()`, but by using the same logic. Therefore, I would need to parameterize `MyAdvice`.

Since the `@Advice.OnMethodEnter` and `@Advice.OnMethodExit` methods are static, are there any ByteBuddy-way solutions for parameterizing them?
Otherwise I would need to use a global state and do the same kind of matching again which I've already done with the ElementMatchers, which bould be cumbersome.

Unfortunately, the interception api is not an option for me, since I don't want to change the class schema.

Thanks in advance!

**Comment by raphw** [comment]
Advice works due to reusing compiled byte code; even if you parameterized the advice class, Byte Buddy could not simply "copy-paste" the code over. What you can do is to use `Advice.AllArguments` and change only specific argument values programmatically depending on what method you run.

If you need to provide method specific arguments to an advice, note that you can add your custom annotations using `Advice.withCustomConfiguration().bind(...).to(MyAdvice.class)`.

**Comment by raphw** [comment]
Yes, you can bind any `StackManipulation` to a custom annotation. You will need to implement a custom binder that creates the array, have a look at `ArrayFactory` to create an `int[]`. Also, use standard iteration, lambdas create methods to invoke in the advice class that will not be accessible to your instrumented class.

**Comment by AndreasMili** [comment]
Thanks for your blazing fast answers. I'm trying to wrap my head around on how to the custom annotation has to look like.

So basically I can achieve this:
```
int[] paramsToChange = // read from file
int[] paramsToChange2 = // read from file
                
builder.visit(Advice.withCustomMapping().bind(MyAnnotation.class, paramsToChange)
                   .to(MyAdvice.class).on(named("doSomething1")))
      .visit(Advice.withCustomMapping().bind(MyAnnotation.class, paramsToChange2)
                   .to(MyAdvice.class).on(named("doSomething2")));
```
```
@Advice.OnMethodEnter
public static void onEnter(@Advice.This Object obj, @Advice.Origin String method,
                           @Advice.AllArguments Object[] args, @MyAnnotation int[] params) {
}
```

With an annotation like that?

```
@Documented
@Retention(RetentionPolicy.RUNTIME)
@java.lang.annotation.Target(ElementType.PARAMETER)
public @interface MyAnnotation {
// Use ArrayFactory here?
}
```

If I'm on the right track, I'll try to figure it out and post an answer as soon as I got something working :)

**Comment by raphw** [comment]
Yes, this is right. All that is leat to do is to combine array factory with integer constant to produce a stack manipulation that loads the integers.

**Comment by raphw** [comment]
Please reopen the ticket if you have further questions.
