### ISSUE TITLE
How to define a field with value?

### ISSUE THREAD

**Issue by icanfly** [raphw/byte-buddy#553]
My code like blew, but it does not work.

```
    @Test
    public void test1() throws NoSuchFieldException, IllegalAccessException, InstantiationException {
        Class<?> target = new ByteBuddy()
                .subclass(NettyServer.class)
                .name("com.test.MyClass")
                .defineField("hello",String.class, Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL).value("world")
                .make()
                .load(ClassLoader.getSystemClassLoader()).getLoaded();

        Object targetObj = target.newInstance();

        Field f = target.getDeclaredField("hello");
        f.setAccessible(true);
        System.out.println(f.get(targetObj));

    }

```

**Comment by raphw** [comment]
The `value` part sets a compile-time constant value as the field's value. If you referenced the field from another Java class, it would copy that field value as a constant instead of reading the field. To really set the field's value, you have to do so in the constructor. For example:

```java
Class<?> target = new ByteBuddy()
  .subclass(Object.class)
  .name("com.test.MyClass")
  .defineConstructor(Opcodes.ACC_PUBLIC)
  .withParameters(String.class)
  .intercept(MethodCall.invoke(Object.class.getConstructor()).andThen(FieldAccessor.ofField("hello").setsArgumentAt(0)))
  .defineField("hello", String.class, Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL).value("world")
  .make()
  .load(ClassLoader.getSystemClassLoader()).getLoaded();

  Object targetObj = target.getConstructor(String.class).newInstance("world");

  Field f = target.getDeclaredField("hello");
  f.setAccessible(true);
  System.out.println(f.get(targetObj));
```

This defines a specific constructor.

Setting a field value using the DSL does not currently allow for more flexibility e.g. setting a constant value but this is on my things to do. Alternatively, you can define your custom `StackManipulation` to do so.

**Comment by icanfly** [comment]
@raphw , I really want to get a default value for my generated class, If use your method, I have to set the value of the field value each time when I instantiate it.

**Comment by raphw** [comment]
This is not possible, the Java specification requires you to set a field value in the constructor. If you do not see this in your Java source code, it is because javac creates the constructor code for you.

**Comment by raphw** [comment]
Byte Buddy 1.9.3 does not provide extended support for setting field values via MethodCall and FieldAcessor. Please reopen this ticket if you have futher questions.

**Comment by kdvolder** [comment]
> does not

I think you probably meant 'does now'?

**Comment by snoopfab** [comment]
Sorry to bother, but i did not understood if it is now possible to do it with Byte Buddy >= 1.9.3  .
Could you provide a simple example of setting a default value  of a  field or property with the new MethodCall and FieldAcessor api ?

Thanks for your time !

**Comment by raphw** [comment]
Yes. You can, within a MethodCall call setsField and define a field value like this from a constructor. The javadoc contains details.
