### ISSUE TITLE
Duplicate annotations  happened when enhance with fellow  grammar. what I can do if I want to Inherit parameter annotations.

### ISSUE THREAD

**Issue by ni-ze** [raphw/byte-buddy#555]
![1](https://user-images.githubusercontent.com/31175234/47838730-3a4d5600-ddeb-11e8-92b3-d7513cfc96c7.jpg)
![2](https://user-images.githubusercontent.com/31175234/47838732-3a4d5600-ddeb-11e8-84a3-aa26e3496c43.jpg)

**Comment by raphw** [comment]
I would expect this; you are telling Byte Buddy to copt the methods of the instrumented method while you are not overriding it such that they end up being duplicated. If you skip the attribute appender, it should be fine.

What is it you are trying to do?

**Comment by ni-ze** [comment]
thx,I figure it out by myself.I want to enhance a subclass which superclass has a annotation on method parameters.If  I do like this:
newClassBuilder.method(isDeclaredBy(typeDescription).and(...)).intercept(...)
It  will lost the superclass's method parameters annotation .
If I do like this:
newClassBuilder.method(isDeclaredBy(typeDescription) .and(...)) .intercept(...)
I will lost superclass's method.
If ido like this:
newClassBuilder.method(...
                            .intercept(...)
                            .attribute(MethodAttributeAppender.ForInstrumentedMethod.EXCLUDING_RECEIVER)
It lead  duplicated annotation  when enhance declared method.
At last,I use it like this:
newClassBuilder.method(isDeclaredBy(typeDescription).and(...))
                            .intercept(...)
                            .method(not(isDeclaredBy(typeDescription)).and(...))
                            .intercept(...)
                            .attribute(MethodAttributeAppender.ForInstrumentedMethod.EXCLUDING_RECEIVER);

It will not lead duplicated annotation,and also can enhance superclass method which has a annotation on parameter correctly.

**Comment by raphw** [comment]
Glad you figured it out. Thanks!
