### ISSUE TITLE
byte buddy has performance problems while high concurrency

### ISSUE THREAD

**Issue by baifan** [raphw/byte-buddy#556]
hi, I use `byte buddy` to implement java agent, when high concurrency, it cost too much to enter `MethodDelegation`.
I have coded a simple demo project at [demo-agent-bb](https://github.com/baifan/demo-agent-bb).
A single method just calculate the nano time to enter the delegation. 
It can take 200 milliseconds.
Does there has a problem with the way I used？

**Comment by raphw** [comment]
I assume this is due to the additional boxing. Rather define your interceptor method as:

    public long enhance(@Argument long argument) {
        return injector.elapse(argument);
    }

And you should not see any difference.

**Comment by baifan** [comment]
In addition. Use the code like below, but there is no improvement in performance.
```java
public class InstanceEnhancer {

    private HelloProxy injector;

    public InstanceEnhancer() {
        injector = new HelloProxy();
    }

    @RuntimeType
    public Object enhance(@Argument(0) long allArgument) {
        return injector.elapse(allArgument);
    }
}

```

**Comment by raphw** [comment]
You are still boxing the return type. But I am wondering how you measure that too. Byte Buddy is fairly well performance-tested, I would have seen issues with this mechanism.

**Comment by baifan** [comment]
It doesn't look like the `box value`'s performance penalty. 
The demo project is very simple, use `byte buddy` to implement java agent, realy cost too long time. It cost 50ms to run just a subtraction when high concurrency.
Can you run it to see the result, and analysis it?

**Comment by raphw** [comment]
Can break some optimizations, the JVM can be particular. But you would need to benchmark that part if you wanted details.

**Comment by baifan** [comment]
:+1: 
Okay, thank you very much!
