### ISSUE TITLE
reword JDK support for attach functionality

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#56]
after addressing #55 i propose to reword API, doc and exceptions.
On Java 9, tools jar is not required. it is part of the appmodules.jimage.

**Comment by raphw** [comment]
Yes, I am planning to change this. Currently, the JDK version 9 is still changing to much and I wait with an implementation until a more mature release of Java 9.

**Comment by raphw** [comment]
Fixed in master.
