### ISSUE TITLE
The library does not seem to work with lambda expressions. Is there a problem with my usage?

### ISSUE THREAD

**Issue by JoeKerouac** [raphw/byte-buddy#560]
The library does not seem to work with lambda expressions. Is there a problem with my usage?example：
```
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.matcher.ElementMatchers;

/**
 * @author JoeKerouac
 * @version $Id: joe, v 0.1 2018年11月10日 10:57 JoeKerouac Exp $
 */
public class ByteBuddyTest {
    public static void main(String[] args) throws Exception {
        Say hello = () -> "hello";
        Say say = new ByteBuddy().subclass(Say.class).method(ElementMatchers.named("say"))
            .intercept(MethodDelegation.to(hello)).make().load(hello.getClass().getClassLoader())
            .getLoaded().newInstance();
        System.out.println(say);
    }

    public interface Say {
        String say();
    }
}
```
this code will throw Exception(ClassNotFoundException),lambda class will not be found.

**Comment by raphw** [comment]
You are right that this is not possible. Lambda classes are anonymous and cannot be a delegation target as they cannot be referenced. In this case, you must specify the class explicitly: `MethodDelegation.to(hello, Say.class)`.

**Comment by JoeKerouac** [comment]
@raphw thx,Can this be done with some simple identification? For example, it is recognized from the class name. If the class name contains $Lambda$, it is considered to be a lambda expression. At this time, the internal internal conversion is called to call the `MethodDelegation.to(hello, Say.class)` method, so that the user experience will be better.I think the user should not perceive this.

**Comment by raphw** [comment]
The problem is that there is no explicit API for it and another VM implementation might choose to do differently. I will improve this solution if I find a way of doing this without any possible (performance) regression. In the mean time, this remains your responsibility.
