### ISSUE TITLE
Writing the class is very slow when it contains a lot of (rewritten) methods

### ISSUE THREAD

**Issue by gsmet** [raphw/byte-buddy#562]
Hi Rafael,

This is related to the Hibernate ByteBuddy enhancer: a user reported that it was really slower than our old Javassist enhancer.

Indeed, the enhancement of a large class takes ~20 seconds, mostly spent in ByteBuddy itself when writing the class.

The user posted a reproducer here: https://github.com/tlamr/enhancerissue . A simple `mvn clean install` shows the issue. The reproducer uses 5.4.0-SNAPSHOT so you either need to deploy a snapshot or you can downgrade to 5.3.7.Final which is already using BB and show the issue.

ByteBuddy: ~ 20 seconds
Javassist: ~ 4 seconds

The issue seems to be in `MethodRegistry.Default#prepare()` and in the large conjunction built there:
```java
           for (Entry entry : entries) {
                if (handlers.add(entry.getHandler())) {
                    instrumentedType = entry.getHandler().prepare(instrumentedType);
                    ElementMatcher<? super MethodDescription> handledMethods = noneOf(helperMethods);
                    helperMethods = instrumentedType.getDeclaredMethods();
                    for (MethodDescription helperMethod : helperMethods.filter(handledMethods)) {
                        implementations.put(helperMethod, entry.asSupplementaryEntry(helperMethod));
                    }
                }
            }
```

See https://hibernate.atlassian.net/secure/attachment/49389/cpu.svg for profiling information (you'll have to scroll quite a bit).

Note that maybe the Hibernate enhancer is doing something wrong when rewriting the classes leading to too many elements there but I think the large number of elements is mostly due to the size of the class (it's extracted from an ERP allowing to customize fields).

Happy to help and experiment if needed.

Thanks!

**Comment by raphw** [comment]
Jap, my bad. This loop was quite performance heavy, went for the pretty solution and got the bill right there. I am adding a test for an instrumentation of a large class and release a new version right after.

**Comment by raphw** [comment]
That said, I am wondering why the duplication filter does not kick in. Normally, Byte Buddy checks if an `Implementation` was applied previously. Even with a lot of methods, I would expect that the implementation only would be applied a single time. I will look into this as well before publishing.

**Comment by raphw** [comment]
@gsmet, @Sanne: The `InlineDirtyCheckingHandler` should really implement hashCode and equals methods. Doing so, Byte Buddy will detect equal handlers and only prepare them once. This is true for any custom `Implementation`s. Nevertheless, my fix will speed up things.

**Comment by raphw** [comment]
I just released Byte Buddy 1.9.4 with the fix for the issue. I still recommend you to add hashCode/equals to all custom implementations to avoid duplicate preparation.

**Comment by Sanne** [comment]
You're awesome! Testing... 

 - https://hibernate.atlassian.net/browse/HHH-13099

**Comment by Sanne** [comment]
Thanks, that huge spike is gone. And I only updated Byte Buddy version so far, I'll see to apply your other suggestions now as well. @gsmet also has another collection of optimisations pending, this will get quite smooth :)

**Comment by raphw** [comment]
Glad it was so easy! Let me know if you find anything more, I added another test for a "huge class" instrumentation but those are sometimes difficult to find.

**Comment by gsmet** [comment]
@raphw thanks a lot for the quick turnaround!
