### ISSUE TITLE
constructor intercept order issue

### ISSUE THREAD

**Issue by honganan** [raphw/byte-buddy#567]
Hi, I think there may be a bug in constructor intercept about execute order. According to the comments in class `InstanceConstructorInterceptor`, the interceptor will called before the origin constructor invocation. But when I test it I found my origin constructor called first, and then the interceptor `onConstruct` method.
After check I found bytebuddy support both two orders, before or after. What makes the difference is `intercept(A.andThen(B))`(L30 ClassEnhancePluginDefine.java):
1) origin constructor first, then the intercept method:
```java
newClassBuilder = newClassBuilder.constructor(constructorInterceptPoint.getConstructorMatcher()).intercept(SuperMethodCall.INSTANCE
                    .andThen(MethodDelegation.withDefaultConfiguration()
                        .to(new ConstructorInter(constructorInterceptPoint.getConstructorInterceptor(), classLoader))
                    )
                );
```
2) the intercept method first, then the origin constructor
```java
newClassBuilder = newClassBuilder.constructor(constructorInterceptPoint.getConstructorMatcher()).intercept(MethodDelegation.withDefaultConfiguration()
                    .to(new ConstructorInter(constructorInterceptPoint.getConstructorInterceptor(), classLoader))
                    .andThen(SuperMethodCall.INSTANCE)
                );
```

**Comment by honganan** [comment]
I think we can change the api in `InstanceConstructorInterceptor` from one method`onConstruct` to two: `beforeConstruct` and `afterConstruct`. But I am not sure if this is suitable.

**Comment by honganan** [comment]
sorry for sending to the wrong page!

**Comment by raphw** [comment]
Did you solve your problem? Or did you intend to post this to skywalking?
