### ISSUE TITLE
@inline annotation

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#57]
Can you provide the functionality to in line methods though annotations?

**Comment by raphw** [comment]
I have considered this for an early version but I have finally decided not to support this kind of feature. Inlining for performance is better applied by the JIT compiler and it creates strange debugging behavior for users, not to speak of countless edge-problems like different versions of the generated byte code and the target class. Byte Buddy will not support such a feature as it is always better to create appropriate class loader hierarchies in combination with `MethodDelegation`.
