### ISSUE TITLE
EnclosingMethod attribute added for non-local (static) classes

### ISSUE THREAD

**Issue by jpfourny** [raphw/byte-buddy#570]
It seems any Byte Buddy transformation of a class (even a no-op ASM visitor) will cause an EnclosingMethod attribute to be erroneously introduced into non-local inner classes. This attribute should only be used in local classes (ie: those enclosed by a method). Whenever an enclosing class exists, Byte Buddy will invoke ClassVisitor.vistOuterClass(..) with a NULL method reference. The OW2 ASM documentation implies this is legal, but it is not. Internally, ClassWriter will ALWAYS emit an EnclosingMethod attribute when enclosingClassIndex is set to non-zero, regardless of whether or not enclosingMethodIndex is set. This will result in an EnclosingMethod referencing constant pool index 0 of the outer class (which is illegal). Moreover, the existence of the EnclosingMethod attribute will cause both the IBM JVM and Oracle JVM to report Class.isLocalClass() as true. This will result in runtime errors when working with this class, since it is not a legal local class (missing synthetic constructor). 

I have worked around the issue by introducing an ASM visitor that ignores the calls to visitOuterClass(..), unless the method and description parameters are non-null. Byte Buddy could do the same. I strongly believe this should be opened as an ASM issue, however. The docs are misleading. There is no legal use case for calling visitOuterClass(..) without a valid method reference.

**Comment by raphw** [comment]
It is legal for methods that are defined in a static block or inside a constructor block. 

Can you provide an example where Byte Buddy sets this attribute? I will look into it, too.

**Comment by jpfourny** [comment]
You need to make Bar static. Check this out:

	class Foo {

		public static void main(String[] args) throws IOException {
			System.out.println(">> ORIGINAL CLASS:");
			byte[] originalBytes = getClassBytes(Foo.Bar.class);
			traceClass(originalBytes);

			System.out.println(">> REDEFINED CLASS:");
			byte[] transformedBytes = new ByteBuddy().redefine(Foo.Bar.class).make().getBytes();
			traceClass(transformedBytes);
		}

		private static byte[] getClassBytes(Class<?> cls) throws IOException {
			String path = cls.getName().replaceAll("\\.", "/") + ".class";
			ByteArrayOutputStream out = new ByteArrayOutputStream();
			byte[] buf = new byte[4096];

			try (InputStream in = Foo.class.getClassLoader().getResourceAsStream(path)) {
				while (true) {
					int len = in.read(buf);
					if (len == -1) {
						break;
					}
					out.write(buf, 0, len);
				}
				return out.toByteArray();
			}
		}

		private static void traceClass(final byte[] bytes) {
			ClassReader r = new ClassReader(bytes);
			r.accept(new TraceClassVisitor(new PrintWriter(System.out)), 0);
		}

		static class Bar {

		}

	}

Compare the ORIGINAL vs REDEFINED trace. The redefined output is the same, except for the new "OUTERCLASS Foo null". If you run these bytes through javap, you will also see that an EnclosingMethod attribute was added. Here is the output from my system:

	class Foo$Bar
	  minor version: 0
	  major version: 52
	  flags: ACC_SUPER
	Constant pool:
	   #1 = Class              #2             // Foo$Bar
	   #2 = Utf8               Foo$Bar
	   #3 = Class              #4             // java/lang/Object
	   #4 = Utf8               java/lang/Object
	   #5 = Utf8               <init>
	   #6 = Utf8               ()V
	   #7 = Utf8               Code
	   #8 = Methodref          #3.#9          // java/lang/Object."<init>":()V
	   #9 = NameAndType        #5:#6          // "<init>":()V
	  #10 = Utf8               LineNumberTable
	  #11 = Utf8               LocalVariableTable
	  #12 = Utf8               this
	  #13 = Utf8               LFoo$Bar;
	  #14 = Utf8               SourceFile
	  #15 = Utf8               Foo.java
	  #16 = Utf8               InnerClasses
	  #17 = Class              #18            // Foo
	  #18 = Utf8               Foo
	  #19 = Utf8               Bar
	  #20 = Utf8               EnclosingMethod
	{
	  Foo$Bar();
		descriptor: ()V
		flags:
		Code:
		  stack=1, locals=1, args_size=1
			 0: aload_0
			 1: invokespecial #8                  // Method java/lang/Object."<init>":()V
			 4: return
		  LineNumberTable:
			line 45: 0
		  LocalVariableTable:
			Start  Length  Slot  Name   Signature
				0       5     0  this   LFoo$Bar;
	}
	InnerClasses:
		 static #19= #1 of #17; //Bar=class Foo$Bar of class Foo
	EnclosingMethod: #17.#0                 // Foo
	SourceFile: "Foo.java"

**Comment by jpfourny** [comment]
Apologies - I should have mentioned that I am running with 1.8.20. I tried the test case again with 1.9.4 and the issue is not reproducible. It seems to be isolated to 1.8.x. I am glad to know that it is fixed! 

Unfortunately, Byte Buddy 1.9.x is not binary compatible with a 3rd party lib we are using (Stagemonitor). We have a private fork that we are extending, so it can be done with some effort.

**Comment by raphw** [comment]
Thanks for verifying! The update to 1.9.* should be fairly easy, just send a PR to stagemonitor!
