### ISSUE TITLE
Change the scope of a transformation in order to reset a subset of the transformed classes

### ISSUE THREAD

**Issue by mariusoe** [raphw/byte-buddy#571]
Hi @raphw ,

I have a querstion regarding the AgentBuilder (more specific the result of it) and whether it is possible to change some of the transformed classes (e.g. resetting only a subset of them).

Let's assume I have the following code:
```
new AgentBuilder.Default()
                .disableClassFormatChanges()
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .type(nameStartsWith("org.MyClass"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                        return builder
                                .visit(Advice.to(LoggerAdvice.class)
                                        .on(named("print")));
                    }
                }).installOn(instrumentation);
```

Using this code, I add an advice (in this example a LoggerAdvice) to all classes named `org.MyClass*`. This works pretty fine.

Now, my question is: is it possible, for example, to change the class matcher to something like this `nameEndsWith("Class")`, so changing the set of matching classes in order to reset those classes which are not matching anymore and add the advice to those which are matching now? :) 

My goal is that I want to change the set of classes which have the Advice assigned and I don't want to reset and retransform all of the classes but only change the necessary subset of classes. I hope you get my point :)

It would be great if you can give me some information if something like this is already possible or a hint what needs to be done for achieving something like this.

Best regards, Marius

**Comment by raphw** [comment]
You can trigger a retransformation manually by calling `Instrumentation::retransformClasses`. All you need to do is to reregister a changed class file transformer by using the same API, this way you can update any delta. Alternatively, you can register a mutable matcher in byte buddy, as long as it is thread safe.

**Comment by mariusoe** [comment]
Hey, first of all thanks for the quick response! :)

I don’t get it completely. As far as I understand, one option would be to trigger the retransformation manually using `retransformClasses` and decide in the transformer what I want to do (do nothing, retransform or reset it). Did I get this right?

Another option would be to implement a mutable matcher and assign it to byte buddy. But in this case I also have to retrigger the analysis of the classes in some way when the matcher is changing, right? Or do you mean to use a mutable matcher in combination with manually triggering the instrumentation?

**Comment by raphw** [comment]
On a retransformation, all classes that are retransformed walk through the same transformer chain as before. If you registered a new class file transformer, any class that would now result in a different state will have changed as a result of the retransformation. Those who would not change do not need to be retransformed as the retransformation result would be the same.

This can be achieved by either creating a new class file transformer or by mutating a transformer that was previously registered.

**Comment by mariusoe** [comment]
By the way, thanks for your help!
