### ISSUE TITLE
Too many Nexus objects cause OOM

### ISSUE THREAD

**Issue by honganan** [raphw/byte-buddy#576]
Hi, We are using Byte buddy to build our apm system. 

And we have some difference to common usage. We have our own jar container which handle any class loading. That means in our system all classes are loaded in our own `ClassLoader`, not the `SystemClassLoader`. Then we met the OOM as too many `Nexus` objects.(we enhanced more than 2k classes in one of our special scenario) 

I noticed `NexusAccessor` uses `SystemClassLoader` directly, I am not sure if the difference usage of `ClassLoader` cause this objects can not be collect?
Thanks!

**Comment by honganan** [comment]
I noticed the Nexus can be disabled by setting system property. But my class enhancement seems not work after I disabled this.

**Comment by raphw** [comment]
Hi, the Nexus reference is kept until the class in question is running its static initializer. If this fails, the Nexus has no way of knowing if a class is already loaded as there can go a lot of time between instrumentation and actual loading. 

On scale, it is the best if you avoid the nexus altogether and rely on instrumentations that do not require a live initializer. This way, you can avoid this other unsolvable problem.

**Comment by honganan** [comment]
Thank you for reply so fast. When I close this Nexus mechanism, I found my enhancements do not work, should I set something else?
I am using version 1.7.9, and write as new AgentBuild().Default()...

**Comment by honganan** [comment]
Hi, I took many time on searching about this Nexus, in my understanding, when the origin type first created, the callback to LoadedTypeInitializer invoked, as we can't make sure when did a type created first so we make the Nexus to hold the initializers combine to ClassLoader so that the Nexus won't be allocated. Am I right?

And I have another two question：
1）Does the LoadedTypeInitializer exist for initializing the auxiliary types？If this callback does not exist, the enhancement of the origin type will not work?
2) As the Nexus reference to the ClassLoader and the classloader will never been destroyed so Nexus can not be collected, then why it be defined as a WeakReference? Will `NexusAccessor`'s clean method invoked after type initialized? Where did this invoke happened?

Byte buddy is really a nice project and designed very good. We are using it to build our apm system.

**Comment by honganan** [comment]
I have tried `InitializationStrategy.Minimal` but got `java.lang.ClassNotFoundException` of auxiliary type.  It seems that if I want this run on the PRODUCT environment, I should use the `InitializationStrategy.SelfInjection` and reduce the instrument class number.

**Comment by raphw** [comment]
In this case it seems that you have a hard requirement to only load the auxiliary classes after the instrumented class was loaded. All you can do is to refactor your code to resolve this requirement or to run a different initialization strategy (it is an interface) where you have better grip of the life cycle as Byte Buddy can offer for the general case.

**Comment by honganan** [comment]
Thank you! I may need more study on it's life cycle.
