### ISSUE TITLE
Cannot instrument everything

### ISSUE THREAD

**Issue by paplorinc** [raphw/byte-buddy#577]
Hey @raphw,

I'm trying to capture every single constructor call - and every accessor, but I'm stuck at constructors for now.
At this stage I don't yet care about the performance impact of instrumenting everything.

I've created to simple project to demonstrate what I'm trying to do: https://github.com/paplorinc/bb_examples

Agent: https://github.com/paplorinc/bb_examples/blob/master/src/main/java/lorinc/pap/agent/Agent.java

It seems to fail because the bootstrap classloader cannot find the agent.
Any help is appreciated! :)

**Comment by jpfourny** [comment]
The agent is loaded by System class loader, so this limits what your advice can do. As soon as you instrument a class of bootstrap classpath, it cannot make references to your agent classes, nor ByteBuddy internals. For this to work, you must promote your agent classes to bootstrap. I know ByteBuddy has some facilities to do this for you ... but I am not very familiar with them, yet. I had a similar problem, and I solved it by re-packing my agent JARs into temp files and adding those files to bootstrap classpath via Instrumentation API. Note: This must happen before you make any references to the rest of your agent. It requires you to break it up a little to take advantage of class lazy-loading.

**Comment by paplorinc** [comment]
Hey @jpfourny, thanks, will investigate it.

**Comment by jpfourny** [comment]
I ended up packing the guts of my agent into separate JAR files as resources (ie: JAR inside a JAR). In the root JAR, I only have agent main/premain and some support classes to bootstrap startup, which includes extraction of temp JAR files and updating bootstrap classpath on Instrumentation. 

Attached, is an example utility to help extract JARs that are embedded into your agent JAR.
[BootstrapJars.txt](https://github.com/raphw/byte-buddy/files/2706085/BootstrapJars.txt)

**Comment by raphw** [comment]
Without any callbacks, your code should work just fine. Did you import the correct `Origin` annotation (within `Advice`)? There is another annotation for method delegation that would not work.

You can register a listener to the agent builder that prints any possible exception that might explain to you what the problem is. If you are using advice, the entire injection bit should be unnecessary.

If you want to exchange the print command with a callback bundled with your agent you need to however apply the suggestion of @jpfourny.

**Comment by paplorinc** [comment]
> There is another annotation for method delegation that would not work.

Yes, it was from `Advice`. Made it explicit in now in https://github.com/paplorinc/bb_examples/blob/instrument_bootstrap_constructors/src/main/java/lorinc/pap/agent/BootstrapAgent.java#L69 

> You can register a listener to the agent builder that prints any possible exception that might explain to you what the problem is. If you are using advice, the entire injection bit should be unnecessary.

Other than the commented out `//.with(AgentBuilder.Listener.StreamWriting.toSystemError())` above?

Thanks Rafael, this instrumentation business seems really difficult...

**Comment by raphw** [comment]
Is the class you expect showing up when you add the listener? maybe it is already loaded, you need to enable retransformation in that case.

**Comment by paplorinc** [comment]
Thanks @raphw, I've tried with those:
```java
new AgentBuilder.Default()
 .disableClassFormatChanges()
 .with(AgentBuilder.Listener.StreamWriting.toSystemError())
 .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
 .enableBootstrapInjection(instrumentation, temp)
 .ignore(none())
 .type(any())
 .transform((builder, t, c, m) -> builder.visit(Advice.to(interceptorClass).on(isConstructor())))
 .installOn(instrumentation);
...
public static class ConstructorInterceptor {
    @OnMethodEnter public static void enter(@Advice.Origin Executable executable) {
        System.out.println("Enter " + executable.getName());
    }
}
```
Now I'm getting:
```
[Byte Buddy] DISCOVERY java.util.ArrayList [null, null, loaded=true]
[Byte Buddy] TRANSFORM java.util.ArrayList [null, null, loaded=true]
[Byte Buddy] COMPLETE java.util.ArrayList [null, null, loaded=true]
```
but the interceptor is not called.

What else should I do to enable retransformation of an already loaded type?

**Comment by raphw** [comment]
I think that the problem is that `ArrayList` is used by Byte Buddy internally and is loaded during registering the transformer. This also applies to other types but the system is not perfect, unfortunately.

You can use `.with(AgentBuilder.RedefinitionStrategy.DiscoveryStrategy.Reiterating.INSTANCE)` after setting the retransformation strategy. But the class might stil miss if it is loaded after the reiteration. In this case, you have to call `retransformClasses(ArrayList.class)` manually after registering the transformer.

**Comment by paplorinc** [comment]
Wow, these are unexpected, but they seem to be working!
Thank you for your help, @raphw and @jpfourny!

For future reference, the code is the following:
```java
public static void main(String[] args) throws Exception {
    premain(null, ByteBuddyAgent.install());

    System.out.println(new ArrayList<>());
    System.out.println(new AbstractMap.SimpleImmutableEntry<>("Key", "Value"));
}

public static void premain(String arg, Instrumentation instrumentation) throws Exception {
    Class<ConstructorInterceptor> interceptorClass = ConstructorInterceptor.class;

    File temp = Files.createTempDirectory("tmp").toFile();
    UsingInstrumentation.of(temp, BOOTSTRAP, instrumentation)
        .inject(singletonMap(new ForLoadedType(interceptorClass), read(interceptorClass)));

    new AgentBuilder.Default()
        .disableClassFormatChanges()
        //.with(Listener.StreamWriting.toSystemError())
        .with(RedefinitionStrategy.RETRANSFORMATION)
        .with(RedefinitionStrategy.DiscoveryStrategy.Reiterating.INSTANCE)
        .with(InitializationStrategy.NoOp.INSTANCE)
        .with(TypeStrategy.Default.REBASE)
        .enableBootstrapInjection(instrumentation, temp)
        .ignore(none())
        .type(any())
        .transform((builder, t, c, m) -> builder.visit(Advice.to(interceptorClass).on(isConstructor())))
        .installOn(instrumentation);

    instrumentation.retransformClasses(ArrayList.class, AbstractMap.SimpleImmutableEntry.class);
}

public static class ConstructorInterceptor {
    @OnMethodEnter(inline = false) public static void enter(@Advice.Origin Executable executable) {
        if (executable.getName().startsWith("java.util.")) {
            System.out.println("Enter " + executable.getName());
        }
    }
}
```
