### ISSUE TITLE
[Question] org.apache.catalina.loader.WebappClassLoader method delegation, class reload failed?

### ISSUE THREAD

**Issue by cngddflzw** [raphw/byte-buddy#578]
I want to delegate class org.apache.catalina.loader.WebappClassLoader.loadClass() method, and I write some test code:

I use VirtualMachine.attach() to load the agent and get the instrument instance, this is not happened at the JVM start time, I invoke the attach() at runtime mannually.

the instrument code:

```java
		new AgentBuilder.Default()
				.with(AgentBuilder.Listener.StreamWriting.toSystemOut().withErrorsOnly())
.with(AgentBuilder.Listener.StreamWriting.toSystemOut().withTransformationsOnly())
				.with(RedefinitionStrategy.REDEFINITION)
				.with(Default.REBASE)
				.ignore(ElementMatchers.none())
				.type(ElementMatchers.is(WebappClassLoader.class))
				.transform((builder, typeDescription, classLoader, module) -> builder.method(named("loadClass")).intercept(MethodDelegation.to(WebappClassLoaderInterceptor.class))
				).installOn(inst);

		ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
		System.out.println(contextClassLoader);
		contextClassLoader.loadClass("java.lang.String");
```

the interceptor code:

```java
public class WebappClassLoaderInterceptor {

	public static Class<?> intercept(@SuperCall Callable<Class<?>> callable) throws Exception {
		System.out.println("intercepted classloader");
		return callable.call();
	}
}
```

and the output is:

```
[Byte Buddy] TRANSFORM org.apache.catalina.loader.WebappClassLoader [java.net.URLClassLoader@c81cdd1, null, loaded=true]
WebappClassLoader
  context: 
  delegate: false
  repositories:
    /WEB-INF/classes/
----------> Parent Classloader:
java.net.URLClassLoader@c81cdd1
```

there is no error and "intercepted classloader" not show here, any thing wrong?

----

After digging a bit deeper, I've known the reason why I can't get the interceptor affected:
1. Rebasing a method will preserve the original method and rename it to something like "test$origin()"
2. Since I want to invoke the original method, so I shoud use @SuperCall, and @SuperCall needs rebase a method, so you can't use TypeStrategy.redifine and disableClassFormatChanges() (I'm not sure this is correct?)
3. HotSwap would not reload any loaded class which adds a new method or field (such as rebase, adds a new method test$origin())

What I want to do is add some code into the beginning of the method WebappClassLoader.loadClass(). such as if I meet a class named "test.me.Foo", I should delegate the class loading to anthoer ClassLoader.

So the question is now how can I inject this class loading delegation code to the original loadClass() method and then reload the WebappClassLoader which is already loaded? Is it @Advice can do this for me? Or can I just add some code into the beginning of the method but not create new field or method, just like asm visitCode()?

**Comment by cngddflzw** [comment]
Finally I use advice to solve this problem. It works fine as @Advice will not add method or field to the class. I write some like:

```java
public class Foo {

	public String test(String name) {
		return "Hello " + name;
	}
}

public class ValueReplaceAdvisor {

	@Advice.OnMethodEnter(skipOn = Advice.OnNonDefaultValue.class)
	public static Object shouldReplaceValue(@Advice.Argument(0) String name) {
		if (name.equals("abc")) {
			return "replace value";
		} else {
			return null;
		}
	}

	@Advice.OnMethodExit
	public static Object replaceValue(
			@Advice.Return(readOnly = false, typing = DYNAMIC) Object returned,
			@Advice.Enter Object enter) {
		if (enter != null) {
			returned = enter;
		}
		return returned;
	}
}
```
this Advisor is not for WebappClassLoader,  but has almost the same effect -- it replaces the value when the name is "abc".

and the configuration code is:

```java
		final Extendable extendable = new AgentBuilder.Default()
				.with(StreamWriting.toSystemOut().withErrorsOnly())
				.with(StreamWriting.toSystemOut().withTransformationsOnly())
				.with(Default.REDEFINE)
				.with(RedefinitionStrategy.REDEFINITION) 
				.disableClassFormatChanges() 
				.ignore(none())
				.type(is(Foo.class))
				.transform(new Transformer() {
					public Builder<?> transform(Builder<?> builder, TypeDescription typeDescription,
							ClassLoader classLoader, JavaModule module) {
						return builder.visit(Advice.to(ValueReplaceAdvisor.class).on(ElementMatchers.named("test")));
					}
				})
```

**Comment by raphw** [comment]
Glad you figured it out, I was on Christmas vacation, therefore I did not answer you in time.
