### ISSUE TITLE
NoClassDefFoundError when instrumenting java.lang.Runtime

### ISSUE THREAD

**Issue by arjunsawhney** [raphw/byte-buddy#579]
Hi. I am able to instrument a method in java.lang.Runtime.

On @Advice.OnMethodEnter, I try to create an object of my own class but I get NoClassDefFoundError

However, when I try to instrument doFilter method of another class, I am able to create this object.

Please help, thank you!

**Comment by paplorinc** [comment]
May be related to my question, too: https://github.com/raphw/byte-buddy/issues/577#issuecomment-450671944

**Comment by raphw** [comment]
I assume that your method is not available to the bootstrap class loader. This is typically the case if your method is part of your Java agent that is loaded by the system class loader.

You have to put your runtime code into a seperate jar file and attach this jar to the bootstap loader search path using the `Instrumentation` instance that is provided to your agent.

**Comment by arjunsawhney** [comment]
I have done the required instrumentation.
I build my jar and attach it to my spring boot application, and then I run it.

Agent.java

return new AgentBuilder.Default().disableClassFormatChanges()
                .ignore(ElementMatchers.none())
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
                .type(ElementMatchers.nameContainsIgnoreCase("java.lang.Runtime"))
                .transform(new AgentBuilder.Transformer.ForAdvice().include(MyAgent.class.getClassLoader())
                        .advice(ElementMatchers.named("exec"),"XYZ"));

XYZ.java:

@Advice.OnMethodEnter
    public static void enterFilter(@Advice.AllArguments Object[] allArguments,
                                   @Advice.Origin Method method) {
       ABC abc = new ABC(); //this line gives me NoClassDefFoundError
    }

But when I use the same instrumentation for a doFilter method and create an ABC object, I do not get NoClassDefFoundError

**Comment by raphw** [comment]
Your agent is loaded on the system class path, I assume that Spring Boot is run on a different class loader. The only class loader that is universally visible is the bootstrap loader.

**Comment by arjunsawhney** [comment]
Okay, I understand.
So can you please tell me how to go about fixing this issue?

**Comment by raphw** [comment]
You have to create a jar file that contains your shared code and append it to the bootstrap class loader search path using the `Instrumentation` instance that is provided to your agent.

**Comment by arjunsawhney** [comment]
I tried doing that by getting the jar file and using instrumentation.appenToBootstrapClassLoaderSearch() but now I am getting a linkage error when I am creating a new AgentBuilder instance.

Any help would be really appreciated.

**Comment by raphw** [comment]
You probably duplicate your code somehow.

Make sure you have to cleanly seperate jars, one for the instrumentation, one for the runtime interception. Make the first jar only depend on the second via a provided scoped dependency.

Attach the second jar before you even load any of the code that will later refer to it. Keep your agent code fully seperate.

**Comment by arjunsawhney** [comment]
I used <Boot-Class-Path> in the pom to load the jar my agent and required java classes, and it worked. Thank you.

**Comment by arjunsawhney** [comment]
I used in the pom to load the jar my agent and required java classes, and it worked. Thank you.

**Comment by arjunsawhney** [comment]
I used <Boot-Class-Path> in manifest entries the pom to load the jar my agent and required java classes, and it worked. Thank you.
