### ISSUE TITLE
Simplify The API

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#58]
Can you simplify the API so it is more intuitive like in https://github.com/square/javapoet

**Comment by sirinath** [comment]
This could be an another abstraction layer on top of the current API.

**Comment by raphw** [comment]
Javapoet is a source code generation library and can therefore imitate the Java language what is of course more intuitive. The Byte Buddy API is constantly refactored and extended but there will not be a higher-level API than the one offered today. For a more high-level API, it would be better-suited to implement a new library that can of course be based upon Byte Buddy.
