### ISSUE TITLE
Creating JAR at runtime for appendToBootstrapClassLoaderSearch

### ISSUE THREAD

**Issue by ndrez93** [raphw/byte-buddy#581]
Hey,

I'm attempting to override some java.lang.*-specific behavior that to my understanding requires a JAR file with custom functionality to be created. When I create the archive manually and include its path when setting up my Byte Buddy instance, it seems to work.
However, am I correct that `AgentBuilder#enableBootstrapInjection` should provide this functionality out of the box? Tracing the code leads me to believe that it should create the JAR and include it in bootstrap class loader search.
Yet if I include this in my agent builder configuration, nothing seems to happen. While transformation succeeds, the JAR does not get generated and the substituted class is obviously not found. Debugging `enableBootstrapInjection` shows that the relevant methods are not even called. What could be missing here?

Minimal (non-) working example:

```
var i = ByteBuddyAgent.install();
// JAR with Stub.class
i.appendToBootstrapClassLoaderSearch(new JarFile("/some/file.jar")); // <- DON'T WANT THIS
var classFileTransformer = new AgentBuilder.Default()
	.with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
	.ignore(none())
	.enableBootstrapInjection(i, FileUtils.getTempDirectory()) // <- SHOULDN'T THIS REPLACE appendToBootstrapClassLoaderSearch?
	.type(ElementMatchers.is(System.class))
	.transform((b, c, d, e) -> b.method(ElementMatchers.named("methodToOverride"))
			.intercept(MethodDelegation.to(Stub.class)))
	.installOn(i);
```

**Comment by ndrez93** [comment]
It appears that the following injection solves my problem:

```
ClassInjector.UsingInstrumentation
    .of(FileUtils.getTempDirectory(), ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, i)
    .inject(Map.of(new TypeDescription.ForLoadedType(Stub.class), ClassFileLocator.ForClassLoader.read(Stub.class)));
```

The JAR file gets created and my class can be found by the bootstrap class loader. However, why didn't `enableBootstrapInjection` work?

**Comment by paplorinc** [comment]
Seems to be related to my question: https://github.com/raphw/byte-buddy/issues/577#issuecomment-450671944

**Comment by raphw** [comment]
Bootstrap injection only injects any generated auxiliary classes into the bootstrap loader as they are created. It does not inject the `Stub` class, only the glue classes (the proxies for example generated for implementing `SuperCall`). Byte Buddy has no chance to know what classes are required for `Stub`, this is why Byte Buddy does not attempt solving this problem but required you to do so.

You can of course use Byte Buddy's convenience APIs as you suggested to inject selected classes.
