### ISSUE TITLE
Can't retrieve annotations from anonymous class's superclass type parameters

### ISSUE THREAD

**Issue by thecodewarrior** [raphw/byte-buddy#583]
First let me apologize if I sound harsh, I've spent all day trying to figure this out so I'm a bit frustrated¹

#### Chapter 1: The Preparations
I'll start this tale with what I wanted to make. I've been developing a [library for Java reflection](https://github.com/TeamWizardry/Mirror) and as part of it I made a simple `TypeToken` class. Like most type tokens it consisted of reading the type parameter specified by an anonymous subclass. After picking up the library again I've been adding support for type annotations, which included getting the `AnnotatedType` from a `TypeToken`. "Easy peasy" I thought… but oh how naive I was…
(skip to chapter 4 for the analysis)

#### Chapter 2: The Discovery
Being so simple, `TypeToken` had no tests and was assumed to work. This held true until recently, when I wrote tests for my type annotation code. For some reason none of the tests showed any type annotations at all! This puzzled me, and after digging around I discovered that the `AnnotatedType` _itself_ was missing the annotations! "It must be a problem with [Kotlin](https://kotlinlang.org/)" I thought, so I decided to write the test in Java to see if that fixed it. When it didn't I decided to look deeper, and discovered—to my horror—that this was a [known issue](https://stackoverflow.com/q/39952812).

#### Chapter 3: The Hope
After blowing and replacing several fuses I managed to get my brain functioning again. I followed the suggestion in that post and resigned myself to using Byte Buddy. (nothing against the library, I just don't like the idea of bringing in a cruise ship when all I needed was a dinghy.) After installing Byte Buddy I tested her out, knowing that—though it was far from ideal—at least this time it'll work… but it didn't. I started investigating into Byte Buddy and was further horrified—I didn't think it was possible—to find that what seemed to be a similar issue was occurring in Byte Buddy.

### Chapter 4: The Analysis

The analysis of the JVM side was discussed in the [StackOverflow post I linked earlier](https://stackoverflow.com/q/39952812). The side of more concern here is Byte Buddy. The inputs for the code were quite simple:
```java
class ExampleTests {
    void theTest() {
        TypeToken token = new TypeToken<@FuckingTypeAnnotation Object1>() {};
        AnnotatedType type = token.getAnnotated();
    }
}
```
In `getAnnotated()` I had the following:
```kotlin
fun getAnnotated(): AnnotatedType {
    val description = pool(this.javaClass.classLoader)
        .describe(this.javaClass.name)
        .resolve()
    val superClass = description.superClass
    val superArguments = superClass.typeArguments
    val annotations = superArguments.only.declaredAnnotations

    // still plain reflection, I never got far enough to work it out.
    return (this.javaClass.annotatedSuperclass as AnnotatedParameterizedType).annotatedActualTypeArguments[0]
}
```
(brief Kotlin translator's guide:
    - `get`/`setXyz` can be used as `xyz`/`xyz = `
    - `var`/`val` for nonfinal/final variables, types are optional)

After setting a breakpoint on the `val annotations =` line and running the debugger state looks like this:
![The debugger state at the `annotations=` line](https://i.imgur.com/5fLbYXt.png)

What seems to be the issue is the fact that the supertype argument's `typePath` is `0;` whereas the annotation's is `.0;`. After looking around in the source I discovered that `.` corresponds to `GenericTypeToken.INNER_CLASS_PATH`. I don't understand most of Byte Buddy, however from this perspective the `TypeToken` type parameter annotation being marked as inside an inner class makes sense, but what doesn't make sense in that case is that the `TypeToken` subclass wouldn't be.

In case it'll be of any use I created a [gist](https://gist.github.com/thecodewarrior/4d2a6c3d674f9eac97563a6875305d48) of the debugger state at that breakpoint. The issue can be reproduced by cloning [Mirror](https://github.com/TeamWizardry/Mirror/tree/byte-buddy-error) and running the test in `ExampleTests`.

P.S. - I haven't really entertained the possibility of being wrong here, which is a fair criticism. However, I'm not doing anything funky and I feel like being able to correctly read the type annotations of an anonymous class's superclasses isn't much to ask, so I'm considering it definitely a bug in the JVM and probably a bug in Byte Buddy. 

[1]: clarification: now that I've stepped away from the problem for about an hour I'm a bit frustrated. Before then my very soul was consumed by a burning, writhing, seething anger toward oracle or whoever else wrote that godforsaken code.

**Comment by thecodewarrior** [comment]
It seems that one works because `main` is a static method. If I make an instance method and make `main` call that it breaks.

```java
public class Sample {

    public static void main(String[] args) {
        new Sample().nonstaticMethod();
    }

    private void nonstaticMethod() {
        TypeToken token = new TypeToken<@FuckingTypeAnnotation Object>() { };
        TypeDescription td = TypePool.Default.ofSystemLoader().describe(token.getClass().getName()).resolve();
        AnnotationDescription desc = td.getSuperClass().getTypeArguments().get(0).getDeclaredAnnotations().get(0);
        System.out.println(desc);
    }

    static class TypeToken<T> { }

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE_USE)
    @interface FuckingTypeAnnotation { }
}
```

**Comment by raphw** [comment]
Now I know what bug you are hitting. Unfortunately, the type annotation is written to the wrong attribute. This is a bug in javac (that I actually reported when I implemented support for type annotations) which was unfortunately only solved in JDK 10 but not backported.

If you run the same code on JDK 11, everything works as expected.

**Comment by thecodewarrior** [comment]
Well shoot. Thanks for the help and quick response though. I want to support Java 8, as one of the primary places I'm going to use this is a Minecraft mod, which generally use Java 8, so I'll just add it to the docs.
