### ISSUE TITLE
Using ElementMatchers for classes in offline instrumentation

### ISSUE THREAD

**Issue by AndreasMili** [raphw/byte-buddy#586]
Hi,

I would like to instrument classes in a jar file without executing it with an agent.
For agents, there exist very convenient ElementMatchers for classes like:

```
        new AgentBuilder.Default()
                .type(isSubTypeOf(FileInputStream.class).and(isAnnotatedWith(named("MyAnnotation"))))
                .transform(...)
```

Using `ByteBuddy().redefine()` with a ClassFileLocator, I have to define the exact class name.
Is there any way of using Matchers like `isSubTypeOf()` in this context?

Thanks in advance!

**Comment by raphw** [comment]
Have a look at `Plugin` and `Plugin.Engine` which allow you to run trasformations from a Gradle plugin, a Maven plugin, the command line or embedded in another application.

**Comment by AndreasMili** [comment]
Thank you, you can close the question for now. I'm currently blocked and will add an example later.
