### ISSUE TITLE
How to inject code at the specified line number!

### ISSUE THREAD

**Issue by hao117** [raphw/byte-buddy#587]
example:
```java
1    public void foo(){
2        doSomething1();
3        doSomething2();
4        doSomething3();
5        doSomething4();
6        doSomething5();
7    }
```
 inject code at line nubmer 4
result:
```java
1    public void foo(){
2        doSomething1();
3        doSomething2();
         doOtherthing(); // inject code
4        doSomething3();
5        doSomething4();
6        doSomething5();
7    }
```
Can you give me an example?

thanks！

**Comment by raphw** [comment]
You can use `MemberSubstitution` to replace the method call for `doSomething2()` by `doSomething2()` followed by `doOtherThing()`. Note that this still requires supplying a custom stack manipulation, this component is still in its infancy but for an easy case, this can be done.

Byte Buddy does not allow for adding information at a line number as this is not a stable location in a compiled class. You can implement it yourself by using the underlying `ASM` API.

**Comment by hao117** [comment]
thank you!
