### ISSUE TITLE
How to redefine a method in super class but not in the sub class itself, and only take effect when the invocation instance type is SubClass?

### ISSUE THREAD

**Issue by cngddflzw** [raphw/byte-buddy#590]
Hi, I want to redefine a method declared in super class, but not declared in the sub class.
The problem is I want to hack the method execution only when the instance type is sub class, and when the instance is super class, the hack code (Advisor) should not work.

Also, it's refine at the jvm runtime, so it should not add any new method in the sub class, right?

For example, I got:
```java
public class Foo {
   void test();
}

public class Bar extends Foo {
}

public class MyAdvisor {
    @Advice.OnMethodEnter
    public static void test() {
        System.out.println("hack");
    }
}

public static void mian(String[] args) {
    Foo foo = new Foo();
    foo.test(); // this invocation should not print "hack"

    Bar bar = new Bar();
    bar.test(); // this invocation should print "hack"
}
```
how can I implement that?

**Comment by raphw** [comment]
In this case, you need to access the instance on which the method is invoked and check for its type:
```java
public class MyAdvisor {
    @Advice.OnMethodEnter
    public static void test(@Advice.This Object self) {
      if (self instanceof Bar) {
        System.out.println("hack");
      }
    }
}
```

**Comment by cngddflzw** [comment]
thanks @raphw, works fine now
