### ISSUE TITLE
How can I access argument names of method

### ISSUE THREAD

**Issue by serkan-ozal** [raphw/byte-buddy#592]
Hi,

I have started playing with ByteBuddy and it works fine to trace execution of methods with arguments and return value. So far so good. But I also want to get names of the arguments when they are available with debug symbols. How can I achieve this through ByteBuddy API?

Thanks

**Comment by raphw** [comment]
This is available via the `TypeDescription` API. If you want to read them using debug symbols, you need to use a `TypePool.Default` implementation using `ReaderMode.EXTENDED` where you can access the symbols via the `ParameterDescription` on a `MethodDescription` declared by this type.

**Comment by serkan-ozal** [comment]
Thanks for quick answer @raphw 

So, what is the best way to get the `MethodDescription` of the intercepted method in my advice annotated with `@Advice.OnMethodEnter`

**Comment by raphw** [comment]
You can register custom annotation bindings using `Advice.withCustomConfiguration().bind(SomeAnnotation.class, binding)`.

Just implement something that extracts the method name during instrumentation. Doing so, you only have to pay the costs for looking up a parameter name a single time.

**Comment by serkan-ozal** [comment]
Hi @raphw 

I am using ByteBuddy version `1.9.7`. Sorry but I couldn't find what should I pass as to `bind` method as `binding` parameter? `TypeDescription` or `MethodDescription`? If so, how can I use them?

Additionally, I have seen this discussion on the similar subject. As far as I see it works through `@Advice.DynamicValue` but seems that it is not available for the version I am using.

**Comment by serkan-ozal** [comment]
By the way, I am using `ForAdvice` in the following way:
``` java
            for (Map.Entry<? extends ElementMatcher, String> entry : getTransformers().entrySet()) {
                builder = builder
                        .type(getTypeMatcher())
                        .transform(
                                new AgentBuilder.Transformer.ForAdvice(Advice.withCustomMapping())
                                        .with(AgentBuilder.PoolStrategy.Default.EXTENDED)
                                        .include(ByteBuddyTest.class.getClassLoader())
                                        .advice(entry.getKey(), entry.getValue())
                        );
            }
```

**Comment by raphw** [comment]
Use:

```java
Advice.withCustomMapping().bind(SomeAnnotation.class, new OffsetMapping() { ... });
```

In the offset mapping, you have the instrumented method available. If the class is already processed using Byte Buddy's type pool with extended parsing, the debug information should be available.

**Comment by serkan-ozal** [comment]
Ok, thx. Now I am able to bind. But somehow, argument names are still like `arg0`, `arg1`, etc ... 

I had set pool strategy to `Default.EXTENDED` in the agent builder as mentioned above. When I decompile the class (or parse with Javassist), I can see the argument names but these are not available in the `OffsetMapping` somehow. Do I need to configure something more?

**Comment by serkan-ozal** [comment]
Ok, when I set pool strategy over `AgentBuilder` (not over `AgentBuilder.Transformer.ForAdvice`), it worked.

**Comment by raphw** [comment]
Yes, the agent builder provides the instrumented type and dependants, the advice provides the advice class.

**Comment by serkan-ozal** [comment]
By the way, thanks for your help. 

Even though the question is not related with this issue but I want to ask you that where should I look/start to implement (and register) a custom callback which will be invoked at each line in the method body?

**Comment by raphw** [comment]
For this you would need to use ASM. Byte Buddy is mainly focusing on instrumenting shapes of types which are stable. The closest you can get is to use `MemberSubstitution` that allows you to do instrumentation based on method calls and field accesses. I would not recommend you to change in-method code as such instrumentations are notoriously instable.

**Comment by raphw** [comment]
Closing as resolved.
