### ISSUE TITLE
Editing .class files

### ISSUE THREAD

**Issue by FSichinger** [raphw/byte-buddy#593]
I'm using ASM APIs to alter .class files of already compiled .jar libraries. Usually i want to add an extra interface, inject my code which works as a callback for my application, change method visibility etc.

My process utilizes using ClassReaders/Writers, ClassAdapters, MethodAdapters,... but let's be honest using asm in this way is is not very pleasant.

Does bytebuddy provide some easier abstraction which could make my life easier?

**Comment by raphw** [comment]
Yes, please refer to the documentation at bytebuddy.net for such information.

**Comment by raphw** [comment]
Closing this issue.
