### ISSUE TITLE
Instrument in java.lang.Thread not working while debugging

### ISSUE THREAD

**Issue by cngddflzw** [raphw/byte-buddy#594]
My code sample

```java
public class ThreadAdvisor {

	@Advice.OnMethodEnter
	public static void replaceValue() {
		System.out.println("test hacked");
	}
}

public class ThreadInstrumentTest {

	public static void main(String[] args) throws Exception {

		InstrumentTask task = inst -> {
			File temp = null;
			try {
				temp = Files.createTempDirectory("test_dir").toFile();
			} catch (IOException e) {
				e.printStackTrace();
			}
			UsingInstrumentation
					.of(temp, Target.BOOTSTRAP, inst)
					.inject(Collections.singletonMap(
							new ForLoadedType(ThreadAdvisor.class),
							ForClassLoader.read(ThreadAdvisor.class)
					));

			new AgentBuilder.Default()
					.with(StreamWriting.toSystemOut().withErrorsOnly())
					.with(StreamWriting.toSystemOut().withTransformationsOnly())
					.with(RedefinitionStrategy.REDEFINITION)
					.with(Default.REDEFINE)
					.ignore(none())
					.enableBootstrapInjection(inst, temp)
					.disableClassFormatChanges()
					.type(is(Thread.class))
					.transform((builder, typeDescription, classLoader, module) ->
							builder.visit(Advice.to(ThreadAdvisor.class)
									.on(ElementMatchers.named("getContextClassLoader"))))
					.installOn(inst);
		};

//		System.out.println("#### 1 " + Thread.currentThread().getContextClassLoader());
		System.out.println("#### 1 " + Thread.currentThread().getContextClassLoader());

		Instruments.start(task);

		System.out.println("### 2 " + Thread.currentThread().getContextClassLoader());
	}

}

```

When running as debug, the log "test hack" was not printed. While running as fine in Run mode

**Comment by raphw** [comment]
This is probably due to a class loading iregularity or your debugger is doing a retransformation that conflicts Byte Buddy. Try using a retransformation as a strategy instead.

**Comment by raphw** [comment]
Does this also happen when you run the application outside of an IDE? I assume that there is another agent active that overrides your instrumentation.

**Comment by cngddflzw** [comment]
@raphw I'm not sure what do you mean by "outside of an IDE" cause I don't know how to debug outside an IDE. What I can prove is that:

1. It works quite well in Running mode inside an IDE
2. I think there is another agent indeed, because you should add a VM option "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005" to the remote application if you want to do a remote debug. but I'm not sure what this agentlib actually do. I would dig it deeper about "jdwp" later, thanks

**Comment by cngddflzw** [comment]
Update:

I tried remote debug with "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", also works fine. Maybe there are something more in local debug mode in intellij idea.

**Comment by raphw** [comment]
IntelliJ attaches agents of its own, I assume this is where the problem roots.

**Comment by cngddflzw** [comment]
@raphw do you have any idea about this problem I can try? I've post an issue on the intellij idea issue tracks. I will report here when I get any progress.

**Comment by raphw** [comment]
That is really very IntelliJ specific, I have no idea, to be honest.

**Comment by cngddflzw** [comment]
ok, thanks @raphw , close it for now, will report here when I get any progress

**Comment by cngddflzw** [comment]
it could be resolved by a setting of Intellij Idea, see: https://youtrack.jetbrains.com/issue/IDEA-206160
