### ISSUE TITLE
Snippet for  byte-buddy-agent

### ISSUE THREAD

**Issue by clankill3r** [raphw/byte-buddy#598]
Why is there no snippet (as in maven etc.) for byte-buddy-agent?
Cause it could work in combination with the `ByteBuddyAgent.installOnOpenJDK()` or am I wrong there?
It is such a pain to add jar's to java projects.

**Comment by raphw** [comment]
I am not sure what you mean by "snippet". `ByteBuddyAgent` is released on Maven Central as *byte-buddy-agent*.

**Comment by clankill3r** [comment]
I meant this with snippet:

![screen shot 2019-01-29 at 10 16 54](https://user-images.githubusercontent.com/738650/51897474-17f9b300-23af-11e9-9c43-85c8b4093e15.png)

I just founded it, I was first looking here:
https://bintray.com/raphw/maven

But it was hidden under the small geen arrow.
