### ISSUE TITLE
Cannot access protected <constructor> from <subclass in another package> with byte-buddy ≥ 1.9.6

### ISSUE THREAD

**Issue by clo-vis** [raphw/byte-buddy#601]
The following code worked with byte-buddy until 1.9.5. Starting with 1.9.6 it throws an _IllegalArgumentException_: 

> Cannot access protected java.util.AbstractCollection() from class Foo
> 	at net.bytebuddy.implementation.MethodCall$Appender.toStackManipulation(MethodCall.java:3439)
> …

```
new ByteBuddy().subclass(java.util.AbstractCollection.class, ConstructorStrategy.Default.NO_CONSTRUCTORS)
                       .name("Foo")
                       .defineConstructor(Visibility.PUBLIC)
                       .intercept(MethodCall.invoke(java.util.AbstractCollection.class.getDeclaredConstructor()).onSuper())
                       .make()
                       .load(Bar.class.getClassLoader())
                       .getLoaded();
```

**Comment by raphw** [comment]
You are right, this is an overly strict visibility check that does not properly consider constuctors. I fixed a false negative in this release and introduced a false positive. Will be fixed in the next release.

**Comment by raphw** [comment]
Fixed on master for the next release.
