### ISSUE TITLE
Misleading documentation of method net.bytebuddy.dynamic.DynamicType.Default.Unloded.load(ClassLoader)

### ISSUE THREAD

**Issue by clo-vis** [raphw/byte-buddy#602]
The behavior of _DynamicType.Builder.make().load(classLoaderThatIsNotInjectionClassLoader)_ changed from 1.8.3 to 1.8.4 but the documentation doesn't reflect the change.

The documentation still ends with: 

> And otherwise, the types are injected into the provided class loader.

This is not true anymore for byte-buddy ≥ 1.8.4, when the "otherwise" case changed to _ClassLoadingStrategy.Default.WRAPPER_.  To keep the pre-1.8.4 behavior, one must now explicitly use _load(classLoader, ClassLoadingStrategy.Default.INJECTION)_.

**Comment by raphw** [comment]
You are right, thanks for pointing that out. It will be fixed in the next release.
