### ISSUE TITLE
Dynamic SynchronizationStrategy class selection fails on Java 11

### ISSUE THREAD

**Issue by eyalkoren** [raphw/byte-buddy#603]
A user of our agent reported (https://github.com/elastic/apm-agent-java/issues/395) the following when running our agent on WildFly 15 with Java 11:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by co.elastic.apm.agent.shaded.bytebuddy.dynamic.loading.ByteArrayClassLoader$SynchronizationStrategy$ForJava7CapableVm to method java.lang.ClassLoader.getClassLoadingLock(java.lang.String)
WARNING: Please consider reporting this to the maintainers of co.elastic.apm.agent.shaded.bytebuddy.dynamic.loading.ByteArrayClassLoader$SynchronizationStrategy$ForJava7CapableVm
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
While I couldn't reproduce this one (even when setting `--illegal-access=debug`) I debugged and saw that indeed ByteBuddy is using `SynchronizationStrategy$ForJava7CapableVm`, which seems to be wrong. Looks like the problem is that https://github.com/raphw/byte-buddy/blob/1107d3ffd6d390b348107c8887767cfd13f2686b/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/ByteArrayClassLoader.java#L250 fails in Java 11 (tested with openjdk-11.0.1.13) with `Method threw 'java.lang.reflect.InvocationTargetException' exception` (succeeds in openjdk 10.0.2), causing https://github.com/raphw/byte-buddy/blob/1107d3ffd6d390b348107c8887767cfd13f2686b/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/ByteArrayClassLoader.java#L430 to fall back to the Java 7 implementation.

**Comment by raphw** [comment]
This issue is a bit confusing as this method should exist as of Java 9. 

Could you ask your customer to get hold of the exception, e.g, by setting a breakpoint. I would not know how this can even happen.

**Comment by eyalkoren** [comment]
I set a breakpoint myself and tested it within our code, here is what I get when invoking `Class.forName("java.lang.invoke.MethodHandles").getMethod("lookup").invoke(null)`:
```
Caused by: java.lang.IllegalArgumentException: illegal lookupClass: class co.elastic.apm.agent.impl.ElasticApmTracer
 	at java.base/java.lang.invoke.MethodHandleStatics.newIllegalArgumentException(MethodHandleStatics.java:123)
 	at java.base/java.lang.invoke.MethodHandles.reflected$lookup(MethodHandles.java:117)
 	at co.elastic.apm.agent.impl.ElasticApmTracer.activate(ElasticApmTracer.java:408)
 	...
```
So, when the `java.lang.reflect.Method` returned by `Class.forName("java.lang.invoke.MethodHandles").getMethod("lookup")` is invoked, what actually gets invoked is `MethodHandles#reflected$lookup`:
```
    /**
     * This reflected$lookup method is the alternate implementation of
     * the lookup method when being invoked by reflection.
     */
    @CallerSensitive
    private static Lookup reflected$lookup() {
        Class<?> caller = Reflection.getCallerClass();
        if (caller.getClassLoader() == null) {
            throw newIllegalArgumentException("illegal lookupClass: "+caller);
        }
        return new Lookup(caller);
    }
```
Indeed in our case both this class I set the breakpoint at and the shaded ByteBuddy classes are loaded from the bootstrap class loader (hence `caller.getClassLoader() == null`).
When I invoke the actual `lookup` method not through reflection from the same class, it works fine and returns a valid Lookup:
<img width="1285" alt="screen shot 2019-02-05 at 6 51 14" src="https://user-images.githubusercontent.com/41850454/52254022-f1d69480-2913-11e9-8f89-76ff3b6c2b00.png">
So I guess the easy solution is to determine the Java version in a different way, and `MethodHandles#lookup` not though reflection, but just plain Java compiled in class that is not loaded unless the right Java version is used.

**Comment by eyalkoren** [comment]
Note, this might be the same behaviour for Java 10 as well, where I see the same Javadoc for `MethodHandles#reflected$lookup`

**Comment by raphw** [comment]
Ah, I have not considered that you are on the boot loader.

I do not want to add a compile-time dependency to Java 7 as I still rely on testing the build on 5 and 6 but I can override the mechanism when loaded on the boot loader.

**Comment by eyalkoren** [comment]
What I suggested is to compile the code that has dependency on Java 7/8/whatever in a separate class and call that class through reflection only when running on the suitable Java version, so that it's safe enough.
Anyway, if there's an easier/better way to overcome this- even better 😄 .
Thanks a lot!

**Comment by raphw** [comment]
You are welcome. It's fixed on master and will be part of the next release, so I am closing this. Can you use JitPack in the meantime since you are shading anyways?
