### ISSUE TITLE
@Delegates annotation 

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#61]
```
@Delegates([f1, f2])
class A {
F1 f1;
F2 f2
}
```

Can you add easy to use annotation to generate delegation pattern (https://en.wikipedia.org/wiki/Delegation_pattern)

**Comment by raphw** [comment]
Delegation is already supported using the `MethodDelegation` and the `Forwarding` classes. An annotation cannot offer the same flexibility and readability to implement similar behavior.

**Comment by sirinath** [comment]
Annotations will be easy to use though less flexible

**Comment by raphw** [comment]
I agree that there could be many other ways to make specific use cases easier. My concern is to make the library difficult to maintain by allowing for such feature-creep. The current `MethodDelegation` allows for any thinkable delegation binding and it already is very extendable by allowing for custom annotations and more. If you have such a demand, you can always implement it the way that suits you best. If you need help with a particular use-case, please feel free to ask.
