### ISSUE TITLE
Cannot enhance sun.net.www.protocol.http.HttpURLConnection

### ISSUE THREAD

**Issue by 1923982924** [raphw/byte-buddy#614]
Injecting classes into the bootstrap class loader was not enabled when use byte-buddy to enhance sun.net.www.protocol.http.HttpURLConnection

**Comment by raphw** [comment]
You can enable bootstrap injection in the agent builder API.

**Comment by xyzmonday** [comment]
I want to enhance sun.net.www.protocol.http.HttpURLConnection , and enable bootstrap injection in the agent builder API like :
new AgentBuilder.Default(byteBuddy)
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
                .ignore(ElementMatchers.nameStartsWith("org.slf4j."))
                .ignore(ElementMatchers.nameStartsWith("org.apache.logging."))
                .ignore(ElementMatchers.nameStartsWith("org.groovy."))
                .ignore(ElementMatchers.nameContains("javassist"))
                .ignore(ElementMatchers.nameContains(".asm."))
                .enableBootstrapInjection(instrumentation, new File(folder))
                .type(PluginManager.buildMatch())
                .transform(new Transformer())
                .with(new Listener())
                .installOn(instrumentation);
but, agent will throw exception:
 java.lang.NoClassDefFoundError: cn/touna/agent/core/plugin/interceptor/enhance/EnhancedInstance

**Comment by raphw** [comment]
In this case, add your interceptor to a seperate jar and include it on the boot path using Instrumentation. appendToBootSearchPath

**Comment by 1923982924** [comment]
@xyzmonday Is it OK?

**Comment by 1923982924** [comment]
@raphw It's not found Target to ClassInjector.UsingInstrumentation in 1.9.10 version，but it's net.bytebuddy.dynamic.loading.ClassInjector.UsingInstrumentation.Target.   Can you help me?

**Comment by raphw** [comment]
Have you tried to debug this by registering a listener? Try to include .with(AgentBuilder.Listener.StreamWriting.toSystemOut()) and see what is printed.

**Comment by raphw** [comment]
Please reopen if there are further questions.
