### ISSUE TITLE
Add a method that access fields

### ISSUE THREAD

**Issue by WellingtonCosta** [raphw/byte-buddy#615]
Hi,

I'm using Byte Buddy with Java Agents to perform runtime code generation and I would like to generate a method inside a class that is annotated with a specific annotation and the method access fields of the class and print its values.

For example:

```java
@Foo public class Person {

  private String name;
  private String email;
  private String phone;

  // the generated method
  public void generated() {
    System.out.println("name = " + this.name + ", email = " + this.email + ", phone = " + this.phone);
  }

}
```

Any idea?

**Comment by raphw** [comment]
Use an `AgentBuilder.Default`, match all types annotated with `Foo` using an `ElementMatcher` and use the `defineMethod` API. You would probably need to combine some `StackManipulation`s to write such a custom expression efficiently. Have a look at `FieldAccessor` and `MethodInvokation` as well as `TextConstant`.

**Comment by WellingtonCosta** [comment]
Yeah. I already using `AgentBuilder.Default`, matching all classes annotated with `@Foo` and defining the `generated()` method with `defineMethod`. But I don't know exactly how to use `StackManipulation`, `FieldAccessor`, `MethodInvokation` and `TextConstant`.

```java
public static void premain(String agentArgs, Instrumentation instrumentation) {
        new AgentBuilder.Default()
                .with(new AgentBuilder.InitializationStrategy.SelfInjection.Eager())
                .type(isAnnotatedWith(Foo.class))
                .transform(new AgentBuilder.Transformer() {
                    @Override public DynamicType.Builder<?> transform(
                        DynamicType.Builder<?> builder,
                        TypeDescription typeDescription, 
                        ClassLoader classLoader, 
                        JavaModule javaModule
                    ) {
                        // how to proceed from here?
                        return builder;
                    }
                })
                .installOn(instrumentation);
    }
```

**Comment by raphw** [comment]
On second thought, you can do all this using MethodCall. The outermost call is println on System.out. As an argument, you use the result of another call whete you nest invocations on a constructed StringBuilder and its append methods that you complete with a call to toString.

**Comment by WellingtonCosta** [comment]
Nice! Do you have some example about this?

**Comment by raphw** [comment]
To create a `StringBuilder` you call `MethodCall.construct(StringBuilder.class.getConstructor())`

You can then call the append to the string builder like: `MethodCall.invoke(StringBuilder.class.getMethod("append", Object.class)).onMethodCall(...).withField(...)` where you start with the initial string builder and then reiterate for every field or constant supplying the last input to the next instance.

You would have to adjust the method based on the field type, if the type is primitive, for this to work. In the end, you have to do a final method call on `toString`.
