### ISSUE TITLE
How to Use AgentBuilder  replace  the method of class

### ISSUE THREAD

**Issue by Aleishus** [raphw/byte-buddy#618]
I can redefine the class to replace `Foo`'s method to `Bar`'s  like this ：
```java
   ByteBuddy byteBuddy = new ByteBuddy();
        byteBuddy
                .redefine(Bar.class)
                .name(Foo.class.getName())
                .make()
                .load(Foo.class.getClassLoader(),
                        ClassReloadingStrategy.fromInstalledAgent());

Foo foo = new Foo()
foo.m()
// output is bar
```
How can I  use `AgentBuilder` do the same work , replace  all `Foo`'s methods  , not delegate
```java
  new AgentBuilder.Default()
                .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
                .with(RedefinitionStrategy.RETRANSFORMATION)
                .type(ElementMatchers.is(Foo.class))
                .transform(
                        ( builder, typeDescription, classLoader, module ) -> 
                              builder.method(ElementMatchers.any()).intercept( //how to write ?)

).installOnByteBuddyAgent();

```
Thks!

**Comment by raphw** [comment]
There is no straight-forward way to do this since you have no guarantee that `Foo` and `Bar` are compatible but in theory, you can create a new `DynamicType.Builder` from the transformer as you already demonstrate creating one. Skip everything from the call to `make` and return it from the transformer.

**Comment by Aleishus** [comment]
Thx!
 This can work.
```java
return new ByteBuddy().redefine(Bar.class).name(Foo.class.getName());
```
But I wish you to implement a new `Implementation` that can specify some  `Bar`'s methods  to replace `Foo`'s, if `Foo` and `Bar` are compatible.

**Comment by raphw** [comment]
I have answered you on StackOverflow: https://stackoverflow.com/questions/54968317/how-to-use-agentbuilder-replace-the-method-of-class/55032434#55032434
