### ISSUE TITLE
How can I transfer field values of the same name to a generated class?

### ISSUE THREAD

**Issue by Shaunwild97** [raphw/byte-buddy#619]
Given the following class:

```java
@Networkable
public class NetworkComponent extends Component {
    @NetworkSync
    private int entityId;

    @NetworkSync
    private String type;
}
```

I have used the library to generate a new runtime class with the following form

```java
public class NetworkComponent_ND {
  public int entityId;
  public String type;
}
```

It simply creates a POJO from the fields annotated with `@NetworkSync`, super simple stuff. Now the next step, I want to rebase the initial `NetworkComponent` class to implement my `INetworkable` interface, which requires the following methods to be implemented with byte buddy:

`T getNetworkData();`
Will return a  new instance of NetworkComponent_ND with its fields set to the same values as the original NetworkComponent class, for example:

```java
public NetworkComponent_ND getNetworkData() {
  NetworkComponent_ND result = new NetworkComponent_ND();
  result.entityId = this.entityId;
  result.type = this.type;
  return result;
}
```

`void applyNetworkData(T t);`
Will set the values in the NetworkComponent instance to the values of the NetworkComponent_ND which is passed in as a parameter, example:

```java
public void applyNetworkData(NetworkComponent_ND nd) {
  this.entityId = nd.entityId;
  this.type = nd.type;
}
```

`Class<T> getNetworkDataType();`
Will return the NetworkComponent_ND class (This part I've done already)

The Generic type <T> shown above could be any other type which had been generated using the method at the top of the question. The code examples given above are only equivalents of what I'd like to generate using byte buddy.

So my question is: How can I implement the former two methods onto the rebased class which will do the expected behaviour in a generic way which would work for any class above?

Sorry for the huge block of text, but I'm completely stuck. Thanks

**Comment by raphw** [comment]
If you want to implement more complex method implementations like the ones you mention, you would need to assemble `StackManipulation`s that represents the above code.

Mainly, you would need to look into `FieldAccessor` to get and set fields and into `MethodInvocation` to create the synthetic class.

**Comment by Shaunwild97** [comment]
Link to documentation on stack manipulation? I can't find any on google?

**Comment by raphw** [comment]
Unfortunately, not all too much. The best source is the javadoc of those classes. You basically have to make your own `Implementation.Simple` where you provide the byte code using the mentioned instances. You should read up the basics of byte code to make sense of it. ASM has a great tutorial.
