### ISSUE TITLE
fails to instrument threadPoolExecutor by bytebuddy

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#620]
I encounter the same problem with this post.
https://stackoverflow.com/questions/49321938/instrument-in-java-level-using-byte-buddy/55032131#55032131

when I use the code instrument threadpoolexecutor,

new AgentBuilder.Default()
            .ignore(ElementMatchers.none())
            .type(ElementMatchers.nameContains("ThreadPoolExecutor"))
            .transform((builder, type, classLoader, module) -> builder
                    .visit(Advice.to(ThreadPoolExecutorAdvice.class).on(ElementMatchers.any()))
            ).installOn(instrumentation);

I got this error, How to solve it?

 java.lang.IllegalStateException: Cannot represent public org.apache.tomcat.util.threads.ThreadPoolExecutor(int,int,long,java.util.concurrent.TimeUnit,java.util.concurrent.BlockingQueue,java.util.concurrent.RejectedExecutionHandler) as given method constant

**Comment by raphw** [comment]
I assume your advice requests a `Method` as an injected parameter while you are instrumenting a `Constructor`.

**Comment by zheyiyi** [comment]
Insead of doing this in the program, 

ExecutorService exec = Executors.newFixedThreadPool(2);
Runnable runnable = TtlRunnable.get(runnable);
exec.execute(new LiftOff());

I want to do this in the program
ExecutorService exec = Executors.newFixedThreadPool(2);
exec.execute(new LiftOff());      

And in this agent, 
public class MultiThreadAdvice {
    public static Logger logger = LoggerFactory.getLogger(MultiThreadAdvice.class);

    @Advice.OnMethodEnter
    private static Span before(@Advice.Argument(value = 1, readOnly = false) Runnable runnable, @Advice.Origin Method method) {
        logger.info(method.toString() + " start to run");


        runnable = TtlRunnable.get(runnable);

        return TraceManager.executorIntercept(method, runnable);
    }
}

**Comment by raphw** [comment]
The value indicates what index the argument has that you require.

**Comment by zheyiyi** [comment]
oh, I see if i have a funtion run(string a,int b),   @Advice.Argument(value = 0, readOnly=false) , the value 0 is related to string a, right?

**Comment by raphw** [comment]
yes.
