### ISSUE TITLE
how to instrument executor in spring boot application

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#621]
I use spring boot application to set up microservice, I want to use multithread in my spring boot application. Any one can teach me how to instrument executor's execute method? I use bytebuddy to instrument it, but it doesn't work. I cannot use bytebuddy to instrument executor in spring boot evironment. Any one can help?

 ExecutorService exec = Executors.newFixedThreadPool(2);
 for (int i = 0; i < 5; i++){
        exec.execute(new LiftOff());
 }

**Comment by raphw** [comment]
What have you tried? You would need to run a Java agent for this.

**Comment by zheyiyi** [comment]
Thanks, I got it worked.

**Comment by dennis0721** [comment]
> Thanks, I got it worked.

hello, i am also try to find how to intercept java's executor submit method with bytebuddy, the question  is familiar with yours, can you tell me how did you do, thank you very much!!!

**Comment by raphw** [comment]
Look after implementing Java agents with Byte Buddy and you should find a bunch of sources.

**Comment by dennis0721** [comment]
> Look after implementing Java agents with Byte Buddy and you should find a bunch of sources.

i have read a lot articles, but i am facing a problem, when i just use "System.out.print()" in the interceptor(used "@Advice.OnMethodEnter"), it worked; but, when i use another class with a static method, it will throw a NoClassDeFoundException, i don't know why, i start the install process of AgentBuilder in the starting method of SpringApplicationRunListener.

**Comment by raphw** [comment]
Because of class loaders. The static method will be part of your agent in the system class loader. To make universally visible classes, you have to inject your code into the bootstrap class loader. The `Instrumentation` interface has a method for it.

**Comment by dennis0721** [comment]
ok, thank you very much, i will try later and post the result as soon as possible!
