### ISSUE TITLE
Copy of super class' methods to subclass may conflicts with some serializer tool 

### ISSUE THREAD

**Issue by honganan** [raphw/byte-buddy#622]
When instrumenting subclass, I found byte-buddy copies some methods of super class to subclass. This makes these methods' declaring class changed from super to sub. And this mechanism seems a little strangle. It conflict with a serializing tool I am using called fastJSON. 
If there is a better scheme to replace this mechanism from now?

The fastJSON tool's relative code likes this:
```java
// support builder set
Class<?> returnType = method.getReturnType();
 if (!(returnType.equals(Void.TYPE) || returnType.equals(method.getDeclaringClass()))) {
       continue;
}
```
The method's declaring class changed makes it jumped to set this property.

**Comment by raphw** [comment]
Byte Buddy needs to redeclare methods if you instrument them as a class manipulation of a given class cannot affect its super classes. What are you trying to do? Maybe there is a better way.

**Comment by honganan** [comment]
I just found this conflicts with another tool and feel doubt. For now it seems reasonable to redeclare methods to protect the super classes. If I use redefine or subClass will not have this problem, right?
Thank you for answering.

**Comment by raphw** [comment]
You can think of Byte Buddy as a tool that allows you to write Java code at runtime. If you redeclare a method, it is like implementing it in the class you are instrumenting. By redefining methods, you replace the original methods; by rebasing them, you copy the original code to another method and reimplement the method with the original signature. By subclassing a class, you are doing exactly that.
