### ISSUE TITLE
Why type can narrow down transformer in bytebuddy

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#624]
I don't know why type can narrow transform?

        new AgentBuilder.Default(byteBuddy).type(
            ElementMatchers.nameStartsWithIgnoreCase("org.springframework.web.client.RestTemplate"))
            .transform(new Transformer())
            .with(new Listener())
            .installOn(instrumentation);

Can I ask What is the principle of type can narrow down transformer?

I know type will be as argument(typedescription ) go to transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule).

      private static class AgentTransformer implements AgentBuilder.Transformer{

        private PluginFinder pluginFinder;
        public AgentTransformer(PluginFinder pluginFinder) {
            this.pluginFinder = pluginFinder;
        }

        public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
       System.out.println(typeDescription);
    }}

The result of print will be org.springframework.web.client.RestTemplate.
But Why does it narrow down?

**Comment by raphw** [comment]
Instrumentation is expensive and the fewer classes you choose to transform the less work has to be done in terms of I/O or the JVM runtime. This is mainly about performance but also about observability.
