### ISSUE TITLE
Method delegation adds property even when none of methods matches

### ISSUE THREAD

**Issue by honganan** [raphw/byte-buddy#626]
How are you! Today I found the method delegation function will add an object of my delegation class to target class' properties, even when no method matched. Here is my code script:
```java
newClassBuilder =
                        newClassBuilder.method(not(isStatic()).and(instanceMethodsInterceptPoint.getMethodsMatcher()))
                            .intercept(
                                MethodDelegation.withDefaultConfiguration()
                                    .to(new InstMethodsInter(interceptor, classLoader))
                            );
```
the `instanceMethodsInterceptPoint.getMethodsMatcher()` returns a method annotation matcher which will not match my problem target class. And I found target class have properties like `public static /* synthetic */ InstMethodsInter delegate$cd5h9l0;` when I use jad decompile it. Is it normal behavior or my usage problem? Thank you very much!

**Comment by raphw** [comment]
Yes, this behavior is normal as the class preparation and the method instrumentation are seperate steps in the process. This is a conscious choice as instrumentations might add methods under the instrumentation process which could not be supported if the field was missing at this stage.

You could also wrap the delegation in your own `Implementation` instance where you only delegate if the instrumented type is matching a certain form.

**Comment by honganan** [comment]
Ok I see. I have avoid this by some way. Thank you for answer me!

**Comment by raphw** [comment]
Closing this as resolved.
