### ISSUE TITLE
Add a annotation to a method

### ISSUE THREAD

**Issue by Aleishus** [raphw/byte-buddy#627]
Hi, 
 I want to add an annotation to a method and not to change the original method body.

example:

origin

```java
 public class Bar {


  public static String make() {
   return "sss";
  }

  public  String m(){
   System.out.println("haha");
   return "bar" ;
  }
}
```
 redefined
```java
 public class Bar {


  public static String make() {
   return "sss";
  }

 
@MyAnnotation
  public  String m(){
   System.out.println("haha");
   return "bar" ;
  }
}

```

```java
byteBuddy
                .redefine(Bar.class)
                .method(ElementMatchers.named("m")).intercept(//how to use)
                .annotateMethod(new MyAnnotation() {

                    @Override
                    public Class<? extends Annotation> annotationType() {
                        return MyAnnotation.class;
                    }
                })
                .make().toJar(new File("/tmp/sss.jar"));
```

and I don't know how to write the intercept method that don't change the method body just add an Annotation.

THX!

**Comment by raphw** [comment]
This is an emberassing hole in the API as this should of course be possible but was not thought of as the annotation capabilities were added after the method interception. I will need to adress this some time.

If it works for you, you can rebase a class and use `SuperMethodCall.INSTANCE` as the interception.

**Comment by raphw** [comment]
From Byte Buddy 1.10.0 it will be possible to do so using `MemberAttributeExtension.ForMethod`.

**Comment by chook** [comment]
@raphw i believe intercepting and changing a method to an ExceptionMethod did remove the original method annotation, can this be fixed with the `MemberAttributeExtension.ForMethod` latest addition? should I file a separate issue?

**Comment by raphw** [comment]
This should not happen, are you sure about this? Could you make a reproducer in this case?

**Comment by chook** [comment]
looks like i misunderstood a Spring annotation.. it's probably there and i thought it will trigger something but it did not. thanks

**Comment by SimplyAmuthan** [comment]
So How to use this in 2025, I want to add an annotation to a method of an fully built object, can you give me some example ?
