### ISSUE TITLE
How to insturment filter by bytebuddy

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#628]
if I have a self-defined filter in spring boot, I can instrument it by bytebuddy.

The self-defined filter is that:

    package com.elephone.TransactionFilter
    import javax.servlet.*;
    
    @Component
    public class TransactionFilter implements Filter {

    private final Logger logger = LoggerFactory.getLogger(TransactionFilter.class);

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException, ServletException {

        HttpServletRequest req = (HttpServletRequest) request;
        logger.info(
                "Starting a transaction for req : {}",
                req.getRequestURI());

        chain.doFilter(request, response);

        logger.info(
                "Committing a transaction for req : {}",
                req.getRequestURI());
    }
    }

My butebuddy is that:

     new AgentBuilder.Default(bytebuddy)
                .type(ElementMatchers.named(**"com.elephone.TransactionFilter"**))
                .transform(new AgentTransformer())
                .installOn(instrumentation);

But if my filter name can be changed, i want a generic edition, How should I write my bytebuddy?

I use   
    
    new AgentBuilder.Default(bytebuddy)
                .type(ElementMatchers.named("javax.servlet.Filter"))
                .transform(new AgentTransformer())
                .installOn(instrumentation);

But it doesn't work.

**Comment by raphw** [comment]
Do you want to instrument all subclasses? In this case, your matcher needs to reflect that: `hasSuperType(named("..."))`

**Comment by raphw** [comment]
Please reopen this ticket if there is a follow-up.
