### ISSUE TITLE
How to instrument createRequest in restTemplate by butebuddy

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#630]
I can instrument doExecute, handResponse function in restTemplate class.
In restTemplate class, there is a function:

     @Nullable
    protected <T> T doExecute(URI url, @Nullable HttpMethod method, @Nullable RequestCallback requestCallback, @Nullable ResponseExtractor<T> responseExtractor) throws RestClientException {
        Assert.notNull(url, "URI is required");
        Assert.notNull(method, "HttpMethod is required");
        ClientHttpResponse response = null;

        Object var14;
        try {
            ClientHttpRequest request = this.createRequest(url, method);
            if (requestCallback != null) {
                requestCallback.doWithRequest(request);
            }

            response = request.execute();
            this.handleResponse(url, method, response);
            var14 = responseExtractor != null ? responseExtractor.extractData(response) : null;
        } catch (IOException var12) {
            String resource = url.toString();
            String query = url.getRawQuery();
            resource = query != null ? resource.substring(0, resource.indexOf(63)) : resource;
            throw new ResourceAccessException("I/O error on " + method.name() + " request for \"" + resource + "\": " + var12.getMessage(), var12);
        } finally {
            if (response != null) {
                response.close();
            }

        }

        return var14;
    }

I can instrument doExecute, handleResponse function, but I cannot intrument createRequest function by the bytebuddy aggent builder.

    new AgentBuilder.Default(bytebuddy).with(AgentBuilder.Listener.StreamWriting.toSystemError())
                .type(  ElementMatchers.named("org.springframework.web.client.RestTemplate")
    )
                .transform(new AgentTransformer())
                .installOn(instrumentation);

private static class AgentTransformer implements AgentBuilder.Transformer{

   
            public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {

           ElementMatcher.Junction<MethodDescription>  junction = not(isStatic()).and( ElementMatchers.named("createRequest"))
            return builder.visit(Advice.to(Class.forName(interceptor)).on(junction);

            }

One thing I found that is createRequest function is defined in the HttpAccessor.class but handleResponse, and doExecute are defined in the RestTemplate.class

**Comment by raphw** [comment]
You have to specify the exact classes that you want to instrument. You can also match all classes in a hierarchy by using `hasSuperType(named(...))` if you want to do that.

**Comment by zheyiyi** [comment]
Can you give an example what hasSuperType do?

**Comment by zheyiyi** [comment]
if we write hasSuperType(named(org.springframework.web.client)), bytebuddy will scan all subclass which has prefix org.springframework.web.client such as org.springframework.web.client.RestTemplate?

**Comment by raphw** [comment]
If you want to match by a package, you need to use the `nameStartsWith` matcher.

**Comment by raphw** [comment]
I am closing this issue until there is a follow-up.
