### ISSUE TITLE
Put module descriptor at top level

### ISSUE THREAD

**Issue by jrostosk** [raphw/byte-buddy#633]
Version 1.9.10.  module-info.class should be at top-level of MR-JAR file, not in META-INF/versions/9.  While module descriptors *can* be versioned using the MR-JAR mechanism, like any versioned class, any .class file in a "versions" directory should *also* be at the top-level (for Java 8 and earlier).

If you placed module-info.class in META-INF/versions/9 to "hide" it from Java 8, there was no need to do this, as Java 8 doesn't see any classes in META-INF anyway.

The MR-JAR mechanism is completely distinct from JPMS, and with it, any versioned class in META-INF/versions should also appear at the top level (for pre-Java 9 releases).  Furthermore, versioned classes should expose the same public API, as a matter of principle (i.e., for the sanity of your library users) - this is the reason that 'any .class file in a "versions" directory should *also* be at the top-level (for Java 8 and earlier)'.

I encountered this while using the "Java 11 ready" Hibernate 5.4.2, which uses Byte Buddy 1.9.10 internally.  I am required to add an "--add-modules net.bytebuddy" argument at runtime, otherwise this module is not found.

Lastly, setting Multi-Release to true in the manifest file implies that you indeed have multiple versions of a class in the JAR, but alas this is not actually the case here.

**Comment by raphw** [comment]
This should not be necessary and when I run an example application, the Byte Buddy module is picked up just fine. Is Hibernate using a module-info.class already? If this does not work, I would expect a bug in the JVM. Can you create a small reproduction for this?

**Comment by raphw** [comment]
I decided to retain the module descriptor where it is now as most tooling seems to handle this correctly while more tooling breaks. I expect module handling code to adjust to this location over time, too whereas many legacy tools are dormant such that I expect a better long term outcome for it.
