### ISSUE TITLE
gradle-plugin do not support Gradle 5.x

### ISSUE THREAD

**Issue by wooyea** [raphw/byte-buddy#635]

**Comment by raphw** [comment]
Too bad, they probably broke the plugin API.

I will need to look into it but please submit a PR if you need this feature. It is not currently on my priority list.

**Comment by raphw** [comment]
In this context, I think it would be a good idea to remove the Gradle-Maven bridge altogether as in:

https://stackoverflow.com/questions/27555560/how-can-i-build-a-gradle-plugin-with-maven

**Comment by raphw** [comment]
Maybe this is an opportunity to fix the build for Gradle on CI. Seems like Spring got it working: https://github.com/spring-projects/spring-boot/commit/9b15e6b5a3c0fc18372f532063bb43f25abcf984#diff-44c691f1cc50d18de4be31c07f38dca3

**Comment by raphw** [comment]
Can you check again? I reworked the plugin. Do you have a stacktrace?

**Comment by raphw** [comment]
The entire build part has been refactored.
