### ISSUE TITLE
failed to match java.util.concurrent.Future

### ISSUE THREAD

**Issue by mliu111477** [raphw/byte-buddy#636]
(hasSuperType(erasure(name(equals(java.util.concurrent.Future)))) and not(isInterface()))
this is my type string

did not invoke AgentBuild#transform method

**Comment by raphw** [comment]
Are you retransforming? The class is most likely loaded when you run your agent.

Also, did you adjust your ignore matcher.

**Comment by mliu111477** [comment]
> Are you retransforming? The class is most likely loaded when you run your agent.
> 
> Also, did you adjust your ignore matcher.

I have retransforming, also I check my code, no ignore matcher.
I make a simple example code like this:
![image](https://user-images.githubusercontent.com/3417650/56104097-dec1ef80-5f68-11e9-92e5-c34c97fbfecf.png)
This is running code:
![image](https://user-images.githubusercontent.com/3417650/56104146-26e11200-5f69-11e9-910c-029f5cab674b.png)

This logger is never output.

**Comment by jpfourny** [comment]
There is an implicit matcher which ignores all classes from bootstrap class loader (which covers your case). You need to explicitly define an alternative matcher that does not ignore the classes you expect to be transformed.

Take a look at net.bytebuddy.agent.builder.AgentBuilder.Default.Default(ByteBuddy). You will find a default ignore matcher like this:

```
new RawMatcher.Disjunction(
                            new RawMatcher.ForElementMatchers(any(), isBootstrapClassLoader()),
                            new RawMatcher.ForElementMatchers(nameStartsWith("net.bytebuddy.").or(nameStartsWith("sun.reflect.")).<TypeDescription>or(isSynthetic())))
```

**Comment by mliu111477** [comment]
> There is an implicit matcher which ignores all classes from bootstrap class loader (which covers your case). You need to explicitly define an alternative matcher that does not ignore the classes you expect to be transformed.
> 
> Take a look at net.bytebuddy.agent.builder.AgentBuilder.Default.Default(ByteBuddy). You will find a default ignore matcher like this:
> 
> ```
> new RawMatcher.Disjunction(
>                             new RawMatcher.ForElementMatchers(any(), isBootstrapClassLoader()),
>                             new RawMatcher.ForElementMatchers(nameStartsWith("net.bytebuddy.").or(nameStartsWith("sun.reflect.")).<TypeDescription>or(isSynthetic())))
> ```

Ok, I see.
But I see the code, I don't know how to remove this default ignore matcher.
I have check net.bytebuddy.agent.builder.AgentBuilder.Default#Default(net.bytebuddy.ByteBuddy), It will add in this method, I have no idea how to don't add this ignore matcher, can you give me an example?
sorry for my poor english.

**Comment by raphw** [comment]
In the simplest case, you could set the matcher by `.ignore(none())` but this will most likely not work. Byte Buddy excludes the boot loader and the `net.bytebuddy.*` namespace by default to avoid class loading circularities which occur quickly if Byte Buddy uses a class that is first loaded during an instrumentation process.

Instrumenting `Future` should be fine, you could therefore mimic the default ignore matcher but add a rule to include Future.

**Comment by mliu111477** [comment]
> In the simplest case, you could set the matcher by `.ignore(none())` but this will most likely not work. Byte Buddy excludes the boot loader and the `net.bytebuddy.*` namespace by default to avoid class loading circularities which occur quickly if Byte Buddy uses a class that is first loaded during an instrumentation process.
> 
> Instrumenting `Future` should be fine, you could therefore mimic the default ignore matcher but add a rule to include Future.

It's worked, thx.
But I also have another question, I saw I need to add enableBootstrapInjection(..) to make it work, I also need to make this class implement my custom interface. Interface is define in my agent.jar. 
When I try to run this code, It throw an NoClassDefFoundError Exception.

Agent code Like this:
![image](https://user-images.githubusercontent.com/3417650/56123013-3a5e9e00-5fa6-11e9-8f5f-1344af06ed4f.png)
and this red circle class define in agent.jar.
![image](https://user-images.githubusercontent.com/3417650/56123171-814c9380-5fa6-11e9-817c-4d9f83dba047.png)


This is Running code:
![image](https://user-images.githubusercontent.com/3417650/56123197-94f7fa00-5fa6-11e9-9ae1-09c4cda9c12b.png)
![image](https://user-images.githubusercontent.com/3417650/56123222-a2ad7f80-5fa6-11e9-8246-fbde5e702131.png)

**Comment by raphw** [comment]
What class are you adding this interface to, to the `Future` class? This might not work if the class is already loaded as you cannot change the shape of a class.

Otherwise, the problem is that the class is in your agent jar, not on the bootstrap loader. You would have to include such files to the bootstrap class loader using `Instrumentation::appendToBootSearchPath` rather then in your agent which will be loaded in the system class loader.

**Comment by mliu111477** [comment]
> What class are you adding this interface to, to the `Future` class? This might not work if the class is already loaded as you cannot change the shape of a class.
> 
> Otherwise, the problem is that the class is in your agent jar, not on the bootstrap loader. You would have to include such files to the bootstrap class loader using `Instrumentation::appendToBootSearchPath` rather then in your agent which will be loaded in the system class loader.

ok, thx.i close it.
