### ISSUE TITLE
two function with different aguments, how to instrument one of them

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#638]
if we have two function with the same name but different aguments, I only want to intrument one of them, how can I do it?

    package sun.net.www.protocol.http;
    public class Handler extends URLStreamHandler {

        protected URLConnection openConnection(URL var1) throws IOException {
        return this.openConnection(var1, (Proxy)null);
    }

    protected URLConnection openConnection(URL var1, Proxy var2) throws IOException {
        return new HttpURLConnection(var1, var2, this);
    }
}

**Comment by raphw** [comment]
All ElementMatchers are chainable. Just refine your condition usimg 'and'

**Comment by raphw** [comment]
Please reopen if there are further questions.
