### ISSUE TITLE
how to get arguments from bytebuddy

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#639]
When I instrument this function in my service:

     public void invoke(StepData stepData){
        System.out.println("55555");
        this.stepData = stepData;
        if(workAroundService.contains(stepData.getStepParams().getTargetService())) DMEWorkaround();
        else DME2();
    }

In my interceptor, I need to extract stepData by cast Object args[0] to StepData type , But in my interceptor, I don't have the type StepData, it is a class in service, What should I do？

     @Advice.OnMethodEnter
    private static Span Enter(@Advice.Origin Method method, @Advice.AllArguments Object[] args){
        logger.info(method.toString() + " start to run");
        args[0]--------------how to change object type to StepData, I cannot cast because
        return null;

    }

**Comment by raphw** [comment]
Just use `@Advice.Argument(0)` which is also more cost efficient.

**Comment by raphw** [comment]
Please reopen if there are further questions.
