### ISSUE TITLE
what are their meaning for the two function

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#640]
Can I ask what do they do， what are their meaning？
 
new TypeDescription.ForLoadedType(MyInterceptor.class)
ClassFileLocator.ForClassLoader.read(MyInterceptor.class).resolve()

**Comment by raphw** [comment]
The former method describes the type in Byte Buddy's type description format, the latter reads the class's byte code from the class's class loader.

**Comment by zheyiyi** [comment]
Thanks, Can you continue to explain more about this statement.

     File temp = Files.createTempDirectory("tmp").toFile();
     ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, inst).inject(Collections.singletonMap(
                new TypeDescription.ForLoadedType(MyInterceptor.class),
                ClassFileLocator.ForClassLoader.read(MyInterceptor.class).resolve()));

**Comment by raphw** [comment]
It means that the type `MyInterceptor` is described by a specific byte code representation. If the loaded class was not availble, you could use a different type description, if the byte code was already provided by for example an agent, you could supply that byte code. Therefore, both parameters can be presented each.

**Comment by raphw** [comment]
Please reopen this ticket if you have any further questions.
