### ISSUE TITLE
ByteBuddy not retaining method annotation that was dynamically added via javassist

### ISSUE THREAD

**Issue by tonyobanon** [raphw/byte-buddy#641]
When using bytebuddy, the transformed class does not contain the method annotation: @ProtectionContext that was present on the method before (though added dynamically via javassist).

Note: this issue does not happen when the annotation is hardcoded in the class. It only happens when the annotation is added dynamically

As you can see, the annotations are detected properly in the matcher, so it means that byte buddy received the class with the method annotation.

But after calling unloaded.load(...), the method annotations are no where to be found.

I 've tried everything, but it's not working
```

                        ElementMatcher<MethodDescription> matcher = new 
                        ElementMatcher<MethodDescription>() {

                        @Override
                        public boolean matches(MethodDescription target) {

                            if (target.isAbstract()) {
                                return false;
                            }

                            for (AnnotationDescription a : target.getDeclaredAnnotations()) {
                                if (a.getAnnotationType().getTypeName().equals(ProtectionContext.class.getName())) {
                                    // System.out.println(target);
                                    return true;
                                }
                            }
                            return false;
                        }
                    };

                   Unloaded<?> unloaded = new ByteBuddy()
                            .with(AnnotationRetention.ENABLED)
                            .rebase(c)
                            .method(matcher)

                      .intercept(MethodDelegation.to(Interceptor.class)
                                 .andThen(SuperMethodCall.INSTANCE)
                       )
                            .make();


                    Class<?> clazz = unloaded.load(...).getLoaded();

                   // Annotation not found on clazz



```

**Comment by tonyobanon** [comment]
@raphw can I see the code used when the method annotations are moved from the former into the rebased class?

**Comment by tonyobanon** [comment]
Added @Inherited to the @interface ProtectionContext is also not working

**Comment by mekkah** [comment]
What `RetentionPolicy` did you define on `ProtectionContext?

**Comment by tonyobanon** [comment]
Runtime

**Comment by tonyobanon** [comment]
The RuntimeVisibleAnnotations attribute was obviously used when the annotation was added at runtime by javassist.
This also evident because my ByteBuddy ElementMatcher can detect it.. However, after
unloaded.load(...) is called, it's no longer present in the newly rebased class

**Comment by raphw** [comment]
Where does `c` come from? Is it a loaded class that was previously modified with Javassist? In this case, Byte Buddy attempts to retain the original byte code it reads from the class loader (typically the class file from disk) and your Javassist changes will be lost.

**Comment by tonyobanon** [comment]
All good now!.. Thanks @raphw
