### ISSUE TITLE
.define(Method method) seems to ignore parameter types

### ISSUE THREAD

**Issue by bbottema** [raphw/byte-buddy#642]
Observe the following interface:
```java
public interface BaseInterface { }

public interface MyInterface extends BaseInterface {
    @SomeMethodAnnotation("A")
    Object referenceMethod(@MyParamAnnotation() String value);
}
```
Using ByteBuddy 1.9.12, I'm creating a new interface, copying the method, overriding `@SomeMethodAnnotation` with a different instance.
```java
Method referenceMethod = ...;

Class<? extends MyInterface> subInterface = new ByteBuddy()
                .makeInterface(BaseInterface.class)
                .define(referenceMethod)
                .withoutCode()
                .annotateMethod(new SomeMethodAnnotation("B"))
                .make()
                .load(BaseInterface.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                .getLoaded();
```
When inspecting the resulting interface, I was unable to find `@MyParamAnnotation` on the parameter of the copied method. Did I miss it or is it missing in the `.define(Method)` implementation?

**Comment by bbottema** [comment]
Confirmed that manually copying the method works where `define(Method)` doesn't, but it is very ugly:

```
DynamicType.Builder.MethodDefinition.ParameterDefinition.Simple<BaseInterface> builder = 
     new ByteBuddy()
            .makeInterface(BaseInterface.class)
            .defineMethod(referenceMethod.getName(), referenceMethod.getReturnType(), referenceMethod.getModifiers());

for (int i = 0; i < referenceMethod.getParameters().length; i++) {
    builder = builder
            .withParameter(referenceMethod.getParameters()[i].getType())
            .annotateParameter(referenceMethod.getParameters()[i].getAnnotations()); // << this fixes it
}

Class<? extends BaseInterface> subInterface = builder
            .withoutCode()
            .annotateMethod(new SomeMethodAnnotation("B"))
            .make()
            .load(BaseInterface.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
            .getLoaded();
```

**Comment by raphw** [comment]
From the javadoc:

> Defines a method or constructor that is similar to the supplied method description but **without copying any annotations** of the method/constructor or method/constructor parameters.

Instead of your workaround, you can register a `MethodAttributeAppender` using the `attribute` step in the DSL. Have a look into `MethodAttributeAppender.Explicit` for your purposes.

**Comment by bbottema** [comment]
> From the javadoc:
> 
> > Defines a method or constructor that is similar to the supplied method description but **without copying any annotations** of the method/constructor or method/constructor parameters.
> 
> Instead of your workaround, you can register a `MethodAttributeAppender` using the `attribute` step in the DSL. Have a look into `MethodAttributeAppender.Explicit` for your purposes.

I'm not sure how to do this. I couldn't find much by examples on this either. Can you point me in the right direction?

**Comment by raphw** [comment]
Could you step through your code and check why the annotation is missing here: https://github.com/raphw/byte-buddy/blob/1107d3ffd6d390b348107c8887767cfd13f2686b/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/attribute/MethodAttributeAppender.java#L296

It should be included by all I know.

**Comment by bbottema** [comment]
> .attribute(MethodAttributeAppender.Explicit.of(new MethodDescription.ForLoadedMethod(referenceMethod)))

Is it possible to only copy the parameter annotations and ignore the method annotations?

**Comment by bbottema** [comment]
I solved it finally, by defining an overloaded version of `MethodAttributeAppender.of(Method)`:
```
public static MethodAttributeAppender.Factory ofMethodParameters(MethodDescription methodDescription) {
    List<MethodAttributeAppender.Factory> methodAttributeAppenders = new ArrayList<>();
    for (ParameterDescription parameter : methodDescription.getParameters()) {
        methodAttributeAppenders.add(new MethodAttributeAppender.Explicit(parameter.getIndex(), parameter.getDeclaredAnnotations()));
    }
    return new MethodAttributeAppender.Factory.Compound(methodAttributeAppenders);
}
```
Then using it like so
```
new ByteBuddy()
   .makeInterface(Foo.class)
   .define(referenceMethod);
   .withoutCode()
   .attribute(ofMethodParameters(referenceMethod)
   .make();
```
But I really wish this was part of the library.

**Comment by raphw** [comment]
Send a PR for a static factory in the explicit appender with a test and I will add it.

**Comment by bbottema** [comment]
> Send a PR for a static factory in the explicit appender with a test and I will add it.

Done.
