### ISSUE TITLE
how to debug bytebuddy agent

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#650]
Now cwss-agent-core-1.0.2.jar is my bytebuddy agent,but it is jar. I cannot set breakpoint inside it. how to debug?
￼
I want to set some breakpoint in cwss-agent-core.jar when I run my application service.

**Comment by raphw** [comment]
You can set a breakpoint in an agent just as in any program. You can use remote debugging and debug the process from the IDE that loaded the source code of it. The debugger API is agnostic to whether code is loaded by an agent or the main program.

**Comment by raphw** [comment]
Please reopen if there are further questions.
