### ISSUE TITLE
Question: how to define a method based on a LoadedMethod and then add extra parameters

### ISSUE THREAD

**Issue by bbottema** [raphw/byte-buddy#654]
Is there an appender that allows me to add parameters, or else is there a way to get back to the Method builder after the method was defined?

Here's what I would ideally do:

```
new ByteBuddy()
   .(...)
   .define(referenceMethod)
   .defineParameter(...)
   .defineParameter(...)
   .withoutCode()
```
Or:
```
new ByteBuddy()
   .(...)
   .define(referenceMethod)
   .withoutCode(referenceMethod)
   .attribute(MethodAttributeAppender...)
```
This then should be compatible with the annotation appenders for copying annotations.

**Comment by raphw** [comment]
No, that is not possible and I do not think that I will add it since this does not seem to be a common scenario. The API is already fairly complex, I try to avoid new steps as long as you can express everything.

**Comment by bbottema** [comment]
> No, that is not possible and I do not think that I will add it since this does not seem to be a common scenario. The API is already fairly complex, I try to avoid new steps as long as you can express everything.

Well, that depends on your definition of "express", but I see your point I guess. I do think the API remains intuitive when returning a `MethodDefinition.ParameterDefinition.Initial<T>` instead of a `MethodDefinition.ImplementationDefinition<T>` from `.define(Method)`.

**Comment by raphw** [comment]
Yes, that is what I mean. Also, I cannot forsee how the Java language is going to evolve in the future such that I might need to add additional steps in between what makes retaining this comfort more expensive. I got burnt by this before, this is why I want to stay conservative about such additional steps.

**Comment by raphw** [comment]
Please reopen if there are further questions.
