### ISSUE TITLE
Distribution Packaging Documentation: about = blank

### ISSUE THREAD

**Issue by hypersoft** [raphw/byte-buddy#657]
This page is blank: https://github.com/raphw/byte-buddy/wiki/How-to-Build-Byte-Buddy

[a] Please add this issue to your task list for prompt-resolution.
[b] Simple text document format will do nicely. 
[c] Apparently somebody went through the trouble to allow you to fill in the blanks. What luck.

[:cheers:]

**Comment by hypersoft** [comment]
The overall problem is that, there is no way for someone who does not know how to use the project to provide the package or packages, with the java-docs; essentially.

**Comment by hypersoft** [comment]
A reasonable, build places everything one would need in a single output directory, for each "separate" package which a package may provide, then the documentation iterates over the directory and or sub-directories. Most projects only provide a single package, whereas yours has 3.

**Comment by raphw** [comment]
I copied the section that is already listed in the project readme of the GitHub project. The root POM lists several build options.

Byte Buddy follows the standard Maven project layout where each module is hosting its own artifacts.
