### ISSUE TITLE
Allow optimized retransformation

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#66]
When using AgentBuilder a possible use case is to define Transformation after classes have been loaded.
AgentBuilder has allowRetransformation() which passes this information to the Instrumentation.
What is missing right now is an easy way to actually perform retransformation.

calling instrumentation.retransform(instrumentation.getAllLoadedClasses()) is not only super slow, it also crashes the JVM.

What I would like to see is something like this:
```java
        @Override
        public ClassFileTransformer installOn(Instrumentation instrumentation) {
            ClassFileTransformer classFileTransformer = makeRaw();
            instrumentation.addTransformer(classFileTransformer, retransformation);
            if (!NO_NATIVE_PREFIX.equals(nonNull(nativeMethodPrefix))) {
                instrumentation.setNativeMethodPrefix(classFileTransformer, nativeMethodPrefix);
            }
            
            if (retransformation) {
              Class[] allLoadedClasses = instrumentation.getAllLoadedClasses();
              for (Class class1 : allLoadedClasses) {
                if(isMatchedByAnyMatcher(class1)) {
                  instrumentation.retransformClasses(class1);
                }
              }
            }
            return classFileTransformer;
        }
```
I tried to implement the magic "isMatchedByAnyMatcher" method, but I am not sure what would be the most efficient way to actually do this.

The basic idea is, that because we know which candidates we would match anyway, we could look them up and retransform them directly.

**Comment by raphw** [comment]
You have a point there. In theory, the retransformation process would result in a no-op as the class file transformer would not attempt to redefine non-matched classes but it makes sense to do a prefiltering to avoid the retransformation attempt alltogether.

This would solve the problem: 

```
if (retransformation) {
  List<Class<?>> retransformedTypes = new LinkedList<Class<?>>();
    for (Class<?> type : instrumentation.getAllLoadedClasses()) {
      for (Transformation transformation : transformations) {
        if (transformation.matches(new TypeDescription.ForLoadedType(type), type.getClassLoader(), type, type.getProtectionDomain())) {
          retransformedTypes.add(type);
          break;
        }
      }
    }
    try {
      instrumentation.retransformClasses(retransformedTypes.toArray(new Class<?>[retransformedTypes.size()]));
    } catch (UnmodifiableClassException exception) {
      throw new IllegalStateException("Cannot retransform classes: " + retransformedTypes, exception);
    }
  }
}
```

**Comment by CodingFabian** [comment]
In theory it would be a no-op, but inst.retransform() is a super expensive call and also it tends to throw exceptions or even segfault when trying without prefiltering.

I wonder if it should be part of installOn() or a separate API.

**Comment by raphw** [comment]
No, I do not think it should be. I expect that people that enable retransformation actually want to conduct a retransformation of the matched classes in the first place. It is most convenient if Byte Buddy applies the retransformation. Otherwise, one can always create the raw retransformer and setup the process manually.

Now merged to `master`.
