### ISSUE TITLE
Use @Advice.FieldValue to get the property's current value

### ISSUE THREAD

**Issue by kalgon** [raphw/byte-buddy#660]
When intercepting a property's getter or setter, `@FieldValue` can be used without providing a field name to get the property's current value. Would it be possible to do the same for `@Advice.FieldValue`?

**Comment by raphw** [comment]
You are right, this is not implemented at the moment. I can add this as a feature to keep it consistent.

**Comment by kalgon** [comment]
BTW, what do you think about using `@Advice.Origin("#p") String propertyName` to get the property name in the advice?

**Comment by raphw** [comment]
Not a bad idea either, I will look into it.

**Comment by kalgon** [comment]
Fixed in 1.10.18
