### ISSUE TITLE
how to close java agent in running time 

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#662]
we attach -javaagent: to our application server, when we start the server, it will initiate java agent. My questions is that if we want to close java agent but don't shut down out application server and remove -javaagent. Do we have any way to do it in running time dynamiclly

**Comment by raphw** [comment]
There is no mechanism in the JVM for removing an agent. You can of course remove an instrumentation, Byte Buddy returns a resettable class file transformer that allows for the reversal of all byte code changes.

For this to work, you do however need to make sure that your instrumentation does not add or remove methods. Set `.disableClassFormatChanges()` on the agent builder to make sure this does not happen.

There is no standard way in the JVM to trigger such a removal. You would need to listen on a socket or scan for a file to trigger this application.

**Comment by raphw** [comment]
Please reopen if there are further questions.
