### ISSUE TITLE
Does not work on JDK 11

### ISSUE THREAD

**Issue by hypercube-softwares** [raphw/byte-buddy#663]
I tried a simple thing: subclass a class Task and it does not work.

```
Loaded<Task> t = new ByteBuddy().subclass(Task.class)
					.name("ObservableTask")					
					.make()
                                        .load(Task.class.getClassLoader());
```

I have an **InvocationTargetException** on **load()** with the following cause (I'm using Open JDK 11.0.2):

> Caused by: java.lang.IllegalAccessError: superclass access check failed: class ObservableTask (in **unnamed module** @0x19976a65) cannot access class com.test.model.Task (in module com.test) because module com.test does not export com.test.model to **unnamed module** @0x19976a65

it seems that the subclass does not belongs to the same module. It is in a **unnamed module.** This is weird because I think you said in the doc that the subclass belongs to the same package...

My pom:
```
<dependency>
	<groupId>net.bytebuddy</groupId>
	<artifactId>byte-buddy</artifactId>
	<version>1.9.13</version>
</dependency>
```

**Comment by raphw** [comment]
There are two problems here:

1. By setting `.name("ObservableTask")`, you are changing the generated class's name and package. Of course, this way, the class does not have a package and ends up in the default package.
2. By not specifying a class loading strategy in `.load(...)` as a second argument, Byte Buddy uses its default strategy and will load the generated class in a new class loader. Even if the package's name was the same as that of the super class, the load time package would not be the same and it could still not extend the non-exported class. This can be avoided by injecting the generated class by using `ClassLoadingStrategy.Default.INJECTION`. Note that this uses unsafe API which might render it impossible to use this strategy in the future.

If you want to make this happen without any hacks or package sharing, consider exporting the `com.test.model` package from your `com.test` module and everything should work. The Java module system is only doing it's job here: protecting a non-exported class from being extended from the outside of the module.

**Comment by hypercube-softwares** [comment]
You said [here ](https://github.com/raphw/byte-buddy/issues/428#issuecomment-377357812)that INJECTION does not work anymore. Indeed now I have the infamous error related to "sun.misc.Unsafe".
So I changed to ClassReloadingStrategy.fromInstalledAgent(). Is it the right way for JDK11 ?

```
Class<? extends Task> ta = new ByteBuddy().subclass(Task.class)
		.name(Task.class.getPackageName() + ".ObservableTask")
		.make()
		.load(Task.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent())
		.getLoaded();
```

My module-info is the following:

```
module testModule {
	exports com.test.byteBuddy;
	requires net.bytebuddy;
	requires net.bytebuddy.agent;
}
```
Now I have `Exception in thread "main" java.lang.IllegalStateException: The Byte Buddy agent is not installed or not accessible`

Cause: `The Byte Buddy agent is not loaded or this method is not called via the system class loader at net.bytebuddy.agent/net.bytebuddy.agent.Installer.getInstrumentation`

An idea ?

**Comment by hypercube-softwares** [comment]
Ah! finally, I revert back to my initial code, I just exported my package to the outside world like this:

```
module testModule {
	exports com.test.byteBuddy;
	exports com.test.byteBuddy.model;
	requires net.bytebuddy;
}
```

I would prefer `opens com.test.byteBuddy.model to net.bytebuddy;` but it does not work.

**Comment by raphw** [comment]
Since Byte Buddy generates byte code and does not work using reflection, opening a module does not work.

One way you could approach this would be to:

1. create an `ByteArrayClassLoader` that is opened for injection (check the constructor arguments).
2. Export your *model* package to that class loaders unnamed module using the Java 9+ reflection API.
3. Use the `InjectionClassLoader.Strategy` to inject your generated code into this class loader which will now be able to see this package.

Doing so, you make it impossible for anybody else to access that package.

**Comment by raphw** [comment]
Please reopen if there are further questions.

**Comment by SamHoque** [comment]
Getting the same error when running `ByteBuddyAgent.install();` on X64 device.

build.gradle.kts:
`    implementation("net.bytebuddy:byte-buddy:1.14.13")
    implementation("net.bytebuddy:byte-buddy-agent:1.14.13")`

System Info:
![image](https://github.com/raphw/byte-buddy/assets/30783651/19db626e-afa7-41f7-9977-6f212f99eb83)
