### ISSUE TITLE
readonly=false not worked

### ISSUE THREAD

**Issue by dennis0721** [raphw/byte-buddy#665]
hello, i am using bytebuddy to enhance rocketmq's produce and consume, and i need to change message's properties, so i used **@Argument(value = 2, readOnly = false) Message message** with **@Advice.OnMethodEnter**, but it seemed not worked, can you give me some advices, thank you very much

**Comment by dennis0721** [comment]
i found the argument **message** is final，does this matters?

**Comment by raphw** [comment]
No, the modifier has nothing to say for the JVM. Do you get an error message in your agentbuilder.listener?

**Comment by dennis0721** [comment]
None of [public static void com.yunpian.attila.hawk.test.bytebuddy.TestInter.enter(java.lang.reflect.Method,java.lang.Object,java.lang.Object[])] allows for delegation from public java.lang.String com.yunpian.attila.hawk.test.bytebuddy.TestImpl.hello(java.lang.String), i used **@Advice.Origin Method method, @Advice.This Object thiz, @AllArguments(readOnly = false) Object[] objects**

**Comment by dennis0721** [comment]
i found the problem, it's none of bytebuddy's business, advice works well, it's the problem of the joinpoint of rocketmq, thank you for your reply!
