### ISSUE TITLE
JavaAgent to intercept @RestController, @Controller etc. in a running Spring Boot App

### ISSUE THREAD

**Issue by MrBW** [raphw/byte-buddy#667]
Hi,

first...wow what a great project!
Currently I'm trying to intercept all Public methods from a Class annotated with a common Spring Annotation like @Controller, @RestController etc.
But I'm not able to get this working. I'm not seeing any errors our outputs that would trigger me in the right direction.

`new AgentBuilder.Default()
                .with(AgentBuilder.Listener.StreamWriting.toSystemError())
                .with(new AgentBuilder.InitializationStrategy.SelfInjection.Eager())
.type(isAnnotatedWith(named("org.springframework.web.bind.annotation.RestController")))
                .transform((builder, typeDescription, classLoader, module) -> builder.method(ElementMatchers.isPublic())
                        .intercept(MethodDelegation.to(SpringBootInterceptor.class)))
installOn(instrumentation);`

Can you please help me?

**Comment by raphw** [comment]
This should work but maybe your agent is loading the annotations prematurely? Do the annotations show up as ignored or not at all when Byte Buddy is logging the status?

**Comment by MrBW** [comment]
They don't appear at all.

Is it because I am forced to load the agent only after the start of the Spring Boot App? I need to instrument an already running Spring Boot App...

**Comment by raphw** [comment]
In your method delegation, try to use a TypePool.Default to describe the class, thus  avoiding any premature class loading.

**Comment by MrBW** [comment]
Did you mean such a config in the Method Delegation? Unfortunately, it does not lead to success.

`.transform((builder, typeDescription, classLoader, module) -> {
                    ClassFileLocator locator = new ClassFileLocator.Compound(
                            ClassFileLocator.ForClassLoader.of(classLoader),
                            ClassFileLocator.ForClassLoader.of(ByteBuddy.class.getClassLoader())
                    );
                    Advice advice = Advice.to(TypePool.Default.of(locator).describe("com.chaos.attacks.spring.boot.agent.SpringBootInterceptor").resolve(),locator);
                    return builder.method(named("test")).intercept(advice);`

In the ByteBuddy logs I also find no entries about any Spring Boot annotated Controllers. Maybe they are not detected?

**Comment by raphw** [comment]
Yes, in this case, I expect that the class in question is loaded before the Byte Buddy agent is installed. This must not happen since you do not use class redefinition where previously loaded classes are not touched.

I was expecting the delegation target to reference the class and cause it to be loaded. You can run your JVM with verbose class loading to find out where the loading is triggered

**Comment by MrBW** [comment]
I managed it, and it works the way I imagined it would. Thanks a lot for your support and your great project!!!

**Comment by chrishyc** [comment]
i have the same problem.
`public static void premain(String agentArgs, Instrumentation inst) {
        LOGGER.info("premain begin, agentArgs: {}, classloader: {}", agentArgs, OverseaAgent.class.getClassLoader().toString());
        System.out.println("premain begin, agentArgs: {}, classloader: {}");

        AgentBuilder.Transformer transformer = new AgentBuilder.Transformer() {
            @Override
            public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder,
                                                    TypeDescription typeDescription,
                                                    ClassLoader classLoader) {
                return builder
                        .method(ElementMatchers.any()) // 拦截任意方法
                        .intercept(MethodDelegation.to(TimeCostInterceptor.class)); // 委托
            }
        };

        AgentBuilder.Listener listener = new AgentBuilder.Listener() {
            @Override
            public void onTransformation(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module, DynamicType dynamicType) {
                LOGGER.info("onTransformation with module: {}", module);
            }

            @Override
            public void onIgnored(TypeDescription typeDescription, ClassLoader classLoader, JavaModule module) {
                LOGGER.info("onTransformation onIgnored module: {}", module);
            }

            @Override
            public void onError(String typeName, ClassLoader classLoader, JavaModule module, Throwable throwable) {
                LOGGER.error("Failed to enhance class {}", typeName);
                LOGGER.error("exception", throwable);
            }

            @Override
            public void onComplete(String typeName, ClassLoader classLoader, JavaModule module) {
                LOGGER.debug("onTransformation complete module: {}", module);
            }
        };

        new AgentBuilder
                .Default()
                .type(ElementMatchers.any()) 
                .transform(transformer)
                .with(listener)
                .installOn(inst);
    }`
in my springboot application,i found nothing log about byte-buddy.  in another springboot,i found  byte buddy log. i don.t  know the diff  about the two springbott application.  how to fix

**Comment by chrishyc** [comment]
> Yes, in this case, I expect that the class in question is loaded before the Byte Buddy agent is installed. This must not happen since you do not use class redefinition where previously loaded classes are not touched.
> 
> I was expecting the delegation target to reference the class and cause it to be loaded. You can run your JVM with verbose class loading to find out where the loading is triggered

after -javaagent:**bytebuddy.jar  
i can.t see  some log about bytebuddy.just  below
`
TmallSpringbootApplication$$EnhancerBySpringCGLIB$$7a946615 from file:/Users/chris/tmall_springboot/target/classes/]
[Loaded org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl from file:/Users/chris/.m2/repository/org/hibernate/hibernate-core/5.4.6.Final/hibernate-core-5.4.6.Final.jar]
[Loaded org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState from file:/Users/chris/.m2/repository/org/hibernate/hibernate-core/5.4.6.Final/hibernate-core-5.4.6.Final.jar]
[Loaded net.bytebuddy.TypeCache from file:/Users/chris/.m2/repository/net/bytebuddy/byte-buddy/1.10.1/byte-buddy-1.10.1.jar]
[Loaded net.bytebuddy.TypeCache$WithInlineExpunction from file:/Users/chris/.m2/repository/net/bytebuddy/byte-buddy/1.10.1/byte-buddy-1.10.1.jar]
[Loaded net.bytebuddy.TypeCache$Sort from file:/Users/chris/.m2/repository/net/bytebuddy/byte-buddy/1.10.1/byte-buddy-1.10.1.jar]
[Loaded net.bytebuddy.TypeCache$Sort$1 from file:/Users/chris/.m2/repository/net/bytebuddy/byte-buddy/1.10.1/byte-buddy-1.10.1.jar]
[Loaded net.bytebuddy.TypeCache$Sort$2 from file:/Users/chris/.m2/repository/net/bytebuddy/byte-buddy/1.10.1/byte-buddy-1.10.1.jar]
[Loaded org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState$ClassRewriter from file:/Users/chris/.m2/repository/org/hibernate/hibernate-core/5.4.6.Final/hibernate-core-5.4.6.Final.jar]
[Loaded org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState$StandardClassRewriter from file:/Users/chris/.m2/repository/org/hibernate/hibernate-core/5.4.6.Final/hibernate-core-5.4.6.Final.jar]
[Loaded org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState$ProxyDe
`

**Comment by chrishyc** [comment]
i wish  bytebuddy,but EnhancerBySpringCGLIB

**Comment by raphw** [comment]
Spring proxies are synthetic and ignored by default. Add a listener to `AgentBuilder` to see what gets ignored. You can change the default ignors by setting `.ignore(...)`.

**Comment by luceat-lux-vestra** [comment]
@MrBW, Could you share your code, please?
