### ISSUE TITLE
any way

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#669]
when We start our application and it will run  premain method and load all things we want to instrument in bytebuddy.  If we change configuration and add new things we want our bytebuddy to instrument, is there any way we can do it dynamically without restarting our application?

**Comment by raphw** [comment]
You can undo an instrumentation by calling `reset` on the `ResettableClassFileTransformer` that is returned by `installOn`. You can then reapply the instrumentation. You would need to create some form of callback to trigger this.

**Comment by raphw** [comment]
Please reopen if there are further questions.
