### ISSUE TITLE
Simple Dynamic attach not found

### ISSUE THREAD

**Issue by rucko24** [raphw/byte-buddy#673]
**Hi Rafael,** 

I have the same 3 classes last [https://github.com/raphw/byte-buddy/issues/643](https://github.com/raphw/byte-buddy/issues/643) very simple, but this time, I use the agentmain due to the jframe already in full execution.

_I am using jdk 8, with the tools.jar in the classpath_

```
public static void agentmain(final String args, Instrumentation inst) {
        System.out.print("agent main");
        new AgentBuilder.Default()
                .ignore(ElementMatchers.none())
                .disableClassFormatChanges()
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(AgentBuilder.Listener.StreamWriting.toSystemOut())
                .type((ElementMatchers.nameContains("Usuario")))
                .transform((builder, typeDescription, classLoader, module) ->
                        builder.visit(Advice.to(MoreLifeAdvice.class)
                                .on(ElementMatchers.isConstructor()))
                )
                .installOn(inst);
    }
```
**MoreLifeAdvice**
```
public class MoreLifeAdvice {

    @Advice.OnMethodExit
    static void giveMeMoreLife(@Advice.FieldValue(value = "life", readOnly = false) int life)
    throws Exception {
        System.out.println("New life set to 1000");
        life = 1000;
    }

}
```
**Launcher**

```
public static void main( String[] args ) {

        final Path path = getFile(null,JFileChooser.FILES_ONLY);

        ByteBuddyAgent.attach(path.toFile(),"pid");
    }
```

**No exception is thrown And the field x is not modified**

![image](https://user-images.githubusercontent.com/17187599/59982676-3a1df700-9616-11e9-8e0f-0cf2b74743d3.png)

Yesterday I was able to verify that the Advice is not executed

**Thanks for the help provided.**

**Comment by raphw** [comment]
Is the instance created before the agent is installed? It is not applied retrospectively for existing instsnces.

**Comment by rucko24** [comment]
my lord, I don't understand very well, first I execute the jframe, I get the pid
 second run ByteBuddyAgent.attach

**Comment by raphw** [comment]
What I wonder is of the 'new' call to create the instance is run before the constructor is instrumented. Constructors are not rerun after an instrumentation.

**Comment by rucko24** [comment]
**iwoa**, Sorry sir, no idea how to do that. any ideas ?

**Comment by rucko24** [comment]
**Iwoa**, Sir, I have no idea how to do that, do you offer any way to do it?

**Comment by raphw** [comment]
You would need to check when your constructor is called and when your agent is attached. If the latter happens before the former, the field value will mot have changed.

**Comment by rucko24** [comment]
My lord, how class of bytebuddy API , helps me? 

I'm going crazy now. Damm lmao.

**Comment by raphw** [comment]
This has nothing to do with Byte Buddy. Byte Buddy modifies code, not state. If code was executed before it was modified, the modification has no effect.

**Comment by raphw** [comment]
Please reopen this ticket if you have further questions.
