### ISSUE TITLE
why my bytebuddy worked after removing defaultAgent.installOn(instrumentation)

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#674]
I remove ResettableClassFileTransformer resetter=defaultAgent.installOn(instrumentation) this line, my bytebuddy still work and can instrument, is it wired?

    public static void premain(String agentArgs, Instrumentation instrumentation) throws IOException {

    final PluginFinder pluginFinder = new PluginFinder(new PluginBootStrap().loadPlugins());

    final ByteBuddy bytebuddy = new ByteBuddy();
     defaultAgent = new AgentBuilder.Default(bytebuddy)
            .type(pluginFinder.buildMatch())
            .transform(new AgentTransformer(pluginFinder, AgentClassLoader.getDefault()))
            //.with(new Listener())
           // .installOn(instrumentation)
     ;
    //ResettableClassFileTransformer resetter=defaultAgent.installOn(instrumentation);
 
    }

**Comment by raphw** [comment]
If you install a transformer, it becomes active until removed. If you reset it, it is implicitly removed.

**Comment by zheyiyi** [comment]
> If you install a transformer, it becomes active until removed. If you reset it, it is implicitly removed.

I am still confused. I remove this line defaultAgent.installOn(instrumentation) which means I haven't install the transfromer, right?

**Comment by raphw** [comment]
No, without the installOn call, nothing will happen.

**Comment by raphw** [comment]
Please reopen if there are further questions.
