### ISSUE TITLE
how to get the same instrumentation from another function

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#675]
I have a global variable instrumentation, and I want the instrumentation reference to instrumentation in the premain.

I want to get instrumentation in the reset function, but I cannot, even I use instrumentation = instrumentation in the  premain function.

     public class Agent {

    private static Instrumentation instrumentation;
    public static ResettableClassFileTransformer resetter;

    public static void premain(String agentArgs, Instrumentation instrumentation) throws IOException {
         //instrumentation = instrumentation 
         defaultAgent = new AgentBuilder.Default(bytebuddy)
                             .type(pluginFinder.buildMatch())
                .transform(new AgentTransformer(pluginFinder, AgentClassLoader.getDefault()))
    
        resetter = defaultAgent.installOn(instrumentation);
    }

    public static synchronized void reset () throws IOException {

        if (resetter == null || instrumentation == null){
            throw new IllegalStateException("Reset  was called before init");
        }

        resetter.reset(instrumentation, AgentBuilder.RedefinitionStrategy.RETRANSFORMATION);
    }}

**Comment by raphw** [comment]
You mean that the reference is null? Then I suspect that your premain method is never called or throws an exception.

**Comment by raphw** [comment]
Please reopen if there are further questions.
