### ISSUE TITLE
what is the difference between RETRANSFORMATION, DISABLED  and RETRANSFORMATION

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#676]
what is the difference between 

AgentBuilder.RedefinitionStrategy.RETRANSFORMATION,
AgentBuilder.RedefinitionStrategy.REDEFINITION,  and         AgentBuilder.RedefinitionStrategy.DISABLED? 

When use redefinition, When use retransformation, when use redefinition

**Comment by raphw** [comment]
Retransformation and redefinition are two different APIs for class transformation within the JVM. I'd generally recommend retransformation unless you want to run on Java 5 where only redefinition is available.

Disabled turns class rewriting off.

**Comment by raphw** [comment]
Please reopen if there are further questions.
