### ISSUE TITLE
how to solve removeTransformer problem in different thread

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#677]
In the same thread, the     instrumentation.removeTransformer(resetter) work very well. 

    public class Agent{
  
    private volatile static Instrumentation instrumentation ;
    public volatile static  ResettableClassFileTransformer resetter;
    public static void premain(String agentArgs, Instrumentation instrumentation) throws IOException {
        ByteBuddyAgent.install();
     defaultAgent = new AgentBuilder.Default(bytebuddy)
                         .type(pluginFinder.buildMatch())
            .transform(new AgentTransformer(pluginFinder, AgentClassLoader.getDefault()))

       resetter = defaultAgent.installOn(instrumentation);
       
        instrumentation.removeTransformer(resetter);
    }
}
But if I move it to different thread, It doesn't work.

new Thread(()->{
Agent.shutdown();
})

  
    public class Agent{
  
    private volatile static Instrumentation instrumentation ;
    public volatile static  ResettableClassFileTransformer resetter;
    public static void premain(String agentArgs, Instrumentation instrumentation) throws IOException {
        ByteBuddyAgent.install();
     defaultAgent = new AgentBuilder.Default(bytebuddy)
                         .type(pluginFinder.buildMatch())
            .transform(new AgentTransformer(pluginFinder, AgentClassLoader.getDefault()))

       resetter = defaultAgent.installOn(instrumentation);
       
    }

    public static synchronized void shutdown() {
        instrumentation= ByteBuddyAgent.getInstrumentation();
        instrumentation.removeTransformer(resetter);

        instrumentation = null;
        resetter = null;}}

I read from java api document, (Due to the multi-threaded nature of class loading,it is possible for a transformer to receive calls after it has been removed. Transformers should be written defensively to expect this situation.) What is the nature of multi-threaded?

boolean removeTransformer(ClassFileTransformer transformer)

Unregisters the supplied transformer. Future class definitions will not be shown to the transformer. Removes the most-recently-added matching instance of the transformer. Due to the multi-threaded nature of class loading, it is possible for a transformer to receive calls after it has been removed. Transformers should be written defensively to expect this situation.

**Comment by raphw** [comment]
Is your desinstallation run before the installation is complete? Byte Buddy is itself fully thread-safe, I doubt that the problem is in the library.

**Comment by zheyiyi** [comment]
Yes, It definitelly finished. What I did is very similar with this. https://stackoverflow.com/questions/44896396/the-instrument-removetransformer-does-not-work-when-in-different-thread

**Comment by zheyiyi** [comment]
> Is your desinstallation run before the installation is complete? Byte Buddy is itself fully thread-safe, I doubt that the problem is in the library.

Yes, It definitelly finished. What I did is very similar with this. https://stackoverflow.com/questions/44896396/the-instrument-removetransformer-does-not-work-when-in-different-thread

**Comment by raphw** [comment]
Can you check if both classes are executed on the same class loader (e.g. print Agent.class.getClassLoader()) to the console on method entry.

I guess you are loading the class twice then.

**Comment by zheyiyi** [comment]
If I write class like this,    instrumentation.removeTransformer(resetter) works.

    public class Agent{
    private volatile static Instrumentation instrumentation ;
    public volatile static  ResettableClassFileTransformer resetter;
    public static void premain(String agentArgs, Instrumentation instrumentation) throws IOException {
   
        defaultAgent = new AgentBuilder.Default(bytebuddy)
                     .type(pluginFinder.buildMatch())
        .transform(new AgentTransformer(pluginFinder, AgentClassLoader.getDefault()))

      for (Map<String, ?> instrumentClass : moduleConfig.get("instrumentClass")) {
            defaultAgent = 
            defaultAgent.type(ElementMatchers.named((String)instrumentClass.get("class")))
                    .transform(new AgentBuilder.Transformer.ForAdvice()
                            .include(FunctionInterceptor.class.getClassLoader())
                            .advice(ElementMatchers.isMethod()                                       .and(ElementMatchers.nameContains((String)instrumentClass.get("method"))),
                                    FunctionInterceptor.class.getName()));
        }
        resetter = defaultAgent.installOn(instrumentation);

         instrumentation.removeTransformer(resetter);}


If I write class like this,    put instrumentation.removeTransformer(resetter) in another thread, it doesn't works.  Both  System.out.println(Instrumentation.class.getClassLoader()) print null.

    public class Agent{
    private volatile static Instrumentation instrumentation ;
    public volatile static  ResettableClassFileTransformer resetter;
    public static void premain(String agentArgs, Instrumentation instrumentation) throws IOException {
   
         System.out.println(Instrumentation.class.getClassLoader());

        defaultAgent = new AgentBuilder.Default(bytebuddy)
                     .type(pluginFinder.buildMatch())
        .transform(new AgentTransformer(pluginFinder, AgentClassLoader.getDefault()))

      for (Map<String, ?> instrumentClass : moduleConfig.get("instrumentClass")) {
            defaultAgent = 
            defaultAgent.type(ElementMatchers.named((String)instrumentClass.get("class")))
                    .transform(new AgentBuilder.Transformer.ForAdvice()
                            .include(FunctionInterceptor.class.getClassLoader())
                            .advice(ElementMatchers.isMethod()                                       .and(ElementMatchers.nameContains((String)instrumentClass.get("method"))),
                                    FunctionInterceptor.class.getName()));
        }
        resetter = defaultAgent.installOn(instrumentation);

          new Thread(()->{
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println(Instrumentation.class.getClassLoader());

            inst.removeTransformer(resetter);

        }).start();}

**Comment by zheyiyi** [comment]
> Can you check if both classes are executed on the same class loader (e.g. print Agent.class.getClassLoader()) to the console on method entry.
> 
> I guess you are loading the class twice then.

**Comment by raphw** [comment]
Do not print the class loader of Instrumentation but of your Agent.class.

**Comment by zheyiyi** [comment]
> Do not print the class loader of Instrumentation but of your Agent.class.

I print  Agent.class.getClassLoader(). All place(       System.out.println(Agent.class.getClassLoader());
) are sun.misc.Launcher$AppClassLoader@18b4aac2.

    public class Agent{
    private volatile static Instrumentation instrumentation ;
    public volatile static  ResettableClassFileTransformer resetter;
    public static void premain(String agentArgs, Instrumentation instrumentation) throws IOException {

     System.out.println(Agent.class.getClassLoader());

    defaultAgent = new AgentBuilder.Default(bytebuddy)
                 .type(pluginFinder.buildMatch())
    .transform(new AgentTransformer(pluginFinder, AgentClassLoader.getDefault()))

      for (Map<String, ?> instrumentClass : moduleConfig.get("instrumentClass")) {
        defaultAgent = 
        defaultAgent.type(ElementMatchers.named((String)instrumentClass.get("class")))
                .transform(new AgentBuilder.Transformer.ForAdvice()
                        .include(FunctionInterceptor.class.getClassLoader())
                        .advice(ElementMatchers.isMethod()                                       .and(ElementMatchers.nameContains((String)instrumentClass.get("method"))),
                                FunctionInterceptor.class.getName()));
    }
    resetter = defaultAgent.installOn(instrumentation);

      new Thread(()->{
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println(Agent.class.getClassLoader());

        inst.removeTransformer(resetter);

    }).start();}


But I found a very interesting phenomenon. if I change my thread.sleep to 10000, the inst.removeTransormer function works, but if I change my thread.sleep to 100000, the inst.removeTransormer function doesn't work

    new Thread(()->{
        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println(Agent.class.getClassLoader());

        inst.removeTransformer(resetter);

    }).start();}

**Comment by zheyiyi** [comment]
It looks like after my agent start to instrument after I send http request to my application server, the   inst.removeTransformer(resetter); function lose its function.
If  inst.removeTransformer(resetter) run before I send http request to my application server. It works. Nomatter how I send http requesst to my application server, my agent never instrument.

**Comment by raphw** [comment]
Then this is very likely a racing condition since you do not synchronize your threads.

**Comment by zheyiyi** [comment]
> Then this is very likely a racing condition since you do not synchronize your threads.

you mean adding synchronized as this?

       new Thread(()->{
            synchronized(Agent.class) {
                System.out.println("888" + Agent.class.getClassLoader());

                try {
                    Thread.sleep(10000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

            inst.removeTransformer(resetter);
                System.out.println("999" + Agent.class.getClassLoader());
            }
        }).start();

**Comment by zheyiyi** [comment]
> Then this is very likely a racing condition since you do not synchronize your threads.

can you give more advice?

**Comment by raphw** [comment]
You would need to synchornize both the agentmain and the thread's method on the same monitor. Could you create a small reproduction of your problem? This way, I could point you better to a concrete improvement.

**Comment by raphw** [comment]
Please reopen if there are further questions.
