### ISSUE TITLE
is there anyway to add new class to instrument in running time

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#678]
is there anyway to add new class to instrument in running time?

if I have a config file, if I add more class in the config, the bytebuddy can read again and instrument them in the running time?

**Comment by raphw** [comment]
You can always add new listeners, if a agent executes its agentmain or premain method, the `Instrumentation` method remains valid for the life-time of the instrumentation and you can always change or retransform single classes.

**Comment by raphw** [comment]
Please reopen this ticket if you have any further questions.
