### ISSUE TITLE
Cannot get Your TimingInterceptor Java Agent Example to work

### ISSUE THREAD

**Issue by moonlitSpider** [raphw/byte-buddy#679]
Hello,

I've spent a few hours on this with no success and, though I suspect a simple error on my part, I don't see what's wrong. The code in premain looks like this:

```
	  new AgentBuilder.Default()
              //.type(ElementMatchers.nameEndsWith("Timed"))
	      .type(ElementMatchers.any())
	      .transform(new AgentBuilder.Transformer() 
	      {
	    	  @Override
	    	  public DynamicType.Builder transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classloader, JavaModule arg3)
	    	  {
	    		  System.out.println("GOT TO HERE");
	    		  return builder.method(ElementMatchers.any()).intercept(MethodDelegation.to(TimingInterceptor.class));
	    	  }
	      }).installOn(instrumentation);
```
I do see the "got to here" message; in fact, I see the "got to here" message four times and the instrumented class's _main_ method does call four methods.

But I never see any output from your TimingInterceptor class. In fact, I am fairly certain it never gets called. I say this because I never see a diagnostic message that I placed in the TimingInterceptor.intercept method.

I am running JRE 7, but also tried compiling the agent code under JDK 1.8; same result. Again, probably a dumb error on my part.

If you can shed any light on this, that would be great.

Thank you.

**Comment by raphw** [comment]
Did you try to register a listener via `.with(AgentBuilder.Listener.StreamWriting.toSystemOut())`? This would allow you to see if a transformation worked or failed and potentially for what reason.

**Comment by moonlitSpider** [comment]
Thank you for getting back to me, Rafael.

I did not register such a listener. Can you point me to an example of its use?

Thanks again.

**Comment by raphw** [comment]
Just chain the above code to your `AgentBuilder` and it will register such a listener. As a result, all instrumentations are printed out to the console.

**Comment by raphw** [comment]
Please reopen if there are further questions.
