### ISSUE TITLE
byte-buddy-maven-plugin transform failed

### ISSUE THREAD

**Issue by lqjack** [raphw/byte-buddy#680]
Execution default of goal net.bytebuddy:byte-buddy-maven-plugin:1.8.17:transform failed: None of [public static java.lang.Object com.demo.LogAspect.intercept(java.lang.reflect.Method,java.util.concurrent.Callable,java.lang.Object[]) throws java.lang.Exception] allows for delegation from public com.amazonaws.services.dynamodbv2.document.Item com.demo.Demo(java.lang.String,com.amazonaws.services.dynamodbv2.document.spec.GetItemSpec)

**Comment by raphw** [comment]
As the exception says, it seems like your method does not allow for delegation to the specified target. Make sure that the delegation target does not require any parameter injections that are impossible for the method being instrumented.

**Comment by lqjack** [comment]
Why do I need to make sure that does not require any parameter to inject?  However I need provide the callback method to invoke so that I can pass the request parameters and request object to the method.

**Comment by raphw** [comment]
The problem is that these parameters are objects which are created in the JVM during the build. These objects do not longer exist if the classes are loaded once again in the JVM that executes the program. Therefore, it is required that you only create stateless references.

**Comment by raphw** [comment]
Please reopen if there are further questions.
