### ISSUE TITLE
how to add filter class by bytebuddy

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#683]
Can I ask if bytebuddy encounter servlet's doget, dopost function, can it attach a full filter class into application? In this case, filter will be the first place to get http request.

    @Component
    public class EntryFilter implements Filter {

    private final Logger logger = LoggerFactory.getLogger(EntryFilter.class);

    private boolean springActuator = false;
    private SpringActuatorStrategy springActuatorStrategy;
    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
        if (System.getProperty("springActuator") != null){
            springActuator = Boolean.valueOf(System.getProperty("springActuator"));

        }
        springActuatorStrategy = new SpringActuatorStrategy();
    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException, ServletException {
        logger.info(" EntryFilter start to run");

        HttpServletRequest req = (HttpServletRequest) request;
        HttpServletResponse resp = (HttpServletResponse) response;
        MutableHttpServletRequest mutableHttpServletRequest = new MutableHttpServletRequest(req);
        Span span = null;

        if (SkyRunningAgent.flag == 0) {

            if (req.getRequestURI().contains("/actuator")) {
                span = springActuatorStrategy.handleStart(req, mutableHttpServletRequest, springActuator, span);

            } else {

                span = TraceManager.startHttpSpan(mutableHttpServletRequest, span);
            }
        }

        logger.info(
                "Starting a transaction for req : {}",
                req.getRequestURI());

        chain.doFilter(mutableHttpServletRequest, response);

        logger.info(
                "Committing a transaction for req : {}",
                req.getRequestURI());

        if (span != null ) {
            springActuatorStrategy.handleEnd(span, resp, response);
        }

    }

    @Override
    public void destroy() {

    }

}

**Comment by raphw** [comment]
Yes, you can register an `AgentBuilder` that intercepts all types that are a super type of servlet filter `hasSuperType(named("javax.servlet.Filter"))` and request instrumentations of the methods with the specified names and signatures. Typically, you would use `Advice` to achieve this.

**Comment by raphw** [comment]
Please reopen if there are further questions.
