### ISSUE TITLE
Provide TypeDescription lookup for binary class name

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#69]
I have a ClassFileTransformer, which gets the class name it transforms as internal slashed String ("java/lang/String")

I would really like to use TypePool / TypeDescription to check inheritance hierarchy (via isAssignableFrom etc)

however to do that I first need to replace / with dots, which is horribly inefficient doing for all classes.

Could the TypePool offer me a lookup based on this name?

**Comment by raphw** [comment]
Internally, the `TypePool` has to transform the name of a class into the form of `com/package/Foo.class` by suffixing `.class` anyways. Therefore, string transformation is already required and despite, the performance gain would be minimal for avoiding such short-lived objects.

I prefer to not bloat the API, the transformation should be easy enough, potentially, one can simply wrap a `TypePool` by another API.

**Comment by CodingFabian** [comment]
thats reasonable, I see a number of ByteBuddy internal classes do the same conversion, perhaps at some point there is a good it to add lookup using internal and normal class name.
