### ISSUE TITLE
[Question] Is it possible to redefine a class to be extended by some other class?

### ISSUE THREAD

**Issue by skapral** [raphw/byte-buddy#691]
Hello

I am on latest version of ByteBuddy. I see a `ByteBuddy::subclass` method for defining new subclass. I see `Builder::implement` methods for adding new interfaces. But is it possible to define a subclass for existing class by means of ByteBuddy? I see nothing for this in API. Maybe I am missing something?...

**Comment by raphw** [comment]
You mean that you'd like to change the class's subclass? No, there is no API for it as Byte Buddy cannot longer validate the integrity of the class.

**Comment by skapral** [comment]
Thanks. It worked.

**Comment by charankamarapu** [comment]
Hi @skapral , I am also trying to do something similar to this please read this [issue](https://github.com/raphw/byte-buddy/issues/1403) . Can you briefly explain what you did to solve your issue ..?  and if you have any suggestions to solve my issue please let me know.
