### ISSUE TITLE
Update ByteBuddy from 1.8.22 to 1.9.15 

### ISSUE THREAD

**Issue by thaarbach** [raphw/byte-buddy#694]
Hi @raphw 

I'm trying to update the ByteBuddy Version to 1.9.15 in [Stagemonitor](https://github.com/stagemonitor/stagemonitor). 

As mentioned in #470 the method `asDecorator` is removed but if i understand it right, there is no need to call asDecorator anymore. Problem, without calling `asDecorator` the instrumention doesn't work anymore :(.

[AgentAttacher.java#L211-L228](https://github.com/stagemonitor/stagemonitor/blob/422c99b66030a3fafd3a83faaf106444ddb00f27/stagemonitor-core/src/main/java/org/stagemonitor/core/instrument/AgentAttacher.java#L211-L228)
```	
private static ClassFileTransformer initByteBuddyClassFileTransformer(AutoEvictingCachingBinaryLocator binaryLocator) {
		AgentBuilder agentBuilder = createAgentBuilder(binaryLocator);
		for (StagemonitorByteBuddyTransformer transformer : getStagemonitorByteBuddyTransformers()) {
			agentBuilder = agentBuilder
					.type(transformer.getMatcher())
					.transform(transformer.getTransformer())
					.asDecorator();
		}


		final long start = System.currentTimeMillis();
		try {
			return agentBuilder.installOn(instrumentation);
		} finally {
			if (corePlugin.isDebugInstrumentation()) {
				logger.info("Installed agent in {} ms", System.currentTimeMillis() - start);
			}
		}
	}
```
As i'm a absoulte newbie on BuddyBuddy and not find the right information in the documentation and now i hope you can give me an advice?

**Comment by raphw** [comment]
That's right, the decoration behavior is now default. Other then that, there should not be any breaking changes from 1.8 to 1.9.

Could you try updating version by version to see when things break up?

**Comment by thaarbach** [comment]
@raphw 

> Could you try updating version by version to see when things break up?
Sure

**Comment by thaarbach** [comment]
@raphw 
it starts with 1.9.0 but i don't know if the removing of `asDecorator` is the problem. For now i have to figure out what the different between 1.8.22 and 1.9.0. 
If you want to have look at it, just checkout stagemonitor, change bytebuddy version, remove `asDecorated` in AgentAttacher.java and run the ./gradlew test. 

Your help would be much appreciated ;-)

Thx

**Comment by raphw** [comment]
It's probably a small thing, I can have a look tomorrow!

**Comment by raphw** [comment]
Alright, I found the problem. I (unintentionally) reversed the transformer application order in Byte Buddy 1.9.0. I do not want to undo this now, 1.9.0 has been around for a while. I will now also add a test for retaining this application order.

If you reverse the order in the comparator in `AgentAttacher` (line 287) while updating to 1.9.*, everything should work as expected.

**Comment by thaarbach** [comment]
@raphw 
a big thank you that solves the problem.
