### ISSUE TITLE
Make PrimitiveUnboxingDelegate.forPrimitive public

### ISSUE THREAD

**Issue by jgremmen** [raphw/byte-buddy#695]
I have usage for an unboxing stack manipulation. PrimitiveUnboxingDelegate essentially provides these manipulations but in order to select the appropriate enumeration (BOOLEAN, BYTE, etc.) I would have to reimplement Method forPrimitive which I cannot use as it is protected.

The PrimitiveBoxingDelegate.forPrimitive method is public so it seems the unboxing method has been forgotten to be made public as well.

**Comment by raphw** [comment]
You are right, I changed this on master. I just did a release before discovering the ticket, you will have to reimplement the method for now but it will be published eventually.
