### ISSUE TITLE
Provide AgentBuilder Hints for ASM

### ISSUE THREAD

**Issue by CodingFabian** [raphw/byte-buddy#70]
While it is possible to access the ClassVisitor API from an ByteBuddy Agent, certain operations require flags, for example to ClassWriter and to ClassReader

          ClassWriter classWriter = new ClassWriter(classReader, ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES);
            classReader.accept(classVisitor, ClassReader.EXPAND_FRAMES);

If it would be possible to tell ByteBuddy to use these flags when talking to ASM, one could still use most of ByteBuddies infrastructure to improve developer productivity, while still offering ASM features.

**Comment by raphw** [comment]
I added methods to the `ClassVisitorWrapper` that allow to specify hints to the `ClassWriter` and  `ClassReader` (if applicable) instances. The above logic can be implemented as follows:

```java
class MyClassVisitorWrapper implements ClassVisitorWrapper {
  @Override
  public int wrapWriter(int hint) {
    return hint | ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES;
  }
  
  @Override
  public int wrapReader(int hint) {
    return hint | ClassReader.EXPAND_FRAMES;
  }

  @Override
  public ClassVisitor wrap(ClassVisitor classVisitor) {
    return new MyClassVisitor(classVisitor);
  }
}
```

**Comment by CodingFabian** [comment]
great!
