### ISSUE TITLE
Quetion : Get field name as String, Is it possible?

### ISSUE THREAD

**Issue by jackflyer** [raphw/byte-buddy#701]
I know this is not right place for asking question. I asked quetion on StackOverflow. But I did not get any proper answer on to this.

What I am trying to achieve is as below in Java. Here getMethodName will work fine if there is only one field x, but for two or more field it is not guaranteed that it will name of x, and not y. So I read some other answers on SO, that suggest it may possible with ByteBuddy.  
```
public class MyClass {
    public int x;
    public int y;
}

public String getMethodName() {
    Class clazz = MyClass.class;
    return clazz.getFields()[0].getName();
}
```

Is that possible to get field name like MyClass.x.getName()  Using ByteBuddy ?

**Comment by raphw** [comment]
Byte Buddy mimics the reflection API, you will probably run into the same problem.

I am not entirely sure what you are trying to achieve. Are you trying to get the first field name of the class?

**Comment by jackflyer** [comment]
I need all field name as String , ensuring that the reference I made while coding towards field remain same while runtime. I am not with using field name hardcoded to get Field. Trying to do something like MyClass.class.getSimpleName() will give me "MyClass", but for fields.

**Comment by jackflyer** [comment]
Hi, @raphw , is this possible with byte-buddy?

**Comment by raphw** [comment]
Sure, you can resolve a `TypeDescription`, either by using a loaded class or by resolving them using a `TypePool`. Then you can call `getName` on a field.

**Comment by raphw** [comment]
Please reopen this ticket if you have further questions.
