### ISSUE TITLE
Q: Proper way to instrument already loaded classes?

### ISSUE THREAD

**Issue by drodriguezhdez** [raphw/byte-buddy#702]
Used ByteBuddy version: `v1.9.12`

I have in `CustomAgentBuilder` class with:

```java
public AgentBuilder get() {
        return new AgentBuilder.Default()
                .ignore(none())
                .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
                .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .type(new ElementMatcher<TypeDescription>() {
                    @Override
                    public boolean matches(final TypeDescription target) {
                        return CustomMatcher.match(target)
                    }
                }, isSystemClassLoader())
                .transform(new CustomTransformer());
    }
```
and I have

```java
public static void premain(final String arg, final Instrumentation instrumentation){
      ....
      customAgentBuilder.installOn(this.instrumentation);
      System.out.println("------------------- Installed Instrumentation");
}
```

Then, If I execute `java -verbose:class XXXXX`, I obtain:

```
[Loaded foo.bar.xyz.ClassOne from xxxxx]
[Loaded foo.bar.xyz.ClassTwo from yyyyy]
------------------- Installed Instrumentation
[Loaded foo.bar.xyz.ClassThree from zzzzzz]
```

Only after trace `Installed Instrumentation` is printed, the `ElementMatcher.matches` method starts to select the classes. But, the already loaded classes are not discovered to be instrumented.

So:

Actual:
- Instrumented classes: `foo.bar.xyz.ClassThree`
- Not instrumented classes: `foo.bar.xyz.ClassOne`, and `foo.bar.xyz.ClassTwo`.

Expected:
- Instrumented classes: `foo.bar.xyz.ClassOne`, `foo.bar.xyz.ClassTwo`, `foo.bar.xyz.ClassThree`.

Is there any error on my approach? 
Did I miss something?

Thanks in advance.

**Comment by raphw** [comment]
Verbose class loading does not consider retransformed classes. I assume that your instrumentation is not capable of retransformation as retransformed classes must not add or remove any members.

Try adding a `AgentBuilder.Listener.StreamWriting` to print potential errors to the console. You should also add `disableClassFormatChanges()` such that Byte Buddy better discovers potential illegal transformation steps.

**Comment by drodriguezhdez** [comment]
Added what you suggested but it seems nothing it is wrong. No errors.
My instrumentation is based on ASM modifications, which has been tested isolated and everything looks fine. No add or remove any members, just add a static invocation to a single method in the `visitLineNumber` method of the `MethodVisitor`.

Giving you more context:
The `javaagent` with this instrumentation is used when a test is executed. Thing is if I create new objects based on other classes inside the test, those objects classes are instrumented (as expected). But the test class itself it is not.

My test class (which is not instrumented) is super straightforward, like:

```java
public class JUnit4ExamplesTest {
    @Test
    public void ok_test_assert_true_is_true() {
        assertThat(true).isTrue();
    }
}
```
and it is loaded from `test-target` folder. 

Thing is, the StreamWriting listener starts writing the first class after the log trace `------------------- Installed Instrumentation`, so it gave me the feeling that it is not checking the previous loaded classes.

**Comment by drodriguezhdez** [comment]
I created a simple `javaagent` with only the instrumentation required and it seems is working fine. So, something is wrong in my original agent which it is affecting the instrumentation of this kind of test.

**Comment by drodriguezhdez** [comment]
OK, I think I got the error.

I had a method to match which class should be instrumented and which not.
Inside of that method, I was loading the class under check.
It seems it is not legal to do it, I have to figure out why (maybe you have some clue).

Anyway, now it seems all classes are being instrumented well.

Thanks for your support!

**Comment by raphw** [comment]
If a class is loaded during instrumentation, this triggers a circularity error what breaks the instrumentation process. Ideally, you match classes by name and avoid referencing application classes alltogether.
