### ISSUE TITLE
how to instrument method in abstract class

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#706]
package org.springframework.integration.channel;

    @IntegrationManagedResource
    public abstract class AbstractMessageChannel extends IntegrationObjectSupport 
    implements MessageChannel, TrackableComponent, ChannelInterceptorAware, 
    MessageChannelMetrics, ConfigurableMetricsAware<AbstractMessageChannelMetrics> {
      public boolean send(Message<?> message) {
        return this.send(message, -1L);
     }
    }

if I want to instrument send method in  abstractmessagechannel class. How should I write in bytebuddy?

What I do is below, but it doesn't work.

      ElementMatcher.Junction<MethodDescription>  junction = not(isStatic()).and(ElementMatchers.named("send"));

        junction = junction.and(ElementMatchers.<MethodDescription>isDeclaredBy(typeDescription));

typeDescription here is from org.springframework.integration.channel.AbstractMessageChannel"

    newClassBuilder = newClassBuilder.visit(Advice.to(Class.forName(interceptor,true,classLoader))
                        .on(junction));
here new classBuilder is DynamicType.Builder<?> builder.

**Comment by raphw** [comment]
Do you want to modify this class? In this case, look into defining an agent which is done via the `AgentBuilder` API which requires you to register a Java agent.

**Comment by raphw** [comment]
Please reopen this ticket if you have further questions.
