### ISSUE TITLE
how to instrument constructor by bytebuddy

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#707]
package org.springframework.integration.channel;

    @IntegrationManagedResource
    public abstract class AbstractMessageChannel extends IntegrationObjectSupport implements MessageChannel, TrackableComponent, ChannelInterceptorAware, MessageChannelMetrics, ConfigurableMetricsAware<AbstractMessageChannelMetrics> {

    public AbstractMessageChannel() {
        this.interceptors = new AbstractMessageChannel.ChannelInterceptorList(this.logger);
    }
    }

I want to instrument constructor in the abstractmessagechannel class, how should i do. I try the way, but if doesn't work.

      AgentBuilder.Default(bytebuddy)
     .type(ElementMatchers.isAbstract()
    .and(ElementMatchers.
    named("org.springframework.integration.channel.AbstractMessageChannel")))
                .transform(new AgentBuilder.Transformer.ForAdvice()
                        .include(TraceChannelInterceptor.class.getClassLoader())
                        .advice(ElementMatchers.isConstructor()
                                        .and(ElementMatchers.any()),
                                (TraceChannelInterceptor.class.getName())));

**Comment by raphw** [comment]
Maybe there is a problem in your advice. Please register a `AgentBuilder.Listener.StreamWriting.toSystemOut()` in your agent to see potential problems.

**Comment by zheyiyi** [comment]
I try to add the listener but there are no error to be printed. It is strange

**Comment by raphw** [comment]
Can you give me the advice that you are using? Constructors have some constraints and they should yield exceptions. I wonder if this is what is expected for you.

**Comment by raphw** [comment]
Please reopen this ticket if you have further questions.
