### ISSUE TITLE
Java agent not work as expected

### ISSUE THREAD

**Issue by aftersss** [raphw/byte-buddy#708]
We have the following classes:
```
package com.example;
public interface Car {
	default String get(){
		return "car";
	}
}

package com.example;
public class Bus implements Car{
}
```

We want to intercept  the method `Bus.get` to do something before and after it, so we wrote the following code:

```
package com.example;
public class InterceptTest {

    public interface OverrideCallable {
        Object call(Object[] args);
    }

    public static class CacheInterceptor {

        @RuntimeType
        public Object intercept(
                @AllArguments Object[] allArguments,
                @Morph OverrideCallable zuper
        ) throws Throwable {
            System.out.println("before interceptor");
            try {
                return zuper.call(allArguments);
            }finally {
                System.out.println("after interceptor");
            }
        }
    }

    public static void main(String[] args) {
        Instrumentation ins = ByteBuddyAgent.install();
        new AgentBuilder.Default()
                .type(named("com.example.Bus"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder transform(DynamicType.Builder builder, TypeDescription typeDescription,
                            ClassLoader classLoader, JavaModule module) {
                        return builder.method(named("get"))
                                .intercept(MethodDelegation.withDefaultConfiguration()
                                        .withBinders(
                                                Morph.Binder.install(OverrideCallable.class)
                                        )
                                        .to(new CacheInterceptor()));
                    }
                }).with(new AgentBuilder.Listener.Adapter() {
                    @Override
                    public void onError(String typeName, ClassLoader classLoader, JavaModule module, boolean loaded, Throwable throwable) {
                        throwable.printStackTrace();
                    }
                }).installOn(ins);

        Bus t = new Bus();
        System.out.println(t.get());
    }
}
```

When execute this code, we expect this output:
```
before interceptor
car
after interceptor
```

But actually we get this:
```
com.example.InterceptTest$CacheInterceptor@451001e5
```

We found that if we change the annotation `@Morph` to `@Morph(defaultMethod=true)`, it works as expected. What I real care is that if we wrote the code like this, maybe throw some exception to `AgentBuilder.Listener.onError` to let us know and without changing the class byte code is better. 

Consider that if at the first time the interceptor code works well, and someone changed their code(for example: remove the default method in `Car.class` and move `get` method into `Bus.class`), then if we upgrade the jar dependency which contains `Bus.class`,  the original behavior will be changed unexpectedly.

**Comment by raphw** [comment]
Seems like Byte Buddy is binding to the `toString` method of your target class instead. You can force it to use a specific method by registering an element matcher as filter in the DSL.

Normally, Byte Buddy would bind a method of the most specific type if it was bindable. This does not seem to be the case for you. I wish there was an easier way of debugging this then stepping through your code but set breakpoints in `Morph.Binder` and `AllArguments.Binder` to see why your method is not selected.

**Comment by aftersss** [comment]
OK, Thanks a lot.
