### ISSUE TITLE
Read class-level annotations via ClassReader

### ISSUE THREAD

**Issue by NeumimTo** [raphw/byte-buddy#711]
I need to parse a type level annotations from a class file, without adding the file to the classpath. 

Im trying to utilize the ClassReader, but cannot figure out how to actually extract class annotation. 

```
   try {
            JarFile jarFile = new JarFile(path.toFile());
            Enumeration<JarEntry> entries = jarFile.entries();
            while (entries.hasMoreElements()) {
                JarEntry jarEntry = entries.nextElement();
                if (isClassFile(jarEntry)) {
                    continue;
                }
                try (InputStream is = jarFile.getInputStream(jarEntry)) {
                    ClassReader classReader = new ClassReader(is);
```

Any help will be much appreatiated

**Comment by raphw** [comment]
If you wanted to use Byte Buddy, you can render a `TypeDescription` that gives you access to annotations via:

```java
TypePool typePool = TypePool.Default.of(new ClassFileLocator.Comound(
  ClassFileLocator.ForClassLoader.ofSystemLoader(), 
  new ClassFileLocator.ForJarFile(new JarFile(path.toFile()))));
TypeDescription typeDescription = typePool.describe("some/Type").resolve();
AnnotationList annotations = typeDescription.getAnnotations();
```

**Comment by NeumimTo** [comment]
In my version of bytebuddy The Compound class is not declared as static. I cannot reference.
Im using 1.10.1, thats also the latest version currently avalaible from maven central.

**Comment by raphw** [comment]
I am not sure that I can follow you. Do you not know the name of the class? Any non-dynamic class has a name, even if it might be cryptic.
