### ISSUE TITLE
Disable type caching

### ISSUE THREAD

**Issue by bsideup** [raphw/byte-buddy#713]
Hi!

I am using ByteBuddy in my Java agent **after** applying some ASM transformations (via `instrumentation.addTransformer`).

The ASM transformation removes `native` modifier from some JDK methods. But ByteBuddy seems to cache this info at transformer creation time and does not apply transformations to not-native-anymore methods.

Is it possible to disable the type caching in ByteBuddy and make it act as a `ClassFileTransformer` that only transforms classes explicitly passed to it, without iterating thought the already loaded classes, making any caches, etc etc?

Thanks!

**Comment by raphw** [comment]
This should not happen unless: (a) you are using retransformation with Byte Buddy and (b) you are not registering your ASM transformer as retransformation capable. If this is the case, there is nothing Byte Buddy can do as the JVM will apply the transformation based from the original byte code.

Otherwise, Byte Buddy retains the byte array that is presented to its class file transformer.

**Comment by bsideup** [comment]
@raphw 

I am "using retransformation with Byte Buddy and (b) you are not registering your ASM transformer as retransformation capable", sounds like exactly my case :)

What helped is to retransform classes first, **before creating** ByteBuddy:
https://github.com/reactor/BlockHound/pull/46/files#diff-21558a210d558456b0f5da4268364dc3R232

But I wanted to avoid two retransform passes.

> Otherwise, Byte Buddy retains the byte array that is presented to its class file transformer.

Is it possible to make it re-read the byte array on every transformation pass, and **not** cache any info?

**Comment by bsideup** [comment]
My previous implementation was based on ASM and there was no problem with it (I simply registered two transformers, one for "un-native" logic, and another one for instrumenting the methods), but with ByteBuddy I got a bug because it "remembers" flags and silently skips the transformation of methods that it thinks are native.
Speaking of which, is it possible to enable some debugging logging to see which methods were matched but skipped?

**Comment by raphw** [comment]
I assume that this is because Byte Buddy is using the loaded class for a `TypeDescription` to avoid parsing any byte code. You can configure the agent builder to use `AgentBuilder.DescriptionStrategy.Default POOL_ONLY` where it always interprets the byte code.

**Comment by bsideup** [comment]
@raphw 

Thanks a lot! I confirm that in my case it works with:
```
.with(AgentBuilder.DescriptionStrategy.Default.POOL_FIRST)
.with((AgentBuilder.PoolStrategy) (classFileLocator, classLoader) -> new TypePool.Default(
        new TypePool.CacheProvider.Simple(),
        classFileLocator,
        TypePool.Default.ReaderMode.FAST
        ))
```

I am using `POOL_FIRST` because it is sufficient in my case and I assume it gives a little bit better performance.
I also had to override the pool strategy too because otherwise it eagerly loads `java.lang.Object` and I need to instrument it.

You can find the final version here:
https://github.com/reactor/BlockHound/pull/46/files#diff-21558a210d558456b0f5da4268364dc3R230

**Comment by bsideup** [comment]
It seems to work well, thanks a lot @raphw for telling me about the `DescriptionStrategy` - it was the missing bit indeed 🎉
