### ISSUE TITLE
how to handle exception by bytebuddy

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#717]
if I want to instrument a function,  I use functioninterceptor to start and end span for function, But if when function run, it throw error, how my functioninteceptor to catch it and end my span.
 
    public class FunctionInterceptor {

        @Advice.OnMethodEnter
        private static Span Enter(@Advice.AllArguments Object[] args) {
              Span span = createSpan();
              return span;
        }
       @Advice.OnMethodExit
       static void exit(@Advice.Enter Span span){
           span.end();
       }

Because if function throw error, it won't go into FunctionInterceptor's exit and the span won't end any more.

do we have this in the bytebuddy?

    @Advice.Exception
    static void exception(@Advice.Enter Span span){
    span.end()}

**Comment by raphw** [comment]
Yes, the OnMethodExit annotation has an onThrowable attribute for it. It describes the annotation to handle. Put Throwable to handle any exception. You can find more info in the javadoc.

**Comment by zheyiyi** [comment]
Thanks, it works

**Comment by raphw** [comment]
Great it worked out.
