### ISSUE TITLE
[Question] transform a nested static class

### ISSUE THREAD

**Issue by DigitalMarc** [raphw/byte-buddy#719]
Hey!
Sorry if that one is already answered somewhere but I can't find any answer for that.
I can't transform a nested public static class method such as:

```
public class MasterClass implements SomeClass{
    public static class TargetedClass extends SomeSuperClass {
      ...
        public void someMethodToTransform() {
          ..
        }
    }
}
```

Òne of the many code I've tried to inject: 
```
agent.type(ElementMatchers.isSubTypeOf(SomeSuperClass.class))
    .transform((builder, typeDescription, classLoader, javaModule) -> builder.visit(Advice.to(SomeAdvice.class)
    .on(named("someMethodToTransform"))));
```

Many thanks!

**Comment by raphw** [comment]
The problem is your matcher `named("SomeMethodToTransform"))` which specifies to match a method of this name whereas you are trying to match a constructor. Use `isConstructor()` instead.

**Comment by DigitalMarc** [comment]
Sorry I've badly written the example code as that's a method. I've updated the example accordingly.

**Comment by raphw** [comment]
It should not matter, specify `.disableClassFormatChanges()` additionally to retransformation, maybe this helps. Also register `.with(AgentBuilder.Listener.StreamWriting.toSystemOut())` to see if the class is picked up.

**Comment by DigitalMarc** [comment]
All good! I had already intercepted that class somewhere else earlier... Thanks for the help!
