### ISSUE TITLE
Hitting Oracle-specific issue loading class as resource from bootstrap classloader

### ISSUE THREAD

**Issue by jpfourny** [raphw/byte-buddy#720]
Hi Ralph,

I have been trying to upgrade Byte-Buddy in my projects recently, but I am hitting an issue with Oracle JRE 1.8, although it works fine on IBM JRE 1.8. I have not yet tried OpenJDK.

With newer versions of ByteBuddy (starting some time in 1.9 branch), some code changed around loading the class bytes for an Advice class. It is kicked of with a call to `Advice.to(XXX.class)` and you will see an error throw like this:

> java.lang.IllegalStateException: Could not locate class file for XXX
> 	at net.bytebuddy.dynamic.ClassFileLocator$Resolution$Illegal.resolve(ClassFileLocator.java:118)
> 	at net.bytebuddy.asm.Advice.to(Advice.java:343)
> 	at net.bytebuddy.asm.Advice$WithCustomMapping.to(Advice.java:10946)
> 	at net.bytebuddy.asm.Advice$WithCustomMapping.to(Advice.java:10935)
> 	at net.bytebuddy.asm.Advice$WithCustomMapping.to(Advice.java:10924)
> ...

The reproduction of this requires the following:
- Run with Oracle Java 8
- Run as pre-main Java agent
- Append the JAR containing advice class XXX to bootstrap classpath via Instrumentation API
- Invoke `Advice.to(XXX.class)` and it goes boom.

FYI: The reason the advice class is on bootstrap class path is because it injects monitoring into java.io classes.

After some experimentation, it seems the resource-loading from Oracle bootstrap class loader cannot reliably see items that are injected into the bootstrap classpath via Instrumentation API from pre-main entry point. Class loading works, but not resource loading. I have found a few whispers of this issue scattered across the internet in archived forums posts, but no real action or defects logged against Oracle. I know this is an Oracle issue and not Byte-Buddy, but maybe you can think of a workaround? 

One more nugget of info: Injecting the same class into the system classloader via Instrumentation API works just fine - this is specific to bootstrap.

**Comment by jpfourny** [comment]
I wonder if I could work around  this by:
1.  Inject JAR into both bootstrap and system classpath (so resource can be loaded via system classloader)
2. Use Advice.to(TypeDescription advice, ClassFileLocator classFileLocator), and pass in a custom ClassFileLocator feed by system classloader.

I am going to try it.

**Comment by jpfourny** [comment]
My work around is a success! A little hacky, but functional. Feel free to close this issue.

**Comment by raphw** [comment]
It should not be necessary to put the advice class onto the bootstrap loader. Its code is inlined, mainly with the purpose to avoid such class loader issues. What problem do you experience when you just keep the advice class in its original loader?

**Comment by jpfourny** [comment]
Unfortunately, not all my advice is 100% inline. I call out to shared utility methods and static variables which are co-located with the advice. It is convenient for coding, but it means I need to drag the advice classes to bootstrap to make the class members visible to instrumented types. It was a poor design choice, but I have to live with it ... at least until I find time to refactor. ;)

**Comment by raphw** [comment]
Advice does accept a type description that you can compute from a `TypePool` with a `ClassFileLocator` as a second argument. Maybe this can be used to circumvent the problem.

**Comment by jpfourny** [comment]
Yes, that was my work-around. :)
