### ISSUE TITLE
how to instrument silf4j

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#722]
I use the following code to instrument silf4j + logback library, but it doen't work. Can you tell me why?

        defaultAgent = defaultAgent.type(ElementMatchers.isFinal().and(ElementMatchers.named("org.slf4j.LoggerFactory")))
                .transform(new AgentBuilder.Transformer.ForAdvice()
                        .include(SpanLogsInterceptor.class.getClassLoader())
                        .advice(ElementMatchers.isMethod().and(ElementMatchers.isStatic().and(ElementMatchers.nameContains("getLogger"))),
                                (SpanLogsInterceptor.class.getName())));

**Comment by raphw** [comment]
Did you register a `.with(AgentBuilder.Listener.StreamWritting.toSystemOut())` to see if your class is processed by Byte Buddy or if the instrumentation fails? Maybe the class was already loaded when your agent runs.

**Comment by zheyiyi** [comment]
i add .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION) 
it works. But can you explain why?

**Comment by raphw** [comment]
The class then is probably loaded before the agent is installed.
