### ISSUE TITLE
VM crashes when using EmulatedAttachment on Windows 10 with long argument

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#723]
When the agent path plus the argument exceeds 272 chars, the VM crashes with the following message:

```
Process finished with exit code -1073741819 (0xC0000005)
```

When it's more than 264 chars and less than 273 chars, the `agentmain` method receives a truncated argument string.

You can reproduce that by modifying this test
https://github.com/raphw/byte-buddy/blob/2d8040720a603f163891b62f6f61b75ebb56acd3/byte-buddy-agent/src/test/java/net/bytebuddy/agent/VirtualMachineAttachmentTest.java#L49-L61

To use a longer argument, for example, `RandomString.make(300)`.

Is that something that can be worked around/fixed or is that an inherent Windows restriction? In the latter case, it's probably better to fail fast within Byte Buddy than letting the VM crash.

A similar restriction seems to apply for the emulated attach on Posix (Mac OS), as well as the non-emulated attach(`ByteBuddyAgent.AttachmentProvider.ForMudularizedVm`) but the limit seems to be around the 1000 char mark.

**Comment by raphw** [comment]
Bummer, I remember darkly that there was some string-length-checking code but I did forget about it, it seems. I will have to revisit all the sources to find the limits and port that over.

Thanks for the hint!

**Comment by felixbarny** [comment]
Could be this: https://github.com/raphw/byte-buddy/blob/2d8040720a603f163891b62f6f61b75ebb56acd3/byte-buddy-agent/src/main/c/attach_hotspot_windows.c#L31

**Comment by raphw** [comment]
Yes, I think I saw similar things in the Solaris and Posix versions and also for J9. The memory for the argument is always preallocated, that is the problem.

**Comment by raphw** [comment]
I had a look at this and the tricky part is that the target VM sets the restriction. Normally, I'd argue that the target VM should be responsible for checking if the input values fit into the designated containers but this is not the case. Byte Buddy can make an estimated guess what values are suitable but that is not happening here, unfortunately.

As a rule of thumb, the shorter the better but I will have a look in what dimension I can have Byte Buddy detect such shortcomings.

**Comment by felixbarny** [comment]
I've changed the Elastic agent so that it does not provide all arguments as agent args as sooner or later the limit will be hit. What I'm doing now is that I create a temporary properties file and only provide the location of that file. This greatly decreases the risk of running into that limit.

But it probably still makes sense to truncate (or trow an `IllegalArgumentException`) in Byte Buddy as opposed to risk a segfault.

**Comment by raphw** [comment]
A segfault should no longer be possible. I did not check the argument length of the emulated Windows attach to make sure that the argument could fit into the container that I transfer to the target VM, this was fixed. And I also increased the possible string length to ca. 1000 characters.

Did you get segfaults anywhere else?

**Comment by felixbarny** [comment]
Ah, I didn't see those changes.

These fixes are in 1.10.2 and consist of these commits, correct?
- https://github.com/raphw/byte-buddy/commit/7337f97083fe724ba43fb5cb82dba60d8217085e#diff-c8a79b8751f94d66529d0631fda598b0
- https://github.com/raphw/byte-buddy/commit/e7ae507a0978a8d36590fb5ed227bb4bff4e26cc#diff-c8a79b8751f94d66529d0631fda598b0
- https://github.com/raphw/byte-buddy/commit/df6a1fa7ff15d74423fe6449f3aefc677f02cc93#diff-c8a79b8751f94d66529d0631fda598b0

**Comment by raphw** [comment]
Yes, messy as always. I need to fix the release notes.
