### ISSUE TITLE
how to instrument overriding method by buteddy

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#724]
if i have two function     private void applyPayout(LocalDate payoutDate)  and     private void applyPayout()

    ElementMatchers.isMethod().and(ElementMatchers.nameContains("applyPayout"))
will instrument the two function

    ElementMatchers.isMethod()
     .and(ElementMatchers.takesArguments(LocalDate.class))
    .and(ElementMatchers.nameContains("applyPayout"))
will instrument applyPayout(LocalDate payoutDate) function

My question is that how to instrument no parameter function specifically?

**Comment by raphw** [comment]
By for example: `takesArguments(0)`.
