### ISSUE TITLE
Tutorial of migrating cglib to Byte Buddy

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#727]
This is a common question and should be addressed in a step-by-step example.

**Comment by cushon** [comment]
Any chance of prioritizing this, given https://github.com/cglib/cglib/commit/ab2974c61ec13e195500f2df8ba4de95e608d804 ?

**Comment by raphw** [comment]
Yes, indeed. I'll see what I can do next week.

**Comment by raphw** [comment]
Better late then never: http://mydailyjava.blogspot.com/2022/02/using-byte-buddy-for-proxy-creation.html
