### ISSUE TITLE
Adding code to static methods

### ISSUE THREAD

**Issue by mmuzikar** [raphw/byte-buddy#731]
I am trying to add code to static methods (sort of a logging code, I just need to see the arguments), I tried to use Advice, because that looked like exactly the use case I was looking for but got this error:
```
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method io.syndesis.qe.hooks.LocatorSnooper$AdviceInterceptor.lambda$enter$0(Ljava/lang/Object;)Z from class com.codeborne.selenide.Selenide
```
```
ByteBuddyAgent.install();
            new ByteBuddy()
                .rebase(Selenide.class)
                .method(named("$"))
                .intercept(Advice.to(AdviceInterceptor.class))
                .make()
                .load(Selenide.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
    public static class AdviceInterceptor {

        @Advice.OnMethodEnter
        public static void enter(@Advice.AllArguments Object... args){
            ... logging ...
        }
    }
```

When using `MethodDelegation` I was able to get it working as intended, but I don't have access to the "original" method, I am using rebase, so the original method should still exist right? How do I access it? When I use either a `SuperCall` or `DefaultCall` (just to be safe), I get an error that Bytebuddy failed to match the method signatures when I have the Callable in there.

**Comment by raphw** [comment]
You cannot use lambda expressions in your advice code due to the way they are compiled. You should stick to "regular Java" instead.
