### ISSUE TITLE
eclipse  has  complie error  when  using class  " net.bytebuddy.dynamic.loading.ClassInjector.UsingUnsafe.Factory "

### ISSUE THREAD

**Issue by li-nianfeng** [raphw/byte-buddy#733]
sorry ! my  english is  bad ! 
 when I using this class in eclipse. I meet an error like this---"net.bytebuddy.dynamic.loading.ClassInjector.UsingUnsafe.Factory cannot be resolved to a 
 type" !    It's  eclipse's bug??  help me.  In idea ,it works  OK !

**Comment by raphw** [comment]
Either you have an incompatible version on your class path or it is a problem in Eclipse. The Byte Buddy artifacts are well-tested and should be fine.

**Comment by jpfourny** [comment]
Definitely an Eclipse bug. Try Intellij ;)
