### ISSUE TITLE
reset instrumentation 

### ISSUE THREAD

**Issue by khiavit** [raphw/byte-buddy#734]
We have a problem with the resetting instrument that I hoped could help me, we want to intercept a class injecting code and then reversing those changes, the problem is that it does not work for me.

thank you

    @Test
    public void test_byte_buddy() throws ClassNotFoundException {
        Instrumentation instrumentation = ByteBuddyAgent.install();

        ResettableClassFileTransformer installation =  new AgentBuilder.Default()
                .with(new AgentBuilder.InitializationStrategy.SelfInjection.Eager())
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .type((ElementMatchers.any()))
                .transform((builder, typeDescription, classLoader, module) -> builder
                        .method(ElementMatchers.nameContains("idToFileName"))
                        .intercept(Advice.to(TimerAdvice.class))).installOn(instrumentation);

       StaticUtil.idToFileName("value1__value2");

        installation.reset(instrumentation, AgentBuilder.RedefinitionStrategy.RETRANSFORMATION);

        StaticUtil.idToFileName("value1__value2");
    }

    @SuppressWarnings("unchecked")
     public static String fileNameToId(String fileName) {
         String str = null;

        if (fileName != null) {
            str = fileName.replaceAll("/", SLASH_REPLACEMENT);
        }
        return str;
    }

     public class TimerAdvice {
  
      @Advice.OnMethodEnter
      static long enter(@Advice.Origin String method) throws Exception {
         long start = System.currentTimeMillis();
         return start;
     }

    @Advice.OnMethodExit
    static void exit(@Advice.Origin String method, @Advice.Enter long start, @Advice.AllArguments Object[] params, @Advice.Return(readOnly = false, typing = Assigner.Typing.DYNAMIC) Object returned) throws Exception {
        long end = System.currentTimeMillis();
        System.out.println(method + " took " + (end - start) + " milliseconds and params: " + params + " and returned: " + returned);

    }

}

**Comment by raphw** [comment]
Did you try registering an `AgentBuilder.Listener` in your reset? I assume that the resett fails for some reason. You should also set `.disableClassFormatChanges()` what is something most JVMs do not support.

**Comment by khiavit** [comment]
Thank you very much for your response, we got it to work using .enableUnsafeBootstrapInjection ();
Is there a problem that could come out using it?

**Comment by raphw** [comment]
In newer versions, the mechanism is refactored to support Java 9+ and modules. Once you update, provide an unsafe injector, for example, and you should support any JVM.
