### ISSUE TITLE
Is there any way can redefineClass when the class was loaded

### ISSUE THREAD

**Issue by C1tas** [raphw/byte-buddy#735]
Hello , i need some help.

i hava a class named `Stuff`
```java
public class Stuff {
    public Stuff() {
    }

    public void do_stuff() {
        System.out.println("do_stuff");
    }
}
```

I want to add a method `do_stuff2` by using jvm attach api to redefineClass(Stuff, bytecode)

use `Instrumentation` in `agentmain` 

but i get 
`java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method`

would someone like to give me some help or advice

thanks : D

**Comment by raphw** [comment]
No, this is not possible with few exceptions. Have a look at the rather experimental dynamic code evolution JVM: https://github.com/dcevm/dcevm

No regular VM allows redefining a loaded class.
