### ISSUE TITLE
Relax validation on parameter Names

### ISSUE THREAD

**Issue by drodriguezhdez** [raphw/byte-buddy#736]
ByteBuddy version: `1.9.16`

Hi, 

I'm trying to instrument some method on `Scala` which has the a parameter whose name is `interface`.

```
private def tcpBind(interface: String, port: Int, settings: ServerSettings): Source[Tcp.IncomingConnection, Future[Tcp.ServerBinding]] = ???
```

And, I'm obtaining the following error message:

```
java.lang.IllegalStateException: Illegal parameter name of final java.lang.String interface for private akka.stream.scaladsl.Source akka.http.scaladsl.HttpExt.tcpBind(java.lang.String,int,akka.http.scaladsl.settings.ServerSettings)
```

Is there any way to relax this kind of validation?

Thank you very much!

**Comment by raphw** [comment]
Hi, sure, Byte Buddy checks against the Java specification but the JVM is more lax.

You can use `new ByteBuddy().with(TypeValidation.DISABLED)`.

**Comment by drodriguezhdez** [comment]
Thanks!
