### ISSUE TITLE
@Advice.enter doesn't work

### ISSUE THREAD

**Issue by zheyiyi** [raphw/byte-buddy#737]
public class FunctionMetricInterceptor {
    public static Logger logger = LoggerFactory.getLogger(FunctionMetricInterceptor.class);
    @Advice.OnMethodEnter
    private static long Enter(@Advice.Origin Class cls, @Advice.Origin Method method, @Advice.AllArguments Object[] args) throws WrongInputTagException {
        long start = System.nanoTime();
        System.out.println("start" + start);
        return start;
    }

    @Advice.OnMethodExit(onThrowable = Throwable.class)
    private static void  exit( @Advice.Thrown Throwable t,@Advice.Origin Class cls, @Advice.Origin Method method, @Advice.Enter Long start) throws WrongOutputTagException {
        logger.info(method.getName() + "end to run");
        System.out.println(start);
    }
}

  System.out.prinlnt(start) cause this error

 Can you tell me why in exit method, my @@Advice.Enter Long start can not get the start return from enter method?

**Comment by raphw** [comment]
I assume that the reference to `logger` is the problem. Your advice code is inlined meaning that the `logger` field mig.ht not be available to the executed code. Try calling `LoggerFactory` from your code directly

**Comment by zheyiyi** [comment]
logger works fine. My problem is not logger. I simplify the code.

    public class FunctionMetricInterceptor {
    @Advice.OnMethodEnter
    private static long Enter(@Advice.AllArguments Object[] args) throws WrongInputTagException {
    long start = System.nanoTime();
    return start;
}


    private static void  exit( @Advice.Enter Long start) throws WrongOutputTagException {
    System.out.println(start);
}

In this case,  when i print start, jvm break

**Comment by raphw** [comment]
How so? Is there an exception?

**Comment by zheyiyi** [comment]
2019-10-02 18:46:17.300  INFO 62395 --- [nio-8080-exec-2]
c.i.m.plugins.FunctionMetricInterceptor  : payend to run
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011db24a52, pid=62395, tid=0x0000000000008c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_191-b12) (build
1.8.0_191-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.191-b12 mixed mode
bsd-amd64 compressed oops)
# Problematic frame:
# j  com.ivoyant.payment.pay(I)V+380
#
# Failed to write core dump. Core dumps have been disabled. To enable core
dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/zheyiyi/Desktop/traceAgent2/hs_err_pid62395.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp

Rafael Winterhalter <notifications@github.com> 于2019年10月2日周三 下午6:24写道：

**Comment by zheyiyi** [comment]
if i use threadlocal save start, it works fine

public class FunctionMetricInterceptor {
@Advice.OnMethodEnter
private static long Enter(@Advice.AllArguments Object[] args) throws WrongInputTagException {
long start = System.nanoTime();
 TimeRecordThreadLocal.setLocal(start);
return start;
}


private static void  exit( @Advice.Enter Long start) throws WrongOutputTagException {
System.out.println(TimeRecordThreadLocal.getLocal());
}

**Comment by raphw** [comment]
Unsure what this is, can you create a reproducer? This should really not happening. But if your second example works, it seems like the reading of the enter value is the issue.

What JVM version are you running? Could you try to make the `@Enter` value a primitive `long`?

**Comment by raphw** [comment]
Please reopen if you still have issues.
