### ISSUE TITLE
Applying advices to methods confuses debugger

### ISSUE THREAD

**Issue by felixbarny** [raphw/byte-buddy#739]
This is basically the same issue as reported in https://stackoverflow.com/questions/52067467/byte-buddy-advice-breaks-eclipse-debugger.

I am able to reproduce with IntelliJ Ultimate 2019.2.3 by setting a breakpoint here:

https://github.com/raphw/byte-buddy/blob/7a41b53d7023ae047be63c8cef2871fd5860b032/byte-buddy-dep/src/test/java/net/bytebuddy/agent/builder/AgentBuilderDefaultApplicationRedefinitionReiterationTest.java#L131

The variables tab in the debugger window says 
> x = 'this' is not available

Whenever there's a `@OnMethodEnter` advice, the `this` reference is not available in the first line of the method. When a `@OnMethodExit` advice is applied, `this` can't be resolved in the whole method.

As described in the SO post, setting `@OnMethodEnter(prependLineNumber = false)` and `@OnMethodExit(backupArguments = false)` helps.

**Comment by raphw** [comment]
There is not much to be done, this is how the debuggers are implemented without that this would be a constraint in the debugging API of the JVM. Without a line number, IntelliJ assumes to be browsing synthetic code, I assume it is confused that the break point is already entered and works around something else. Without the argument backup, I assume it is confused that the `this` reference is reassigned.

I am pretty sure this is to avoid bugs with obfuscators and "strange languages" and breakpoints in decompiled code of those languages. I cannot work around this, I tried, but you can file it with Jet Brains.

**Comment by felixbarny** [comment]
Alright, so let's close as "wont fix".

Could you maybe describe the drawbacks of `prependLineNumber = false` and `backupArguments = false`?
