### ISSUE TITLE
How to use MethodDelegation for interface type

### ISSUE THREAD

**Issue by fantasticmao** [raphw/byte-buddy#742]
Hi, I am new to use Byte Buddy, and I use it to write a Java Agent, but now I meet some problems with using MethodDelegation for interface type. Sample code like this:

```java
new AgentBuilder.Default()
    .with(AgentBuilder.Listener.StreamWriting.toSystemOut().withTransformationsOnly())
    .type(ElementMatchers.named("org.springframework.web.servlet.HandlerAdapter"))
    .transform(((builder, typeDescription, classLoader, module) -> builder
        .method(ElementMatchers.named("handle"))
        .intercept(MethodDelegation.to(new MyInterceptor()))
    ))
    .installOn(inst);
```

It works well with an specific implemented subclass type like `org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter`, but when I change it to the supper interface type, I will get an exception: `java.lang.IllegalStateException: Cannot only define public, static, final field 'delegate$k8sj6c0' for interface type`.

I know Byte Buddy will use asm to create a `public static volatile` delegate filed (as the picture which is shown below) when the target type is `class`, but it looks like that Byte Buddy will do the same logic for the `interface` type.

![image](https://user-images.githubusercontent.com/20675747/66988314-e79ca500-f0f4-11e9-9631-cc3203eafc0d.png)

I wonder how to enhance the interface type in Byte Buddy. Looking forward to your reply, thank you very much.

**Comment by raphw** [comment]
Yes, this is a bit of a contradiction, I never thought much of this case with default methods in interfaces, to be honest. Byte Buddy is falling victim to its own validation in this case.

Can you try disabling type validation via:

```
new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED))
```

and see if it works?

**Comment by raphw** [comment]
You probably want to match the entire hierarchy? Try:

```
hasSuperType(named("org.springframework.web.servlet.HandlerAdapter")).and(not(isInterface()))
```

This matches all classes that implement the interface but not the interfaces itself.

**Comment by FantasticMao** [comment]
Yes, I want to enhance all subclass of `org.springframework.web.servlet.HandlerAdapter` and record some HTTP request data. But I think it might cause repeat calls of the enhance logic via match all subclass, in some scenarios. Think of the following example:

```java
interface A {

    void foo();
}

class A_Decorator implements A {
    A a;

    public A_Decorator(A a) {
        this.a = a;
    }

    @Override
    public void foo() {
        a.foo();
    }
}

class B implements A {

    @Override
    public void foo() {
        System.out.println("Hello B");
    }
}
```

Finally I will execute `new A_Decorator(new B()).foo()`. If I match all subclass of `A`, the generated code by Byte Buddy would be like:

```java
interface A {

    void foo();
}

class A_Decorator implements A {
    A a;

    public A_Decorator(A a) {
        this.a = a;
    }

    @Override
    public void foo() {
        // enhance logic
        a.foo();
    }
}

class B implements A {

    @Override
    public void foo() {
        // enhance logic
        System.out.println("Hello B");
    }
}
```

But the code in need that I want is:

```java
interface A {

    default void foo() {
        // enhance logic
        _foo();
    }

    void _foo();
}

class A_Decorator implements A {
    A a;

    public A_Decorator(A a) {
        this.a = a;
    }

    @Override
    public void _foo() {
        a.foo();
    }
}

class B implements A {

    @Override
    public void _foo() {
        System.out.println("Hello B");
    }
}
```

I think it might be a bit strange, but can I implement such a function in Byte Buddy?

**Comment by raphw** [comment]
To achieve this, you would need to redirect all invcations in a custom manner, I would not recommend this. Rather, I would instrument all methods and then rather use some mechanism like the `StackWalker` API to identify your caller and to skip your instrumentation logic in case it is duplicated.

**Comment by FantasticMao** [comment]
Good idea, thank you for your advice!
