### ISSUE TITLE
JDK version in GitHub Actions

### ISSUE THREAD

**Issue by sormuras** [raphw/byte-buddy#743]
https://github.com/raphw/byte-buddy/blob/a207f2e9199b2a5adc2323e0d137c300c0fffa38/.github/workflows/main.yml#L22

IIRC, this will only work within a single GH Actions step, as the modifications to the `PATH` and `JAVA_HOME` environment variables only apply to the current shell session -- each step is run it its own shell session.

Same applies to the `OpenJ9` matrix down below in the `main.yml` workflow file.

Either use a multi-line script:
```
- name: 'Install JDK & Build project (without Gradle)'
  run: |
    . .ci/install-jdk.sh --feature ea --os linux-x64
    ./mvnw verify -Dnet.bytebuddy.test.ci=true -pl !byte-buddy-gradle-plugin
```

Or resort to `actions/setup-java@1` with passing a local `jdkFile`.
Or find out what makes a change to `PATH` ["permanent"](https://github.blog/changelog/2019-10-01-github-actions-new-workflow-syntax-features/#env-at-the-workflow-and-job-level) within an entire job run

**Comment by raphw** [comment]
Fixed on master.
