### ISSUE TITLE
GIT chokes on Windows file name case

### ISSUE THREAD

**Issue by sormuras** [raphw/byte-buddy#744]
Can't update my fork due to a directory `license` and a regular file named `LICENSE`. _There can only be one..._ on this OS. The other one is always "auto-deleted".

![image](https://user-images.githubusercontent.com/2319838/67066049-0b053580-f171-11e9-8a5d-a7a28135301e.png)

Underlying reason: https://stackoverflow.com/questions/27749219/working-in-git-with-directories-with-the-same-name-but-different-case-in-windows

Rename one of them?

**Comment by raphw** [comment]
Thanks, I renamed the folder, never thought about it.
