### ISSUE TITLE
Advice on how to delegate using ByteBuddy

### ISSUE THREAD

**Issue by pdoro** [raphw/byte-buddy#746]
Hi. I'm trying to proxy a class in order to apply cross cutting logic. To do so I'm using `MethodDelegation` with `Pipe`. I've provided a demo code to help. I'm facing several problems and have some questions I wish someone could answer.

FYI. I'm using ByteBuddy 1.10.1

- The class `CustomService` does not have a no-args constructor so I'm afraid I can't instanciate using `newInstance()` on the loaded class.This means I cannot proxy a class without no-args constructor or is there any alternative for this? (the only solution I see is providing an ad-hoc interface `CustomInterface` to allow reflection to work)
- How could I select a method whose return type is `Collection<Integer>`? I've tried `returnGeneric()` by I don't really find the way to go.
- Is there any problem using ClassLoadingStrategy INJECTION to wrap a proxy inside another one?
- When I try to build a proxy subclassing `CustomInterface` an `AbstractMethodError` is thrown. Why is this? How should I proxy then? **Update**: Looks like I was using the api incorrectly, I was missing  `intercept(MethodDelegation.to(delegate, clazz))` in order to delegate all method invocations to the delegate except for the most specific `ElementMatchers`
- In `InterceptorB#intercept` the method signature is `public Collection<String> intercept(@Pipe Function<Object, Collection<String>> pipe)`. Is this signature ok for ByteBuddy? What happens if the signature does not match the expected one? An RuntimeException is thrown or the method is not called at all?

```java
package com.sample;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.implementation.bind.annotation.Pipe;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Objects;
import java.util.function.Function;

import static net.bytebuddy.matcher.ElementMatchers.*;

public class MinimalExample {

    interface CustomInterface {
        Collection<String> method1(String param1, int param2);
        Collection<Integer> method2();
    }

    static class CustomService implements CustomInterface {

        private final String field1;
        private final String field2;

        CustomService(String field1, String field2) {
            this.field1 = Objects.requireNonNull(field1);
            this.field2 = Objects.requireNonNull(field2);
        }

        @Override
        public Collection<String> method1(String param1, int param2) {
            return Arrays.asList(param1, field1, field2);
        }

        @Override
        public Collection<Integer> method2() {
            return Arrays.asList(1, 2, 3);
        }
    }

    static class InterceptorA<T, K> {

        private final T delegate;

        InterceptorA(T delegate) {
            this.delegate = Objects.requireNonNull(delegate);
        }

        @RuntimeType
        public K intercept(@Pipe Function<Object, K> pipe) {
            // custom logic
            K result = pipe.apply(delegate);
            // custom logic
            return result;
        }

        public static <T> T proxy(T delegate, Class<T> clazz) throws IllegalAccessException, InstantiationException {
            return new ByteBuddy()
                    .subclass(clazz)
                    .method(isPublic().and(returns(List.class)))
                    .intercept(MethodDelegation.withDefaultConfiguration()
                            .withBinders(Pipe.Binder.install(Function.class))
                            .to(new InterceptorA<>(delegate)))
                    .make()
                    .load(ClassLoader.getSystemClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                    .getLoaded()
                    .newInstance();
        }
    }

    static class InterceptorB<T> {

        private final T delegate;

        InterceptorB(T delegate) {
            this.delegate = Objects.requireNonNull(delegate);
        }

        public Collection<Integer> intercept(@Pipe Function<Object, Collection<Integer>> pipe) {
            // custom logic
            Collection<Integer> result = pipe.apply(delegate);
            // custom logic
            return result;
        }

        public static <T> T proxy(T delegate, Class<T> clazz) throws IllegalAccessException, InstantiationException {
            return new ByteBuddy()
                    .subclass(clazz)
                    .method(isPublic().and(named("method2")))
                    .intercept(MethodDelegation.withDefaultConfiguration()
                            .withBinders(Pipe.Binder.install(Function.class))
                            .to(new InterceptorB<>(delegate)))
                    .make()
                    .load(ClassLoader.getSystemClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                    .getLoaded()
                    .newInstance();
        }
    }


    public static void main(String[] args) throws InstantiationException, IllegalAccessException {

        // Caused by: java.lang.NoSuchMethodException: com.sample.MinimalExample$CustomService$ByteBuddy$7ZOm8l23.<init>()
        CustomService service = new CustomService("field1", "field2");
        service = InterceptorA.proxy(service, CustomService.class);
        service = InterceptorB.proxy(service, CustomService.class);

        service.method1("param1", 1);
        service.method2();

        CustomInterface otherService = new CustomService("field1", "field2");
        otherService = InterceptorA.proxy(otherService, CustomInterface.class);
        otherService = InterceptorB.proxy(otherService, CustomInterface.class);
        
        // Exception in thread "main" java.lang.AbstractMethodError: com.sample.MinimalExample$CustomInterface$ByteBuddy$TImvCJLa.method1(Ljava/lang/String;I)Ljava/util/Collection;
        otherService.method1("param1", 1);
        otherService.method2();
    }
}
```

**Comment by raphw** [comment]
1. You are right, you cannot instantiate a class without a no-argument constructor. It is impossible to express such a thing in byte code without irritating the Java verifier which is why Byte Buddy does not support it either. Instead, generate a constructor and use a library like Objenesis to create your instance. This might break in the future, too, but for now this is a common way of approaching this problem.
2. Easiest is to implement a custom matcher where you just check if the raw type is a `List`, the generic type is `PARAMETERIZED` and then you check if the single parameter is an `Integer`. Just implement an `ElementMatcher` and access the properties of the `TypeDescription.Generic` for it. The DSL does not offer too much around generics as there are too many options.
3. No, I'd prefer that strategy for proxies. It uses some unsafe API but can easily be substituted by the one using method handles from Java 9 up.
4. An `AbstractMethodError` is thrown if you do not implement all interface methods.
5. For method delegations, Byte Buddy does not currently consider the generic types, only the raw ones. If you instrumented method does however not return a `Collection` type, the delegation is not bound and any other available method is considered. The mechanism is detailed in the Javadoc. You can also put `Object` as return and pipe targets and annotate the interception method with `@RuntimeType` to ask Byte Buddy for type castings.

**Comment by pdoro** [comment]
Thanks for the response @raphw

So the parametrized element matcher should look like these:
```java
method(isDeclaredBy(clazz).and(returnsGeneric(type -> {
    type.asErasure().represents(Collections.class)
                    && type.getSort().isParameterized()
                    && type.getTypeArguments().get(0).asErasure().isAssignableFrom(Integer.class);
})))
```

One last question. Is it safe to reuse `ByteBuddy` instances? Is the creation a heavy process?

**Comment by raphw** [comment]
Yes, all of Byte Buddy is immutable. You should reuse as much as possible.
