### ISSUE TITLE
Need an advice on how to shade ByteBuddy's DLLs

### ISSUE THREAD

**Issue by bsideup** [raphw/byte-buddy#747]
Hi,

Since ByteBuddy includes the self-attach DLLs for Windows, it becomes tricky to shade it.

Could you please share some advices on how to properly shade it?
Maybe ByteBuddy can handle the shading in a way Netty does it? (via the `packagePrefix` system property, as was suggested by... [you](https://github.com/testcontainers/testcontainers-java/issues/178#issuecomment-234058671) :D)

Thanks!

**Comment by raphw** [comment]
As mentioned in the linked ticket: there is no JNI involved and therefore shading works just fine. It's an opt-in feature to begin with and if you do not intend to use it, Byte Buddy will simply not consider the approach.

**Comment by bsideup** [comment]
@raphw let's say I want my users to be able to opt-in. I shaded ByteBuddy, and also want to move the DLLs to the shaded package, so that they won't overlap with non-shaded ByteBuddy DLLs.
Since BB will expect them under `/win32-*/*.dll` path of the classpath, the files will be missing.

Is there some property or anything else to set, so that BB will be looking for them in some another directory?

**Comment by raphw** [comment]
JNA expects that folder but this can be overridden by setting properties according to the doc: https://java-native-access.github.io/jna/4.5.0/javadoc/index.html?com/sun/jna/NativeLibrary.html

However, for picking files up on the class path, there is not much choice as that is not customizable. Would be something to put forward in the JNA project. 

However, if the file is added twice, it would be discovered as expected and the overlap would not matter much as long as the API stays stable what I somewhat expect.

**Comment by bsideup** [comment]
@raphw okay, I see. I would still prefer to prefix the files, so that they become `reactor.blockhound.shaded.attach_hotpost_windows.dll` and be able to tell ByteBuddy to use the `reactor.blockhound.shaded.`, but at least I got your point about the JNA now 👍

**Comment by raphw** [comment]
Would be a nice addition to JNA upon the `loadLibrary` call to avoid accidental conflicts in DLL names.

**Comment by bsideup** [comment]
@raphw 

Not sure that this is JNA's responsibility.

Would you consider accepting a PR that will add a prefix support to this call?
https://github.com/raphw/byte-buddy/blob/ae14ba1ea49f661ba82c618dae0d54b3728ee1c2/byte-buddy-agent/src/main/java/net/bytebuddy/agent/VirtualMachine.java#L1228

Since it is an arbitrary string, ByteBuddy could prepend an optional prefix to the file's name

**Comment by raphw** [comment]
Good point, I just added a property which will be available in 1.10.3. (`net.bytebuddy.library.name`).

**Comment by bsideup** [comment]
@raphw thank you so much! I will try it once released 👍 Need to check whether Gradle Shadow Plugin will rename that property or not.
