### ISSUE TITLE
[Question] Intercept HTTP Call

### ISSUE THREAD

**Issue by davidasync** [raphw/byte-buddy#749]
I have jetty application,
This application have many http call requests to other services. e.g to elastic cache, elastic search, mongo, or other jetty application server

Last month our application down, because we didn't notice some of this application's dependency which is dynamo db is down,after several check we notice that issue and our application is up again

We decided to create java agent or something else to intercept all http call and ends up to byte-buddy

So my question,
Is there any easiest way to intercept all http call without listing all class that do the http call

**Comment by raphw** [comment]
You can write an agent that for example intercepts all calls to `Servlet::service`. This way, you can listen to any call to a servlet container without any specifics.

There are already tools for this, for example https://www.testcontainers.org/ as a free tool or https://www.instana.com/ for a commercial one which are both based on Byte Buddy.

**Comment by davidasync** [comment]
> You can write an agent that for example intercepts all calls to `Servlet::service`. This way, you can listen to any call to a servlet container without any specifics.
> 
> There are already tools for this, for example [stagemonitor.org](https://www.stagemonitor.org/) as a free tool or [instana.com](https://www.instana.com/) for a commercial one which are both based on Byte Buddy.

I see, 
btw another question (sorry for noob question), 
I want to trace my application interaction with redises and memcacheds
Is it possible to intercept redis and get the host and latency during runtime with this library ?

could you provided documentation related with this

**Comment by raphw** [comment]
You can instrument the driver for these libraries to do so. You can have a look at Stagemonitor if you want to see an example.
