### ISSUE TITLE
[Question] Get Property of the Object During OnMethodEnter

### ISSUE THREAD

**Issue by davidasync** [raphw/byte-buddy#752]
Hi,
Is it possible to get property name during onMethodEnter

For background, 
I want to trace redison client, 
the host is given during redis client constructor

so is it possible to get host during onMethodEnter

**Comment by raphw** [comment]
You want to read a field? Use @Advice.Field for this.

David Async <notifications@github.com> schrieb am Fr., 25. Okt. 2019, 00:15:
