### ISSUE TITLE
Question : How can I change the field constant value?

### ISSUE THREAD

**Issue by jaeukchoi** [raphw/byte-buddy#756]
How can I change the field constant value?
example):
before-> public static final String DATA = "Hello";
after-> public static final String DATA = "Bye";

**Comment by raphw** [comment]
You can set: `.field(named("DATA")).value("Bye")` in a redefinition.

Do however note that javac copies such compile-time constants and Byte Buddy has no chance to track where the constant was copied to under source compilation.
