### ISSUE TITLE
Gradle plugin jar is missing classes

### ISSUE THREAD

**Issue by ohad7** [raphw/byte-buddy#758]
I experienced a few challenges using the gradle plugin. 

1. Gradle complains if you just put the plain plugin

```
* What went wrong:
Plugin [id: 'net.bytebuddy.byte-buddy-gradle-plugin'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)

```
It's possible to overcome by adding a version: 

`id 'net.bytebuddy.byte-buddy-gradle-plugin' version '1.10.2' `

2. Gradle throws a class not found exception when invoking the plugin: 

```
Caused by: java.lang.NoClassDefFoundError: net/bytebuddy/dynamic/scaffold/inline/MethodNameTransformer
        at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:69)
        at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:55)
        at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:35)
        at org.gradle.internal.instantiation.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:213)
        at org.gradle.internal.instantiation.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:161)
        ... 157 more
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.dynamic.scaffold.inline.MethodNameTransformer
        ... 162 more
```

The reason is that the jar that's published in maven contains only the plugin classes. Not sure if the right thing to do is to fatjar the missing classes, I was able to overcome it by adding it into the configuration :

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.net.bytebuddy:byte-buddy-gradle-plugin:1.10.1"
    classpath "net.bytebuddy:byte-buddy-dep:1.10.1"
  }
}
```

3. It's awesome that you can configure the plugin, could be that it's worth while to add an example for configuring a plugin with an argument:

```
configurations {
  examplePlugin
}

dependencies {
  examplePlugin "foo:bar:1.0"
}

byteBuddy {
  transformation {
    plugin = "com.yahoo.MyPlugin"
    classPath = configurations.examplePlugin
    argument { value = 'Some parameter' }
  }
}
```

**Comment by raphw** [comment]
I argue that (1) works as designed. Byte Buddy is uploaded to Gradle's plugin repository but it is not an official Gradle plugin, therefore you need to specify the number.

As for (2), I was not aware of that, thanks for reporting. I probably need to shade the plugin artifact before uploading it to Gradle. I will look into how this can be done.

**Comment by raphw** [comment]
For (2), this is a build option to explore: https://gist.github.com/melix/574b32a710c5bf5063ee7a34c888697a

**Comment by raphw** [comment]
This should be fixed now and should work with the next release.

**Comment by raphw** [comment]
Version 1.10.5 is released where this should be fixed. Please reopen this ticket, if you still have problems.
