### ISSUE TITLE
[Question] java.lang.IllegalAccessError: tried to access class

### ISSUE THREAD

**Issue by davidasync** [raphw/byte-buddy#761]
I want to create visitor for redisson library to get latency for each operation at class [org.redisson.command.CommandAsyncService](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/command/CommandAsyncService.java)

Here's my code

**// CommandAsyncServiceVisitor.kt**
```
  private const val clazz = "org.redisson.command.CommandAsyncService"

  override fun getMatcher(): ElementMatcher<TypeDescription> {
    // Reference https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/command/CommandAsyncService.java
    return nameContains<TypeDescription>(clazz)
      .and(not(isInterface()))
      .and(not(isStatic()))
  }


  override fun applyVisitor(builder: DynamicType.Builder<*>): DynamicType.Builder<out Any>? {
    return builder
      .visit(
        Advice
          .to(CommandAsyncServiceVisitor::class.java)
          .on(hasMethodName("get"))
      )
  }

  @JvmStatic
  @Advice.OnMethodEnter()
  @Throws(Exception::class)
  private fun enter(@Advice.Argument(value = 0, readOnly = false) rFuture: RFuture<*>) {
    val startTime = System.currentTimeMillis()

    rFuture.addListener {
      println(startTime - System.currentTimeMillis())
    }
  }
```
**// Agent.kt**
```
object Agent {
  @JvmStatic
  fun premain(arguments: String?, instrumentation: Instrumentation?) {
    AgentBuilder.Default()
      .with(AgentBuilder.InitializationStrategy.SelfInjection.Eager())
      .with(AgentBuilder.Listener.StreamWriting.toSystemOut()) // For debugging purpose
       .type(CommandAsyncServiceVisitor.getMatcher())
       .transform { builder, typeDescription, classLoader, module ->
         CommandAsyncServiceVisitor.applyVisitor(builder)
       }
      .installOn(instrumentation)
  }
}
```

But I got this error, 
Any advice ? why this happened ?

```
java.lang.IllegalAccessError: tried to access class com..agent.profiler.instrumentation.CommandAsyncServiceVisitor$enter$1 from class org.redisson.command.CommandAsyncService
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:140)
	at org.redisson.RedissonObject.get(RedissonObject.java:74)
	at org.redisson.RedissonBucket.set(RedissonBucket.java:131)
	at com..dependency.sample.SampleRedissonActionKt.sampleRedissonAction(SampleRedissonAction.kt:23)
	at com..dependency.sample.SampleServiceKt.main(SampleService.kt:5)
	at com..dependency.sample.SampleServiceKt.main(SampleService.kt)
```

**Comment by raphw** [comment]
Kotlin creates an anonymous subclass to implement the callback which is package private. Since advice is a template, the code is inlined into target methods which typically are defined within other packages. 

To overcome this, define the class explicitly and public. If the class loader that is targeted does not see your agents class loader, you will also need to inject your callback. Have a look at ClassInjector for this.

**Comment by davidasync** [comment]
waw thanks !!

**Comment by QizhengMo** [comment]
> Kotlin creates an anonymous subclass to implement the callback which is package private. Since advice is a template, the code is inlined into target methods which typically are defined within other packages.
> 
> To overcome this, define the class explicitly and public. If the class loader that is targeted does not see your agents class loader, you will also need to inject your callback. Have a look at ClassInjector for this.

Thank you from 2024
