### ISSUE TITLE
[Q] How to redefine complete methods using AgentBuilder

### ISSUE THREAD

**Issue by drodriguezhdez** [raphw/byte-buddy#766]
`JDK: 1.8`
`ByteBuddy: 1.10`

Hi, 

I know you've answered this questions a couple of times, but I'm checking the response of this Stackoverflow question (https://stackoverflow.com/questions/54968317/how-to-use-agentbuilder-replace-the-method-of-class), but I am not able to obtain the desired behaviour.

I'm trying to redefine a couple of methods from `org.junit.runners.BlockJUnit4ClassRunner` of `JUnit4`.

Class with redefined methods:

```
public class NewBlockJUnit4ClassRunner extends BlockJUnit4ClassRunner {

    public NewBlockJUnit4ClassRunner(Class<?> klass) throws InitializationError {
        super(klass);
        System.out.println("------------ NewBlockJUnit4ClassRunner constructor");
    }

    @Override
    public void run(RunNotifier notifier) {
        System.out.println("-------------- NewBlockJUnit4ClassRunner: before run");
        super.run(notifier);
        System.out.println("-------------- NewBlockJUnit4ClassRunner: after runChild");
    }

    @Override
    protected void runChild(FrameworkMethod method, RunNotifier notifier) {
        System.out.println("-------------- NewBlockJUnit4ClassRunner: before runChild");
        super.runChild(method, notifier);
        System.out.println("-------------- NewBlockJUnit4ClassRunner: after runChild");
    }
}
```

And the AgentBuilder:

```
new AgentBuilder.Default()
   .ignore(none())
   .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
   .with(AgentBuilder.TypeStrategy.Default.REDEFINE)
   .with(AgentBuilder.RedefinitionStrategy.REDEFINITION)
   .type(named(instrumentedClassName)).transform(new AgentBuilder.Transformer() {
       @Override
       public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
              return new ByteBuddy().redefine(NewBlockJUnit4ClassRunner.class).name(BlockJUnit4ClassRunner.class.getName());
           }
    })
);
```

When I set a Listener to check everything is correct, it is:
`---- onTransformation: org.junit.runners.BlockJUnit4ClassRunner`

Once the class has been redefined, I create a test to use that Runner:

```
    @Test
    public void should_use_instrumented_runner() {
        applyInstrumentation(new Runnable() {
            @Override
            public void run() {
                try {
                    final JUnitCore jUnitCore = new JUnitCore();
                    final Result result = jUnitCore.run(new JUnit4(TestSucceed.class));
                    assertThat(result.wasSuccessful());
                } catch (Exception e){
                    e.printStackTrace(System.err);
                }
            }
        });
    }
```

I'm expecting to see `System.out` traces, but nothing appears.

Did I miss something in the code?

**Comment by drodriguezhdez** [comment]
OK, it seems there is an error It's not being shown in the Listener:

![image](https://user-images.githubusercontent.com/29516565/68384011-007a0280-0157-11ea-8704-c643b9ee18b4.png)

Is it possible to redefine methods from superclasses or interfaces?

**Comment by raphw** [comment]
I assume that the replacement defines fields or methods that do not appear in the original class. This is not supported by most JVMs.

**Comment by drodriguezhdez** [comment]
I'm trying to substitute some methods of `BlockJUnit4ClassRunner` to add certain custom logic to `runChild` and `runLead` methods.

So, the changes should be:
- Avoid extending the class.
- To have exactly the same class content, and then, modify the methods you want.

It is that correct?
