### ISSUE TITLE
MethodDelegation.to does not work in remote  web application enviroment.but work in local  main application.

### ISSUE THREAD

**Issue by chrishyc** [raphw/byte-buddy#767]
`private static final String ENHANCE_CLASS_CLIENT_CREATE = "com.facebook.swift.service.ThriftClientManager";
    private static final String ENHANCE_METHOD_CLIENT_CREATE = "createClient";

AgentBuilder.Transformer transformer = (builder, typeDescription, classLoader, javaModule) -> {
            String className = typeDescription.getTypeName();
            if (ENHANCE_CLASS_CLIENT_CREATE.equals(className)) {
            // can go into here.
                return builder
                        .method(ElementMatchers.named(ENHANCE_METHOD_CLIENT_CREATE)) //
                        .intercept(MethodDelegation.to(ThriftClientManagerInterceptor.class));
            }
        };

new AgentBuilder
                .Default()
                .type(ElementMatchers.named(ENHANCE_CLASS_SERVER)
                        .or(ElementMatchers.named(ENHANCE_CLASS_CLIENT_CREATE)))
                .transform(transformer)
                .with(AgentBuilder.Listener.StreamWriting.toSystemError())
                .with(listener)
                .installOn(inst);

public class ThriftClientManagerInterceptor {
    private static final Logger LOGGER = LoggerFactory.getLogger(ThriftClientManagerInterceptor.class);
    private static String SESSION_ID = "SessionId";

    @RuntimeType
    public static Object intercept(@This Object obj, @AllArguments Object[] allArguments, @Origin Method method,
                                   @SuperCall Callable<?> callable) {
        long start = System.currentTimeMillis();
        try {
            // can not go here.
            System.out.println("allArguments:" + allArguments.length + ";allArguments[0]:" + allArguments[0].getClass());
            FramedClientConnector connector = (FramedClientConnector) allArguments[0];
            connector.setNiftyClientHandler(channelPipeline -> channelPipeline.addLast("LogChannelHandler", new LogChannelHandler()));
            try {
                return callable.call();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } finally {
            LOGGER.info("ThriftClientManagerInterceptor----------------" + method + ": took " + (System.currentTimeMillis() - start) + "ms in premain test"
                    + "; method parameters:" + Arrays.toString(allArguments) + "; sessionId:" + MDC.get(SESSION_ID)
                    + "================");
        }
        return null;
    }
}`

**Comment by chrishyc** [comment]
all run log:


`[Byte Buddy] DISCOVERY com.facebook.swift.service.ThriftClientManager [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Loaded com.xiaomi.mifi.oversea.apm.interceptor.ThriftClientManagerInterceptor from file:/home/work/bin/apm-zander/my-agent.jar]
[Byte Buddy] ERROR com.facebook.swift.service.ThriftClientManager [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] COMPLETE com.facebook.swift.service.ThriftClientManager [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Loaded com.facebook.swift.service.ThriftClientManager from file:/home/work/bin/oversea-admin-api/webapp/WEB-INF/lib/swift-service-0.15.0-mdf1.0.17.jar]
[Byte Buddy] DISCOVERY com.facebook.swift.service.ThriftClientManager$1 [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] IGNORE com.facebook.swift.service.ThriftClientManager$1 [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] COMPLETE com.facebook.swift.service.ThriftClientManager$1 [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Loaded com.facebook.swift.service.ThriftClientManager$1 from file:/home/work/bin/oversea-admin-api/webapp/WEB-INF/lib/swift-service-0.15.0-mdf1.0.17.jar]
[Byte Buddy] DISCOVERY com.facebook.swift.service.ThriftClientManager$2 [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] IGNORE com.facebook.swift.service.ThriftClientManager$2 [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false][Loaded java.util.concurrent.TransferQueue from /home/work/bin/oversea-admin-api/jdk1.8.0_202/jre/lib/rt.jar]
[Byte Buddy] COMPLETE com.facebook.swift.service.ThriftClientManager$2 [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Loaded com.facebook.swift.service.ThriftClientManager$2 from file:/home/work/bin/oversea-admin-api/webapp/WEB-INF/lib/swift-service-0.15.0-mdf1.0.17.jar]
[Byte Buddy] DISCOVERY com.facebook.swift.service.ThriftClientManager$TypeAndName [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] IGNORE com.facebook.swift.service.ThriftClientManager$TypeAndName [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] COMPLETE com.facebook.swift.service.ThriftClientManager$TypeAndName [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Loaded com.facebook.swift.service.ThriftClientManager$TypeAndName from file:/home/work/bin/oversea-admin-api/webapp/WEB-INF/lib/swift-service-0.15.0-mdf1.0.17.jar]
[Byte Buddy] DISCOVERY com.facebook.swift.service.ThriftClientManager$ThriftClientMetadata [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] IGNORE com.facebook.swift.service.ThriftClientManager$ThriftClientMetadata [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] COMPLETE com.facebook.swift.service.ThriftClientManager$ThriftClientMetadata [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Loaded com.facebook.swift.service.ThriftClientManager$ThriftClientMetadata from file:/home/work/bin/oversea-admin-api/webapp/WEB-INF/lib/swift-service-0.15.0-mdf1.0.17.jar]
[Byte Buddy] DISCOVERY com.facebook.swift.service.ThriftClientManager$ThriftInvocationHandler [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] IGNORE com.facebook.swift.service.ThriftClientManager$ThriftInvocationHandler [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Byte Buddy] COMPLETE com.facebook.swift.service.ThriftClientManager$ThriftInvocationHandler [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]
[Loaded com.facebook.swift.service.ThriftClientManager$ThriftInvocationHandler from file:/home/work/bin/oversea-admin-api/webapp/WEB-INF/lib/swift-service-0.15.0-mdf1.0.17.jar]`

**Comment by chrishyc** [comment]
[Byte Buddy] ERROR com.facebook.swift.service.ThriftClientManager [EnvironmentClassLoader[web-app:production/webapp/default/ROOT], null, loaded=false]

I FIND  ERROR,BUT  nothing exception show

**Comment by chrishyc** [comment]
AgentBuilder.Listener#onError=com.facebook.swift.service.ThriftClientManager;null;java.lang.NoClassDefFoundError: org/jboss/netty/channel/ChannelHandler

**Comment by chrishyc** [comment]
[Loaded io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask$1 from file:/home/work/bin/oversea-admin-api/webapp/WEB-INF/lib/netty-transport-4.1.1.Final.jar]
java.lang.NoClassDefFoundError: org/jboss/netty/channel/ChannelHandler
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.channel.ChannelHandler

**Comment by chrishyc** [comment]
[Loaded io.netty.channel.ChannelHandler from file:/home/work/bin/oversea-admin-api/webapp/WEB-INF/lib/netty-transport-4.1.1.Final.jar]

**Comment by raphw** [comment]
As the error message suggests: in your remote enviornment, the class `org.jboss.netty.channel.ChannelHandler` cannot be accessed. Is it included in the deployment?

You can query the class loader of the instrumented type to see what classes it knows.

**Comment by chrishyc** [comment]
![image](https://user-images.githubusercontent.com/18613277/68558807-a2f6f600-0475-11ea-9058-86401261835a.png)
![image](https://user-images.githubusercontent.com/18613277/68558819-af7b4e80-0475-11ea-869c-5b24c2bde977.png)
![image](https://user-images.githubusercontent.com/18613277/68558825-b2763f00-0475-11ea-9ab0-e01f11ffa74a.png)
you are right, the classloader  can not find 
`org.jboss.netty.channel.ChannelHandler`.  but it  is really loaded. how to solve it?

**Comment by chrishyc** [comment]
i  have  found the real problem !  it is  related with   -javaagent  not about  bytebuddy.
-javaagent  always  use sun.misc.Launcher$AppClassLoader.

but  my   web application  classloader is EnvironmentClassLoader[web-app:production/webapp/default/ROOT],  the descendant of   javaagent.

i think this problem will be common  with all  spring web applicaiton.  i think it will be   helpful  for all
people  that  are using javaagent in spring web applicaiton.

![image](https://user-images.githubusercontent.com/18613277/68575898-026df980-04a8-11ea-96a9-614e40b0ccae.png)

**Comment by raphw** [comment]
Good you figured it out and thanks for documenting it for future readers.
