### ISSUE TITLE
How to combine multiple agents?

### ISSUE THREAD

**Issue by andreheringer** [raphw/byte-buddy#768]
I found a similar question here https://stackoverflow.com/questions/49189495/instrumenting-multiple-methods-within-same-class-with-bytebuddy

But what I want to know is: given multiple types, multiple ways to match those types, and multiple advices for decorations of said types, is there a way to combine all of that in a single agent?

Let's say I have a `.type(ElementMatchers.isAnnotatedWith(A.class))` and I transform it with an advice on there setters using `.isSetter()`.
And I also have a `.type(nameContains(packageDescriptor))` and I transform it with an advice on an specific method.

Right now I'm building two separate agents and installing both. Is it possible to merge them into a single agent? (Applying the correct transformations to each type)

**Comment by raphw** [comment]
It is possible, `Advice` is decoration and can be stacked. Since Byte Buddy 1.9.*, multiple type matchers in the `AgentBuilder` are also stacked unless you explicitly tell Byte Buddy to complete instrumentation after the first match in the agent builder DSL.

**Comment by andreheringer** [comment]
What do you mean with "can be stacked"? can you give me an example?
