### ISSUE TITLE
[Question] How to redefine function parameter without reassign the param

### ISSUE THREAD

**Issue by davidasync** [raphw/byte-buddy#769]
I have this piece of code

```
  companion object {
    @JvmStatic
    @Advice.OnMethodEnter(suppress = Throwable::class)
    @Throws(Exception::class)
    private fun enter(
      @Advice.Origin method: String
    , @Advice.Argument(value = 1, readOnly = false) callback: Callback<HttpResponse>
    ) {
      callback = CallbackInterceptor(callback)
    }
  }
```

I want to replace the callback with my interceptor with same interface
but because of I write my code in kotlin I can't reassign function parameter

is there any way to redefined function parameter ? without reassigning the param?

**Comment by raphw** [comment]
No, the whole advice concept is based on assignability of the parameters as it yields inlinable byte code. I'd generally recommend to write advice in Java, not only for this reason, javac yields the most compatible byte code for inlining.
