### ISSUE TITLE
Add an annotation to the type enclosed into an Optional<T>

### ISSUE THREAD

**Issue by MYDIH** [raphw/byte-buddy#771]
Hi,

Let's say that I want to generate an Optional of String, I would use this :

```java
TypeDescription.Generic description = TypeDescription.Generic.Builder
    .parameterizedType(Optional.class, String.class)
    .build()
```

In this scenario, How would I annotate the String type using ByteBuddy ?

Thanks a lot

**Comment by raphw** [comment]
You can would generate a generic type using this very same builder API which allows you to generate a raw type that can be annotated. Build these types and feed them as arguments back to another instance of your builder, e.g. the one you are naming in your example.

**Comment by MYDIH** [comment]
Does it work in 1.7.1 ?

**Comment by raphw** [comment]
Given [the javadoc](https://javadoc.io/doc/net.bytebuddy/byte-buddy/1.7.1/net/bytebuddy/description/type/TypeDescription.Generic.Builder.html), it should.

**Comment by MYDIH** [comment]
Thanks,

Was stuck between wrong assumptions and weird things in my codebase ... Sorry for the trouble.

**Comment by MYDIH** [comment]
Sorry, me again,

Very minimal example :
```java
new ByteBuddy()
                .subclass(Object.class)
                .name("Test")
                .defineField("testField", TypeDescription.Generic.Builder
                    .parameterizedType(TypeDescription.ForLoadedType.of(Optional.class),
                            TypeDescription.Generic.Builder.rawType(String.class)
                                    .annotate(AnnotationDescription.Builder.ofType(NotNull.class).build())
                                    .build())
                        .build())
                .make()
                .toJar(new File("test.jar"));
```

And no annotation on String into optional, am I missing something here ?

**Comment by raphw** [comment]
Are you sure? I tried with:

```java
@Target(ElementType.TYPE_USE)
public @interface Email {}
```

and receive:

>   // access flags 0x0
>   // signature Ljava/util/Optional<Ljava/lang/String;>;
>   // declaration: testField extends java.util.Optional<java.lang.String>
>   Ljava/util/Optional; testField
>   @Lnet/bytebuddy/Foo$Email;() : FIELD, 0; // invisible

for the byte code, the annotation seems to be there fore me.

**Comment by MYDIH** [comment]
Hey,

I'm not really confident in my tests, as you can see, I'm not in my element right now. For confirming If the annotation was there or not, I used IDEA integrated decompiler. Maybe I shouldn't, let me know. Moreover, I'm using this [annotation](https://github.com/eclipse-ee4j/beanvalidation-api/blob/master/src/main/java/javax/validation/constraints/Email.java), which should be used to do validation. Using the code I posted above, the validation do not find the annotation either.

Thanks for taking the time

**Comment by MYDIH** [comment]
Ok my bad, my codebase is interfering again, the validator correctly detect the violation in my minimal example, Closing for good.
