### ISSUE TITLE
Matcher for "inherited" method annotations

### ISSUE THREAD

**Issue by tylerbenson** [raphw/byte-buddy#772]
I am trying to figure out how to implement a method matcher like `isAnnotatedWith` but with the semantics of `inheritsAnnotation`.

I realize this would be a relatively costly matcher due to java not providing this info directly and the need to navigate the class hierarchy, but I was hoping that perhaps I was missing something.

Is this implemented somewhere?  If not, any suggestions for how I could implement it?

Context:  I'm trying to match methods based on [jax-rs annotation inheritance](https://download.oracle.com/javaee-archive/jax-rs-spec.java.net/jsr339-experts/att-3593/spec.pdf).

Thanks!

**Comment by raphw** [comment]
I'd just implement my own `ElementMatcher` for a `TypeDescription` where I traverse the super type hierarchy in the manner you find it meaningful. It's not very well-defined what method overrides which one due to the possibility of multiple overrides by interfaces being implemented.

Fortunately for you, Byte Buddy implicitly resolves generic types when you navigate the hierarchy, you do not have to resolve any type variables yourself, this is why this should be really easy to do.

**Comment by tylerbenson** [comment]
Here is my attempt. Does this look reasonable?

https://github.com/DataDog/dd-trace-java/pull/1098/files#diff-4ff29e1382175118ee5412d3db9285f5

**Comment by raphw** [comment]
Yes, small code feedback but looks good otherwise.

**Comment by tylerbenson** [comment]
@raphw what was the feedback?  I didn't see comments anywhere.

**Comment by raphw** [comment]
I added them to your pull request.

**Comment by tylerbenson** [comment]
Perhaps you didn't save/submit them?  I don't see anything from you.

**Comment by raphw** [comment]
They are inline. Did you ctrl+f "raphw" on the page?

**Comment by tylerbenson** [comment]
I did... I can't find it anywhere.

**Comment by raphw** [comment]
It's basically just performance advise. Don't chain filter and iterations as it will allocate. And matchers are executed a lot. Use

and(matcher()).isEmpty()

to avoid the intermediate materialization.

**Comment by tylerbenson** [comment]
Sorry,  I see the problem, but I'm not sure I follow your suggested solution.

```java
       for (final MethodDescription methodDescription :
          declaringType.getDeclaredMethods().filter(signatureMatcher)) {
          if (matcher.matches(methodDescription)) {
            return true;
          }
        }
```

How do I optimize that?

**Comment by tylerbenson** [comment]
@raphw sorry for not understanding, but any further clarification you could offer on your suggested change?

**Comment by raphw** [comment]
No problem. I meant that you should not both filter and iterate as you do extra work. Rather:

```java
for (final MethodDescription methodDescription :   declaringType.getDeclaredMethods()) {
  if (signatureMatcher.matches(methodDescription) && matcher.matches(methodDescription)) {
    return true;
  }
}
```

This way you do not resolve the entire list against the signature unneccessarily if you have an early match.

**Comment by tylerbenson** [comment]
ah, ok that makes sense.  thanks for your help!
