### ISSUE TITLE
Intercept method with different parameters

### ISSUE THREAD

**Issue by pippoflow** [raphw/byte-buddy#773]
I'm trying to intercept `close()`(an implementation of `java.io.Closeable#close`)  in my class. I defined an interceptor as this:
```
public class DemoCloseHandler implements Handler {
    @Override
    public void handle(@SuperCall Callable<?> zuper, @This Object value) throws Exception {
        // close logic
    }
}
```
however it throws the "Cannot resolve ambiguous delegation" exception. I was stepping through the code and I noticed the candidates for binding are methods in the `Object` class (that would have a bunch of methods with similar signatures, no wonder ambiguity happens), and the method defined in my interceptor wasn't even considered. I understand this is due to different parameters.

Is there a work-around to this? Thanks!

**Comment by raphw** [comment]
It looks good to me. Did you import the right annotations? Maybe, if you use a `Runnable` type for the `@SuperCall` proxy, it works since close returns void.
