### ISSUE TITLE
Can bytebuddy dynamically add an AgentBuilder after the agent has started successfully?

### ISSUE THREAD

**Issue by code98** [raphw/byte-buddy#774]
Can bytebuddy dynamically add an AgentBuilder after the agent has started successfully?

**Comment by raphw** [comment]
Of course, an agent can be installed at any time, given you have an instance of `Instrumentation`. Also look into *byte-buddy-agent* for retrieving such an agent and how to install an agent on a different VM.

**Comment by code98** [comment]
Hello, is there an example code?

**Comment by code98** [comment]
![image](https://user-images.githubusercontent.com/10418235/69175604-03a1c500-0b3f-11ea-8784-d762c6e6667e.png)
For example: I want to intercept an A method. When the A method is executed, use Bytebuddy's AgentBuilder to intercept another B method.

**Comment by raphw** [comment]
You should always instrument both methods to begin with and then rather decide any subsequent logic within your advice.

If you search around the Internet, there are plenty examples on how to write a simple agent with Byte Buddy. Using `Advice` is likely the right approach. Just apply it from an agent builder and install it using *byte-buddy-agent*.
