### ISSUE TITLE
MethodDelegation failed to run

### ISSUE THREAD

**Issue by code98** [raphw/byte-buddy#775]
I deleted the parameters of line 158 and it can run successfully. Adding this parameter program fails. The error is as follows:

![image](https://user-images.githubusercontent.com/10418235/69214738-accdd700-0ba2-11ea-86d9-5ebd1e5b369f.png)

![image](https://user-images.githubusercontent.com/10418235/69214714-a2134200-0ba2-11ea-8b94-48fa630fec79.png)

![image](https://user-images.githubusercontent.com/10418235/69214880-1cdc5d00-0ba3-11ea-83e9-8b76add94b05.png)

**Comment by raphw** [comment]
I would assume that you are not overriding a method that is declared as an interface default method and that Byte Buddy rejects it for that. Did you mean `@SuperCall`?

**Comment by code98** [comment]
I want to use the `@DefaultCall` annotation, Modify the method using `redefine`.Unable to run successfully

**Comment by raphw** [comment]
How does you class `c` look like and what interfaces does it implement? Ideally, you would produce a runnable reproduction.

**Comment by code98** [comment]
![image](https://user-images.githubusercontent.com/10418235/69254021-846cc980-0bf0-11ea-846c-f13a4fdde499.png)

Hi, this is the implementation of my class

**Comment by raphw** [comment]
This class does not implement any Java 8 default methods as it does not implement an interface. As I suggested, you probably look for `@SuperCall`.
