### ISSUE TITLE
Can I get the Instrumentation object through ByteBuddyAgent.install() in a normal program

### ISSUE THREAD

**Issue by code98** [raphw/byte-buddy#776]
Do not use --javaagent to start the agent program.
Can I get the Instrumentation object through `ByteBuddyAgent.install()` in a normal program, and intercept other classes?

![image](https://user-images.githubusercontent.com/10418235/69324891-3bfeeb80-0c84-11ea-8a4a-057c302c2d9f.png)

**Comment by raphw** [comment]
Yes, it works as it would normally. However, you might need to use retransformation if a class is already loaded.

**Comment by code98** [comment]
![image](https://user-images.githubusercontent.com/10418235/69355094-31f8df00-0cbc-11ea-933d-eabd5c555705.png)

Hi, Mr. Raphw, am I writing the code correctly? It doesn't work here for me

**Comment by raphw** [comment]
You probably want to set the `.disableClassFormatChanges()` option, too. Register a listener to see if there are any errors.

**Comment by code98** [comment]
thank! Registered a listener found an error, the error message is in the picture, how should this be resolved? Thank you!

![image](https://user-images.githubusercontent.com/10418235/69394747-e5db8800-0d17-11ea-9cd2-c820cd5ca32b.png)

![image](https://user-images.githubusercontent.com/10418235/69394774-f0961d00-0d17-11ea-8c64-17d222e49790.png)

**Comment by raphw** [comment]
Did you include your advice class in your project? It seems to be missing.

**Comment by code98** [comment]
I am going to develop an agent program. The process is to create an AOP for method A. If method A is called, then create an AOP for method B. All code is in the agent program, running with --javaagent.

The current situation is that after the program is started, method A can be intercepted. When running 'Method B to create an AOP' code, the error 'Could not locate class file for XXXXX'.

All classes are in the agent project, including advice class.

**Comment by raphw** [comment]
It's hard to tell for me what is going wrong there. Byte Buddy queries a class loader eventually, to get hold of the class file. For some reason, your class loader does not seem to yield that class file. You can set a break point in the `ClassFileLocator.ForClassLoader` method that looks up the method and see if the class file is indeed not available and why.

Is there any special class loader in use?

Generally, I'd recommend you to instrument both methods in one go. Instrumentation is a rather expensive operation and you ideally group it up.
