### ISSUE TITLE
Graal support - reflection and runtime loading

### ISSUE THREAD

**Issue by raphw** [raphw/byte-buddy#777]
Add support for running Byte Buddy on Graal native image by offering a runtime mode where generated classes are cached in a location and retreived in a different runtime mode such that no runtime code generation needs to take place.

The final API should ideally not require any changes to make it automatically applicable for any Byte Buddy user, direct or indirect.

Also, files for required reflection should be added as a convenience to support the runtime.

**Comment by webfolderio** [comment]
It's impossible to support GraalVM. bytebuddy do many magic behind the reflection support.

C++ is older than Java but it still doesn't have such a feature. Why do we need to use reflection? Why do we need magic libraries? Java developers obsessed with all kinds of reflection libraries. Best solution is stay away from these kind of libraries. Reflection is the worst feature of Java. JDK developers know this and they try to minimize and block reflection usage with JPMS.

You might ask why we shouldn't use reflection?It's hard to debug, hard to read and hard to understand code.

**Comment by gruenich** [comment]
Probably the target milestone is no longer valid. Do you mind changing it or removing it altogether?

**Comment by raphw** [comment]
I abuse the field to note the report version. Sorry for the confusion.

**Comment by dthommes** [comment]
Hi Rafael,

I was also looking for a similar solution, as we are having a lot of Mockito tests that we are trying to run with Graal's new [JUnit native support](https://medium.com/graalvm/gradle-and-maven-plugins-for-native-image-with-initial-junit-testing-support-dde00a8caf0b). Mockito uses ByteBuddy to generate classes at runtime. So, I found this issue here.

Investigating further, I saw that dynamic class loading is a PR in the Graal project that has recently been merged:

https://github.com/oracle/graal/pull/2442

So maybe, ByteBuddy can leverage the upcoming functionality of Graal to realize this feature. What do you think?

**Comment by raphw** [comment]
Interesting. This would require that the default naming strategy is deterministic what is certainly possible, but it would likely also require reflection to work but this should be picked up by the agent. I will certainly look into this!

**Comment by raphw** [comment]
Byte Buddy can now kind of work with this, as long as class names are deterministic. There are still some rough edges but we are moving forward, at least!

**Comment by mosche** [comment]
@raphw Pretty awesome to see this working out of the box if collecting [predefined classes](https://www.graalvm.org/22.1/reference-manual/native-image/ExperimentalAgentOptions/#support-for-predefined-classes) using an agent run 🎉 

Though, I noticed predefined classes are not collected if the dynamic type is loaded using `ClassLoadingStrategy.UsingLookup.of(MethodHandles$Lookup)`. Is there any way to get this to work or continue using the old INJECTION strategy on Java 11 with the GraalVM agent?

**Comment by raphw** [comment]
This would be a bug in Graal if so. Byte Buddy only adjiusts its default class naming strategy to work with the Graal agent out of the box. It's Graal that is responsible of collecting class files.

**Comment by mosche** [comment]
Thanks @raphw! In deed, classes injected into the system class loader are skipped (https://github.com/oracle/graal/issues/4248). Unfortunately, that's what will typically happen when defining a class using a lookup :/
