### ISSUE TITLE
@Advice.local with constructor instrumentation seems to be not working

### ISSUE THREAD

**Issue by mjok** [raphw/byte-buddy#779]
Hi, I am getting ```Exception in thread "main" java.lang.VerifyError: Bad local variable type``` if I'am using  ```@Advice.Local("name")``` in ```@Advice.OnMethodEnter``` method.

more details:
```
Exception in thread "main" java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    lt/slabs/com/jkoolcloud/remora/JustATest2.<init>()V @50: aload_1
  Reason:
    Type top (current frame, locals[1]) is not assignable to reference type
  Current Frame:
    bci: @50
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { }
  Bytecode:
    0x0000000: 014c 0941 b200 3e12 40b6 0046 b200 0212
    0x0000010: 40b6 0004 2bc7 001d bb00 4859 123a b700
    0x0000020: 4b4c b200 0212 4db6 0004 b200 3e12 4db6
    0x0000030: 0046 2bb2 0051 0101 b200 5599 0009 b200
    0x0000040: 3ea7 0004 01b8 005b 41a7 0005 3a04 a700
    0x0000050: 032a b700 01b2 0002 1203 b600 04b1     
  Exception Handler Table:
    bci [4, 73] => handler: 76
  Stackmap Table:
    same_frame(@50)
    full_frame(@68,{UninitializedThis},{Object[#72],Object[#87],Null,Null})
    full_frame(@69,{UninitializedThis},{Object[#72],Object[#87],Null,Null,Object[#66]})
    same_locals_1_stack_item_frame(@76,Object[#56])
    same_frame(@78)
    same_frame(@81)

	at lt.slabs.com.jkoolcloud.remora.RemoraTest2.main(RemoraTest2.java:34)
```

**Comment by raphw** [comment]
Could you provide further details? Neither reading or writing seems to break it for me:

```java
public class Foo {
    public static void main(String[] args) throws Exception {
        Advice advice = Advice.to(Foo.class);
        new ByteBuddy()
                .subclass(Object.class)
                .visit(advice.on(isConstructor()))
                .make()
                .load(null)
                .getLoaded()
                .getConstructor()
                .newInstance();
    }

    @Advice.OnMethodEnter
    public static void enter(@Advice.Local("name") String x) {
        x = "abc";
        String y = x;
    }
}
```

**Comment by mjok** [comment]
Ok, that was not actual problem I thought, but I did "broke" your sample to reproduce the problem:

```
    public static void main(String[] args) throws Exception {
        Advice advice = Advice.to(scratch.class);
        new ByteBuddy()
                .subclass(Object.class)
                .visit(advice.on(isConstructor()))
                .make()
                .load(null)
                .getLoaded()
                .getConstructor()
                .newInstance();
        Object o = new Object();
    }

    @Advice.OnMethodEnter
    public static void enter(@Advice.Local("name") String x) {
        if (x == null) {
            x = "abc";
        }
        String y = x;
    }
```

**Comment by raphw** [comment]
I understand now. Byte Buddy does not currently expect that advice declares a local variable only in the enter advice and does not inject a frame after the declaration of the local variables. In the same way, it is not currently possible to only declare a local variable only in the exit advice but there this problem is encountered and an exception is thrown.

I will fix the problem for now by also throwing an exception in your case but the local variables setting needs some general fix up at some point, this will become possible in the future.

For now, if you only declare a local variable in the enter advice, simply declare it in the method body:

```
@Advice.OnMethodEnter
public static void enter() {
  String x = null;
  if (x == null) {
    x = "abc";
  }
  String y = x;
}
```

**Comment by mjok** [comment]
I am using this same local variable on ```@Advice.OnMethodEnter``` and  ```@Advice.OnMethodExit```
in the ```@Advice```. I have just used your sample to show the problem in possible shortest code.

I am not expecting ```@Advice.Local``` to be set in run time. I am using ```null``` check in my  ```@Advice``` only for a Unit ```@Test``` purposes. And it actually works perfect if the instrumented method is not constructor. 

```java
public class Foo {
    public static void main(String[] args) throws Exception {
        Advice advice = Advice.to(Foo.class);
        new ByteBuddy()
                .subclass(Object.class)
                .visit(advice.on(isConstructor()))
                .make()
                .load(null)
                .getLoaded()
                .getConstructor()
                .newInstance();
        Object o = new Object();
    }

    @Advice.OnMethodEnter
    public static void enter(@Advice.Local("name") String x) {
        if (x == null) {
            x = "abc";
        }
        String y = x;
    }

    @Advice.OnMethodExit
    public static void exit(@Advice.Local("name") String x) {
            x = "def";
    }
}
```

```java
public class FooTest {
    public interceptorTest() {
        String testCase = "hij";
        Foo.enter(testCase);
        assertEquals("abc", testCase);
        Foo.exit(testCase);
        assertEquals("def", testCase);
    }
```

**Comment by raphw** [comment]
I just ran your example with the latest version and get a verifier error without the exit advice but with it, everything works out fine.

**Comment by mjok** [comment]
My bad, I have assumed it's the same as I have coded. Actually the sample is working, no verify error in my environment either, just I had missing the ```@Advice.OnMethodExit``` annotation in my code.

**Comment by raphw** [comment]
I fixed this on master now to throw an exception and will make it part of the next release. I still plan to support local-annotated variables in the future, simply to make the use more comfortable in cases where exit advice is optional.
