### ISSUE TITLE
Calling getters from DynamicType poxy

### ISSUE THREAD

**Issue by andreheringer** [raphw/byte-buddy#786]
Supose I've subclassed a type using bytebuddy and added a new propertiy to it using ```.defineProperty(name, type)``` how should I get/set the value from such property? Can bytebuddy let me call and ```subClassInstance.getProperty()```? Or I would get a compilation error?

**Comment by raphw** [comment]
That depends. The byte code changes are applied but will not be visible within the same project. Do you want to access the fields in an interceptor?

**Comment by andreheringer** [comment]
I wish to access the fields in the same project. I believe it's not possible because the compiler needs to know beforehand that the method is declared by the type at compilation time.

If I would do something like this I would need to use some reflection shenanigans. Like a ```.get()``` that access all class fields with reflection.

How would the access in an interceptor would look like?

**Comment by raphw** [comment]
From method delegation or advice, you can use for example `@FieldValue` or `@Advice.FieldValue` to read a fields value by the fields name, also if the property was generated dynamically.

**Comment by raphw** [comment]
If you have further questions, please reopen.
