### ISSUE TITLE
can not intercept method when use InitBinder

### ISSUE THREAD

**Issue by geektcp** [raphw/byte-buddy#787]
byte-buddy can not intercept method when I use InitBinder:

look at this , and the intercept method(static void enter(@Advice.Origin Method method) throws Exception) do nothing? why?  How to resolve it ？

================================
@RestController
@RequestMapping("/")
public class TestController {

    @InitBinder
    public void initBinder(WebDataBinder dataBinder) {
        dataBinder.registerCustomEditor(
                PropertyEditorSupport.class, new PropertyEditorSupport() {});
    }
    
    @GetMapping("/test")
    public String test() {
        log.info("test api");
        try{
            get();
            Thread.sleep(200);
        }catch (Exception e){
            log.error(e.getMessage());
        }
        return "success";
    }
}

    @Advice.OnMethodEnter
    static void enter(@Advice.Origin Method method) throws Exception {
        if(method.getName().equals("getTemplateDTO")){
            Annotation[] declaredAnnotations = method.getDeclaredAnnotations();
            Annotation[] annotations = method.getAnnotations();
            System.out.println("this method will  not be excuted");
            System.out.println("annotations" + Arrays.toString(annotations));
        }
    }

**Comment by raphw** [comment]
How does your agent builder look like?

**Comment by raphw** [comment]
Please reopen if you still struggle with this.

**Comment by geektcp** [comment]
> Please reopen if you still struggle with this.

Hei,raphw!  I think it is really a question, I am sure it cannot intercept when I use the version bytebuddy-1.10.4
Buy when  the @InitBinder code stay in  a single class and the api code stay in annother class, It will be no happed ,means intercepted the method!

**Comment by raphw** [comment]
Have you tried registering a `AgentBuilder.Listener` to see if there is an error or if the method is explicitly ignored? If it works sometimes, it mighr depend on the class already being loaded during your agent's application.
