### ISSUE TITLE
Outdated example on webpage concerning new AgentBuilder.Default().rebase...

### ISSUE THREAD

**Issue by Petikoch** [raphw/byte-buddy#79]
Hi @raphw,
today, I tried to write a simple agent, which logs the method calls with it's args to sysout.
I started with byte-buddy 0.7.1. 
The code example on http://bytebuddy.net/#/tutorial under "Creating Java agents" seems to be based on 0.6.*. There is no rebase() method anymore in AgentBuilder.Default() 0.7.1. 

Could you update the documentation to the current byte-buddy version?

Thanks & best regards from Lucerne / Switzerland,
Peti

**Comment by raphw** [comment]
Thank you for the hint. I fixed the documentation. The `rebase` method was renamed to `type`.

**Comment by Petikoch** [comment]
Thanks a lot @raphw !
