### ISSUE TITLE
Clarification needed on AgentBuilder.Transformer.ForAdvice::include()

### ISSUE THREAD

**Issue by prydin** [raphw/byte-buddy#795]
I'm trying to capture a call coming in through a servlet engine. Here's my code:

```public class ServletIngressHandler {
    
    
    @Advice.OnMethodEnter
    public static void enter(final @Advice.AllArguments Object[] args) {
       GenericIngressHandler.enter(args[0], "getHeader");
    }

    @Advice.OnMethodExit
    public static void exit() {
        GenericIngressHandler.exit();
    }

    public static AgentBuilder buildAgent(AgentBuilder b) {
        return b.type(named("javax.servlet.http.HttpServlet"))
                .transform(
                        new AgentBuilder.Transformer.ForAdvice()
                            .include(ServletIngressHandler.class.getClassLoader())
                            .advice(new Matchers.WildcardMethodMatcher(
                        "service(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)"),
                                ServletIngressHandler.class.getName()));
        
    }
}
```

It fails when it's trying to load the GenericIngressHandler when executed through the Open Liberty appserver. It seems that it has some custom classloader that doesn't see my code. 

So I added ```include(ServletIngressHandler.class.getClassLoader())``` to the definition of the transformer thinking that it would somehow insert the classloader of my package into the mix. However, it still can't see the class. Maybe I'm using ```include()``` wrong? Some clarification in the documentation would be great!

**Comment by prydin** [comment]
I managed to do what I needed using this hack, but it feels kind of dirty. Is this what include() is supposed to help me with or am I completely mistaken?

```
public static void premain(String agentArgs, Instrumentation inst) throws Exception {
        ServletIngressHandler.setHandler(new GenericIngressHandler());
        instrument(JettyIngressHandler.buildAgent(newBuilder()), inst);
        instrument(ServletIngressHandler.buildAgent(newBuilder()), inst);
        instrument(SpringEgressHandler.buildAgent(newBuilder()), inst);
        instrument(ApacheEgressHandler.buildAgent(newBuilder()), inst);
        instrument(JaxRsEgressHandler.buildAgent(newBuilder()), inst);

        // Some classloaders don't look at the system classloader. Hack them to do that!
        newBuilder().type(named("org.eclipse.osgi.internal.loader.BundleLoader"))
                .transform(new AgentBuilder.Transformer.ForAdvice()
                    .advice(named("findClass"), ClassLoaderEnhancer.class.getName())).installOn(inst);
    }

    private static class ClassLoaderEnhancer {
        @Advice.OnMethodExit(onThrowable = ClassNotFoundException.class)
        public static void exit(
                @Advice.Argument(0) String className,
                @Advice.Return(typing = Assigner.Typing.DYNAMIC, readOnly = false) @RuntimeType Object value,
                @Advice.Origin String origin,
                @Advice.Thrown(readOnly = false) Throwable thrown) throws Throwable {
            if(thrown != null) {
                if(className.startsWith("net.virtualviking.b3inject")) {
                    value = ClassLoader.getSystemClassLoader().loadClass(className);
                    thrown = null;
                } else {
                    throw thrown;
                }
            }
        }
    }
```

**Comment by raphw** [comment]
Any code referenced in your advice classes must be available to the class loader that is executing the advice. The *include* method only assures that Byte Buddy can see class files provided by class loaders while inlining the advice.

Normally, you add classes that you need to be universally visible to the bootstrap class loader. The `Instrumentation` interface provides a method for that.

**Comment by prydin** [comment]
The problem is that there doesn't seem to be a way to determine the name of the instrumentation JAR file, so it's kind of hard to use the methods on ```Instrumentation```. Anyway, my ugly hack works fine, so that will do it for now.

**Comment by raphw** [comment]
Normally, you would package those classes in a seperate jar and attach it as a resource to your agent. Then, at runtime, you read it via `getResourceAsStream`, and store this jar on the local file system and reference it using `Instrumentation`.

**Comment by prydin** [comment]
Aaaah, **THAT'S** how you do it! Thanks! I learned something useful today. BTW, this is what I'm working on. A simple little utility that inject B3-headers for Java programs running within an Istio Service mesh: https://github.com/prydin/b3inject

**Comment by raphw** [comment]
Good to hear, checked your doc and this approach should also allow you avoid - Xbootclassloader.
