### ISSUE TITLE
Intercept HttpURLConnection error

### ISSUE THREAD

**Issue by dengliming** [raphw/byte-buddy#797]
here is my code.
i try to inject bootstrap

```java
import net.bytebuddy.agent.ByteBuddyAgent;
import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.ClassFileLocator;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.dynamic.loading.ClassInjector;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.matcher.ElementMatchers;
import net.bytebuddy.utility.JavaModule;

import java.io.File;
import java.lang.instrument.Instrumentation;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.util.Collections;

public class BootstrapAgent {

    public static void main(String[] args) throws Exception {
        premain(null, ByteBuddyAgent.install());
        HttpURLConnection urlConnection = (HttpURLConnection) new URL("http://www.google.com").openConnection();
        System.out.println(urlConnection.getRequestMethod());
    }

    public static void premain(String arg, Instrumentation instrumentation) throws Exception {
        File temp = Files.createTempDirectory("tmp").toFile();
       ClassInjector.UsingInstrumentation.of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation)
                .inject(Collections.singletonMap(
                new TypeDescription.ForLoadedType(GeneralInterceptor.class),
                ClassFileLocator.ForClassLoader.read(GeneralInterceptor.class)));

        new AgentBuilder.Default()
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
                .with(new AgentBuilder.InjectionStrategy.UsingInstrumentation(instrumentation, temp))
                .type(ElementMatchers.nameEndsWith(".HttpURLConnection"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
                        return builder.method(ElementMatchers.named("getRequestMethod")).intercept(MethodDelegation.to(new GeneralInterceptor()));
                    }
                }).installOn(instrumentation);
    }

}

public class GeneralInterceptor {

    @RuntimeType
    public Object intercept(@AllArguments Object[] allArguments,
                            @Origin Method method, @SuperCall Callable<?> callable) throws Exception {
        // intercept any method of any signature
        System.out.println("===============================intercept");
        return callable.call();
    }
}```

MethodDelegation.to(GeneralInterceptor.class) it works
MethodDelegation.to(new GeneralInterceptor()) got this exception.
I want to know why? @raphw 

> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
> 	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
> 	at java.net.URL.openConnection(URL.java:979)
> 	at bytebuddy.BootstrapAgent.main(BootstrapAgent.java:29)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at java.net.HttpURLConnection.<clinit>(HttpURLConnection.java:313)
> 	... 4 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.bytebuddy.dynamic.Nexus.initialize(Nexus.java:137)
> 	... 9 more
> Caused by: java.lang.IllegalArgumentException: Can not set static bytebuddy.GeneralInterceptor field java.net.HttpURLConnection.delegate$1m4atp0 to bytebuddy.GeneralInterceptor
> 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
> 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
> 	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:81)
> 	at java.lang.reflect.Field.set(Field.java:764)
> 	at net.bytebuddy.implementation.LoadedTypeInitializer$ForStaticField.onLoad(LoadedTypeInitializer.java:129)
> 	at net.bytebuddy.implementation.LoadedTypeInitializer$Compound.onLoad(LoadedTypeInitializer.java:192)
> 	at net.bytebuddy.agent.builder.AgentBuilder$InitializationStrategy$SelfInjection$Dispatcher$InjectingInitializer.onLoad(AgentBuilder.java:3132)
> 	... 14 more

**Comment by raphw** [comment]
I think that the class for `GeneralInterceptor` exists twice, once in the system class loader and once in the boot loader. The class is loaded already in your method before it is injected, this is why the field cannot be set.

You would need to inject the class without loading it. Try using a `ClassFileTransformer` on the class loader where you only refer to the class using a string. Also, use a `TypePool` for creating a type description that you provide to the method delegation.

**Comment by dengliming** [comment]
> I think that the class for `GeneralInterceptor` exists twice, once in the system class loader and once in the boot loader. The class is loaded already in your method before it is injected, this is why the field cannot be set.
> 
> You would need to inject the class without loading it. Try using a `ClassFileTransformer` on the class loader where you only refer to the class using a string. Also, use a `TypePool` for creating a type description that you provide to the method delegation.

I've been using this lately, and I'm a little confused.Would you mind giving me a simple example and I'd really appreciate it.
All I want is to be able to inject into the system class like Thread or HttpURLConnection with custom instance class. Which is the same thing as above and I can instantiate it with parameters
 like “.intercept(MethodDelegation.to(new GeneralInterceptor(params))”

**Comment by raphw** [comment]
Here is a working example:

```java
public static void main(String[] args) throws Exception {
  premain(null, ByteBuddyAgent.install());
  doMain();
}

private static void doMain() throws Exception {
  HttpURLConnection urlConnection = (HttpURLConnection) new URL("http://www.google.com").openConnection();
  System.out.println(urlConnection.getRequestMethod());
}

public static void premain(String arg, Instrumentation instrumentation) throws Exception {
  String interceptor = "your.pkg.GeneralInterceptor";
  ClassFileLocator locator = ClassFileLocator.ForClassLoader.ofSystemLoader();
  TypePool pool = TypePool.Default.of(locator);
  final TypeDescription target = pool.describe(interceptor).resolve();

  File temp = Files.createTempDirectory("tmp").toFile();
  ClassInjector.UsingInstrumentation
    .of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation)
    .injectRaw(Collections.singletonMap(interceptor, locator.locate(interceptor).resolve()));

    new AgentBuilder.Default()
      .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
      .with(new AgentBuilder.InjectionStrategy.UsingUnsafe.OfFactory(ClassInjector.UsingUnsafe.Factory.resolve(instrumentation)))
      .type(ElementMatchers.nameEndsWith(".HttpURLConnection"))
      .transform(new AgentBuilder.Transformer() {
        @Override
        public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
          return builder.method(ElementMatchers.named("getRequestMethod")).intercept(MethodDelegation.to(target));
        }
      }).installOn(instrumentation);
  }
```

Note that I made the interception method static; this way it is not required to inject a field into the target class which might avoid future problems. If you need to add state in the interceptor, rather add a public static field to the `GeneralIntercpetor` and initialize that field after injection into the boot loader.

**Comment by dengliming** [comment]
so，I can't  initialize the field of GeneralIntercpetor by constructor like “new GeneralInterceptor(params)”?
the below code can put to custom Transformer instance？or it must be injected into the boot loader before.
`ClassInjector.UsingInstrumentation
    .of(temp, ClassInjector.UsingInstrumentation.Target.BOOTSTRAP, instrumentation)
    .injectRaw(Collections.singletonMap(interceptor, locator.locate(interceptor).resolve()));`

**Comment by raphw** [comment]
This is possible but it is a bit tricky as the Byte Buddy annotations live on the system loader while the intercepted type needs to be put on the boot loader that cannot see those annotations. I just added an API to supply a type definition rather than a loaded type but for now, it is only possible by eithr:

1. Loading your entire agent in the boot loader, you can add your jar to the manifest of the agent, for example.
2. You define a static field explicitly and add the agent instance explicitly. Change your interceptor like this to achieve this:

```java
builder
  .defineField("delegator", target, Ownership.STATIC, Visibility.PRIVATE)
  .initializer(new LoadedTypeInitializer() {
    @Override
    public void onLoad(Class<?> type) {
      try {
        Field field = type.getDeclaredField("delegator");
        field.setAccessible(true);
        field.set(null, Class.forName(interceptor, false, null).getConstructor().newInstance());
      } catch (Exception e) {
        throw new RuntimeException(e);
      }
    }

    @Override
    public boolean isAlive() {
      return true;
    }
  })
  .method(ElementMatchers.named("getRequestMethod"))
  .intercept(MethodDelegation.toField("delegator"));
```

I change the constructor visibility to `public for a next version, too.

**Comment by dengliming** [comment]
I got it，thank you so much.

**Comment by dengliming** [comment]
`.type(ElementMatchers.named("java.net.HttpURLConnection"))` not working, but getRequestMethod is exits in this class, and it should work, And `sun.net.www.protocol.http.HttpURLConnection` works. Why?

**Comment by raphw** [comment]
Difficult to say without further details, are you getting an exception or something?

**Comment by dengliming** [comment]
No exception,
Here is my code:
```
public static void main(String[] args) throws Exception {
        premain(null, ByteBuddyAgent.install());
        HttpURLConnection urlConnection = (HttpURLConnection) new URL("http://www.google.com").openConnection();
        System.out.println(urlConnection.getRequestMethod());
    }

    public static void premain(String arg, Instrumentation instrumentation) throws Exception {
        AgentClassLoader.initDefaultLoader();
        Map<String, byte[]> classTypeMap = new HashMap<>();
        BootstrapInstrument.inject(classTypeMap);
        ClassInjector.UsingUnsafe.Factory factory = ClassInjector.UsingUnsafe.Factory.resolve(instrumentation);
        factory.make(null, null).injectRaw(classTypeMap);

        new AgentBuilder.Default()
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
                .with(new AgentBuilder.InjectionStrategy.UsingUnsafe.OfFactory(factory))
                .type(ElementMatchers.named("java.net.HttpURLConnection"))
                //.type(ElementMatchers.nameEndsWith("Executor"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
                        return builder.method(any())
                                .intercept(MethodDelegation.withDefaultConfiguration()
                                        .to(BootstrapInstrument.forDelegateClass("com.example.core.InstanceInterceptor_delegator")));
                    }
                })
                //.transform(new AgentTransformer())
                //.with(AgentBuilder.Listener.StreamWriting.toSystemOut())
                .installOn(instrumentation);
    }
```

**Comment by raphw** [comment]
You have to match the class that declares a method, especially when overridden. Otherwise, you have to match `hasSuperType(named(...))`.

**Comment by goudai** [comment]
> This is possible but it is a bit tricky as the Byte Buddy annotations live on the system loader while the intercepted type needs to be put on the boot loader that cannot see those annotations. I just added an API to supply a type definition rather than a loaded type but for now, it is only possible by eithr:
> 
> 1. Loading your entire agent in the boot loader, you can add your jar to the manifest of the agent, for example.
> 2. You define a static field explicitly and add the agent instance explicitly. Change your interceptor like this to achieve this:
> 
> ```java
> builder
>   .defineField("delegator", target, Ownership.STATIC, Visibility.PRIVATE)
>   .initializer(new LoadedTypeInitializer() {
>     @Override
>     public void onLoad(Class<?> type) {
>       try {
>         Field field = type.getDeclaredField("delegator");
>         field.setAccessible(true);
>         field.set(null, Class.forName(interceptor, false, null).getConstructor().newInstance());
>       } catch (Exception e) {
>         throw new RuntimeException(e);
>       }
>     }
> 
>     @Override
>     public boolean isAlive() {
>       return true;
>     }
>   })
>   .method(ElementMatchers.named("getRequestMethod"))
>   .intercept(MethodDelegation.toField("delegator"));
> ```
> 
> I change the constructor visibility to `public for a next version, too.

If I want to intercept the constructor, how should I write it. For example, I want to intercept the constructor of `java.util.concurrent.ThreadPoolExecutor`.

**Comment by raphw** [comment]
You can intercept with .constructor, but rebaing won't work if the class is already loaded.

I would strongly advice you to use Advice for such approaches and rather inject your context in some other way. You can for example inject some form of carrier object into the bootstrap loader and then read an object from a static public field of this carrier object.

**Comment by goudai** [comment]
I don't want to use adivce. It cannot prevent function calls. Can you provide me with a demo for reference, such as intercepting the constructor of `java.util.concurrent.ThreadPoolExecutor`. Use intercept instead of advice mode.

**Comment by raphw** [comment]
For a constructor, this is not possible since you cannot guarantee that the class is not already loaded when your agent is triggered. Have a look at `ClassInjector` and add a class such as:

```java
public class MyDispatcher {
  public static MyDispatcher dispatcher;
  public void dispatch() { ... }
}
```

You can now load this dispatcher from your advice code and do similar things as with delegation, only that you avoid the problem that you were initially having.
