### ISSUE TITLE
mocking kotlin interface with extension method that has generic receiver or parameter fails when compiling with -java-parameters flag

### ISSUE THREAD

**Issue by kevin1e100** [raphw/byte-buddy#803]
Running the following Kotlin file compiled with `-java-parameters` fails with the exception shown below:

```
package mockito

import org.mockito.Mockito.mock

object MockitoMain {
  @JvmStatic
  fun main(args: Array<String>) {
    mock(WithExtensionMethod::class.java)
  }
}

interface WithExtensionMethod {
  fun GenericClass<*>.doSomething()
}

open class GenericClass<T>
```

Compiled and run (on JDK8) like so:
```
$ path/to/kotlinc_1.3.61/bin/kotlinc -d /tmp/mockito_repro.jar -cp mockito-1-10-19.jar:byte-buddy-1.9.12.jar MockitoMain.kt -jvm-target 1.8 -java-parameters
$ java -cp /tmp/mockito_repro.jar:mockito-1-10-19.jar:byte-buddy-1.9.12.jar:objenesis-3.0.1.jar:path/to/kotlinc_1.3.61/lib/kotlin-stdlib.jar mockito.MockitoMain
Exception in thread "main" org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface mockito.WithExtensionMethod.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
[...]
Underlying exception : java.lang.IllegalArgumentException: object is not an instance of declaring class
	at mockito.MockitoMain.main(MockitoMain.kt:8)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$ForTypeArgument.resolve(TypeDescription.java:3466)
[...]
org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:40)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:60)
	at org.mockito.Mockito.mock(Mockito.java:1288)
	at org.mockito.Mockito.mock(Mockito.java:1166)
	... 1 more
```

Omitting the `-java-parameters` flag from the kotlinc command shown above allows the example to terminate normally. This flag causes `MethodParameters` bytecode attributes to be emitted by the compiler, IIUC, which seems to include a "mandated" parameter for the interface's extension method:

```
$ javap -v -cp /tmp/mockito_repro.jar mockito.WithExtensionMethod
[...]
public interface mockito.WithExtensionMethod
  minor version: 0
  major version: 52
  flags: ACC_PUBLIC, ACC_INTERFACE, ACC_ABSTRACT
Constant pool:
[...]
{
  public abstract void doSomething(mockito.GenericClass<?>);
    descriptor: (Lmockito/GenericClass;)V
    flags: ACC_PUBLIC, ACC_ABSTRACT
    Signature: #7                           // (Lmockito/GenericClass<*>;)V
    RuntimeInvisibleParameterAnnotations:
      0:
        0: #9()
    MethodParameters:
      Name                           Flags
      $this$doSomething              mandated
}
SourceFile: "MockitoMain.kt"
[...]
```

**Comment by raphw** [comment]
I am slightly confused. Are you using Mockito 1.10.19 for this? Looking at your class path.

**Comment by TimvdLippe** [comment]
Google still uses the Mockito 1 API, but we are using the ByteBuddyMockmaker already. I expect Google to use the full Mockito 2 API in the first half of 2020.

**Comment by TimvdLippe** [comment]
We have confirmed the issue exists on Mockito 2 and 3 as well.

**Comment by raphw** [comment]
There is something funky with Kotlin's byte code in play with the reflection API. Normally, if a type is for example a parameterized type, when requesting the annotated for, you'd expect an instance of annotated parameterized type rather than, let's say, a wildcard annotated type.

I added guards to the resolver to check for the types to be consistent and to otherwise not resolve type annotations such that the example no longer fails. I pushed that to master but I'll try to find out what's wrong to report this as a bug.

**Comment by TimvdLippe** [comment]
Awesome work Rafael. Thank you very much for the quick resolution!

**Comment by raphw** [comment]
Your welcome. I planned a release for next week. You can build it yourself in the meantime if you are in a hurry.

**Comment by kevin1e100** [comment]
Please let me know/post here if you end up filing a bug.

I'm happy to help with filing a bug at https://youtrack.jetbrains.com/issues/KT, but I'd need help understanding what's wrong in the generated bytecode.

**Comment by raphw** [comment]
I start to think that it is a bug in the reflection API, even though the method does not guarantee a specific return type. I am just confused by the fact that I never encountered this with a javac compiled class. I am not sure it has anything to do with Kotlin, just the fact that the class file is unusual while also valid.

**Comment by kevin1e100** [comment]
"mandated" entries in MethodParameters are rare, and kotlinc-generated .class files look ok to me, but I'm unclear where exactly this flag is appropriate, based on what's written [here](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.24).  Either way it's weird that this flag would affect execution semantics.

**Comment by raphw** [comment]
I think that is where the problem lies, it's a one off error since the code that would check for type annotations on method parameters does not respect it. Therefore, when calling `getParameterTypes` on the Java reflection API, a different sort for a parameter is assumed as in the code for `getAnnotatedParameterTypes()` where the mandated flat is not considered.

It's pretty much a corner-case and I could not guarantee that Byte Buddy's type annotation processor would assign type annotations on their type path correctly for such method but I will try to build a simple reproducer (in generated code) soon and try to push a fix to OpenJDK.

**Comment by cushon** [comment]
JLS 13.1 has context on how `ACC_MANDATED` is used [1]. IIUC kotlinc is creating entries in `RuntimeVisibleParameterAnnotations` that correspond to mandated parameters, which javac does not do, but which is allowed by JVMS 4.7.18 [2]:

> a compiler may choose to create entries in [RuntimeVisibleParameterAnnotations] corresponding only to those parameter descriptors which represent explicitly declared parameters in source code

e.g. in the following example javac starts at offset 0 for the parameter annotation, even though isn't on the first explicit parameter and the descriptor and signature include an implicit mandated parameter:

```java
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.PARAMETER, ElementType.TYPE_USE})
@interface A {}

class T {
  class I {
    I(@A int x) {}
  }
}
```

```
  T$I(T, int);
    descriptor: (LT;I)V
    flags: (0x0000)
    Code:
      stack=2, locals=3, args_size=3
         0: aload_0
         1: aload_1
         2: putfield      #1                  // Field this$0:LT;
         5: aload_0
         6: invokespecial #7                  // Method java/lang/Object."<init>":()V
         9: return
      LineNumberTable:
        line 12: 0
    MethodParameters:
      Name                           Flags
      this$0                         final mandated
      x
    RuntimeVisibleTypeAnnotations:
      0: #19(): METHOD_FORMAL_PARAMETER, param_index=0
        A
    RuntimeVisibleParameterAnnotations:
      parameter 0:
        0: #19()
          A
```

I can imagine code in core reflection or JSR-269 making javac-centric assumptions there, I'd be interested in a minimal repro for the issue you're seeing.

[1] https://docs.oracle.com/javase/specs/jls/se11/html/jls-13.html#jls-13.1
[2] https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.7.18

**Comment by TimvdLippe** [comment]
@raphw Could we have a release for this fix? I would like to integrate it into our monorepository :smile: Thanks!

**Comment by raphw** [comment]
Trying to do a release right now. Java 6 builds broke since Maven Central disabled HTTP without S and TLS 1.0 is not supported. Worked around it now and should be ready to do it now.

**Comment by Fiouz** [comment]
> Please let me know/post here if you end up filing a bug.
> 
> I'm happy to help with filing a bug at https://youtrack.jetbrains.com/issues/KT

[KT-40857](https://youtrack.jetbrains.com/issue/KT-40857) shares similarities with the current issue:
* Kotlin compilation with `javaParameters=true`
* Extension function on Parameterized receiver
* Java reflection API

One JetBrains member [commented](https://youtrack.jetbrains.com/issue/KT-40857#focus=Comments-27-4645051.0-0):
> Looks like the problem is caused by the fact that we're generating the receiver parameter with `ACC_MANDATED` for some reason, which I think we shouldn't do.
