### ISSUE TITLE
Advisors on reactive methods

### ISSUE THREAD

**Issue by PeibGrylls** [raphw/byte-buddy#806]
Hi @raphw,

I have a question/problem related to reactive programming:

Is it possible to set advisors on reactive methods and obtain real data about its execution (duration, return data, ...)?

**Comment by raphw** [comment]
Byte Buddy does not really care about the type of application that you are instrumenting. As long as you can locate type and method to instrument, you can install your own hooks. Have a look into the `AgentBuilder` API and Java agents for it.

**Comment by PeibGrylls** [comment]
What I mean is, if you add a regular Advice.to on a reactive method, you are going to obtain info about the creation of the "promise" of a result: ~0ms execution time, and no real @Adive.Result.

**Comment by raphw** [comment]
You would need to trace the life cycle of a reactive component yourself. Byte Buddy is a code instrumentation tool, it is not opinionated towards a specific programming style.

**Comment by PeibGrylls** [comment]
Question answered then, thank you very much ;)
