### ISSUE TITLE
@OnMethodExit to set return value for primitive type.

### ISSUE THREAD

**Issue by kendang007** [raphw/byte-buddy#807]
First thank you for the amazing work.
I am play around the byte buddy and try to intercept like java.io.ObjectInputStream readBoolean function using the following agent:

```java
  new AgentBuilder.Default()
                .with(RedefinitionStrategy.RETRANSFORMATION)
                .with(InitializationStrategy.NoOp.INSTANCE)
                .with(TypeStrategy.Default.REDEFINE)
                .ignore(new AgentBuilder.RawMatcher.ForElementMatchers(nameStartsWith("net.bytebuddy.").or(isSynthetic()), any(), any()))
                .with(new Listener.Filtering(
                        new StringMatcher("java.io.ObjectInputStream", StringMatcher.Mode.EQUALS_FULLY),
                        Listener.StreamWriting.toSystemOut()))
                .type(named("java.io.ObjectInputStream"))  //class
                .transform((builder, type, classLoader, module) ->
                        builder.visit(Advice.to(INTERCEPTOR_CLASS).on(named("readBoolean")))
                )
                .installOn(inst);
```

INTERCEPTOR_CLASS is as below:

```java
@Advice.OnMethodExit
    public static void exit(@Advice.Return(readOnly = false) boolean returned) throws Exception {
        System.out.println("in exit");
        returned = true;
    }
```

But it seems returned is not as true when execute readBoolean. also it doesn't work if I change returned to Object. Any suggestion?

**Comment by raphw** [comment]
As for setting it to `Object`, you would need to set the assigner typing to `DYNAMIC` where it is static by default. Byte Buddy will then insert a cast to the required type.

As from your code, it should work. Can you see the print out? What happens if you attach a debugger to see what the method returns? Also, try `RETRANSFORM` instead of `REDEFINE`, it's normally what you want to do.

**Comment by kendang007** [comment]
Thank you for replying me. 

according to your reply, I changed my code to:

    @Advice.OnMethodExit
    public static void exit(@Advice.Return(readOnly = false, typing = Assigner.Typing.DYNAMIC) Object returned) throws Exception {
        System.out.println("in exit");
        returned = true;
    }

However the return from readBoolean is not true.

By the way you advice to change REDEFINE to RETRANSFORM . However for TypeStrategy.Default, there is no RETRANSFORM, only REDEFINE  and REBASE.

**Comment by raphw** [comment]
Is the print statement executed when you run your code?

**Comment by kendang007** [comment]
Yes, It's executed. However I suspect the parameter is passed by value. After running @Advice.OnMethodExit, it will be back to its' original value. Is that possible?

**Comment by raphw** [comment]
That should really not happen, the return value is overridden before it is popped off the stack. Are you really sure? Could you run your code with `-Dnet.bytebuddy.dump=/some/folder` to extract the class files?
