### ISSUE TITLE
Documentation for inner class name matching is wrong

### ISSUE THREAD

**Issue by zeitlinger** [raphw/byte-buddy#808]
Contrary to the [documentation](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/matcher/NameMatcher.java#L25) inner classes are matched by `$` instead of `.`.

So either the documentation or the implementation should be fixed.

**Comment by raphw** [comment]
The matching is supposed to follow the source code form, the intention was to match classes by that but I will probably retain the current behavior to provide backwards compatibility. I'll fix the documentation, thanks for pointing it out!

**Comment by raphw** [comment]
Fixed on master.
