### ISSUE TITLE
Error on attachement: group owner of java pid file

### ISSUE THREAD

**Issue by akram** [raphw/byte-buddy#809]
Hi there, thanks for your great work with byte-buddy.
I am a maintainer on Jenkins image for OpenShift, and a user raised the following issue: https://github.com/openshift/jenkins/issues/1018

It seems that byte-buddy complains when the java_<pid>.pid file is not owned by the primary group of the user running the process.
In our case, we are running Jenkins in OpenShift which gives arbitrary user to the user running the container and its primary group will be 0, but the secondary one will be $(id -u) .

Would it make sense to check that the pid file is owned by one of the group of the user owning the process not only its primary group ?

cc @jelmew

**Comment by raphw** [comment]
Hi, Byte Buddy is only using the JVM's attach API that is provided by HotSpot in your code: http://hg.openjdk.java.net/jdk/jdk/file/932418820c80/src/jdk.attach/linux/native/libattach/VirtualMachineImpl.c#l167

There is nothing Byte Buddy can do to prevent this. However, Byte Buddy implements its own virtual machine API which does not have this restriction. It requires adding a version of JNA to the class path an you also would need to explicitly enable this. A lot of users of Byte Buddy are however not using the custom implementation but rather the one the JVM bundles as it obviously is more stable.
