### ISSUE TITLE
Null Pointer Exception in ETAPLog4jFilter

### ISSUE THREAD

**Issue by mikepoz59** [raphw/byte-buddy#811]
Hello!

So my organization recently updated Appium to latest, which has byte-buddy 1.8.15, which has a dependency on something called `com.etap.core`.   I'd reach out to whoever created that, unfortunately I get zero results anywhere for that, so I'm reaching out to you.

Here's the issue in ETAPLog4jFilter.class of com.etap.core:
```
    public int decide(LoggingEvent event) {
        this.readConfig();
        if (this.properties != null && this.properties.getProperty("logLocation").equalsIgnoreCase("debug") && (event.getLevel() == Level.INFO || event.getLevel() == Level.ERROR || event.getLevel() == Level.DEBUG || event.getLevel() == Level.WARN)) {
            return 1;
        } else if (this.properties != null && this.properties.getProperty("logLocation").equalsIgnoreCase("info") && (event.getLevel() == Level.INFO || event.getLevel() == Level.ERROR || event.getLevel() == Level.WARN)) {
            return 1;
        } else {
            return this.properties == null || !this.properties.getProperty("logLocation").equalsIgnoreCase("all") || event.getLevel() != Level.INFO && event.getLevel() != Level.ERROR && event.getLevel() != Level.DEBUG && event.getLevel() != Level.WARN ? -1 : 1;
        }
    }
```

When the `this.readConfig()` line is invoked, if there is no Config.properties file where it's looking to read, the `this.properties` collection is not null, it's empty (as in zero properties).

In the "if" logic folows, because there is no check for an empty property set, an uninformative null pointer exception is thrown.

My current workaround is to create a Config.properties file in the location where it's looking (`Config` folder) with the singular property of `logLocation=` (with no set value), however anyone who updates to your latest version of byte-buddy, without that exact file in the expected location is going to be throwing an NPE.

If this is an offshoot of your code, please fix it, if it isn't but you know who owns the code, please forward this bug report to them so they can fix it.

Regards,
Mike Posluszny

**Comment by raphw** [comment]
Hi Mike, did I understand this correctly that you updated the library and not only Byte Buddy? I am not sure how this relates to Byte Buddy then. I have not heard of Appium before but I assume that the error is in their code.

**Comment by mikepoz59** [comment]
Hi Raphael,

Appium is a tool used to create test automation on mobile devices (such as iPhone and Android).

The reason I brought the issue here is because Appium 7.3.0 has a dependency on Byte-Buddy 1.8.15.  Where as the previous Appium version we were using has a dependency on Byte-Buddy 1.7.9.  When I set the dependency to exclude Byte-Buddy dependency from Appium and force it to Byte-Buddy 1.7.9, com.etap.core is never included as a dependency, and the problem never appears.

I'm using IntelliJ 2019.3.2 for my IDE  which does real time decompilation during debugging so I can step through the imported dependency code, and the path back to the offending class shows it as a dependency of byte-buddy 1.8.15.  Please see the attached PNGs.

![byte-buddy-eTap-dependency](https://user-images.githubusercontent.com/5043905/74260455-60c89500-4cae-11ea-8ed2-6f8099fe5714.png)
![etap-class-path-under-byte-buddy](https://user-images.githubusercontent.com/5043905/74260458-61612b80-4cae-11ea-83f1-02ada26cb234.png)

Given that I'm unable to find the actual owners of com.etap.core, I'm reaching out to you as the owner of byte-buddy in the hopes that we may be able to figure out where the com.etap.core component comes from so we can get it fixed.

Does that help to answer why I reached out to you?  

Thanks!
Mike Posluszny

**Comment by raphw** [comment]
Hi Mike, it's weird to see this dependency as part of Byte Buddy. It certainly is not; is that a shaded jar?

That said, I have no idea why the update would cause this problem. I do however have a suspicion. In the library code, if you did not specify a `ClassLoadingStrategy` Byte Buddy 1.7.* chose the injection strategy by default. With the module system, this was no longer a good option and Byte Buddy does now only use unsafe API if you are opting into it, therefore, since 1.8.*, the wrapping strategy became the default. Probably, some class becomes invisible as a result triggering the error.

You have two options here:
- stay on an old version of Byte Buddy. They are working fine.
- find calls of `DynamicType.Unloaded.load(ClassLoader)` and add `ClassLoadingStrategy.Default.INJECTION` as second argument.

**Comment by mikepoz59** [comment]
Hey Raphael,

Had to look up what a "shaded jar" is, and it's possible, unfortunately our pipeline (which I have no control over) seems to be pulling it down.    

It's good to hear that using the 1.7.* version of Byte-Buddy won't be a problem, we will continue to use that for our purposes as it seems to have resolved a few issues with our unit tests including a "forked process" error that was blocking us.

I'm going to close this so that it's not an issue you need to deal with within your code.  Have a great day!

Regards,
Mike Posluszny
