### ISSUE TITLE
MethodDelegation.to unexpected Method

### ISSUE THREAD

**Issue by FlyingSheepOnSailfish** [raphw/byte-buddy#814]
Hi Rafael

I am using ByteBuddy to delegate calls to Interface methods to a proxy, as outlined in this StackOverflow question.

https://stackoverflow.com/questions/60317919/byte-buddy-method-interception-invocationhandler-vs-methoddelegation-to-general.

I changed my code to use the "GeneralInterceptor" approach. 
Most of the calls to interface methods are delegated to the `intercept()` method marked with the  `@RuntimeType` annotation in the proxy class as expected.

However some are not: these delegate to an unexpected (to me) method.

e.g.. If my proxy contains a method with this signature:
`public int wrongmethod(Object value) {}`

it will intercept calls to methods with this signature:
`public int dummy(String string1, Double dbl);`

If I remove `wrongmethod()` from my proxy, or change its signature, then calls to `dummy()` will be intercepted by `intercept()` as expected.

I guess that ByteBuddy's MethodDelegation.to() logic considers `wrongmethod()` a better match than `intercept()`

**Comment by FlyingSheepOnSailfish** [comment]
If I mark `wrongmethod()` with the annotation `@IgnoreForBinding` then it will be ignored, and `intercept()` will intercept as expected. However that seems a little hit-or-miss.

**Comment by FlyingSheepOnSailfish** [comment]
Marking `intercept()` with` @BindingPriority(value = 999)` seems to work in my simple demo, will see if it works with my real code...

**Comment by raphw** [comment]
You can filter methods: `MethodDelegation.withDefaultConfiguration().filter(...).to(...)`. This way, you can explicitly state what methods to consider. You can also use the `@IgnoreForBinding` annotation on methods you want to ignore.

**Comment by FlyingSheepOnSailfish** [comment]
Thanks Rafael once again for your rapid and helpful response.
Explicitly configuring the delegate target method is perfect. My Byte-Buddy now looks like this:
```
Class<? extends S> clazz = new ByteBuddy()
   .subclass(serviceSuperClass)
   .implement(serviceInterface)
   .name(className)
   .defineField(PROXY, ServiceSupport.class, Visibility.PUBLIC)
   .method(isDeclaredBy(serviceInterface)
       .and(
           isAnnotatedWith(
                           anyOf(
                                 AutoRequest.class, 
                                 AutoSimpleSqlRequest.class, 
                                 AutoSimpleSqlDMLRequest.class
                                 )
                           )
           )
       )
   .intercept(MethodDelegation.withDefaultConfiguration()
                              .filter(named(INTERCEPTMETHOD))
                              .toField(PROXY))
   .make ()
   .load(classLoader)
   .getLoaded();
```
I prefer this to both the `@IgnoreForBinding` and `@BindingPriority(value = 999) `annotations suggested in the comments above.

Interestingly, `wrongmethod()` was not marked with the annotation `@RuntimeType` (only `intercept()` was) yet was still being taken in place of `intercept()`.

**Comment by raphw** [comment]
You are welcome. You can also set up a custom `AmbiguityResolver` to decide what methods to chose before one another.
