### ISSUE TITLE
How to change the filed value and make the method use the changed value using bytebuddy

### ISSUE THREAD

**Issue by amar1019** [raphw/byte-buddy#816]
public void method(Object object1){

      // i want to replace object1 with object2 at the beginning.

      // method's code (will use object2 and update it )

      // i want to use the updated object2
}

@raphw  Can u please help me in this

**Comment by raphw** [comment]
Have a look at `Advice` and the `@Advice.Argument(value = 0, readOnly = false)` parameter annotation. The javadoc should explain how this is applied. It allows you to change a parameter as you want.

**Comment by amar1019** [comment]
@raphw thanks for the answer. Suppose there are two arguments and I want to update the second argument. Should I put value=1 in that case?

**Comment by amar1019** [comment]
I have put value =1 it worked. Thank you very much
