### ISSUE TITLE
How to return in @Advice.onMethodEnter 

### ISSUE THREAD

**Issue by amar1019** [raphw/byte-buddy#819]
I want to return from a method if some particular condition is true. How do i do that?

public void method(){
     if(condtition==true){
         return ;
      } // i do not want the method's code to execute.
    //method's code

}

https://stackoverflow.com/questions/50237592/is-it-possible-to-return-from-a-method-using-advice-onmethodenter
I tried this approach. It didn't work.

**Comment by raphw** [comment]
You want to skip a method's execution? Have a look at `@Advice.OnMethodEnter(skipOn = ...)`.

You can then conditional abort method execution.

**Comment by amar1019** [comment]
Yes . Actually that link worked. I was using the values which would suit for OnDefaultValue.
