### ISSUE TITLE
Add metadata necessary to be recognized by m2e out of the box

### ISSUE THREAD

**Issue by odrotbohm** [raphw/byte-buddy#820]
It would be cool if the ByteBuddy Maven plugin would automatically be detected and properly executed within m2e (Eclipse Maven integration). Ideally that would also cause execution errors to properly reported in Eclipse's problems view etc.

Currently m2e is not able to detect proper lifecycle mappings (see [the docs](https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html#lifecycle-mapping-metadata-provided-by-maven-plugin))but you can Eclipse to invoke the plugin by editing the lifecycle metadata configuration (Settings > Maven > Lifecycle Mappings > Open workspace lifecycle mappings metadata) and adding the following snippet of XML.

```xml
<pluginExecution>
  <pluginExecutionFilter>
    <groupId>net.bytebuddy</groupId>
    <artifactId>byte-buddy-maven-plugin</artifactId>
    <versionRange>[0.0.1,)</versionRange>
    <goals>
      <goal>transform</goal>
    </goals>
  </pluginExecutionFilter>
  <action>
    <execute>
      <runOnIncremental>true</runOnIncremental>
    </execute>
  </action>
</pluginExecution>
```

The m2e developer documentation contains [useful hints](https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html) on what it takes to make this work.

**Comment by raphw** [comment]
Fixed bt #897.

**Comment by odrotbohm** [comment]
Looks like this has been resolved and published already? According to Maven Central 1.10.13 is already out.

**Comment by odrotbohm** [comment]
I have to take that back. After a M2E configuration cleanups and a restart I am back to where I started. A bit of investigation revealed that the current [version of the metadata file](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml) simply contains:

```xml
<action>
  <execute />
</action>
```

whereas the [developer documentation](https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html) states that `<runOnIncremental>true</runOnIncremental>` would be needed to execute the plugin during Eclipse builds.

I am a bit puzzled not to even find that file (`META-INF/m2e/lifecycle-mapping-metadata.xml`) at all in the JARs obtained from Maven Central. I just built the plugin locally and that seems to package it at least up appropriately. Does that somehow not get package when releasing?

**Comment by odrotbohm** [comment]
A final one hopefully. What I observed is essentially caused by #896 fixed by #897, just as linked to above. I guess what added to my confusion is that the ticket is still assigned to 1.10.8, a still open but already released milestone. Does it make sense to flip the fix version for this one here to 1.10.14, too as it effectively needs #897 to be fully resolved and that one will be in 1.10.14 the earliest.

**Comment by raphw** [comment]
I am closing this as I understand that this issue is resolved? Please let me know if something is missing here.

**Comment by odrotbohm** [comment]
It is indeed. Thanks, Raphael!
