### ISSUE TITLE
[Q] Remove instrumentation by ResettableClassFileTransformer

### ISSUE THREAD

**Issue by dengliming** [raphw/byte-buddy#823]
@raphw Hi~ I have a few questions that I don't quite understand.
If I call ResettableClassFileTransformer#reset method, How does it actually work, Is it executed synchronously or asynchronously? Will it affect the performance of the application itself? like cpu.

I also want to control this operation remotely, Can you give me a simple example? Thank you very much.

**Comment by raphw** [comment]
It will iterate over all classes and retransform those that were previously transformed but without applying the represented transformer. Methods are deoptimized but methods that are currently executed remain in that state until they exit - an infinite loop would for example never return to it's old state.

If you want to trigger this remotely, you have to register some endpoint for it, e.g. an HTTP server or a JMX MBean.

**Comment by dengliming** [comment]
Thanks, Will it affect the performance of the application itself? like cpu. Is the application sensorless when call ResettableClassFileTransformer#reset method?

**Comment by raphw** [comment]
Yes, there will be a stop-the-world-pause to apply the retransformation and then there will be some code falling back into interpreted mode when the optimized code is thrown out.

**Comment by dengliming** [comment]
Thanks, Do you have any good ways to remove Instrument instead of calling ResettableClassFileTransformer#reset method？

**Comment by raphw** [comment]
You can guard your instrumentation with some form of if statement which you can turn off; this way your code will be ineffective once disabled.

**Comment by dengliming** [comment]
Got it, Thanks.
