### ISSUE TITLE
VirtualMachine.attach uses incorrect temporary directory on Mac OS X

### ISSUE THREAD

**Issue by qwwdfsad** [raphw/byte-buddy#825]
Steps to reproduce:

* Clone https://github.com/dkhalanskyjb/byteBuddyMacBug
* export `TMPDIR` to point to any dir
* Try to self-attach

Explanation:

On Mac OS X, there are multiple notions of "temporary directory".
1) One is "current OS user's temporary directory". This has the form of `/var/folders/81/6kccpxhx0vs_tjy4x93n2zzc0000gq/T/` (this is a rough equivalent of the hash of user id). It (the path) cannot be modified to point somewhere else, it can be retrieved by a system call `confstr(_CS_DARWIN_USER_TEMP_DIR)` and this is exactly what [Hotspot does](https://github.com/openjdk/jdk/blob/6bab0f539fba8fb441697846347597b4a0ade428/src/jdk.attach/macosx/native/libattach/VirtualMachineImpl.c#L321) for attach mechanism.
2) Another one is `$TMPDIR`. By default, it points to current OS temporary directory but can be changed. The change affects only applications that **explicitly** use this environment variable. E.g. it won't change the location of `.hsperfdata`, the location of `File.createTempFile` or the result of bash utility `mktemp`.

ByteBuddy [uses](https://github.com/raphw/byte-buddy/blob/1f63d1a18edaa66691541fcf652e668202385628/byte-buddy-agent/src/main/java/net/bytebuddy/agent/VirtualMachine.java#L891) the latter, which doesn't work when `$TMPDIR` is overridden.
E.g. self-attach stops working on any Mac OS X CI (where all these temp directories are usually overwritten. This is exactly the case that prevents us from releasing the JNA-based fix for #670).

It seems like the only reliable solution is to use JNA in order to call `confstr`

**Comment by raphw** [comment]
I see, I am really not a Mac guy, so I have no idea of these MacOS specifics. I tried to implement the resolution but have no mac to try, could you verify: https://github.com/raphw/byte-buddy/tree/mac-attach

**Comment by qwwdfsad** [comment]
Thanks! I've verified it locally and it works as expected.

I also want to verify it on our CI Mac OS X agents, though it may take a while to resolve some publication-specific issues

**Comment by qwwdfsad** [comment]
[Verified](b4a6bcda16b4e6fc1ec2ebc8f2ec47ecfa8518b6), works like a charm

**Comment by raphw** [comment]
Great, will merge and release some time this week.

**Comment by raphw** [comment]
Merged to master.
