### ISSUE TITLE
performance of big class and many hook points

### ISSUE THREAD

**Issue by hnwyllmm** [raphw/byte-buddy#828]
I have a class with 292 methods total, and almost every method have a singal delegation.
It cost about 1.9S on my PC which have a I5 CPU and 8G ram.
I have found that it cost too much in `MethodRegistry.Prepared prepare`, as you can see:

![image](https://user-images.githubusercontent.com/5187215/77273495-b56c2080-6cee-11ea-85bc-33381467ab72.png)

The `declaredMethods` have 292 items and `typeDescription` have 292 methods, so 
```java
if (!declaredMethods.contains(methodDescription))
```
will compute 85K times and `methodDescription`'s hashCode has to be recompute too many times.

In the `MethodDescription::hasCode`, `asTypeList` take the half time of it.
Do you have any suggestion to optimize it?

**Comment by raphw** [comment]
I added `@CachedReturnPlugin.Enhance` to all hash code computations. This implies that all instances will retain their previously computed hash code. I also added reuse logic for instrumented type computations; i.e. if your instrumented type is altered, the hash code needs to be recomputed.

I hope this should remedy your issue.

**Comment by hnwyllmm** [comment]
yes, that's great!
