### ISSUE TITLE
cannot redefine inner class as public

### ISSUE THREAD

**Issue by maciejmikosik** [raphw/byte-buddy#83]
Inner classes are compiled as package-private. They have constructor with parameter accepting outer class. I try to redefine inner class as public and add public no-arg constructor. This way I can create local classes with properties I want without need to make them top-level.

This generally works except one small detail. Inspecting class modifiers does not show it is public. This is my junit test

```
import static java.lang.reflect.Modifier.PUBLIC;
import static net.bytebuddy.dynamic.loading.ClassLoadingStrategy.Default.WRAPPER;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.lang.reflect.Modifier;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.implementation.SuperMethodCall;

import org.junit.Test;

public class RedefineInnerClassTest {
  class Inner {}

  @Test
  public void makes_class_public_with_public_constructor() throws Exception {
    Class<?> redefined = new ByteBuddy()
        .redefine(Inner.class)
        .modifiers(PUBLIC)
        .name("Redefined")
        .defineConstructor(Object.class.getConstructor())
        .intercept(SuperMethodCall.INSTANCE)
        .make()
        .load(Inner.class.getClassLoader(), WRAPPER)
        .getLoaded();

    assertNotNull(redefined.getConstructor().newInstance());
    assertTrue(Modifier.isPublic(redefined.getModifiers()));
  }
}
```
Last assertion fails.

However it looks like class is public afterall.
 - Removing `.modifiers(PUBLIC)` makes test fail on first assertion with `java.lang.IllegalAccessException`
 - Saving bytecode to file and running `javap` show that class is public.
 - Also changing `Inner` class to top-level package-private makes test pass.

Is this a bug or I did something wrong?

**Comment by raphw** [comment]
Hi, thanks for the report. Inner classes have spefic meta information attached to them in order to represent class-contextual modifiers such as `private` classes. Byte Buddy has not patched this attribute but only changed the actual modifiers. This is now fixed in master and will be part of the next release.
