### ISSUE TITLE
[Question] Use annotation object in Advice.OnMethodExit method

### ISSUE THREAD

**Issue by cptkng23** [raphw/byte-buddy#831]
Hi Raphael.

First of all thanks for this incredible library. I came across this just a month ago, but already fell it love with it.

Like so many others, I played around to implement an agent for cross cutting concerns, specifically metrics.

For this I have an annotation that I use in my business code, like:

```java
/**
 * Methods with this annotation will emit a count increment metric to Datadog for each invocation.
 */
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface DatadogCount {
    /**
     * Mandatory parameter for the name of the metric.
     *
     * @return the name of the metric.
     */
    String metricName();

    /**
     * The optional list of tags to be included during metric submission.
     * Example:
     * - tags = "key1:value1"
     * - tags = {"key1:value1", "key2:value2"}
     *
     * @return the list of tags
     */
    String[] tags() default {};
```

What I would like to achieve now it to use a transformer and `withCustomMapping()...`, so that in the   
`ExitAdviceMethod` - annotated with `@Advice.OnMethodExit` I can access my `@DatadogCount` annotation as a method parameter. 
All works well if I'm _just_ interested in the metricName. For that I have

1. configured a method visitor in the `transform` method of my Transformer (extends ` extends AgentBuilder.Transformer.ForAdvice`) like this
  ```java
    ...
  Advice.withCustomMapping()  
    .bind(MetricsAdvice.DatadogCountMetricName.DatadogCountResolver.Factory.INSTANCE)
    ...
  ```
2. annotated the ExitAdviceMethod accordingly
  ```java
private static class ExitAdviceMethods {
        @Advice.OnMethodExit(onThrowable = Throwable.class)
        static void exit(@MetricsAdvice.DatadogCountMetricName final String metricName,
                         @Advice.Origin final Executable executable) {
 ...
  ```

3. Created the respective factory
  ```java
  ...
@Retention(RetentionPolicy.RUNTIME)
    @java.lang.annotation.Target(ElementType.PARAMETER)
    public @interface DatadogCountMetricName {
        class DatadogCountResolver implements Advice.OffsetMapping {
            @Override
            public Target resolve(TypeDescription instrumentedType,
                                  MethodDescription instrumentedMethod,
                                  Assigner assigner,
                                  Advice.ArgumentHandler argumentHandler,
                                  Sort sort) {
                final String metricName = instrumentedMethod.getDeclaredAnnotations()
                                                            .ofType(DatadogCount.class)
                                                            .load()
                                                            .metricName();
                return Target.ForStackManipulation.of(metricName);
            }

            protected enum Factory implements Advice.OffsetMapping.Factory<DatadogCountMetricName> {
                INSTANCE;

                @Override
                public Class<DatadogCountMetricName> getAnnotationType() {
                    return DatadogCountMetricName.class;
                }

                @Override
                public Advice.OffsetMapping make(final ParameterDescription.InDefinedShape target,
                                                 final AnnotationDescription.Loadable<DatadogCountMetricName> annotation,
                                                 final AdviceType adviceType) {
                    return new DatadogCountResolver();
                }
            }
        }
    }
  ... 
  ```

But as the annotation has more that just a metric name, and is still _constant_ in terms of the information for each method it annotates, I was wondering if I could directly access the annotation instance/object in the ExitAdviceMethods like this? Mainly to avoid the reflection lookup from the executable.
  ```java
private static class ExitAdviceMethods {
        @Advice.OnMethodExit(onThrowable = Throwable.class)
        static void exit(@MetricsAdvice.DatadogCountAnnoation final DatadogCount annoation,
                         @Advice.Origin final Executable executable) {
 ...
  ```

I was scanning through all the examples of the ByteBuddy code, but couldn't find a way to return an annotation to the Advice method.

Is that at all possible, and if yes, would you have a hint?

**Comment by raphw** [comment]
It needs to be constant in the sense of a compile time constant. Otherwise, you would need to create an instance dynamically what is exactly what using the annotation API is doing. Therefore, if you want to go for minimum runtime overhead, you'd need to store the value as a string in a constant pool.

Alternatively, you can look into implementing a bootstrap method for a constdynamic instruction what Byte Buddy supports and the JVM does in invokedynamic. The disadvantage is that you need an outgoing call to some bootstrap method to bind the custom constant.

**Comment by cptkng23** [comment]
Hi Raphael.

Thank you for your prompt reply. Trying to rephrase what you said to understand it correctly:

> It needs to be constant in the sense of a compile time constant. Otherwise, you would need to create an instance dynamically what is exactly what using the annotation API is doing. Therefore, if you want to go for minimum runtime overhead, you'd need to store the value as a string in a constant pool.

_store the value as a string_: I think this is what I'm doing in the above snippet, where I store the annotation's property _metricName_ as a String. What I wanted to achieve was to access my whole (more or less constant, as it's defined during compilation) annotation object in the Advice method, to be able to not only access the metricName as above, but also e.g. the tags property of the annotation. Of course I could extract each and every property separately, but being able to access this all at once would haven been nice.
So I understand your comment in the way that I need to extract each property separately and store it in a string constant?

Thanks for mentioning a second option here. Currently, this seems a bit too complex for my use case. Still, would you have a good advice where to look for further hints on how to implement it?

Thanks again,
Arne

**Comment by raphw** [comment]
The constant pool can store strings, primitive values and method handles. Beyond that you can only bind custom values using constantdynamic.

One workaround is to store a serialized value as a base64 encoded string and deserialize it on access. Byte Buddy supports it, but performance is terrible. I'd rather explode values if I have a chance.

**Comment by cptkng23** [comment]
Thanks again.

Deserializing really sounds wrong. Of course exploding is possible, it's just a log of code duplication, as all my annotations I want to process have the same properties (here e.g. metricName), but I still need to write a separate resolver/OffsetMapping for each of them.

But I understand now why that is.

Related to your constantdynamic mention, among the first search results I found was a blog post of yours: https://www.javacodegeeks.com/2018/08/hands-on-java-constantdynamic.html

I'm closing this, thanks for your advices.
