### ISSUE TITLE
Grade plugin ignores the `tasks` property

### ISSUE THREAD

**Issue by bsideup** [raphw/byte-buddy#833]
Hi!

I am playing with ByteBuddy's Gradle plugin (version 1.10.9) and it seems that the `tasks` property is ignored.

My config:
```groovy
byteBuddy {
    setTasks(new AbstractSet<String>() {
        @Override
        boolean contains(Object o) {
            new Exception(o.toString()).printStackTrace()
            return false; // "compileBuildPluginTestJava" == o
        }

        @Override
        Iterator<String> iterator() {
            return Collections.emptyIterator()
        }

        @Override
        int size() {
            return 0
        }
    })

    transformation {
        plugin = "reactor.tools.agent.ReactorDebugByteBuddyPlugin"
    }
}
```

(`AbstractSet` here just to debug `contains`, but it does not work with `["nonExistingTask"] as Set` neither)

Running the logs with `--info` gives me:
```
> Configure project :reactor-tools
Evaluating project ':reactor-tools' using build file '/Users/bsideup/Work/reactor/reactor-core/reactor-tools/build.gradle'.
Compiling build file '/Users/bsideup/Work/reactor/reactor-core/reactor-tools/build.gradle' using SubsetScriptTransformer.
Compiling build file '/Users/bsideup/Work/reactor/reactor-core/reactor-tools/build.gradle' using BuildScriptTransformer.
java.lang.Exception: compileJarFileTestJava
	<...>
	at build_6qu5i2imhbvxxd29jtzu5e6km$1.contains(/Users/bsideup/Work/reactor/reactor-core/reactor-tools/build.gradle:34)
	at net.bytebuddy.build.gradle.ByteBuddyExtension.implies(ByteBuddyExtension.java:239)
	at net.bytebuddy.build.gradle.PostCompilationAction.execute(PostCompilationAction.java:62)
```

And later in the same log:
```
Task ':reactor-tools:compileJava' is not up-to-date because:
  Output property 'destinationDirectory' file /Users/bsideup/Work/reactor/reactor-core/reactor-tools/build/classes/java/main has been removed.
  Output property 'destinationDirectory' file /Users/bsideup/Work/reactor/reactor-core/reactor-tools/build/classes/java/main/reactor has been removed.
  Output property 'destinationDirectory' file /Users/bsideup/Work/reactor/reactor-core/reactor-tools/build/classes/java/main/reactor/tools has been removed.
The input changes require a full rebuild for incremental task ':reactor-tools:compileJava'.
Compiling with JDK Java compiler API.
/Users/bsideup/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.10.9/cbbeffa557e6b1b4cbb181b0782436921c523699/byte-buddy-agent-1.10.9.jar(/net/bytebuddy/agent/ByteBuddyAgent.class): warning: Cannot find annotation method 'value()' in type 'SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found
/Users/bsideup/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.10.9/cbbeffa557e6b1b4cbb181b0782436921c523699/byte-buddy-agent-1.10.9.jar(/net/bytebuddy/agent/ByteBuddyAgent.class): warning: Cannot find annotation method 'justification()' in type 'SuppressFBWarnings'
/Users/bsideup/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.10.9/cbbeffa557e6b1b4cbb181b0782436921c523699/byte-buddy-agent-1.10.9.jar(/net/bytebuddy/agent/ByteBuddyAgent.class): warning: Cannot find annotation method 'value()' in type 'SuppressFBWarnings'
/Users/bsideup/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.10.9/cbbeffa557e6b1b4cbb181b0782436921c523699/byte-buddy-agent-1.10.9.jar(/net/bytebuddy/agent/ByteBuddyAgent.class): warning: Cannot find annotation method 'justification()' in type 'SuppressFBWarnings'
4 warnings
Resolved plugin: reactor.tools.agent.ReactorDebugByteBuddyPlugin
Resolved entry point: REBASE
Processing class files located in in: /Users/bsideup/Work/reactor/reactor-core/reactor-tools/build/classes/java/main
Transformed 7 types
```

Reproducer:
1. Clone https://github.com/reactor/reactor-core
2. Reproduces with commit `b681a6b5f4e41d462178d014a8b15c85a19a247e`
3. Run `test` task in `reactor-tools` module
4. `stackTrace()` test case will fail because the instrumentation is applied two times

**Comment by raphw** [comment]
Not sure why this happens. The code says:

```java
if (byteBuddyExtension.implies(task)) {
  task.doLast(new TransformationAction(project, byteBuddyExtension, task));
} else {
  project.getLogger().info("Skipping non-specified task {}", task.getName());
}
```

**Comment by rmlekus** [comment]
I encountered the same effect with ByteBuddy Gradle Plugin in version 1.9.13. , when trying to limit a ByteBuddy Plugin to not be by `compileJava'  task ( no ByteBuddy class manipulation for test sources:

**Comment by raphw** [comment]
Hmm, do you guys know Gradle enough to explain why this is? I don't see what I am supposed to do differently.

**Comment by rmlekus** [comment]
Sorry for the delayed reaction. From reading the code of the implementation I would also have deduced that it should work as intended. I might get time do to the current social distancing guidelines to get a bit into debugging on the weekend.

Originally I thought it might be an issue with my personal gradle build script I just could not identify for unknown reason, and do to time restrictions and worked around by both partially separating the unit test sources into a different build without bytebuddy plugin and/or using "-x test" in combination with maven driven builds for the tests to work around this.  But it's about getting time for to clean up my work arounds (coding sins .)

**Comment by raphw** [comment]
Please do. I looked into it but would not know why this is happening giving this constraint. That said, the Gradle API is massive, I wonder if I am checking the wrong flag.

**Comment by rmlekus** [comment]
Sorry for the really long delay, but finally I could look at it, but finally I would Identify the reason for the tasks set not being considered to a conflict with gradle´s lazy configuration mechanism. 

Pleas find an attempted fix in my fork of the project as well as a pull request with my attempted fix in: https://github.com/raphw/byte-buddy/pull/918

**Comment by raphw** [comment]
I rewrote the plugin in its entirety and this should no longer be an issue.
