### ISSUE TITLE
use bytebuddy with newrelic

### ISSUE THREAD

**Issue by huangyoje** [raphw/byte-buddy#838]
bytebuddy version:1.10.1  
newrelic version:5.10.0

It seems that the newrelic agent will create some classes dynamically, and these classes implement some interfaces of newrelic agent. When bytebuddy agent tries to match these classes, it can't locate the class file for these interfaces.

I tried two ways for customing LocationStrategy, neither worked.

-  `ClassFileLocator.ForJarFile.ofClassPath("path of newrelic.jar")`

    This does't work because newrelic.jar is a fat jar, and the target interface belongs to a jar within newrelic.jar.

- I found that newrelic call `java.lang.instrument.Instrumentation#appendToBootstrapClassLoaderSearch(jars within newrelic.jar)`, so i tried `ClassFileLocator.ForClassLoader.ofBootLoader()`.

This also does't work, the reason can refer to [https://stackoverflow.com/q/51347432/7645128](https://stackoverflow.com/q/51347432/7645128)

```java
        new AgentBuilder.Default(new ByteBuddy())
                .ignore(nameStartsWith("com.newrelic"))
                .type(new ElementMatcher.Junction.AbstractBase<TypeDescription>() {
                    @Override
                    public boolean matches(TypeDescription target) {
                        try {
                            return hasSuperType(nameStartsWith("test.Enhance.")).matches(target);
                        } catch (Throwable t) {
                            System.out.println(String.format("match %s error msg %s", target, t.getMessage()));
                            return false;
                        }
                    }
                })
                .transform((builder, typeDescription, classLoader, module) ->
                        builder.constructor(any())
                                .intercept(SuperMethodCall.INSTANCE
                                        .andThen(MethodDelegation.withDefaultConfiguration()
                                                .to(new ConstructorInter())
                                        ))
                )            .with(AgentBuilder.LocationStrategy.ForClassLoader.STRONG.withFallbackTo(ClassFileLocator.ForClassLoader.ofBootLoader()))
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .installOn(net.bytebuddy.agent.ByteBuddyAgent.install());
```
error message:
```text
match class com.sun.proxy.$Proxy35 error msg Cannot resolve type description for com.newrelic.agent.bridge.Instrumentation
match class com.sun.proxy.$Proxy36 error msg Cannot resolve type description for com.newrelic.agent.bridge.ExitTracer
match class com.nr.agent.instrumentation.tomcat7.TomcatRequest error msg Cannot resolve type description for com.newrelic.api.agent.ExtendedRequest
```

What if one of my application class was enhanced to implement these interfaces by newrelic, and i also want to enhance that class use bytebuddy? How to resolve it? 

Thanks very much.

**Comment by raphw** [comment]
Yes, unfortunately, appending classes to the boot search path does not affect the availability of the classes as a resource, that's why it is named search path.

You would probably need to implement your own class locator strategy that explodes the fat jar. Or, you pick up the location of the jar files on the file system as they are placed out by New Relic. To use the append API, they need to be on the file system somewhere.

**Comment by huangyoje** [comment]
For these classes on the boot search path, is it safe to use `AgentBuilder.PoolStrategy.ClassLoading.FAST` to load these classes to get TypeDescription? I'm not sure if these classes can be loaded by bytebuddy?

I have tested this way,  however i'm stuck in the following situation, let me explain: 
1. This poolStrategy will create typePool1, the parent of typePool1 is typePool2(type is TypePool.Default.WithLazyResolution),    
2. Assume that the class to be matched is `class SomeClass implements InterfaceA `,  and the matcher is `hasSuperType(xxx)`
3. Using poolStrategy above will get `new LazyTypeDescription("scomClass")`, which the typePool in it is typePool2, not typePool1. 
4. When `LazyTypeDescription.getInterfaces()` is called, it will use typePool2 to resolve `InterfaceA`. However, what i want is `InterfaceA` can be resolved by `typePool1`.

Code that create `LazyTypeDescription`
```java
            protected TypeDescription toTypeDescription() {
                return new LazyTypeDescription(Default.this,
                        actualModifiers,
                        modifiers,
                        internalName,
                        superClassName,
                        interfaceName,
                        genericSignature,
                        typeContainment,
                        declaringTypeName,
                        declaredTypes,
                        anonymousType,
                        nestHost,
                        nestMembers,
                        superTypeAnnotationTokens,
                        typeVariableAnnotationTokens,
                        typeVariableBoundsAnnotationTokens,
                        annotationTokens,
                        fieldTokens,
                        methodTokens);
            }
```

Is this normal behavior?

**Comment by raphw** [comment]
Sounds like you are using the wrong aproach. You'd need to compose class file locators for use with a single type pool.

Think of class file locators as multiple jars of the same class loader and type pools as a tree of class loaders.

**Comment by huangyoje** [comment]
> You would probably need to implement your own class locator strategy that explodes the fat jar. 
This way solved my issue.  Thanks!

> Think of class file locators as multiple jars of the same class loader and type pools as a tree of class loaders.
This makes me more clear. However, what i try to do is that for these classes on the boot search path, if the class file locator can't locate the class file, then fallback to use `TypePool.ClassLoading`, is this possible?

**Comment by raphw** [comment]
Hmm, not really unless you would implement one that extends `Default` and applies this as a backup.
