### ISSUE TITLE
how to add implements javax.servlet.Filter class BodyReaderFilter

### ISSUE THREAD

**Issue by liujianrong** [raphw/byte-buddy#839]
@Component
public class BodyReaderFilter implements Filter {

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
        // do nothing
    }

    @Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
            throws IOException, ServletException {
        ServletRequest requestWrapper = null;
        if (request instanceof HttpServletRequest) {
            requestWrapper = new BodyReaderHttpServletRequestWrapper((HttpServletRequest) request);
        }
        if (requestWrapper == null) {
            chain.doFilter(request, response);
        } else {
            chain.doFilter(requestWrapper, response);
        }

    }

    @Override
    public void destroy() {
        // do nothing

    }

}

**Comment by raphw** [comment]
Not sure what you mean. Are you thinking of creating a Java agent to add an interface to a given class?

**Comment by txyx-artomu** [comment]
> Not sure what you mean. Are you thinking of creating a Java agent to add an interface to a given class?

I want to add servlet filters dynamically to the javaagent

 new AgentBuilder.Default()
                .type(hasSuperType(named("javax.servlet.Filter")))
                .transform((builder, typeDescription, classLoader, module) ->
                        builder.method(ElementMatchers.named("doFilter"))
                                .intercept(MethodDelegation.to(DoFilterInterceptor.class)))
                .installOn(instrumentation);

**Comment by liujianrong** [comment]
> Not sure what you mean. Are you thinking of creating a Java agent to add an interface to a given class?

I want to add servlet filters dynamically to the javaagent

new AgentBuilder.Default()
.type(hasSuperType(named("javax.servlet.Filter")))
.transform((builder, typeDescription, classLoader, module) ->
builder.method(ElementMatchers.named("doFilter"))
.intercept(MethodDelegation.to(DoFilterInterceptor.class)))
.installOn(instrumentation);
