### ISSUE TITLE
Couldn't call rebased final method thru @Super auxiliary type

### ISSUE THREAD

**Issue by Spikhalskiy** [raphw/byte-buddy#84]
```
public class SimpleObject {
    public **final** void method() {
        System.out.println("ABC");
    }
}

public class Interceptors {
    public static void method(@Super SimpleObject thisObjectWithOriginalMethods) {
        thisObjectWithOriginalMethods.method();
    }
}

public class InterceptorsInitializer {
    public static void main(String[] args) {
        registerModificationInterception();
    }
}

public static void registerModificationInterception() {
    TypePool typePool = TypePool.Default.ofClassPath();
    new ByteBuddy()
        .rebase(typePool.describe("SimpleObject").resolve(), ClassFileLocator.ForClassLoader.ofClassPath())
                .method(named("method")).intercept(MethodDelegation.to(typePool.describe("Interceptors").resolve()))
        .make()
        .load(InterceptorsInitializer.class.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
        .getLoaded();
    }
}

public class SimpleTest {
    @BeforeClass
    public static void before() {
        InterceptorsInitializer.registerModificationInterception();
    }

    @Test
    public void test() {
        SimpleObject simpleObject = new SimpleObject();
        simpleObject.method();
    }
}
```

When start `SimpleTest#test()`, we will get
```
java.lang.StackOverflowError
	at SimpleObject.method(SimpleObject.java)
	at Interceptors.method(Interceptors.java:8)
	at SimpleObject.method(SimpleObject.java)
	at Interceptors.method(Interceptors.java:8)
```
So `@Super` auxiliary type actually proxy call to intercepter method's code, not original method. If remove **final** keyword from `void method()` - everything works fine.

**Comment by raphw** [comment]
The problem here is that it is impossible to override a `final` method. But in order to change the method's behavior, it is necessary to do that. The contract of the `@Super` annotation clearly states that this is the case. Additionally, it is not currently possible to redefine a modifier such that this would be visible to the `@Super` annotation. I hope to be able to include such a possibility in a future version of Byte Buddy. Note however, that it would still be necessary to remove the modifier.

However, what you want to do is trivial. Since the method is not overridden, change your interceptor like follows:

```java
public class Interceptors {
    public static void method(@This SimpleObject thisObject) {
        thisObject.method();
    }
}
```

Now everything works as expected for a `final` method. Byte Buddy cannot really offer a better alternative since the Java type system sets this restriction.

**Comment by Spikhalskiy** [comment]
Hi @raphw But I make a **redefine** here? So, what's the problem if I redefine final method before loading it's bytecode? Change it's name and create new one as with non-final method. Don't see any problem with this process.

**Comment by raphw** [comment]
That is what Byte Buddy is doing under the covers. But in order to reuse the type, `@Super` needs to retain the names even when proxying the call. Maybe you want to use `@SuperCall` instead? Here, this limitation does not apply:

```java
public class Interceptors {
    public static void method(@SuperCall Runnable runnable) {
        runnable.run();
    }
}
```

**Comment by Spikhalskiy** [comment]
Yes, SuperCall or Morph can be used here I think. Ok, clear, we just can't make auxiliary class once more because of *final* modifier and stuck in analog of modifier() absence on `MatchedMethodInterception` currently in ByteBuddy.

**Comment by raphw** [comment]
The problem with `@Super` here is the way it is implemented in order to reuse Java types. The interception looks like this:

```java
public class SimpleObject$Super extends SimpleObject {
    
   SimpleObject actual$super;

   @Override
    public void method() {
        actual$super.method$super();
    }
}
```

In order to implement such a proxy, neither the instrumented type or the instrumented method must be final. There is no way arround this, as the JVM enforces this.

**Comment by Spikhalskiy** [comment]
We have an ability to remove final from class before it get loaded, so we can do same modification for methods? Before loading class byte-code - just remove final from method. It will make all of this possible, no?

**Comment by raphw** [comment]
Eventually, I plan to allow for this. Currently, I have some issues with the internal type representation that I need to refactor first. Once these changes are made, I hope that I can allow for such transformations.
