### ISSUE TITLE
Question: possible performance improvement

### ISSUE THREAD

**Issue by cliviu** [raphw/byte-buddy#840]
Hi, I use the following code to instantiate an objectFactory. Somehow, the method is running slower as the cglib version. Here is what I do: 

https://github.com/serenity-bdd/serenity-core/blob/master/serenity-core/src/main/java/net/thucydides/core/steps/StepFactory.java

The method is createProxyStepLibrary() ... My concerns are mostly related to the method  
```java
  private ClassLoadingStrategy getClassLoadingStrategy(Class targetClass) {
        ClassLoadingStrategy<ClassLoader> strategy;
        try {
            if (ClassInjector.UsingLookup.isAvailable()) {
                Class<?> methodHandles = Class.forName("java.lang.invoke.MethodHandles");
                Object lookup = methodHandles.getMethod("lookup").invoke(null);
                Method privateLookupIn = methodHandles.getMethod("privateLookupIn",
                        Class.class,
                        Class.forName("java.lang.invoke.MethodHandles$Lookup"));
                Object privateLookup = privateLookupIn.invoke(null, targetClass, lookup);
                strategy = ClassLoadingStrategy.UsingLookup.of(privateLookup);
            } else if (ClassInjector.UsingReflection.isAvailable()) {
                strategy = ClassLoadingStrategy.Default.INJECTION;
            } else {
                throw new IllegalStateException("No code generation strategy available");
            }
            return strategy;
        } catch (NoSuchMethodException |InvocationTargetException | IllegalAccessException | ClassNotFoundException e) {
            LOGGER.error("Cannot get ClassLoadingStrategy  for target class " +  targetClass , e);
            throw new IllegalStateException("No code generation strategy available");
        }
    }
```

Thanks !

**Comment by raphw** [comment]
Looking at your code, it seems like you are creating the same class many, many times. Cglib has an implicit cache which does however create leaks, this is why Byte Buddy does not reproduce it. Have a look at delegating to a field, rather to an instance, use a `TypeCache` and then only create the class you need once. Instead, set the fields for any instance you create of it later.

**Comment by cliviu** [comment]
Do you have some somewhere kind of example of a best practice how to do it ? Should I have some static class with static initializer for delegating to a field ? How to use the TypeCache  ?

**Comment by raphw** [comment]
You could have a look at what Hibernate is doing, it's similar to your requirement:

https://github.com/hibernate/hibernate-orm/blob/34f58e91c6fae370dc3d546aaaab254c0ebe6fba/hibernate-core/src/main/java/org/hibernate/bytecode/internal/bytebuddy/BasicProxyFactoryImpl.java#L41

**Comment by cliviu** [comment]
> Looking at your code, it seems like you are creating the same class many, many times. Cglib has an implicit cache which does however create leaks, this is why Byte Buddy does not reproduce it. Have a look at delegating to a field, rather to an instance, use a `TypeCache` and then only create the class you need once. Instead, set the fields for any instance you create of it later.

Are you talking now about the ByteBuddy  class initialization when you say that the same class is created many, many times ?  I'm not sure how to optimize this because the "interceptor" is always a new object ... Storing the ByteBuddy instance in a field will not help because the "intercept" method becomes always a new interceptor ...

**Comment by raphw** [comment]
You'd base the `TypeCache` key on `scenarioStepsClass` and the type of `interceptor` and then change `MethodDelegation.toField("foo")` where you'd also define a field of the type of interceptor.

I guess that those combinations of interceptor type and steps class are repeated, you'd save a lot of time for every time you reuse a class; this is what cglib does for you permanently but it also disallows that classes are ever unloaded which is why Byte Buddy has an explicit mechanism with a cache.

**Comment by cliviu** [comment]
This means I will need a field "foo" in the scenarioStepClass. But the scenarioStepClass  is a POJO. Not sure how to deal with this. And, the relationship between ScenarioStepClass and interceptor is not 1:1. The interceptor is alway given as a  parameter to the createProxyStepLibrary() ...

**Comment by raphw** [comment]
You'd needed to define a field but it would be placed in the subclass that you create, it should not conflict. 

Other than that, you can of course reuse:

```java
  Class<?> methodHandles = Class.forName("java.lang.invoke.MethodHandles");
                Object lookup = methodHandles.getMethod("lookup").invoke(null);
                Method privateLookupIn = methodHandles.getMethod("privateLookupIn",
                        Class.class,
                        Class.forName("java.lang.invoke.MethodHandles$Lookup"));
```

which is rather expensive to call.

**Comment by raphw** [comment]
You can create a method handle to access `Interceptor` or you define an interface with some method `setInterceptor` such that you can cast the class and set that field.

**Comment by cliviu** [comment]
Thanks, I will try it

**Comment by cliviu** [comment]
Thanks, your advice helped  improving the performance.
