### ISSUE TITLE
Illegal parameter name of java.lang.String <set-?>

### ISSUE THREAD

**Issue by IceBlizz6** [raphw/byte-buddy#843]
I am using the byte-buddy maven plugin on a Kotlin project.
I need to retain the parameters for another library.
Currently the byte-buddy plugin now fails on transforming the class.

This works if i do not retain parameters, so it looks like Kotlin generates some parameter names for the setter on properties that byte-buddy is unable to handle.

pom.xml
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>sample</groupId>
    <artifactId>sample</artifactId>
    <version>1.0</version>

    <properties>
        <kotlin.version>1.3.72</kotlin.version>
        <bytebuddy.version>1.10.9</bytebuddy.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy-dep</artifactId>
            <version>${bytebuddy.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jvmTarget>1.8</jvmTarget>
                    <args>
                        <arg>-java-parameters</arg>
                    </args>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.bytebuddy</groupId>
                <artifactId>byte-buddy-maven-plugin</artifactId>
                <version>${bytebuddy.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>transform</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <transformations>
                        <transformation>
                            <plugin>sample.MyPlugin</plugin>
                        </transformation>
                    </transformations>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

This is the line that will retain parameters. Project builds successfully without this line.
<arg>-java-parameters</arg>

Class1.kt (this one fails)
```
class Class1 {
    var name: String? = null
}
```

Class2.kt (this one succeeds)
```
class Class2 {
    var name: String? = null
        get() = field
        set(value) { field = value }
}
```

Class2 causes no errors, i believe this is because i have given the setter a parameter name.
The plugin itself does nothing.

```
override fun apply(builder: DynamicType.Builder<*>, typeDescription: TypeDescription, classFileLocator: ClassFileLocator
    ): DynamicType.Builder<*> {
        return builder
    }
```

The error output is as follows:

> mvn install
.........
........
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.192 s
[INFO] Finished at: 2020-04-22T19:31:34+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.bytebuddy:byte-buddy-maven-plugin:1.10.9:transform (default) on project sample: Failed to transform class files in C:\Users\MyUser\source\repos\untitled4\target\classes: Illegal parameter name of java.lang.String <set-?> for public final void sample.Class1.setName(java.lang.String) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I have attached a zip file with this sample.
Please let me know if i can be of further assistance.
This is currently a blocker on our project.

[sample.zip](https://github.com/raphw/byte-buddy/files/4518026/sample.zip)

**Comment by IceBlizz6** [comment]
Code fails at line 851 in net.bytebuddy.dynamic.scaffold.InstrumentedType

Based on javap the property setter parameter name is literally named "<set-?>"
```
public final void setName(java.lang.String);
    descriptor: (Ljava/lang/String;)V
    flags: (0x0011) ACC_PUBLIC, ACC_FINAL
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: aload_1
         2: putfield      #11                 // Field name:Ljava/lang/String;
         5: return
      LineNumberTable:
        line 4: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       6     0  this   Lsample/Class1;
            0       6     1 <set-?>   Ljava/lang/String;
    RuntimeInvisibleParameterAnnotations:
      parameter 0:
        0: #7()
          org.jetbrains.annotations.Nullable
    MethodParameters:
      Name                           Flags
      <set-?>
```

This makes the method isValidIdentifier(String identifier) on line 973 return false as it does not consider this name a valid identifier. Which leads to the exception being thrown.

I believe the fix is to make the "<set-?>" name allowed as an exception in the isValidIdentifier method.
Would make a pull request of this myself, but i am unable to build the project in IntelliJ.

**Comment by raphw** [comment]
The problem here is that it's illegal according to the JVM specification. 

What you can however do is to disable validation alltogether by implementing your own entry point: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/build/EntryPoint.java#L70 - simply set `byteBuddy.with(TypeValidation.DISABLED)`.

At the same time, I'd report this as a bug to the Kotlin team.

**Comment by IceBlizz6** [comment]
@raphw 
Are you saying the parameter name "<set-?>" is illegal?
In that case i will certainly try to report this to the Kotlin team, do you have a reference for this?

**Comment by raphw** [comment]
It's my understanding that it's not a valid identifier name according to the spec but the JVM tolerates a lot. Typically, this can however confuse tools and the reflection API which I consider it wrong to use such names despite the JVM's lazy resolution and therefore tolerance.

I think it's fair to bring it up for these reasons to see what the Kotlin team thinks of this choice, maybe they want to change it.

For you, I'd suggest enabling "JVM mode" by disabling type validation.

**Comment by IceBlizz6** [comment]
Created an issue for the Kotlin team here.
https://youtrack.jetbrains.com/issue/KT-38547

**Comment by IceBlizz6** [comment]
@raphw Looks like we got a response from the Kotlin team now.
I would recommend that you visit the link above to read it.

As i understand it, there is a list of certain special characters that is not allowed, like forward slash, semicolon and so forth. But it doesn't look like < and - is on that list.
I will disable the validation as you are recommending here, However i will also ask you to reconsider the implementation of the validation.

**Comment by raphw** [comment]
I use Java's own API to determine if something is a valid identifier: `Character.isJavaIdentifierPart`. It returns `false` for `-` which is also why Byte Buddy rejects it.

**Comment by zambrovski** [comment]
Hi,

the same problem seem to happen with names of methods generated by the Kotlin compiler for property getters and setters.

    data class Foo(val bar: String)

will result in something like this in Java:

    class Foo {
       final String bar;

       Foo(String value) {
          this.bar = value;
       }

       public String getBar-ylcku() {
          return bar;
       }
    }

and `net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated (InstrumentedType.java:1743)` fails saying that the method name is illegal.

Is there any simple "plug-in" solution for working with Kotlin?

**Comment by patschl** [comment]
Hey, sorry to push this rather old issue, but which version will contain this `validated` flag? The next `1.12.x` release or `1.13.x`?

**Comment by raphw** [comment]
Should be released as of this week.

**Comment by zambrovski** [comment]
Hi, 

does 1.12.18 contain the `validated` flag? 
Can't find it so far...

Cheers,

Simon

**Comment by patschl** [comment]
No, it has not yet been released. Should be coming in the next release according to raphw

**Comment by raphw** [comment]
It's released:

```xml
<initialization>
  <validated>false</validated>
</initialization>
```

**Comment by zambrovski** [comment]
Great! 
Thanks a lot!

The problem with Kotlin data classes access is gone. 
This issue is then solved and might be closed?
