### ISSUE TITLE
Figure out if a transformation was successful

### ISSUE THREAD

**Issue by joshiste** [raphw/byte-buddy#844]
Is there some way to figure out if the transformation was successful using the api?

currently I use the `.with(AgentBuilder.Listener.StreamWriting.toSystemOut())` and look onto my console if there is an error (e.g. TypeDefinition for advice class not found). 

I'd like to throw in error if that happens - so is there some (easy) way to figure out if the transformation was successful or not?

**Comment by raphw** [comment]
Where would you want to throw an error? In the user thread loading a class? This is not possible. The JVM implements the class file transformation API to suppress any errors that are thrown.

**Comment by joshiste** [comment]
> Where would you want to throw an error?

I would like to throw the error in the thread calling the `new AgentBuilder.Default().....transform(...).installOn(instrumentation)`.

> In the user thread loading a class? This is not possible. The JVM implements the class file transformation API to suppress any errors that are thrown.

When I implement a `AgentBuilder.Listener` ... would it be able to track the error?

**Comment by joshiste** [comment]
thanks!
