### ISSUE TITLE
Is there a reason AgentProvider is protected?

### ISSUE THREAD

**Issue by Vampire** [raphw/byte-buddy#846]
I've seen `net.bytebuddy.agent.ByteBuddyAgent.AgentProvider` is protected and its use totally encapsuled.

Is there a reason to now open it to `public`, so that one for example could use `net.bytebuddy.agent.ByteBuddyAgent.AgentProvider.ForByteBuddyAgent` to get the path of the ByteBuddy agent, e. g. to automatically start a new JVM with the agent attached, or to tell users to start with that jar file as agent to make things work?

It might also be nice to have `attach` and `attachNative` variants where you could supply an own `AgentProvider` instance that does some custom logic, like building the to-be-attached agent jar on-the-fly or similar, just like the `ForByteBuddyAgent` one does.

It might even be an additional option to provide from ByteBuddy side the logic to construct such an on-the-fly agent jar by supplying the agent class, the manifest entries that should be set and the classes to include in the JAR, possibly including a `ClassFileLocator` for how to get the bytes to put in the JAR for the classes.

**Comment by raphw** [comment]
Sorry for the late reply.

I am not sure what kind of functionality you are trying to implement that is currently impossible. If you are attaching to a foreign JVM, the agent needs to end up on the file system eventually. Therefore, you should just create a jar file with the particular agent you want to attach and use the corresponding API to attach this file. The `AgentProvider` abstraction is more meant to support self-attach and attach to a foreign agent internally without having to duplicate too much code.

As for resolving the current path: I am still hoping that there are better ways in the future so I'd like to avoid exposing the code to being able to easily change it in the future. I think it'd be better to copy the code.
