### ISSUE TITLE
Difference between Advice as AsmVisitorWrapper and Implementation

### ISSUE THREAD

**Issue by Vampire** [raphw/byte-buddy#847]
This is mainly a comprehension question.
Why does this properly work:
```java
.type(is(String.class))
.transform((builder, typeDescription, classLoader, module) -> builder
        .visit(Advice
                .to(Test.class)
                .on(named("replaceAll").and(takesArguments(String.class, String.class))))
);
```
while this does not:
```java
.type(is(String.class))
.transform((builder, typeDescription, classLoader, module) -> builder
        .method(named("replaceAll").and(takesArguments(String.class, String.class)))
        .intercept(Advice.to(Test.class))
);
```
Without `disableClassFormatChanges()` the latter says `java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method`, with `disableClassFormatChanges()` it says `java.lang.IllegalStateException: Cannot call super (or default) method for public java.lang.String java.lang.String.replaceAll(java.lang.String,java.lang.String)`

**Comment by raphw** [comment]
When visiting, you are decorating any method while leaving its original implementation intact. With an interception, you replace the original method; in your example with a stub method wrapping your visitor wrapper.

**Comment by Vampire** [comment]
I still don't get how replacing a method (I hope with one with the same binary signature) will either add a new method or try to call a super method.
Would you mind a little more detail?

**Comment by gaoxingliang** [comment]
> When visiting, you are decorating any method while leaving its original implementation intact. With an interception, you replace the original method; in your example with a stub method wrapping your visitor wrapper.

Clear explanation. Thanks

**Comment by raphw** [comment]
Is this still an issue? Sorry for overlooking this. Please create a new issue with the most recent release in use if you are still facing issues.
