### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by amar1019** [raphw/byte-buddy#848]
Hi @raphw ,
When i include logger inside Advice class , i am getting NoClassDefFoundError for that advice class. Do u know what is the reason. But when i remove it i dont get that error.

**Comment by raphw** [comment]
An advice is inlined (copy-pasted) into the target method. When you apply advice and reference a field of the class, this class cannot necessarily be resolved by the target class's class loader and you'll receive this error.

**Comment by amar1019** [comment]
Okay. But why is it that it happens only with some of the advice classes. Also,
public void onMethodEnter(){

    try{
      logger.debug("xxxxxxxx");
       .......
    } catch(Exception ex){
       logger.error("XXXXXXXXXX");
    }

}
 When i remove debug() it works. It works with error()
logger.error() is not creating the exception

**Comment by raphw** [comment]
The question you have to ask yourself: would it compile if you copied the content of your advice to the beginning and the end of your method. If not, you'll get a `NoXXXDefError`.

**Comment by yaohwu** [comment]
@raphw Since an advice is inlined (copy-pasted) into the target method.
And it works using this method to load FooAdvice class;
```
  new AgentBuilder.Transformer.ForAdvice()
                                    .include(classloader_which_can_load_FooAdvice)
                                    .advice(named("Foo"),
                                            FooAdvice.class.getName()
                                    )
```
But it will occur NoClassDefFoundError because the classloader of target class cannot load some classes using in FooAdvice class.
```
@Advice.OnMethodEnter()
        private static void enter() {
            // xxx
            TimeClassWhichCannotLoadByDefaultClassLoader  o = new TimeClassWhichCannotLoadByDefaultClassLoader();
            // xxx
        }
```
Is there any way to indicate the classloader of classes using in FooAdvice ?

**Comment by raphw** [comment]
No, since the code is copy-pasted, you cannot imply an execution class loader, it is simply not possible since the loaded class is fixed. If you want to use a globally visible class in the advice method, you'd need to inject it into the class loader.

**Comment by yaohwu** [comment]
That's what I thought. 
Thank you
