### ISSUE TITLE
instrument micronaut's lazy-loaded classes using ByteBuddyAgent

### ISSUE THREAD

**Issue by ratcashdev** [raphw/byte-buddy#849]
I am using micronaut-core as a platform. I'd like to use the ByteBuddyAgent to apply runtime-trace logging. However, I am facing issues because my instrumentations are not getting applied when I start my app like this:
```
java -javaagent:my-logging-agent.jar -Druntime.event.log.filename=/tmp/runtime-trace.log -jar my-app-shadow.jar
```

Interceptors are created like this:
```
public static AgentBuilder setupPlaced(final AgentBuilder agentBuilder) {
        return agentBuilder.type(isSubTypeOf(MyBusinessClass.class))
                .transform((builder, typeDescription, classLoader, javaModule)
                        -> builder
                            .visit(to(MyInterceptor.class).on(named("methodName")))
                );
    }
```
However, they DO get applied, when activating the agent programmatically (e.g. inside a test case). Can you please kindly suggest how to go around these kind of situations?

**Comment by ratcashdev** [comment]
For reference, it seem that while during test-case execution `MyBusinessClass` is properly discovered and instrumented. However, when the full app is started with the `-javaagent` argument, only `MyBusinessClass$1` is discovered and never `MyBusinessClass`. Furthermore, MyBusinessClass$1 is not `subTypeOf` MyBusinessClass.

**Comment by ratcashdev** [comment]
Related (probably more detailed) issue: https://github.com/micronaut-projects/micronaut-core/issues/3110
Tested with ByteBuddy 1.9.8 up to 1.10.9, all giving the same result.

**Comment by ratcashdev** [comment]
solved. the preMain() method was not applying transformations, why the agentMain was.

**Comment by raphw** [comment]
Glad you found out and thanks for closing the ticket!
