### ISSUE TITLE
Cannot change '@AllArguments Object[] args' from helper method in another class

### ISSUE THREAD

**Issue by kriegaex** [raphw/byte-buddy#850]
I do not have much experience in ByteBuddy, just started this week. Please bear with me. I searched the code base (especially tests) and issue list (also closed ones) here as well as StackOverflow. My situation is this:

I am instrumenting JRE class `String` using an `Advice` and a transformator attached during runtime via `ByteBuddyAgent`. The advice as such works fine, so there are no problems with redefining the bootstrap class.

Now I want to generalise my advice, using it as a wrapper and dispatching to helper methods in other classes and it works 99% fine. There is just one edge case which I cannot get working:
  * My `@OnMethodEnter` advice has one parameter `@AllArguments(readOnly = false, typing = DYNAMIC) Object[] args` which I forward to the helper method in the other class.
  * If I change any value in the arguments array e.g. via `args[0] = newValue`, the change is not reflected in the advice after the helper method returns to it, i.e. the helper method cannot change the parameter list before the wrapped method is called after exiting the advice.
  * Besides, even if I change the value in the advice method itself, this does not work. I really have to create new array via `args = new Object[] { newValue, args[1] };` if I want to manipulate the method parameters before proceeding to the target method.
  * But even that approach does not work in a helper class. I could not find a way to reflect the arguments changes back into the actual static advice method and from there on to the target method.

One notable problem I had was making the helper class known to the bootstrap classloader. I solved that via something like this:

```java
Map<TypeDescription, byte[]> types = new HashMap<>();
Stream
  .of(StringReplaceAllHelper.class)  // the helper class
  .forEach(clazz -> types.put(
    new TypeDescription.ForLoadedType(clazz),
    ClassFileLocator.ForClassLoader.read(clazz)
  ));
ClassInjector.UsingUnsafe.Factory factory = ClassInjector.UsingUnsafe.Factory.resolve(instrumentation);
factory.make(null, null).inject(types);

AgentBuilder.Identified.Extendable agentBuilder = new AgentBuilder.Default()
  .disableClassFormatChanges()
  .ignore(none())
  .with(new AgentBuilder.InjectionStrategy.UsingUnsafe.OfFactory(factory))
  .with(RETRANSFORMATION)
  // (...)
```

I also had to put both the `byte-buddy` and `byte-buddy-agent` dependencies on the boot classpath when running this from a JUnit test. Strangely, when running from an application class and not from a test class, I do not need to change the boot classpath.

But as I said, the program is running, the instrumentation happening and the advice does what it should and can even communicate data on to the corresponding `@OnMethodExit` advice. The only thing not working is the `@AllArguments` part.

Normally when I manipulate entries of an `Object[]` (or whatever type of array) in a called method, the calling method can see the changes. Is this some kind of problem with the helper class being resolved again in the boot classloader? Why can I communicate the array into the helper method but not back out?

**Comment by kriegaex** [comment]
I also verified that with normal Java method calls the array's object identify does not change:

```text
args = [Ljava.lang.Object;@7ef20235 -> [foo, bar]  // outer method, before calling helper
args = [Ljava.lang.Object;@7ef20235 -> [foo, bar]  // helper method, before changing array element
args = [Ljava.lang.Object;@7ef20235 -> [foo, XXX]  // helper method, after changing array element
args = [Ljava.lang.Object;@7ef20235 -> [foo, XXX]  // outer method, after returning from helper
```

But when calling a helper method from my advice:

```text
args = [Ljava.lang.Object;@ffaa6af  -> [foo, bar]  // outer method, before calling helper
args = [Ljava.lang.Object;@316bcf94 -> [foo, bar]  // helper method, before changing array element
args = [Ljava.lang.Object;@316bcf94 -> [foo, XXX]  // helper method, after changing array element
args = [Ljava.lang.Object;@6404f418 -> [foo, bar]  // outer method, after returning from helper
```

As you can see, the `args` array gets a copy, not the original array instance. Even more strangely, the array instance changes one more time when we are back in the advice method. I must be doing something phenomenally stupid, but I don't know what.

**Comment by kriegaex** [comment]
Okay, here is an [MCVE](https://stackoverflow.com/help/mcve). I removed pretty much everything that was "special" like trying to manipulate already loaded JRE classes or inject classes into the boot loader. The same problem happens with this simple setup:

```java
package de.scrum_master.agent.bytebuddy;

public class DemoTarget {
  String text;

  public DemoTarget(String text) {
    this.text = text;
  }

  public String replaceAll(String regex, String replacement) {
    return text.replaceAll(regex, replacement);
  }
}
```

```java
package de.scrum_master.agent.bytebuddy;

import java.util.Arrays;

public class AdviceHelper {
  public void before(Object[] args) {
    System.out.println("args = " + args + " -> " + Arrays.deepToString(args));
    args[1] = "XXX";
    System.out.println("args = " + args + " -> " + Arrays.deepToString(args));
  }
}
```

```java
package de.scrum_master.agent.bytebuddy;

import net.bytebuddy.asm.Advice;

import java.util.Arrays;

import static net.bytebuddy.implementation.bytecode.assign.Assigner.Typing.DYNAMIC;

public class DemoAspect {
  @Advice.OnMethodEnter
  public static String before(
    @Advice.AllArguments(readOnly = false, typing = DYNAMIC) Object[] args
  ) {
    System.out.println("args = " + args + " -> " + Arrays.deepToString(args));
    new AdviceHelper().before(args);
    System.out.println("args = " + args + " -> " + Arrays.deepToString(args));
    return "proceed";
  }
}
```

```java
package de.scrum_master.agent.bytebuddy;

import net.bytebuddy.agent.ByteBuddyAgent;
import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.agent.builder.AgentBuilder.InstallationListener;
import net.bytebuddy.agent.builder.AgentBuilder.Listener;
import net.bytebuddy.agent.builder.AgentBuilder.RedefinitionStrategy;
import net.bytebuddy.asm.Advice;

import java.util.Arrays;

import static net.bytebuddy.agent.builder.AgentBuilder.RedefinitionStrategy.RETRANSFORMATION;
import static net.bytebuddy.matcher.ElementMatchers.is;
import static net.bytebuddy.matcher.ElementMatchers.named;

public class Demo {
  public static void main(String[] args) {
    normalArrayManipulation();
    doInstrumentation();
  }

  private static void normalArrayManipulation() {
    Object[] args = new Object[] { "foo", "bar" };
    System.out.println("args = " + args + " -> " + Arrays.deepToString(args));
    new AdviceHelper().before(args);
    System.out.println("args = " + args + " -> " + Arrays.deepToString(args));
  }

  private static void doInstrumentation() {
    ByteBuddyAgent.install();
    new AgentBuilder.Default()
      .disableClassFormatChanges()
      .with(RETRANSFORMATION)
      .with(RedefinitionStrategy.Listener.StreamWriting.toSystemError())
      .with(Listener.StreamWriting.toSystemError().withTransformationsOnly())
      .with(InstallationListener.StreamWriting.toSystemError())
      .type(is(DemoTarget.class))
      .transform((builder, typeDescription, classLoader, module) -> builder
        .visit(Advice.to(DemoAspect.class).on(named("replaceAll")))
      ).installOnByteBuddyAgent();
    new DemoTarget("Your foo is very strong").replaceAll("foo", "bar");
  }
}
```

Console log:

```text
args = [Ljava.lang.Object;@4b67cf4d -> [foo, bar]
args = [Ljava.lang.Object;@4b67cf4d -> [foo, bar]
args = [Ljava.lang.Object;@4b67cf4d -> [foo, XXX]
args = [Ljava.lang.Object;@4b67cf4d -> [foo, XXX]
[Byte Buddy] BEFORE_INSTALL net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer@1d057a39 on sun.instrument.InstrumentationImpl@26be92ad
[Byte Buddy] REDEFINE BATCH #0 [1 of 1 type(s)]
[Byte Buddy] TRANSFORM de.scrum_master.agent.bytebuddy.DemoTarget [sun.misc.Launcher$AppClassLoader@18b4aac2, null, loaded=true]
[Byte Buddy] REDEFINE COMPLETE 1 batch(es) containing 1 types [0 failed batch(es)]
[Byte Buddy] INSTALL net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer@1d057a39 on sun.instrument.InstrumentationImpl@26be92ad
args = [Ljava.lang.Object;@1e6454ec -> [foo, bar]
args = [Ljava.lang.Object;@b62d79 -> [foo, bar]
args = [Ljava.lang.Object;@b62d79 -> [foo, XXX]
args = [Ljava.lang.Object;@6631f5ca -> [foo, bar]```

**Comment by raphw** [comment]
So, advice is a nice trick but you do indeed need to assign the entire array to make this work. Here is why:

Byte Buddy finds byte code locations where you access an annotated variable. It then replaces the location with an instruction that represents what the annotation indicates. So if you do `Object o = args`, then Byte Buddy reads all parameters into an array and replaces `args` by it. If you write `args[0]`, in byte code this is two instructions. Again, Byte Buddy replaces the `args` bit but after being read, the array is a value without attachment to the original arguments.

The only way for setting an argument is by assigning `args` a value where Byte Buddy can replace this byte code instruction. Again, the array object is not tagged in any particular way.

**Comment by kriegaex** [comment]
@raphw, thanks for the explanation. My suggestions:
* I think this caveat should be documented in the Javadocs of `Advice.AllArguments` and `Advice.Argument`. Otherwise nobody knows how to change arguments in a before advice before proceeding.
* It would also be good to explain in in the `Advice` Javadoc
* as well as maybe in the tutorial on the website.
* Maybe you also have an FAQ list, I do not remember to have seen one.
* If there are no automatic tests or other example code covering this situation, I think you should create some.

Unfortunately, in your answer you did not tell me what I should do instead. I am still waiting for your suggestion.

I came up with two approaches:
  1. Copy `args` into a `SortedMap<Integer, Object>` with the keys being the original array indexes. Hand the map over to the helper method which can easily use `argsMap.put(index, newValue)` in order to update the map. After returning, copy the map contents into a newly created `Object[] returnedArgs` and finally issuing `args = returnedArgs`. This works, even if it is a bit ugly with loops and all.
  2. Just use `Object[] argsCopy = Arrays.copyOf(args, args.length)`, hand the `argsCopy` over to the helper method (which can keep the `Object[] args` signature and does not need to use a map), let the helper manipulate the copied array and finally assign `args = argsCopy` in order to make ByteBuddy notice that the argument list was changed and it should do its magic.

Both approaches work in my real code manipulating JRE method `String.replaceAll`. But I was very surprised to find the array copying approach failing in my stripped down minimal example from above. If I change `DemoAspect` to:

```java
package de.scrum_master.agent.bytebuddy;

import net.bytebuddy.asm.Advice;

import java.util.Arrays;

import static net.bytebuddy.implementation.bytecode.assign.Assigner.Typing.DYNAMIC;

public class DemoAspect {
  @Advice.OnMethodEnter
  public static String before(
    @Advice.AllArguments(readOnly = false, typing = DYNAMIC) Object[] args
  ) {
    Object[] argsCopy = Arrays.copyOf(args, args.length);
    System.out.println("argsCopy = " + argsCopy + " -> " + Arrays.deepToString(argsCopy));
    new AdviceHelper().before(argsCopy);
    System.out.println("argsCopy = " + argsCopy + " -> " + Arrays.deepToString(argsCopy));
    args = argsCopy;
    System.out.println("args = " + args + " -> " + Arrays.deepToString(args));
    return "proceed";
  }
}
```

I see this exception when running `Demo`:
```text
args = [Ljava.lang.Object;@4b67cf4d -> [foo, bar]
args = [Ljava.lang.Object;@4b67cf4d -> [foo, bar]
args = [Ljava.lang.Object;@4b67cf4d -> [foo, XXX]
args = [Ljava.lang.Object;@4b67cf4d -> [foo, XXX]
[Byte Buddy] BEFORE_INSTALL net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer@1d057a39 on sun.instrument.InstrumentationImpl@26be92ad
[Byte Buddy] REDEFINE BATCH #0 [1 of 1 type(s)]
[Byte Buddy] TRANSFORM de.scrum_master.agent.bytebuddy.DemoTarget [sun.misc.Launcher$AppClassLoader@18b4aac2, null, loaded=true]
[Byte Buddy] REDEFINE ERROR #0 [1 of 1 type(s)]
java.lang.IllegalStateException: Error invoking java.lang.instrument.Instrumentation#retransformClasses
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6877)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:7148)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:6993)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4855)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:9463)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9384)
	at net.bytebuddy.agent.builder.AgentBuilder$Default.installOnByteBuddyAgent(AgentBuilder.java:9395)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOnByteBuddyAgent(AgentBuilder.java:10993)
	at de.scrum_master.agent.bytebuddy.Demo.doInstrumentation(Demo.java:40)
	at de.scrum_master.agent.bytebuddy.Demo.main(Demo.java:19)
Caused by: java.lang.VerifyError
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6869)
	... 9 more
[Byte Buddy] REDEFINE COMPLETE 1 batch(es) containing 1 types [1 failed batch(es)]
[Byte Buddy] INSTALL net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer@1d057a39 on sun.instrument.InstrumentationImpl@26be92ad
```

I use JDK 1.8.0_211  64-bit on Windows 10. This looks like a bug.

Rafael, I would be very grateful if you would actually run my code and suggest a stable, canonical solution. You often ask for minimal running sample code in issue comments here. I gave you one and would appreciate your help also beyond the technical background you explained.

**Comment by kriegaex** [comment]
**Update:**  Another workaround which does not yield a `VerifyError` during transformation is this:

```java
package de.scrum_master.agent.bytebuddy;

import net.bytebuddy.asm.Advice;

import java.util.Arrays;

import static net.bytebuddy.implementation.bytecode.assign.Assigner.Typing.DYNAMIC;

public class DemoAspect {
  @Advice.OnMethodEnter
  public static String before(
    @Advice.AllArguments(readOnly = false, typing = DYNAMIC) Object[] args
  ) {
    System.out.println("args = " + args + " -> " + Arrays.deepToString(args));
    Object[] argsCopy = new Object[args.length];
    System.arraycopy(args, 0, argsCopy, 0, args.length);
    // This leads to a VerifyError during transformation
//    Object[] argsCopy = Arrays.copyOf(args, args.length);
    System.out.println("argsCopy = " + argsCopy + " -> " + Arrays.deepToString(argsCopy));
    new AdviceHelper().before(argsCopy);
    System.out.println("argsCopy = " + argsCopy + " -> " + Arrays.deepToString(argsCopy));
    args = argsCopy;
    System.out.println("args = " + args + " -> " + Arrays.deepToString(args));
    return "proceed";
  }
}
```

The console log now looks as expected:

```text
args = [Ljava.lang.Object;@4b67cf4d -> [foo, bar]
args = [Ljava.lang.Object;@4b67cf4d -> [foo, bar]
args = [Ljava.lang.Object;@4b67cf4d -> [foo, XXX]
args = [Ljava.lang.Object;@4b67cf4d -> [foo, XXX]
[Byte Buddy] BEFORE_INSTALL net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer@1d057a39 on sun.instrument.InstrumentationImpl@26be92ad
[Byte Buddy] REDEFINE BATCH #0 [1 of 1 type(s)]
[Byte Buddy] TRANSFORM de.scrum_master.agent.bytebuddy.DemoTarget [sun.misc.Launcher$AppClassLoader@18b4aac2, null, loaded=true]
[Byte Buddy] REDEFINE COMPLETE 1 batch(es) containing 1 types [0 failed batch(es)]
[Byte Buddy] INSTALL net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer@1d057a39 on sun.instrument.InstrumentationImpl@26be92ad
args = [Ljava.lang.Object;@1a4013 -> [foo, bar]
argsCopy = [Ljava.lang.Object;@306f16f3 -> [foo, bar]
args = [Ljava.lang.Object;@306f16f3 -> [foo, bar]
args = [Ljava.lang.Object;@306f16f3 -> [foo, XXX]
argsCopy = [Ljava.lang.Object;@306f16f3 -> [foo, XXX]
args = [Ljava.lang.Object;@702b8b12 -> [foo, XXX]
```

Why does it make a difference for ByteBuddy if I write
```java
Object[] argsCopy = Arrays.copyOf(args, args.length);
```
or
```java
Object[] argsCopy = new Object[args.length];
System.arraycopy(args, 0, argsCopy, 0, args.length);
```

**Comment by Vampire** [comment]
> Byte Buddy finds byte code locations where you access an annotated variable. It then replaces the location with an instruction that represents what the annotation indicates.

@raphw wouldn't it be feasible to recognize a method call where the annotated array is given as arguments and then after the method call generate the code that sets the arguments from that array just as if you would have encountered an `args = ...` instruction?

**Comment by raphw** [comment]
It would require backtracking within the method what would make things rather expensive, therefore I want to avoid it. What you can always do is to implement your own binding for an annotation and wrap your own logic around it.

I'll look into the verifier error. That should not happen.

**Comment by kriegaex** [comment]
I just wanted to confirm that using the latest 1.10.11-SNAPSHOT in which you fixed another `VerifyError` does not have any influence on this one. I did not expect it to anyway, but I gave it a spin because I had the project open anyway.

**Comment by raphw** [comment]
I did not expect that, but I'll look into the one you found next!

**Comment by raphw** [comment]
I just found the problem here which should be fixed in https://github.com/raphw/byte-buddy/commit/fa9533ff9a5ff5c523955476703b4e074a12b7e5.

**Comment by kriegaex** [comment]
A quick test with the above MCVE after a local build shows that now it works with

```java
Object[] argsCopy = Arrays.copyOf(args, args.length);
```
instead of

```java
Object[] argsCopy = new Object[args.length];
System.arraycopy(args, 0, argsCopy, 0, args.length);
```

Thanks, @raphw! :-)

**Comment by kriegaex** [comment]
After upgrading to 1.10.11 and removing one of my TODOs in my project's source code, I just noticed that this ticket has no milestone. Maybe you want to add one.
