### ISSUE TITLE
maven plugin : How to get a path to a currently processed class file ?

### ISSUE THREAD

**Issue by constantOut** [raphw/byte-buddy#852]
Hey, as far as I understand first source code is compiled into a class only then would maven plugin go over generated classes to find those that match particular plugin.
I need to put new types in same package as the old types - how do I achieve this ?

**Comment by constantOut** [comment]
The only idea that comes to mind at the moment is to assume the language used is Java and the module that have this .class file should also have a path like "$rootPackageName\$packageName\$className.*"

**Comment by raphw** [comment]
You can add an auxiliary type to any type and it will be stored in the same base folder as the instrumented type. Byte Buddy is hiding the location to avoid that there needs to be on the file system. The build engine can support any form of store.

**Comment by constantOut** [comment]
Builder from ```
@Override
    public Builder<?> apply(Builder<?> builder, TypeDescription typeDescription, ClassFileLocator classFileLocator)
``` doesn't have `makeInterface` method, so I'm creating a new one with `new ByteBuddy()`
I want to add those auxiliary types to package named '$originalTypeName.schema'
And the builder parameter doesn't have makePackage.

**Comment by constantOut** [comment]
Do you suggest something like : `declaredTypes(TypeDescription... type)` ?
It won't work for my case because I need to generate new interfaces and then make instrumented type implement those interfaces.

**Comment by constantOut** [comment]
I've implemented search for a file by java package naming convention.
