### ISSUE TITLE
How do I rise compilation error from ByteBuddy maven plugin ?

### ISSUE THREAD

**Issue by constantOut** [raphw/byte-buddy#853]
```
    @Override
    public Builder<?> apply(Builder<?> builder, TypeDescription typeDescription, ClassFileLocator classFileLocator) {
``` 
doesn't throw any exceptions, what if my plugin cannot process particular annotation and needs to inform user about it ?

**Comment by raphw** [comment]
You can throw an exception. If fail-fast is enabled, the instrumentation is aborted immediately.
