### ISSUE TITLE
Intellij doesn't see generated classes 

### ISSUE THREAD

**Issue by constantOut** [raphw/byte-buddy#855]
I understand this is not a bug in byte-buddy, but it's related to developer experience.
If I build a module that is being instrumented with maven it gets cached in local maven repo - then if I remove it from top level maven module - Intellij would analyze jar from local repo and all generated types are visible.
Do you happen to know how I can force this behavior without adding/removing module ?

**Comment by raphw** [comment]
Not much Byte Buddy can do as far as I would understand. Maybe if you enable auto reimport? I'd ask at JetBrains how this can be addressed.

**Comment by constantOut** [comment]
Fixed. Not related to ByteBuddy.
