### ISSUE TITLE
"Broken pipe" error when using VirtualMachine API emulation

### ISSUE THREAD

**Issue by eyalkoren** [raphw/byte-buddy#856]
We provide a utility for remote attachment of our agent that relies on ByteBuddy's `VirtualMachine` emulation feature. The current version we use is greater than `1.10.1`, where there is a mention of "broken pipe" [in the release notes](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.10.1). 

We have a user reporting getting the `broken pipe` error using the following environment:
- Oracle JVM 1.8.0_74 (using the same JRE to run the app and the attachment utility)
- Centos Linux release 7.4
- SELinux is disabled
- Running both the app and the attachment utility as root

Here is the relevant part of the stack trace: 
```
Caused by: com.sun.jna.LastErrorException: [32] Broken Pipe
at com.sun.jna.Native.invokeInt(Native Method)
at com.sun.jna.Function.invoke(Function.java:426)
at com.sun.jna.Function.invoke(Function.java:361)
at com.sun.jna.Library$Handler.invoke(Library.java:265)
at net.bytebuddy.agent.$Proxy0.write(Unknown Source)
at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket.write(VirtualMachine.java:735)
at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket.write(VirtualMachine.java:686)
at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$OnPersistentByteChannel.execute(VirtualMachine.java:592)
at net.bytebuddy.agent.VirtualMachine$ForHotSpot.load(VirtualMachine.java:361)
at net.bytebuddy.agent.VirtualMachine$ForHotSpot.loadAgent(VirtualMachine.java:335)
```

Do you know what could cause this kind of errors ?
- from the stack trace, creating the temporary file in working directory and opening the socket is not the issue
- issue is triggered when trying to write to the socket using JNA, is `broken pipe` a generic issue for JNA, or does it provide any meaningful indication about the root cause ?

**Comment by raphw** [comment]
Yes, before I reused pipes after any message where the server closes them after receiving just one. Therefore I needed to recreate them what I tested.

A broken pipe indicates that the server errored and closed the pipe before a connection could be established.

Does "normal" attach work for this user? It might just be that the JVM does not support it.

**Comment by eyalkoren** [comment]
With a "normal" attach they get `java.io.IOExecption: well-known file is not secure`. Looking it up, it seems to be a problem with mismatching user permissions. They _are_ using the same user for both JVMs, but this user is root and I found that in some systems people got that with root, so I asked them to try with a different user. 
Do you think it may be related?

> Ideally, you also try with a recent version of Byte Buddy.

My bad, we are using 1.10.8, fixing the description.

**Comment by raphw** [comment]
Sounds like it's the same issue. To be honest, I did not really reimplement the error handling but throw raw exceptions. The permission problem sounds familiar. With root, sometimes the chmod is wrong for the file where it should be *600* but might include the root user.

**Comment by eyalkoren** [comment]
OK, thanks! If they manage to attach without emulation when using a different user, we'll ask them to do the same with emulation and see if it works. I will update here.

**Comment by raphw** [comment]
They could also try to set the permissions of the socket file manually.

Is this on Docker?

**Comment by eyalkoren** [comment]
> They could also try to set the permissions of the socket file manually.

Is that the `.attach_pid<pid>` file?

**Comment by raphw** [comment]
Yes, would be interesting to check its chmod for being 600.
