### ISSUE TITLE
how to modify argument during bootstrap inject

### ISSUE THREAD

**Issue by zhang98722** [raphw/byte-buddy#860]
hi raphw,sorry to bother you,but i meet some problems and they stuck me for days.

im just trying to inject **java.util.concurrent.AbstractExecutorService** to enhance muti threads switch context log,my plan is to use interceptor or advice enhance the **submit** or  **newTaskFor**.

the current situation is i need to modify the argument, wrap it and insert the current context , so i could transport context to the thread in thread pool, as bellow:

```
 public static class EnhancedCallable implements Callable{

        Callable                    delegate;
        TraceContext.Snapshot       snapshot;

        public EnhancedCallable(Callable callable, TraceContext.Snapshot snapshot){
            this.delegate = callable;
            this.snapshot = snapshot;
        }

        @Override
        public Object call() throws Exception {
            if(snapshot!=null){
                TraceContext.loadSnapshot(snapshot);
            }
            try {
                return delegate.call();
            }finally {
                TraceContext.clearContext();
            }
        }
    }
```

i use the agentbuild as bellow:

```
new AgentBuilder.Default(byteBuddy)
                .enableBootstrapInjection(instrumentation, Files.createTempDirectory("tmp").toFile())
                .ignore(nameStartsWith("net.bytebuddy.")
                        .or(nameStartsWith("org.slf4j."))
                        .or(nameStartsWith("org.apache.logging."))
                        .or(nameStartsWith("org.groovy."))
                        .or(nameContains("javassist"))
                        .or(nameContains(".asm."))
                        .or(nameStartsWith("sun.reflect"))
                        .or(ElementMatchers.<TypeDescription>isSynthetic()))
                .type(...)
                .transform(new Transformer())
                .with(new Listener())
                .installOn(instrumentation);
```

but when i tried to use advice to modify the argument with annotation
```
@Advice.Argument(value = 0, readOnly = false, typing = DYNAMIC) Object argument
```
 i always got the exception
```
ava.lang.IllegalStateException: Cannot define writable field access for java.lang.Object argument when using delegation
```
AllArgument is not work neither, seems its because the binding check failed but i dont know how to fix

the intercepter only provider the wrapped callable, i tried but not find a way to modify the argument

could you help me solve my problem?
thanks

**Comment by raphw** [comment]
It seems that you are using `@Advice.OnMethodXXX(inline = false)`. In this case, it is not possible to redefine an argument from within the advice as calls in Java pass a reference to the heap location by value. You need to inline to make this possible. It has nothing to do with bootstrap injection, it is a general limitation.

**Comment by zhang98722** [comment]
yes it is!!!
i read it somewhere ever
but i set it to true to help debug...
and forgot fix it then

really thanks

**Comment by zhang98722** [comment]
and i have another additional question
you can just ignore it and just close this issue if it cost you too much time

as i mentioned:
i was trying to intercept **java.util.concurrent.AbstractExecutorService**  to track thread switch things
but as this class loaded by bootstrap classloader
so i have to move the intercept things to a jar and loaded it by 
```
instrumentation.appendToBootstrapClassLoaderSearch
```
is there an easier way to do such things or just do it in application classloader?
it really cost me lots of time to move the dependences to bootstrap classloader and i have to keep the dependency update by myself

**Comment by raphw** [comment]
As said, it should not be necessary to inject anything into the bootstrap loader. Advice in a way copies and pastes your code to the target class. 

Are you having dependencies in your advice? Ideally, you avoid them and dispatch all interactions to some generic dispatcher in the boot loader what minimizes this effort.
