### ISSUE TITLE
How to change a single type/method modifier flag via transform API?

### ISSUE THREAD

**Issue by kriegaex** [raphw/byte-buddy#861]
I know I can use something like this for types:

```java
      .transform((builder, typeDescription, classLoader, module) ->
          builder
            // Remove 'final' modifier from classes
            .modifiers(typeDescription.getModifiers() & ~Modifier.FINAL)
            // Exclude non-final methods
            .ignoreAlso(not(isFinal()))
            // Remove 'final' modifier from methods
            .visit(new ModifierAdjustment()
              .withMethodModifiers(isFinal().and(isNative()), MethodManifestation.NATIVE)
              .withMethodModifiers(isFinal().and(isBridge()), MethodManifestation.BRIDGE)
              .withMethodModifiers(isFinal().and(not(isNative().or(isBridge()))), MethodManifestation.PLAIN))
      )
```

So for any given type I can just remove the final modifier via `.modifiers(typeDescription.getModifiers() & ~Modifier.FINAL)` without changing the other modifiers.

For methods I seem to need this workaround with all kinds of combinations of flags because I can only set an absolute combination of modifier flags, not a single bit of it. Am I understanding this correctly? I would like to have a means in the builder API to say: "just remove final and leave the rest unchanged". Is there some way to do a bit-wise operation like for the type? I do not know the API well enough. In Javassist I have convenience methods like `removeFinal()`.

**Comment by raphw** [comment]
Have a look at `Transformer.ForMethod.withModifiers(...)`.

The constants used by this API know the range of each modifier such that you only reset those modifiers that stand in direct conflict.

**Comment by kriegaex** [comment]
I am failing to see how this helps me. Could you please elaborate a bit and show how I would use that in my code?

**Comment by raphw** [comment]
You can use transformers in the `.method(...)` DSL where you can transform members in their entirety. But probably, the ASM approach is better suited for this use case.

**Comment by kriegaex** [comment]
Sorry, I must be too stupid or at least too slow on the uptake here. Please forgive me.

AFAIK `Transformer.ForMethod.withModifiers(...)` takes `ModifierContributor` arguments just like `.withMethodModifiers(...)` as its second argument, see my code snippet above. But where can I erase a single flag or make a bitwise logical operation with an existing one? Other than for the class where I can use `typeDescription.getModifiers()` to get the existing modifiers, I have no idea where to get the existing modifiers for the method from.

**Comment by raphw** [comment]
You can do it as follows:

```java
new ByteBuddy().rebase(Foo.class)
  .method(...).intercept(SuperMethodCall.INSTANCE) // do not change implementation
  .transform(Transformer.ForMethod.withModifiers(...)
```

For your case with an agent, it might however be easier to write a custom method visitor that only strips the modifiers directly on the visitor.

**Comment by kriegaex** [comment]
> For your case with an agent, it might however be easier to write a custom method visitor that only strips the modifiers directly on the visitor.

Which is exactly what I ended up doing. I still do not understand what too fill into the second "..." section, but let us just stop here. You are very busy and I am sure I will have more tricky questions for you in the future. 😉
