### ISSUE TITLE
Source JAR for ByteBuddy library out of sync with class JAR?

### ISSUE THREAD

**Issue by kriegaex** [raphw/byte-buddy#862]
For several versions of ByteBuddy (BB) when jumping to the BB source code from my own code via `Ctrl-B` in IntelliJ IDEA I see a warning `Library source does not match the bytecode for class X`:

![image](https://user-images.githubusercontent.com/1537384/81462880-c231ce80-91df-11ea-8dff-313d6c7dbb77.png)

I cannot be 100% sure that this is not a problem in IDEA itself, but I never experienced it with any library other than BB. So I would like to ask if there might be something in your build process which changes the sources after compilation in any way which could cause this warning. If so, could it be fixed? Thank you.

**Comment by raphw** [comment]
Byte Buddy adds equals and hashCode methods for its component using itself during build time. This way, I avoid the error-prone, manual implementation. The methods are used by Byte Buddy to improve its caching at runtime without having an effect on the physical outcome. Unfortunately, this leads to those IDEA hints.
