### ISSUE TITLE
shaded asm source only partially included in sources JAR

### ISSUE THREAD

**Issue by mirabilos** [raphw/byte-buddy#864]
In https://github.com/raphw/byte-buddy/issues/783#issuecomment-558815489 you said that you agree the shaded ASM source should be present in the sources JAR.

In 1.10.10 turns out that this is true only for asm, not asm-commons (compare sources JAR and binary JAR, `net/bytebuddy/jar/asm/` does not contain `commons/` in the former).

**Comment by raphw** [comment]
Thanks, I'll look into it. It should be there, indeed.

**Comment by mirabilos** [comment]
Rafael Winterhalter dixit:

>Thanks, I'll look into it. It should be there, indeed.

Thanks! I wish all projects would care about the sources to the
binaries they ship as much as you.

**Comment by raphw** [comment]
Should be fixed on master this time, I had to adjust the filter a bit. Well spotted!

**Comment by mirabilos** [comment]
Fixed on 1.0.11, thanks!
