### ISSUE TITLE
[Question] TypeMatcher for Thread class and subclasses?

### ISSUE THREAD

**Issue by drodriguezhdez** [raphw/byte-buddy#865]
ByteBuddy version: `1.10.10`.

I'm trying to instrument `java.lang.Thread` class and its subclasses using the following matcher:
* TypeMatcher: `hasSuperType(named("java.lang.Thread"))).or(named("java.lang.Thread")`
* CLMatcher: `any()`

The classes which extends `java.lang.Thread` are discovered by the agent but the `java.lang.Thread` itself is not.

If I use
* TypeMatcher: `named("java.lang.Thread")`
* CLMatcher: `any()`

The `java.lang.Thread` is discovered by the agent without problems.

Is there a mistake in the TypeMatcher I'm using? 
Is there any limitation in this kind of TypeMatchers?

Thanks!

**Comment by raphw** [comment]
No, they shoukd be equivalent, also because any class is a subtype of itself.

Did you check with a listener if the class is retransformed?

**Comment by drodriguezhdez** [comment]
Yes, I checked the listener and `Thread` class is not discovered. Thing is it seems this only happens if I execute the test using IntelliJ. 

Using `surefire` plugin, it seems that works as expected :S

**Comment by raphw** [comment]
I assume that IntelliJ injects its own agent for some stuff which disrupts the instrumentation process. Can you check the exact command line in IntelliJ on your test execution?

**Comment by drodriguezhdez** [comment]
Yeap, IntelliJ is using its own agent:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java -ea -Dscope.tests.running=true -Didea.test.cyclic.buffer.size=1048576 -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=49847:/Applications/IntelliJ IDEA CE.app/Contents/bin
```
The misleading indication is that I only have detected this issue with `Thread` class, but probably if I do more tests with `bootstrap` classloader classes, it will be the same.

**Comment by raphw** [comment]
I assume they do some things to monitor started thread what then gets in the way.

**Comment by drodriguezhdez** [comment]
Thanks for your help! I close the issue.
