### ISSUE TITLE
A question about byte-buddy method wrapping.

### ISSUE THREAD

**Issue by andresluuk** [raphw/byte-buddy#866]
A client of mine is having some issue with broken classes (through elastic-apm-agent-1.15.0.jar I think).
Currently I think byte-buddy might be related to the issue but I have some trouble reproducing it and need some advice from byte-buddy experts.

So the basic issue is that there is a weld proxy class that gets instrumented. (The proxy is from JDK6 class and running on JDK8)
Inside the class there is a method. That gets intercepted with:
@Advice.OnMethodEnter(suppress = Throwable.class)
and
@Advice.OnMethodExit(suppress = Throwable.class, onThrowable = Throwable.class)
now after the class is transformed. the method changes:
public brokenMethod() {
  .. stuff from OnMethodEnter ..
  original method body.
  .. stuff from OnMethodExit ..
}
Now when I try todo a similar thing in my machine I get:
public brokenMethod() {
  .. stuff from OnMethodEnter ..
  brokenMethod$orginal$xxx();
  .. stuff from OnMethodExit ..
}
public brokenMethod$orginal$xxx() { .. }

Currently I enable bytebuddy like this:
new AgentBuilder.Default()
    .type((any()))
    .transform((builder, typeDescription, classLoader, module) -> builder
        .method(ElementMatchers.nameStartsWith("brokenMethod"))
        .intercept(Advice.withCustomMapping().bind(new XXXMappingFactory()).to(XXXInstrumentation.class))
    ).installOn(instrumentation);
XXXInstrumentation contains the methods annotated with @Advice.OnMethodEnter and @Advice.OnMethodExit

I think I should add disableClassFormatChanges (ElasticApmAgent has a disableClassFormatChanges call) to escape the method move bytebuddy does?
But if I do it, I will not get no "$orginal" method (jei!) but the instrumentation is also skipped. i.e. no ".. stuff from OnMethodEnter ..".

What can I try to get byte-buddy insert the stuff before and after the method instead of moving the original body into a wrapper method?

**Comment by raphw** [comment]
You should use `Advice` as a decorator, not an interceptor:

```
Advice.withCustomMapping()
  .bind(new XXXMappingFactory())
  .to(XXXInstrumentation.class)
  .on(ElementMatchers.nameStartsWith("brokenMethod"))
```

**Comment by andresluuk** [comment]
Hi
Thanks for the suggestion. It helped me and I could reproduce the issue with byte-buddy.
I made an example application that showcases the issue I had with byte-buddy though elastic:
https://drive.google.com/file/d/1fTH83KG3ZnFPX2I6f03oLjQMhjqebw8N/view?usp=sharing
I hope you can access the example application
mvn package
mvn exec:exec 
will run the application with the custom bytebuddy and verification agent and there will be a failing log line:
Verify failed: xxxx
I think the issue is that Weld generates some weird stack maps (they dont fail on theire own) and after bytebuddy has gone over them they are broken.
Because JVM ignores broken stack from bytecode jdk 6 the class will not normally fail, but if you have another agent after bytebuddy then this will fail with asm if it tries to load the frames.
Like it happened to me when jrebel passed over the bytes.

**Comment by raphw** [comment]
You are right, the frames are invalid despite the computation by ASM. This
should not happen and is related to your use of the EXPAND_FRAMES flag. I
assume that ASM incorrectly expands the frame somewhere and this would be
need to fixed in the library. I reported the issue here:
https://gitlab.ow2.org/asm/asm/issues/317907

Am Di., 19. Mai 2020 um 08:40 Uhr schrieb Andres Luuk <
notifications@github.com>:

**Comment by andresluuk** [comment]
I saw Eric response, I think you need to extract the ASM code from inside bytebuddy also that breaks the Weld frames. Sadly because the insides of bytebuddy are complex, I can't do it myself.

**Comment by andresluuk** [comment]
Just curious. 
Internally byte-buddy uses EXPAND_FRAMES when it does it's transforms and then CheckClassAdapter as the last step to make sure that all bytes it generates are valid?

**Comment by raphw** [comment]
No, it uses neither.

**Comment by andresluuk** [comment]
Ah. When I was investigating the bytecode I saw the same broken frames Eric pointed out. 
They where not present in the original weld class, but appeared there after byte-buddy had done it's thingy. 
I think, from ASM's view, generally ASM wants only to read legal bytecode and it is fine (from theire side) for it to fail if it sees something not legal. So he will probably point out that the the bytecode produced by byte-buddy should not contain broken frames.

**Comment by raphw** [comment]
I think I found the issue. Weld proxies issue a stack map frame prior to the first instruction what Byte Buddy did not expect. I fixed this now on master and it should no longer occur with the next release.

**Comment by andresluuk** [comment]
Great!
I will close the case then. This was probably a rare error, so good that it got sorted out.
