### ISSUE TITLE
How to replace a annotated Kotlin property 

### ISSUE THREAD

**Issue by StefMa** [raphw/byte-buddy#867]
I have a project idea in mind where I wanted to annotate a property in a Kotlin class and set (or change the return value) at compile/build time. 
Example:
```kotlin
class Clazz {
  @Annotation
  private val something = ""
}
```
This should be changed to 
```kotlin
private val something = "filledWithSomething"
```

For this I evaluate different libraries (like byte-buddy) which enabled me to do this.

Unfortunately I don't get smart with [the documentation](https://bytebuddy.net/#/tutorial) 😂 
I read that byte-buddy is here for `runtime` changes. Which is fine.
But is it also possible at build time? Because I read this sentences: 
>Furthermore, Byte Buddy offers a convenient API for changing classes either manually, using a Java agent or during a build.

To make it short:
Can someone push me into the right direction how to do this?
Or is it even possible with ByteBuddy?
In the worst case (which seems is possible) I would implemented it a little bit different:
* At runtime I create a new class `AnnotationFiller`
* Search for all Annotated fields
* Create a new method in the `AnnotationFiller` and fill it with the content (`filledWithSomething`)
* Delegate all `getters` of the annotated properties to the new `AnnotationFiller` 

Thank you in advance 😇

**Comment by raphw** [comment]
The documentation is on the list of things that really need renewal, it's terribly outdated.

You can use a `net.bytebuddy.build.Plugin` and the Maven and Gradle plugins. You can then instrument any type that declares the annotation on any field. For each such type, match all such fields in the `DynamicType.Builder` API and override the value. Not sure how Kotlin implements such fields, maybe you also need to instrument all constructors to set the field value.

**Comment by StefMa** [comment]
Thanks @raphw! This helps a lot..

I have already a working example where I replace `static` **fields** in Kotlin with an annotation.
This works great.

But I have few more questions:
1. Does this field really have to be static?
2. Does this field really has a `null` value? (I noticed that if I set them a value it will not be overriden)
3. How can I get the `value` of the annotation and set it as value? Currently I set it the value hardcoded to `Test`. But I have no clue how to get the `value` of the annotation (which contains the text)

Thank you 🙂

**Comment by raphw** [comment]
1. No, this should not be necessary. Do you instrument constructor's to override the field value?
2. The default value is the compile-time constant value, it should not be required.
3. You can get the value using Byte Buddy's description API. You should be able to read it from there and to set the value.
