### ISSUE TITLE
miss class to instrument

### ISSUE THREAD

**Issue by mittyok** [raphw/byte-buddy#869]
In my project, it use spring framework + tomcat, I use bytebuddy agent to instrument classes. when I use "com.a.b." as prefix to instrument, I can see log in onTransform event(Indicate that the class "com.a.b.c.d.Test" has been instrumented). But when i use "com.a." as prefix, nothing to print, and the class "com.a.b.c.d.Test" was not instrumented.

Why ?
How to know what happend? I have add install listener and custom listener.

Thank you.

**Comment by raphw** [comment]
I'd need to know more but possibly you are creating a circularity by instrumenting more classes. Is there nothing in your logs?

**Comment by mittyok** [comment]
Thank you for your reply. I test it again. If I use "com." as prefix, it will transform the class rightly. It is so strange. Do you use wechat or other chat tools. How can I connect you conveniently. This problem is very strange.

**Comment by raphw** [comment]
It must be a class loading issue. Try to run with verbose class loading to see if the class loading order changes in your favor when renaming the class.

**Comment by mittyok** [comment]
Thank you. Could you tell me how to distinguish the problem "the class loading order changes in your favor when renaming the class", how can I ensure it from the log, thank you very much.

**Comment by raphw** [comment]
You can for example extract the class loading information:

```java
java -verbose:class -version 2>/dev/null |
  sed -ne 's/\[Loaded \(.\+\) from \(.\+\)\]/\2/p' | 
  sort -u
```

**Comment by mittyok** [comment]
Ok, yes, I can get the information. But how to analyse it to ensure the problem reason.
