### ISSUE TITLE
about intercept ThreadPoolExecutor

### ISSUE THREAD

**Issue by hnwyllmm** [raphw/byte-buddy#871]
I have success intercept the `java.util.concurrent.ThreadPoolExecutor` in the unittest, some code as below:
```java
agentBuilder = agentBuilder
                .ignore(nameStartsWith("net.bytebuddy.")
                        .or(nameStartsWith("sun.reflect"))
                        .or(isSynthetic()))
                .with(new AgentBuilder.InjectionStrategy.UsingUnsafe.OfFactory(bootstrapTypeFactory))
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION);
```
It works fun at almost senario.
But it not work when something load the class `ThreadPoolExecutor` before my interceptor code.
I have add the argument `-Dnet.bytebuddy.dump=/tmp/` and I can see the instrumented class file:
```java
public void execute(Runnable var1) {
        DELEGATION.intercept(new fHar5WJ8(this), this, cachedValue$NqnPS4f2$gtalt20, new Object[]{var1});
    }
```
Doesn't it reload to bootstrap class loader namespace?
Or something else wrong?

**Comment by raphw** [comment]
You cannot change the class layout of a class that is already loaded on most JVMs. If you retransform classes, set the `.disableClassFormatChanges()` and register an `AgentBuilder.Listener` to discover the error message.

With retransformation, you typically want to use `Advice`, not `MethodDelegation`.

**Comment by hnwyllmm** [comment]
Thanks for your reponse.

**Comment by hnwyllmm** [comment]
Another message： I use the Arthas attaching the process, and use disas the class of `ThreadPoolExecutor` in the running JVM, the class has been success instrumented.
