### ISSUE TITLE
@OnMethodExit: How to return default value for primitive types in a generic way?

### ISSUE THREAD

**Issue by kriegaex** [raphw/byte-buddy#873]
I did not find anything obvious in the documentation and only one loosely related issue #807.

The simple requirement is: Whatever the return type of the captured method I am advising is, I want to have an easy way to return the default value for any given return type. E.g. it would be nice if I could just set my  `@Return(readOnly = false, typing = DYNAMIC) Object returnValue` to `null` and ByteBuddy would automatically cast, convert, replace the value to `0`, false`, `'\0'` or whatever. There is some kind of intelligence when I return `0` or `null` for `void` methods, but for other types I have to do something like:

```java
Class<?> returnType = method.getReturnType();
if (!returnType.isPrimitive())
  return null;
if (returnType.equals(long.class))
  return 0L;
if (returnType.equals(float.class))
  return 0.0f;
if (returnType.equals(double.class))
  return 0.0d;
if (returnType.equals(char.class))
  return '\0';
if (returnType.equals(boolean.class))
  return false;
return 0;
```

I saw that BB has some helper classes for wrapping/unwrapping primitives, but I am not sure if and how I could use them in this context.

**Comment by raphw** [comment]
You can use `@Advice.StubValue Object` as an advice argument. Reading from this argument will produce a boxed default return value.

**Comment by kriegaex** [comment]
Sorry, this answer does not help me and your automatic tests only use `@Advice.StubValue` for entering advices, not exiting ones. What I need is to return the default value conditionally, i.e. if some condition in the after advice is met. In other cases I might return another stub value or the real method result which is bound to another advice parameter.

**Comment by kriegaex** [comment]
**Update:** The problem was sitting in front of the computer. I had forgotten to skip the target method call in the before advice, i.e. the condition evaluated in an unexpected way and was false instead of true.

Now I am doing something like:

```java
    // If target method was not executed, initialise return value with default value
    // for that type, i.e null, 0, false
    if (!proceedMode)
      returnValue = stubReturnValue;
```

To make a long story short: It works now.

Thank you for your quick reaction and helpful advice (no pun intended).
