### ISSUE TITLE
java.lang.VerifyError on Websphere

### ISSUE THREAD

**Issue by mjok** [raphw/byte-buddy#881]
I am getting:
Error 500: java.lang.VerifyError: JVMCFRE028 ldc* bytecode must reference a constant; class=org/apache/commons/fileupload/util/LimitedInputStream, method=read()I, pc=0 Exception Details: Location: org/apache/commons/fileupload/util/LimitedInputStream.read()I @0: JBldc Reason: Wrong type at the index 65 of constant pool Exception Handler Table: bci [0, 27] => handler: 178 bci [30, 175] => handler: 178

That error arises on WebSphere only, the same application class on JBoss works as expected.

I have created an advice on with type matcher: `hasGenericSuperType(named("java.io.InputStream"))`

I have added option `-Dnet.bytebuddy.dump` as you mentioned somewhere in comments.
Here is the output:
[bytebuddy.zip](https://github.com/raphw/byte-buddy/files/4778998/bytebuddy.zip)

The class is an example, other InputStream classes also seems to  fail on WebSphere.

**Comment by raphw** [comment]
Seems like you are adding a type constant to a class file below version 1.5.

Have a look at `TypeConstantAdjustment`. If you register, Byte Buddy translates these instructions with slightly changed semantics.
