### ISSUE TITLE
re: java.lang.VerifyError

### ISSUE THREAD

**Issue by LikeTheSalad** [raphw/byte-buddy#883]
Hi, I'm getting this issue when trying to use MockK to create a mock for this class: http://jsdp.sourceforge.net/api/net/sourceforge/jsdp/SessionDescription.html 

The guys from MockK say that this could be an issue on ByteBuddy, so I just would like to know if, at a first glance, the class that I just shared can provide some hints on why is this error happening only for it, and if so, I'm curious of whether it's a config issue or it'd be something that would require a new ByteBuddy release.

There's more details of this issue and another similar one here: https://github.com/mockk/mockk/issues/448

Many thanks,
Cesar.

**Comment by raphw** [comment]
Could you run with `-Dnet.bytebuddy.dump=/some/folder` to see what class files are transformed and how?

**Comment by LikeTheSalad** [comment]
Yes, I got these 2 class files, I had to zip them before attaching them here:

[testdump.zip](https://github.com/raphw/byte-buddy/files/4790674/testdump.zip)

I hope it helps!
Cesar.

**Comment by raphw** [comment]
It's a configuration setup. I answered in the original question.

**Comment by LikeTheSalad** [comment]
Cool! - I didn't know this class was that old :sweat_smile: It makes sense that something could fail since I guess MockK was made for newer Java versions. Though I'm glad there's a mechanism to make things work anyway.

Many thanks,
Cesar.
