### ISSUE TITLE
How to match a class annotated with a special value annotation

### ISSUE THREAD

**Issue by yaohwu** [raphw/byte-buddy#885]
Could you please tell me how to macth A.class annotated with @Monitor (key = "A") 
but not match B.class annotated with @Monitor (key = "B")?

Is there any way to make it work?

**Comment by yaohwu** [comment]
Well, I find I can implement a matcher for this, but is there any embedded matcher which can make the same thing?

**Comment by raphw** [comment]
There are so many variants, implementing this as a lambda seems like the best option. Therefore, no standard matcher is supplied.
