### ISSUE TITLE
Add annotation in enclosed type T to existing field

### ISSUE THREAD

**Issue by IceBlizz6** [raphw/byte-buddy#886]
This is essentially the same issue as #771  , but need to append annotation to existing type from a byte-buddy plugin .

let's say i have a 

```
class Model {
    private List<String> names;
    // Getters and setters
}
```

And my goals is to annotate the type parameter in List
So expected output would be:
```
class Model {
    private List<@MyAnnotation String> names;
    // Getters and setters
}
```

The answer that was given in #771  worked because it was based on defining a new field in a class.
But the byte-buddy plugin i'm writing needs to be able to append an annotation to existing field.

Is this possible? and if so how?

**Comment by raphw** [comment]
You can add a `Transformer` when matching the field where you replace the field's type with your own by returning a new `FieldDescription`. You would also need to rewrite all annotations by setting `AnnotationRetention.DISABLED` in Byte Buddy to force the library into recreating all annotations.

**Comment by IceBlizz6** [comment]
I'm having some problem understanding where to start here, I'm not very familiar with bytebuddy.
Could you provide or link me to a sample that is using a Transformer and FieldDescription?

I currently have a Plugin and an EntryPoint.

**Comment by raphw** [comment]
You can intercept fields and transform them in the end: `field(<matcher>).transform(...)`. In this transformer, you can replace the actual field with a new representation that will be written to the class file. To enforce the annotation rewrite, you need to disable annotation retention.
