### ISSUE TITLE
Add annotation to an existing Entity POJO class

### ISSUE THREAD

**Issue by nitishborade** [raphw/byte-buddy#888]
I am new to Byte Buddy, and I was exploring if it could be a solution to my requirement, which I believe so, but do not know how.
I have some JPA entity POJO classes in a jar that I use in my application. I simply want to add some annotations at field level, and modify setter methods of these entity classes before I use it to load data from the database.

For example, have this entity class `Employee.class` packaged in `db-model.jar`, I want to add annotations (`MyAnnotation1`, `MyAnnotation2`) as shown in the sample, and modify `setName` method. And use this modified entity class while fetching employees from the database. And after I have loaded employees I want to use the instance for further logic processing.

Can I do this with ByteBuddy? Your help and response will be highly appreciated.

```
import javax.persistence.*;
import java.util.Set;

@Entity
@Table(name = "EMPLOYEE", schema = "TESTSCHEMA", uniqueConstraints = @UniqueConstraint(columnNames = { "NAME"}))
public class Employee implements java.io.Serializable {
	private Long id;

        @MyAnnotation1 // I want to add this annotation on this field
	private String name;
        
        @MyAnnotation2 // I want to add this annotation on this field
	private Set<Address> addresses;
....
....
	public void setName(String name) {
                // I want to add this 
                if(name.contains("some string")) {
                     name = "some default name";
                     return;  
                }
                // This is existing
		this.name = name;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}
}

```

**Comment by raphw** [comment]
Yes, Byte Buddy can redefine existing types and add annotations. The approach for this does however depend a bit on when and how you want to add this annotation.

If you want to add the annotation during your build, have a look at Byte Buddy's build plugins for Maven and Gradle and their documentations on their respective module. Plugins are implemented via the `Plugin` interface.

If you want to add the annotation during runtime, look into Java agents (a standard feature of the JVM and the `AgentBuilder` API that allows you to define such agents easily. On YouTube, you find several presentations on how to implement those.

All you'd need to do would be to match the type to add the annotations to (or methods) and define them using the `.defineAnnotation` step in the DSL. For methods, you need to specify a matcher first to identify a method to add the annotation to.

**Comment by nitishborade** [comment]
Thank you so very much @raphw, for your quick response. I am grateful.
Redefining during build seems a good approach for my use case, and since I could control the build with profiles respectively for dev and release. I will look into the plugins as suggested by you.
Thank You :)
