### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by RamDz** [raphw/byte-buddy#890]
![image](https://user-images.githubusercontent.com/37937794/86060808-6fe19100-ba5d-11ea-930b-3a58fbb2e41f.png)
I just got this error while using some game modifier i changed the "JAVA_HOME" variable to the JDK installation path which the variable didnt exist before

**Comment by raphw** [comment]
I assume that you have selected a JVM without a JDK installation. Those lack the *tools.jar* which is required for attachment.

Choose a proper JDK or include JNA (the library) to your application path such that Byte Buddy can emulate the attachment.

**Comment by RamDz** [comment]
I actually dont even have byte buddy so is that a problem ?

**Comment by RamDz** [comment]
![image](https://user-images.githubusercontent.com/37937794/86062502-c0a6b900-ba60-11ea-8199-59c77a77d9b0.png)
I chose the first one on the variable

**Comment by raphw** [comment]
Check if it countains a file tools.jar. Byte Buddy is likely used by a program you are using and expects a JDK. How is the error produced?

**Comment by RamDz** [comment]
![image](https://user-images.githubusercontent.com/37937794/86062628-124f4380-ba61-11ea-8896-4923c5d9280a.png)
So the program injects the modification into the java game the tutorial said to install JDK and select the right path in JAVA_HOME variable i did it then i got a problem idk if the version is right because he recommended to use JDK 8 which I did install JDK 8u251 windows x64 and the file of JDK doesnt actually contain the tools.jar

**Comment by RamDz** [comment]
Hmm please i really need help if the folder doesnt contain tools.jar what do i do to get it ?

**Comment by raphw** [comment]
It should be in the lib folder. Download a JDK distribution if it is missing. They are free and can be found multiple places.

**Comment by vcjmhg** [comment]
Dear Sir,
I have just run the example of tutorial at bytebuddy.net/#/tutorial,and it have the java.lang.IllegalStateException.
The exmaple code like this:
```java
@Test
  public void testReloadClass() {
    ByteBuddyAgent.install();
    Foo foo = new Foo();
    new ByteBuddy()
        .redefine(Bar.class)
        .name(Foo.class.getName())
        .make()
        .load(Foo.class.getClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
  }
class Bar {
  String m() {
    return "bar";
  }
}
public class Foo {
  String m() {
    return "foo";
  }
}
```
The exception info like this:
![image](https://user-images.githubusercontent.com/55177318/87238446-2c136200-c435-11ea-86f2-dc379c34409a.png)
![image](https://user-images.githubusercontent.com/55177318/87238464-4ea57b00-c435-11ea-9335-a07841b74263.png)

the envirmoent of my pc:
os:windows 7
jdk:.1.8(it has tool.jar)
![image](https://user-images.githubusercontent.com/55177318/87238553-4994fb80-c436-11ea-8464-c851ed2af3da.png)

maven depency:
![image](https://user-images.githubusercontent.com/55177318/87238517-d8554880-c435-11ea-87c2-8cdfa70f3490.png)

I want to kown how to deal this Exception?
thanks!!

**Comment by raphw** [comment]
The problem is that one class is package-private and one is public. Redefinition is limited to byte code but you cannot change a (visibility) modifier.
