### ISSUE TITLE
Patching method bytecode smartly

### ISSUE THREAD

**Issue by KOLANICH** [raphw/byte-buddy#891]
Hello. I wonder if it can be used to patch method bytecode smartly.

I mean, if I have a lib, a method in a lib and patched source code for this method (and, maybe  compiled jars for both), can I patch the method in runtime without rewriting it wholly (I mean if the original method has changed without conflicts to the patch, the patched method should also change)? I know that the method can probably be splitted into parts that can be overridden, but the maintainer of the upstream is unwilling to merge the patches doing this.

Also I wonder, if it is possible to make a tool, diffing the 2 versions of a lib and generating the patching code automatically.

**Comment by raphw** [comment]
Yes, you can replace an entire class file using the instrumentation API using the `Instrumentation.redefineClass` method.

The only requirement is that you do not add methods or change signatures. You don't need Byte Buddy for this, but you can use Byte Buddy agent which allows you to get an instance of `Instrumentation` easily. Refer to the javadoc for seing how to replace a class file.

**Comment by KOLANICH** [comment]
I didn't quite meant replacing the whole class. I meant patching it in memory.

The context: there is a CLI tool. I have modified it to allow usage through API as a lib, for all security, efficiency and access to some internals not exposed via CLI. But the maintainer has refused to merge my changes because he says that lots of people depend on his tool so he is afraid to merge any non-cosmetic and non-bug-fixing changes (though he has merged some, but he is the maintainer, it's his project, who am I to reason on what he can do with own software he is developing and maintainig for more than 20 years?).

Maintaining a fork is clearly not an option: it puts too lot of burden on me:
* updating it in pace with the original tool
* building and testing it
* persuading people that my fork is really needed.

Unfortunately the code is written the way that if I wanted to divert it from using files, I'd have to patch methods bodies, I cannot get what I need by inheritance and interfaces because the code is not enough abstracted. And, as you can guess, even if I fixed that, the maintainer would have refused to merge it.

Probably something like LuckyPatcher (a dalvik bytecode patcher, usually used to remove unwanted functionality from Android apps, the patches matching part resemble YARA rules) could have helped, but it is too dumb, I mean too generic (YARA and similar stuff is designed to match arbitrary binaries), so there may be false-positives, false-negatives and it doesn't care of Java program structure. The same patches often work on multiple versions.

So, what I mean, I wonder if ByteBuddy can selectively patch methods, taking care of local variables and control flow, so the resulting bytecode is still valid code. I mean a high-level patching, not `replace these bytes with that bytes`, not `replace this class with the pre-prepared class`, not `replace this method with a pre-prepared method`, but `in this method, find bytecode matching these high-level conditions (in terms of control flow, variables, maybe variables names (won't work on obfuscated or maliciously manipulated code, but for my task of an uncooperating maintainer of a FOSS project I don't expect any actions to intentionally break the patch), objects, fuction calls, and assignments) and synthesise this code (probably using the info extracted from the original code) and replace the original code with it.

In an ideal case the generation of patcher code should be automated. I mean a user provides the original source, the patched one, the tool diffs them simply, then it diffs the patched files and finds patched methods, then it diffs patched methods ASTs (there is a tool for diffing ASTs called [gumtree](https://github.com/GumTreeDiff/gumtree), though I am not sure if it is enough), then it generates a patch for AST in its internal format, then the patch is matched against bytecodes of the 2 compiled versions of the lib and generates the patch for bytecode, probably using auxilary info as variables names, if they are present, then it translates the patch into code using ByteBuddy locating the needed place and synthesising the needed bytecode for it).

**Comment by raphw** [comment]
Is this still an issue? Sorry for overlooking this. Please create a new issue with the most recent release in use if you are still facing issues.
