### ISSUE TITLE
Multiple Advice

### ISSUE THREAD

**Issue by semos2k** [raphw/byte-buddy#893]
Is it possible to use more than one advice on the same method?

![image](https://user-images.githubusercontent.com/23361212/86161533-00a68400-bad3-11ea-8163-efd554cb4a66.png)

the objetive is allow to define multiple advices for example: Log, Security, and others.

thx.

**Comment by raphw** [comment]
Not if applying `Advice` as an implementation. But `Advice` can also be used as a decorator using:

```java
builder.visit(Advice.to(LogAdvice.class).on(...))
```

This will wrap the advice around the existing method without changing it.

**Comment by semos2k** [comment]
Yes, worked fine.

thx.
