### ISSUE TITLE
maven-plugin: ability to control log level of "No types were transformed during plugin execution"

### ISSUE THREAD

**Issue by famod** [raphw/byte-buddy#895]
First, thanks for this awesome Maven plugin and its plugin concept.

We are using a custom plugin to generate constructors for CDI bean classes in a Maven project with many submodules.
Not all of those modules have such CDI bean classes so the warning:
```
[WARNING] No types were transformed during plugin execution
```
is unnecessarily nagging for us and we would like to reduce the level to info.

There could be a new property to control that, e.g. `warnIfNoTransformations` which is `true` by default. If set to `false`, the Mojo could use `.info()` instead of `.warn()`.

**Comment by raphw** [comment]
Just added a switch for it. This is of course a reasonable use case.

**Comment by famod** [comment]
@raphw Thanks! Do you already have a release date for 1.10.14?

**Comment by raphw** [comment]
Some time in July, I think!
