### ISSUE TITLE
maven-plugin Eclipse Metadata not published

### ISSUE THREAD

**Issue by tkalmar** [raphw/byte-buddy#896]
The required metadata for eclipse is under:
 https://github.com/raphw/byte-buddy/tree/master/byte-buddy-maven-plugin/src/main/resources/META-INF/m2e
but is it not included in 
https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-maven-plugin/1.10.13/byte-buddy-maven-plugin-1.10.13.jar
the released jar
I think the problem is the Filtering in the pom.xml of the maven plugin:

```
<build>
        <resources>
            <resource>
                <directory>..</directory>
                <targetPath>META-INF</targetPath>
                <filtering>true</filtering>
                <includes>
                    <include>LICENSE</include>
                    <include>NOTICE</include>
                </includes>
            </resource>
        </resources>
    </build>
```
This should also include META-INF/m2e

**Comment by mickroll** [comment]
this may also resolve #820

**Comment by famod** [comment]
Good catch!
