### ISSUE TITLE
How does ByteBuddy intercept an exception that has a trycatch?

### ISSUE THREAD

**Issue by wyt** [raphw/byte-buddy#901]
How does ByteBuddy intercept an exception that has a trycatch?

**Comment by yaohwu** [comment]
As far as I know, ByteBuddy only can intercept the exception throwing just like this https://stackoverflow.com/questions/36320330/bytebuddy-intercept-exception-throw, cause it just intercepts the method which may contain the `try catch` block. During the runtime, you may do not know where is the `try catch` in a method.

**Comment by raphw** [comment]
You cannot intercept in-code catch blocks with Byte Buddy's high level API. Byte Buddy exposes ASM for this purpose

**Comment by wyt** [comment]
Why not provide a high-level API for this?

**Comment by yaohwu** [comment]
> Why not provide a high-level API for this?

You can reach that by using ASM
