### ISSUE TITLE
agent for interface with jdk dynamic proxy class

### ISSUE THREAD

**Issue by yfcchilly** [raphw/byte-buddy#904]
i want to **enhance interface with jdk dynamic proxy class**. for example, **mybatis mapper interface**, mybatis framework will generate Proxy class by MapperProxy. when i execute SuperCall `zuper.call()` in the bytebuddy interceptor, will throws exception as follow:

`java.lang.NoSuchMethodError: com.ng.trade.mapper.TestMapper.getAllUsers$original$c2Kx3tFv()Ljava/util/List;
	at com.ng.trade.mapper.TestMapper.getAllUsers$original$c2Kx3tFv$accessor$Tm0E4WT5(TestMapper.java) ~[classes/:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) ~[?:1.8.0_181]
	at org.apache.ibatis.binding.MapperProxy.invokeDefaultMethod(MapperProxy.java:84) ~[mybatis-3.4.6.jar:3.4.6]
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53) ~[mybatis-3.4.6.jar:3.4.6]
	at com.sun.proxy.$Proxy114.getAllUsers$original$c2Kx3tFv$accessor$Tm0E4WT5(Unknown Source) ~[?:?]
	at com.ng.trade.mapper.TestMapper$auxiliary$KkWjqYIs.call(Unknown Source) ~[classes/:?]`

is bytebuddy support interface with dynamic proxy class?  anything can help will be appreciated

**Comment by raphw** [comment]
Not sure how you produce this error but maybe you are facing a class loading race? Could you provide a reproduction project?

**Comment by yfcchilly** [comment]
byteBuddyVersion = '1.10.9'

1. premain entrance

new AgentBuilder.Default()
	.with(DebugListener.getInstance())
	.type(typeOf("com.ng.trade.mapper.TestMapper"))
	.transform(new CustomTransformer(CommandInterceptor.class))
	.installOn(instrumentation);

2. type description tools method

public static ElementMatcher<TypeDescription> typeDef(String className) {
    if (WormHoleCommonUtil.isEmpty(className)) {
        return null;
    }
    ElementMatcher.Junction<TypeDescription> classJunction = null;
    classJunction = className.contains("*") ? nameMatches(className) : named(className);
    return classJunction.and(not(nameContains("$auxiliary$")))
            .and(not(nameContains("BySpringCGLIB$")))
            .and(not(isStatic()));
}

3. custom transformer

public class CustomTransformer extends AbstractTransformer {

    private ElementMatcher<MethodDescription> methodMatcher;

    public CustomTransformer(Class customInterceptor,
                             ElementMatcher<MethodDescription> methodMatcher) {
        super(customInterceptor);
        this.methodMatcher = methodMatcher;
    }

    public CustomTransformer(Class customInterceptor) {
        super(customInterceptor);
    }

    @Override
    protected DynamicType.Builder.MethodDefinition.ImplementationDefinition builderTransform(
            DynamicType.Builder<?> builder, ClassFileLocator.Compound compound) {
        ElementMatcher.Junction<MethodDescription> elementMatcher = not(ElementMatchers.<MethodDescription>isPrivate()
                .or(ObjectMethodElementMatchers.INSTANCE));
        return builder.method(methodMatcher != null ? elementMatcher.and(methodMatcher) : elementMatcher);
    }
}

public abstract class AbstractTransformer implements AgentBuilder.Transformer {

    private final Class interceptor;

    protected AbstractTransformer(Class interceptor) {
        this.interceptor = interceptor;
    }

    protected abstract ImplementationDefinition builderTransform(DynamicType.Builder<?> builder,
                                                                 ClassFileLocator.Compound compound);

    @Override
    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder,
                                            TypeDescription typeDescription,
                                            ClassLoader classLoader,
                                            JavaModule module) {

        ClassFileLocator.Compound compound = new ClassFileLocator.Compound(
                ClassFileLocator.ForClassLoader.of(classLoader),
                ClassFileLocator.ForClassLoader.ofSystemLoader());

        return builderTransform(builder, compound).intercept(
                MethodDelegation.to(TypePool.Default.of(compound).describe(interceptor.getName()).resolve()));
    }
}

4. interceptor define like：

public class CommandInterceptor {
    @RuntimeType
    public static Object intercept(@SuperCall Callable<?> zuper,
                                   @Origin Method method,
                                   @AllArguments Object[] params) throws Throwable {
        Object result = client.call(); // will throw NoSuchMethod Exception
        // do something
        return result;
    }

}

5. spring mybatis mapper define

@Mapper
public interface TestMapper {
    @Select("SELECT * FROM User")
    List<User> getAllUsers();
}

**Comment by raphw** [comment]
You can extract the byte code of all classes setting `-Dnet.bytebuddy.dump=/some/folder`. Could you check if the auxiliary methods are indeed missing in the transformed class?

It looks right to me, and neither does it look like some premature loading is involved. If you create a standalone project and put it on GitHub, I can have a look.

**Comment by yfcchilly** [comment]
thanks, @raphw! it's good idea to create a standalone project on github, tomorrow  i will do that

**Comment by yfcchilly** [comment]
sample project on GitHub url: https://github.com/yfcchilly/agent-mapper
sub-project: agent is agent module package with showJar
sub-project: service is demp bootstrap app with springboot.

**Comment by raphw** [comment]
I drilled the problem down to rather problematic code in MyBatis.

Have a look at `invokeDefaultMethod` in `MapperProxy`. It intercepts any invocation on instances of `UserMapper` and binds them to a proxy instance that is also of type `UserMapper` but not the same instance as the intercepted instance. Therefore, their joggling with method handles misdirects and an error yields.

This is something to report to MyBatis and is not related to Byte Buddy.

**Comment by yfcchilly** [comment]
yeah, i have already consider to instrument the `MapperProxy` yesterday, it works well actually! 
I will also look at the documents about `Advice`. Thank you very much! @raphw 

`agentBuilder = agentBuilder.type(typeDef("org.apache.ibatis.binding.MapperProxy"))
                .transform(new CustomTransformer(MapperInterceptor.class,
                        methodDef(Arrays.asList("invoke"), false)));`
