### ISSUE TITLE
How to define a new constructor to execute super(args[0],new CClass(args[2],args[3]))

### ISSUE THREAD

**Issue by asasas234** [raphw/byte-buddy#905]
Suppose I have the following code
`
public class AClass {
     public AClass(Object obj,CClass param) {
         ...
     }
}
public class BClass {
     
}
`
I want to add a new constructor to BClass via bytebuddy.
The constructor looks like this
`
public BClass(Object param1,Object param2,Object param3) {
       super(param1,new CClass(param2,param3))
}
`
How do I do it? @raphw

**Comment by raphw** [comment]
Use `MethodCall` (it includes consturctors where you provide the first argument and then as a second argument another `MethodCall` to this constructor to which you present the second and third. Something like this:

```java
new ByteBuddy()
  .subclass(AClass.class, ConstructorStrategy.Default.NO_CONSTRUCTORS)
  .name("some.pkg.BClass")
  .defineConstructor(Visibility.PUBLIC)
  .withParameters(Object.class, Object.class, Object.class)
  .intercept(MethodCall.invoke(Base.class.getConstructor(Object.class, CClass.class))
    .onSuper()
    .withArgument(0)
    .withMethodCall(MethodCall.construct(Argument.class.getConstructor(Object.class, Object.class)).withArgument(1, 2)))
  .make();
```

This

**Comment by asasas234** [comment]
Thank you so much @raphw 。I've solved the problem the way you said.
