### ISSUE TITLE
Can ByteBuddy intercept finalize method?

### ISSUE THREAD

**Issue by mjok** [raphw/byte-buddy#906]
I'd like to intercept finalize method using Advice, I'd like to know when the object is actually garbage collected.
I have tried to instrument InputStream using method matching: 

`named("close").or(named("finalize")).and(takesArguments(0))`

I checked with **net.bytebuddy.dump** option, and seems that the my InputStream class `close` method has been changed, but bytecode had no `finalize` method at all. 

I suppose that it has to be, that finalize method was never implemented at first place. 
Can you instrument the method witch is inherited from superclass and never implemented in the actual class you're instrumenting?

**Comment by raphw** [comment]
Yes, but it is ignored by default to avoid accidental matching by 'catch all' matchers since it is so costly on garbage collection.

You'd need to configure your default BYTEbuddy instance to set a different default ignore.
