### ISSUE TITLE
can bytebuddy support package level interface

### ISSUE THREAD

**Issue by wuxingye** [raphw/byte-buddy#907]

**Comment by wuxingye** [comment]
`interface AuthorizationServiceProxy extends IgtRestfulServicesProxy {
    CheckAssocatedGetOrderResponse checkAssocatedGetOrder(CheckAssocatedGetOrderRequest var1);
}`

**Comment by raphw** [comment]
Yes, simply name the type without a package.

**Comment by wuxingye** [comment]
i wanna know how can byte buddy support Dynamic Proxy to package level interface(the default modifiers)

such as

`interface AuthorizationServiceProxy extends IgtRestfulServicesProxy { 
        CheckAssocatedGetOrderResponse checkAssocatedGetOrder(CheckAssocatedGetOrderRequest var1); }
`

**Comment by raphw** [comment]
Yes, use `Visibility.PACKAGE_PRIVATE`.

**Comment by wuxingye** [comment]
Thank you!

please show me detail

my code:
`    DynamicType.Unloaded<?> clazz = new ByteBuddy(ClassFileVersion.JAVA_V8).subclass(Object.class)
        .implement(AuthorizationServiceProxy.class).method(isDeclaredBy(AuthorizationServiceProxy.class))
        .intercept(InvocationHandlerAdapter.of(ServiceClientInvocationHandler.getInstance())).make();
`

but exception

`Caused by: java.lang.IllegalAccessError: class com.ctrip.igt.restful.service.AuthorizationServiceProxy$ByteBuddy$AcYMg0Ve cannot access its superinterface com.ctrip.igt.restful.service.AuthorizationServiceProxy
`

**Comment by raphw** [comment]
During loading, you need to inject the class into the same runtime package as the package-private interface.

The `load` method takes a second argument, a `ClassLoadingStrategy`. Use the `ClassLoadingStrategy.Default.INJECTION` strategy to target the same package.

**Comment by wuxingye** [comment]
It can not solve my problem.

My code:

`
public class ServiceClientFacadeFactoryBean<T> extends BaseService implements FactoryBean<T> {

  private final static Logger LOGGER = LoggerFactory.getLogger("SOA-Client");

  private Class<T> serviceClientFacadeInterface;

  public ServiceClientFacadeFactoryBean(Class<T> serviceClientFacadeInterface) {
    super();
    this.serviceClientFacadeInterface = serviceClientFacadeInterface;
  }

  @Override
  public T getObject() throws Exception {
    DynamicType.Unloaded<?> clazz = new ByteBuddy(ClassFileVersion.JAVA_V8).subclass(Object.class)
        .implement(serviceClientFacadeInterface).method(isDeclaredBy(serviceClientFacadeInterface))
        .intercept(InvocationHandlerAdapter.of(ServiceClientInvocationHandler.getInstance())).make();

    return (T) clazz.load(getClass().getClassLoader(), ClassLoadingStrategy.Default.INJECTION).getLoaded()
        .newInstance();

  }
`

The class(interface) will be proxy is package-private, and in another package.

But the same exception

`
Caused by: java.lang.IllegalStateException: Invisible interface type interface com.ctrip.igt.restful.service.AuthorizationServiceProxy for class net.bytebuddy.renamed.java.lang.Object$ByteBuddy$Cwn3Qrwj

`

**Comment by raphw** [comment]
If the interface is in another package and package-private, the JVM will never allow for the inheritance relationship.

**Comment by wuxingye** [comment]
Thank you! I will public the interface.

**Comment by wuxingye** [comment]
Can I generate bytecode and assign the same package with the interface, so the interface is visible to the class

**Comment by raphw** [comment]
You can define a name using the `.name()` step.

**Comment by wuxingye** [comment]
Yes, it works

the final code:

```
public class ServiceClientFacadeFactoryBean<T> extends BaseService implements FactoryBean<T> {

  private final static Logger LOGGER = LoggerFactory.getLogger("SOA-Client");

  private Class<T> serviceClientFacadeInterface;

  public ServiceClientFacadeFactoryBean(Class<T> serviceClientFacadeInterface) {
    super();
    this.serviceClientFacadeInterface = serviceClientFacadeInterface;
  }

  @Override
  public T getObject() throws Exception {
    DynamicType.Unloaded<?> clazz = new ByteBuddy(ClassFileVersion.JAVA_V8).subclass(Object.class)
        .name(serviceClientFacadeInterface.getName() + "ImplProxy").implement(serviceClientFacadeInterface)
        .method(isDeclaredBy(serviceClientFacadeInterface))
        .intercept(InvocationHandlerAdapter.of(ServiceClientInvocationHandler.getInstance())).make();

    return (T) clazz.load(getClass().getClassLoader(), ClassLoadingStrategy.Default.INJECTION).getLoaded()
        .newInstance();

  }
```
