### ISSUE TITLE
Can't add multiple fields with the same name but different type

### ISSUE THREAD

**Issue by CalebFenton** [raphw/byte-buddy#91]
It doesn't seem possible to create classes with more than one field of the same name (but different types). Consider this valid Java class:

```
package org.cf.test;

class OverloadedFields 
{
  public static int field1;
  public static Object field1;
}
```

It compiles fine. Here's the disassembly:
```
class org.cf.test.OverloadedFields
  minor version: 0
  major version: 50
  flags: ACC_SUPER
Constant pool:
  #1 = Utf8               org/cf/test/OverloadedFields
  #2 = Class              #1              // org/cf/test/OverloadedFields
  #3 = Utf8               java/lang/Object
  #4 = Class              #3              // java/lang/Object
  #5 = Utf8               field1
  #6 = Utf8               I
  #7 = Utf8               Ljava/lang/Object;
{
  public static int field1;
    descriptor: I
    flags: ACC_PUBLIC, ACC_STATIC

  public static java.lang.Object field1;
    descriptor: Ljava/lang/Object;
    flags: ACC_PUBLIC, ACC_STATIC

}
```

The check appears to be here: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/scaffold/InstrumentedType.java#L725

Cool story, bro:
I was trying to make this work in 0.7.8, but it was failing at least in part because `FieldDescription.hashCode()` was only including the name, and not the type. I saw it was fixed in https://github.com/raphw/byte-buddy/commit/5e0c9b4ab0f08fcd483da817283aca824420e0d6#diff-0eeeae09607b736fca224fe598fd7c9aL476.

**Comment by raphw** [comment]
The *javac* compiler would not compile your above example due to the ambiguous name. It would however be permissive on the byte code level, that is correct. I might be able to add a possibility in the future.

**Comment by CalebFenton** [comment]
Right, javac won't compile it, but javac will in some cases make classes that have multiple fields with the same name and different type.

```
public class OverloadedFields2 {
    static final int[] $assertionsDisabled = new int[0];
    public static void main(String[] args) {
        System.out.println($assertionsDisabled.length);
        assert System.currentTimeMillis() == 0L;
    }
}
```

javac adds another field called `$assertionsDisabled`:
```
  static final int[] $assertionsDisabled;
    descriptor: [I
    flags: ACC_STATIC, ACC_FINAL

  static final boolean $assertionsDisabled;
    descriptor: Z
    flags: ACC_STATIC, ACC_FINAL, ACC_SYNTHETIC
```

It's an edge case, sure. I'm dealing with classes that have been obfuscated, so they're using all kinds of tricks and doing things that are valid at the bytecode level but not by the compiler.

**Comment by raphw** [comment]
You are right. I am currently preparing the release of version 1.0 and I redid a lot of the things. There is also a new validation API that can be disabled but I just updated it to recognize fields as a pair of type and name.

Cheers!

**Comment by CalebFenton** [comment]
This library is pretty boss. I'm actually learning some tricks going through the code. Thanks for what must have been a lot of effort and work.

This is an ugly hack but I'd feel guilty if I didn't share it. This is the change I made to get things working until 1.x:
```
if (!fieldNames.add(fieldName+fieldDescription.getType().toString())) {
```

**Comment by raphw** [comment]
Thanks for the hint. 1.0 should be release some time next week for everybody that can wait that long.
Cheers!
