### ISSUE TITLE
Feature request: Unique Identifier per Advice application

### ISSUE THREAD

**Issue by tylerbenson** [raphw/byte-buddy#911]
Given a class like this:
```java
public class Foo {
  public void foo1() {}
  public void foo2() {}
}
```

If I write advice that instruments each public method in `Foo`, there is not a simple way to uniquely identify the advice for each method.  I suggest something like this:

```java
@Advice.Pointcut int unscopedUniqueIdentifier
@Advice.Pointcut(Foo.class) int fooScopedUniqueIdentifier
```

I expect this would be implemented via a shared AtomicInteger per the scope provided.  The ID could be injected as a constant into the bytecode and probably regenerated each time a retransformation occurs.

The alternative would be to use a combination of class and method name + signature mapping to an ID, but that would be much less performant.

**Comment by raphw** [comment]
not a bad idea. I'll consider both!

**Comment by raphw** [comment]
Hi Tyler, you can easily accomplish this by using `Advice.withCustomBinding().bind(MyAnnotation.class, ...)` where you implement a custom `OffsetMapping` or even an `OffsetMapping.Factory`. If you wanted to use a regeneration of the id after the retransformation was applied, you could indeed use an atomic value to update the offsett mapping.

I think this requirement is to individual to add it to the library, I think the freedom of implementation is a bigger advantage here.

Let me know if this recommendation does not make sense to you but I think it should be fairly easy to do given the current infrastructure.

**Comment by tylerbenson** [comment]
I was not familiar with the custom binding.  Thanks for pointing that out.  How does this work for something relatively constant like a primitive or a string, vs a constructed object? Does it call the factory each method invocation or once at transformation time?

**Comment by raphw** [comment]
If it's a constant value, you can return that from the mapping using a [stack manipulation](https://javadoc.io/doc/net.bytebuddy/byte-buddy/1.10.2/net/bytebuddy/asm/Advice.OffsetMapping.Target.ForStackManipulation.html). In the instrumented class it is then bound as a constant pool value.

**Comment by tylerbenson** [comment]
Cool. Do you know of any examples you could point me to?

**Comment by raphw** [comment]
Have a look at the unit tests, they should reflect any possible use case. Other then that, have a look at Mockito. We inject unique ids per mock maker in there. Mockito only defines a hand full of advice, so it should be easy to find by looking for the `@Advice` annotations there.
