### ISSUE TITLE
Question about Advice and MethodDelegation

### ISSUE THREAD

**Issue by pippoflow** [raphw/byte-buddy#913]
I'm trying to use `Advice` to enhance a class which extends another class. In this subclass, methods from superclass are not declared. I tried:
```
new AgentBuilder.Default()
                .disableClassFormatChanges()
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .ignore(none())
                .type(is(SubclassInQuestion.class))
                .transform(((builder, typeDescription, classLoader, module) -> builder
                        .visit(Advice.to(MyAdvice.class)
                                .on(not(isDeclaredBy(Object.class)
                                        .or(named("init"))
                                        .or(named("buildFactory"))
                                        .or(named("initClientPool"))
                                        .or(isConstructor()))))))
                .installOnByteBuddyAgent();
```
and the methods from superclass are not enhanced by `Advice` as expected.

So in order to use `Advice`, in this case, 
1) do I have to declare all the methods from superclass in subclass? If yes, which is something I don't want to do, because that would be a lot of code, and if methods change or new methods being added, I would have to change my code as well. 
2) I tried `MethodDelegation`, which failed because the class is already loaded and got `attempted to change the schema (add/remove fields)` exception... Could you please suggest a workaround for this? Thanks.

**Comment by raphw** [comment]
You would need to transform all classes in the hierarchy for this to work: `.type(isSuperTypeOf(SubclassInQuestion.class))`.

You can also use advice as an interceptor via the `.method(...).intercept(...)` steps but this instructs Byte Buddy to instrument all methods in a hierarchy. This would declare the overridden methods in `SubclassInQuestion` which adds methods what is not possible when using retransformation as a JVM-restriction. Adding byte code as `Advice` is doing as a decorating visitor is alright, however.

**Comment by pippoflow** [comment]
I instead create a new class `SubSub` on the fly, which extends that `SubclassInQuestion` and use an interceptor to override all inherited methods. What I want to achieve is, in the overriding methods, first get an instance of _superclass_ (i.e. superclass of both `SubclassInQuestion` and `SubSub`) and then call the exact method on that instance. This class ideally looks something like this:

```
@Override
public String set(final String key, final String value) {
     return getInstance(key).set(key, value);
}

@Override
public String get(final String key) {
     return getInstance(key).get(key);
}

private Superclass getInstance(String key) {
  // get an instance of superclass
}
```

Now with an interceptor, I can't avoid using reflection to invoke the method on the instance (and I want to avoid it). Using `Advice`, I seem to face the same issue, because I still don't know the actual method to call until runtime. (or am I wrong?)

Is it possible with Bytebuddy, to generate `SubSub` with methods such that invocation of a method on a certain instance can act as with compiled code. Can `Advice` somehow achieve this? Please advice. Thanks!

**Comment by raphw** [comment]
I think you are looking for `MethodCall` which can give you these implementations without the overhead of reflection (or boxing the arguments in wrappers and an array):

```java
Implementation implementation = MethodCall.invokeSelf()
  .on(MethodCall.invoke(named("getInstance").withArgument(0))
  .withAllArguments();
```

In addition to this interceptor, you only need to define a method `getInstance(String key)` which you can implement as you'd like.

**Comment by pippoflow** [comment]
So I did this:

```
Implementation interceptor = MethodCall.invokeSelf()
                .on(MethodCall.invoke(named("getInstance")).withAllArguments())
                .withAllArguments();

Class<?> instrumentedClientType = new ByteBuddy()
                .subclass(R2mShardedClient.class)
                .method(not(isDeclaredBy(Object.class)
                        .or(isDeclaredBy(R2mShardedClient.class))))
                .intercept(interceptor)
                .make()
                .load(ClassLoader.getSystemClassLoader(), ClassLoadingStrategy.Default.WRAPPER)
                .getLoaded();
```
Looks like `MethodCall` is not assignable to `AbstractBinaryCacheClusterClient` (my class) and threw `IllegalStateException("Cannot invoke " + invokedMethod + " on " + fieldDescription)` during `toStackManipulation`. What I did wrong here?

**Comment by pippoflow** [comment]
I tried:

```
Implementation interceptor = MethodCall.invokeSelf()
                .on(MethodCall.invoke(named("getClient")).withAllArguments())
                .withAllArguments().withAssigner(Assigner.DEFAULT, Assigner.Typing.DYNAMIC);
```
now the `MethodInvoker` has a `typeDescription` of `net.bytebuddy.implementation.MethodCall`, which is not `assignableFrom` my class, so `invokedMethod.isInvokableOn(typeDescription)` is false and `IllegalStateException` is thrown.

I realize I need to supply something other than a `MethodCall` to the `on` method... Should I create a `StackManipulation` myself?

**Comment by raphw** [comment]
You are using the latest version of Byte Buddy for this? In this case, what type does `getInstance` return?

**Comment by pippoflow** [comment]
I tried this:

```
Implementation interceptor = MethodCall.invokeSelf()
                .onMethodCall(MethodCall.invoke(named("getInstance")).withArgumentArray())
                .withAllArguments();
```

and it works like a charm. Thanks @raphw for your time!

**Comment by raphw** [comment]
Is this still an issue? Sorry for overlooking this. Please create a new issue with the most recent release in use if you are still facing issues.
