### ISSUE TITLE
MethodConstant fallback for non-binary compatible bridge methods

### ISSUE THREAD

**Issue by TuomasKiviaho** [raphw/byte-buddy#916]
bridge-method-injector is a binary compatibility preserver that I'm still using mostly for auto-boxing/unboxing return values.

https://web.archive.org/web/20180818064629/http://bridge-method-injector.infradna.com/

`get(Privileged)Method` used in `MethodConstant` seems to return sometimes a bridged variant that the injector had generated. I'm using `MethodDelegation` via Hibernate Enhancer so #493 has nice an example of the the static section that causes problems with `cachedValue` pointing sometimes to bridge methods that are not compatible with the `TypeToken` of `MethodDescriptor` 

Would it be possible to have a toggle for `get(Privileged)Methods`  based fallback in case a bridged variant was returned and it did't match precisely what the `MethodDescriptor` had stated at it's `SignatureToken` at compile time.

**Comment by raphw** [comment]
I'm not sure I follow, did you discover a bug in Byte Buddy where an exception is thrown? You can configure Byte Buddy's behavior for generating bridge methods in the `ByteBuddy` instance. You can also configure a `MethodGraph.Compiler` that considers JVM signatures rather then Java signatures in the same instance. This way, you can discriminate by return type.

I would however not recommend it. javac will get confused and reflection will get broken if such methods exist.

**Comment by TuomasKiviaho** [comment]
I would rather call this a feature request rather than a bug because what you said about reflection being broken was what I encountered. Sorry for leaving the details out from the initial description. I'll go into more details below.

I use Kohsuke's bridge method injector to preserve binary backwards compatibility with JPA entities in a way that might break even that spec, but Hibernate has been coping well until I discovered that proxies do not always behave as expected.

They tend to throw an exception whenever a bridge method having a legacy primitive return type is being fed null via a boxed primitive return type of the non-bridged method. I have placed now some countermeasures that turn the nulls as default values but that approach will have it's own side effects in the long run.

Below is a caricature of such entity without all the hibernate related methods that comes out from the Hibernate Enhancer.

``` java
package com.example;

import java.lang.reflect.*;
import java.util.*;
import org.hibernate.bytecode.enhance.spi.*;
import org.hibernate.engine.spi.*;
import org.hibernate.proxy.*;

public class EntityImpl$HibernateProxy$5IwwkzRr extends EntityImpl implements HibernateProxy, ProxyConfiguration
{
    private ProxyConfiguration$Interceptor $$_hibernate_interceptor;
    private static final /* synthetic */ Method cachedValue$2E8Sfxj8$k44q0v3;

    static {
        cachedValue$2E8Sfxj8$k44q0v3 = EntityImpl.class.getMethod("getFoobar", (Class<?>[])new Class[0]);
        cachedValue$2E8Sfxj8$k44q0v3 = EntityImpl.class.getMethod("setFoobar", Integer.TYPE);
    }
}
```
And the original entity would be along the lines of the following example

``` java
package com.example;

import com.infradna.tool.bridge_method_injector.WithBridgeMethods;
import javax.persistence.*;

@Entity
public class EntityImpl 
{
    @Access(AccessType.PROPERTY)
    @Column
    private Integer foobar;

    @WithBridgeMethods(value=int.class, castRequired=true, adapterMethod="convert")
    public Integer getLevel()
    {
        return foobar;
    }

    @Deprecated
    public void setLevel(int foobar)
    {
        this.foobar = foobar;
    }

    public void setLevel(Integer foobar)
    {
        this.foobar = foobar;
    }

   @SuppressWarnings("unused")
    private Object convert(Object value, Class targetType) { 
	    return value == null ? Array.get(Array.newInstance(targetType, 1), 0) : value;
    }
}
```

The `cachedValue$2E8Sfxj8$k44q0v3 = EntityImpl.class.getMethod("getFoobar", (Class<?>[])new Class[0]);` comes from Hibernate's Enhancer (big thanks for making that possible) and it's Javaassist roots where proxying was also done using invocation handler pattern. The downside in this approach is that reflection API is being relied upon and apparently I went and broke it with my "cleverness".

For reasons unknown to me (optimization perhaps) the `getMethod` returned sometimes the bridge method thus it did not verify the return type even though the class files permit ambiguity when searching only with name and parameter types. 

I was thinking if bytebuddy could lend a helping hand in a way of optionally testing the return type and using for instance `getMethods` to solve this kind of ambiguity out-of-the-box. `MethodGraph.Compiler` would be the answer if reflection API would not have been used in the Hibernate Enhancer implementation at all but I believe that it might not have been practical from `org.hibernate.proxy` standpoint when it needed to keep Javaassist still around.

If by a slim chance bytebuddy would provide such a fallback feature then possibly this could also be optionally made available in Hibernate Enhancer if I manage to ask them nicely enough. I doubt that `HibernateLookupDispatcher` - suggestion made in the #493 - kind of approach to solve what I'm trying to do here would gain any traction there, but perhaps a new entry in `WithCustomProperties` controlling `MethodDelegation` in `ByteBuddyState$ProxyDefinitionHelpers` might be more acceptable. 

``` java
PrivilegedAction<MethodDelegation> delegateToInterceptorDispatcherMethodDelegationPrivilegedAction =
	new PrivilegedAction<MethodDelegation>() {

	@Override
	public MethodDelegation run() {
		return MethodDelegation.to( ProxyConfiguration.InterceptorDispatcher.class );
	}
};
```

I opened the issue here if somebody else is as determined as I am to break the reflection API. I know I am since Kohsuke's nifty maven plugin has still it's merits after all these years and Hibernate Enhancer is a must. I just would have liked to see these two play along nicely.

**Comment by raphw** [comment]
So, the problem here is as follows: Byte Buddy needs to resolve type hierarchies and merge methods with compatible signatures, not only when it comes to the return type. For instance, the following classes would be created by *javac* for a generic type:

```java
class Foo<T> {
  T identity(T arg) { return arg; }
}
class Bar extends Foo<String> {
  /* synthetic bridge */ Object identity(Object arg) { return identifiy((String) arg); }
  String identity(String arg) { return arg; }
}
```

Both return types and argument types change for the method. Regardless, Byte Buddy needs to only overwrite one of the methods, otherwise, the interception would cause an indefinite recursion if a bridge method was invoked. Byte Buddy puts quite an effort into resolving methods correctly down the hierarchy; disregarding your (non-covariant) return type would break this mechanism.

When using reflection, the JVM returns methods randomly in newer VM releases to avoid that anybody returns in method order. Reflection is aware of bridge methods but I assume for your synthetically added methods, there is no good way for the VM to determine what method to return and thus returns it incorrectly some times by chance.

**Comment by TuomasKiviaho** [comment]
>  Byte Buddy puts quite an effort into resolving methods correctly down the hierarchy

Kudos for that from me.

> ; disregarding your (non-covariant) return type would break this mechanism.

The codebase to me in general seems to carry the return type as if it would be part of the signature (`MethodDescription$TypeToken` or `MethodDescription$SignatureToken`). In certain places I assume that there could be some optimizations that would omit the return type check since one should probably not be doing what I'm doing.

> When using reflection, the JVM returns methods randomly in newer VM releases to avoid that anybody returns in method order. Reflection is aware of bridge methods but I assume for your synthetically added methods, there is no good way for the VM to determine what method to return and thus returns it incorrectly some times by chance.

Yes. And the sad thing about this is that one needs to resolve to using `getMethods` and doing basically the same as what `getMethod` does under the hood. If it just would have an alternative where one could give the return type as well.  Similar glue code would be needed if one would need to resolve the actual type of the T in your example if the inheritance hierarchy would be just a bit more complicated. I'd call both of these scenarios as a sort of shortcomings in the reflection API.

**Comment by raphw** [comment]
Byte Buddy supports JVM signatures (including return type) all the way. It takes the JVM perspective everywhere but the default method graph compiler considers the Java perspective what is a reasonable default.

Since the reflection API also takes the Java perspective its really to screws to turn. Byte Buddy already allows you to plug any custom diapatchers and a custom method graph compiler, you can already accomplish what you want inside of it. In the end, it woukd be up to Hibernate to consider your use case, but I doubt it gets picked up. The bridges would really need to be equivalent to begin with, I don't think its the best API evolution strategy. This would better be solved by deprecation and adding methods with new names.
