### ISSUE TITLE
Injecting resources into a ClassLoader

### ISSUE THREAD

**Issue by anuraaga** [raphw/byte-buddy#921]
Currently, it's possible to inject `Class` bytecode into a `ClassLoader`

https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/ClassInjector.java

It doesn't seem to be possible to inject a resource. Is this something that could be added to byte-buddy? I'd love to be able to inject resources, such as a `logback.xml` into the classloader at runtime.

Thanks!

**Comment by raphw** [comment]
No, it's unfortunately not possible. The JVM only allows injecting classes into a class loader for which a generic API exists. Resources cannot be added.

**Comment by anuraaga** [comment]
@raphw I see - resources feel like they should be easier to deal with than classes :) But if there's no way to do it, then it is what it is. For reference, I am thinking of solving on the `ClassLoader` side itself by rewriting `getResource` to read from memory. I assume this is too high-level of an approach for byte-buddy but just in case it's interesting.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1172

**Comment by raphw** [comment]
When injecting classes, they are injected directly into the JVM handler of the class loader, the `loadClass` facilities are avoided. There is no equivalent for resources what is the issue here. The same is true when appending to a class loader using `Instrumentation`.
