### ISSUE TITLE
java.lang.VerifyError during class loading (Instruction type does not match stack map)

### ISSUE THREAD

**Issue by pfichtner** [raphw/byte-buddy#922]
During maven build some constructors are enhanced using a [net.bytebuddy.build.Plugin](https://github.com/pfichtner/jsr380-pg/blob/c3d5b299b5ad78dbc3f48eb5a89394ad66fe6a3c/src/main/java/com/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/AddJsr380ValidationPlugin.java#L50), the code added to the constructor(s) can be found [here](https://github.com/pfichtner/jsr380-pg/blob/c3d5b299b5ad78dbc3f48eb5a89394ad66fe6a3c/src/main/java/com/github/pfichtner/bytebuddy/pg/agent/Constructor.java#L17)

While this works without any issues on my local machine all builds of the travis build (openjdk8/11/14 and oraclejdk11) are not working: During class loading the verifier throws an exception: 
```
java.lang.VerifyError: Instruction type does not match stack map
Exception Details: Location:
    com/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/Person.<init>(Ljava/lang/String;Lcom/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/Person$auxiliary$JNmEMluC;)V @4: aload_2
  Reason:
    Type uninitializedThis (current frame, locals[2]) is not assignable to 'com/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/Person$auxiliary$JNmEMluC' (stack map, locals[2])
```

(see https://travis-ci.org/github/pfichtner/jsr380-pg)

**Comment by raphw** [comment]
It should fail on your local machine, too.

Constructors are oddballs in the Java world. They require another constructor call before any real interaction with the object. You can add another constructor call using MethodCall and append your delegation with andThen. Typically, you call a constructor of the super class.

**Comment by pfichtner** [comment]
Thank's for the advice, will check it out. 
As said, it does not fail on my local machine using 
```
$ java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7-Ubuntu-1ubuntu1)
OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing)

$ javac -version
javac 14.0.1

$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/xck10h6/bin/apache-maven-3.6.3
Java version: 14.0.1, vendor: Private Build, runtime: /usr/lib/jvm/java-14-openjdk-amd64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-42-generic", arch: "amd64", family: "unix"
```

**Comment by pfichtner** [comment]
What makes me wonder: My ideas was to **add** code to constructors (not to replace existing code there). So there already should already be a call to the superclass' constructor. Am I wrong?

**Comment by raphw** [comment]
Using `SuperMethodCall.INSTANCE.andThen(MethodDelegation.to(...))` you can add code to the end, but you can also combine them the other way. Note that you cannot access `this` or field values if you do it before. By using rebasing (the default), the code will be added.

**Comment by pfichtner** [comment]
Not able to get it working :-/

While the [JavaAgent](https://github.com/pfichtner/jsr380-pg/blob/f4d7319532734399b94804ba187b68bd09591d6a/src/main/java/com/github/pfichtner/bytebuddy/pg/_3_no_anno_with_agent/Agent.java#L27) does work for weeks like expected, the [Plugin](https://github.com/pfichtner/jsr380-pg/blob/f4d7319532734399b94804ba187b68bd09591d6a/src/main/java/com/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/AddJsr380ValidationPlugin.java#L51) does not (did change the code as suggested). 

The original constructor
```
public Person(final String s) {
    this.name = s;
}
```
now becomes
```
public Person(final String s) {
    this(s, null);
    Constructor.exitConstructor(s);
}
```
but **should** become
```
public Person(final String s) {
    this.name = s;
    Constructor.exitConstructor(this);
}
```
Code decompiled using procyon. Any help welcome.

**Comment by raphw** [comment]
If you are using delegation, the above is expected because the original code (via `SuperMethodCall`) needs to be placed somewhere what Byte Buddy manages for you. If you want to do the latter, you need to use `Advice` but using the `.visit` method. In the Advice, you can simply invoke your static interceptor method manually, the advice code template with `@OnMethodExit` is then copied as byte code into the target method.

**Comment by pfichtner** [comment]
Many thanks @raphw , got it! Didn't realize this option. Now it works as expected! :-)

**Comment by pfichtner** [comment]
Unfortunately it does not work :-/

I don't understand why 
```builder.constructor(any()).intercept(to(Constructor.class)))``` 
works using [Agent](https://github.com/pfichtner/jsr380-pg/blob/f4d7319532734399b94804ba187b68bd09591d6a/src/main/java/com/github/pfichtner/bytebuddy/pg/_3_no_anno_with_agent/Agent.java#L27) while 
```builder.constructor(any()).intercept(to(Constructor.class))```
using [Plugin](https://github.com/pfichtner/jsr380-pg/blob/01c44d3d1ddcea3d18d204cc6cf2bf0a3d3a959b/src/main/java/com/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/AddJsr380ValidationPlugin.java#L50) does not. 

Do they differ? Why don't they work identically? 

Where do I have to use (override?) the visit method? 
Thanks in advance!

**Comment by pfichtner** [comment]
@raphw could you please give me a hint? Thanks! :-)

**Comment by raphw** [comment]
There should not really be any difference. Can you run using `-Dnet.bytebuddy.dump=/some/folder`? This outputs the generated byte code so I could easily tell what the difference is.

How did you setup the plugin compared to the agent? Are you using rebasing versus redefinition? I have a feeling that that's the issue. You can change the plugin to use redefinition what is sensible for advice by setting an entry point in your build tool.

**Comment by pfichtner** [comment]
I did add jvm.options and plugin options REDEFINE to pom.xml using a separate branch named [issue](https://github.com/pfichtner/jsr380-pg/tree/issue)
Running `mvn clean package -Djvm.options="-Dnet.bytebuddy.dump=/some/folder"`with plugin REDEFINE configuration fails
`[ERROR] Failed to execute goal net.bytebuddy:byte-buddy-maven-plugin:1.10.17:transform (default) on project jsr380-pg: Failed to transform class files in /home/myuser/git/jsr380-pg/target/classes: Cannot call super (or default) method for public com.github.pfichtner.bytebuddy.pg._4_no_anno_apt.Person(java.lang.String) -> [Help 1]
`
The whole project is just for playing around with bytebuddy and less than 300 LOCs javacode, so it would be great if you could get a deeper look in it. Any help welcome! Thanks

**Comment by raphw** [comment]
So, if you are using `Advice` via interception and with `REDEFINE`, Byte Buddy replaces the original method (or constructor) with a new method that replaces the old one. With `REBASE`, it retains the original code.

What you however want to do is to decorate the method what you can do by

```java
builder.visit(Advice.to(Constructor.class).on(isConstructor()))
```

**Comment by pfichtner** [comment]
Thanks for your support but still not working. 

```
java.lang.VerifyError: 
Instruction type does not match stack map
Exception Details:
  Location:
    com/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/Person.<init>(Ljava/lang/String;Lcom/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/Person$auxiliary$aBnorwiy;)V @4: aload_2
  Reason:
    Type uninitializedThis (current frame, locals[2]) is not assignable to 'com/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/Person$auxiliary$aBnorwiy' (stack map, locals[2])
```
see https://travis-ci.org/github/pfichtner/jsr380-pg/jobs/737216202#L1319

While all CI build breaks with this issue in contrast all my local builds all working (as I mentioned in my first post, too). Why the local build does not fail is absolutely not explainable to me. Even more because procyon locally now fails trying to decompile the class: 
```
public Person(final String p0) {
    // 
    // This method could not be decompiled.
    // 
    // Original Bytecode:
    // 
    //     1: astore_2       
    //     2: aload_1        
    //     3: astore_3        /* name */
    //     4: aload_2         /* this */
    //     5: invokespecial   java/lang/Object.<init>:()V
    //     8: aload_2         /* this */
    //     9: aload_3         /* name */
    //    10: putfield        com/github/pfichtner/bytebuddy/pg/_4_no_anno_apt/Person.name:Ljava/lang/String;
    //    13: goto            16
    //    16: invokestatic    javax/validation/Validation.buildDefaultValidatorFactory:()Ljavax/validation/ValidatorFactory;
    //    19: invokeinterface javax/validation/ValidatorFactory.getValidator:()Ljavax/validation/Validator;
    //    24: aload_0        
    //    25: iconst_0       
    //    26: anewarray       Ljava/lang/Class;
    //    29: invokeinterface javax/validation/Validator.validate:(Ljava/lang/Object;[Ljava/lang/Class;)Ljava/util/Set;
    //    34: astore_2       
    //    35: aload_2        
    //    36: invokeinterface java/util/Set.isEmpty:()Z
    //    41: ifne            53
    //    44: new             Ljavax/validation/ConstraintViolationException;
    //    47: dup            
    //    48: aload_2        
    //    49: invokespecial   javax/validation/ConstraintViolationException.<init>:(Ljava/util/Set;)V
    //    52: athrow         
    //    53: goto            56
    //    56: return         
```

**Comment by pfichtner** [comment]
For safety reasons I purged all lombok annotations from the target class jPerson) just to be sure the issue is not caused by lombok / bytebuddy clashes during compile time but the problem still remains.

**Comment by raphw** [comment]
Is your Jenkins running another agent? 

In your case, I'd try using `Advice` what is more friendly with constructors and allows for inlining.
