### ISSUE TITLE
have a hello world example for android??

### ISSUE THREAD

**Issue by jayjupdhig** [raphw/byte-buddy#924]
no matter what i do, i always get that on android:

```
I/System.out: class java.lang.IllegalArgumentException: null
```

Code from your example:

```

							Class<?> dynamicType = new ByteBuddy()
									.subclass(Object.class)
									.method(ElementMatchers.named("toString"))
									.intercept(FixedValue.value("Hello World!"))
									.make()
									.load(getClass().getClassLoader())
									.getLoaded();
```

So please not no RTFM-comments, i just need a similar simple example for android.

thx.

kind regards,
jan

**Comment by jayjupdhig** [comment]
and it sould be compatible to android 7 and upwards...

**Comment by jayjupdhig** [comment]
and the files i included:

- byte-buddy-android-1.10.14.jar
- byte-buddy-agent-1.10.14.jar
- byte-buddy-dep-1.10.14.jar


Correct ones or not?

**Comment by raphw** [comment]
The agent won't work on Android. You only need the android module which offers you a `AndroidClassLoadingStrategy`. If you provide this as the second argument to the `.load` step in Byte Buddy, it should work on Android. There's not more to it than that.

**Comment by jayjupdhig** [comment]
thank you very much - will look about it.

with kind regards,
jan

**Comment by jayjupdhig** [comment]
`new AndroidClassLoadingStrategy.Wrapping(this.getDir("dexgen", Context.MODE_PRIVATE)`

Is that the correct code?

**Comment by jayjupdhig** [comment]
does not work, solved by an "unclean" oo design which solves the problem better than your lib...

**Comment by raphw** [comment]
That's the code but 'does not work' does not give me much to work with.
