### ISSUE TITLE
How to reduce our startup time overhead of instrumentation which uses Method delegation,Morph&Advices

### ISSUE THREAD

**Issue by vipinCheck536** [raphw/byte-buddy#926]
We are working on a Java agent to inject tracing information in various Http libraries, and we have been getting reports that the agent is causing significant increase in startup times for larger applications. In some anecdotal cases start up used to be 30 seconds but is now more than 10 minutes with the agent installed. We looked at chaining transforms by using asDecorator() ( issue-521) but seems like it is deprecated in 1.9. Do you have any suggestions to reduce startup time?

Our patterns:

Pattern 1:
agentBuilder.type(ElementMatchers.hasSuperType(ElementMatchers.named("SomeClassPath")).transform((builder, typeDescription, classLoader, module) -> {
            return builder.method(ElementMatchers.named("service")).intercept(MethodDelegation.to(MyLogic.class));
        });

Pattern 2:

agentBuilder.type(ElementMatchers.named("SomeClassPath1")).transform((builder, typeDescription, classLoader, module) -> {
            return builder.method(ElementMatchers.named("somemethod2")).intercept(MethodDelegation.withDefaultConfiguration().withBinders(new ParameterBinder[]{Binder.install(MyLogic2.Morpher.class)}).to(MyLogic2.getClass()));
        })

Pattern 3:
 agentBuilder.with(NoOp.INSTANCE).with(RedefinitionStrategy.REDEFINITION).with(Default.REDEFINE).type(createTypeMatcher()).transform((builder, typeDescription, classLoader, module) -> {
            return builder.visit(Advice.to(SomeClassPath2.class).on(ElementMatchers.named("somemethod2")));
        });

**Comment by raphw** [comment]
Did you configure any caches for your agent? The type pool strategy should use one. Are you instrumenting too many classes? The listener facility can give you insight here. Did you configure efficient ignore matchers? A lot of code does not typically require processing.

**Comment by vipinCheck536** [comment]
Did you configure any caches for your agent? The type pool strategy should use one. 

-----> We are not using one as of now. Do you have a sample?

Are you instrumenting too many classes? The listener facility can give you insight here. 

------> Working on collectiong metrics and will update by 09/15.

Did you configure efficient ignore matchers? A lot of code does not typically require processing.

-----> Investigate on this topic and will update soon.

**Comment by raphw** [comment]
As for a cache, the easiest approach would be using the preimplemented cache: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/agent/builder/AgentBuilder.java#L2793

For a better solution, you'd start using a caching framework as a plain concurrent hash map would never be cleared even after all transformations have been applied.

**Comment by vipinCheck536** [comment]
Thanks @raphw,

We will try it and keep you posted.


Thanks,
Sai
