### ISSUE TITLE
FieldAccessor.ForImplicitProperty.setsValue(Object) throws NullPointerException for null argument (not documented)

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#931]
I [consulted the relevant javadocs](https://javadoc.io/static/net.bytebuddy/byte-buddy/1.10.16/net/bytebuddy/implementation/FieldAccessor.ForImplicitProperty.html#setsValue-java.lang.Object-) but had to learn from trial and error that supplying `null` as an argument will result in a `NullPointerException`, since a [blind invocation of `getClass()` is attempted](https://github.com/raphw/byte-buddy/blob/3fef9b8ac7f44b85b1fc579eae60e843c0873d09/byte-buddy-dep/src/main/java/net/bytebuddy/implementation/FieldAccessor.java#L684).  This does not appear to be documented.

**Comment by raphw** [comment]
That can be fixed and should be, it's an easy patch. I'll add it before the next release.

**Comment by raphw** [comment]
Fixed on master.
