### ISSUE TITLE
Feature Request: Better Granularity ins Working With ByteCode

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#933]
Can we have better granularity in woking with ByteCode. E.g. go through all catch blocks and add a logger. Add login of all method parameters and return types. Etc.

In order to do this:
- there should be a very efficient bytecode query system
- ability to access each construct like loops, try-catch blocks, if statements, method calls, statements, etc.
- transform bytecode at this granular level

[Spoon](https://github.com/INRIA/spoon) does this at the sourcecode level. Is it possible to extend ByteBuddy to be able to do it at the bytecode level?

**Comment by raphw** [comment]
On the source code level, such high level constructs exist and can be traversed as you know them from source code. In byte code, they do not. You can however use ASM to traverse byte code which is exposed in Byte Buddy. Have a look at `AsmVisitorWrapper` for this.
