### ISSUE TITLE
Java generic multiple bound

### ISSUE THREAD

**Issue by ericfoongcheesoon** [raphw/byte-buddy#939]
I am using bytebuddy 1.10.16. 

I want to create Data.java that has multiple bound type argument in byte buddy:
Class User { }
interface EntityIntf { }

class Data <T extends User & EntityIntf> { }

How can I create the multiple bound generic in bytebuddy? Can you please provide the guideline?

**Comment by raphw** [comment]
The `typeVariable` step allows for specifiying multiple bound: https://javadoc.io/static/net.bytebuddy/byte-buddy/1.10.4/net/bytebuddy/dynamic/DynamicType.Builder.html#typeVariable-java.lang.String-net.bytebuddy.description.type.TypeDefinition...-

**Comment by ericfoongcheesoon** [comment]
thank you for your information.

The solution can be used to create the multi bound generic.
