### ISSUE TITLE
Cannot find net.bytebuddy.dynamic.ElementMatchers

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#940]
Since `https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/matcher/ElementMatchers.java` is in `byte-buddy-dep` I have included:

```gradle
    implementation group: 'net.bytebuddy', name: 'byte-buddy', version: "$byteBuddyVersion"
    implementation group: 'net.bytebuddy', name: 'byte-buddy-dep', version: "$byteBuddyVersion"
```

But InteliJ compaints:

![image](https://user-images.githubusercontent.com/637415/95208621-fb11b600-0806-11eb-9936-a0512f2be539.png)

Also there is this:

> # Byte Buddy (with Dependencies)

> Byte Buddy is a Java library for creating Java classes at run time. This artifact is a build of Byte Buddy with a remaining dependency onto ASM. You should never depend on this module without repackaging Byte Buddy and ASM into your own namespace.

Source: https://mvnrepository.com/artifact/net.bytebuddy/byte-buddy-dep

**Comment by raphw** [comment]
Replace *dynamic* with *matchers*.
