### ISSUE TITLE
Introduce: Plugin.Agent & Plugin.LoadTime to reuse plugin implementation with agents and class loading

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#943]
In order to write a plugin and reuse the same code at build time and load time, is it possible to add the ability to apply plugin bytecode changes at load time? The changes can be through an agent and/or at class loading.

**Comment by raphw** [comment]
Yes, this is possible. There is a transformer to wrap a build-plugin: https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/agent/builder/AgentBuilder.java#L2195
