### ISSUE TITLE
Advice.NewField to introduce a static and non static fields to store class level data between evocations

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#944]
Add something like `Advice.NewField` akin to `Advice.Local` but to declare a class-level field which can be static or non-static. This can be used to store variables at the object level as a non-static field and at the class level as a static field.

**Comment by raphw** [comment]
you can always define a field using Byte Buddy's `DynamicType.Builder` API which will be available from the advice as a consequence.
