### ISSUE TITLE
More Control Over Advice

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#946]
<strike>Can the `Advice` be made more granular in addition to the currently existing ones as there are times can one do not bother about if a method is static, instance or a constructor. In this case, the current `Advice` is fine. So can the following be added:
- `Advice.OnInitialisersEnter`, `Advice.InitialisersEnter` - start of initilisation - start of 1st initilisation block
- `Advice.OnInitialisersExit`, `Advice.InitialisersExit` - end of initilisation - end of last initilisation block
- `Advice.OnInitialiserBlockEnter`, `Advice.InitialiserBlockEnter`
- `Advice.OnInitialiserBlockExit`, `Advice.InitialiserBlockExit`
- `Advice.OnStaticInitialisersEnter`, `Advice.StaticInitialisersEnter`
- `Advice.OnStaticInitialisersExit`, `Advice.StaticInitialisersExit`
- `Advice.OnStaticInitialiserBlockEnter`, `Advice.StaticInitialiserBlockEnter`
- `Advice.OnStaticInitialiserBlockExit`, `Advice.StaticInitialiserBlockExit`
- `Advice.OnConstuctorsEnter`, `Advice.ConstuctorsEnter` - start of construction - start of 1st constructor
- `Advice.OnConstuctorsExit`, `Advice.ConstuctorsExit` - end of construction - end of last constructor
- `Advice.OnConstuctorEnter`, `Advice.ConstuctorEnter`
- `Advice.OnConstuctorExit`, `Advice.ConstuctorExit`
- `Advice.OnInstanceMethodEnter`, `Advice.InstanceMethodEnter`
- `Advice.OnInstanceMethodExit`, `Advice.InstanceMethodExit`
- `Advice.OnStaticMethodEnter`, `Advice.StaticMethodEnter`
- `Advice.OnStaticMethodExit`, `Advice.StaticMethodExit`</strike>

Maybe the same can be achieved with additional optional parameters to the existing annotations.

Also the `Advice.to` class can also have:
- `Advice.Static` (default, current behaviour)
- `Advice.Singleton` - one singleton object created - only one object created which share fields across types, methods and instances
- `Advice.PerType` - one object per type - fields are shared across all methods and instances of the object
- `Advice.PerInstance` - one object per instrumented object - fields are shared with all methods in a given instance
- `Advice.PerMethod` - one object per method - fields are shared across the object for a given method
- `Advice.PerMethodInstance` - one object per method per instance - fields are for a given method per instance (non-static)
- `Advice.PerCall` - one object per call - fields are not shared are reinitialised every call
- `Advice.PerCaller` - one object per caller
- `Advice.PerCallerInstance` - one object per caller instance

Also: [this](https://github.com/raphw/byte-buddy/issues/941#issuecomment-706072070) and [this](https://github.com/raphw/byte-buddy/issues/944)

**Comment by raphw** [comment]
This would be too much to maintain and too broad of an API. Rather define multiple advice classes and then using matchers to only apply advice to the methods an advice is suited for.

Also, if you find this too repetitive, you can advice your advice before applying it.

**Comment by sirinath** [comment]
OK. 

May you can have a parameter like `Advice.OnMethodExit(for=Advice.Types.Constructors)`. This might be simpler.

Also AspectJ `per*` like `perthis`, `percflow`, etc. It will be good to have something like that.

**Comment by raphw** [comment]
I don't think that I want to offer such functionality, this would be confusing if the advice would not have passed the explicit, programmatic matcher and would therefore not be applied. It's simple enough to add an annotation and to register advices by discovering the annotation and applying a matcher based upon it, if that would be a meaningful feature to somebody.

**Comment by sirinath** [comment]
Can the instantiation model part of the issue be considered? This is the more important part than the matching part. So we can write something like `Advice.to(MyAdvices.class).instentiate(IntentionModel.PerClass).on(ElementMatchers.isMethod())`

**Comment by raphw** [comment]
I don't think I want to add more complexity into advice, it's rather difficult to maintain at it is and there is a thousand convenience shortcuts I could add, but generally I think that this functionality can already be emulated by adding an API on top of advice. This way, you can tailor your API after your demands and achieve the same thing.
