### ISSUE TITLE
Q: Is @Advice.Enter and @Advice.Exit Thread Safe

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#947]
When managing states through `@Advice.Enter` and `@Advice.Exit` can they get corrupted in multi-threading? If not can it be made thread-safe?

**Comment by raphw** [comment]
The advices are only templates and fully thread-safe. What do you mean by managing state? Reading values from annotated parameters are as thread-safe as they would be if you coded it manually. Byte Buddy is fully thread-safe.

**Comment by sirinath** [comment]
> What do you mean by managing state? Reading values from annotated parameters are as thread-safe as they would be if you coded it manually.

If the same method is evoked by many threads, does say `@Advice.Enter enter` or `@Advice.Exit exit` value will not get mixed up. This was my concern.

**Comment by raphw** [comment]
No, they will not be, they are stack allocated.
