### ISSUE TITLE
Enhancement to @Advice: @Advice.Caller, @Advice.Stack variables

### ISSUE THREAD

**Issue by sirinath** [raphw/byte-buddy#952]
Wondering if the following can be added:
- `@Advice.Caller` - `Method` or `String` with class and method information
- `@Advice.Stack` - `StackFrame` array or `Method` array or `String` array

If it is faster and efficient than `@Advice.This self` followed by `self.getClass()` introduce `@Advice.ThisType selfType`

**Comment by raphw** [comment]
You can already do `@Advice.Origin Class<?> type` what gives you the class of the method's declaring type.

You cannot access the caller of a method in Java other then creating an exception or using the stack walker API. Neither are compile-time constants so you can just extract this from your advice code.
