### ISSUE TITLE
Installing the agent via external process fails when java is running as root

### ISSUE THREAD

**Issue by NorbiPeti** [raphw/byte-buddy#953]
When running java as root it fails to attach the agent with the default settings. It produces the error described in #612 after creating a dump of all threads.
The steps described there, passing `-Djdk.attach.allowAttachSelf=true -XX:+StartAttachListener` fixes the issue.

When running it as a regular user, it works without needing these arguments.

Java version:
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

The application may run as root and it would be best if those arguments weren't required, if possible, or a more descriptive error would be helpful.

**Comment by raphw** [comment]
I assume that HotSpot does not start the attach thread for the root user, there's not much Byte Buddy can do since the JVM simply does not respond in this case what might mean about anything. I'll see if this is somehow detectable and issue another error if so.
