### ISSUE TITLE
Java varargs parameter

### ISSUE THREAD

**Issue by ericfoongcheesoon** [raphw/byte-buddy#960]
Greeting,

I have one question and I have try to find the solution myself for sometime, but find no solution. Please help.

How to add varargs parameter via defineMethod?
For example, 
public void test(int param1, String... param2){ }

How to create the param2 in defineMethod?

**Comment by raphw** [comment]
You need to define the second parameter as `String[]` type in the `defineMethod` step, and also set `MethodArguments.VARARGS` as a modifier.

**Comment by ericfoongcheesoon** [comment]
TQ for the information. The variable length argument can be added  using the MethodArguments:

.defineMethod("testMethod", String.class, Visibility.PUBLIC, MethodArguments.VARARGS)
.withParameters(int.class, String[].class)
.intercept(FixedValue.nullValue());

**Comment by ericfoongcheesoon** [comment]
Java permits parameter to have final modifier. How to add the final modifier to the parameter?

**Comment by raphw** [comment]
Use the `.withParameter(...)` step - without the *s* - it allows you to specify parameter names and modifiers.

**Comment by ericfoongcheesoon** [comment]
TQ for the information, the solution works.
