### ISSUE TITLE
FixedValue#value(Object) does not consider JavaConstant

### ISSUE THREAD

**Issue by ljnelson** [raphw/byte-buddy#961]
I'm aware that `FixedValue` has two `value` methods.  One takes a `JavaConstant` and the other takes an `Object`.

The one that takes an `Object` does not check to see if the `Object` is, itself, a `JavaConstant` implementation.  I think it should, and should then delegate to the `value(JavaConstant)` method.

(Obviously the work around is for the user herself to do the (tedious, boring) `instanceof` check before choosing which method to invoke.)

I'll file a PR soon.

**Comment by raphw** [comment]
The value methods should all support `TypeDescription`, `JavaConstant` and literal values, this is an oversight! Thanks for fixing!

**Comment by ljnelson** [comment]
See #962.
