### ISSUE TITLE
Update references to non-existent ofClassPath in the tutorial

### ISSUE THREAD

**Issue by asarkar** [raphw/byte-buddy#963]
The [tutorial](https://bytebuddy.net/#/tutorial) refers to various `ofClassPath` that don't exist in v1.10.17.
```
TypePool typePool = TypePool.Default.ofClassPath()
```
and
```
ClassFileLocator.ForClassLoader.ofClassPath()
```

**Comment by raphw** [comment]
Thanks, updated the references, it's `ofSystemLoader` for a while now.
