### ISSUE TITLE
Method annotation without @Target being attached to return type

### ISSUE THREAD

**Issue by bgaraude** [raphw/byte-buddy#966]
When using TypeDescriptions, if I have an annotated method with an annotation A whose attribute is another annotation B without @Target, then this attribute annotation B becomes a declared annotation on the method's return type.

If this is not clear, here is a test case reproducing the issue: https://gist.github.com/bgaraude/b5d1d608987803cf56e9e557295ad810

I experience this on 1.10.17.

I'm not sure if this is expected behavior or not, but it seems weird to me.

**Comment by bgaraude** [comment]
Thank for your answer (on the gist). It occurs with java 14.

But, I think I actually found the issue:
I tried to run the test case with java 15 through mvn, and it's successful. I tried several java versions (from 8 to 15) through mvn and they are all successful. However, if I run it through eclipse, it always fail (from java 8 to 14).

I think eclipse's java compiler generates some kind of "invalid" bytecode for these annotations. So it's probably an issue on eclipse JDT side.
In case you are interested, I've created a new test case containing the bytecode as generated by eclipse. Since the test case embeds the bytecode generated by eclipse, it also fails with mvn:
https://gist.github.com/bgaraude/b3b2fd59f1a93f75acd6c641b37a24bb

**Comment by raphw** [comment]
From the class file:

```
  public abstract get()Ljava/lang/String;
  @Lcom/foo/Annotations2Test$Ann;(value=@Lcom/foo/Annotations2Test$Ann$Child;(value="foo"))
  @Lcom/foo/Annotations2Test$Ann$Child;(value="foo") : METHOD_RETURN, null
```

You are right about the Eclipse compiler adding the annotation.
