### ISSUE TITLE
Illegal type annotations on parameter java.lang.Object arg0 using org.jetbrains.annotations.Nullable

### ISSUE THREAD

**Issue by yaohwu** [raphw/byte-buddy#967]
Similar problem https://github.com/raphw/byte-buddy/issues/843 happened to my project when using openJDK 1.8-191 on linux or 1.8-201-redhat on Windows.

The exception is that: 
`Illegal type annotations on parameter java.lang.Object arg0 for public abstract void xxx.agent.template.DynamicAccessor.beforeExecute(java.lang.Object,java.lang.reflect.Method,java.lang.Object[])
`.

The only illegal type annotation  of parameter `java.lang.Object` arg0 is "`org.jetbrains.annotations.Nullable`"

The solution https://github.com/raphw/byte-buddy/issues/843#issuecomment-618843112 works for me, too. But there is a different reason from #843. Is there anyway better to fix it ?

**Comment by raphw** [comment]
No, the validation is checking all properties of a class. It helps as a filter for people coming and asking questions where the exception can hopefully guide them to a solution instead. If you want to ignore a conceptually incorrect class - with annotations the JVM ignores it - you can and should disable the validation.

**Comment by yaohwu** [comment]
https://github.com/raphw/byte-buddy/issues/1185
