### ISSUE TITLE
Intercepting Loaded Class

### ISSUE THREAD

**Issue by saden1** [raphw/byte-buddy#97]
I have a use case where a user supplies a Class<?> as input and I need to intercept all instances of this class to perform some business operations. I can't subclass the class because doing so means a new instance of the class will be created and this can result in two instances of the class being detected in the classpath. I can't redefine the class because that would mean I would need a concrete class to replace it and I would lose information in the original class. This leaves me with rebase and/or Java Agent as the the only option right?

The documentation on writing a Java Agent is not clear and I was wondering how do I write one that allows me to take in a specific class as input and intercept class to methods in this class? I have tried a few things without much success. Here is test case of usecase and what I have tried so far.

```java
import java.util.concurrent.Callable;
import net.bytebuddy.ByteBuddy;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.dynamic.ClassFileLocator;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.implementation.MethodDelegation;
import net.bytebuddy.implementation.bind.annotation.AllArguments;
import net.bytebuddy.implementation.bind.annotation.RuntimeType;
import net.bytebuddy.implementation.bind.annotation.SuperCall;
import static net.bytebuddy.matcher.ElementMatchers.isDeclaredBy;
import static net.bytebuddy.matcher.ElementMatchers.not;
import net.bytebuddy.pool.TypePool;
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.Test;

public class RebaseTest {

    /**
     * Works but only if you have string representation of the class name. I
     * only have the Class and if I call Class#getName() the class gets loaded.
     */
    @Test
    public void testRebase_Works() {
        //Class<?> type = Greeting.class;
        String className = "com.fitbur.testcase.bytebuddy.RebaseTest$Greeting";
        TypePool typePool = TypePool.Default.ofClassPath();
        TypeDescription typeDescription = typePool.describe(className).resolve();
        ClassFileLocator locator = ClassFileLocator.ForClassLoader.ofClassPath();

        new ByteBuddy().rebase(typeDescription, locator)
                .method(not(isDeclaredBy(Object.class)))
                .intercept(MethodDelegation.to(new GreetingInterceptor()))
                .make()
                .load(ClassLoader.getSystemClassLoader(), ClassLoadingStrategy.Default.INJECTION);

        Greeting greeting = new Greeting();
        String result = greeting.phrase();
        assertThat(result).endsWith("!");
    }

//    /**
//     * Throws AssertionError because calls are not intercepted
//     */
//    @Test
//    public void testRebase_DoesNotWork() {
//        new ByteBuddy().rebase(Greeting.class)
//                .method(not(isDeclaredBy(Object.class)))
//                .intercept(MethodDelegation.to(new GreetingInterceptor()))
//                .make()
//                .load(ClassLoader.getSystemClassLoader(), ClassLoadingStrategy.Default.CHILD_FIRST);
//
//        Greeting greeting = new Greeting();
//        String result = greeting.phrase();
//        assertThat(result).endsWith("!");
//    }

//    /**
//     * Throws UnsupportedOperationException: class redefinition failed:
//     * attempted to change the schema (add/remove fields)
//     */
//    @Test
//    public void testRebase_DoesNotWork1() {
//        ByteBuddyAgent.install();
//        new ByteBuddy().rebase(Greeting.class)
//                .method(not(isDeclaredBy(Object.class)))
//                .intercept(MethodDelegation.to(new GreetingInterceptor()))
//                .make()
//                .load(ClassLoader.getSystemClassLoader(), ClassReloadingStrategy.fromInstalledAgent());
//
//        Greeting greeting = new Greeting();
//        String result = greeting.phrase();
//        assertThat(result).endsWith("!");
//    }

    public static class Greeting {

        public String phrase() {
            return "Hello";
        }

        public String phrase(String phrase) {
            return phrase;
        }
    }

    public static class GreetingInterceptor {

        @RuntimeType
        public Object intercept(@SuperCall Callable<?> zuper, @AllArguments Object... args) throws Exception {
            return zuper.call() + "!";
        }
    }

}
```

**Comment by raphw** [comment]
What you are trying to do is unfortunately not supported by the JVM. There is an enhancement proposal for [JEP 159](http://openjdk.java.net/jeps/159) that wants to add this feature in a future release of HotSpot but I would be surprised to see it merged before Java 10.

You can currently only instrument a class when you fully replace a method, e.g. apply a redefinition instead of rebasing a class. And even then you must not add fields (implcitily done when delegating to an instnace). 

What you can do as a work-arround is to preemtively instrument all classes and to switch out the interceptor on demand. E.g. do the following:

```java
interface MyInterceptor {
  Object intercept(@SuperCall Callable<?> zuper, @AllArguments Object... args) throws Exception;
}

class NoOp implements MyInterceptor {
  @Override
  Object intercept(@SuperCall Callable<?> zuper, @AllArguments Object... args) throws Exception {
    return zuper.call();
  }
}

class FieldSetter {
  static void (@This Object value) throws Exception {
    value.getClass().getDeclaredField("foo").set(value, new NoOp());
  }
}

new ByteBuddy().rebase(typeDescription, locator)
  .method(not(isDeclaredBy(Object.class)))
  .intercept(MethodDelegation.toInstanceField("foo", MyInterceptor.class)))
  .constructor(any())
  .intercept(SuperMethodCall.INSTANCE.andThen(MethodDelegation.to(FieldSetter.class)))
  .make()
  .load(ClassLoader.getSystemClassLoader(), ClassLoadingStrategy.Default.INJECTION);
```

Does this serve your purposes?

**Comment by saden1** [comment]
Thanks for the quick response. I can redefine a method and I don't need to add any fields but I must deal with loaded classes. Can I redefine a method of a loaded class?

**Comment by raphw** [comment]
Hi, the thing is that `MethodDelegation.to(new GreetingInterceptor())` needs to define a synthetic field on the generated class to store `new GreetingInterceptor()`. If you use `MethodDelegation.to(GreetingInterceptor.class)`, this does not happen (just declare the method static).

In this case, you can redefine a class (not rebase). This way, you are however loosing the original method's code.

**Comment by saden1** [comment]
I'm a bit confused. In your example you used rebase but earlier mentioned that due to JVM limitation we can't define fields. Also, I must use typeDescription and loader or can I just use Greeting.class?

**Comment by raphw** [comment]
You need to apply the instrumentation at the beginning at your program but in such a generic way that you can exchange the behavior on demand only. So instead of redefining a class, you implement it to always delegate the behavior to custom code, in this case the `MyInterceptor`.

You can then implement this interface and set the field value by `value.getClass().getDeclaredField("foo").set(value, new MyCustomInterceptor())` if you need a behavioural change. This way, you can avoid the necessary redefnition of the class, you piggy back on behavior that you have already implemented.

**Comment by saden1** [comment]
Got it. I'm still wrangling with whether it is possible to take in a class (Greeting.class) and rebase it. I was thinking of a) loading the class and capturing the name of the class, b) creating a new classloader, c) setting the current classloader to the new classloader and d) finally used the name captured in step a to rebase the class. 


Do you think that could work?

**Comment by raphw** [comment]
You can always rebase the class but it is not legal to substitute the loaded class with its rebased version. You can however always represent the class as an interface within your application and then load the rebased version of the class with another class loader. This does however result in your instances being retained and you would need to capture and transfer their state in some form.

Substituting class loaders is not permitted by the JVM.

**Comment by saden1** [comment]
I understand. Thank you for all the help.

**Comment by pippoflow** [comment]
> What you are trying to do is unfortunately not supported by the JVM. There is an enhancement proposal for [JEP 159](http://openjdk.java.net/jeps/159) that wants to add this feature in a future release of HotSpot but I would be surprised to see it merged before Java 10.
> 
> You can currently only instrument a class when you fully replace a method, e.g. apply a redefinition instead of rebasing a class. And even then you must not add fields (implcitily done when delegating to an instnace).
> 
> What you can do as a work-arround is to preemtively instrument all classes and to switch out the interceptor on demand. E.g. do the following:
> 
> ```java
> interface MyInterceptor {
>   Object intercept(@SuperCall Callable<?> zuper, @AllArguments Object... args) throws Exception;
> }
> 
> class NoOp implements MyInterceptor {
>   @Override
>   Object intercept(@SuperCall Callable<?> zuper, @AllArguments Object... args) throws Exception {
>     return zuper.call();
>   }
> }
> 
> class FieldSetter {
>   static void (@This Object value) throws Exception {
>     value.getClass().getDeclaredField("foo").set(value, new NoOp());
>   }
> }
> 
> new ByteBuddy().rebase(typeDescription, locator)
>   .method(not(isDeclaredBy(Object.class)))
>   .intercept(MethodDelegation.toInstanceField("foo", MyInterceptor.class)))
>   .constructor(any())
>   .intercept(SuperMethodCall.INSTANCE.andThen(MethodDelegation.to(FieldSetter.class)))
>   .make()
>   .load(ClassLoader.getSystemClassLoader(), ClassLoadingStrategy.Default.INJECTION);
> ```
> 
> Does this serve your purposes?

Hi Raphael,

I was searching for a solution to a similar problem before I came across this post, I know it's very old and I'm sorry I add comment if I'm not supposed to. I tried your code above and it didn't work, because 1) the original class doesn't have a field named "foo"; 2) `.intercept(SuperMethodCall.INSTANCE.andThen(MethodDelegation.to(FieldSetter.class)))` is attempting to add a method when rebasing. Could you explain how to make it work in this case? 
To be more specific, if 1) I'm to rebase a class; 2) I want to add a field to it; 3) I want every method in the rebased class to be intercepted by methods defined in the added field in 2). Is this possible?

Thanks.

**Comment by raphw** [comment]
If you can add fields, you can also add methods and if the former is impossible, the latter also is.

Byte Buddy does not have any constraints on what you would like to to from your above list, they all are VM related. What exactly is it what you are trying to achived?
