### ISSUE TITLE
The advice method not be excuted when I try to intercept submit() or execute() of ThreadPoolExecutor

### ISSUE THREAD

**Issue by the-valley** [raphw/byte-buddy#972]
Hello, I meet some problems.
When I try to intecept submit() or execute() of ThreadPoolExecutor, but the advice method not be executed. Bytebuddy version :1.10.16 ,byte-buddy-agent version: 1.10.14

Full code below:
`    public static void main(String[] args) throws Exception {

        final ThreadPoolExecutor service = new ThreadPoolExecutor(1,
                1, 60,
                TimeUnit.SECONDS, new LinkedBlockingDeque<>());
        service.execute(() -> System.out.println("test"));
        new AgentBuilder.Default()
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .disableClassFormatChanges()
                // 默认情况下是忽略了jdk类的，所以需要指定忽略的类来覆盖默认值
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy."))
                .type(ElementMatchers.named("java.util.concurrent.ThreadPoolExecutor"))
                .transform(new AgentBuilder.Transformer() {
                    @Override
                    public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder,
                                                            TypeDescription typeDescription,
                                                            ClassLoader classLoader,
                                                            JavaModule module) {
                        return builder.visit(Advice.to(SubmitAdvice.class)
                                .on(ElementMatchers.named("execute")));
                    }
                }).installOn(ByteBuddyAgent.install());

        service.execute(() -> System.out.println("test"));
        service.shutdown();

    }`

`public class SubmitAdvice {
    @Advice.OnMethodEnter
    public static void onMethodEnter(@Advice.Argument(value = 0, readOnly = false) Runnable task) {
        System.out.println("hello");
    }

    @Advice.OnMethodExit
    public static void onMethodExit(@Advice.Origin Method method, @Advice.AllArguments Object[] arguments, @Advice.Return Object ret) {

    }
}`

Any help is appreciated!

Thank you!

**Comment by raphw** [comment]
Did you try to register a listener to see if the instrumentation failed?

You can do so by:

    .with(AgentBuilder.Listener.StreamWriting.toSystemOut())

**Comment by the-valley** [comment]
Thank you, I have solved the problem, the method can intercepted normally.
But i meet another one, I want wrap the argument of Runnable in advice, so I create a util-class and static method.
The code below:
`
@Advice.OnMethodEnter
    public static void onMethodEnter(@Advice.Origin String method, @Advice.AllArguments(readOnly = false, typing = Assigner.Typing.DYNAMIC) Object[] allArgs) {
        System.out.println("hello");
        if (allArgs.length != 0) {
            if (allArgs[0] instanceof Runnable) {
                allArgs[0] = WrapUtil.wrapperRunnable(((Runnable) allArgs[0]));
            }
            if (allArgs[0] instanceof Callable) {
                allArgs[0] = WrapUtil.wrapperCallable(((Callable) allArgs[0]));
            }
        }
    }
`
Run the code and get some error below:
`
Exception in thread "main" java.lang.NoClassDefFoundError: com/test/agent/test3/wrapper/WrapUtil
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:110)
	at com.test.agent.test3.TestMain4.main(TestMain4.java:40)
`
Any help is appreciated!

Thank you!

**Comment by raphw** [comment]
You cannot refer to classes of your agent in code that is inlined into the bootstrap class loader such as `WrapUtil`. You need to inject this code into the appropriate class loader (and module) to reach it. It would however be easier to code out everything within the advice method.

**Comment by the-valley** [comment]
Thanks very much, but how can i inject the code into the appropriate class loader so that I can reach it? or is there some demo code as reference?

**Comment by the-valley** [comment]
So thankful for your help. The jar file of codes is attached to the BootstrapClassloader by using the Instrument and it works.  Thanks.

**Comment by raphw** [comment]
Glad you figured it out!
