### ISSUE TITLE
How to mock a loaded class?

### ISSUE THREAD

**Issue by lwsbox** [raphw/byte-buddy#974]
`
public class Tester{

    public static void test2() {

        ByteBuddyAgent.install();
        AgentBuilder.Transformer transformer = new AgentBuilder.Transformer() {
            @Override
            public DynamicType.Builder<?> transform(DynamicType.Builder<?> builder, TypeDescription typeDescription, ClassLoader classLoader, JavaModule javaModule) {
                return builder.method(ElementMatchers.any()).intercept(MethodDelegation.to(MockInterceptor.class)); 
            }
        };

        new AgentBuilder
                .Default()
                .type(ElementMatchers.any())
                .transform(transformer)
                .with(new AgentListener())
                .installOnByteBuddyAgent();
    }

    public static void test1() {
        Man man = new Man();
        man.doNothing();
    }
    public static void main(String[] args) 
        Tester.test1();
        Tester.test2();
        Tester.test1();
    }
}
`

if Tester.test1() run before Tester.test2(),  can't delegate the man.doNothing().   
I want to delegate the method in dynamic for mocking method. (not in premain, target class may be loaded.)
if I use advice, I can't find the way to mock a result and skip the  @method.
how to do ?
Thanks.

**Comment by raphw** [comment]
Have a look at `RetransformationStrategy` which you register in the agent builder, typically in combination with `disableClassFormatChanges()`. It is normally better to use `Advice` then rather then delegation.

**Comment by lwsbox** [comment]
I add the setting(disableClassFormatChanges() and RedefinitionStrategy.RETRANSFORMATION  as follow:
but it doesn't work, what's wrong?  
Tester.test2(); must run before Tester.test1();  so that the man.doNothing(); can be delegated.

 ```
new AgentBuilder
                .Default()
                .disableClassFormatChanges()
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .type(ElementMatchers.any())
                .transform(transformer)
//                .with(new AgentListener())
                .installOnByteBuddyAgent();
``` 

Can Advice be used to modify the return value and skip the method?

Thanks.

**Comment by raphw** [comment]
Yes, it's documented in the javadoc.

**Comment by lwsbox** [comment]
As follow solution?  
https://stackoverflow.com/questions/50237592/is-it-possible-to-return-from-a-method-using-advice-onmethodenter
> Yes, it's documented in the javadoc.

**Comment by raphw** [comment]
Yes!

**Comment by lwsbox** [comment]
> Yes!

Thanks  a lot.  I have done what I need  with your help.
