### ISSUE TITLE
How to avoid method which be overridden intercepted by Advice repeatly?

### ISSUE THREAD

**Issue by blackbk** [raphw/byte-buddy#977]
Agent code:

```
public class Agent {
    public static void premain(String arguments, Instrumentation instrumentation) {
        new AgentBuilder.Default()
                .type(ElementMatchers.hasSuperType(ElementMatchers.named(
                        "demo.Api")))
                .transform((builder, type, classLoader, module) -> builder
                        .method(ElementMatchers.namedOneOf("hello", "bye"))
                        .intercept(Advice.to(DemoAdvice.class))
                )
                .installOn(instrumentation);
    }
}
```

```
public class DemoAdvice {
    @Advice.OnMethodExit
    public static void after(@Advice.Origin String method) {
        System.out.println("Invoke method " + method);
    }
}
```

App code:

```
public interface Api {
    void hello();
    void bye();
}
```

```
public class Parent implements Api {
    @Override
    public void hello() {
        System.out.println("Parent say hello!");
    }
    @Override
    public void bye() {
        System.out.println("Parent say bye!");
    }
}
```

```
public class Child extends Parent{
    @Override
    public void hello() {
        System.out.println("Child say hello!");
    }
}
```

===============================

Run Test:

```
Api api = new Child();
api.hello();
api.bye();
```

===============================
Output:

```
Child say hello!
Invoke method public void demo.Child.hello()
Parent say bye!
Invoke method public void demo.Parent.bye()
Invoke method public void demo.Parent.bye()
```

What I expected:

```
Child say hello!
Invoke method public void demo.Child.hello()
Parent say bye!
Invoke method public void demo.Parent.bye()
```

I decode the Child.class, `super.bye()` be added into Child#bye, then Advice intercept twice. 
How can I avoid?

**Comment by raphw** [comment]
Well, this is not really an instrumentation problem, it is a general property of Java, Byte Buddy only copies the code where you want it. What you could do would be to define a static `ThreadLocal<Boolean>` somewhere and wrap your advice code in a *try-catch* block where you only invoke the code if the thread local is not `true` already on entering:

```java
boolean b = Holder.ACTIVE.get();
if (!b) {
  Holder.ACTIVE.set(true);
  try {
    System.out.println("Invoke method " + method);
  } finally {
    Holder.ACTIVE.set(false);
  }
}
```

You just need to make sure that this thread local is accessible everywhere.

**Comment by blackbk** [comment]
> Well, this is not really an instrumentation problem, it is a general property of Java, Byte Buddy only copies the code where you want it. What you could do would be to define a static `ThreadLocal<Boolean>` somewhere and wrap your advice code in a _try-catch_ block where you only invoke the code if the thread local is not `true` already on entering:
> 
> ```java
> boolean b = Holder.ACTIVE.get();
> if (!b) {
>   Holder.ACTIVE.set(true);
>   try {
>     System.out.println("Invoke method " + method);
>   } finally {
>     Holder.ACTIVE.set(false);
>   }
> }
> ```
> 
> You just need to make sure that this thread local is accessible everywhere.

Thank you for your suggest, that's really a helpful idea.
