### ISSUE TITLE
Can byte-buddy advice the interface method?

### ISSUE THREAD

**Issue by lwsbox** [raphw/byte-buddy#982]
```
DemoService demoService = (DemoService)context.getBean("demoService");
String hello = demoService.hello();
```
DemoService is a interface.

I use demoService.getClass() to advice the demoService.hello  method?

Has easy way to advice interface without care which class implements the interface?

Thanks.

**Comment by raphw** [comment]
You can apply advice to all types that implement the interface. Are you using an `AgentBuilder`? In this case, use the `hasSuperType(...)` method.

**Comment by lwsbox** [comment]
Thanks a  lot
