### ISSUE TITLE
getter for Boolean

### ISSUE THREAD

**Issue by dineelbathina** [raphw/byte-buddy#986]
Getter method for Boolean is generating incorrectly. 

**Current output:**

private Boolean test;

public Boolean istest() {
        return this.test;
    }

**expected output:**

private Boolean test;

public Boolean gettest() {
        return this.test;
    }

**Comment by raphw** [comment]
Good point, JAXB uses `is` for wrapper boolean types some time, I likely took it from there. It will be fixed in the next release.
