### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by asasas234** [raphw/byte-buddy#987]
@raphw Please ask a question, I have a class A and B and C, in class A, I enhanced class B by the following code, enhanced code written in class C, class A and B ClassLoader is Spring's LaunchedURLClassLoader, class C ClassLoader is ByteBuddy's ByteArrayClassLoader, when enhanced successfully, I execute class B will lead to NoClassDefFoundError, please ask what solution, such as whether you can specify the class C loader

 new ByteBuddy()
                .redefine(B)
                .visit(Advice.to(C,
                        new ClassFileLocator.Compound(
                                ClassFileLocator.ForClassLoader.of(B.getClassLoader()),
                                ClassFileLocator.Simple.of(C.getName(), bytes))
                ).on((ElementMatchers.named(method).and(ElementMatchers.takesArguments(classes)))))
                .make()
                .load(B.getClassLoader(), classReloadingStrategy);

@Slf4j
public class C {

    @Advice.OnMethodEnter
    public static void enter(
            @Advice.This Object obj,
            @Advice.AllArguments Object[] allArgs,
            @Advice.Origin Method method
    ) {
        log.error("className == {}, methodName == {}, allArgs == {}", obj.getClass().getName(), method.getName(), JSON.toJSONString(allArgs));
    }
}

**Comment by asasas234** [comment]
For example, can the enhanced code change from C.enter(xxx) to Class.forName("xxx",true,CustomerClassLoader).get("enter ").invoke(null,xxx)

**Comment by asasas234** [comment]
@raphw I have solved the problem, no need to answer it

**Comment by xuhuanzy** [comment]
How to solve it?
