### ISSUE TITLE
Bytebuddy advice messes up debugging in eclipse

### ISSUE THREAD

**Issue by laurit** [raphw/byte-buddy#989]
Debugging classes that have been instrumented doesn't work correctly in eclipse, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1926
I was able to reproduce this by running AdviceEnterValueTest#testVariableMappingAdviceLarger() with a breakpoint in Sample#bar(). I have worked on the same issue before while doing instrumentation with asm so I'll try to give you some insight which might be wrong because I didn't verify it. Eclipse debugger probably calls StackFrame#thisObject from jdi api which assumes that this is in slot 0, but as bytebuddy remaps this to a different slot it fails to find this and throws an exception. The way I solved it was to realign validity region for this and method arguments to cover the whole method after instrumentation. While keeping this at slot 0 will probably solve eclipse breaking completely it might also be a good idea to apply the same logic on method arguments as when method breakpoints are used the ide will show only the variables that are active from the very start of the method. When testing method breakpoints it might help when you make eclipse compile without line numbers because eclipse cheats with method entry breakpoint and places it on the first line of the method instead of using an actual method breakpoint, nowadays I believe intellij also employs the same trick (should be controlled by emulated checkbox in breakpoint view).

**Comment by raphw** [comment]
Yes, this is very much on purpose. Some programming languages and obfuscators throw around the variables of the method, therefore Byte Buddy creates a copy by default and lets the method run on the copy, to retain the original state for any exit advice. Debuggers could pick this up if they were nifty, to bad Eclipse cannot map it.

It can be disable din advice by setting `OnMethodExit(backupArguments = false)` but this will break compatibility for some JVM languages and when obfuscators are used.

**Comment by raphw** [comment]
I'm closing this issue, please get in touch if you have any further questions.
