### ISSUE TITLE
[Question]Can i modify final class

### ISSUE THREAD

**Issue by yuhang-liu01** [raphw/byte-buddy#993]
final class A {
}

I can not modify class A in following way: 

DynamicType.Unloaded<?> dynamicType = new ByteBuddy()
                .subclass(A.class)
                .field(ElementMatchers.named("PROPERTIES_PATH_NAME"))
                .value("new path")
                .make();

absolutely,it will throw exception: java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types

**Comment by raphw** [comment]
The JVM prohibits this. If you wanted to subclass `A`, you'd need to redefine it to not be final. This must be done before it is loaded for the first time, typically by defining a Java agent.

**Comment by yuhang-liu01** [comment]
> The JVM prohibits this. If you wanted to subclass `A`, you'd need to redefine it to not be final. This must be done before it is loaded for the first time, typically by defining a Java agent.

Actually I use java agent to do this.In the process,I need a new class to work with `addTransformer` which Instrumentation's method,but it seems that byte-buddy can't modify the final class `A`.Now I use the ASM to achieve this, looking forward to this ability in byte-buddy.

**Comment by raphw** [comment]
You can do so, simply set the modifier `TypeManifestation.PLAIN`.
