### ISSUE TITLE
How to determine if a Class can be redefine

### ISSUE THREAD

**Issue by asasas234** [raphw/byte-buddy#994]
@raphw hi,Please ask a question, is there a lightweight API that allows me to determine if a Class can be redefine

**Comment by raphw** [comment]
Sure, `Instrumentation` has one. Other then that, you must typically restrict Byte Buddy to not change the class file format's shape. You can do so by setting `.disableClassFormatChanges()`.

**Comment by asasas234** [comment]
@raphw isModifiableClass ？I tried to call this method, but I still can't completely filter the classes that may fail to be enhanced, for example, if the class has been enhanced before

**Comment by raphw** [comment]
What do you mean by 'fail'? If a class has been enhanced before, it can still be reenhanced. If you try to create a repeatable enhancement, it likely fails because of a format-changing retransformation.

**Comment by asasas234** [comment]
@raphw Let me tell you another situation, for example, some classes are generated at runtime, when I use ByteBuddy to enhance these classes, it will report an error in the ClassFileLocator.ForClassLoader.read method, because it is generated at runtime, so it is normal that it cannot be found from the disk, I know ByteBuddy can pass in ClassFileLocator I specified to solve this problem, but I was trying to filter the classes. Because what I'm doing is a tool that lets the user select classes and methods in the interface to do bytecode enhancement, but I don't want the user to select classes where the enhancement might fail.

**Comment by asasas234** [comment]
@raphw At the moment I'm doing it in a stupid way, using class names to match keywords to filter, so I'd like to ask you if there is a better way

**Comment by asasas234** [comment]
> If you try to create a repeatable enhancement, it likely fails because of a format-changing retransformation

Yes, it is the first change in the structure of the class, resulting in the failure of the 2nd enhancement, but the first enhancement, I did not do, at present I am able to determine by the enhanced class, whether an additional interface to determine, but this can only filter out the results of the first enhancement of a particular framework, and can not filter other similar cases.

**Comment by raphw** [comment]
Well, matching by name is the most efficient method since it does not even require to parse the byte code. Otherwise, the agent normally has the byte code presented, even for generated classes. If you mark your generated classes for example as synthetic and exclude classes by that criteria, this is also often efficient, despite the naming convention not being beatable.

**Comment by asasas234** [comment]
> Well, matching by name is the most efficient method since it does not even require to parse the byte code. Otherwise, the agent normally has the byte code presented, even for generated classes. If you mark your generated classes for example as synthetic and exclude classes by that criteria, this is also often efficient, despite the naming convention not being beatable.

Okay, I see, I thought there was a lightweight API that could determine all such special cases, but it seems there isn't, thanks!
