### ISSUE TITLE
Unable to use MethodDelegation or Advice redefine class.

### ISSUE THREAD

**Issue by Astronaut-K** [raphw/byte-buddy#996]
byte-buddy version:1.10.18
java version: 1.8

Here is my demo:

```
public class Hello {
    public void hello(String a) {
        System.out.println("Hello: " + a);
    }
}
```

```
public class HelloInterceptor {
    @RuntimeType
    public static String hello(@AllArguments Object[] args,
                             @SuperCall Callable<String> callable) {
        System.out.println("args: " + Arrays.toString(args));
        try {
            return callable.call();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
}
```

```
public class HelloAdvice {
    @Advice.OnMethodExit
    public static void onExit(@Advice.AllArguments Object[]args) {
        System.out.println("args: "+ Arrays.toString(args));
    }
}
```

```
public class HelloMain {
    public static void main(String[] args) {
        ByteBuddyAgent.install();
        new ByteBuddy()
                .redefine(Hello.class)
                .method(ElementMatchers.named("hello"))
//                .intercept(Advice.to(HelloAdvice.class))
                .intercept(MethodDelegation.to(HelloInterceptor.class))
                .make()
                .load(Thread.currentThread().getContextClassLoader(), ClassReloadingStrategy.fromInstalledAgent());

        Hello hello = new Hello();
        hello.hello("Tom");
    }
}
```

When I use Advice `.intercept(Advice.to(HelloAdvice.class))` to intercept method "hello", app throw exception [_**Cannot call super (or default) method for public void xx.Hello.hello(java.lang.String)**_].

When I use MethodDelegation `.intercept(MethodDelegation.to(HelloInterceptor.class))` to intercept method "hello", app throw exception [_**None of [public static java.lang.String xx.HelloInterceptor.hello(java.lang.Object[],java.util.concurrent.Callable)] allows for delegation from public void xx.Hello.hello(java.lang.String)**_]

I don't know which code or set up is wrong in my code.
Thanks.

**Comment by raphw** [comment]
With the delegation, you would need to `rebase` rather then `redefine`. When redefining, by using an instrumentation (via `.method(...).intercept(...)`, you replace the method. With a rebasing, you retain it. When replacing it, Byte Buddy complains that there is no super method left to be called.

Advice is not an instrumentation but a decoration, therefore it works. You can use Advice both as decoration and instrumentation, delegation only as an instrumentation.
