### ISSUE TITLE
Can we invoke a method which does not get executed in threads

### ISSUE THREAD

**Issue by maneeshbhunwal123** [raphw/byte-buddy#997]
Lets say there is a method 
```
public int getSize() {
return 3;
}
```
No other method calls this method in the java code, Hence i can not intercept the method and capture the return value. 

From my java agent i want to execute getSize() method. What are the ways to do this?

**Comment by raphw** [comment]
Are you using the `AgentBuilder` API? Intercept the declaring type and direct it to the method, there should not be any restriction.

**Comment by maneeshbhunwal123** [comment]
i am doing 
```
agentBuilder = agentBuilder.type(isSubTypeOf(Object.class)).transform((builder, type, classLoader, module) -> {
                return builder.method(ElementMatchers.any().and(isAnnotatedWith(named("com.codahale.metrics.annotation.Gauge"))))
                        .intercept(MethodDelegation.to(new InstrumentationInterceptor()));
```

but intercept will be invoked only when getSize() is called from some other method right? 
I want to invoke a method without it being called from any in my java code.

**Comment by raphw** [comment]
Not sure what you mean by that. Byte Buddy only transforms byte code; you'd need to invoke it somewhere.

**Comment by maneeshbhunwal123** [comment]
thanks for confirming.
