### ISSUE TITLE
Let build plugins auto-detect transformations

### ISSUE THREAD

**Issue by odrotbohm** [raphw/byte-buddy#998]
I am not sure whether I am the odd one out here but enabling a transformation on the build plugin seems unnecessarily verbose assuming that the plugin's dependencies contain transformations and*all* of those are supposed to be applied. Here's what a declaration currently looks like:

```xml
<plugin>
  <groupId>net.bytebuddy</groupId>
  <artifactId>byte-buddy-maven-plugin</artifactId>
  <version>${bytebuddy.version}</version>
  <executions>
    <execution>
      <goals>
        <goal>transform</goal>
      </goals>
    </execution>
  </executions>
  <dependencies>
    <dependency>
      <groupId>org.jmolecules</groupId>
      <artifactId>jmolecules-jpa-plugin</artifactId>
      <version>${jmolecules.version}</version>
    </dependency>
  </dependencies>
  <configuration>
    <transformations>
      <transformation>
        <plugin>org.jmolecules.jpa.plugin.JMoleculesJpaPlugin</plugin>
      </transformation>
    </transformations>
  </configuration>
</plugin>
```

The entire `<transformations />` block seems redundant. Does it make sense, to e.g. scan the plugin's dependencies for a properties file (`META-INF/bytebuddy.properties`?) for transformations to apply *unless* a `<transformation />` element is available?

**Comment by raphw** [comment]
That's a good point. I will add something like it. The plugin API was originally designed to be a supplement to writing Java agents but it makes sense to define plugin-oriented jars where classes are loaded from the jar file itself.

**Comment by raphw** [comment]
Added to master with file */META-INF/net.bytebuddy/build.plugins*

**Comment by odrotbohm** [comment]
Do you think we can also make this work for `Plugin.Factory` implementations as well? I am trying to calculate which plugins to apply based on the classpath of the project the plugin is applied that and `Plugin.Factory` would allow me to do that and return `NoOp` instead of the actual plugin instance if the required APIs are not available on the classpath.

I am pretty sure `Class.forName(…)` is a pretty weird way of trying this. Some API handed into `Factory.make()` that would allow to inspect the classpath applying to the current goal's scope (`transform` using the compile classpath VS `test-transform`using the test classpath) would be helpful. Happy to open another ticket, if you think that's an idea worth pursuing.

**Comment by odrotbohm** [comment]
`ClassFileLocator` seems to be what I am looking for. I've come to a solution based on `Plugin` solely, registering a shell plugin that matches all types until the first invocation of `apply(…)` uses the `CFL` handed into that and shortcutting further invocations should the class lookup fail for this.

An overload `Plugin.Factory.make(ClassFileLocator)` (with a default implementation delegating to the parameterless version) plus the ability to list factories in the config file would help creating a less involved arrangement.

**Comment by raphw** [comment]
I see the use case, I will look into it. I am wondering: did you look into the `WithPreprocessor` subclass which allows to iterate through all classes (including their class file locator) prior to class processing? Maybe this covers your case? The idea is that plugins can be stateful to begin with, so you could move the decision to the `onPreprocess` method?

The idea of not providing it in a constructor was that class location is something class context dependent, especially in module context such that the class file locator is provided on a 'by class' basis.

**Comment by odrotbohm** [comment]
That helps a lot. I now check type presence per `TypeDescription` as suggested and also immediately apply `matches(…)` to create an optimized plugin chain per `TypeDescription`.

That said, I think that completely removes my need to declare plugin factories in the configuration file. Looking forward to the release!

**Comment by odrotbohm** [comment]
Looks like the discovery is not yet working as `ByteBuddyMojo.execute()` checks for `transformations` to be `null` or empty to immediately return. The auto-discovery seems to be implemented to take place at a later stage. If I skip the check if `discover` is enabled, I still need to fix the initialization of the transformations on discovery. Also, the attempted lookup of the configuration file doesn't seem to "see" the plugin JARs. I.e. it never finds any configuration file.

**Comment by raphw** [comment]
I fixed the first issue but I have not run a full test yet. I will try to resolve this over the weekend.

**Comment by raphw** [comment]
I did some end to end testing and think that I resolved the remaining issues. Can you give it another spin?

**Comment by odrotbohm** [comment]
Auto-discovery seems to work now. That said, playing with this I ran into a corner case:

1. Auto discovery kicking in executing my plugin which adds annotation A due to the presence of annotation B. The plugin checks for whether A is already present on the type and skips the addition if so.
2. An outdated manual declaration of the plugin in the `<transformations />` section of the plugin configuration, causing the plugin to run again and thus the annotation being added twice.

Does it make sense to disable the discovery if explicit transformations are configured or generally make sure no duplicate plugin executions are created when collecting them?

**Comment by raphw** [comment]
Yes, that makes sense. I like the notion of this: You can configure an auto configuration with a default setting but for changing the plugin's behavior, you set it up yourself. In the course of it, I also disabled that the same plugin can be discovered twice.

**Comment by raphw** [comment]
Implemented on master.

**Comment by odrotbohm** [comment]
I just tried 1.10.12 and it looks like the auto-discovery is still triggered even if explicit transformations are declared? Any chance that particular change hasn't made it into the release?

**Comment by raphw** [comment]
Should not have happened, no. You are using 1.10.20? 12 won't work.

**Comment by odrotbohm** [comment]
I mistyped originally. I mean 1.10.20. I'll try to come up with a reproducer.

**Comment by raphw** [comment]
I tried it out, but I assume my example was too simple. If it's broken, I'll fix it.

**Comment by odrotbohm** [comment]
Looks 'm running into a corner case here. I have three plugins in a JAR: X, Y and Z with Z delegating to both X and Y depending on the classpath setup. I have explicit declarations for X and Y and would've expected the first explicit declaration to turn off the auto-discovery entirely. The discovery in 1.10.20 now adds Z to the overall picture, so that X and Y get applied twice.

I can work around this problem explicitly setting `discover` to false. Not sure whether others should be surprised by this "discover despite explicit declarations" or whether it's just fine. I guess you're right: without that very special delegation behavior, the problem probably wouldn't exist.

**Comment by raphw** [comment]
I see, you'd expect that auto discovery only activates on a plugin declaration?

While I see the argument, I thibk the suggested behaviour would make composition of several plugins more difficult, if they are unrelated. Some plugins might just always be auto-discovered.

**Comment by odrotbohm** [comment]
What just strikes me as little odd is that explicitly listing transformations doesn't have the limiting effect, *unless* I also declare `<discover>false</discover>`. If my plugin JAR declares plugins A and B and registers both for auto-detection, the two will be found if none are declared as transformations at all, but *also* if one of the two is declared explicitly. I kind of would expected that as soon as at least one transformation is declared, auto-detection is implicitly disabled. I.e. don't list transformations at all -> auto-discovery. If you list explicitly, you *only* get the ones listed.

I don't think we have to overthink this. Whenever someone else thinks the current arrangement is counter intuitive, they either find this discussion or file a ticket and you can rethink.

**Comment by raphw** [comment]
You are right, this is not great default behavior but I am more concerned about the following case:

I add dependencies from project X and Y where X uses auto-discovery but Y does not and requires an explicit setup. X does not consider that a plugin would need explicit configuration and just explains how Byte Buddy is to be set up. But after adding Y, you suddenly need to.

By setting `<discover>false</discover>`, the behavior can still be enabled when desired, but this way I hope that most cases are solved without surprise. I expect most dependencies to contain one independent plugin, this way they can be composed fairly simply.

**Comment by odrotbohm** [comment]
I see. Coming from a "transformations have to be declared explicitly" state of affairs pre-1.10.20, all currently existing configurations will have transformations configured explicitly. I would then think that it's fine that you can only move to auto-discovery if *all* plugin JARs support that.

Another reason I think that'd be the better approach is that with the current one, it's possible to sneak an additional plugin into the setup by declaring it in the plugin JAR, ship an update, the user upgrading and despite the explicit declarations, it'll be picked up, potentially without the user noticing.

I.e. I though, removing the transformations and relying on auto-detection is me handing over trust to the plugin JAR author. Explicitly declaring a transformation declaring "I want to explicitly control the setup".

**Comment by raphw** [comment]
Yeah, you are right. Maybe I should switch it, to make discovery despite transformations being declared an opt-in. Unfortunate that I shipped that version in the current state, but fortunately, by renaming I can break builds what allows people to lookup and correct their setup. I will look into it!
