### ISSUE TITLE
Allow multiple methods with the same name only differing in their return value

### ISSUE THREAD

**Issue by Gleyder42** [raphw/byte-buddy#999]
Normally, in Java you can define multiple methods with the same name, but different type parameters, which is called
overloading. Defining two methods with same name only differing in their return value is forbidded. This makes sense, because the compiler couldn't tell if you want to call `int get()` or `long get()`.

However, the JVM itself supports these kinds of method overloading. This can be read here:
https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Resolving-Method-Signature-Conflicts

> The method getID() in the parent class, and the getID() method we are trying to define differ only on return type. This type of overload is not supported by Java and the compiler will raise an error when we try to compile our mixin:

> However, there is a silver lining hidden in the engine which powers Java, the Java Virtual Machine (JVM): the JVM itself does support this kind of overload, it is only the Java language which does not. This means that if we can somehow convince the compiler to compile our code, then the actual class will work just fine.

Assuming we create two methods.
```java
public class Overloading {

  public static void main(String[] args)
      throws NoSuchMethodException, IllegalAccessException, InvocationTargetException, InstantiationException {
    DynamicType.Builder<Object> subclass = new ByteBuddy().subclass(Object.class)
        .implement(IntGet.class)
        .withoutCode()
        .implement(LongGet.class)
        .withoutCode();

    subclass = subclass
        .defineMethod("get", long.class, Modifier.PUBLIC)
        .intercept(FixedValue.value(100L));

    subclass = subclass
        .defineMethod("get", int.class, Modifier.PUBLIC)
        .intercept(FixedValue.value(10));

    Class<?> loaded = subclass
        .make()
        .load(Overloading.class.getClassLoader())
        .getLoaded();

    for (final Method method : loaded.getMethods()) {
      System.out.println(method);
    }

    Object o = loaded.getConstructor().newInstance();

    try {
      // To access the int get()
      IntGet intGet = (IntGet) o;
      System.out.println(intGet.get());
    } catch (AbstractMethodError error) {

    }

    // To access the long get()
    LongGet longGet = (LongGet) o;
    System.out.println(longGet.get());
  }

  public interface IntGet {

    int get();
  }

  public interface LongGet {

    long get();
  }
}
```
Only one `get()` method is defined. 
The JVM can handle this, but ByteBuddy replaces the previous defined method with the latest.

To access the explicit method, we can use interfaces. 

Depending in what order the methods are defined, the first or second `get()` call will fail with an `AbstractMethodError`.
ByteBuddy actually implements both methods as abstract methods, but only one will receive a method body.

**Comment by raphw** [comment]
I think that's because of the bridging, can you try registering a `MethodGraph.Compiler.Default.forJVMHierarchy()` in `ByteBuddy`?

This should solve the problem.

**Comment by Gleyder42** [comment]
This works. Thank you
